### ISSUE TITLE
About the Editable pdf Format

### ISSUE THREAD

**Issue by lester1027** [jgraph/drawio-desktop#1001]
Hi, I would like to know if the diagrams will lose some properies when I only keep the pdf versions of them.

Thank you.

**Comment by jclambert** [comment]
At a base level with any vector-based application, you are moving it from a vector/image format to just an image PDF.  The remaining features will be whatever you can do with a PDF document

**Comment by lester1027** [comment]
Currently, we can "include a copy of the diagram" in drawio when we export the diagram in the pdf format. In that way, after exporting, we can still use drawio to open the pdf file and edit it. What I would like to know is, if we save and edit the drawio diagrams in pdf format, we will lose some functionality of the original diagram or not.

**Comment by lester1027** [comment]
@davidjgraph Could you please provide me with some insights about this question? Thank you.

**Comment by davidjgraph** [comment]
Why are you singling me out to answer it?
