### ISSUE TITLE
Backup draft file not hidden

### ISSUE THREAD

**Issue by szmabcd** [jgraph/drawio-desktop#1002]
A file like this exists on every save

![Snipaste_2022-05-17_09-39-56](https://user-images.githubusercontent.com/38176269/168710495-89a1c451-1518-469d-9eb6-5f2e2592a0ee.png)

**Comment by davidjgraph** [comment]
What version are you using?

**Comment by szmabcd** [comment]
18.0.2 and 18.0.6-windows-no-installer.exe have this problem

**Comment by davidjgraph** [comment]
And the file isn't hidden? Do you have hidden files shown in whatever you are using to list files in that directory?

**Comment by szmabcd** [comment]
yes,not hidden

**Comment by m-mohamedin** [comment]
We've added an option to disable the creation of backup files
![Screen Shot 2022-05-31 at 7 17 40 PM](https://user-images.githubusercontent.com/24944765/171299046-d85f7954-4ec9-4a9a-b997-4a3a10ede5b8.png)

**Comment by J-keaper** [comment]
@m-mohamedin 
Hello, can the "Auto Backup" option be persistent?
This option was reset when I closed the drawio-desktop application and restarted the application.

**Comment by m-mohamedin** [comment]
> @m-mohamedin Hello, can the "Auto Backup" option be persistent? This option was reset when I closed the drawio-desktop application and restarted the application.

Please share with us the environment (OS, version, ...) as we couldn't reproduce

**Comment by J-keaper** [comment]
> > @m-mohamedin Hello, can the "Auto Backup" option be persistent? This option was reset when I closed the drawio-desktop application and restarted the application.
> 
> Please share with us the environment (OS, version, ...) as we couldn't reproduce

OS: MacOS 10.15.6
drawio-desktop version: 20.2.3
I tried it a few times and found that if I just closed the application window, this option would reset, but if I quit the app completely, this option would persist.

**Comment by davidjgraph** [comment]
@J-keaper please create a new issue, this isn't the same issue as the original.

**Comment by J-keaper** [comment]
> @J-keaper please create a new issue, this isn't the same issue as the original.

Ok. I've already created it.  #1114
