### ISSUE TITLE
Window disappears after double-clicking on title bar

### ISSUE THREAD

**Issue by wxlie** [jgraph/drawio-desktop#1007]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Window disappeared after double-clicking on title bar.

**To Reproduce**
Issue persists even after: -
- force quit and relaunching
- opening various draw.io projects
- rebooting in safe mode
- changing resolution on displays
- using a single display, both native and external
- moving draw.io.app to trash and reinstalling
- moving 18.0.6 to trash and install 18.0.4

**Expected behavior**
Expected to maximise window when double-clicking

**Screenshots**
Only a blue outline of the window appears when using the Show All Windows option
<img width="187" alt="image" src="https://user-images.githubusercontent.com/17251844/169177415-484578b8-d7de-4822-8714-7a68009e3a37.png">
![IMG_9596](https://user-images.githubusercontent.com/17251844/169177765-d6a83ec9-cb57-4605-bef8-8919ba3f0f0a.jpg)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 18.0.6

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1

**Additional context**

**Comment by kaverne** [comment]
Same issue with the following details.
MacOS 11.4 (Big Sur)
MacBook Air (M1, 2020)

**Comment by saifsabir97** [comment]
Same issue with the following details.
MacOS 12.3.1 (Monterrey)
MacBook Air (M1, 2020)

**Comment by camoore1979** [comment]
Same issue with the following details.
MacOS 12.2
MacBook Pro (2019)

**Comment by saifsabir97** [comment]
As a workaround, I removed the app and installed again with 17.4.2 release. I did not verify if this issue happens for a later version but it definitely didn't work for the current latest.

**Comment by davidjgraph** [comment]
Could everyone edit their comments to include which dmg they installed please?

**Comment by nexusgoblin** [comment]
It seems to trigger when resizing with the window gadgets on occasion.  Workaround is to quit and remove `lastWinSize` from the configuration; this attribute seems to get set to `"1,29"` and... the app is then broken. 

The file `~/Library/Application Support/draw.io/config.json` contains something like:
```
{
	"lastWinSize": "1,29"
}
```

Quit draw.io if it is running and remove that attribute (and any comma separating it from any other attributes in the JSON) from the config.json file and restart.

For example, if your config.json looks like:
```
{
	"dontCheckUpdates": false,
	"lastWinSize": "1,29"
}
```
change it to be:
```
{
	"dontCheckUpdates": false
}
```
and restart.

Hopefully that helps.

**Comment by m-mohamedin** [comment]
Thanks for the report (special thanks for @nexusgoblin for finding the reason)

Problem will be fixed in the next release
