### ISSUE TITLE
Custom URL protocol

### ISSUE THREAD

**Issue by IllugiSvensson** [jgraph/drawio-desktop#1009]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I use my own httpn protocol in my schemes, which allows you to open applications from a browser. The "scheme - protocol - application" connection has been working for a year, but on May 16-17, 2022, drawio stopped supporting httpn url (similar protocols http, https continue to work).

**To Reproduce**
1. In the desktop version, in edit mode, click on the element
2. Edit link alt+shift+l
3. Write url httpn://VNC default (at this moment everything works in edit mode)
4. Export schema to html
5. In the html file, click on the element
6. See that the link is not working (worked until May 17, 2022)

**Expected behavior**
After clicking on an element with a custom protocol, the corresponding protocol should be called and handle the link. The rules for the operation of the protocol are written in the registry for Windows and in x-mime-schema for Linux

**Screenshots**
Desktop editor
![image](https://user-images.githubusercontent.com/49456695/169277195-44c1e080-4ec5-4452-a650-98264dfc4382.png)
Web editor
![image](https://user-images.githubusercontent.com/49456695/169277335-f1cf4f5a-e74b-493e-8966-7718e75e741e.png)
after schema export, link is broken in both cases

**draw.io version (In the Help->About menu of the draw.io editor):**
i tried several desktop versions and browser version 18.0.6

**Desktop (please complete the following information):**
 - OS: Windows10, Oracle Linux 7.6, 8.4

**Additional context**

**Comment by davidjgraph** [comment]
So, this was removed after a security review, protocols were restricted to http(s). Right now, I have no idea what httpn is, so we can't put it back. If there is a good resource to learning what it is, I'll look (bonus points for security implications).

**Comment by IllugiSvensson** [comment]
> So, this was removed after a security review, protocols were restricted to http(s). Right now, I have no idea what httpn is, so we can't put it back. If there is a good resource to learning what it is, I'll look (bonus points for security implications).

this is my personal development that allows my colleagues to remotely connect to office computers from the diagram (click on the computer on the diagram and the VNC / PuTTY window opens). I can show the source of this program.

**Comment by dsiJPee** [comment]
Hi,
We're using the same feature to automate RDP, SSH connexion from our architectcture diagram,
the custom protocol we have defined is apphttp,
would it be possible to add an option allowing custom protocol (like a checkbox in diagram properties) ? (thus leaving the choice to the user whether to strictly stick to http/https or not).
kind regards

**Comment by davidjgraph** [comment]
We'll add a method to set the regex used in the link sanitizer in a future build. Note, you will need to run your own build for this, we don't want this in app.diagrams.net as we don't want to be responsible for the security surface it creates.

**Comment by davidjgraph** [comment]
We've added:

`window.DOM_PURIFY_CONFIG`

in 18.1.1. Adjust the regex for your specific needs. The current value is:

```
window.DOM_PURIFY_CONFIG = window.DOM_PURIFY_CONFIG ||
    {ADD_TAGS: ['use'], ADD_ATTR: ['target'], FORBID_TAGS: ['form'],
    ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto|tel|callto|data):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i};
```

See the [DOM Purify](https://github.com/cure53/DOMPurify) docs for more details.

**Comment by dan31** [comment]
> We've added:
> 
> `window.DOM_PURIFY_CONFIG`
> 
> in 18.1.1. Adjust the regex for your specific needs. The current value is:
> 
> ```
> window.DOM_PURIFY_CONFIG = window.DOM_PURIFY_CONFIG ||
>     {ADD_TAGS: ['use'], ADD_ATTR: ['target'], FORBID_TAGS: ['form'],
>     ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto|tel|callto|data):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i};
> ```
> 
> See the [DOM Purify](https://github.com/cure53/DOMPurify) docs for more details.

How do I modify `DOM_PURIFY_CONFIG` in draw.io desktop app? Thx.
