### ISSUE TITLE
Doesn't launch if draw.io is blocked

### ISSUE THREAD

**Issue by lbruun** [jgraph/drawio-desktop#101]
The application cannot be launched if you are on a network which blocks access to draw.io.

This is ironic as this may be the exact reason why you would be using the drawio-desktop in the first place, as opposed to the online version.

The problem is that on corporate networks the URL draw.io is often blocked as it is on security vendor's list  of URLs to block (risk of data leakage).

So why can't drawio-desktop be started if the "draw.io" URL is blocked?  

@Developers:  Not so easy to replicate: You need to find a mode so that Internet as such is available but the "draw.io" site is not.  Perhaps fiddle with your local hosts file can be a way to replicate the issue?

Ref:  #80, #86    (but these are not mentioning the fact that you cannot launch the application, it is phrased in such way so it sounds like an inconvenience, not a show-stopper)

**Comment by davidjgraph** [comment]
We have a fix for this in the next release.

**Comment by davidjgraph** [comment]
Fixed in 10.7.5 https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5
