### ISSUE TITLE
Dark Mode VSDX Created Files Shape and Arrow Vectors Disconnected in Web Visio

### ISSUE THREAD

**Issue by megamorphg** [jgraph/drawio-desktop#1010]
### Preflight Checklist

* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
VSDX (Visio) files generated from Draw.Io using the Dark theme, when opened in Microsoft Visio on the web, have issues with the shapes and arrows being disconnected and discolored.

**To Reproduce**
1. Set theme to dark
2. Add two boxes connected via an arrow manually
3. File > Export As > VSDX (beta)
4. Open VSDX file in Visio on the Web and go to Edit Mode
5. Observe issues with shapes and arrows by moving around shape

**Expected behavior**
Shapes and arrows should be free of defect when doing VSDX export in dark mode

**Screenshots**
![image](https://user-images.githubusercontent.com/1782353/169295590-38697bcf-d255-4c60-8166-e3965455c4b1.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 18.0.6

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
I am opening the VSDX file in web version of Sharepoint.

**Comment by davidjgraph** [comment]
Did you check whether the same issue exists outside of dark mode?

**Comment by megamorphg** [comment]
@davidjgraph yes, the issue only exists with dark mode enabled.

**Comment by megamorphg** [comment]
This is important for switching between drawio and visio on the web.

**Comment by davidjgraph** [comment]
First of all, we would like to express our gratitude for your time and effort in posting, your contribution to improving the project is much appreciated.

We have noticed that it has attracted very few or no votes from the community. As our development team needs to prioritize tasks that are in higher demand and directly impact the core functionality of the project, we have decided not to address this specific issue at the moment.

Please understand that this decision does not in any way devalue your suggestion. We truly appreciate your input and encourage you to continue sharing your ideas and feedback with us in the future. Our project thrives on the contributions of its users, and we will keep evaluating all issues to make sure we address the most pressing needs.

Once again, thank you for your understanding and your contribution to the project.
