### ISSUE TITLE
IPC comms slow and sync

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio-desktop#1014]
Autosaving large files on desktop causes the UI to become unavailable for periods due to the speed of transferring the data between the two processes.

Investigating replacing file drafts with indexeddb.

**Comment by ClosetMonkey** [comment]
Another option would be to use a delta of the canvas state and only change/save the difference.

**Comment by ClosetMonkey** [comment]
This strategy would also work if ever wanted to make a version of Draw,io for groups.

**Comment by ClosetMonkey** [comment]
Than provide the service on the cloud for paid members and make a million bucks. Your welcome.
