### ISSUE TITLE
Pull in latest drawio release and release new version of drawio-desktop

### ISSUE THREAD

**Issue by matt-linn-ves** [jgraph/drawio-desktop#1016]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
The drawio module has been updated to 18.1.2 as of yesterday. Many of the updates after 18.0.6 were to resolve security issues.

**Describe the solution you'd like**
I would like a new release of drawio-desktop that has the latest release of the drawio git submodule

**Describe alternatives you've considered**
Forking and updating the code manually.

**Additional context**
None

**Comment by davidjgraph** [comment]
The security issues were server-side, they don't affect the desktop build.
