### ISSUE TITLE
Error message "Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded." when open a file using desktop version of draw.io

### ISSUE THREAD

**Issue by rabbitsweet** [jgraph/drawio-desktop#1020]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
- When I tried to open the attached file, an error message "_Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded._" appeared.  The file cannot be opened.

[draw.io file.zip](https://github.com/jgraph/drawio-desktop/files/8792635/draw.io.file.zip)

**To Reproduce**
1. Go to 'draw.io' desktop version
2. Click on 'open the file'
3. See error

**Expected behavior**
- Expected to open the file

**Screenshots**

![Error message](https://user-images.githubusercontent.com/106460748/170852564-b82446a6-9cf0-4211-8c3d-ff82f3be8518.jpg)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 18.1.3

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
- It would be much appreciated if the file can be fixed.  Thank you.

**Comment by davidjgraph** [comment]
What is the encoding of the file in this zip?

**Comment by rabbitsweet** [comment]
No ideas.  I just saved the file in "draw.io" as usual.  When I tried to open it the next day, I cannot open it and this error message pop up.

**Comment by davidjgraph** [comment]
Could you send the file, not zipped, to support@diagrams.net please, and link this issue. Without knowing the file encoding I can't unzip it.

**Comment by rabbitsweet** [comment]
The drawio file sent to [support@diagrams.net](mailto:support@diagrams.net) already.  Thank you.

**Comment by msounkere** [comment]
> Could you send the file, not zipped, to [support@diagrams.net](mailto:support@diagrams.net) please, and link this issue. Without knowing the file encoding I can't unzip it.

I just had the same problem, there would be an explanation, how to recover the file.

**Comment by davidjgraph** [comment]
The most likely explaination is what you are trying to load is not a drawio data file. If you open the file in a text editor, what does the start of the file look like?

**Comment by msounkere** [comment]
> The most likely explaination is what you are trying to load is not a drawio data file. If you open the file in a text editor, what does the start of the file look like?

Noooo, sure it's a drawfile, have a look on it 
https://share.veone.net/s/rMpST6qLsKae3g9

**Comment by davidjgraph** [comment]
That file is cut off, but you didn't use app.diagrams.net to create this file, this is a different thread to the original one.

**Comment by msounkere** [comment]
> That file is cut off, but you didn't use app.diagrams.net to create this file, this is a different thread to the original one.

We use diagrams through the nextcloud plug-ins but it's still based on app.diagrams.net. please could you help us to recover the file or there is no possibility.

**Comment by davidjgraph** [comment]
No, this file is cut off. It looks like the nextcloud integration doesn't check that a file is complete.
