### ISSUE TITLE
Config file documentation

### ISSUE THREAD

**Issue by holzkohlengrill** [jgraph/drawio-desktop#1021]
The configuration under Extras in the editor is great but I am missing some documentation for that.

What I can get as information within the application does not seem so work for the config (it seems not all options are supported and the names/member access is different).

So is there a way (or documentation page) to get the config names/parameters from somewhere (ideally from the GUI) that it can be used in the configuration options under Extras in the editor?

**Comment by mararad** [comment]
Does this help? https://www.diagrams.net/doc/faq/configure-diagram-editor

Regards,

**Comment by holzkohlengrill** [comment]
Thanks for the link. That's already something.
What I still cannot find how to get all the current names/options?
Take the line jumps setting for example.

Or is there any option that I can generate a config based on the current settings?

**Comment by holzkohlengrill** [comment]
Did you miss my last comment?

**Comment by holzkohlengrill** [comment]
Bump to keep it active. Still waiting for a response.

**Comment by holzkohlengrill** [comment]
Any answer to my point?

**Comment by alderg** [comment]
Use Edit Style (Ctrl+E) to see the keys and values.

**Comment by holzkohlengrill** [comment]
They are not matching the config file options.

**Comment by alderg** [comment]
The config file options are here: https://www.diagrams.net/doc/faq/configure-diagram-editor

**Comment by holzkohlengrill** [comment]
The thing is only a small fraction is documented there.
The rest is just painful reverse engineering if the config file options.

**Comment by alderg** [comment]
The documentation should be complete. Which specific config option is missing?

**Comment by tiamiceli** [comment]
Examples of questions I am unable to answer based on the (in)"complete" documentation at [https://www.diagrams.net/doc/faq/configure-diagram-editor](https://www.diagrams.net/doc/faq/configure-diagram-editor): 
* How do you set a default line-height?
* What is jettySize?

**Full request**: As a user of draw.io that wants to minimize manual editing of shape styles, text, etc. the "Extras > Configuration" json option is a partial solution. To make a full solution, we want a _full library_ of configuration options (like 'rounded', 'jumpStyle', 'labelBackgroundColor', etc.) for each element (like 'defaultVertexStyle').

For illustration, here's an incomplete one that I have edited based on the example at the end of your page, [https://www.diagrams.net/doc/faq/configure-diagram-editor](https://www.diagrams.net/doc/faq/configure-diagram-editor). I may have mistakes that I don't know about, but this is a bit closer to what we are asking for:
```
"defaultVertexStyle": {
		"edgeStyle": "orthogonalEdgeStyle",
		"rounded": "1",
		"orthogonalLoop": "1",
		"jettySize": "auto",
		"html": "1",
		"fontSize": "20",
		"strokeWidth": "4",
		"strokeColor": "#000000",
		"fillColor": "none",
		"curved": "0",
		"jumpStyle": "gap",
		"labelBackgroundColor": "none"
	},
	"defaultEdgeStyle": {
		"edgeStyle": "orthogonalEdgeStyle",
		"rounded": "1",
		"jettySize": "auto",
		"orthogonalLoop": "1",
		"html": "1",
		"fontSize": "14",
		"strokeWidth": "4",
		"strokeColor": "#000000",
		"fillColor": "none",
		"labelBackgroundColor": "none"
	},
```
