### ISSUE TITLE
Draw.io Desktop in PortableApps.com Format for use on any Windows PC without installing

### ISSUE THREAD

**Issue by JohnTHaller** [jgraph/drawio-desktop#1022]
[X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
[X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Portable use of draw.io on internal drives, external drives, and cloud drives while keeping all settings as it moves around and not leaving file association registry entries behind.

**Describe the solution you'd like**
Easily install and use a portable copy of draw.io in PortableApps.com Format without needing any additional configuration.

**Additional context**
I built it myself for PortableApps.com but did not want to release it without permission. I have a test version built here (copy the link and paste it into a new tab/window): https://download2.portableapps.com/portableapps/_temp/DrawioPortable_18.1.3_Dev_Test_1.paf.exe

We're happy to build and host ourselves at PortableApps.com, build for you to host, have you build and host, etc. Just let me know. Thanks!

**Comment by davidjgraph** [comment]
Hi John, you're welcome to release it, many third-parties release various integrations.

We would just ask you make it clear in the listing that it's not this project that is responsible for the app and point to any support forum if there is one.

**Comment by JohnTHaller** [comment]
Thanks David. I've added the support disclaimer as requested. It's been released here: https://portableapps.com/apps/graphics_pictures/drawio-portable

**Comment by davidjgraph** [comment]
Cool. Could you just remove jgraph as a publisher please?

**Comment by JohnTHaller** [comment]
> Cool. Could you just remove jgraph as a publisher please?

Sure, done. It'll show up in the cache refresh in a few.
