### ISSUE TITLE
draw.io stops responding if a file is opened while 'Save As' dialog is open

### ISSUE THREAD

**Issue by larsch** [jgraph/drawio-desktop#1023]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
draw.io on Windows completely locks up if you attempt to open a file while 'Save As' dialog is open. Only solution is to kill the draw.io process using the Task Manager. Unsaved work is lost.

**To Reproduce**
1. Start a new diagram
2. Click File > Save As
3. Leave the 'Save As' Dialog open
4. Double-click another .drawio file in Windows Explorer

**Expected behavior**
Diagram opens in a new WIndow.

**Screenshots**
![image](https://user-images.githubusercontent.com/15712/171176329-5b5be42c-a06d-4c4c-9a67-d8700f5d24b6.png)

After closing 'Save As' Dialog:

![image](https://user-images.githubusercontent.com/15712/171176659-83f0e375-dbf3-4df9-88a1-4ff2bfb0118e.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 18.1.3

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by davidjgraph** [comment]
Version is 18.1.3?

**Comment by larsch** [comment]
Yes, sorry for typo.
![image](https://user-images.githubusercontent.com/15712/171180452-20b093f9-b903-4487-99cf-eeb600ba34be.png)

**Comment by mararad** [comment]
I managed to reproduce the 1s part on every test but the 2nd part (after "Save as" dialog was closed) the file was displayed correctly in some cases and drawio is not responding in other cases as reported
![Capture1](https://user-images.githubusercontent.com/44292306/171392244-f6c00beb-bd98-405f-8cfe-eb94ef5819b5.JPG)

![Capture2](https://user-images.githubusercontent.com/44292306/171392886-ebcc6291-ffec-4b2c-a14d-4a5bcf4896fa.JPG)

18.1.3 and Win 10 Pro

**Comment by m-mohamedin** [comment]
Thanks for the report.
In the next version, opening new files while the open/save dialog is active will be disabled (no action when a file is opened while a dialog is active). We couldn't find a solution to the problem and this workaround is to protect user data from being lost
