### ISSUE TITLE
Can i save my draw.io file to local gitlab by draw.io-desktop?

### ISSUE THREAD

**Issue by Winelfeng** [jgraph/drawio-desktop#1025]
* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
No you can't and external comms is outside the scope of the project.
