### ISSUE TITLE
mathematical typesetting not converted

### ISSUE THREAD

**Issue by gismo07** [jgraph/drawio-desktop#103]
From one day to another, mathematical typesetting stopped working.
No formulars are getting converted on the desktop version. However, within the browser it is working.

I tried to update to the latest version, but the issue still persists.
Is there any way to see the console output of the desktop verison?

**Comment by davidjgraph** [comment]
What version does help->about show?

**Comment by gismo07** [comment]
v 10.7.3

**Comment by alderg** [comment]
Fixed in 10.7.4. Thanks for the report!
