### ISSUE TITLE
No "Mathematical Typesetting" option in Minimal Theme

### ISSUE THREAD

**Issue by Oeaps** [jgraph/drawio-desktop#1031]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I love the *Minimal* theme indeed, but when it's applied, neither the *Mathematical Typesetting* nor *Spell Checker* option Appear in the menu. So I have to switch to default theme to toggle the options, which is really inconvenient. 

**Describe the solution you'd like**
Add the missing menu items to all themes.

**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by davidjgraph** [comment]
What spell checker option is that?

**Comment by davidjgraph** [comment]
We're not sure about continuing the minimal theme, does the sketch theme work for you?

**Comment by Oeaps** [comment]
> We're not sure about continuing the minimal theme, does the sketch theme work for you?

I tried it, but there are even fewer items in the menu than the *Minimal*. Many options are not provided, such as *Ruler*, *Scrollbars*, *ScratchPad*, etc.

**Comment by davidjgraph** [comment]
Fixed in 19.0.3
