### ISSUE TITLE
vertailAlign does not default on new edges

### ISSUE THREAD

**Issue by megamorphg** [jgraph/drawio-desktop#1032]
### Preflight Checklist

* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

Style parameter "verticalAlign=bottom" does not default on new edges after clicking Set as Default Style on an edge with this set.

**To Reproduce**
1. Create an edge and set Bottom Text parameter aka "verticalAlign=bottom" parameter:
![image](https://user-images.githubusercontent.com/1782353/172198578-2f126562-bd6c-426c-9df7-ac341bbcab11.png)
2. Go to Style tab and click Set as Default Style
3. Create a new edge and observe that the edge does not start with this parameter

**Expected behavior**

In step #3, new edge should already have the default verticalAlign parameter.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 19.0.0

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...
Windows

**Additional context**
This is an important default setting because normally people like to have any text on arrows above the arrow/edge ("verticalAlign=bottom") and not through the edge itself.

**Comment by egrimate** [comment]
Not all style changes are written in the default style. This was a design decision and for some styles it is questionable whether they should go in or not.

**Comment by megamorphg** [comment]
@egrimate it would be nice to have this added to default style.

We can't hard-code it because I checked other systems have the text go through the middle of the arrow (Visio and Lucid Charts for instance) so it would be inconsistent...

However, it makes no sense to me to have text go in the middle of an edge since I draw pretty small arrows.
