### ISSUE TITLE
Line endings broken in Entity Relation Shapes

### ISSUE THREAD

**Issue by hubitor** [jgraph/drawio-desktop#104]
Line endings (i.e. cardinality) are not showing up in the Entity Relation Shapes of the drawio-desktop. Even if the line endings are modified on the right panel, the lines remain unchanged. The online version of drawio doesn't have this issue.

![drawio_ERD_lines](https://user-images.githubusercontent.com/6114541/58828853-aa081580-8646-11e9-8eb0-53518b3880b8.png)
![drawio_ERD_notation](https://user-images.githubusercontent.com/6114541/58828884-bd1ae580-8646-11e9-9f0e-d4e0d7510ed9.png)
![drawio_ERD_notation2](https://user-images.githubusercontent.com/6114541/58828899-c1470300-8646-11e9-8b2a-a6d0f9549a4d.png)

OS: Arch Linux
v. 10.6.8

**Comment by davidjgraph** [comment]
Is this repeatable if you download 10.8.0 manually from https://github.com/jgraph/drawio-desktop/releases, install it and check?

**Comment by hubitor** [comment]
I've installed v10.7.7 and it seems to be fixed. Thanks!
