### ISSUE TITLE
Save to gitlab function, cannot save to private gitlab of LAN

### ISSUE THREAD

**Issue by BraveMomo** [jgraph/drawio-desktop#1040]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

Save to the gitlab function, can not save to the local area network private gitlab, I want to save the production flow chart to my local area network, private gitlab, this warehouse, there is only one url, when I choose to save to gitlab, I can not find such an option, I hope you can provide, this is very important, I can not save the file to the official warehouse of gitlab, our security requirements do not allow

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...

**Additional context**

**Comment by BraveMomo** [comment]
When I modify the storage method and choose to save to gitlab, the software will jump directly to gitlab.com, but my LAN gitlab is not here. For example, my gitlab address is a xxx.xxx.xxx.xx url, so I think that when users choose to save to gitlab, they should provide an option to enter url to see if they want to save to the local area network warehouse.

**Comment by davidjgraph** [comment]
This is outside the scope of the desktop app.
