### ISSUE TITLE
External plugins disabled on diagrams.net 19.0.3

### ISSUE THREAD

**Issue by appa1303** [jgraph/drawio-desktop#1049]
Hello, 

I see that from diagrams.net 19.0.3 desktop on windows external plugins are disabled (see image below)
Is there a way to re-enable external plugins ?

Thank you.

![image](https://user-images.githubusercontent.com/12508835/174484698-d5492184-3de7-40ef-a413-0031744de455.png)

**Comment by appa1303** [comment]
when running from command line I could see the message:
>Plugins now disabled by default. Use --enable-plugins on command line to enable.

**Comment by gytisrepecka** [comment]
On macOS it works like this:

```
open -a /Applications/draw.io.app --args --enable-plugins
```

**Comment by zhangjx007** [comment]
> 

 How to operate in windows.thank you!

**Comment by rikrdo89** [comment]
create a shortcut to the exe file, and in the target box, add ` --enable-plugins` as show below:
![image](https://user-images.githubusercontent.com/24930604/224192141-b522b1f1-aa46-46b1-b17b-3d709480158f.png)

**Comment by YNG2020** [comment]
Thanks, it works in my win11 system!

**Comment by felixvd** [comment]
To enable for drawio installed via Snap on Linux: https://askubuntu.com/questions/1026378/how-do-i-add-start-parameter-to-a-program-installed-via-snap
