### ISSUE TITLE
Problem printing white text on dark background - text prints grey

### ISSUE THREAD

**Issue by skoer** [jgraph/drawio-desktop#1050]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
White text on dark box appears as expected on the screen, but doesn't print the same way either using a printer or pdf - text is grey and very difficult to read on printed paper.

**To Reproduce**
Either print to printer or pdf - text formatted as white in program is printed as grey on paper document or PDF.

**Expected behavior**
Expect white text on dark box to show up as white text on dark box

**Screenshots**
Box & text as it shows on the screen:
![image](https://user-images.githubusercontent.com/86178765/174561900-e7f7132e-3a89-43c7-b1d2-55f2d27a3e60.png)

Box as it appears on printed paper or PDF:
![image](https://user-images.githubusercontent.com/86178765/174562590-7841b90a-a8ca-4771-a51c-588d997a7e3e.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 9.0.3

**Desktop (please complete the following information):**
 - OS: Windows 10 (have tried on multiple set ups and printers and issue is consistent across all devices & setups)

**Additional context**
Nothing more to add

**Comment by ram6ler** [comment]
I also noticed this issue. However, exporting the diagram to a pdf instead of printing it directly appears to work as desired.

**Comment by adithyaappu** [comment]
I faced the same issue when exporting to PDF. Then I was able to work around the issue by unchecking 'Word Wrap' & 'Formatted Text'. Not sure what is causing the issue.

![image](https://github.com/jgraph/drawio-desktop/assets/37062841/215e6c1c-b7b3-4699-bd9b-6369f1949a54)

**Comment by PaulMakinMojaloop** [comment]
I have this issue with all white, bold text on a coloured background. Thank you to @adithyaappu for identifying a workaround, which I can confirm works. But only if BOTH "Word Wrap" and "Formatted Text" are unchecked.
