### ISSUE TITLE
Advanced export does not include grids even when enabled

### ISSUE THREAD

**Issue by deepu2** [jgraph/drawio-desktop#1052]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When exporting using advanced menu, the exported image does not include grids even after enabling grid option.

**To Reproduce**
1. Go to 'File'
2. Click on 'Export As'
3. Click on 'Advanced'
4. Select JPEG
5. Turn on 'Grid'
6. Click on 'Export' and select destination

**Expected behavior**
The exported image should have grids displayed

**Screenshots**
 - Using 'Export as' vs 'advance export'
 
![using export as jpg](https://user-images.githubusercontent.com/30926681/175228788-8bbf44d8-739a-44ce-9e9f-253a878f9086.jpg)
![using advance export](https://user-images.githubusercontent.com/30926681/175228797-ef5ee392-74fa-493b-aaa5-1ba64eb3421e.jpg)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version diagrams.net 19.0.3

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
This is the same behavior regardless of export type(JPEG,PNG,PDF)

**Comment by mararad** [comment]
Reproduced with 19.0.3, Win 10 Pro

Grid is exporting via File > Export as > JPEG with ticked grid is used. This might help if you don't need advanced settings.

**Comment by deepu2** [comment]
> Grid is exporting via File > Export as > JPEG with ticked grid is used. This might help if you don't need advanced settings.

This is ok but it doesn't include DPI settings for PNG which I need.

**Comment by Andrei030x** [comment]
And they did not deign to correct it...
