### ISSUE TITLE
Unsigned libraries in windows installer

### ISSUE THREAD

**Issue by jhellstein-ext95058** [jgraph/drawio-desktop#1053]
While adding version 19.0.1 to the internal application catalog (used for remote silent install), my coleagues from Malware Protection department pointed out that in the Windows installer there are some unsigned libraries:

- libEGL
- libGLESv2
- vk_swiftshader
- vulkan-1
- ffmpeg

They all should belong to the Electron.

Is there a chance that you could sign these libraries in next release of Windows installer?

**Comment by davidjgraph** [comment]
https://github.com/electron/electron-packager/issues/656
https://github.com/electron/asar/issues/123

describe the issues. I'd suggest to build the sign everything yourself to get around the problem for now.
