### ISSUE TITLE
Export html format with CLI

### ISSUE THREAD

**Issue by GordianDziwis** [jgraph/drawio-desktop#1055]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I use drawio in a ci job for exporting the diagram and it is not possible to export embedded html.

**Describe the solution you'd like**
Make all export options from the GUI usable from the CLI

**Comment by virgiliu-prpl** [comment]
I have the exact same use case.  I have to export manually each time I update a diagram since HTML can't be exported via CLI. Because of this missing feature I can't integrate drawio in the pipeline.

**Comment by cd-a** [comment]
Please keep open

**Comment by cbacon322** [comment]
Are there any updates on this? It would be very useful in automating documentation processes.

**Comment by mironx** [comment]
Hi, what is a status of this issue?

**Comment by davidjgraph** [comment]
The current status of this issue is that it's open.

**Comment by mironx** [comment]
> The current status of this issue is that it's open.

Yes,  Thank you. You have completely right :-) 

I should ask what is a plan and how I can help (maybe with testing)?
I realized that it could be perfect to generate via command line in pipeline to store html in s3 as static web page.

**Comment by davidjgraph** [comment]
There is no current plan. This project has about 1 person month per year of time and 160 open issues.

**Comment by davidjgraph** [comment]
In 29.6.6
