### ISSUE TITLE
"--no-sandbox" incorrectly parsed as a file?

### ISSUE THREAD

**Issue by rpavlik** [jgraph/drawio-desktop#1056]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I'm trying to run drawio on CI, in a docker container. I have to add `--no-sandbox` to get it to almost start. However, it then dies with "Error: input file/directory not found". I suspect it's trying to treat `--no-sandbox` as another file to process, but am not 100% sure.

**To Reproduce**
1. Install some way that gives you a drawio command
2. Run `drawio --export --format pdf --embed-diagram --output architecture.drawio.pdf architecture.drawio` as a normal user, not in docker: it should work if you have an "architecture.drawio" file.
3. Now run `drawio --no-sandbox --export --format pdf --embed-diagram --output architecture.drawio.pdf architecture.drawio`

**Expected behavior**
It should run, but without using the sandboxing features from electron

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 19.0.3

**Desktop (please complete the following information):**
 - OS: Linux: Debian Bullseye AMD64

**Additional context**
If there's an alternate preferred way to script this, I'd be happy to hear it, especially since using the desktop deb requires an Xvfb fake X server, asound, etc: lots of things that the actual command-line usage shouldn't probably use, but which are getting pulled in by being part of a larger app.

**Comment by mgrzybek** [comment]
Hi,

Same behaviour using a Debian 11.3 container and Draw.io 19.0.3. Here are the logs:

```bash
$ drawio --border=0 --export --no-sandbox --output diagrams/schema.png --page-index=3 \
        diagrams/schema.drawio
[20489:0802/112631.689242:ERROR:node_bindings.cc(276)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[20489:0802/112632.026361:ERROR:ozone_platform_x11.cc(248)] Missing X server or $DISPLAY
[20489:0802/112632.026380:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
make: *** [Makefile:164: diagrams/schema.png] Aborted (core dumped)
```

**Comment by 2pc** [comment]
the same with Ubuntu Server 20.04 LTS 64bit && drawio 20.3.0
```
ubuntu:~# sudo dpkg -i drawio-amd64-20.3.0.deb 
(Reading database ... 92170 files and directories currently installed.)
Preparing to unpack drawio-amd64-20.3.0.deb ...
Unpacking draw.io (20.3.0) over (20.3.0) ...
Setting up draw.io (20.3.0) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for shared-mime-info (1.15-1) ...
ubuntu:~# drawio
[1109/143750.469308:FATAL:electron_main_delegate.cc(297)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap (core dumped)
ubuntu:~# drawio   --no-sandbox
[32082:1109/143802.180830:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[32082:1109/143802.180893:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
Segmentation fault (core dumped)
```

**Comment by modelmat** [comment]
A solution for this is to have `--no-sandbox` as the last argument:

https://github.com/jgraph/drawio-desktop/issues/249#issuecomment-634157627 (a previous issue which was closed, probably because it got slightly derailed)

As for the "preferred" way to script this, as far as I know the recommendation is either to use Xvfb or to use the web server to export it (as recommended https://github.com/jgraph/drawio-desktop/issues/127#issuecomment-520125076)

**Comment by rpavlik** [comment]
Still there in the latest release.

```sh
drawio --border=0 --export --no-sandbox --output test.png lifecycle-original-draw-io.svg
```

gives

```
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
Error: input file/directory not found
```

**Comment by m-mohamedin** [comment]
Thanks for the report. It will be fixed in the next release.

**Comment by davidjgraph** [comment]
In 24.5.3.

**Comment by kalvdans** [comment]
@davidjgraph do you have a reference to the individual commit that fixed the issue?

**Comment by davidjgraph** [comment]
No, it wasn't made in a public repo.

**Comment by kalvdans** [comment]
Seems to be https://github.com/jgraph/drawio-desktop/commit/32badd8f0627841bac7aa4a39adef39bfb8c2f5d by @m-mohamedin
