### ISSUE TITLE
Closing the first window causes second window to exit as well [snap package]

### ISSUE THREAD

**Issue by jelovac** [jgraph/drawio-desktop#1057]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

When having two Draw.io windows open, closing the first one closes the second window as well. I came to this bug because of another bug, basically the discard changes functionality on exist doesn't work. When I open the app again I am presented with previous draft instead of a new project popup. So in order to create a new project I go to File => New which opens a new project in a new window. When I close the first window, the second window closes as well.

**To Reproduce**
1. Open Draw.io desktop
2. Create a blank diagram
3. Add some element to it
4. Close without saving
5. Open Draw.io desktop
6. The previous draft will be still there (no new project popup)
7. Go to File => New and create new project (new Draw.io Window will opened)
8. Close the first Window with the draft

**Expected behavior**

Only the first window should be closed.

Discarding a draft should actually discard it and not preserve it when you start Draw.io again.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 19.0.3 (snap)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
Thanks for the report
