### ISSUE TITLE
Export HTML from CLI

### ISSUE THREAD

**Issue by virgiliu-prpl** [jgraph/drawio-desktop#1059]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I would like to integrate diagram export in the build pipeline. The end goal is to have the HTML diagrams available on a local server.
According to the draw.io help command exporting HTML is not possible.

````
-f, --format <format>              if output file name extension is
                                     specified, this option is ignored (file
                                     type is determined from output extension,
                                     possible export formats are pdf, png, jpg,
                                     svg, vsdx, and xml) (default: "pdf")
````

**Describe the solution you'd like**
I would like to be able to export diagrams as HTML via CLI, along the lines of `./draw.io -x <path_to_diagram> -f html -o <path_to_output>`

**Describe alternatives you've considered**
I considered exporting as XML and creating a parser for the XML, but it proved time consuming.

**Additional context**
It seems weird to be able to export HTML from the desktop application's menu, but not from CLI.

**Comment by davidjgraph** [comment]
Duplicate #1055
