### ISSUE TITLE
Export as PNG

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio-desktop#106]
Desktop app version 10.7.5 for Win.
Performed steps: create a diagram, File > Export as PNG + Include a Copy of diagram. Then when I try to reopen it back to draw.io via File > Open, I get the error. The same thing for File > Export > Advanced > PNG.
![error](https://user-images.githubusercontent.com/44292306/59025026-8534bd80-8853-11e9-9f77-f2a95524de3c.PNG)

P.S when the file is dragged&dropped into draw.io canvas, it can't open it also ![drag drop](https://user-images.githubusercontent.com/44292306/59025308-2a4f9600-8854-11e9-88b7-291f23554c1c.PNG)

**Comment by alderg** [comment]
Works for me in 10.7.7.
