### ISSUE TITLE
"Convert Labels to SVG" missing in v19.0.3

### ISSUE THREAD

**Issue by AnSt96** [jgraph/drawio-desktop#1063]
Hello all,

I noticed that in the newer desktop versions of the application the option "Convert Labels to SVG" is missing. In older versions (e.g. [v16.5.1](https://github.com/jgraph/drawio-desktop/releases/tag/v16.5.1)) the function can still be found under File > Export as > SVG > Text Settings. The option is also described [here](https://www.diagrams.net/doc/faq/svg-export-text-problems), for example.

In newer versions, such as [v19.0.3](https://github.com/jgraph/drawio-desktop/releases/tag/v19.0.3), this option is no longer available, neither for the desktop version for MacOs nor for Windows. In the latest web app, however, the option still exists and works properly. I also tried downgrading for multiple older versions ([v16.5.1](https://github.com/jgraph/drawio-desktop/releases/tag/v16.5.1) to [v17.4.2](https://github.com/jgraph/drawio-desktop/releases/tag/v17.4.2)) but unfortunately the option, even it still exists, does not work properly anymore - the exported files are erroneous, saying for example: "This XML file does not appear to have any style information associated with it. The document tree is shown below."

Would it be possible fix this issues and to implement the option again for the desktop versions?

Thank you in advance.

![error](https://user-images.githubusercontent.com/33228502/179184204-e5aa8b68-f202-4247-b038-5049570a6c25.png)

**Comment by davidjgraph** [comment]
This has never been in the desktop tool. It requires an external server to convert the labels, the desktop app doesn't allow external connections.

**Comment by AnSt96** [comment]
Thank you for your answer! I know, that an external server connection is required, as described [here](https://www.diagrams.net/doc/faq/svg-export-text-problems), but in the previous desktop versions it was possible, as described, to select File > Export as > SVG > Text Settings to use this functionality. I used it and it worked fine. But now, since the latest updates, this option is no longer available for the newer desktop versions and for the older versions it's not working properly anymore.

**Comment by davidjgraph** [comment]
23.0.2 now replaces the warning text with a high-res image of the label, if embed images and embed fonts are ticked in the SVG export dialog.
