### ISSUE TITLE
Export preview in the application menu

### ISSUE THREAD

**Issue by ankurrajw** [jgraph/drawio-desktop#1064]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

First, I would like to thank the team behind the project. The *draw-io* tool has been really helpful for me and I use it for creating charts and diagrams for all my projects. It has become a go-to solution for me.

**Application Information**

My application version - diagrams.net 19.0.3

**Feature description**

In the 'export as' menu, it would be helpful to have an export preview option. This would allow seeing, if the final exported version fits the requirements.
Since there is no preview option, I have to check manually the exported file and modify it later on in the draw-io application and delete the no longer needed files. Sometimes I would  like to examine, how does the border width or shadow would look like before exporting. An export preview option would be really helpful for it.

Hope it would be added soon in the future releases.
Thank you 😄

**Comment by cxbignekoc** [comment]
Hi, just my 2 cents:

I think the Export Options 20.3.0 are pretty clear and pictures and diagramms are exported as expected.

Do you have any issues with it?
Can you give an Example why and when u have this complication?

I mean it seems only a gap betweens describe what the App want to do and what u expected.
