### ISSUE TITLE
unable to move the draw.io interface using the mouse

### ISSUE THREAD

**Issue by ahrib** [jgraph/drawio-desktop#1065]
Hi, am unable to move the draw.io interface using the mouse (click & drag) anywhere on the title bar in Draw.io v19.0.3

what I have tried
- following instructions in https://groups.google.com/g/drawio/c/TcikGL_aAwc/m/KrRxFZjvDwAJ  

what does work:
- using alt-space and selecting 'move' allows me to move the window e.g. with arrow keys
- resizing the window using mouse controls
- minimise, maximise, full screen and close controls

Environment
- Draw.io v19.0.3 Desktop for Windows 64 bit
- Windows 10 21H2 64-bit
- HP EliteBook 840 G8 Notebook PC

_Originally posted by @ahrib in https://github.com/jgraph/drawio-desktop/issues/866#issuecomment-1178323214_

**Comment by as7212325** [comment]
me too

**Comment by PeterGarner** [comment]
This is not a dupe IMO, it's a ruecurring issue.  My enviroment is similar ro ahrib's, Win 10, 19044.1826, draw.io desktop 19.0.3. The link above doesn't help.  minimise, maximise, full screen and close controls are working but I'm not even able to right click and get the usual menus (move etc).  No arrow key move functionality either

**Comment by davidjgraph** [comment]
This issue hasn't been marked as duplicate.
