### ISSUE TITLE
Feature Request: Hide List of Pages at bottom of Draw.io user interface

### ISSUE THREAD

**Issue by pcgeek86** [jgraph/drawio-desktop#1067]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

I would like to be able to hide the horizontal list of Pages at the bottom of the Draw.io desktop user interface. Right now, there doesn't seem to be an option to hide the list of Pages.

**Comment by mararad** [comment]
It's not supported at the moment but as a workaround you can try Sketch theme (Extras > Theme > Sketch) and check if it suits your needs.
