### ISSUE TITLE
Allow any registered URL scheme/protocol in links

### ISSUE THREAD

**Issue by saf-dmitry** [jgraph/drawio-desktop#1070]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm missing the possibility to link to local resources (files, notes, etc.) using any custom protocol associated with a certain URL scheme and registered on the OS level, e.g. `file://`, `ibooks://`, `mobilenotes://`, etc.

**Describe the solution you'd like**
Using any custom protocol associated with a certain URL scheme and registered on the OS level. Handling of such external links should simply be delegated to the OS.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by neeles83** [comment]
Can I ask why this was declined as it seems a very handy feature. As ssh:// worked a while ago for me but now it doesn't. 
This makes it really powerfull to make drawings of environments and directly connect to devices upon issues shown. 

Same applies for linking to file/folders where documentation is placed. 

Hope the team will re-consider and enable the https://en.wikipedia.org/wiki/List_of_URI_schemes implementation of most commonly used URI schemes. like ssh/file/smb/mailto.

**Comment by davidjgraph** [comment]
Because I don't want to be responsible for the security implications of allowing arbitary protocols.
