### ISSUE TITLE
Please add support for Mac OS Ventura

### ISSUE THREAD

**Issue by ghost** [jgraph/drawio-desktop#1079]
[+] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
[+] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

When I download and try to open draw.io app - it says that the OS Ventura is not supported.
![image](https://user-images.githubusercontent.com/25117767/182929734-66aa77af-be7d-4244-88cf-7879eacc55f3.png)
There is no such issue with other non Apple apps.

Please, just make sure that user can launch on Ventura, even if it is a buggy thing.

**Comment by teivarodiere** [comment]
Hi olezhlviv, did Draw.IO end up working since you posted this comment or is it still a problem with MacOS 13 Ventura?

**Comment by ghost** [comment]
Hello @teivarodiere , a few days ago it was still an issue so I have removed the app.

**Comment by teivarodiere** [comment]
Hi @olezhlviv, got my hands on a spare Macbook Pro Intel and upgraded to MacOS Ventura and draw 20.3.0 appears to be working fine. I haven't tried it on a M1 though

**Comment by teivarodiere** [comment]
I've upgraded my MacBook Pro M1 from Monterey to Ventura and draw.io starts fine. Can modify and save files. I have not used it in anger but so far so good.

**Comment by ghost** [comment]
Checked on the Intel-based MacBook Pro, and it's working. Thank you!
