### ISSUE TITLE
Export as JPEG fails if file name isn't saved fast

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio-desktop#108]
When you go to File > Export as JPEG, the spinning wheel "Exporting" shows and you basically don't know when exporting is over (i.e if you don't write file name and save it, it will just show spinning wheel endlessly). So when you click File > Export as JPEG and save File name fast, it exports well, but when you wait a little bit, the export fails. I recorded a video so you can see all the details.

![spinning wheel exporting](https://user-images.githubusercontent.com/44292306/59033932-3f372400-886a-11e9-9fc4-8913daa3cd04.PNG)

**Comment by ashrafteleb** [comment]
Fixed in v10.8.0
