### ISSUE TITLE
The connect point of the square is only in the center.

### ISSUE THREAD

**Issue by TasukuMatsuura** [jgraph/drawio-desktop#1086]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When connecting arrows in a rectangle, connectors appear only in the center.

**To Reproduce**

1. Start Drowio
2. Enter a flowchart
3. After using Drowio for a while, the lines that could be connected to the sides of a square can now only be connected to the center of the square.
4. Restart drowio (reopen the file) to get back to normal.

**Expected behavior**
The default square can have lines connected to its edges.

**Screenshots**
when there is a problem
![image](https://user-images.githubusercontent.com/28883540/184531489-0f10500a-6541-4f0f-9f53-4bf268379313.png)

when there is no problem
![image](https://user-images.githubusercontent.com/28883540/184531560-e58d4de6-9a9e-4b0a-bc1e-8a0748a7cd10.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 20.2.3

**Desktop (please complete the following information):**

- OS: Windows10

**Additional context**

I like and use drowio but may have to switch to another drawing tool because of this problem. Please fix this problem as soon as possible so that I can continue to use drowio.

**Comment by davidjgraph** [comment]
Why do you keep calling it drowio?

**Comment by TasukuMatsuura** [comment]
> Why do you keep calling it drowio?

Isn't drowio the official name?

**Comment by TasukuMatsuura** [comment]
@davidjgraph 
Will this problem be fixed soon?
