### ISSUE TITLE
Error - Invalid File Data

### ISSUE THREAD

**Issue by lightify97** [jgraph/drawio-desktop#1088]
**Describe the bug**
I'm getting invalid data file error on opening a file. I have been working on a very complex diagram with auto save enabled. Unfortunately my PC lost power somehow and after turning on, the file (attached as zip below) is not opening. It gives the "Invalid file data" error. 
[sequence2.zip](https://github.com/jgraph/drawio-desktop/files/9339383/sequence2.zip)

**Screenshots**
![Screenshot 2022-08-16 002524](https://user-images.githubusercontent.com/16276964/184703618-0b0c200b-6c0c-4a6b-a8f0-9e619a9ec65b.png)

- draw.io version 20.2.3
- OS: Windows

PS: I'm a student and devoted significant amount of time working on it and can't redo all the work again.

**Comment by mararad** [comment]
Hi,

We keep two hidden recovery files next to main file (.$FILENAME.bkp and .$FILENAME.dtmp). These file should include an older version of the main file.

**Comment by dbishoponline** [comment]
The exact same issue as @lightify97.  See screenshot

- macOS Big Sur
- diagrams.net 20.2.3 (latest version at time of writing this comment)

<img width="556" alt="Screen Shot 2022-08-28 at 1 41 28 PM" src="https://user-images.githubusercontent.com/306974/187094074-71fa3020-6d6d-4e39-bcf5-0b6b3a280240.png">

Checking the recovery files now to see what got saved.  Thanks for the suggestion @mararad

**Comment by LuisAngelLibreros** [comment]
Es de gran ayuda sincronizar la carpeta donde estás guardando tus archivos .drawio con algún tipo de nube (en mi caso GDrive), a pesar de tener los archivos de respaldo (.bkp y .dtmp) me seguía surgiendo el error (Invalid File Data). Busqué en la papelera de reciclaje de la nube, filtré los archivos por fecha de eliminación y encontré, por suerte, el último archivo de respaldo antes de tener el archivo corrupto, lo descargué y funcionó, además de tener todos mis diagramas como los había dejado

Espero les pueda servir de ayuda 😁
![si](https://user-images.githubusercontent.com/123835651/215287409-aeff6006-d796-4937-88c0-dd690ba2b8fe.png)

**Comment by yelinlan** [comment]
I met same problem too,so upset! bakfile not complete,file size turn to 0 kb. mybe I need redo it.

**Comment by federicoch** [comment]
Hi, make sure that the file encoding is UTF-8
I went through the same problem and after debugging I found that it could not detect the encoding, in my case it had UTF-8 BOM and I changed it to UTF-8 and it worked correctly.
![image](https://github.com/jgraph/drawio-desktop/assets/4155762/64066977-bac6-4249-81a1-b933da9d81ec)

Your sequence2.drawio file is ANSI encoded, and full of null characters, it is unrecoverable.

**Comment by davidjgraph** [comment]
Moving to https://github.com/jgraph/drawio-desktop/issues/1366
