### ISSUE TITLE
italicization not working during exporting

### ISSUE THREAD

**Issue by jerryzhujian9** [jgraph/drawio-desktop#109]
italicized texts are rendered as normal fonts after exporting to pdf (i.e., not kept italicized)

**Comment by davidjgraph** [comment]
Test with single line of text in Helvetica exported correctly. Please provide exact reproduction steps.

**Comment by jerryzhujian9** [comment]
I am testing with draw.io offline version 10.7.7 under mac. Helvetica and
Times New Roman neither works.
[image: image.png]

**Comment by davidjgraph** [comment]
Download the latest dmg from https://github.com/jgraph/drawio-desktop/releases, install and try again.

**Comment by jerryzhujian9** [comment]
Yes. I have been using the latest version draw.io 10.7.7 under Mac OS X
10.10.5. The snapshot in last email was done with the latest version.

**Comment by davidjgraph** [comment]
You specifically downloaded that version is the past 5 days?

**Comment by jerryzhujian9** [comment]
Yes. I tested it again in my virtual machine (same configurations) with a
fresh install. Still same issue.

[image: image.png]

**Comment by davidjgraph** [comment]
You have a VM of MacOS?

**Comment by jerryzhujian9** [comment]
I have both VM of MacOS and actual MacOS. Tried on both, still same issues.

**Comment by davidjgraph** [comment]
Just can't repeat, tried on 5 different Macs, all fine. It's Latin text you're typing?

**Comment by jerryzhujian9** [comment]
weird. Thanks for trying. I am using mac osx 10.10.5 (yosemite, both actual
and virtual). tried different fonts as well (verdana, times new roman,
helvetic). all same issues when exporting as pdf. but no issue when
exporting as png

**Comment by davidjgraph** [comment]
Could you do a video please?

**Comment by jerryzhujian9** [comment]
The recording is here
https://www.dropbox.com/s/kbpkcn3clyewzt4/drawioitalic.mp4?dl=0

**Comment by davidjgraph** [comment]
Thanks, I'll see if anyone else at our end can reproduce.
