### ISSUE TITLE
Enable external plugins in the desktop version

### ISSUE THREAD

**Issue by LirazShay** [jgraph/drawio-desktop#1098]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't add custom plugin to the desktop version
![image](https://user-images.githubusercontent.com/16083652/186397070-dd35b2c9-8412-4b64-991e-5b693f40c7b8.png)

**Describe the solution you'd like**
Allow to enable custom plugin in desktop version

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
Use `--enable-plugins` on command line to enable
