### ISSUE TITLE
File association does not work correctly on Linux Mint with AppImage

### ISSUE THREAD

**Issue by matthew-rindel** [jgraph/drawio-desktop#11]
Hi there,

A big thank you to the Draw.IO team for creating such fantastic software, full of awesome templates, an easy to use interface and both web and desktop support. Our team workflow has been revolutionised by all of your efforts, which means you have indirectly contributed to the overall development of Africa because of our work.

I wanted to report an issue when opening files through Nemo in Linux Mint 17. It does not open the file specified but rather just shows the new/open file dialog.

Also when trying to open a file from the terminal it does the same thing.

I have not developed with Electron, though I assume it is relatively simple to pass the command line arguments to the application.

Have a great week and as said in Madagsacar, tsikitsiky lava (always smile),
Matthew

![open with draw io](https://user-images.githubusercontent.com/26255902/33179128-7e37e180-d079-11e7-81d6-b36377cc050d.png)
![file does not open](https://user-images.githubusercontent.com/26255902/33179132-8065e06a-d079-11e7-8c8a-320890a894c7.png)

**Comment by alderg** [comment]
Hujambo!

Please vote for this feature here: https://trello.com/c/Yi0s2ZXu/273-handle-command-line-arguments-in-electron-builds-open-file-scripted-export

Asante sana!

**Comment by ksix** [comment]
This is a massive workflow problem for us too. We have 15+ developers who use draw.io desktop from macOS. This really would be great to fix.

**Comment by ashrafteleb** [comment]
Added, should be available with the next release

**Comment by ebousse** [comment]
This does not appear to work in Linux systems? In the release notes I can only see the following:
>.drawio is now the default extension and .drawio is associated with the application in **Window** on install.

**Comment by ashrafteleb** [comment]
Did you try the AppImage format?

**Comment by davidjgraph** [comment]
On debian the mime type is text/plain, which will cause an issue.

**Comment by ebousse** [comment]
> Did you try the AppImage format?

I was using the `.rpm` installed. I just tried with the Appimage and it works, the mime type does get added to the system, and even remains there after removing the Appimage, which solved the problem for my rpm-bases installation.

**Comment by zeitue** [comment]
This is an issue on Linux as well, I have tested both the deb file and the AppImage, neither of them has the mime-type registered. In addition to that, neither of them actually put an icon for the app in place. I have a blank no icon spot for where the app is.

**Comment by ashrafteleb** [comment]
Which linux distribution had this problem?

**Comment by PapsOu** [comment]
I've got this problem (missing mime-type and missing icon) under fedora 30 with GNOME 3.32.2.

**Comment by TimHandy** [comment]
I also find this annoying on PopOS! Can r-click > Open with Draw.io, but can't double-click as it thinks its a plain text file, and also the icon is just a plain text file rather than the drawio icon. Setting the default app to draw.io makes no difference.

**Comment by giner** [comment]
File association doesn't on the snap package but works when deb-package is installed. Here is a work around https://gist.github.com/giner/0eb272c11085036c4438413f6de0e454.

**Comment by giner** [comment]
Also it seems that snapcraft don't support mime types registering yet https://bugs.launchpad.net/snapd/+bug/1849094

**Comment by Lezurex** [comment]
When I select .drawio or .xml as file type in the save dialog, it will be saved with mime type **text/plain** for **.drawio** and **application/xml** when saving as **.xml**. When I want to open the file again, I have to right-click on it and select to open it with with draw.io. However, this also changes the default application for all normal text files which also have text/plain as their mime type. This means, if I want to open a normal text file, I have to change it back again.

In the **.desktop** file of draw.io, two mime types are configured:
- application/vnd.jgraph.mxfile
- application/vnd.visio

But these definitions are useless if draw.io doesn't save its files with these mime types.

**Comment by giner** [comment]
Try this https://gist.github.com/giner/0eb272c11085036c4438413f6de0e454

**Comment by davidjgraph** [comment]
There's a number of requests for support for specific OS's and specific images. We're going to have to treat different distros as different issues, the Linux OS ecosystem has very fragmented behaviour. I'll change this one to be that of the original author, if yours varies from that please open a new issue.
