### ISSUE TITLE
Window can't be moved with collapsed title bar in draw.io desktop

### ISSUE THREAD

**Issue by ctoabidmaqbool** [jgraph/drawio-desktop#1100]
Draw.io desktop windows : 20.2.3

![image](https://user-images.githubusercontent.com/10474725/187033103-5f05ac26-b424-487f-a568-e18ae2f4e4d4.png)

When Title bar is collapsed, Window can't be moved using mouse drag & drop.

**Comment by ricardoMTC** [comment]
Im having the same issue over here as well. I actually didnt realize that I would need uncollpase the window in order to move it

**Comment by davidjgraph** [comment]
Duplicate #784
