### ISSUE TITLE
links that take you to a specific shape

### ISSUE THREAD

**Issue by jitterbug888** [jgraph/drawio-desktop#1103]
I wanted to create links that take you to a specific shape. 
The shape could be on another part of the workspace in another mind map, on another tab, or on another layer.

This allows me to create complex general mind maps (like a visual index), that I can click shape links on, that take me to another shape at the beginning of another mind map

Assuming this would work by being able to first name the shape we want to link to, then on the linking shape, using "edit link", "link to (name of shape we just named)"..
Something like that.

**Comment by mararad** [comment]
You can try using custom links: https://www.diagrams.net/doc/faq/custom-links

**Comment by jitterbug888** [comment]
thanks for the link, I dont program so its very confusing to me. I`ll wait for further developments if any. Just want to do the same right click and choose the named shape from a link list.
