### ISSUE TITLE
How to manipulate a rectangle?

### ISSUE THREAD

**Issue by ffgg11** [jgraph/drawio-desktop#1105]
Thanks for your contributions.

How to divide a rectangle into several sub-shapes and fill different sub-shapes of a rectangle with different colors?

**Comment by cxbignekoc** [comment]
What is the meaning of Sub-Shapes?
You have just ICONS...and Icons are just Pictures.
Draw.io is not a Graphic App like Inkscape to Edit these Pictures in that kind.

Maybe there is an Icon what looks like u want.
