### ISSUE TITLE
Arrows issue with the 'Freehand' tool

### ISSUE THREAD

**Issue by Joelg4dea** [jgraph/drawio-desktop#1107]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When I draw with the 'Freehand' tool, it appears an 'arrow' tool (I don't know this tool's name) that creates arrows connected to what I made. So, drawing too fast causes non-intentional clicks on that 'arrow tool'.

**Describe the solution you'd like**
I think that a good solution would be not to show the 'arrow' tool when using the 'Freehand' tool.

**Describe alternatives you've considered**
Showing the 'arrow' tool after 1.5 seconds of inactivity may be an alternative solution.

**Additional context**
'Arrow' tool:
![ArrowTool.png](https://cdn.discordapp.com/attachments/421764608416808970/1016346743148920933/unknown.png)

Issue:
![ArrowIssue.gif](https://cdn.discordapp.com/attachments/421764608416808970/1016345264807751770/ArrowIssue.gif)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/24e3016c7ad5acf53f4c83e5578af1a7eccb5a1e
Internal release https://drawio.atlassian.net/projects/DS/versions/11214

**Comment by davidjgraph** [comment]
In 20.3.0 release.
