### ISSUE TITLE
Support 2022 AWS icons/shapes

### ISSUE THREAD

**Issue by maunzCache** [jgraph/drawio-desktop#1108]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
I just noticed that drawio is limited to the AWS icon set from 2017-19 but does not feature newer services. Instead of downloading, extracting and importing all the new icons into drawio i'd love to have the new icons and deprecate older ones.

**Describe alternatives you've considered**
Manually import icons.

**Additional context**
Apparently #974 does not seem to fix the issue for me. Using 20.2.8 currently.

**Comment by davidjgraph** [comment]
Could you show us in the more shape dialog where you believe the AWS icons are the 19 set?

**Comment by maunzCache** [comment]
Sure. Even though my dialogs are in german you should be able to understand them from the context.

![image](https://user-images.githubusercontent.com/166729/188802040-80d2139a-ef3a-4d19-95da-7cfcb428608d.png)

So basically my click-path is to open a diagram, then go to the bottom left and click "more shapes". This opens the dialog in the screenshot. If you scroll a little to the "Network" section it will show up the AWS icon sets.

**Comment by davidjgraph** [comment]
19 is the current set.

**Comment by sebastian-fredriksson-bernholtz** [comment]
@davidjgraph The latest release from AWS at the time of writing this is [2023-01-31 (2023 Q1)](https://d1.awsstatic.com/webteam/architecture-icons/q1-2023/Asset-Package_01312023.d59bb3e1bf7860fb55d4d737779e7c6fce1e35ae.zip), linked from
https://aws.amazon.com/architecture/icons/
