### ISSUE TITLE
Click to stop drawing in 'Freehand' tool

### ISSUE THREAD

**Issue by Joelg4dea** [jgraph/drawio-desktop#1109]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
My feature request is something more like a 'remove feature' request. I have been testing a bit of the 'freehand' tool, and it's so useful and great, but the 'click to stop drawing' is very annoying. I constantly click on the screen to draw, and sometimes the tool stops drawing when that was not what I intended. It's not a bug, it's just that if I try to draw a word like 'time', the 'freehand' tool will disable itself during or after the letter 'i'.

**Describe the solution you'd like**
The removal of 'click to stop drawing' would be a good solution.

**Describe alternatives you've considered**
An alternative solution may be 'click 500 pixels away from what you just drew' so the program can interpret it as 'I want to stop drawing'. Another alternative solution can be 'secondary click to stop drawing'.

**Additional context**
Me trying to draw 'time':
![TimeDraw](https://cdn.discordapp.com/attachments/421764608416808970/1017028999282708531/TimeDraw.gif)

In a draft, how many times did I unintentionally 'stopped drawing'?:
('compensated' status means that I pressed 'X' to 'start drawing' again)
![compensation](https://cdn.discordapp.com/attachments/421764608416808970/1017076918161510551/freeCompensation.gif)

As seen in the context, there were several times that I had to compensate for the deactivation of the 'Freehand' tool.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release. (You can use the "x" key to start/stop drawing.)

**Comment by Joelg4dea** [comment]
Great! Thank you so much!

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/aeb252941c76efb6d758f2e11ed0a47d42bbd705
