### ISSUE TITLE
When Shadow is set on the background, it is not showing on the front page.

### ISSUE THREAD

**Issue by omg247** [jgraph/drawio-desktop#1110]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When a diagram "shadow" option is checked, and if that same diagram (or page) is set as a background to another, the shadow is not showing.

**To Reproduce**
1. Create New Blank Diagram
2. Insert a new page 
3. Now we should have Page-1 and Page-2
4. Go to Page-2, drop as many Rectangle shapes (or any shape), let's add 2
5. Still on Page-2, click anywhere free on the workspace, this will deselect any selection
6. By default a Diagram tab should be showing in the top right corner
7. Look for the Shadow checkbox, check it
8. The Rectangles should now be showing with a shadows
9. Now, go back to Page-1
10. Under the Diagram tab top right, check the "Background" checkbox, and click on the "Change" button.
11. In the dialog, select the 2nd radio button and choose Page-2, click Apply
12. The bug, Page-1 is not showing any shadow but Page-2 does.

**Expected behavior**
I would expect to see shadows on Page-1 (the front page) when I choose to have shadows in the background (Page-2).

**Screenshots**
![image](https://user-images.githubusercontent.com/74977207/188994675-624b0b1f-5c05-4d9a-b0e8-8c8c6e6ab8e5.png)
![image](https://user-images.githubusercontent.com/74977207/188994780-1fcd5d84-7886-4dcf-aa45-08c7eb95f8aa.png)
![image](https://user-images.githubusercontent.com/74977207/188994820-fca75d5d-5101-469d-be9d-9712be5c8f9a.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.2.8
- draw.io version 19.0.3

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise

**Additional context**

**Comment by mararad** [comment]
If you select both rectangles together, click "Shadow" under Style tab and then add background does it help?
It is working at my place.
![shadow](https://user-images.githubusercontent.com/44292306/189334587-6bd8a54d-a3b8-4cd8-9c8b-d02e2a49b341.JPG)

**Comment by omg247** [comment]
Yes, adding a shadow for each shape on the background page will work but that would defeat the purpose of having a shadow option for the whole diagram no? With one simple click, you can add or remove all shadows...

But TBH, perhaps I should've pointed this out first... the shadow option for a particular shape vs the shadow for the whole diagram, are both different, the one for the diagram is smoother and much better.

Style Shadow
![image](https://user-images.githubusercontent.com/74977207/193683347-2f9ffc65-8c44-4277-b142-9f9b38707193.png)

Diagram Shadow
![image](https://user-images.githubusercontent.com/74977207/193683450-9df56dcf-a2aa-466b-9459-e9d2f1a2da8c.png)
