### ISSUE TITLE
C4 - Person - Long Description Overflow Issue

### ISSUE THREAD

**Issue by rowan-trade** [jgraph/drawio-desktop#1112]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When I use a description for a C4 person it breaks out of the person container

![overflow drawio](https://user-images.githubusercontent.com/113126667/189170134-9b757a5f-3f15-4114-a324-43c63ce42e23.png)

**To Reproduce**
1. create a doc
2. add c4 person
3. add a long description

**Expected behavior**
The text should not break out of the person container 
![fix drawio](https://user-images.githubusercontent.com/113126667/189170532-4ac53c0b-4529-40ee-878b-870e853183c6.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.3.0

**Comment by mararad** [comment]
Reproduced. Text overflow options don't help.

**Comment by rowan-trade** [comment]
Re-created in draw.io repo - https://github.com/jgraph/drawio/issues/3064
