### ISSUE TITLE
Autosize of multiple selected vertices does not work anymore

### ISSUE THREAD

**Issue by nap-devotion** [jgraph/drawio-desktop#1116]
Hello,

with version 20.3.0, the button **Autosize** under menu **Arrange** is deactivated if multiple vertices are selected.
The corresponding keyboard shortcut does also have no effect.

![image](https://user-images.githubusercontent.com/99590972/189537050-d044ecd2-3d6e-453f-80e6-43405a92e87f.png)

I'm sure that I've used **Autosize** on multiple selected vertices on older versions in the past.

**Comment by mararad** [comment]
What would you like to get on two shapes autosize, please?
Autosize basically works after a change is made.
If you click Autosize button under Arrange tab on the right, does it help?

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/977dac79da0bc7cec68ec4e74a9713e2fc0e5f48
Internal commit https://drawio.atlassian.net/projects/DS/versions/11215

**Comment by davidjgraph** [comment]
Fixed in 20.3.1
