### ISSUE TITLE
Blurry Interface

### ISSUE THREAD

**Issue by bender-ai** [jgraph/drawio-desktop#1120]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The **characters**, the writings, of the **interface** randomly appear **blurry**. When the mouse hovers over, the interface returns to normal.
(see attached image)

Same problem even with older versions

Multimonitor setup. GPU Nvidia

**To Reproduce**
randomly

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/78745008/190105815-74398ff7-844c-4661-8546-5043e49d853f.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.3.0

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Additional context**

**Comment by davidjgraph** [comment]
This isn't a general issue, it's specific to your setup, it's not something we have the resources to investigate.

**Comment by bender-ai** [comment]
Thanks for the reply. It only happens with this program. I thought it would be useful to at least report
