### ISSUE TITLE
File name in title bar

### ISSUE THREAD

**Issue by blopa1961** [jgraph/drawio-desktop#1125]
Feature request for the Windows app:
Would it be possible to add the document filename to the title bar?
Thank you.

**Comment by mararad** [comment]
Please take a look at https://github.com/jgraph/drawio-desktop/issues/191

**Comment by blopa1961** [comment]
I just did, but displaying the document name in the title bar is not the same as having to click SaveAs to find out which document you are editing. Usually document editing programs like Word for instance have the name of the document you are editing there, and draw.io is a (Windows in this case) document editing program.
Thank you.

**Comment by cxbignekoc** [comment]
> I just did, but displaying the document name in the title bar is not the same as having to click SaveAs to find out which document you are editing. Usually document editing programs like Word for instance have the name of the document you are editing there, and draw.io is a (Windows in this case) document editing program. Thank you.

What Problem is related to it?
You can just open ONE Dokument and you can just have ONE Name for it. If you work on a File
the Filename shows in Title Bar - Thats the File you edit and work on. Normally you can always "Save as" new Version via File Tab.
If you use "Save as" the Title Bar show the saved as File. So you know you not working on the previous file.
Thats pretty normal imho...

**Comment by blopa1961** [comment]
It seems you never opened 2 (or more) instances of the program to be able to copy a part of a graph and paste it in another graph/file. I would really appreciate this feature, but if all I'll get is criticism, I give up.
Thanks anyways.

**Comment by davidjgraph** [comment]
cxbignekoc, the tone of your post does come over as somewhat rude. The original request isn't entirely unreasonable, as an external commenter please adhere to the https://github.com/jgraph/drawio-desktop/blob/dev/CODE_OF_CONDUCT.md.
