### ISSUE TITLE
Predefined Process, text alignment

### ISSUE THREAD

**Issue by Gwilym-Rutherford** [jgraph/drawio-desktop#1132]
when adding text to a predefined Process, under the flow chart tab, the text lies below the box instead of inside the box.
Hopefully something that can be easily fixed

**Comment by mararad** [comment]
Select the shape and change Position to Center under Text tab.

![position center](https://user-images.githubusercontent.com/44292306/193582262-fc4b8271-c964-4f6d-a9b1-6c233799c6e9.JPG)
