### ISSUE TITLE
Export in HTML format from the CLI

### ISSUE THREAD

**Issue by SamuelDeal** [jgraph/drawio-desktop#1133]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I would like to generate interactive diagrams from my CI. 
The draw.io has nice CLI ```--export``` and ```--format``` flags but it seems *HTML* is not supported

**Describe the solution you'd like**
I would like the CLI to export HTML diagrams like the GUI tools. I just need it to work like the GUI with all option checkboxes unchecked. 

**Describe alternatives you've considered**
I've tried other formats but they are not interactive

**Comment by cd-a** [comment]
This is a feature that I miss dearly. Being able to run a cronjob every morning to export the latest version to HTML would be a game changer.

**Comment by davidjgraph** [comment]
Duplicate #1055
