### ISSUE TITLE
Add "Convert Labels to SVG" to the desktop version of drawio.

### ISSUE THREAD

**Issue by VorpalBlade** [jgraph/drawio-desktop#1134]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When exporting SVGs in drawio-desktop "Convert Labels to SVG" is missing. This seems not to be a bug but a missing feature based on some previous bug reports. According to https://www.diagrams.net/doc/faq/svg-export-text-problems this is implemented by "[...] transmits the diagram to our servers, generates a PDF, then pipes that through Inkscape, and returns the SVG output."

However, if inkscape is installed locally (as is quite common on Linux at least) this should also be possible to run locally.

**Describe the solution you'd like**
I propose an optional dependency on inkscape, perhaps with a configuration option to specify the path to it (may be needed on Windows/Mac as inkscape is less likely to be in `PATH`).

**Describe alternatives you've considered**
Manually exporting to PDF, running through inkscape and saving. It is annoying and time consuming: the software should be able to do it automatically.

**Additional context**
Distro: Arch Linux (rolling release, so no version).

**Comment by VorpalBlade** [comment]
Any motivation for why this is declined? Is it too difficult to implement? I'm not a javascript programmer, but in something like Python it would be as simple as a couple of `subprocess.run()` calls. I can't imagine that nodejs makes it that much harder to run a process?

**Comment by davidjgraph** [comment]
We don't want to implement and maintain it. I haven't closed it.

**Comment by VorpalBlade** [comment]
I don't believe this is stale, nor is it fixed.

**Comment by davidjgraph** [comment]
We're not going to implement this.

**Comment by argenos** [comment]
I just wanted to add another data point even if it doesn't change the `wontfix` status, as I ran into this issue today and need this feature offline.

**Comment by griffin-warrior** [comment]
I'm using the latest version and still encountering this issue.

**Comment by davidjgraph** [comment]
We're not going to implement this.

**Comment by davidjgraph** [comment]
23.0.2 now replaces the warning text with a high-res image of the label, if embed images and embed fonts are ticked in the SVG export dialog.

**Comment by Timmmm** [comment]
How does the online conversion deal with this? Do you run headless Chrome or something like that?

**Comment by Timmmm** [comment]
Never mind; I thought draw.io was open source and was going to try to implement it myself but it seems that's not the case.

**Comment by ap653998** [comment]
> We're not going to implement this.

How arrogant is this guy?

Then, remove also the export to SVG feature at all, it's useless if you don't follow the SVG standard.
What's the point to export a vectorized diagram that embeds fonts as PNG images?
How stupid to do that?

How hard is to do that:

```
	<style type="text/css">
	<![CDATA[
		.st2 {fill:#000000;font-family:Calibri;font-size:1.00001em}
	]]>
	</style>
```

And later on, just use:

`<text x="39.07" y="1129.8" `class="st2">Testing</text>`

Really? And you're developer on drawio?
