### ISSUE TITLE
partConcEllipse broken in 10.8.0?

### ISSUE THREAD

**Issue by martijnlaan** [jgraph/drawio-desktop#114]
It seems like partConcEllipse is broken in 10.8.0:

Here's an example of how one I use looks in 10.7.7:

![afbeelding](https://user-images.githubusercontent.com/1092369/60009642-80a33e00-9676-11e9-970e-1eff944374bf.png)

The style is:
`verticalLabelPosition=bottom;verticalAlign=top;html=1;shape=mxgraph.basic.partConcEllipse;startAngle=0.5;endAngle=0.75;arcWidth=0.27;shadow=0;direction=west;strokeColor=none;fillColor=#000000;`

And here's how it looks after an update to 10.8.0 without any changes to the .drawio file:

![afbeelding](https://user-images.githubusercontent.com/1092369/60010413-0c699a00-9678-11e9-9bc0-0def7d92359a.png)

If you look at it closely you will see it has 3 different parts and colors.

I was unable to get it to be like in looks in 10.7.7 again so I downgraded for now.

**Comment by davidjgraph** [comment]
Can you repeat the problem on www.draw.io?

**Comment by martijnlaan** [comment]
Thanks for the reply. I just tried and it looks fine when opened on www.draw.io.

**Comment by davidjgraph** [comment]
OK, the 10.8.0 release has this bug, the releases use the current online production version, so it'll be fixed in the next release.

**Comment by martijnlaan** [comment]
Thanks 👍
