### ISSUE TITLE
Please add Arm Linux release 

### ISSUE THREAD

**Issue by xiaohelong** [jgraph/drawio-desktop#1140]
* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

No arm64 Linux deb,rpm or snap,flatpak package,please add this feature

**Comment by alvsanand** [comment]
In my case, I use devcontainer on Mac M1 and without it it would not work. Are you planning to do it?

**Comment by vkaelin** [comment]
> In my case, I use devcontainer on Mac M1 and without it it would not work. Are you planning to do it?

I have exactly the same issue. If anyone has a workaround it would be nice!

**Comment by ZelnickB** [comment]
+1 to this request!

@alvsanand, do you mean that you have found a method to use a devcontainer as a workaround? If so, is there any way that you could share instructions?

**Comment by alvsanand** [comment]
I was able to compile it modifying the electron-builder-linux-mac.json file.

Here is my script using ubuntu:

```
#!/bin/bash

export NODEJS_VERSION="14"
export FPM_VERSION="1.9.3"
export CC="clang"
export CXX="clang++"
export npm_config_clang="1"
export USE_SYSTEM_FPM="true"

apt-get update && apt-get install -y libgnome-keyring-dev icnsutils graphicsmagick xz-utils rpm git curl jq

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash \
    && export NVM_DIR="$HOME/.nvm" \
    && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
    && nvm install $NODEJS_VERSION && nvm use $NODEJS_VERSION \
    && curl -o- -L https://yarnpkg.com/install.sh | bash \
    && export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

git clone --recursive https://github.com/jgraph/drawio-desktop && cd drawio-desktop \
    && git reset --recurse-submodule "v$DRAWIO_VERSION"

apt update && apt-get install --no-install-recommends -y ruby-full bsdtar rpm libopenjp2-tools \
    && gem install fpm -v $FPM_VERSION

cp electron-builder-linux-mac.json electron-builder-linux-mac.json.old \
    && cat electron-builder-linux-mac.json.old \
    | jq 'del(.publish)' \
    | jq 'del(.mac)' \
    | jq 'del(.target)' \
    | jq '.linux += { "target": [ { "target": "deb", "arch": [ "arm64" ]} ] }' > electron-builder-linux-mac.json

cp package.json package.json.old \
    && cat package.json.old \
    | sed 's/ --publish always//g' > package.json  \
    && cat package.json

export NVM_DIR="$HOME/.nvm" \
    && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
    && nvm use $NODEJS_VERSION \
    && npm install -g yarn \
    && export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH" \
    && yarn install \
    && yarn run sync \
    && yarn run release-linux
```

**Comment by m-mohamedin** [comment]
Will be included in the next release

**Comment by davidjgraph** [comment]
In 21.6.5

**Comment by alvarosantossyngenta** [comment]
Thanks a lot!
