### ISSUE TITLE
希望改进设置文本的字体的方法（I hope you can improve the way that set the font of a text）

### ISSUE THREAD

**Issue by zjyyshyn** [jgraph/drawio-desktop#1141]
问题：目前的文本的字体的设置方法太笨了，一般用户根本不从哪里获得字体的索引名称（不是显示名称） 。
建议：自动获取操作系统中已安装的字体的显示名称的列表和索引名称的列表，再根据用户选择的字体名称，然后根据对应的索引名称将当前文本的字体为目标字体。
Problem: The current way of setting TEXT fonts is so stupid that the average user doesn't get the index name (not the display name) of a font from anywhere.

Suggestion: Automatically obtain the list of display names and index names of installed fonts in the operating system, and set the current text font as the target font based on the selected font name and corresponding index name.

**Comment by davidjgraph** [comment]
And how do you get the OS installed fonts from a browser?

**Comment by yamazakitouma** [comment]
> And how do you get the OS installed fonts from a browser?

建议可以参考 Figma 提供一个获取本地字体的程序，安装到本地系统上。
