### ISSUE TITLE
Update bug

### ISSUE THREAD

**Issue by DamarisJolon** [jgraph/drawio-desktop#1142]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The program is running slow with the new update. They do not load changes quickly and do not copy and paste elements. If you could fix it, thank you.

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...

**Additional context**

**Comment by JanB1** [comment]
I had a problem where I wasn't able to auto-update from 20.6.2 to the newest version. It would tell me "Update available, would you like to update" and when I clicked yes, it went through the whole update installation procedure, only to tell me "Update available, would you like to update" again the next time I started the program.

Maybe @DamarisJolon encountered the same issue?

**Comment by davidjgraph** [comment]
We're not able to recreate this issue, so there's isn't anything we can reasonably do.

I'd assume it's an issue with the electron updater package we use, but the lack of recent reports suggest it's fixed.

The workaround is to download the latest version from https://github.com/jgraph/drawio-desktop/releases and install.
