### ISSUE TITLE
This error keeps appearing and I haven't done much (Not a diagram file (error on line 1 at column 19922945: Extra content at the end of the document))

### ISSUE THREAD

**Issue by Hamphrie** [jgraph/drawio-desktop#1145]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

I have an error that makes me unable to open my diagram

**To Reproduce**
1. Go to draw.io
2. Click on Dragon de la Cima Helada

**Expected behavior**

Error:
Not a diagram file (error on line 1 at column 19922945: Extra content at the end of the document)

**Screenshots**

![image](https://user-images.githubusercontent.com/115879012/195986910-ba7d6556-d017-4930-8116-2de4178e4086.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

20.3.0

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...

Windows10

**Additional context**
[File With Error.zip](https://github.com/jgraph/drawio-desktop/files/9792105/File.With.Error.zip)

**Comment by Hamphrie** [comment]
I have changed a few things, it still doesn't work but if I add (opening brackets)/diagram(closing brackets) (opening brackets)/mxfile(closing brackets) the error changes to:

![image](https://user-images.githubusercontent.com/115879012/195997771-ab7eae1a-411e-48c5-8a0d-06efea341e4f.png)

**Comment by Hamphrie** [comment]
If I could get the file restored that would be great I have worked a long time in this file and would like if that effort was still there

**Comment by mararad** [comment]
Since you replied you managed to restore the file from a backup (DND-758) I'll close the issue.
