### ISSUE TITLE
Unable to open diagram

### ISSUE THREAD

**Issue by mistvan** [jgraph/drawio-desktop#1146]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Unable to open my older diagrams. Can open just recently created ones.

**To Reproduce**
1. Try to open this diagram https://performgroup-my.sharepoint.com/:u:/g/personal/miroslav_istvan_dazn_com/Eaus0O2MtXhPg76Rmav40wMBOb9xGZaRfYWCUv1qa2Dvlw?e=Py8AOe

**Expected behavior**
Diagram should be opened fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/814958/196617475-a3b3e4d0-8b71-4462-abbf-345110d98794.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.3.0

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
Nothing to add

**Comment by davidjgraph** [comment]
You're trying to open a diagram at a URL using the desktop version? That would never have worked.

**Comment by mistvan** [comment]
No, please download diagram from that ULR and try to open using standard File -> Open menu.

**Comment by mistvan** [comment]
It is fine to close this issue, as it was connected with syncing files to onedrive, so I was trying to open file which I didn't have locally, but on onedrive disk.
