### ISSUE TITLE
failed to add custom link to open local file.

### ISSUE THREAD

**Issue by cusber** [jgraph/drawio-desktop#1148]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
**failed to add link to open local file.**

**Expected behavior**
Really hope that in the next version, software could support file protocol.  
add custom link like this `file://***/***.pdf`   can open the local file  in system.
or at least tell me a method can similar do like this.  It borders me many days. 
Thanks ~

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.3.0

**Desktop (please complete the following information):**
Windows 10

**Comment by frankgerhardt** [comment]
I was looking for exactly this feature and can not believe that this is not implemented, just a link to another file!? And wontfix... I'd reopen this issue but I can not.

**Comment by davidjgraph** [comment]
Cool, please send in the PR with a full security review.

**Comment by davidjgraph** [comment]
File protocol is a security risk, this will not be implemented.
