### ISSUE TITLE
Can't "search-replace" by <nothing>

### ISSUE THREAD

**Issue by doej1367** [jgraph/drawio-desktop#1152]
### Preflight Checklist

* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

**Describe the bug**
A search'n'replace by <nothing> is not possible as a greyed out box does not permit it

**To Reproduce**
1. Go to `Ctrl`+`F`
2. Enter any string (e.g. ") into the 'Search Field'
3. Try to click on `Replace All`
4. You can't because it is greyed out

**Expected behavior**
Normally you can always use a search'n'replace feature to remove all occurrences of a string - here you can't

**Screenshots**
![grafik](https://user-images.githubusercontent.com/19228364/198360120-aa3ae096-037e-406c-b5b8-176dcdcadb3b.png)

**draw.io version:**
- draw.io version 20.3.0

**Desktop:**
 - OS: Windows 10

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
Thanks for the report

**Comment by davidjgraph** [comment]
In desktop release 22.1.18
