### ISSUE TITLE
Custom font does not stay when exporting a diagram

### ISSUE THREAD

**Issue by Kile** [jgraph/drawio-desktop#1153]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When using a custom font, then exporting the digram, the font has gone back to a default font.

**To Reproduce**
- Click on text
- Click on the font menu
- Click on "Custom.."
- Click on "Web Fonts"
- (In my case) enter some font name and for the url use [this](https://cdn-133.anonfiles.com/PcXdI9Edya/953d74e7-1666910547/keifont.woff)
- Write something in that font
- Export the digram as png or jpeg

**Expected behavior**
The png or jpeg has the written text in the specified font

**Screenshots**
The png or jpeg does not have the written text in the specified font

How the editor looked when I exported it:
![](https://cdn.discordapp.com/attachments/1035322027420168223/1035322282022797404/unknown.png)

Actual output: 
![](https://cdn.discordapp.com/attachments/1035322027420168223/1035322028112216074/unknown.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.3.0

**Desktop (please complete the following information):**
 - OS: MacOS Ventura on an M1 Pro

**Comment by e-nikolov** [comment]
In my case I am trying to use the Virgil web font - https://virgil.excalidraw.com/Virgil.woff2 and it also fails when exporting to PNG. I noticed some relevant errors in the Developer Tools:

> Refused to connect to 'https://virgil.excalidraw.com/Virgil.woff2' because it violates the following Content Security Policy directive: "connect-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com".


Looks like the security policy only allows custom fonts from Google.

**Comment by m-mohamedin** [comment]
Unfortunately, web fonts are not supported in desktop anymore due to security issues.
Google fonts are still available
