### ISSUE TITLE
Some suggestion for the latest Version 20.3.0 (Text Field, Icons, UX)

### ISSUE THREAD

**Issue by cxbignekoc** [jgraph/drawio-desktop#1155]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### **Would be cool add own icon sets**
- mybe related to #1124 

**Describe the solution you'd like**
"Add Icons" (maximum size 64x64, filetype: ico,png, svg,)
"Visit Flaticon" Link to a Website? Maybe
What i just found is you can just drop icons from flaticon into drow.io :) (with black background :/)

**Is your feature request related to a problem? Please describe.**
Not a Real Problem because you can add your Pictures as an Alternate

### **Would be nice to drop icons from the "More Shapes"-Window PopUp**

**Describe the solution you'd like**
This Window shows 
- bigger and 
- better scrollable 
- and ALL Icons at once
- Also would be nice, if above Suggestion is implemented to Detach this Popup to a Second Screen or other Position

**Is your feature request related to a problem? Please describe.**
Not a real Problem, but you have access to all Icons, instantly

### **Writing Text/ Field Access under an Icon is a bit cumbersome**

**Describe the solution you'd like**
- If you are zoomed out, the Blinking Line is close to the "Size-handles" and "binded-arrow-handles".
- Maybe its possible to re-position the text field a bit or
- add a Text-Field in the TEXT-Sidebar as well, so you never can accidently click wrong.
- This Sidebar Field should contain all editable features.
- Detach Text Field from Icon-edits

**Is your feature request related to a problem? Please describe.**
Yes, to get access to the Textfield again it can happens a misclicking behaviour to handles,
because the handles are also visible when text mode is active
Access the Text field is blocked, so you need multiple clicks to get into Text Edit Mode

[ ] | ### **Edit a market Text in a Textfield should have instant Edit-possibillities (bold, italic, underlined)**

**Describe the solution you'd like**
Its better to connect marked Text instantly with Text Edit Features, what else you wanna do?
Sure you have the Sidebar as well, but mostly i think you wanna resize, bold or change a bit the style or underline it imho*

**Is your feature request related to a problem? Please describe.**
no, or maybe related to the accessabillity

### **"Arrow to Icon" binding should have bit more space to the Icons itself**

**Describe the solution you'd like**
To get a better look / difference between Icons and Arrows i want to suggest that arrows are not too close to Icons.
so i suggest to have a round not rectangle based arrow-binding to icon-system

**Is your feature request related to a problem? Please describe.**
no, just for a better look

Thanks and Respect
cheers*

**Comment by davidjgraph** [comment]
Thanks for the details. It would be very useful if you could split these into one issue per issue. github doesn't have the concept of sub-issues, tracking these will be very hard in a single thread.
