### ISSUE TITLE
Embed from file in Word does not update from sources

### ISSUE THREAD

**Issue by eried** [jgraph/drawio-desktop#1156]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

The embeded elements cannot be updated.

Word 2209 (latest from 365 subscription), Windows 10 21H2

1) Open draw.io sidebar in Word and "Pick Device File"
2) Select a .drawio file and click "Insert"
3) Modify the .drawio file 

Try to update the diagram in Word with "Update All" -> does not work, select the diagram and click "Edit selected" gets an error message:
![image](https://user-images.githubusercontent.com/1091420/199518270-ef9f975e-d5f1-4a5b-a6c7-4ee67fb30f77.png)

**Comment by m-mohamedin** [comment]
Unfortunately, device files cannot be updated due to security restrictions.

We only have access to the file at the insertion time. So, to update a device file, you need to insert it again.
