### ISSUE TITLE
MS Store client stays open in the background, uses a lot of CPU and RAM after a while

### ISSUE THREAD

**Issue by o-l-a-v** [jgraph/drawio-desktop#1160]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

I made some diagrams two days ago, then closed Draw.io. Left my PC on for other reasons, today when I got back to it the fans are ramped up. Then I see Drawio / Diagrams running in the background with constant high CPU and RAM

![image](https://user-images.githubusercontent.com/6450056/200508792-e55bfcac-e22d-43c3-b9d7-0fe43522a659.png)

**To Reproduce**

I'm having a hard time to find out what exact steps must be done in order to reproduce it, but what I did was:

* Use the Microsoft Store Diagrams app
* Close it.
* It will take more and more CPU and RAM as time goes.

**Expected behavior**

No reason for it to run after it's closed.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

20.2.3.0

**Desktop (please complete the following information):**

Windows 10 22H2 19045.2130,

**Comment by tianq02** [comment]
I have the same issue. I just finished drawing and closed the program and suddenly the fan spins wildly. What's even stranger is that I see in Task Manager that the program's 6 processes used up all the CPU resources, and 6 happens to be the number of CPU cores I have. It feels like it's mining.
![image](https://user-images.githubusercontent.com/94333179/208069909-822191fd-a686-480a-8df0-1f040e1dab79.png)
This doesn't happen all the time. In my case, The program is closed after running a day or so, can that be a problem?

**Comment by davidjgraph** [comment]
Is this using 20.2.3 from the MS store? It should update to 20.6.2, see if that improves it.

**Comment by o-l-a-v** [comment]
v20.6.2 did not get pushed by Microsoft Store before now. I'll test it and write here if the problem persists.

**Comment by davidjgraph** [comment]
Closing. If someone can still repeat, please open new ticket.
