### ISSUE TITLE
JavaScript Crash

### ISSUE THREAD

**Issue by fpozatto** [jgraph/drawio-desktop#1161]
OS: Windows 10, x64
Draw.io: 20.3.0

I keep getting this error
![image](https://user-images.githubusercontent.com/102676879/200617471-7b30c05e-d508-473f-b12f-febb6f5b1f34.png)

I can't really pin point what generates it. It seems quite random, depending of several aspects, but mostly on saving.
Started several days ago. Tried to re-install, without success.

While editing any diagram, the error appears randomly, I click OK and keep working. It doesn't seem to affect the functionality at any way, just need to keep clicking OK to continue.

Regards

**Comment by ghost** [comment]
我也遇到了相同的问题

**Comment by aslan-im** [comment]
Have the same issue

**Comment by davidjgraph** [comment]
Please try 20.6.1

**Comment by fpozatto** [comment]
Thanks @davidjgraph . Good job, seems to be solved.
