### ISSUE TITLE
Missing X server or $DISPLAY

### ISSUE THREAD

**Issue by 2pc** [jgraph/drawio-desktop#1162]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

**To Reproduce**
```
ubuntu:~# sudo dpkg -i drawio-amd64-20.3.0.deb 
(Reading database ... 92170 files and directories currently installed.)
Preparing to unpack drawio-amd64-20.3.0.deb ...
Unpacking draw.io (20.3.0) over (20.3.0) ...
Setting up draw.io (20.3.0) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for shared-mime-info (1.15-1) ...
ubuntu:~# drawio
[1109/143750.469308:FATAL:electron_main_delegate.cc(297)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap (core dumped)
ubuntu:~# drawio   --no-sandbox
[32082:1109/143802.180830:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[32082:1109/143802.180893:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
Segmentation fault (core dumped)
```
**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
 Ubuntu Server 20.04 LTS 64bit && drawio 20.3.0

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04 LTS 

**Additional context**

**Comment by davidjgraph** [comment]
"Running as root without --no-sandbox is not supported"

**Comment by champaanand** [comment]
@davidjgraph, I get the below error: 
[root@cas-centosl1 ~]# drawio --no-sandbox
[13922:0216/005448.268716:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[13922:0216/005448.268796:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
Segmentation fault

Could you please help on this issue.
Also can i launch the drawio from command line.

**Comment by davidjgraph** [comment]
Then your error is not the same one as this thread and is off-topic.
