### ISSUE TITLE
Scale svg not working from command line

### ISSUE THREAD

**Issue by lazee** [jgraph/drawio-desktop#1165]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
when exporting to a svg file, from a drawio document, the `--scale` option has no effect. This works for png and jpeg.
When exporting from the UI, and setting zoom level, scaling the svg works.

**To Reproduce**
1. This is tested on a Mac, hence the path to Draw.io
2. Save a drawio document to disk (eg : test.drawio)
3. From the command line run `/Applications/draw.io.app/Contents/MacOS/draw.io -x -f svg --scale 2.5 -o test.svg  test.drawio`
4. Open the svg in the browser. You will see that size is unchanged.
5.  But if you from the UI exports the diagram with 250% zoom, then the svg will be the expected size.

**Expected behavior**
I would have expected the svg to be 2,5 times the original size, where `--scale` wasn't used.

**Screenshots**
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/11016/198886489-8fc429b5-e65b-4ba9-9ef4-46ea242c2505.png">

The biggest svg, exported with 250% zoom from UI. The small image from command line with `--scale 2.5`. 

**draw.io version :**

- 20.3.0

**Desktop :**
 - OS: MacOS Monterey
 - Browser: Edge
 - Edge Version 107.0.1418.24

**Comment by m-mohamedin** [comment]
Thanks for the report, a fix will be available in the next release
