### ISSUE TITLE
Fonts in the GUI gets smeared up

### ISSUE THREAD

**Issue by michaelleepow90** [jgraph/drawio-desktop#1168]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The font on the GUI keeps getting smeared up. If I hover over it, it gets back to normal sharpness.

**To Reproduce**
1. Go to 'More Shapes'
2. Click on 'category'
3. Scroll down to 'other shape options'
4. The font starts to get blurry & distorted.

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.2.3

**Desktop (please complete the following information):**
 - OS: Windows.

**Additional context**
![Blurry Fonts](https://user-images.githubusercontent.com/25166581/203654554-7a6a6b15-b6aa-4927-a517-4c1ee706986b.png)

**Comment by mararad** [comment]
Please update and tell me if you see the same in desktop 20.3.0.
At my place in 20.3.0 all is good (OS: Win)
