### ISSUE TITLE
[feature] Remember last used folder on Linux

### ISSUE THREAD

**Issue by ebousse** [jgraph/drawio-desktop#117]
(moved from https://github.com/jgraph/drawio/issues/228)

When opening/saving/exporting a drawing, draw.io always opens the file opener in the home folder of the operating system, even just after opening a file.

Could maybe draw.io remember what was the last folder that was used while opening/saving/exporting?

**Comment by thekalinga** [comment]
This is a huge pain in the ass everytime we try to save

**Comment by davidjgraph** [comment]
Please avoid comments that do not add anything constructive. There is a thumbs up to indicate your vote.

**Comment by alderg** [comment]
The last folder is used for me on macOS. What operating system and version of draw.io are you using?

**Comment by davidjgraph** [comment]
You need to download the latest from https://github.com/jgraph/drawio-desktop/releases. Using the in-browser update versions won't give you this.

**Comment by thekalinga** [comment]
Apologies for my earlier language

> The last folder is used for me on macOS. What operating system and version of draw.io are you using?

Ubuntu 16.04 LTS

I open an existing file & tried saving it as another file, I am always taken to user home directory, not the directory in which the file thats currently open

**Comment by davidjgraph** [comment]
I guess the title needs changing

**Comment by ebousse** [comment]
Indeed thanks, I forgot to mention that I was using Fedora 30!

**Comment by Honghe** [comment]
Good feature request!
It is better that if draw.io Desktop can remember a list of recently exported directories.

**Comment by Honghe** [comment]
Good feature request!
It is better that if draw.io Desktop can remember a list of recently exported directories.

**Comment by ashrafteleb** [comment]
Last open, save, export folders are currently remember.

If there is an issue, please comment and we'll re-open
