### ISSUE TITLE
希望中文可以正确竖排

### ISSUE THREAD

**Issue by yamazakitouma** [jgraph/drawio-desktop#1172]
当前中文竖排的形式为将字体旋转 90° ，希望可以将字体正确竖排，使字体处于正确角度。

<img width="77" alt="image" src="https://user-images.githubusercontent.com/28669193/205007951-ec73808c-1c56-4b15-8e1f-7cd4c531cb42.png">

**Comment by lbcmiao** [comment]
drawio中所有东亚字符都做不到正确竖排，。不过文本量比较少的话可以自己手动逐字换行（enter键）来实现竖排。不要用自带那个文本编辑里面的垂直功能。

**Comment by cyhcyhhychyc** [comment]
Hope drawio can do more to support vertical text

**Comment by davidjgraph** [comment]
Duplicate of jgraph/drawio#4068 . Although earlier, we'll use the English version.

**Comment by wzj042** [comment]
新建一个窄于单个字的文本组件，直接输入就是竖排了

![Image](https://github.com/user-attachments/assets/65886b4f-acb0-4884-a118-3ce1c3626be4)
