### ISSUE TITLE
20.6 won't start after update anymore

### ISSUE THREAD

**Issue by Kurpanik** [jgraph/drawio-desktop#1174]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

1. After the update from my latest working version (not sure but I think it was 20.2.8) to the current release of 20.6, the application will not start anymore. It hangs in the screenshot below:
2. Uninstall & Reinstall doesn't help either

**Screenshots**
![grafik](https://user-images.githubusercontent.com/71767601/205283369-3a89f51f-1cd4-4069-93c6-ad963f5c2449.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by nijawang** [comment]
Have the same issue.

**Comment by TW96** [comment]
Same here. Also W10.

**Comment by peternormann** [comment]
I have the same issue using linux amd64 (debian package)

**Comment by davidjgraph** [comment]
Please thumbs up the original issue if your comment doesn't add any further information, "me too" comments aren't helpful.

**Comment by davidjgraph** [comment]
Please manually downgrade to 20.3.0 while we debug.

**Comment by akornatskyy** [comment]
similar issue with debian bullseye linux.

**Comment by davidjgraph** [comment]
Fix in 20.6.1
