### ISSUE TITLE
Incorrect behaviour of "Autosave" feature

### ISSUE THREAD

**Issue by max-che** [jgraph/drawio-desktop#1183]
### Preflight Checklist

* [х] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [х] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Incorrect behaviour of "Autosave" feature

**To Reproduce**
1. Enable "Autosave"
2. Create new diagram
3. Save it
4. Make any change
5. Notification "Saving..." appears
6. See notification "The file has been modified. Click here to synchronize. (function(){...." - see screenshot
7. Click this notification to sync file
8. Nothing happens, notification stays, file is not saved

**Expected behavior**
1. The autosave should auto save document without additional user action for it
2. Notification "Click here to synchronize" should execute sync action
3. Notification should not contain confusing code fragments

**Screenshots**
![image](https://user-images.githubusercontent.com/6055596/206707616-172d1889-aa31-41d4-8f91-1477923e8762.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.6.1

**Desktop (please complete the following information):**
 - OS: Windows 10.0.17763 LTSC x64

**Comment by davidjgraph** [comment]
Which windows binary is this?

**Comment by max-che** [comment]
x64
