### ISSUE TITLE
The latest version draw.io sketch theme bug

### ISSUE THREAD

**Issue by ghost** [jgraph/drawio-desktop#1184]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Sorry, I didn't find the real bug before, now I found it, thought that my drawio has always been sketch theme, resulting in opening the default followed by new is sketch mode, the latest version of sketch theme after opening all UI components disappeared, no draw.io close button. Drawing cannot be implemented, other themes can be used.

https://user-images.githubusercontent.com/80820992/206737475-7f10e7df-1960-4fe1-ac21-2bff06d80543.mp4

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...

**Additional context**

**Comment by davidjgraph** [comment]
"You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed."
