### ISSUE TITLE
The latest version sketch theme is wrong

### ISSUE THREAD

**Issue by ghost** [jgraph/drawio-desktop#1185]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
After opening the latest version of draw.io sketch theme, all UI components disappear, drawing operations cannot be performed, the software cannot be closed normally, and other themes can be operated
**To Reproduce**
1. Switch to the sketch theme
2. Reopening the drawio interface shows blank, without any function

**Expected behavior**
 Reopening the drawio interface shows blank, without any function

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.6.1

**Desktop (please complete the following information):**
 - OS: [win11]
 - Browser [chrome]

https://user-images.githubusercontent.com/80820992/206748889-77dba229-437d-41bc-a3ca-289c57f6ceb1.mp4

**Additional context**

**Comment by davidjgraph** [comment]
Use the "sun" icon top-right to change to simple theme. I can't repeat this with the theme menu.
