### ISSUE TITLE
Problems with commandline export as svg

### ISSUE THREAD

**Issue by thekalinga** [jgraph/drawio-desktop#119]
The svg exported from terminal should match what we export from the UI, which is not the case now

Attached the sample drawio file, commandline exported svg & ui exported svg

Here are the problems with commandline export

1. The dimensions of the svg objects are outside the bounds of the svg image
2. The text is completely missing
3. There are breaks in the lines which are not present in the original image

Opened the commandline exported svg in inkscape to clearly see the issue

Command used to export as svg: `draw.io -x -o commandline-export.svg test.drawio`
Platform: `Ubuntu 16.04.6 LTS`
Drawio: `10.8.0`

[issue.zip](https://github.com/jgraph/drawio-desktop/files/3369027/issue.zip)

**Comment by alderg** [comment]
Commandline-export.svg and ui-export.svg look exactly the same for me in Chrome. We're using foreignObject for the labels, try using a viewer that supports that.

**Comment by thekalinga** [comment]
Its not completely true. As per this recommendation, the export should behave exactly the same

https://desk.draw.io/support/solutions/articles/16000042487-why-does-the-text-of-svg-export-sometimes-not-display-correctly-in-ie-and-some-svg-editors-

**Comment by thekalinga** [comment]
Gap in inkscape

![gap](https://user-images.githubusercontent.com/452518/60822129-7af33f80-a1c2-11e9-9808-925fb362b9c5.png)

Alignment in inkscape

![alignment](https://user-images.githubusercontent.com/452518/60822130-7b8bd600-a1c2-11e9-8d6f-87401689d2cc.png)

Looks like the text was missing because wordwarp was enable for the text. If fixed that in this newer version of the image

[issue-v2.zip](https://github.com/jgraph/drawio-desktop/files/3369085/issue-v2.zip)

**Comment by davidjgraph** [comment]
And in Chrome?

**Comment by thekalinga** [comment]
Here is the ui exported version

No Gap

![no gap](https://user-images.githubusercontent.com/452518/60822366-ef2de300-a1c2-11e9-80a0-7d8ca7a98a13.png)

No alignment issue within svg bounds

![ui-export-alignment](https://user-images.githubusercontent.com/452518/60822367-ef2de300-a1c2-11e9-9447-e91f1073d45b.png)

> And in Chrome?

Both look the same. No break in lines & Alignment is something I can verify as it does not have the notion of bounds (if I open raw svg directly AFAIK)

**Comment by davidjgraph** [comment]
Does the exported SVG have the gap and alignment issues when opened in Chrome?

**Comment by thekalinga** [comment]
> Does the exported SVG have the gap and alignment issues when opened in Chrome?

Both look the same. No break in lines & Alignment is something I can verify as it does not have the notion of bounds (if I open raw svg directly AFAIK)

**Comment by davidjgraph** [comment]
Both look the same as what? Please answer the question with a yes or no.

**Comment by thekalinga** [comment]
> Does the exported SVG have the gap and alignment issues when opened in Chrome?

No. I dont see any gap & alignment is not applicable in chrome (AFAIK). Overall answer NO

**Comment by thekalinga** [comment]
I just manually copy pasted the following two attributes from ui exported svg to commadline svg. Now, the overall svgs sits inside the view bounds

These are the attributes that are missing from the commandline exported svg

`width="1131px" height="521px" viewBox="-0.5 -0.5 1131 521"`

These are the original attributes on the commdline exported svg

```xml
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" style="left: 0px; top: 0px; width: 100%; height: 100%; display: block; min-width: 1132px; min-height: 522px;">
```

But, ui exported svg's attributes are (I removed few additional attributes for brevity)

```xml
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="1131px" height="521px" viewBox="-0.5 -0.5 1131 521" style="background-color: rgb(255, 255, 255);">
```

So, If commandline export can add the `width`, `height` & `viewBox` attributes to the exported svg, then atleast the bound issue will go away

**Comment by thekalinga** [comment]
@alderg 

> Commandline-export.svg and ui-export.svg look exactly the same for me in Chrome. We're using foreignObject for the labels, try using a viewer that supports that.

I dont think this is true w.r.t the commandline exported svg. As the exported xml does not contain any `foreignObject` elements (refer to `issues-v2.zip`)

**Comment by thekalinga** [comment]
Can you reopen the issue?

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
