### ISSUE TITLE
Window freeze focus change on windows desktop client

### ISSUE THREAD

**Issue by jstiops** [jgraph/drawio-desktop#1193]
Hi,
I'm using windows 10 on a powerfull laptop and having freezes with the draw.io desktop client everytime draw.io is minimized or another window gains focus. It's the only app with this problem. Everytime i return to the draw.io window, i have to wait 4-5 seconds before the gui reacts to anything. 
Any tips for troubleshooting this? I use the browser for now, but i would like to make the desktopclient workable as well.

using version 20.6.2 
autosaving disabled.
2 dual core 2.6GHz , 16GB RAM, SSD storage.

**Comment by davidjgraph** [comment]
Which binary are you using?

**Comment by jstiops** [comment]
the one that comes with the windows installer

**Comment by davidjgraph** [comment]
which windows installer?

**Comment by jstiops** [comment]
one like draw.io-20.6.2-windows-installer.exe , auto-updated over time offcourse. 
reinstalled several times to see if that would help, but it did not.

**Comment by jstiops** [comment]
sigh.... 
i upped my google-fu a bit and stumbled upon this:
https://github.com/microsoft/vscode/issues/146737

somewhere it was suggested to clear the folder C:\Users\username\AppData\Roaming\draw.io 
so i uninstalled. removed the draw.io folder completely, reinstalled, and now i have no freezes whatsoever!

**Comment by davidjgraph** [comment]
OK, thanks for the tip, that's useful.
