### ISSUE TITLE
Attrib.exe has been denied access

### ISSUE THREAD

**Issue by Rainmaker52** [jgraph/drawio-desktop#1194]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
My desktop has the Windows 10 feature enabled for "Controlled Folder Access". I've given draw.io access to write to the directories in question. However, since upgrading to 20.6.2, I'm getting warnings about attrib.exe trying to modify files in controlled folders whenever I put the draw.io window in focus.

I've searched the code for any reference to attrib.exe, but cannot find any. Possibly this is caused by a supporting library?

Using Procmon, I've managed to capture the execution. The parent PID here (24244) is cmd.exe, which unfortunately does not report a parent PID itself within the procmon output.

This happened directly after installng a new version of draw.io. I do not remember the earlier version, but it was a while since I updated.

Parent PID: 24244, Command line: attrib  +h K:\Data\Documents\Klanten\Nederland\MyCust\.$Tekeningen.drawio.bkp, Current directory: C:\Programs\draw.io\, Environment: 
	=C:=C:\Programs\draw.io
	ALLUSERSPROFILE=C:\ProgramData
	APPDATA=C:\Users\Roel Brook\AppData\Roaming
	CommonProgramFiles=C:\Program Files\Common Files
	CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
	CommonProgramW6432=C:\Program Files\Common Files
	COMPUTERNAME=HP360
	ComSpec=C:\WINDOWS\system32\cmd.exe
	DriverData=C:\Windows\System32\Drivers\DriverData
	HOMEDRIVE=C:
	HOMEPATH=\Users\Roel Brook
	JAVA_HOME=C:\Program Files\Microsoft\jdk-11.0.15.10-hotspot\
	LOCALAPPDATA=C:\Users\Roel Brook\AppData\Local
	LOGONSERVER=\\HP360
	NUMBER_OF_PROCESSORS=8
	OneDrive=C:\Users\Roel Brook\OneDrive
	OnlineServices=Online Services
	ORIGINAL_XDG_CURRENT_DESKTOP=undefined
	OS=Windows_NT
	Path=C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin;C:\Program Files\Microsoft\jdk-11.0.15.10-hotspot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\PowerShell\7\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X64\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X86\;C:\Program Files (x86)\Common Files\Pulse Secure\TNC Client Plugin\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\Docker\Docker\resources\bin;C:\Users\Roel Brook\.cargo\bin;C:\Users\Roel Brook\AppData\Local\Microsoft\WindowsApps;;C:\Programs\Microsoft VS Code\bin;C:\Users\Roel Brook\.dotnet\tools;C:\Program Files\Azure Data Studio\bin
	PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
	platformcode=AN
	POWERSHELL_DISTRIBUTION_CHANNEL=MSI:Windows 10 Pro
	PROCESSOR_ARCHITECTURE=AMD64
	PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
	PROCESSOR_LEVEL=6
	PROCESSOR_REVISION=8e0c
	ProgramData=C:\ProgramData
	ProgramFiles=C:\Program Files
	ProgramFiles(x86)=C:\Program Files (x86)
	ProgramW6432=C:\Program Files
	PROMPT=$P$G
	PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
	PTSMINSTALLPATH=c:\Program Files\HP\HP ProtectTools Security Manager\Bin\
	PTSMINSTALLPATH_X86=C:\Program Files (x86)\HP\HP ProtectTools Security Manager\Bin\
	PUBLIC=C:\Users\Public
	RegionCode=EMEA
	SESSIONNAME=Console
	SystemDrive=C:
	SystemRoot=C:\WINDOWS
	TEMP=C:\Users\Roel~1\AppData\Local\Temp
	TMP=C:\Users\Roel~1\AppData\Local\Temp
	USERDOMAIN=HP360
	USERDOMAIN_ROAMINGPROFILE=HP360
	USERNAME=Roel Brook
	USERPROFILE=C:\Users\Roel Brook
	windir=C:\WINDOWS
	ZES_ENABLE_SYSMAN=1
	__PSLockDownPolicy=0

**To Reproduce**
1. Enable folder protection
2. Create a drawing in a protected folder
3. Allow draw.io to write, but don't allow other applications.

**Expected behavior**
I would expect "hiding" a backup file to be done using system calls, not by running external processes.

**draw.io version (In the Help->About menu of the draw.io editor):**
20.6.2

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by tkonsta** [comment]
I experience the same problem. I see two workarounds, which however both are not really appealing:
- Save the file in a different location, which is not protected => Then I need to come up with some directory only for drawio files, which then are not automatically backed up etc. 
- Add an exception for attrib.exe => This however decreases the security of the system and could be misused for data corruption (e.g. ransomware)

**Comment by davidjgraph** [comment]
We don't have anything constructive to add here. We'll leave the conversation unlocked, but unsubscribe.

**Comment by richlv** [comment]
As the original reporter stated,

> I would expect "hiding" a backup file to be done using system calls

Currently draw.io is flagged by various security solutions. Would it be possible to change to syscalls to avoid that?
