### ISSUE TITLE
Scale (zoom) the size of shapes in the Shape Menu

### ISSUE THREAD

**Issue by christianitis** [jgraph/drawio-desktop#1195]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Some shape sets (in my case, namely the Sitemap shapes) appear too small in the shape menu on the left. It's hard to see the content of some shapes.

**Describe the solution you'd like**
The ability to dynamically zoom in/scale the shape menu to increase the size of the shape previews.
For example, to increase the size of the shapes in the menu; a user would:
1. Hover the mouse over the shape menu.
2. CTRL-Mouse Wheel to scroll in and out, increasing or decreasing the scale of the shapes.
3. Shapes at the end of a row would automatically overflow to the next row (and vice versa) if they become too big to fit, which is identical to what happens when the width of the shape menu is adjusted using the bar on the right of the shape menu.

**Describe alternatives you've considered**
1. A range slider, a number input, or even just buttons to increase/decrease the scale in the shape menu.
2. An option in the toolbar ribbon to increase/decrease the scale of shapes in the shape menu.

**Additional context**
I'm using a 23.6 inch 1920x1080 display.

**Comment by jeliker** [comment]
I completely agree the shape rendered image size is far too small. See below example (consider the menu font in my screenshot for comparison of what's "normal" text size).

I am using macOS with Retina desktop resolutions. Perhaps that is the gap (the desktop app doesn't properly interpret Retina scaling?).

If not the option for zoom suggested here, at least a preferences setting for what zoom level to display shapes would make a huge difference.

![drawio_shapes_too_small](https://github.com/jgraph/drawio-desktop/assets/590333/7056aceb-7b74-4eb6-94a0-4cfa840e6017)

**Comment by rinze24** [comment]
I have similar problem with Windows installation, too small shapes.

Workaround:

Extras -> Configuration
```
{
  "css": ".geSidebar { zoom: 160% !important }"
}
```

**Comment by jeliker** [comment]
> I have similar problem with Windows installation, too small shapes.
> 
> 
> 
> Workaround:
> 
> 
> 
> Extras -> Configuration
> 
> ```
> 
> {
> 
>   "css": ".geSidebar { zoom: 160% !important }"
> 
> }
> 
> ```

Wonderful! That is a great suggestion and works beautifully. Thank you!
