### ISSUE TITLE
Associate (.drawio) extension with file drawio desktop editor (win 10)

### ISSUE THREAD

**Issue by Diaskhan** [jgraph/drawio-desktop#120]
Is possible when installing drawio associate (.drawio)  files with editor ?
windows 10 
----------edited
I guesse is dubl
https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5

**Comment by Diaskhan** [comment]
I guesse is dubl
https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5

**Comment by Diaskhan** [comment]
But there is another problem why associate extension not fully work !
Step to reproduce
1.
![image](https://user-images.githubusercontent.com/15046677/60836366-5b224280-a1e7-11e9-8fcc-77630e684025.png)
2.
![image](https://user-images.githubusercontent.com/15046677/60836440-7db45b80-a1e7-11e9-9039-154571a8b8e7.png)

3.
![image](https://user-images.githubusercontent.com/15046677/60836469-90c72b80-a1e7-11e9-96f2-951eecc61645.png)

When Diagram is saving is saving without extension
![image](https://user-images.githubusercontent.com/15046677/60836506-a6d4ec00-a1e7-11e9-8a46-5258b92da281.png)

**Comment by davidjgraph** [comment]
So, you're saying we should not allow users to delete the .drawio suffix when saving?

**Comment by Diaskhan** [comment]
![image](https://user-images.githubusercontent.com/15046677/60880808-30c39a00-a266-11e9-88b8-9753157806b8.png)

As u See there have filter type.
After pressing save Program appends the extension if there no extension
![image](https://user-images.githubusercontent.com/15046677/60880877-581a6700-a266-11e9-8f91-7e7c1f50ad34.png)

**Comment by Diaskhan** [comment]
Somebody Could tell me where is Electron specific code that handles saving file ?
or Saving a file is  browser specific code ?

![image](https://user-images.githubusercontent.com/15046677/65185239-f3129700-da88-11e9-8658-e82d693248d7.png)

**Comment by Diaskhan** [comment]
Could Somebody give advice or show this code ?
