### ISSUE TITLE
drawio-desktop will cause embedded Visio graph in Word document can't be edited in place?

### ISSUE THREAD

**Issue by yingang** [jgraph/drawio-desktop#1200]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
After installed drawio-destkop, it's found that some embedded Visio graphs in Word documents won't be able to be edited in place:
- Normally, when I choose a such graph, the status bar of Word will prompt something like "double click to edit Microsoft Visio graph"
- While in my case, when I did that, it only prompt like "double click to edit Unknown" and if I double clicked it, it would prompt an error like "can't find application, source file ..." (see the later attached screenshots please, it's in Chinese although)

**To Reproduce**
(No need to do anything special for drawio-desktop)
1. Create a new Word document
2. Embed a Visio graph in it and then close the document
3. Re-open the file, double click the embedded Visio graph (have attached one test file in the last part of this post)

**Expected behavior**
An installed drawio-desktop won't interfere with any co-existing Visio application behaviour.

**Screenshots**

The status bar in Word after choosing the embedded Visio graph:
![image](https://user-images.githubusercontent.com/1246410/209256892-1cb8533c-22bd-452c-8f66-d7264650c125.png)

After double-clicking the embedded Visio graph:
![image](https://user-images.githubusercontent.com/1246410/209256867-248b9f2d-6869-4a65-ba7b-60fd991d06a9.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.3.0

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Office 2016

**Additional context**

This is a Word file that has embedded two Visio graphs:
[Test.docx](https://github.com/jgraph/drawio-desktop/files/10291531/Test.docx)

To be noticed: the first graph is in 2003-2010 format and looks like it survived while the second one is in latest format and it failed to survive.

**Comment by davidjgraph** [comment]
You need to remove the file association of .vsdx files with the draw.io app in the operating system.

**Comment by yingang** [comment]
Thanks for your response. Could you please provide more detailed instructions?

Just tried to set the default application for .vsdx type in my Win10 box to Visio 2016, the problem still exists.

Also, wondering if drawio-desktop would provide some extra installation options to avoid this conflict? like avoid assocaiting .vsdx file type?
