### ISSUE TITLE
draw.io desktop在windows系统如何启用外部插件？（draw.io desktop How do I enable external plugins on windows?）

### ISSUE THREAD

**Issue by zhangjx007** [jgraph/drawio-desktop#1201]
draw.io desktop在windows系统如何启用外部插件？
![image](https://user-images.githubusercontent.com/110375200/210038667-9645f36f-96f9-4a0e-9a20-13d6ee5b46ae.png)

**Comment by Jeangowhy** [comment]
On windows system:

   .. code:: bash

      ./draw.io.exe --enable-plugins
