### ISSUE TITLE
Hi,please help restore original file by BKP file.

### ISSUE THREAD

**Issue by suyu15** [jgraph/drawio-desktop#1205]
Hi,

Can you help me restore my work by bkp file?

[mysql.drawio.bkp](https://github.com/BinLee218/suyu/blob/main/~%24mysql.drawio.bkp)

**Comment by davidjgraph** [comment]
The content is all zeros, there's nothing in here.

**Comment by suyu15** [comment]
Thank you. 
But I don't know why there is nothing in it. 
This is the only backup file I can find. And it shows 30MB.
