### ISSUE TITLE
The exported PDF file doesn't keep the infill with a type other than "Solid" to be vectorized

### ISSUE THREAD

**Issue by FallAndFarewell** [jgraph/drawio-desktop#1210]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

The exported PDF file doesn't keep the infill with a type other than "Solid" to be vectorized, checked using both Acrobat Reader and SumatraPDF.

I'm currently working on a project to convert drawio files to SVG files while keeping most of its layout and look, it utilizes the exported pdf, which keeps most elements in place and has no SVG 1.1 warning, then the pdf file will be converted to SVG using Inkscape. 

During my test, the directly exported SVG files can't preserve the icons from "Allied Telesis" group and are not friendly enough for some image viewers or Microsoft Word, direct exporting is not an option in this case.  

Using the PDF files seems can get this job done. But when working with shapes that have a non-solid infill, the infill gets rasterized in the exported PDF file compared to the exported SVG file. Although this won't cause much trouble in most cases, I'm assuming the vectorized infill is implemented by design,  but for some reason, it missed out when exporting as PDF. It would be best If this issue can be fixed.

Anyway, thank you for your work to make this excellent software.

Update:
Enabling the "sketch" option can result in a correct PDF output, and setting "jiggle=0" can make infill lines straight, but the hatch lines write out of the box.

**To Reproduce**
1. Open Draw.IO and create an empty graph
2. Drag and drop a rectangle onto the graph
3. Select the rectangle, change the fill type to anything other than "Auto" or "Solid", and set the infill to be colored for an easy visual check.
4. Export both SVG and PDF files.
5. In the SVG file, both the edges and infill are kept vectorized, but in the PDF file, only the edges are vectorized, and the infill gets rasterized.

**Expected behavior**
The exported PDF file should keep infill vectorized as in the exported SVG file.

**Screenshots**
![rasterized infill](https://user-images.githubusercontent.com/61380342/211418488-3666ba02-96a5-4bfa-b302-acbe380ce801.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.7.4

**Desktop (please complete the following information):**
 - OS: Windows10 21H2

**Comment by davidjgraph** [comment]
Is the PDF from app.diagrams.net better?

**Comment by paloha** [comment]
@davidjgraph No, the exported pdf from app.diagrams.net looks the same.

**Comment by davidjgraph** [comment]
We don't have any solution to this.

**Comment by carlobrok** [comment]
Is this going to be fixed at some point? 
For me using v27.0.9 it still looks as described in this issue:

![Image](https://github.com/user-attachments/assets/4102fc08-76cd-4d5b-9a71-c6d41d0313f5)

**Comment by powejam** [comment]
Problem still exists in august 2025. Is no-one else complaing about this??
