### ISSUE TITLE
Let export a diagram as a figure but including a custom watermark

### ISSUE THREAD

**Issue by manueljordan** [jgraph/drawio-desktop#1213]
For any diagram created by this wonderful tool, when is the time to export it as a figure based in any format - pls could you consider to add the option to add a custom watermark?

Thanks in advance

**Comment by davidjgraph** [comment]
Add some text in a specific layer and reduce the text opacity?

**Comment by manueljordan** [comment]
Is there a link from the official documentation to learn that approach and let me test it?

**Comment by davidjgraph** [comment]
No, we don't have any documentation.
