### ISSUE TITLE
Colour of default action button wrong

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio-desktop#1219]
20.8.14 univeral dmg on MacOS 13.1 (dark mode) on M1.

<img width="426" alt="Capture d’écran 2023-01-31 à 21 54 12" src="https://user-images.githubusercontent.com/1761087/215892590-13e525f3-2b83-46e2-ac55-f7dd7c136f92.png">

**Comment by alderg** [comment]
Fixed https://github.com/jgraph/drawio-dev/commit/106d52402a0346db36f566459dcf6d23b2d21c7e
