### ISSUE TITLE
Expressions!!!

### ISSUE THREAD

**Issue by VasigaranAndAngel** [jgraph/drawio-desktop#1221]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am looking for a big feature which is expressions. In excel sheets we can use formulas to calculate values. like in excel, it would be very useful if draw io can also do that.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/72515046/216129104-f1ae7415-c29d-4f7f-9038-1228a9779cac.png)
In this, all the values are depending on the starting value. so if I need to change the starting value I have to recalculate and change all the following values 🥴. and this is only a small part of my graph.

**Describe alternatives you've considered**
Manually calculating and changing all the values.

**Additional context**

**Comment by davidjgraph** [comment]
Thanks for the suggestion, but I view this as outside the scope of this project.
