### ISSUE TITLE
Ability to exit/close the application from within the application

### ISSUE THREAD

**Issue by pv4** [jgraph/drawio-desktop#1222]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Hello! I just installed draw.io 20.8.10 on linux and it appears to miss exit/close menu entry/button present in all other applications I have. When I choose "Close" from "File" menu it does not close the application, but instead suggests opening/creating a new diagram.

**Describe the solution you'd like**
It would be great to either have "Quit" menu item in "File", as in most of other apps, or to have a separate close button somewhere in the interface.

**Describe alternatives you've considered**
I was able to close draw.io using xkill but I think it's wrong. It's still convenient for many people (at least among those who I personally know) to have close/exit function inside an application itself without relying on external tools like xkill (unix) or process manager (windows).

**Comment by marcaurele** [comment]
I have the same issue on my side using i3 under Linux. I have to force kill the application. The `close` action only gets the user to the _create/open_ diagram dialog, and there is no option to close the app.

**Comment by m-mohamedin** [comment]
Will be added to the next release.
Currently, the app can be closed using the window close button and keyboard shortcut (OS depependent)

**Comment by davidjgraph** [comment]
In desktop release 22.1.18
