### ISSUE TITLE
Pins in Electrical shapes not center aligned on grid making strictly horizontal/vertical connection line difficult

### ISSUE THREAD

**Issue by erusyd** [jgraph/drawio-desktop#1223]
The pins in a lot of symbols in Electrical shapes, i.e. Electrical/Transistors, are not center aligned on grid(I change the grid to 1pt):
![image](https://user-images.githubusercontent.com/1529102/216501664-80666117-96df-44a8-ab67-05041afc8a17.png)
This makes the connection line between different symbol's pin not strictly horizontal or vertical.
Is there any way to modify the symbol in the library(for example, ungroup the symbol first and edit each element)?

**Comment by Bochets34** [comment]
Hello, how did you fix this ?

**Comment by erusyd** [comment]
I switch to other tools, i.e. inkscape, xcircuit.

**Comment by erusyd** [comment]
> Hello, how did you fix this ?

I switch to other tools, i.e. inkscape, xcircuit.
