### ISSUE TITLE
Desktop App Loading Diagrams from Drive

### ISSUE THREAD

**Issue by weiserhase** [jgraph/drawio-desktop#1230]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
The Desktop app should be able to open diagrams from Google Drive

**Describe the solution you'd like**
There should be an integration to enable opening files from Google drive

**Comment by davidjgraph** [comment]
Duplicate of #950

**Comment by weiserhase** [comment]
Sorry for the confusion 😬
