### ISSUE TITLE
I can't open rtsp://address video_stream protocol

### ISSUE THREAD

**Issue by igor9105** [jgraph/drawio-desktop#1231]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Hi! I can open rtsp://... link from any program, like OpenOffice, LibreOffice also from terminal and any others, but I can't start rtsp:// stream from drawio-desktop.AppImage
I had read some recomendations from #1009, rewrite source code and rebuild app, but rtsp:// is not custom protocol, it's like https:// or ftp:// but for streams.

**To Reproduce**
1. Make link `rtsp://user:password@192.168.0.2/`
2. Click on the link.
3. Nothing.

**Expected behavior**
Behavior like click on https:// link start browser, click on rtsp:// link start my default program and open video stream. 

**Screenshots**
![Screenshot_20230210_101043](https://user-images.githubusercontent.com/12896340/218030335-8414299e-d32f-4cf6-b28c-418ea7de65df.png)

**draw.io version (In the Help->About menu of the draw.io editor):
diagrams.net 20.8.16

- draw.io version x.y.z
drawio-x86_64-20.8.16.AppImage
**Desktop (please complete the following information):**
 - OS: Manjaro Linux

**Additional context**
Appreciate any help.

**Comment by davidjgraph** [comment]
This is expected. We would need to understand the security consequences of this allowing links in this protocol and we just don't.
