### ISSUE TITLE
Add Neural Network Gallery

### ISSUE THREAD

**Issue by jiaqiwang1212** [jgraph/drawio-desktop#1233]
During my dissertation, I often had to use plots of neural networks, e.g.
![image](https://user-images.githubusercontent.com/40316182/218250514-c05400af-f4ba-46d2-ab24-bac5d97f90df.png)
![image](https://user-images.githubusercontent.com/40316182/218250547-2e586939-73bc-4c1a-b8e0-576e7a53ca67.png)
and so on.
Can you  add this gallery please? It contains some of the smallest component units.
Thank you!!!

**Comment by mararad** [comment]
Hi,

Please send us the link to icons sets as well as the licenses for those sets.

Thanks,
