### ISSUE TITLE
mac app cant save, just does nothing. No error message.

### ISSUE THREAD

**Issue by nutmix** [jgraph/drawio-desktop#1234]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I am running an updated version of the local draw.io app on mac osx Monterey
When I try to save, or save as, nothing happens, and nothing is saved.  
at the top it says "unsaved changes, click here to save".   when I click on this, nothing happens, and nothing is saved.

**To Reproduce**
1. create a new diagram
2. Click on save, or save as.
3. Notice notice that nothing is saved, no dialog pops up to allow save as.

**Expected behavior**
save as to popup a dialog to chose were to save.
save to actually save.

version: 20.8.16

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z
version: 20.8.16

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...
 - osx Monterey on apple silicon.

**Additional context**

**Comment by m-mohamedin** [comment]
Hi,

I've tried the same version on MacOS Ventura (13.2) and it works for me.

Can you try running it from a terminal `/Applications/draw.io.app/Contents/MacOS/draw.io` and open the "Developer Tools" (Help -> Open Developer Tools) then try to save. Any errors in the terminal or Developer console?

**Comment by davidjgraph** [comment]
Please check if the problem still occurs on latest version.

**Comment by hexerei** [comment]
Installed draw.io 22.1.2 on mac Monterey 12.7.1 and have the same behaviour, no saving mechanism works (save, save as, click on changes tooltip, export), no file browser is opened, but busy cursor pops up for a while and application stalls.

also tried starting from terminal, neither error messages in terminal, nor in developer tools console...

after restarting the issue was solved and I could save again.

what was different when it did not work:
- I opened draw.io wich displayed an unsaved diagram
- draw.io popup states there is a new version
- selected download and install
- download took to long, so i canceled the process
- could not save from draw.io anymore
- did manual installation of new version
- still could not save

only after restart issue was fixed.

**Comment by hexerei** [comment]
This is also related to any disk access e.g., export...

**Comment by fransf-wtax** [comment]
This seems to happen to me regularly when I've had draw.io open for a while.
Running v22.1.16 on macOS Monterey 12.2.1.

It seems like anything that needs to open a file system dialog to select a file or directory stops working:
- Open
- Save
- Save As
- Import...
- Export As...

**Comment by fransf-wtax** [comment]
Attempting to open Developer Tools gives me an error:

**A JavaScript error occurred in the main process**

Uncaught Exception:
TypeError: Object has been destroyed
at IpcMainImpl.<anonymous> (/Applications/draw.io.app/Contents/Resources/app.asar/src/main/electron.js:191:14)
at IpcMainImpl.emit (node:events:529:35)
at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86338)
at WebContents.emit (node:events:517:28)

**Comment by davidjgraph** [comment]
Please update to the latest version and see if the problem persists.

**Comment by Innoriam** [comment]
I first time installed draw.io desktop for macOS-Universal (v24.0.4) today and it seems this problem still exists. 

For me it appeared while exporting a file to pdf. I could change the name of the file but the save button wasn't activated and I could not click on any folder/file in the sidebar or folder window.
After some time and tapping out / doing different things the "Save" button was activated again and I successfully exported it.
System is Sonoma 14.4 (23E214)

**Comment by davidjgraph** [comment]
The problem in this thread is there isn't one report with the exact environment details. We can't investigate without that.
