### ISSUE TITLE
Missing icon when "Save as -> Editable Vector Image .svg"

### ISSUE THREAD

**Issue by saulogt** [jgraph/drawio-desktop#1236]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

Some icons do not appear in the svg file (Editable Vector Image)
The file generated contains a path to the icon file inside the app itself, which obviously will not work out of my computer.
```
...
<image x="-0.5" y="-0.5" width="50" height="41" 
xlink:href="file:///Applications/draw.io.app/Contents/Resources/app.asar/drawio/src/main/webapp/img/lib/mscae/Docker.svg"/>
...
```

**To Reproduce**
1. Search for "Docker" shape and add to the document
2. Save as "Editable Vector Image .svg" - *.drawio.svg
3. Open the svg file

**Expected behavior**
All icons should be displayable

**Screenshots**

<img width="993" alt="arquitecture2 drawio svg - diagrams net 2023-02-14 12-03-01" src="https://user-images.githubusercontent.com/8147068/218848821-b42c5d65-2dc1-4af2-931d-ab5081dd6e13.png">

![documentation at svg 2023-02-14 12-06-29](https://user-images.githubusercontent.com/8147068/218850027-3ce310de-25b8-4905-8956-4068e9b4030d.png)

**draw.io version:**

- draw.io version 20.8.16

**Desktop:**
 - OS: MacOS

**Additional context**
NA

**Comment by saulogt** [comment]
I found a similar issue in other repo, but the cause is different https://github.com/jgraph/drawio/issues/2763

**Comment by jan-hudec** [comment]
> I found a similar issue in other repo, but the cause is different [jgraph/drawio#2763](https://github.com/jgraph/drawio/issues/2763)

The workaround mentioned there is, however, just as applicable here—make the icons embedded.

I don't consider it a fix, because it requires going over all icons in the diagram, plus you don't really need to embed the images in the drawio document, only in the exported SVG.
