### ISSUE TITLE
 Color picker crash Drawio (Fedora 37/flatpak/Wayland)

### ISSUE THREAD

**Issue by gael-o0o** [jgraph/drawio-desktop#1237]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Each time I click on color picker, Drawio crash.

**To Reproduce**
1. Open a new diagram
2. Click to change color
3. Click on color picker
4. Drawio crash with the following first line : 
`com.jgraph.drawio.desktop.desktop[83811]: [2:0213/185139.183093:ERROR:shared_x_display.cc(39)] Unable to open display`

**Expected behavior**
Get the color picker

**draw.io version (In the Help->About menu of the draw.io editor):**
- diagrams.net 20.7.4
[coredump.txt](https://github.com/jgraph/drawio/files/10724914/coredump.txt)

**Desktop (please complete the following information):**
 - OS: Fedora 37 
- Drawio from flatpak **com.jgraph.drawio.desktop**   **20.7.4**   

**Additional context**
Wayland without X11

I can attach multiple coredump if it's usefull.

**Comment by gael-o0o** [comment]
Seems related to Flatpak version. 20.7.4 AppImage version doesn't crash.  20.8.16 AppImage neither

**Comment by davidjgraph** [comment]
We're not the authors of the flakpak version.
