### ISSUE TITLE
Questionnaires

### ISSUE THREAD

**Issue by mahjinkhai** [jgraph/drawio-desktop#1241]
Hi all,

I am proposing my company to use [draw.io](http://draw.io/) desktop app and these are the questionnaires from management and IT department, will be good if I have an expert here to help me with it.

Last external penetration test/vulnerability report
If required, can we run penetration tests ourselves against your platforms?
SOC2 Report
Cyber Essentials Report / Certificate
Data Protection / GDPR Policy
Do you conform to data protection frameworks to evidence your compliance?
Privacy Policy
Information Security Policy
Business Continuity Plan
Implementation process for the system, including responsibilities and estimated timescales for the completion of each stage
ICO registration number
Any purchase terms/terms and conditions/order forms etc. for our legal team to review if required.
Where our data is stored and processed
how our data is destroyed
What security standards do you conform to or comply with? ISO27001, ISO27017, ISO27018, SOX, FedRAMP etc.?

What control frameworks do you use? (e.g., ISO27002, NIST SP800, CSF etc.?)

Our usual expected baseline is:

Authentication by SSO from Azure AD
User management – Users should be provisioned and deprovisioned by SCIM from Azure AD - [What is automated app user provisioning in Azure Active Directory | Microsoft Docs](https://docs.microsoft.com/en-us/azure/active-directory/app-provisioning/user-provisioning)
IPv6 Support
For browser based services we expect them to use Microsoft Edge with Tracking Prevention and Enhanced Security set to Strict
For installed applications we expect
For Windows - apps that can be deployed via MSI from Microsoft Endpoint
For MacOS - apps that can be deployed via DMG/PKG from Microsoft Endpoint
For Mobile Apps - Apps that can be secured with a Microsoft Endpoint App Protection Policy/Azure AD Conditional Access Policy
Do you support this baseline (and can you provide links to your implementation guidelines and an estimate of the implementation time)?

If you don’t support SCIM, can you advise how the user lifecycle is managed, and how it can be automated.

If you don’t support SSO, can you advise:

What password policies can be set (length / complexity / expiry)
How MFA is implemented
How logins can be restricted by IP/Location/Device
Account recovery methods
How sessions are managed and if all sessions can be logged out globally
Web application compatibility - We use Microsoft Edge as our preferred browser,  . Will your site support these settings?

Network Requirements - We expect your application to be able to support clients using only IPv6.

**Comment by davidjgraph** [comment]
The problem here is this is a completely generic set of the questions. It would be a lot more managable if the set of questions were specific to a desktop application.

All the SSO and networking questions are N/A. The purchasing questions are N/A. Passwords, MFA, login, etc, etc.
