### ISSUE TITLE
Add a switch to determine whether to compress the content to one line.

### ISSUE THREAD

**Issue by 0400H** [jgraph/drawio-desktop#1242]
**Is your feature request related to a problem? Please describe.**
Status:
Client compress project's content to one line and save it file `xxx.drawio`.

Advantages:
Greatly compresses the file size of `xxx.drawio`, when just store it only for the latest version.

Disadvantages:
Disk space usage grows linearly when using version management tools(git).

**Describe the solution you'd like**
Add a switch, the user decides to enable structured storage or compressed storage.

**Additional context**
compressed storage：
![image](https://user-images.githubusercontent.com/16373603/220653481-5e0bdfaa-bd64-47ce-9477-8648fcd00b23.png)

structured storage：
When the version changes, only some changes need to be stored.
![image](https://user-images.githubusercontent.com/16373603/220653728-0867002e-0616-4355-bbc4-f76d8876c417.png)

**Comment by davidjgraph** [comment]
Closing, we no longer support compression of the format.
