### ISSUE TITLE
Cannot connect multiple connectors to a manually added connection point

### ISSUE THREAD

**Issue by hickeng** [jgraph/drawio-desktop#1245]
I believe this to be a recent regression as it was not an issue previously and I _have_ multiple connectors to one connection point from a prior edit which follow the object when it's moved correctly.

However I cannot replicate that with new connectors. Once one is snapped to a connection point I cannot get another to do so.

I don't know if it's relevant, but these are connection points I added myself to an image (on locations of ethernet ports on a chassis image). The image is part of a custom library.

Desktop application version `20.8.16`.

**Comment by stevewf** [comment]
Two workaround methods:
1) For the second connector, drag its connection point (the end) onto the outline of the object that you wish to connect to (not onto the connection point - onto the **outline** of the object) until the outline "lights up"; don't release the mouse button yet. Then, still holding the mouse button, drag the connector to the desired connection point. While dragging, avoid lighting up other things on the way to the connection point.

2) Temporarily "bring to front" the object to which you wish to connect (select object, menu:Arrange>To Front). Then connect your second connector. Then send the object back again.
