### ISSUE TITLE
Spell Checker shows red wavy lines for miss-spelled words, but right clicking on a word does nothing

### ISSUE THREAD

**Issue by TheOtherRealm** [jgraph/drawio-desktop#1246]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If you enable the Spell checker in Extras, it shows red wavy lines for miss-spelled words, but unlike in the browser version which has a built in checker, in the desktop version, right clicking on a word does nothing.  It would be great if there was a right clickable list of suggestions.  I know electron has spell check capabilities.

**To Reproduce**
1. Go to Extras and enable spell checking
2. Create a box and enter a wrongly spelled word
3. Right click on the red wavy line
4. Nothing happens

**Expected behavior**
A menu box should open like it does in the browser (obviously in the browser it is the browser that is doing it)

**Screenshots**
NA (it is an lack of anything happening)

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net 20.8.16

**Desktop (please complete the following information):**
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎2021-‎04-‎29
OS build	19045.2673
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by m-mohamedin** [comment]
Should be fixed in the latest release, please confirm

**Comment by TheOtherRealm** [comment]
Yep, thanks!
