### ISSUE TITLE
Background colour is not exported to .jpg or .png while using CLI

### ISSUE THREAD

**Issue by wjuszczak** [jgraph/drawio-desktop#1250]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The background colour is not exported to .jpg or .png while using CLI. Regardless of the background colour set, it is always exported as white (unless we use -t, then it is transparent). 

**To Reproduce**
1. Open sample diagram
2. Set background colour to #FF0000
3. Save the diagram as diagram.drawio
4. In the terminal: $ drawio ~/diagram.drawio -x -f png -b 20

**Expected behavior**
The background colour should be exported, as is happening while using GUI

**Screenshots**
![issue](https://user-images.githubusercontent.com/105645743/223709766-5335a0d6-144f-4f97-98a3-1755a4ef5ade.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 20.8.16

**Desktop (please complete the following information):**
 - Linux pop-os 6.0.6-76060006-generic #202210290932~1667401208~22.04~d2df702 SMP PREEMPT_DYNAMIC Wed N x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by davidjgraph** [comment]
which binary is that?

**Comment by wjuszczak** [comment]
https://github.com/jgraph/drawio-desktop/releases/download/v20.8.16/drawio-amd64-20.8.16.deb

**Comment by davidjgraph** [comment]
Is this still an issue in 24.0.4?
