### ISSUE TITLE
Export MXLibrary Compressed

### ISSUE THREAD

**Issue by Murmele** [jgraph/drawio-desktop#1251]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When exporting a created library the exported xml content is compressed, even when the option for compression is disabled in "File->Properties->Compressed" (Diagrams are not compressed which is correctly)

**To Reproduce**
1. Create new shape
```
<shape w="60" h="20" aspect="variable" strokewidth="inherit">
  <connections>
    <constraint y="0.5" x="0" perimeter="1" name="SW1" />
    <constraint y="0.5" x="1" perimeter="1" name="SW2" />
  </connections>
  <background>
    <!-- <rect x="0" y="0" w="60" h="20" /> -->
  </background>
  <foreground>
    <fillstroke />
    <path>
      <move x="0" y="10" />
      <line x="20" y="10" />
      <line x="40" y="00" />
      <move x="40" y="10" />
      <line x="60" y="10" />
      <stroke />
      <ellipse h="5" w="5" x="17.5" y="7.5" />
      <fillstroke />
      <ellipse h="5" w="5" x="37.5" y="7.5" />
      <fillstroke />
    </path>
    <stroke />
  </foreground>
</shape>
```
2. Create new library
3. Add Shape to library
4. Export Library to file. `Library.xml`
5. Check `Library.xml` with text editor

**Expected behavior**
The shape is stored as above

**Observed**
The shape is stored in compressed format

**Screenshots**
No screenshot

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.8.16

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Nothing

**Comment by davidjgraph** [comment]
We're going to switch off compression everywhere by default at some point in the future.. It seems to cause far more problems than solutions.

**Comment by davidjgraph** [comment]
Fixed at some point a while ago, not sure exact version.
