### ISSUE TITLE
 https://app.diagrams.net/app goes to a 404 (Blog may need updated)

### ISSUE THREAD

**Issue by AE720** [jgraph/drawio-desktop#1252]
Sorry if this seems overly trivial but when researching offline usage, I found this blog https://www.diagrams.net/blog/diagrams-offline and it says at the bottom to "Go to https://app.diagrams.net/app while you still have internet connectivity to load the application into your browser.". That link leads to a 404 either meaning that link should redirect to https://app.diagrams.net/ (Assuming this is the new link and clicking the 3 dots and then "install" will make it work offline), or the blog should be updated to reflect that. I didn't find any newer blog to reflect the change but it might make it easier for those looking for the information like I was.

**Comment by xiamuguizhi** [comment]
I agree with you, because I have the same problem as you and I think it needs to be solved.

**Comment by davidjgraph** [comment]
Fixed, thanks for the report.
