### ISSUE TITLE
Allow export to HTML from command line

### ISSUE THREAD

**Issue by dettmering** [jgraph/drawio-desktop#126]
It would be great to have the possibility to export to HTML (and XML) through the command-line. I successfully managed to export PDF and PNG, but my workflow also needs HTML as an output format.

**Comment by davidjgraph** [comment]
How would export to XML on the command line work?

**Comment by dettmering** [comment]
I would imagine something like `/Applications/draw.io.app/Contents/MacOS/draw.io --export --all-pages --output diagram.xml diagram.drawio`, maybe with an option to disable compression.

**Comment by ashrafteleb** [comment]
XML export is added with compression option. But it always export all pages. We may add HTML export in the future

**Comment by ejemba** [comment]
@ashrafteleb hi, do you have an idea when you could implement the HTML export ?

**Comment by davidjgraph** [comment]
Please open a new issue with the request.
