### ISSUE TITLE
textbox cannot resize automatically 

### ISSUE THREAD

**Issue by yyt178** [jgraph/drawio-desktop#1260]
hello,
i was wondering if there is a way that textbox can resize automatically with the input text increase.
if there is not, i hope new version can add the feature. thank you.
![屏幕截图 2023-03-16 133953](https://user-images.githubusercontent.com/127017620/225525237-b5503d35-539e-43fa-9734-7e9443df976b.png)

**Comment by mararad** [comment]
Does Autosize under Arrange tab help when a shape is selected?

![autosize](https://user-images.githubusercontent.com/44292306/225651551-583f29eb-a047-420a-b55f-cd13c5ae6e46.JPG)

**Comment by ChMah** [comment]
You might also use the keyboard shortcut Ctrl+Shift+Y
