### ISSUE TITLE
Command line export with sheet name with the parameter --page-index

### ISSUE THREAD

**Issue by vhavard** [jgraph/drawio-desktop#1261]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am using the draw.io command line regularly to export my schema into png or pdf format for my research paper.
For example I am using that:
```shell
draw.io --export "path/t/schema/file.drawio" -o "path/to/Schema-export/file.png" -p 3 -s 2 -b 0
```
However if I am adding a sheet before page 3 in file.drawio, my command is not working anymore I need to update to **-p 4**
```shell
draw.io --export "path/t/schema/file.drawio" -o "path/to/Schema-export/file.png" -p 4 -s 2 -b 0
```

**Describe the solution you'd like**
Is it possible to add an export by sheet name and in a same way as sheet index, like that ?
For example if I had a sheet into draw.io which is called "Workflow_v1"
```shell
draw.io --export "path/t/schema/file.drawio" -o "path/to/Schema-export/file-Workflow_v1.png" -p "Workflow_v1" -s 2 -b 0
```
Another request is to be able to get the sheet name from command line
```shell
draw.io --sheet-name "path/t/schema/file.drawio" --p 3
%  must return "Workflow_v1"
```

**Comment by davidjgraph** [comment]
Is this still happening?
