### ISSUE TITLE
Connect the cloud

### ISSUE THREAD

**Issue by FairyTail2000** [jgraph/drawio-desktop#1264]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Since the web (pwa) version was so annoying with giving me the desktop version. I was surprised that there is no feature parity between them

**Describe the solution you'd like**
I want to use the desktop version like the pwa version

**Describe alternatives you've considered**
Just using the PWA Version

**Additional context**
I found this closed issue #449 . Which explains this behavior with offline capabilies. I personally don't consider this, as, for example OneDrive, has Offline Capabilities too.

**Comment by davidjgraph** [comment]
This is outside the scope of the desktop project. The scope of the project is defined as a stand-alone, non-connected app, that is not going to change.

**Comment by FairyTail2000** [comment]
Thanks for your clear answer
