### ISSUE TITLE
The web version of PlantUML cannot be used

### ISSUE THREAD

**Issue by gitLinan** [jgraph/drawio-desktop#1266]
![image](https://user-images.githubusercontent.com/33097694/227301462-e778ff1d-4cbb-4774-a311-c588ba740447.png)
![image](https://user-images.githubusercontent.com/33097694/227301527-1eeee386-dd6b-44b7-a88b-326fc4f8f85a.png)
![image](https://user-images.githubusercontent.com/33097694/227301619-2cff7dcf-2d70-407e-8ab7-236aa929d321.png)
![image](https://user-images.githubusercontent.com/33097694/227301804-ef4d282c-e346-46e5-8ba3-f7e4d5850454.png)

**Comment by davidjgraph** [comment]
What was your input? There are chinese characters in the response, so the input you've shown cannot be the one you sent.

**Comment by gitLinan** [comment]
I hope to generate a mind map using Markdown code on the web version of draw.io, using the advanced PlantUML component. However, after adding the Markdown code, I received a notification that the PlantUML server-side component is outdated and needs to be updated.
the screenshot process is as follows:
![image](https://user-images.githubusercontent.com/33097694/227398905-73dec77d-8933-4822-b30b-1837822d1d7d.png)

![image](https://user-images.githubusercontent.com/33097694/227399596-c94dc550-ca9e-4e57-8532-9ca91eae0c37.png)

![image](https://user-images.githubusercontent.com/33097694/227399725-df59593b-57dc-4c8f-8b6f-06b8e3c1ca62.png)

**Comment by davidjgraph** [comment]
Thank you for reaching out to us regarding the PlantUML version in diagrams.net. We understand your interest in having the latest version available in our platform.

While PlantUML integration is a valued feature, it is not considered a core part of the site. Our team prioritizes essential updates and improvements to the main functionality. As a result, updates to PlantUML might not be as frequent.

We appreciate your understanding and apologize for any inconvenience this may cause. In the meantime, if you require the most up-to-date version of PlantUML, we recommend deploying your own instance for a more tailored experience.

Please note that we are unable to provide a specific timeline for when we might update PlantUML.

Thank you once again for your interest in diagrams.net, and we appreciate your support.
