### ISSUE TITLE
Dark mode makes text in rectangles very hard to read

### ISSUE THREAD

**Issue by JVApen** [jgraph/drawio-desktop#1267]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Dark mode updates text color, though not the style applied on a box. This causes perfectly readable text in light mode to be unreadable in dark mode.

**To Reproduce**
1. Go to General
2. Add a rectangles 
3. Apply the light orange style (page 4 of styles)
4. Add text to the rectangles 
5. Change mode to dark mode
6. Look at the box and try to read the text

**Expected behavior**
When changing a diagram from light mode to dark mode (and vice versa), I expect the diagram to stay readable.
This implies that if text colors would be adapted, also all other colors would be adapted along.

**Screenshots**
![Style menu](https://user-images.githubusercontent.com/1300786/227866418-b3443645-c093-4d19-8812-be02a99affb8.png)
![Light mode](https://user-images.githubusercontent.com/1300786/227865085-e48fbac5-4d05-4d66-98bf-e49bf2e179be.png)
![Dark mode](https://user-images.githubusercontent.com/1300786/227865218-c0619048-2bea-42ec-be38-54a3917b65dc.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.8.16

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
This is mostly annoyable when sending a draw.io diagram to another person using the other dark/light theme as the one creating the diagram.

**Comment by FanningHau** [comment]
Same issue here

**Comment by davidjgraph** [comment]
Try 21.6.1
