### ISSUE TITLE
file manager only shows empty symbols

### ISSUE THREAD

**Issue by theCollectiv** [jgraph/drawio-desktop#1270]
I### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
On any interaction, the draw.io-"file manager" only shows empty symbols (see screenshot).
I'm on Linux/Ubuntu.
I don't have any other app, which got this behavior on my system. So I guess this is connected to draw.io/diagrams.net.

**To Reproduce**
Try to open or safe anything, where file manager action is involved.

**Expected behavior**
Navigating by a file manager which is not using blank or crypted symbols

**Screenshots**
![2023-03-29_12-22](https://user-images.githubusercontent.com/78902012/228507476-623272b6-2234-4939-a9a4-f42f3a10d347.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [diagrams.net 20.8.16]

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Browser --
 - Version --

**Additional context**
I installed drawio via snap, like this [Install draw.io on Linux | Snap Store](https://snapcraft.io/drawio)

**Comment by davidjgraph** [comment]
Duplicate #368
