### ISSUE TITLE
package-manager-install for linux/ubuntu without buggy drawio-desktop

### ISSUE THREAD

**Issue by theCollectiv** [jgraph/drawio-desktop#1271]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
It's more a feedback than a bug.

**To Reproduce**
1. I installed draw.io via snap. But that failed due to 
[file manager only shows empty symbols · Issue #1270 · jgraph/drawio-desktop](https://github.com/jgraph/drawio-desktop/issues/1270) and 
[Unintelligible characters in Draw.io snap package on Fedora 32 · Issue #368 · jgraph/drawio-desktop](https://github.com/jgraph/drawio-desktop/issues/368)
The fonts are not working.
Clearing the fonts cache before running drawio fixes that ...but only for one time, launching draw.io.
2. I installed draw.io via flatpack. But that failed too. See 'screenshot'.
There might be a workaround too, but it's even harder than 1.
[How to Hack gtk3-nocsd Into Flatpak Applications | Stephan Sokolow's Blog](http://blog.ssokolow.com/archives/2022/09/20/how-to-hack-gtk3-nocsd-into-flatpak-applications/)

**Expected behavior**
To have a package manager installation for easy adaption.
There is no non-buggy drawio-desktop installation via ubuntu/linux package manager available at the moment. This somehow restricts the easy adaption of draw.io.
 ...if an installation by a package manager*  would work right out of the box, it'll help for an easier access for more users.
 * no package manager for an app is a no-go for me

**Screenshots**
```
 >> flatpak run com.jgraph.drawio.desktop
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
[2:0330/132711.034894:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[2:0330/132711.034955:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
```

**draw.io version (In the Help->About menu of the draw.io editor):**

any actual install via package manager for linux/ubuntu

**Desktop (please complete the following information):**
Ubuntu 22.04

**Additional context**
drawio is really a great app, when it's working correctly, and I'm loving it. With lower barriers for usability, it'll be perfect.

**Comment by davidjgraph** [comment]
I appreciate the problem, but this is ultimately an issue that package management on linux is poor, overall. There are packages for every major package manager, if none of those are good enough, you need an issue specific to the one(s) you want fixed, with specifics as to what the problem(s) are.

"Improve package managers on linux" is just to broad to have an open issue on this repo. I don't disagree, it's just the broadness of scope I will close this for.
