### ISSUE TITLE
How do I change the font in the Latex formula?

### ISSUE THREAD

**Issue by reincornator** [jgraph/drawio-desktop#1276]
### Discussed in https://github.com/jgraph/drawio-desktop/discussions/1274

<div type='discussions-op-text'>

<sup>Originally posted by **reincornator** April  2, 2023</sup>
Hello. I am writing an article in Microsoft Word and using MathType for formulas. I do illustrations in Draw io. The journal requires that the symbols in the formulas and in the figures be written in the same font. How do I change the font for Latex to "Liberation Serif"?</div>

**Comment by davidjgraph** [comment]
This isn't an "issue". The discussion post is the better place.
