### ISSUE TITLE
A paid commercial software is similar to this project

### ISSUE THREAD

**Issue by LiuZeJie97** [jgraph/drawio-desktop#1277]
**Describe the bug**
XunJie FlowChart(A paid commercial software) is similar to this project
迅捷流程图（一款收费的商业软件）与该项目存在雷同

Official website of the XunJie FlowChart: https://www.liuchengtu.com/
迅捷流程图官方网站：https://www.liuchengtu.com/

Main interface of the XunJie FlowChart: 
迅捷流程图的软件主界面：
![image](https://user-images.githubusercontent.com/69414234/230765382-bc8fc3c7-1aa7-4b3f-8d2b-b61167d76442.png)

Evidence of suspected plagiarism: Open the XunJie FlowChart software, click the font in the menu bar, click Customize, and then click the Help button, then we can open the website "https://www.diagrams.net/blog/external-fonts"
疑似抄袭的证据：打开”迅捷流程图“，点击菜单栏的字体，点击自定义，然后点击帮助按钮，可以打开网站”https://www.diagrams.net/blog/external-fonts“

Screenshot of XunJie FlowChart: 
![image](https://user-images.githubusercontent.com/69414234/230765395-0d33f7fa-3e6c-4ab2-aed9-21b1574960cb.png)

Screenshot of XunJie FlowChart: 
![image](https://user-images.githubusercontent.com/69414234/230765430-76b6a488-bfbd-4aea-baf5-a2939601a2cd.png)

Screenshot of XunJie FlowChart: 
![image](https://user-images.githubusercontent.com/69414234/230765721-3a143cb0-5b59-42ee-964a-83560367889d.png)

Charges: 
收费情况：
![image](https://user-images.githubusercontent.com/69414234/230765824-a0d23cc1-0a4a-4dda-90ae-25fc03e5d544.png)

抄袭抄到国外去了，实在是太丢人了。

**Comment by davidjgraph** [comment]
Cool.
