### ISSUE TITLE
smart templates

### ISSUE THREAD

**Issue by p92** [jgraph/drawio-desktop#1279]
### Preflight Checklist

* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
smart template not working on linux with drawio snap 21.1.2

**To Reproduce**

1. open drawio
2. choose new diagram
3. select 'Smart Template' on left
4. describe "draw a migration process in 5 steps"
5. select diagram type "flux diagram"
6. click on generate
7. popup says "error / unknown error"
8. click on ok
9. new popup "error / error 0"

**Expected behavior**
a smart template is generated and shown in the editor

**Screenshots**
![image](https://user-images.githubusercontent.com/553530/231571849-c3420b07-51b9-46e2-ba81-97bab7c4b007.png)
![image](https://user-images.githubusercontent.com/553530/231571940-b7b19e62-7c4c-4c77-a237-1038861bd8b6.png)
![image](https://user-images.githubusercontent.com/553530/231571998-a7ae199c-8aeb-41c4-80bd-404cd98e67c2.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 21.1.2

**Desktop (please complete the following information):**
 - OS: Linux Kubuntu 22.10
 - Linux version 5.19.0-1022-lowlatency (buildd@lcy02-amd64-059) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.2.0-3ubuntu1) 12.2.0, GNU ld (GNU Binutils for Ubuntu) 2.39) #23-Ubuntu SMP PREEMPT_DYNAMIC Wed Mar 29 10:15:02 UTC 2023

**Additional context**
drawio installed by snap
drawio                                21.1.2                      172       latest/stable  jgraph✓                -

**Comment by p92** [comment]
any choice of "diagram type" gives same error
changing diagram description gives same error

**Comment by davidjgraph** [comment]
Yes, that should be exposed in desktop, comms aren't allowed so it will always error. We've a fix to remove it in the next release.
