### ISSUE TITLE
Drag and drop to link to other documents

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio-desktop#128]
Right now when you drag one .drawio file onto an open diagram, the app imports all of the tabs from the other diagram. I don't really see why anyone would want that. What if instead it inserted a `file://` url linking to the other diagram? That way you could quickly build a large, easily navigable database of interconnected information spread across many documents.

**Comment by JesseAldridge** [comment]
Screenshot for context: 
![Screen Shot 2019-07-11 at 2 14 43 PM](https://user-images.githubusercontent.com/191903/61086027-ace4eb80-a3e6-11e9-9553-08afb94cfcb1.png)

**Comment by davidjgraph** [comment]
That would only work for one machine, sounds like a recipe for a ton of support tickets for us....

**Comment by JesseAldridge** [comment]
Hmm, didn't think about that.
What about adding support for relative file urls?
https://superuser.com/questions/210263/file-to-point-a-relative-file-to-current-directory

**Comment by JesseAldridge** [comment]
This does in fact work in web browsers:

foo.html
```
<a href="file:./bar.html">bar</a>
```

bar.html
```
<a href="file:./foo.html">foo</a>
```

**Comment by realyukii** [comment]
If the diagram become more and more larger, it would be helpful to have some way to add ref/link that will navigate the user to other shape or other tab

So, the user can jump from one shape to the other shape :)
