### ISSUE TITLE
Hope to add a shortcut key for advanced export

### ISSUE THREAD

**Issue by luodeyu** [jgraph/drawio-desktop#1284]
* [ok] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ok ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Exporting high-definition png images is too complicated

**Describe the solution you'd like**
Hope to add a shortcut key for advanced export，Relevant path: File -> Export As -> Advanced

**Comment by stefan2904** [comment]
I agree, this is a major PITA when working with drawio. 

Click trough the Export menu, configure the export, save file; then make some small changes, and the whole thing from start.


Would it help if we propose a clearer user flow for this feature request? Or is it simply not part of the plan? :-) Thanks!

---

related issues:

-  #508 → stale
-  #771 → duplicate 
-  #899 → duplicate

**Comment by davidjgraph** [comment]
Thanks for the suggestion, but declined due to too little interest in this request.
