### ISSUE TITLE
Regression on mermaid import

### ISSUE THREAD

**Issue by Greybird** [jgraph/drawio-desktop#1286]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Following an update, the way mermaid diagrams are imported leads to format loss.

**To Reproduce**
1. Go to Arrange > Insert > Advanced > Mermaid
Import following mermaid diagram:
```
sequenceDiagram
participant C as Client
participant S as Server

rect rgb(255, 200, 200)
C->>+S: Request
S->>-C: Response
end
```

**Expected behavior**
The diagram should be imported with all colors

**Screenshots**
1. Mermaid generation:
![image](https://user-images.githubusercontent.com/8553578/232720550-5b927880-8b67-46f4-813d-399cd67ed2d8.png)

2. Previous import
![image](https://user-images.githubusercontent.com/8553578/232721011-2ee4410a-ac61-4705-b51a-0af872fbea9c.png)

3. Current import
![image](https://user-images.githubusercontent.com/8553578/232720762-ad7119cb-a198-47b5-8b6e-1ae4a2f2bec8.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.1.2
Tested on the Store version, the web version on Windows and Chrome 112

**Additional context**
it seems that when we modify an existing imported mermaid diagram by double-clicking on it and injected a new mermaid description (even drastically different) the style is correctly applied

**Comment by davidjgraph** [comment]
There's a pulldown at the bottom of the mermaid dialog (diagram, image). If you want a mermaid image, select image. The default is now native draw.io format, which will look different.

**Comment by Greybird** [comment]
I'm sorry to hear that this is expected behavior now, because I was relying on this quite a lot, but I can understand there are trade-offs to make, especially for a free product.

So thanks for your feedback and more generally for this tool!

**Comment by davidjgraph** [comment]
It's only one more click to get the previous behaviour.

**Comment by Greybird** [comment]
I'm very sorry, I misread your comment. You are right, the feature is right there, and the regression I identified is in fact an improvement in the general case where you want to work with an actual schema.
Sorry for the multiple confusions on my side 😳.
