### ISSUE TITLE
Shortcut Clear Waypoints is not working

### ISSUE THREAD

**Issue by rikoari** [jgraph/drawio-desktop#1288]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Shortcut to Clear Waypoints (Alt+Shift+R) is not working.
As stated in https://viewer.diagrams.net/#Uhttps%3A%2F%2Fviewer.diagrams.net%2Fshortcuts.svg

**To Reproduce**
1. Create 2 objects, i.e. Rectangle
2. Create connection between those two
3. Move pointer into the connection, and try to customize the line so it creates new waypoints
4. Click the connection line, and perform the shortcut
5. The connection line is not changing back to default

**Expected behavior**
The connection line should be changed back to default

**Screenshots**
_Current issue (not changing)_
![image](https://user-images.githubusercontent.com/48411313/233245271-1fdc0275-6369-4c56-a152-333218b84476.png)

_Expected (manually click Clear Waypoints)_
![image](https://user-images.githubusercontent.com/48411313/233246605-969d2a0a-e0f4-493b-98f2-cb1de8c045d2.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.1.2

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 22H2 OS Build 19045.2728

**Additional context**
Last working version was 19.0.3 as far as I remember.

**Comment by m-mohamedin** [comment]
Using the latest version, we cannot reproduce, please try again and let us know
