### ISSUE TITLE
GraphML graphs cannot be imported in desktop app, but does in online version. 

### ISSUE THREAD

**Issue by watermarkhu** [jgraph/drawio-desktop#1289]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Importing `.graphml` files does not work in the Desktop App, but does in diagrams.net. There is no error message. There is a short loading animation but nothing is imported. 

**To Reproduce**
1. Go to "File"
2. Click on "Import"
3. Select a `.graphml` file. 

**Expected behavior**
The graph should be imported the same way as in the online version. 

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.2.3
- draw.io version 20.8.16
- draw.io version 21.1.2

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by davidjgraph** [comment]
We don't have the code in JS, it requires a server. This is the expected behaviour.

**Comment by watermarkhu** [comment]
Is that part also open source? If yes, can you point me towards it? I haven't found anything reliable that can translate graphml into mxGraph.

**Comment by davidjgraph** [comment]
No, it's not open source.

**Comment by watermarkhu** [comment]
Alright, thanks for the quick answer.
