### ISSUE TITLE
Feature Requests for draw.io: Customizable Dashed Line Style, Batch Selection of Pages, and Update Reminder

### ISSUE THREAD

**Issue by Robert30-xl** [jgraph/drawio-desktop#1292]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Thank you very much to the developers of draw.io! In March, 21, I downloaded version 13.3 of draw.io with just one dash style that directional connector and line pattern could set, and the others were dotted lines. I just noticed that my desktop app wasn't updated today, so I immediately updated to version 21.2.1. I find that after two years, I can use more shapes, and there are three dash styles that directional connector and line pattern can set. Because of the dashed line used to be, it looks like a dotted line when you zoom out. But I still have two feature suggestions, which I hope developers can consider.

**Describe the solution you'd like**
First, I want to add custom functionality to the dashed line style that directional connector and line patterns can set. The current styles are solid, dashed (1), dashed (2), dashed (3), dotted (1), dotted (2), dotted (3). When I don't want to use these styles, I want a tool to customize the pattern.

Second, I want to add a feature for page batch selection. When I save the entire draw.io document as a new draw.io, I only want to keep a few pages. However, the current 21.2.1 version still does not have the ability to select pages in batches, so it is not good for me to delete them in batches. I need to click pages one by one and delete them. This step is tedious and frustrating.

Third, I want draw.io to show a red dot at the *** of the about feature when there are updates to it to remind users that a new version of draw.io is available.

**Additional context**
![pattern](https://user-images.githubusercontent.com/80387795/233790805-3d201cbc-473e-47a1-8346-2e68c5f2c59d.png)
![select pages in batches](https://user-images.githubusercontent.com/80387795/233790814-0b1e8749-661f-4860-9142-b3d143583eae.png)

I've been using draw.io for a long time to draw flowcharts, functional block diagrams, and status diagrams. Thank you very much for your active maintenance. Thank you for your support of Chinese, which greatly facilitates my use

**Comment by Quest33n** [comment]
It would nice to have custom line patterns

![lines](https://github.com/jgraph/drawio-desktop/assets/110933765/92678534-5926-4d5e-b61c-6bbb7102ff5a)

**Comment by worthwhileindustries** [comment]
I agree. Adjusting the step size and size of dashes at the very least would be very nice.

**Comment by alderg** [comment]
Try Dash Pattern:

<img width="241" alt="Screenshot 2024-06-14 at 09 47 40" src="https://github.com/jgraph/drawio-desktop/assets/921200/71e68742-32ef-40b5-8347-b6283439046b">

**Comment by davidjgraph** [comment]
Note that individual issues within this issue might well be valid, but it's simply impossible to deal with such an overloaded issue. If anyone wanted one of the issues listed, you are welcome to open as a single ticket.

**Comment by worthwhileindustries** [comment]
> Try Dash Pattern:
> 
> <img alt="Screenshot 2024-06-14 at 09 47 40" width="241" src="https://private-user-images.githubusercontent.com/921200/339683579-71e68742-32ef-40b5-8347-b6283439046b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MDEyODAsIm5iZiI6MTcxODQwMDk4MCwicGF0aCI6Ii85MjEyMDAvMzM5NjgzNTc5LTcxZTY4NzQyLTMyZWYtNDBiNS04MzQ3LWI2MjgzNDM5MDQ2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQyMTM2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjRiNWVkMzIxOWFmMjVlNGJkMDJjYmY3ZjQxNDNiZTFhM2NiNTFmYTY5ZTlmOWM2ODJiOGMyNDg4ZDI1ZGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kizZ8_LP9oNTSH5ANN2N8sR-GDpUMS4GX1AbNGu-PKU">

@alderg Saw that and for some reason did not try it. Thanks. That solves my problem.
