### ISSUE TITLE
draw.io should add more regular polygon shapes to the base graphics library

### ISSUE THREAD

**Issue by hhhcs** [jgraph/drawio-desktop#1293]
* [ yes ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ yes ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Regular polygon shapes are often used in  graphics  but draw.io only provides square  and pentagon. I can currently only get different regular polygons by rotating the line segments at different angles. Hopefully draw.io will add more regular polygon patterns to the base graphics library.
Thank you for your work.

**Comment by spatial-data-scientist** [comment]
The problem is still not solved. There is currently not even a pentagon regular shape.
