### ISSUE TITLE
choose storage method in drowio-desktop with mac

### ISSUE THREAD

**Issue by collery** [jgraph/drawio-desktop#1295]
* [*] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [*] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
when i use drawio with web,i can choose storage method,but i can't when i use in macos

**Describe the solution you'd like**
i want add thise feature in mac desktop app.

**Comment by davidjgraph** [comment]
There is only storage method, the computer the app is installed on. This isn't an online, connected app.
