### ISSUE TITLE
Deactivate Preloaded shapes in search results

### ISSUE THREAD

**Issue by bifiwurscht** [jgraph/drawio-desktop#1297]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When the Search shapes bar worked for searching for my own shapes I allways was shown the Preloaded shapes higher than my own. For example: I search for "Cisco": I get tons of shapes from the cisco library and have to click "Load More" several times until i get to my own shapes.

**Describe the solution you'd like**
I would like to disable the preloaded shapes from the search shapes bar all together. Or connect it to the toggle for showing them in the shapes section. So when I dont have the Cisco library activated, the search gives me no results as well.

**Describe alternatives you've considered**
Put the search results of my own shapes to the top.

**Additional context**

**Comment by davidjgraph** [comment]
Thanks for the suggestion, however, the effort to implement this doesn't justify the time to build and maintain the feature. Thus, it will be declined.
