### ISSUE TITLE
Exporting defaults to wrong filenames

### ISSUE THREAD

**Issue by pesho-ivanov** [jgraph/drawio-desktop#1299]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Exporting defaults to `[filename].drawio.[ext]`. Double extensions are not standard and I doubt that anyone wants "drawio" in their filename when they export from it.

**To Reproduce**
1. Go to File -> Export as -> PDF...
2. Click 'Export'
![image](https://user-images.githubusercontent.com/110152/234289219-e96911ea-f7e2-48e9-a885-6eb50f150fb4.png)

**Expected behavior**
Default to `[filename].drawio.[ext]` when exporting.

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 21.2.1 on Ubuntu 20.04.5 LTS
- https://app.diagrams.net 20.5.3

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS

**Comment by davidjgraph** [comment]
The problem is how to indicate that the export contains the diagram data. Making everything .pdf means you cannot tell the difference.

If it's an issue don't include the diagram in the export.

**Comment by pesho-ivanov** [comment]
Oh, I see, thank you for noting this (it was not obvious to me)!

I guess my bug report dissolves into whether including the diagram is a good default option, given that it causes diagram duplication and potential versioning issues. This has happened to me when my colleague edits the `.drawio`, exports `.svg` (for web), and `.pdf` (for latex).

**Comment by davidjgraph** [comment]
I see the problem, however, if we don't include the diagram we'll have 20 reports a week from users exporting to PDF without saving and asking how to reload their diagram (which is why we changed this). The average user doesn't understand the difference between saving and exporting.

**Comment by pesho-ivanov** [comment]
I see the tradeoff. Let me try to suggest how to alleviate the issue by keeping a state of the exporting options (only during the session; not saved). Then once parameters are chosen, the second export is less tedious and error-prone because of not requiring an inspection of each and every checkbox. Such a solution may be useful in other situations as well. I guess the limiting factor is the added complexity of keeping the state.
