### ISSUE TITLE
Extension while saving/exporting

### ISSUE THREAD

**Issue by jorgedlcruz** [jgraph/drawio-desktop#13]
Hi guys,
Love this app so much! Never turned on my VM anymore to use my old Visio 2010. One thing while saving or exporting to .png, etc, the file goes without any extension, and you need to rename them manually, it happens while you try to save, or if you try to export to any format.

Can we have that fixed, please?

Cheers!

**Comment by Cragdoo** [comment]
I'll add a +1 to Jorge's request. Would be nice if you could define an extension for the files (and associated icon) when using "Save" or "Save as" , easier to identify files.

**Comment by davidjgraph** [comment]
.dio ?

**Comment by Cragdoo** [comment]
as default , yeah , as long as the extension is associated with the application.

**Comment by Rainmaker52** [comment]
.dio for digrams
.dil for libraries (draw.io.libraries?)
?

**Comment by Rainmaker52** [comment]
Well, I see the same on sites as filext.com etc, but it's not among the extensions listed on the Delphi wiki http://delphi.wikia.com/wiki/Delphi_File_Extensions.

If you're worried about collisions: a file extension is not necessarily 3 letters. You could use .drawiodrawing and .drawiodrawing.

Those are almost guaranteed to be unique.

**Comment by ephronx** [comment]
Hi;
I am keen to see the default drawing extension change too. We use a doc mng system that uses the default windows associations to open the correct applications. I have been using .drawio for my diagrams and it works a treat, but would be nice if application defaulted to a similar extension vs xml. The general default for xml on users standard workstations is IE - which is not ideal.

**Comment by davidjgraph** [comment]
Should default to .draw.io now
