### ISSUE TITLE
Reveal in finder

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio-desktop#130]
Sublime text has a feature where you open the macOS finder in the directory containing a file. It comes in handy for all sorts of things. It would be cool if drawio supported this.

![Screen Shot 2019-07-17 at 1 48 49 PM](https://user-images.githubusercontent.com/191903/61410770-d051df80-a899-11e9-8d6c-e30c42d2eb8d.png)

**Comment by davidjgraph** [comment]
Closing due to lack of interest from core team.

**Comment by jamesharr** [comment]
I was looking to open this exact same ticket (except there'd be an equivalent option for Windows/Linux too).

I'm curious what my path is now. Do I open a new ticket or try to get this one re-opened?

**Comment by davidjgraph** [comment]
I would open one for each.
