### ISSUE TITLE
Ubuntu 23.04

### ISSUE THREAD

**Issue by khteh** [jgraph/drawio-desktop#1300]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
![image](https://user-images.githubusercontent.com/3871483/234453078-19d3ff1b-2c5f-48b6-b84a-6cecb75228d1.png)

**To Reproduce**
1. Go to 'File > Open'

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.2.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04

**Additional context**

**Comment by davidjgraph** [comment]
Duplicate #368
