### ISSUE TITLE
Adding new text on an object and immediately change the font size remove the text

### ISSUE THREAD

**Issue by dev-mansonthomas** [jgraph/drawio-desktop#1303]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
On any object (custom icon, library icon, arrows), adding text for the first time (not editing the current text) and immediately changing the font size lead in the removal of the text just entered before.

**To Reproduce**

1. Add an icon that do not have text description
2. double click to enter description edit mode
3. Add text
4. Immediatly change the font size, either with the arrows, or type a new font size
5. ==> the text entered in step 3 is removed

**Expected behavior**
the expected behaviour is to keep the text entered in step 3 and change the font accordingly

**Screenshots**
See video hosted on GDrive (too large for github 10MB) : https://drive.google.com/file/d/1l_hx9GUMg5VGOpFWjzS6XgO9rd9G95yc/view?usp=sharing

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version
 diagrams.net 21.2.1

**Desktop (please complete the following information):**
 - OS: MacOs X / intel
 
![image](https://user-images.githubusercontent.com/5695269/235007089-79369ed8-4477-49cd-b9f8-e6393a39b12c.png)

**Additional context**
We're good :)

**Comment by HiL0op** [comment]
Is 'text-overflow' set to hidden?

**Comment by dev-mansonthomas** [comment]
Hi,
By default it's set to visible. 
It looks like it's an UI thing, as, as soon as I change the font the current menu change to the "Style" menu.
I've tried with text-overflow hidden, block, fill, same behaviour. 

See here : 
https://drive.google.com/file/d/1YL0dNGxM2Vuv_Ty6Vt2Gs7xDaBWs3eaO/view?usp=sharing

**Comment by HiL0op** [comment]
It seems as though you are beyond this in troubleshooting but the other more obvious reason would be the shape type.

**Comment by dev-mansonthomas** [comment]
Well, here it's a PNG pasted in DrawIO, which is something I use a lot, since there's a lot of stuff that is not in the default libraries. 

If you try with basic shapes such as rectangle, or more elaborated, like AWS icon, you're blocked from changing the text size (you can see the number going from 12 to 13 and be reverted back to 12....), which is also a bug for me. 

==> We should be able to edit the text size right away, otherwise, we loose time.
