### ISSUE TITLE
'No Selection' window as default window.

### ISSUE THREAD

**Issue by HiL0op** [jgraph/drawio-desktop#1304]
### Preflight Checklist

* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Popup window on hover populates as empty first, then the object table is loaded. 
Global settings for behavior set to 'none' disables all popup windows. 'Click', loads a blank window until an object is clicked. And 'hover' populates a 'No Selection' window with a blank text area, until a block is selected/hovered.

This: 'No Selection' popup window -- cannot be edited, disabled, or have the title changed. 

**To Reproduce**
1. Create a bloqq with a hover.
2. Hover over the exterior of the graph, or an object with no behavior assigned. 
3. Attempt global behavior changes: none, hover, click. Attempt object level behavior: none, hover, click. Assign table data to global. Write table data for div container class or similar. 
4. See error "No Selection' window

**Expected behavior**
1. An ability to change the 'No Selection' window to unique content. 
2. The ability to disable the 'No Selection' window.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...

**Additional context**

**Comment by davidjgraph** [comment]
Don't understand this at all.
