### ISSUE TITLE
The contents of the file changed to nul nul nul

### ISSUE THREAD

**Issue by Weorano** [jgraph/drawio-desktop#1306]
There is a file I've been working on for a month and a half. Due to the fact that the program worked confidently, I stopped saving the file. The last save was a week ago. Computer power outage and the web version changed my file to empty, but the size remained the same. These were the most difficult intellectual works, do I have an option to survive?

[file.txt](https://github.com/jgraph/drawio-desktop/files/11364714/file.txt)

**Comment by davidjgraph** [comment]
What version of draw.io were you using? Is there a .bkp file?
