### ISSUE TITLE
how to remove an extra buggy plugin

### ISSUE THREAD

**Issue by elinx** [jgraph/drawio-desktop#1307]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I add an extra plugin which is buggy then got an error on every startup of the program, don't know how to delete it because can't go into the plugins dialog.

**To Reproduce**
load this plugin:
```js
Draw.loadPlugin(function (ui) {
  mxEvent.addListener(document, "mousedown", function (event) {
    mxLog.warn("mouse button: " + event.button);
    // check if the side button 1 was pressed (zoom in)
    if (evt.button === 3) {
      ui.actions.get("zoomInMouse").funct();
    }
    // check if the side button 2 was pressed (zoom out)
    else if (evt.button === 4) {
      ui.actions.get("zoomOutMouse").funct();
    }
  });
});

```

**Expected behavior**
Give the user a hint how to remove the buggy plugin.
I guess the plugin is copied to somewhere on macos because the error still happends after I reinstall the who program, where is it?

**Screenshots**
<img width="416" alt="image" src="https://user-images.githubusercontent.com/3711927/235471075-e4210850-e8d8-43f1-8c6b-85d3f0d18161.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.2.1

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**

**Comment by m-mohamedin** [comment]
Plugin now are disabled by default. You can remove the buggy plugin then enable them
