### ISSUE TITLE
Changing existing shape to another shape using shift-click does not work

### ISSUE THREAD

**Issue by WizDig** [jgraph/drawio-desktop#1308]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
In previous versions (like 20.8.16) I could replace an existing shape with a template shape from the shape side panel with a shift-click. In the newer versions (like 21.2.1) this does not work any more. This is a documented feature: https://www.diagrams.net/doc/faq/uml-lifeline-shape-change

**To Reproduce**
1. Go to existing diagram
2. Select an existing shape
3. Go to the shape side panel and shift-click on a different shape
4. Existing shape is **not** updated

**Expected behavior**
Shape should be changed to the shift-clicked shape

**Screenshots**
N/A

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 21.2.1

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprice (using the no-installer)

**Additional context**
none

**Comment by alderg** [comment]
This works for me. What was the existing and what was the other shape? (Does it work for, say, a rectangle and an ellipse?)

**Comment by WizDig** [comment]
> This works for me. What was the existing and what was the other shape? (Does it work for, say, a rectangle and an ellipse?)

Hi, 
You are right that it works if the existing or other shape is a General type shape. So the issue is more specific.

In this case I am working with BPMN 2.0 shapes. If the existing shape and the other shape (the new shape) are both part of the same BPMN 2.0 category the shape will not change. 
For example, add a Generic Task shape (BPMN 2.0 Tasks) on an empty diagram and try to do a shift-click to change it to the Standard Loop task. 

Maybe the shift-click implementation does not look at new style parameters between the shapes as the basic parameters are all the same in this case.

It was working fine in version 20.8.16

**Comment by davidjgraph** [comment]
In core 21.3.4

**Comment by WizDig** [comment]
Hi,
Tested in the new version of 21.3.7 and the issue is resolved. 
Thanks.
