### ISSUE TITLE
Export to .vsdx Fails with TypeError: Cannot read properties of undefined (reading 'style')

### ISSUE THREAD

**Issue by brynne8** [jgraph/drawio-desktop#1309]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
While attempting to export a draw.io diagram to .vsdx format, the operation failed and an error was displayed in the developer console. The error message is: "TypeError: Cannot read properties of undefined (reading 'style')".

**To Reproduce**
Steps to reproduce the behavior are currently unclear. The error occurred during an attempt to export a diagram to .vsdx format.

**Expected behavior**
The expected behavior was for the diagram to be successfully exported in .vsdx format without any errors.

**Screenshots**
No screenshots are available. However, the error message from the developer console reads as follows:
```
TypeError: Cannot read properties of undefined (reading 'style')
    at c (extensions.min.js:1063:44)
    at p (extensions.min.js:1074:84)
    at x (extensions.min.js:1076:129)
    at T (extensions.min.js:1083:206)
    at VsdxExport.exportCurrentDiagrams (extensions.min.js:1083:461)
    at App.<anonymous> (app.min.js:11900:99)
    at app.min.js:181:107
```

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.2.1

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
No additional context is available at this time. The issue pertains specifically to exporting diagrams in .vsdx format.

**Comment by brynne8** [comment]
Additional info about this issue:

I analyzed the problem and found that `mxGraphView.prototype.getState` is not guaranteed to generate a new state, as

```js
mxGraphView.prototype.getState = function(cell, create)
{
	create = create || false;
	var state = null;
	
	if (cell != null)
	{
		state = this.states.get(cell);
		
		if (create && (state == null || this.updateStyle) && this.graph.isCellVisible(cell))
		{
			if (state == null)
			{
				state = this.createState(cell);
				this.states.put(cell, state);
			}
			else
			{
				state.style = this.graph.getCellStyle(cell);
			}
		}
	}

	return state;
};
```

If the state is null but the cell is not visible, then it won't create a new state for the cell, which will cause the following [applyMxCellStyle](https://github.com/jgraph/drawio/blob/6379dc675d2b84d3268ae8c7d3b963b6c8880d3c/src/main/webapp/js/diagramly/vsdx/VsdxExport.js#L577) function to raise an error.

```
TypeError: Cannot read properties of undefined (reading 'style')
```

as it tries to read the style of the state.

**Comment by davidjgraph** [comment]
Closing, no repo provided.
