### ISSUE TITLE
High refresh rate (>60Hz) support

### ISSUE THREAD

**Issue by yasamoka** [jgraph/drawio-desktop#131]
First of all, I would like to thank all the contributors for this fantastic platform.

I have the following specs:
CPU: Intel Core i7 5820K @ 4.3GHz
RAM: 16GB
GPU: NVIDIA GeForce GTX 1080Ti
Display: Viewsonic XG2703-GS - 2560x1440 165Hz G-Sync
OS: Ubuntu 19.04

Running draw.io in Mozilla Firefox renders the diagram I am currently working on at a pretty much flawless 165FPS. Enabling the Firefox framerate overlay through setting layers.acceleration.draw-fps to true corroborates this - the average framerate shown goes up to around 163FPS the more I scroll fast horizontally and the total render time maxes out at around 3.5ms and definitely less than 4ms, meaning it is sufficient for even 240FPS.

However, the draw.io Desktop version seems to be limited to 60FPS. I tried rummaging through the source code but was unable to find anything that points to some sort of enforced framerate lock.

Is this limitation part of the Electron framework, or somewhere else? Is a fix possible?

I would be very thankful if you would point me in the right direction.

Thank you again for this amazing platform.

**Comment by ashrafteleb** [comment]
We don't limit framerate. Most probably it's Electron or Chrome issue

**Comment by hholst80** [comment]
Might be related. https://bugs.chromium.org/p/chromium/issues/detail?id=535392

**Comment by yasamoka** [comment]
I believe that's an old bug. It's been resolved. Chrome runs 165Hz here. Didn't re-test the draw.io desktop app though.

**Comment by davidjgraph** [comment]
I'll close this up, if anyone still sees the issue any us know.
