### ISSUE TITLE
Failed updates from v20.8.10 on win7x64

### ISSUE THREAD

**Issue by git29jet** [jgraph/drawio-desktop#1311]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Last good release to install correctly
draw.io-20.8.10-windows-installer.exe

Attempts to update via internal program updater OR new install via dl of latest release result in this error message after install completion when program attempts to open:
"draw.io.exe - Entry Point Not Found
The procedure entry point DiscardVirtualMemory could not be located
in the dynamic link library KERNEL32.dll.
OK"

Reinstalling v20.8.10 works correctly & program opens w/o errors

**Desktop (please complete the following information):**
Windows 7 x 64 w/updates & 0Patch service applied

**Comment by davidjgraph** [comment]
21.1.2 was the last windows 7 supported version. Manually install that and when prompted for updates tick the don't ask again box.
