### ISSUE TITLE
snap package depends on the old core18 base snap

### ISSUE THREAD

**Issue by LaurentBonnaud** [jgraph/drawio-desktop#1313]
Hi,

**Is your feature request related to a problem? Please describe.**

The snap package depends on the old `core18` base snap:

```
$ snap info drawio --verbose
[...]
base:         core18
```

**Describe the solution you'd like**

It should be updated to depend on a more recent core snap (`core20` or `core22`)

**Additional context**

drawio is one of the few snaps still depending on `core18`.  Updating it would allow to remove core18 and free up space on systems.

**Comment by boukendesho** [comment]
+1

**Comment by davidjgraph** [comment]
Electron builder defaults to core20, according to the docs. I'll mark this to close until someone can show that is incorrect.

**Comment by LaurentBonnaud** [comment]
I confirm that drawio now depends on core20.  Thank you for the update!
