### ISSUE TITLE
Excel add-in: White screen

### ISSUE THREAD

**Issue by Bosse1976** [jgraph/drawio-desktop#1319]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
It worked fine, but suddenly when we open Excel, the Draw.io Add-in only gives a fully white screen, so the normal functionallity is missing. To try to fix it, we updated the Draw.io application to the latest version, and we also tried to reinstall the Add-in, but the problem still exists.

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
- <img width="263" alt="Schermafbeelding 2023-05-10 113124" src="https://github.com/jgraph/drawio-desktop/assets/109293671/0f818226-47ef-43b9-8ab9-ee38aa5c3f99">

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 21.2.8

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
-

**Comment by davidjgraph** [comment]
This is the project for drawio desktop only.
