### ISSUE TITLE
Release downloads are failing?

### ISSUE THREAD

**Issue by nmenon** [jgraph/drawio-desktop#132]
$ wget https://github.com/jgraph/drawio-desktop/releases/download/v10.9.5/draw.io-amd64-10.9.5.deb

`--2019-07-22 10:52:36--  https://github.com/jgraph/drawio-desktop/releases/download/v10.9.5/draw.io-amd64-10.9.5.deb
Resolving webproxy.ext.ti.com (webproxy.ext.ti.com)... 10.248.194.18, 10.248.194.19, 192.91.66.131, ...
Connecting to webproxy.ext.ti.com (webproxy.ext.ti.com)|10.248.194.18|:80... connected.
Proxy request sent, awaiting response... 500 Internal Server Error
2019-07-22 10:52:37 ERROR 500: Internal Server Error.

`
I did notice https://github.com/jgraph/drawio-desktop/issues/14 -> I tried two different networks, tried firefox and chrome in addition to wget

**Comment by davidjgraph** [comment]
It's something we have any control over, you would have to ask github.

**Comment by nmenon** [comment]
Hmm.. I did notice https://github.com/microsoft/vscode/issues/72438 -> will try and report this to github support.

**Comment by nmenon** [comment]
@davidjgraph  Ticket ID: 319762

**Comment by davidjgraph** [comment]
https://twitter.com/search?q=github%20download&src=typed_query&f=live
https://www.githubstatus.com/

**Comment by nmenon** [comment]
@davidjgraph gee thanks. I guess just bad timing on my side :(

Thanks for an excellent tool btw.

**Comment by nmenon** [comment]
@davidjgraph looks resolved now. Sorry for the noise.

**Comment by davidjgraph** [comment]
No worries, does raise the point that the releases exist nowhere other than Github, might think about mirroring.
