### ISSUE TITLE
Procedure entry point could not be located in the dynamic link library

### ISSUE THREAD

**Issue by patefoniq** [jgraph/drawio-desktop#1324]
I can't run this software due to the message like below:
`the procedure entry point discard virtual memory could not be located in the dynamic link library draw.io.exe`.

Problem has started from the version [21.2.1], while [21.1.2] works without any issues.

OS: Windows 8.1 x64 with the latest updates.

**Comment by davidjgraph** [comment]
21.1.2 was the last version that supports Windows 8.
