### ISSUE TITLE
alt+left click not work since version 21.2.1

### ISSUE THREAD

**Issue by missuor** [jgraph/drawio-desktop#1327]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

**To Reproduce**

Version: 20.8.16
![image](https://github.com/jgraph/drawio-desktop/assets/4561294/0ac0af91-8b65-4468-82fa-320279e05c13)
![image](https://github.com/jgraph/drawio-desktop/assets/4561294/ffc2a149-d672-4610-bd7f-ed5e69d02a88)

Version: 21.2.8
![image](https://github.com/jgraph/drawio-desktop/assets/4561294/f8aa44f6-1fdc-46fe-9701-cdff8d9fd798)

20.8.16 is ok，and  21.2.1 、 21.2.8 has bug 
![image](https://github.com/jgraph/drawio-desktop/assets/4561294/0b8c8cd0-52ce-4af6-8989-24a671606d99)

The functions in the 20.8.16 version are correct, but there are bugs in the 21.2.1 and 21.2.8 versions. When using the keyboard and mouse to add icons, there is no response
same proble with  alt|alt+ctrl|alt+shift  + left click  

env：
![image](https://github.com/jgraph/drawio-desktop/assets/4561294/2e3f63e5-0157-424f-aa25-4d356412aae4)

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...

**Additional context**

**Comment by missuor** [comment]
Am I the only one experiencing this problem?
Last night I reinstalled my laptop, downloaded the latest version of drawio, and then encountered this phenomenon again. I thought there was a problem with my computer. I thought of this when I was using another computer in the morning. Suddenly I remembered that I had reported a BUG before. It has been so long, and the version has been updated, but this problem that seriously blocked the use has not received any attention. I'm not sure if this problem only occurs in my environment.

**Comment by missuor** [comment]
![Peek 2023-09-18 11-09](https://github.com/jgraph/drawio-desktop/assets/4561294/b32791ce-7976-4418-af7b-3fcb9ac39853)

**Comment by missuor** [comment]
Has anyone encountered the same problem?

**Comment by davidjgraph** [comment]
You will encounter banning if you don't stop bumping.

**Comment by missuor** [comment]
装个什么臭逼？
我非常详细的提供BUG路径，问题复现截图，花大量时间复现问题，怕开发人员找不出来问题还又是截图又是录屏解释。

我提交的问题好几个月没有任何人关注过。时间久远到我自己都忘记了自己提交过！

我再次遇到同样的问题，补充了问题说明和路径，第三次又遇到了同样的问题，上来搜索一下有没有人遇到同样的问题，结果发现问题依然没有任何动静，这并不是什么特别复杂的路径不是么？

怎么我补充了一下BUG的描述说明等，咨询一下是否有人遇到同样的问题就击中了@davidjgraph 你的G点？

我花费了大量时间来反馈问题，怎么你还不乐意了？我关闭这个问题可还行?
