### ISSUE TITLE
Background page relation lost when opening copy of the diagram from PDF file, works OK for PNG

### ISSUE THREAD

**Issue by hatramatra** [jgraph/drawio-desktop#1328]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When exporting a diagram to PDF file, it is possible to include the copy of the diagram. When the exported PDF file is being opened again by drawio, the information about their background pages is lost. This works OK with PNG export and included copy of the diagram there.

**To Reproduce**
1. Create diagram with two pages, one being a "background" page for the other.
2. Export the diagram to PDF format
3. Open exported PDF file in drawio again
4. Background content is messed up on pages referring to background page and the relation to the background page is lost

**Expected behavior**
It is expected, that information about the background page is preserved in the diagram copy included in the PDF file, same as in PNG file

**Screenshots**
See attached exported PDF file

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.2.8

**Desktop (please complete the following information):**
 - OS: Linux...

**Additional context**
See example PDF export with included copy of the diagram:
[pdf-export-bug.pdf](https://github.com/jgraph/drawio-desktop/files/11546214/pdf-export-bug.pdf)

**Comment by m-mohamedin** [comment]
As a workaround, please use File->Open instead of import or DnD
