### ISSUE TITLE
Bad characters in file dialog on save/export

### ISSUE THREAD

**Issue by bsimpson** [jgraph/drawio-desktop#1332]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

Ubuntu snap package 21.2.8 shows a buggy file dialog when saving or exporting to PNG/JPG/etc. This does not happen on the web.

**To Reproduce**
1. Create a blank diagram
2. File -> Save
3. Buggy file dialog is shown

**Expected behavior**

A functional file dialog is shown with file and directory names instead of broken characters

**Screenshots**

![image](https://github.com/jgraph/drawio-desktop/assets/3703/bd706efd-69af-4dad-b335-d6fc5b4b803b)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.2.8

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 23.04)

**Additional context**

**Comment by davidjgraph** [comment]
Duplicate #368
