### ISSUE TITLE
File corruption: File is truncated when inspected.

### ISSUE THREAD

**Issue by askpatrickw** [jgraph/drawio-desktop#1334]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Corrupted file
`Not a diagram file (error on line 820 at column 11613: AttValue: ' expected)` is the error.

**To Reproduce**
UNKNOWN

**Expected behavior**
I've been working on this file on and off for a year.
I tried to open it the other day and the file won't open.
`Not a diagram file (error on line 820 at column 11613: AttValue: ' expected)`

I looked at the file in VS Code and the XML is truncated \ seems incomplete.

mxfile, diagram, root are not closed.
The last element is mxCell which is also unclosed.

I save to an iCloud sync'd HD location on MacOS Ventura 13.4 (22F66)

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 21.2.8

**Desktop (please complete the following information):**
MacOS Ventura 13.4 (22F66)

**Additional context**

I save to an iCloud sync'd HD location.
I tried downloading the file from iCloud and it was also truncated.

**Comment by Narvath** [comment]
Similar situation here, updated to the latest version (21.4.0), added 2 pieces of text, 2 rectangles and 2 crosses (x) (all standard assets) and after closing and reopening, I get the same error, but with a different line and column. It was saved on a local shared drive.

If you find an answer, please let us know!

**Comment by davidjgraph** [comment]
Moving to #1366
