### ISSUE TITLE
Add option for 5 group grid lines

### ISSUE THREAD

**Issue by andreinagy** [jgraph/drawio-desktop#1335]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I would appreciate an option for the grid to have 5 subdivisions like milimetric paper.
There are options to customize the grid size in diagram > grid and page setup, but the grid always has 4 subdivisions.
I'm not used to imperial units and trying to make lines of speciffic dimensions involves some mental arithmetic.
![draw io](https://github.com/jgraph/drawio-desktop/assets/4987417/9ab66767-ac09-4245-9b0f-c68124120d36)

**Describe the solution you'd like**
A dropdown in the diagram > grid for example where I would be able to select a 4 group grid 5 group grid (not sure if logarithmic makes sense).
![milimetric](https://github.com/jgraph/drawio-desktop/assets/4987417/2d115288-a527-41d1-8dba-992e148828e7)

**Describe alternatives you've considered**
I'm trying to mock a real world object I want to create as a hobby, I tried getting used to the existing grid and it's unintuitive that 10mm looks like two 4 square groups + another half group. So I always have to do mental math whereas milimetric paper is intuitive to me.
I could try using a milimetric paper texture as an image sent to back.

**Additional context**
First I want to thank you for creating this great software! I'm using it for a few years and have recommended it to colleagues.
This is just a nice to have feature for me, but possibly much more helpful for others.

**Comment by alderg** [comment]
Try [this configuration](https://app.diagrams.net/#_CONFIG_UzV3UjUySi/KTAkuSS0oBrJVjR1NVc1dAA==):

`
{
  "gridSteps": 5
}
`
