### ISSUE TITLE
Hiding one layer also hides elements from a different layer

### ISSUE THREAD

**Issue by Cypone-X** [jgraph/drawio-desktop#1339]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When using layers, a connection line (arrow) between 2 objects is regarded as part of the respective objects layer if we hide the layer, even if the connection line is assigned to a different layer.

**To Reproduce**
1.
create at least 2 layers, the first one with some objects (icons, squares etc) and the 2nd layer with a connection line/arrow between the objects in the first layer:
![image](https://github.com/jgraph/drawio-desktop/assets/135949361/76884fdd-9d6c-47e2-913e-8313a04142aa)

2.
when hiding the "connect" layer, the connection line is hidden and only the circles from "objects" layer remain visible, which is the expected behaviour:
![image](https://github.com/jgraph/drawio-desktop/assets/135949361/c3e0d492-cd11-4110-9b83-1601f69f02c4)

3.
but when hiding "objects" layer, the connection line is also hidden, even if the "connect" layer should be visible:
![image](https://github.com/jgraph/drawio-desktop/assets/135949361/faa68f3a-22f8-4def-ae0f-2665be057554)

**Expected behavior**
The expected behaviour is that when hiding the layer named "objects", the connection arrow should be visible, as it's part of a different layer named "connect"

**Screenshots**
Added screenshots above

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.2.8

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by mararad** [comment]
Hi,

Do you see the same behaviour in the latest 21.5.0 version?
If you do, please attach the file. 
Shapes can be connected in different ways so the diagram will help.

Thanks,

**Comment by Cypone-X** [comment]
Hello,

I tested also with the latest version (21.6.1) and it's the same behaviour.
I attached a simple diagram with 2 layers:
[layer_display_issue_on_21.6.1.drawio.zip](https://github.com/jgraph/drawio-desktop/files/12160662/layer_display_issue_on_21.6.1.drawio.zip)

Thank you!

**Comment by davidjgraph** [comment]
That's the expected behaviour. This is a diagramming (node/edge) tool, rather than just whiteboarding. An edge is hidden if none of its connected nodes are visible.
