### ISSUE TITLE
On xmonad: scroll bar appears on exported png

### ISSUE THREAD

**Issue by aiya000** [jgraph/drawio-desktop#134]
## version

Arch Linux * drawio-desktop 11.0.5-1

```
aur/drawio-desktop 11.0.5-1 (+14 1.00%) (Installed)
```

## Problem

Hi, I like draw.io very much :smiley:

I have a simple problem.
I did `$ draw.io --export --format png c-2-product.xml` to make `c-2-product-xml.png`,
but unexpected scroll bars shew on the gotten `c-2-product-xml.png`.

![c-2-product.xml.png](https://user-images.githubusercontent.com/4897842/62200182-d7abd980-b3bf-11e9-982a-ae49129bc332.png)

- [c-2-product.xml](https://gist.githubusercontent.com/aiya000/7a5ea83344be0b584ec4aa090369e3c8/raw/0181504188823f5db2160b1fc45b7b63cf71ead7/c-2-product.xml)

Please help x(

**Comment by davidjgraph** [comment]
Latest version of draw.io desktop is 10.9.5. Can you repeat the problem with our release?

**Comment by aiya000** [comment]
@davidjgraph Thanks!
I tried same cli with https://github.com/jgraph/drawio-desktop/releases/tag/v10.9.5 `draw.io-x86_64-10.9.5.AppImage`, but same problem occurs :sob:

**Comment by aiya000** [comment]
I exported c-2-product.xml.png using GUI, also got scroll bars ~!

**Comment by davidjgraph** [comment]
I just tried 10.9.5 on MacOS 10.14 and don't get scrollbars. You tested 10.9.5 on Linux?

**Comment by aiya000** [comment]
Yes, I tested 10.9.5 on Arch Linux!

**Comment by aiya000** [comment]
I tested 10.8.0 and 10.7.7, and got scroll bars.

**Comment by ashrafteleb** [comment]
I tried on Ubuntu and couldn't reproduce.

Can you please share your Arch Linux setup details. Specifically, what is your desktop environment?

**Comment by aiya000** [comment]
Here is my installation :+1:

(for 10.9.5)

```shell-session
$ yay -S --noconfirm drawio-desktop
```

(10.9.5 and other versions)

- Manually download the appimage from https://github.com/jgraph/drawio-desktop/releases

**Comment by ashrafteleb** [comment]
Unfortunately, xmonad is not currently fully support

As a workaround, add a dummy shape in the bottom-right corner of the diagram such that the scrollbars are on that shape, then crop the image using another software.

**Comment by aiya000** [comment]
Oh, I understood :sob:
I'll use that workaround. Thanks!

**Comment by aiya000** [comment]
I added an empty text :point_down:
![Screenshot_2019-08-13_16-55-59](https://user-images.githubusercontent.com/4897842/62924641-7cc8a800-bdeb-11e9-98d5-e5d2952b0f7d.png)

Then I succeed to avoid this problem without cropping the image :+1:

**Comment by jinjamator** [comment]
FYI: I can reproduce this with the current windows version aswell
