### ISSUE TITLE
dragging a folder from a Finder window to Export dialog must not move the folder

### ISSUE THREAD

**Issue by ernest-bruce** [jgraph/drawio-desktop#1341]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

**To Reproduce**
1. create a diagram
2. choose File > Export as > PNG…
3. from a Finder window of a different folder, drag a folder into the Export dialog
4. note that the dragged folder is moved from the Finder window into the dialog *and* the action is reflected in the filesystem
=> dragging a folder from a Finder window into an Export dialog must not change the filesystem

**Expected behavior**
the active folder in the Export dialog changes to the dragged folder

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: macOS
 
<img width="952" alt="Screen Shot 2023-06-08 at 18 12 46" src="https://github.com/jgraph/drawio-desktop/assets/6908514/d0ab3e05-543d-47cb-9dda-7bb122924122">
<img width="796" alt="Screen Shot 2023-06-08 at 18 14 41" src="https://github.com/jgraph/drawio-desktop/assets/6908514/0f7a118e-a0b2-489e-82a9-7e908ecad55a">
<img width="811" alt="Screen Shot 2023-06-08 at 18 15 13" src="https://github.com/jgraph/drawio-desktop/assets/6908514/bdb59a2c-4391-4b34-aa54-498738478fd4">
<img width="952" alt="Screen Shot 2023-06-08 at 18 15 19" src="https://github.com/jgraph/drawio-desktop/assets/6908514/0f9f26f5-f9cf-4d4b-9fc1-8810ac5f73ef">

**Additional context**

**Comment by m-mohamedin** [comment]
Unfortunately, this is how MacOS works. Also, latest version of MacOS doesn't behave like that
