### ISSUE TITLE
no diagram file error

### ISSUE THREAD

**Issue by nielskoomen91** [jgraph/drawio-desktop#1342]
hello,

i have a problem with Draw.io desktop app.
it seems that the files I save are corrupt some how.
is this something I can fix?

I get the following message;
Geen diagrambestand (error on line 220 at column 218649: AttValue: ' expected)

I use the latest version of Draw.io desktop app (MAC)
file is attached in zip file.

![Scherm­afbeelding 2023-06-09 om 10 40 07](https://github.com/jgraph/drawio/assets/136069308/508d29de-b60b-40e4-943d-28ed974438a4)

[Schema tekening Vision stage V2.drawio.zip](https://github.com/jgraph/drawio/files/11704258/Schema.tekening.Vision.stage.V2.drawio.zip)

**Comment by alderg** [comment]
Is there a file called ~${filename}.bkp or a file called {filename}.crswap in the directory where the file was originally saved (where {filename} is the name of the original file, eg. MyDrawing.drawio)?

**Comment by Narvath** [comment]
I just got the same error (just another line and column) after updating to 21.4.0 (maybe related?), I can't open my diagram either and the backup that is usually located at the same place is nowhere to be found either.

**Comment by nielskoomen91** [comment]
> Is there a file called ~${filename}.bkp or a file called {filename}.crswap in the directory where the file was originally saved (where {filename} is the name of the original file, eg. MyDrawing.drawio)?

no there is not.

**Comment by davidjgraph** [comment]
What version of desktop were you using at the time?

**Comment by davidjgraph** [comment]
21.2.8. Is the directory you are saving to a synced folder from a cloud drive, like google drive, onedrive, etc?

**Comment by nielskoomen91** [comment]
I don't no for sure.
date of the commend is 2 weeks ago. I was up to date.
now I'm using version 21.5.0
same problem.

**Comment by nielskoomen91** [comment]
I save the files local to a Dropbox folder.

**Comment by Narvath** [comment]
In the meantime I found how to resolve the problem with the files, usually it's missing tags at the end of it.
And as for myself, those problems keep on reappearing everytime I work on a network shared drive. Everything is fine when working g on a local copy

**Comment by davidjgraph** [comment]
@nielskoomen91 dropbox does versioning, doesn't it? What if you download the previous revision of the file from dropbox and use that?

**Comment by alderg** [comment]
Were there concurrent changes? (Ie. did Dropbox fail to merge changes or did our app fail to write to a synced folder?)

**Comment by nielskoomen91** [comment]
> @nielskoomen91 dropbox does versioning, doesn't it? What if you download the previous revision of the file from dropbox and use that?

don't work eether.



> Were there concurrent changes? (Ie. did Dropbox fail to merge changes or did our app fail to write to a synced folder?)

we don't have the problem with other files in the same folder.

**Comment by davidjgraph** [comment]
Moving to #1366
