### ISSUE TITLE
Not a diagram file (error on line 4717 at column 54: Specification mandates value for attribute hei)

### ISSUE THREAD

**Issue by Ahmed196-Abogabal** [jgraph/drawio-desktop#1343]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I get this error message when i open a draw.io file
Not a diagram file (error on line 4717 at column 54: Specification mandates value for attribute hei)
**To Reproduce**

**Expected behavior**
The file should have opened
**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.3.7

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...
Windows
**Additional context**
I need to open the file , it was working fine untill i added some diagram piece then suddenly
it just collapsed

**Comment by davidjgraph** [comment]
Moving to https://github.com/jgraph/drawio-desktop/issues/1366
