### ISSUE TITLE
Deselecting item, by clicking on locked layer area

### ISSUE THREAD

**Issue by r3538987** [jgraph/drawio-desktop#1348]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Unable to deselect item, if performing click on locked layer.

**To Reproduce**
1. Create 2 layers with items, lock one of them (_making it as somehow background layer_) 
2. Select item on non-locked layer, which appears on top of your background. 
3. Try do deselect selected item, by click somewhere where background layer area is. 
4. Item remains selected. 
To deselect : you need no click on entirely empty spot, or try to "draw" tiny selection zone with cursor, or click RMB

**Expected behavior**
Not sure if this is expected behavior, but when was using version 20.3.0 this was not the case. Back then you could deselect item, by click even on locked layer. 

**draw.io version:**
- draw.io version 21.4.0

**Desktop:**
 - OS: Windows 11, 22H2

**Additional context**
When working on big graph, this can be issue, in example if you are used to navigate drawing with arrow buttons. 
- previously, you deselect item, and move around
- now deselection behavior is changed, you try to move around, and now your are moving your item.

**Comment by mararad** [comment]
Hi,
I repeated the behaviour in desktop app 21.5.0 and also in Chrome/FF and Win 10.
Looks like a shape within non-licked layer can't be deselected when the content within locked layer is clicked.

https://github.com/jgraph/drawio-desktop/assets/44292306/458c3c8a-c79f-4b90-8a4f-d4d51fa9d4ca

**Comment by r3538987** [comment]
Checked bunch of older _windows-no-installer_ builds to find when this issue started to occur.
20.8.16 - no such problem,
21.1.2 - issue is present.

**Comment by davidjgraph** [comment]
Fixed in desktop 21.7.5 release. Was fixed in previous core release, desktop just wasn't updated.
