### ISSUE TITLE
External plugins stopped working

### ISSUE THREAD

**Issue by appa1303** [jgraph/drawio-desktop#1352]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
On old versions (e.g. 20.8.16) running DrawIO desktop on windows with the --enable-plugins option, allowed me to load external plugin. In version 21.5.0 this no longer works. 
To verify I tried to load the numbers.js plugin from ...\drawio-21.5.0\src\main\webapp\plugins as an external plugin and it will not work, using the internal version of the plugin works fine.

**To Reproduce**
1. start DrawIO desktop on windows from commandline: C:\Program Files\draw.io>draw.io.exe --enable-plugins
2. Goto extras => Plugin => Add, and add external plugin
3. Restart drawIO
4. The plug in is not working
5. Download the drawIO source from git, locate the numbers.js plugin and install  it as external plugin 
6. The numbers.js plugin is not working 

**Expected behavior**
External plugins should have loaded when running drawio desktop with --enable-plugins

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.5.0

**Desktop (please complete the following information):**
os: Windows 11  

**Additional context**
The plugin I am trying to use worked at least up to version 20.8.16, Since i can't load Numbers.JS also i think it is a problem in drawio desktop

**Comment by davidjgraph** [comment]
Unfortunately, this is a side effect of security measures we have added to the app. The measures are very important, so the plugin functionality will have to longer be a part of the desktop app.

**Comment by appa1303** [comment]
Thank you for the quick reply, 

Since the plugin is a must for us, is it possible for us to rebuild DrawIO desktop without the new security measures ?
Can you please direct us to instruction for the building process ?

**Comment by davidjgraph** [comment]
You can run it up locally using the instructions in the main README.

**Comment by davidjgraph** [comment]
We'll have a better review to see if this is possible to restore.

**Comment by davidjgraph** [comment]
Intended fix in 21.5.1
