### ISSUE TITLE
Upon saving project, a bunch of squares appears instead of text

### ISSUE THREAD

**Issue by CelianGdfrd** [jgraph/drawio-desktop#1353]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Text is completely glitched on the save page of a project.

**To Reproduce**
1. Create a project
2.  Ctrl+S

**Expected behavior**
Everything should be readable

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/31107370/0510955c-7c56-4310-aac5-aceb22dfdc11)

**draw.io version (In the Help->About menu of the draw.io editor):**

draw.io snap 21.5.0

**Desktop (please complete the following information):**
Ubuntu 23.04

**Comment by davidjgraph** [comment]
Duplicate #368 

"I have searched the issue tracker for a feature request that matches the one I want to file, without success."
