### ISSUE TITLE
Provide a program option to enable/disable check for updates at program start

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio-desktop#1355]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When Diagram.net is launched, it checks for update, and alerts the user if there is an update available. 
Its dialog box has an option "do not ask this question again".

If the user selects this option, he does not have any option to turn the option once again.
So once this option is selected, the user will not realize if a new update is available in the future.

**Describe the solution you'd like**
I suggest two separate design changes:

1. Currently, the "check for updates" dialog box has a "do not ask again" option, and the user is allowed to click on that option itself. When he clicks there, the OK and Cancel buttons are bypassed. IMHO this is wrong design. Instead of this, the "Do not ask again" option should be a checkbox (not a clickable control). After this, if the user selects "Yes", that means the program will keep checking for updating. If the user selects "No", the program will stop checking for updates.

2. Diagram.net should have a **Tools >Options** menu, which opens the **program options** dialog. That dialog should have all program options such as "check for updates on launch"

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
24.5.1 adds the startup parameter --disable-update. If you then add to manually check for updates you can do so.
