### ISSUE TITLE
v21.5.0 cannot run on Windows 7 64-bit

### ISSUE THREAD

**Issue by JohnnyLee91** [jgraph/drawio-desktop#1358]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
V21.5.0 can be successfully installed on Windows 7 SP1 64-bit system, but I got an error when open it:
Entry Point Not Found : The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll. 

**To Reproduce**
1. Run draw.io.exe as administrator.
2. You may got none respone after running it, if so, open eventvwr.msc to see the error info:
Windows Logs -- System -- Information (Source: Applicaiton Popup) :
Application popup: draw.io.exe - Entry Point Not Found : The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll. 

**Expected behavior**
None.

**Screenshots**
None.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.5.0

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate 6.1.7601 SP1

**Additional context**

**Comment by davidjgraph** [comment]
21.1.2 was the last windows 7 and windows 8 supported version. Manually install that and when prompted for updates tick the don't ask again box.

**Comment by JohnnyLee91** [comment]
thx

**Comment by mocallins** [comment]
I've got this same basic error with different entry point

![image](https://github.com/jgraph/drawio-desktop/assets/1242690/95c2a773-c156-4e3c-9eb4-b0960380c9cd)


draw.io version : 22.0.3

OS: Windows 8.1 Pro

I've tried reinstalling, installing 32bit version, same error

**Comment by davidjgraph** [comment]
Windows 8 isn't supported. You need to use 21.1.2.

**Comment by mocallins** [comment]
Thanks, will do.

    On Saturday, October 28, 2023 at 10:43:42 AM CDT, David Benson ***@***.***> wrote:  
 
 


Windows 8 isn't supported. You need to use 21.1.2.
