### ISSUE TITLE
Accessibility improvements for older eyes

### ISSUE THREAD

**Issue by NetwarSystem** [jgraph/drawio-desktop#1359]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

There are two accessibility issues that I find to be increasingly serious as the years keep coming.

My desktop has a 28" 3840x2160 display. The screen real estate is a benefit for all sorts of things, but there are a groups of applications I am forced to install in a VM in order to use at 1920x1080 resolution. The work area zoom for Draw.io is fine, what is needed is an equally straightforward means of sizing the fonts and icons in the user interface. As I look at the configuration options it _seems_ like there might be a way to do this, but it's not clear how. If what I describe is already possible it would be nice to have a Github repo that's just well commented JSON configuration files.

The other accessibility issue comes from designers interpreting dark mode as stylistic choice rather than a mechanism used to reduce eye strain.  Just as with the work area vs. user interface, it's possible to adjust the drawing background to black, but the user interface's dark is a sort of brown/tan, pouring out photons that make the program harder to use in each moment, and exhausting over the typical amount of time I'd spend on a drawing.

Having started drawing with Visio not long after it first appeared back in the mid 90s, I don't want to sound ungrateful - Draw.io is among the open source crown jewels. But if it were possible to address the two vision related issues I described ... that would be absolutely excellent.

**Comment by AimForNaN** [comment]
I also would like to see at least the ability to set a default page zoom for the electron app. This would cover everything. The app is currently designed for small screens. I'm currently using the app under Ubuntu on a 4K TV, and it also does not recognize that I have `Large Text` enabled for the desktop environment.

https://www.electronjs.org/docs/latest/api/web-frame#webframesetzoomfactorfactor

Current workaround that seems to work is opening the developer tools (Help > Open Developer Tools) and running the following code in the console.

```js
document.body.style.zoom = 1.5;
```

There's no guarantee that this will always be available in electron, and to have to do this manually each time is asking for a lot. Not to mention that this is not a perfect solution, causing mouse to canvas mappings to become inaccurate.

**Comment by davidjgraph** [comment]
21.5.1 adds -z --zoom (float)

Github can't manage multiple things within one ticket, so I have to close this to reflect something is implemented. If the other issue is important please add a ticket for that.

**Comment by davidjgraph** [comment]
24.6.1 adds zoom UI option to help menu.
