### ISSUE TITLE
Draw.io hangs indefinitely when executing within GitLab CI

### ISSUE THREAD

**Issue by ivanli** [jgraph/drawio-desktop#136]
Draw.io version: 10.9.5
GitLab CI runner environment: Windows Server 2012 R2

I'm running draw.io with `--export --border=10 --output=<file>` option before consuming the generated PNG file in a subsequent build step. The `drawio.exe` process hangs indefinitely causing the CI job to never finish. 

When I run the same command through command line on the same machine, it works without issue.

**Comment by ashrafteleb** [comment]
More info please and is this issue is related to #135
