### ISSUE TITLE
dark mode setting is lost

### ISSUE THREAD

**Issue by lvmm** [jgraph/drawio-desktop#1362]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Switching from dark to light mode makes light mode permanent, switching from light to  dark mode doesn't.

**To Reproduce**
Steps to reproduce the behaviour:

prerequisites: dark mode is on

1. start draw.io
2. switch to light mode via the top-right corner crescent icon
3. exit
4. start again - light mode is on, mode setting  was saved between sessions
5. switch to dark mode
6. exit
7. start again - light mode is on, mode setting was lost

**Expected behaviour**
at step 7 dark mode should've been on

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 21.5.0

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by m-mohamedin** [comment]
Should be fixed in v22.1.15
Thanks for the report
