### ISSUE TITLE
UML Class 3, 4 and 5 and Interface 2 shapes don't respect dark mode.

### ISSUE THREAD

**Issue by lvmm** [jgraph/drawio-desktop#1363]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
UML Class 3, 4 and 5 and Interface 2 shapes have hardcoded black separator lines poorly visible in the dark mode - see the attached screenshot.

**To Reproduce**
Steps to reproduce the behaviour:
prerequisites: dark mode is on

1. drag the aforementioned shapes to canvas

**Expected behavior**
The aforementioned shapes should've had light separator lines in dark mode.

**Screenshots**
![uml-dm](https://github.com/jgraph/drawio-desktop/assets/11752339/24a33856-86a6-4228-97f2-7188afceb92d)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 21.5.0

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by lvmm** [comment]
Also UML 2.5 Trigger, Send Signal, Object Node, Activity Partition, Send Object Action and Accept Event Action shapes have hardcoded white background fill which result in white on white text in dark mode.

**Comment by davidjgraph** [comment]
Please re-check with 21.6.1

**Comment by lvmm** [comment]
Yes, all is fine now.
