### ISSUE TITLE
Guidelines not disappearing when using daw.io 25.1.0

### ISSUE THREAD

**Issue by parlconst** [jgraph/drawio-desktop#1364]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Since update to draw.io for desktop 21.5.0, the guidelines which show when moving objects around do not disappear after placement is complete.

**To Reproduce**
Error is not always consistently reproducible, but happens quite often.  Closing the file and reopening solves the problem.  Click on an object and move it - guidelines appear to help line up with other objects.  Once placed the guideline should disappear, but they don't always.  

**Expected behavior**
Prior to this version of draw.io, the problem was not encountered.

**Screenshots**
Screenshot attached 
**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 25.1.0

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
![Error in draw io 25 1 0](https://github.com/jgraph/drawio-desktop/assets/125815072/27503aee-c3c8-4052-944a-3f99c34edf83)

**Comment by parlconst** [comment]
Still not resolved in 25.1.1

**Comment by davidjgraph** [comment]
> draw.io version 25.1.0

There is no such version.

> Still not resolved in 25.1.1

We never said we've fixed it, and there's still no such version.

The issue is tracked in the core editor project as https://github.com/jgraph/drawio/issues/3695

**Comment by parlconst** [comment]
If there is no such version, why is my version number shown as 25.1.1?
![Version screen shot](https://github.com/jgraph/drawio-desktop/assets/125815072/106c8b51-7989-413e-8c9e-9fa2c544297c)

**Comment by davidjgraph** [comment]
It's not....
