### ISSUE TITLE
Saving to synced local folders

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio-desktop#1366]
There's been on ongoing problem for a while regarding saving to folder that has something else actively accessing that folder.

This largely means cloud storage synced folders (think OneDrive, Google Drive, Dropbox, etc), but there have been a couple of reports on this for network drives.

We've had another review to attempt a fix (we have tried previously, but it obviously wasn't the right fix). This review focuses on flushing write streams. Our thinking is that something else is accessing the file prior to a local flush and that causes the file handle to be lost prior to flush.

We've never repeated the issue unfortunately, so please do test 21.5.1 and report to us if you still see this happening.

Note that the last save must have been using 21.5.1, not that you upgraded to 21.5.1 and loaded a file with a problem, that occurred saving in the previous version.

**Comment by davidjgraph** [comment]
Change out in 21.5.1

**Comment by karuna432** [comment]
Hello

I have a similar problem.

draw IO 20.8.16

I am working for a small company. The files are saved to SharePoint Cloud.

I encountered the following error codes:

- Keine Diagrammdatei (error on line 1 at column 1048577: Extra content at the end of the document)
- Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
- Invalid file data   (The file in question has now 0 KB)


I already tried to attach in the editor =</diagram></mxfile> or just </mxfile> but it did not help.

Do you have any ideas for a solution! I would very very grateful!

**Comment by davidjgraph** [comment]
That's a really old version now, please update it. The thread states that the fix is 21.5.1, and you're using a version earlier than the fix...

**Comment by HugoCortell** [comment]
I have the latest version and I seem to be getting that error trying to save to my draw.io folder. Issue fixed by just saving to a folder that does not have a running app, like my downloads folder.
![image](https://github.com/jgraph/drawio-desktop/assets/59887727/7e8914bc-8a8b-4574-950d-5c139119d462)

**Comment by berbakay** [comment]
Hi. I'm seeing this error on v24.6.4.0. 

Not a diagram file (error on line 5909 at column 300: Specification mandates value for attribute parent).

It has been saved in cloud storage folder.
