### ISSUE TITLE
Add Arm64/Aarch64 architecture support

### ISSUE THREAD

**Issue by Nikki-Devil** [jgraph/drawio-desktop#1369]
* [☑] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [☑] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I literally can't use the application since I use Linux on an Arm64 device
(I still can use the webpage but this defeat the purpose of the existence of the app isn't it ?)

**Describe the solution you'd like**
You can try to simply compile the program for Arm64 and/or Aarch64 architecture for every packages along side x86 and x64 architecture

**Describe alternatives you've considered**
Using the webpage version, which works fine, but defeat the purpose of the application existing in the first place since I can't work on it while offline

**Additional context**
I don't know what to say here ^^"

**Comment by davidjgraph** [comment]
Duplicate #1140
