### ISSUE TITLE
snap installation fails

### ISSUE THREAD

**Issue by dshcherb** [jgraph/drawio-desktop#137]
Hi draw.io developers,

Thank you for working on the application and a snap package for it.

I was trying to install a snap downloaded from the "releases" page but it failed with an error.

```
sudo snap install --dangerous ~/Downloads/draw.io-amd64-11.1.1.snap 
error: cannot read snap file: invalid snap name: "draw.io"
```

If I unsquashfs and change the snap name under meta/snap.yaml to "drawio" (removing the dot) and run `snap try` on the unpacked directory I also get the following (which means that under "apps" section a dot cannot be used as well":

```
error: cannot read snap info for /tmp/draw.io/squashfs-root: invalid definition of application
       "draw.io": cannot have "draw.io" as app name - use letters, digits, and dash as separator
```

Could you please change the snap and app name to exclude the dot to make snapd happy?

It would also be good if it was published under https://snapcraft.io/ to avoid using --dangerous during the installation.

Thanks in advance!

**Comment by davidjgraph** [comment]
https://snapcraft.io/drawio
