### ISSUE TITLE
Drawio : PDF export not show valves

### ISSUE THREAD

**Issue by Rabl0** [jgraph/drawio-desktop#1374]
When export a Drawio desing to PDF(application) the symbol of valves changes to  a rectangle.

This issue is resolve when i open the layout  file by web (https://app.diagrams.net/) and export it to PDF, but when I use the app (desktop) valves symbol become a rectangle. HELP (Me)

![image](https://github.com/jgraph/drawio/assets/138307128/dd0b7bb6-c250-466e-b62f-16fd77b142fa)

![image](https://github.com/jgraph/drawio/assets/138307128/814fc9c8-ab64-4585-b24d-18f87360a3cd)

**Comment by alderg** [comment]
Fixed in desktop v21.6.1.
