### ISSUE TITLE
App/Window Header Icon low visibility macOS

### ISSUE THREAD

**Issue by JonoMacC** [jgraph/drawio-desktop#1377]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The app icon in the header of the application chrome to the left of the document title (e.g. "Untitled Diagram.drawio") has low visibility, appearing as white on a transparent background in light mode or black on a transparent background in dark mode. In previous releases, this icon always appeared on the brand color background, following a Google Docs header menu convention. The resulting visibility is low and the appearance does not look intentional.

**To Reproduce**
1. Open a new drawio window
2. Put the appearance in the default mode if it isn't already (i.e. not "Simple")
3. If the header is collapsed, click the double-chevron on the right-most edge of the toolbar to expand the header
4. See icon in top left edge of header.

**Expected behavior**
The icon should be placed on a background with enough contrast that it is clearly visible if its appearance is intentional or the icon should be removed/the header revised to better align with desktop conventions on macOS.

**Screenshots**
<img width="386" alt="Screenshot 2023-07-10 at 08 56 42" src="https://github.com/jgraph/drawio-desktop/assets/39803935/e3a93a01-fb47-498a-929b-3a1d0c1cd803">

**draw.io version:**
- draw.io version 21.6.1

**Desktop:**
 - OS: MacOS

**Comment by davidjgraph** [comment]
It's known and is fixed in the pending release.
