### ISSUE TITLE
Retain view when switching pages 

### ISSUE THREAD

**Issue by lduperval** [jgraph/drawio-desktop#1382]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I switch from one page to the other in my diagram and the focus and Zoom changes

**Describe the solution you'd like**
If I set the position and Zoom to a certain setting, I would like it to remain

**Describe alternatives you've considered**
For now, I use Shift-Ctrl-H to see everything and then zoom in again. But it's tiresome. 

**Additional context**
It doesn't always happen. See here: https://vento.so/view/c40216af-2046-44f6-a07f-5733441744df?utm_medium=share

**Comment by Ragiton** [comment]
+1

**Comment by m-mohamedin** [comment]
The video is showing the zoom level is retained but the view is changed. We couldn't reproduce the issue. We need the diagram in the video to analyze please.
