### ISSUE TITLE
Using image file links in the format of `file:///C:/path/to/file.png` does not work in version 21.5.0 and higher.

### ISSUE THREAD

**Issue by JamesO2x** [jgraph/drawio-desktop#1387]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Using image file links in the format of `file:///C:/path/to/file.png` does not work in version 21.5.0 and higher.

**To Reproduce**
1. Install diagrams.net 21.4.0
2. Add an image using the `file:///` link format.
3. See the image appear.
4. Save your project.
5. Install diagrams.net 21.5.0 or later
6. Open the project.
7. Image links no longer appear in the editor.

**Expected behavior**
Images are loaded and displayed, just like any browser can.

**Screenshots**
A picture of the difference in two versions.
![BUG](https://github.com/jgraph/drawio-desktop/assets/29412392/8826e80d-cdd0-44e5-af02-a8790e2685d9)

I tested multiple versions to verify.
![screenshot](https://github.com/jgraph/drawio-desktop/assets/29412392/52f2d01d-8217-4b76-a9c1-7044a7f05370)

**draw.io version (In the Help->About menu of the draw.io editor):**

## Works In These Versions
diagrams.net 21.2.8
diagrams.net 21.3.7
diagrams.net 21.4.0

## Does Not Work in These Versions
diagrams.net 21.5.0
diagrams.net 21.5.1
diagrams.net 21.6.1

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2

**Additional context**
No additional context. The above should describe the issue clearly.

**Comment by davidjgraph** [comment]
Yes, that change was intentional. Allowing file procotol access from the app creates a decent sized additional attack surface. I can't find whether there was a specific attack against this, but electron's architecture does create an environment where RCEs are easily exposed. We've had to go ultra risk-adverse on everything that could contribute to an attack chain, so there's no possibility we can put this back.

**Comment by JamesO2x** [comment]
@davidjgraph Well that seems strange, since other Electron apps are able to load local images without any security issues that I'm aware of. Browsers themselves have been doing it for decades too, like if I create a local HTML file with associated image files. 

So what are my options then? To use 21.4.0 with potential security vulnerability, or just abandon Drawio all together?

Here's my specific use case, I am using an external python script that does the following:

- Generates thumbnail images from a collection of images in a folder called "img_in" and saves them into a folder called "thumbs"
- Then, the script opens the ".drawio" file as XML, and inserts new elements that contain image links to the files in the "thumbs" directory.
- I can then open the ".drawio" file using Drawio, and reposition the new elements as I see fit.

I'm doing this for a folder of bulk images that would be cumbersome, tedious, and repetitive to do manually. I also want to use image links specifically, because I want to be able to edit the thumbnail images as needed in an external program, and have them update within the .drawio file automatically. Basically I want to use the images in the same way a standard HTML or XML document might reference images.

The default behavior of Drawio is that imported images are converted to a base64 string, which means any changes to the external images would not be reflected in the Drawio diagram. This is less than ideal because it creates duplicate data, and also bloats up the file size of my .drawio document.

I suppose I _could_ modify my python script to convert the images to a base64 string, but then any changes made to any images in the "thumbs" directory would need to be manually re-imported into the Drawio diagram. And we're talking about potentially hundreds of images, which is not fun.

So what are my other options?

Is there not some way you could allow external images with a warning screen? A lot of other software do this. The first example I can think of is Blender: If you load a ".blend" file that was created on someone else's computer that has python scripts inside of it, it will warn the the user (you) with something like "The automatic execution of scripts has been disabled for this document. Do you trust the source of this Blend file?" - with a "YES, run scripts" button and a "NO, block scripts" button.

Could we not have something similar for Drawio, with a warning allowing the loading of local images?

**Comment by davidjgraph** [comment]
> Well that seems strange, since other Electron apps are able to load local images without any security issues that I'm aware of. Browsers themselves have been doing it for decades too, like if I create a local HTML file with associated image files.

Which electron apps are these? Please list only electron apps with the nodeJS integration enabled and a bug process that means any security holes would realistically be found.

Browsers do not have an IPC connection to a complete nodeJS deployment. The surface attack of browsers and electron is not comparable.

If you click on the hackivitiy tabs on https://huntr.dev/repos/jgraph/drawio/ you will find about 4-6 RCEs in the desktop. These are critical security holes. In order for the desktop app to continue as a realistic project, we had to shut down every possible route to creating a security chain.

To repeat my answer from https://github.com/jgraph/drawio-desktop/issues/1070 , I don't want to be responsible for the security implications of allowing arbitary protocols.

**Comment by JamesO2x** [comment]
> Which electron apps are these? Please list only electron apps with the nodeJS integration enabled and a bug process that means any security holes would realistically be found.

I don't know how it works under the hood, I'm not an electron programmer, nor know much about NodeJS.

I'm just a user reporting unexpected behavior with Drawio.

But to answer the question, "Obsidian" comes to mind as an example - its literally entirely based on loading local markdown files and images directly from a user's selected folder. I believe it locks down its given "vault" directory to some degree, but any files in that directory (or its subdirectories) can be altered outside of Obsidian and changes are reflected in the app immediately. Its designed entirely to be interoperable in that way.

You'd have to investigate how exactly they perform those actions. I'm pretty sure it only stores references to files as relative paths like `images/example.png` (standard MarkDown) and logs them all in a database-like JSON format or something. I don't really know the specifics.

> These are critical security holes. In order for the desktop app to continue as a realistic project, we had to shut down every possible route to creating a security chain.

That makes sense, sure. Understandable.

> To repeat my answer from #1070 , I don't want to be responsible for the security implications of allowing arbitary protocols.

I'm not asking you for "arbitrary protocols", I'm just asking for displaying PNG images loaded from my own machine. I don't _specifically_ care if the method to accomplish this uses the insecure `file:///` protocol or not, I just want the local image to be linked in some way so that changes made outside of Drawio are reflected in the document when it is reloaded. If the `file:///` method of linking images is insecure, then yeah, plug that hole up. Let's completely forget about the `file:///` protocol then, and move on. 

That said, I would like _some_ sort of alternative for displaying local images. Is there not a protocol (custom, stock, or otherwise) that could securely access a specific _whitelist_ of **just image file types** without allowing some arbitrary malicious code injection or something? Like some sort of "filter" that checks a file header to ensure that it is indeed an image and not something else?

On a related note, when I load an image into Drawio (either by dragging the image file onto the canvas, or using the "open" dialog) what method is that using to load an image, and how is that method "secure", and why would that not be a viable method for loading an image from a stored string of a relative path? It clearly also has to load a local file from my machine at least once (which is then converted into a base64 string and stored in the .drawio XML itself).

**Comment by davidjgraph** [comment]
Obsidian doesn't allow direct access from the webview to the underlying file system. It works via the IPC bridge. They also don't have a bug bounty program that I can find. Until we started our bug bounty program we thought we were secure...

Let me put it this way. If we add support for file procotol into the webview are you willing to legally bind yourself to pay out all/any bug bounties that occur as a direct result?

We can save time as the answer is no. If you won't then please don't expect me to (I've paid out about $6k so far in attack chains on desktop, this isn't a commercial product, this comes out of my pocket and the other main maintainer (50% each).

If we add an allowlist (which probably requires a weakening of the CSP applied to the web view), why should only you get the exact file type you want? We'd have to allow any request if you allow it for you.

But, it still comes down to will you legally accept liability for this?

**Comment by davidjgraph** [comment]
I just checked direct file procotol access in chrome, it's not allowed:

![Screenshot 2023-07-17 at 11 51 23](https://github.com/jgraph/drawio-desktop/assets/1761087/769bf1fd-3cdb-4eeb-9877-80984bc81498)

https://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode explains there is a flag. If you wanted to disable web security on the chromium build in electron, there's likely a way to do that ( I think it's allow-unsafe-something now), but good luck with that...

**Comment by JamesO2x** [comment]
> Obsidian doesn't allow direct access from the webview to the underlying file system. It works via the IPC bridge. They also don't have a bug bounty program that I can find. Until we started our bug bounty program we thought we were secure...

Ah I see. I have no idea what an IPC Bridge is, but I can take an educated guess that it "bridges" two different internal systems to make the file loading work. And from what you're saying, it might not be super secure. I'll have to look into that later.

> Let me put it this way. If we add support for file procotol into the webview are you willing to legally bind yourself to pay out all/any bug bounties that occur as a direct result?
> 
> We can save time as the answer is no. If you won't then please don't expect me to (I've paid out about $6k so far in attack chains on desktop, this isn't a commercial product, this comes out of my pocket and the other main maintainer (50% each).

Ok I get it. I feel like you're getting _really_ hung up on specifically using "file protocol" as if I'm angrily demanding you to make the program less secure at everyone's expense. I am not. I am not angry, nor demanding anything. I don't want the program to be less secure. I'm just trying to understand why the workflow I used previously suddenly doesn't work after updating.

I understand why the changes were made. I understand that using the `file:///` protocol is insecure. We've already established that. I'm just trying to understand why (as a non-developer regular user that I am) there is literally no alternative to accessing my own files than completely disabling web security across the whole app. That seems like such overkill. And if that's the only way, why is that?

I've looked a little further, and it seems like this issue is generally a broader Electron issue, as I'm seeing people mentioning similar problems with other Electron built apps. It seems Electron takes an "all or nothing" approach to security: If you want file access, you have to disable all security features. I'm guessing this has to do largely with fact that its built on top of a web browser technology (Chromium) which makes certain assumptions about file security, and thus these extra restrictions are necessary.

As other people have run into this issue too: https://github.com/electron/electron/issues/23393 and here: https://stackoverflow.com/questions/50272451/electron-js-images-from-local-file-system

But that has me wondering again about the part of my post you didn't address: 

> On a related note, when I load an image into Drawio (either by dragging the image file onto the canvas, or using the "open" dialog) what method is that using to load an image, and how is that method "secure", and why would that not be a viable method for loading an image from a stored string of a relative path? It clearly also has to load a local file from my machine at least once (which is then converted into a base64 string and stored in the .drawio XML itself).

Why does loading images in this way not violate security or require the use of the `file:///` protocol? Is it because "drag and drop" or "open file dialog" use some fundamentally different approach to loading a file? Is it different because its requesting files from the OS itself? And what would prevent a user from loading malicious content in this way?

This is the part that I don't understand, because from my layman's point of view, Drawio can already load local files this way. So what is this approach doing differently?
