### ISSUE TITLE
Add support for third-party/remote plugins

### ISSUE THREAD

**Issue by alnavart** [jgraph/drawio-desktop#139]
HI,

I created this issue in the C4 plugin GitHub https://github.com/tobiashochguertel/c4-draw.io/issues/14 

I don't know the reason of why is not compatible right now. But I need to edit this kind of diagramas, when I open old Draw versions directly redirects to github in order to upgrade. Are there any way to use older Draw versions until this issue can be solved?

**Comment by davidjgraph** [comment]
Are you using draw.io online or desktop (this is desktop project)?

**Comment by davidjgraph** [comment]
Ah, ok, yes, desktop. No the older version has a critical security flaw, we cannot allow it to be used. That your version could have the githib page injected means it has the flaw and you're online to allow the flaw to be exposed.

**Comment by davidjgraph** [comment]
Try 10.9.5 until the C4 plugin is fixed.

**Comment by alnavart** [comment]
Thanks, I tried since 10.7.5 version onwards and doesn't work. But if I try to load the plugin in draw.io works fine.
It seems a problem with permanent loading of plugins, because I also tried with number plugin "https://jgraph.github.io/drawio/src/main/webapp/plugins/number.js" and seems same issue.

**Comment by davidjgraph** [comment]
Ah, this is a remote plugin. No the desktop version doesn't currently support them for security reasons.

**Comment by alnavart** [comment]
Ok, thanks, I will follow the issue in order to have more news about this support or alternatives.

**Comment by jeybee** [comment]
Interested in what the solution is here since forcing an upgrade and then breaking custom plugins isn't exactly ideal.

**Comment by timberviewproductions** [comment]
(I am attempting to load a plugin from localhost)

**Comment by timberviewproductions** [comment]
Not sure why my comment was deleted. I'll restate it. Forcing people to upgrade and in the process breaking custom plugins is not exactly ideal. I am loading plugins from localhost, so look forward to a solution soon.

**Comment by codering** [comment]
For macOS desktop:

1、Download plugin file.  eg: /Users/xxx/c4plugins/c4.js
2、Add plugin in Plugin Panel
      URL: `file:////Users/xxx/c4plugins/c4.js`
3、Apply and restart.

**Comment by alnavart** [comment]
Thanks @codering, I was working with the online editor, but your solution works great.

**Comment by jdstuart** [comment]
I'm running `v12.2.2` and also have this issue.

The plugin I tried to load is https://tobiashochguertel.github.io/c4-draw.io/c4.js.

I tried the solution proposed by @codering above, but it didn't work.

**Comment by davidjgraph** [comment]
We'll add support for third-party plugins, but not remote, they must be installed locally.

**Comment by ashrafteleb** [comment]
Support for third-party plugins from a local file is added now.
