### ISSUE TITLE
[Bug] Apply edit dialog using keyboard doesn't work

### ISSUE THREAD

**Issue by akrpic77** [jgraph/drawio-desktop#1390]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
A feature to Apply Edit Dialog using keyboard was added to [drawio](https://github.com/jgraph/drawio/issues/2438), but never got to the desktop drawio.

**To Reproduce**
1. Add a shape, do the Edit Data...
2. Try to Apply the dialog using keyboard: Ctrl+Enter
4. Doesn't work

**Expected behavior**
Ctrl+Enter should Apply and close the edit data dialog.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.6.1
- OS: Doesn't work on Windows and Linux, not tested on MacOS.

**Comment by davidjgraph** [comment]
Works for me on MacOS 13.4 with 21.6.1, can someone test win?

**Comment by akrpic77** [comment]
I've tested it now with no-install version on another windows 10 machine. it does not work.

**Comment by mararad** [comment]
Tested in Win 10 with 21.6.1 and at my place it doesn't work. Tried with both Edit > Edit data and Edit data in format panel

https://github.com/jgraph/drawio-desktop/assets/44292306/459f8460-b185-40a7-85e4-ffd23887a890
