### ISSUE TITLE
draw.io.exe failed to start by cmd in win11

### ISSUE THREAD

**Issue by zxyqq** [jgraph/drawio-desktop#1393]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
draw.io.exe failed to start by cmd in win11

**To Reproduce**
1. open 'cmd'
2. run command
c:\Apps\draw.io\draw.io.exe --trace-warnings
draw.io gui opened but stay in full blank 
3. See error
01:24:33.749 > Checking for update
(node:39312) electron: Failed to load URL: file:///C:/Apps/draw.io/resources/app.asar/drawio/src/main/webapp/index.html?dev=0&test=0&gapi=0&db=0&od=0&gh=0&gl=0&tr=0&browser=0&picker=0&mode=device&export=https%3A%2F%2Fconvert.diagrams.net%2Fnode%2Fexport&disableUpdate=0&enableSpellCheck=0&enableStoreBkp=1&appLang=zh-CN with error: ERR_BLOCKED_BY_CLIENT
(Use `draw.io --trace-warnings ...` to show where the warning was created)
01:24:37.199 > Update for version 21.6.1 is not available (latest version: 21.6.1, downgrade is disallowed).

**Expected behavior**
draw.io.exe can open only in windows explorer.

**Screenshots**
draw.io gui opened but stay in full blank 
![image](https://github.com/jgraph/drawio-desktop/assets/6967453/42d20f50-5fb3-4149-9b6b-b9d5b0a05605)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.6.1

**Desktop (please complete the following information):**
 - OS: Windows, win11

**Additional context**

**Comment by cowcomic** [comment]
same problem

![image](https://github.com/jgraph/drawio-desktop/assets/4745969/6a20fa12-6f6e-4697-9f66-9fb750402d51)

**Comment by m-mohamedin** [comment]
Unfortunately, we cannot reproduce in the latest version. Is it still an issue?

**Comment by mvf** [comment]
Can confirm that this is fixed. Until recently, `draw.io.exe` would only start when `argv[0]` was an absolute path with an upper-case drive letter.
