### ISSUE TITLE
save as gui full of unreadable font chars

### ISSUE THREAD

**Issue by p92** [jgraph/drawio-desktop#1394]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

**To Reproduce**
1. start drawio
2. choose create a new diagram
3. choose virgin diagram
4. click on save as
5. fileselector appears but with no readable fonts (each char is a rectangle)

**Expected behavior**
the file selector should be displayed with readable fonts

**Screenshots**

![image](https://github.com/jgraph/drawio-desktop/assets/553530/bc6d3fdd-6a10-4755-bf33-3177a4324d70)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.6.1  snap version

**Desktop (please complete the following information):**
 - OS: Linux Kubuntu 23.04

**Additional context**

**Comment by davidjgraph** [comment]
Duplicate #368
