### ISSUE TITLE
Save dialog can not display any text

### ISSUE THREAD

**Issue by DinoCloudlet** [jgraph/drawio-desktop#1396]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The save dialog does not show any text.

**To Reproduce**
Open the save file dialog on an unsaved file.

**Expected behavior**
A save dialog with readable text.

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/18594646/db9c66b7-9317-4aa0-95f8-5bd44c507d17)
![image](https://github.com/jgraph/drawio-desktop/assets/18594646/232f3cd7-0330-4e3e-b96b-b68de7bead3a)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.6.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04

**Additional context**
Other software can use the save dialog as intended.

**Comment by davidjgraph** [comment]
Please actually search other issues rather than just ticking the boxes. This has been reported about 12 times. #368
