### ISSUE TITLE
Background changing to text original on export from web to desktop

### ISSUE THREAD

**Issue by brentspine** [jgraph/drawio-desktop#1399]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

(Issue might be related to #1328 #1250 #1268)

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When transfering a diagram from the webapp to Desktop some text fields or parts of text fields have a changed background (white in my case).

**To Reproduce**
1. Go to app.diagrams.net
2. Create a text field
3. Paste text from a webpage (e. g. Wikipedia) --> Text gets the background of the text field
5. Export the file as `.drawio`
6. Open the file in Desktop
7. Background of the text field changed to white

**Expected behavior**
Keep the background as in the field

**Screenshots**
Webapp
<img src="https://i.imgur.com/5ZWflDc.png">
Desktop
<img src="https://i.imgur.com/132TH31.png">

**draw.io version**

- v21.6.5

**Desktop (please complete the following information):**
 - Windows 11 Version 22H2 (v10.0.22621 Build 22621.1992)

**Additional context**
[‎  ](https://symfonycasts.s3.amazonaws.com/sample.mp3)

**Comment by brentspine** [comment]
Bump

**Comment by davidjgraph** [comment]
Banned for bumping.
