### ISSUE TITLE
chrome extention app v21.2.7 can't run

### ISSUE THREAD

**Issue by z2care** [jgraph/drawio-desktop#1402]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The chrome extention app（version 21.2.7） installed from google app market was alert never support and couldn't be launched.
The extention is great for us, do you have any plan to update it? 

**To Reproduce**
1. Go to 'https://chrome.google.com/webstore/detail/drawio-desktop/pebppomjfocnoigkeepgbmcifnnlndla'
2. Click on 'add to chrome' and wait done
3. It can not be launched after installed.

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
21.2.7, it's from chrome app market.

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...

**Additional context**

**Comment by davidjgraph** [comment]
Google have removed support for all operating systems except for ChromeOS.
