### ISSUE TITLE
shapes with images by url file:/// do not work

### ISSUE THREAD

**Issue by axydraw** [jgraph/drawio-desktop#1407]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Editing a shape an inserting an image by url and protocol file:///x:/path/file.ext does not work any longer with v21.6.5.
This did work in previous versions up to v??.x.y. The protocol http:// however still does work.
Example code: <image src="file:///C:/Users/userid/Desktop/image.png" x="0" y="0" w="640" h="356"></image>
The shapes with file protocol are now just empty.

**To Reproduce**
1. Place an image file in a directory
2. Edit URL with file:///, drive letter, path and file name in the shape
3. Preview or apply the shape and nothing is visible

**Expected behavior**
The local images shall be visible in Draw.io

**Desktop (please complete the following information):**
 - OS: [Win10 Business x64]
 - Draw.io Desktop version 21.6.5

** Remark:
Sorry, I do not know the version of draw.io where the feature with local file:/// URLs has gone.

**Comment by davidjgraph** [comment]
Duplicate of #1070

**Comment by axydraw** [comment]
In our company we created a lot of block diagrams with linked graphic files from a network drive completed with connection points. Now without working links, all draw.io files do not show any graphics and just empty shapes. Apparently this was a complete dead end street. Only workaround could be the transfer of complete image folder structure from network drive to an dedicated intranet web server. Uuuh! But with this method, offline working is no longer possible. With file-protocol this was still possible by synchronizing onedrive, nextcloud, dropbox … and using or substituting defined drive letters.

**Comment by davidjgraph** [comment]
Removing file procotol access was a security fix, it was used as part of a critical severity attack chain. This cannot be reverted.

**Comment by axydraw** [comment]
Thank you David for explanation. That is SW life cycle due to bad attackers using every front- or back door (protocol) they can find.
