### ISSUE TITLE
Host Google Fonts locally

### ISSUE THREAD

**Issue by privacyembrace** [jgraph/drawio-desktop#1408]
Desktop App fetches fonts from Google servers, which is a problem for privacy.

<img width="1274" alt="Bildschirmfoto 2023-07-27 um 18 49 12" src="https://github.com/jgraph/www.diagrams.net-source/assets/59489277/41408a6a-8ecf-41ce-9136-5bd874b51254">

Please host fonts locally to avoid data transfer to google.

**Comment by davidjgraph** [comment]
Please be precise, how do you deem this to be "data transfer to google"?

**Comment by privacyembrace** [comment]
Since I am a lawyer and not a programmer unfortunately I cannot precisely explain, whether data is transferred and, if yes, when and how. But I assume that e.g. the IP address and probably some common device information is transferred to google, when fonts are loaded remotely. I currently have a client request to review drawio desktop app from the data privacy perspective which also includes being sure that the app doesn't send any data to third parties including the developer. Can you confirm this?

**Comment by davidjgraph** [comment]
Being a lawyer you'll understand if I say nothing for which I might be liable for :).

**Comment by privacyembrace** [comment]
Haha! Sure, but it isn't my intention to make you liable for anything. Instead we are greatful to have the opportunity to use the app for free. However we need to understand, whether the app sends data anywhere and if yes what exactly in order to assess internal data privacy risks. So your help is essential and very much appreciated. You can contact me via email, if it helps. ra@kanzlei-hengstler.de. We can conclude an NDA.

**Comment by davidjgraph** [comment]
An NDA, ok, only a lawyer should suggest that :D. That's not how open source works. I'll open an issue to review all possible connections.

If you want assurances and assessments you're better off with commercial software.

**Comment by privacyembrace** [comment]
Well, I tend to disagree on that since it implies that non-commercial open source software is less privacy friendly which isn't true and shouldn't become real. After all drawio claims on it's website as follows: Bring your storage to our online tool, or go **max** **privacy** with the desktop app. Intrasparency on possible external connections isn't max privacy.

**Comment by davidjgraph** [comment]
Web site fixed.
