### ISSUE TITLE
Possible external connections review

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio-desktop#1409]
Following on from #1408 we should:

- Review the CSP overall. Do we need all of these? Should we make things like google fonts require a load parameter?
- Review the update process. We need to remind people if the version is getting old, we do have security holes. Even if it's just to tell them the URL to check.

**Comment by davidjgraph** [comment]
Current CSP:

`'Content-Security-Policy': ['default-src \'self\'; script-src \'self\' \'sha256-PDJOTCOfwIg8Ri7U2PH1pIpx+haCyKsJEbFxlW6hdSI=\' \'sha256-6g514VrT/cZFZltSaKxIVNFF46+MFaTSDTPB8WfYK+c=\'; connect-src \'self\' https://*.draw.io https://*.diagrams.net https://fonts.googleapis.com https://fonts.gstatic.com; img-src * data:; media-src *; font-src *; frame-src \'none\'; style-src \'self\' \'unsafe-inline\' https://fonts.googleapis.com; base-uri \'none\';child-src \'self\';object-src \'none\';'`

- Remove draw.io and diagrams.net
- Remove google fonts by default and add menu option to enable it

That's no connections.

**Comment by m-mohamedin** [comment]
CSP:
- Remove draw.io and diagrams.net: Done
- Remove google fonts by default and add menu option to enable it: Done (menu: Extras -> Google Fonts)
- Swap style-src unsafe-inline for style hashes from core: In progress

To disable automatic updates, we already have the environment variable `DRAWIO_DISABLE_UPDATE=true`

**Comment by davidjgraph** [comment]
Implemented in 21.7.5. Removal of style unsafe-inline isn't possible at this time.
