### ISSUE TITLE
Missing dependency in the drawio snap

### ISSUE THREAD

**Issue by dshcherb** [jgraph/drawio-desktop#141]
```
snap install drawio --edge

➜  ~ drawio
/snap/drawio/2/drawio: error while loading shared libraries: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
```

It looks like some `stage-packages` are missing in the snapcraft.yaml. Can't seem to find where the snapcraft.yaml used to build the snap is though to find out the full list.

**Comment by davidjgraph** [comment]
We don't have a snapcraft.yml, we'll try adding one.

**Comment by jfunction** [comment]
> We don't have a snapcraft.yml, we'll try adding one.

While you're at it could you please add removable-media as @ASLanin described at https://github.com/jgraph/drawio-desktop/issues/353 - an example is at https://snapcraft.io/docs/snapcraft-interfaces

Thanks for the work on this library!
