### ISSUE TITLE
Some tabs views slip every time I move away and back to the tab

### ISSUE THREAD

**Issue by MScoutsDCI** [jgraph/drawio-desktop#1411]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I have a document with 14 tabs. Most of them are fine but there are a couple of tabs that have this issue. Every time I click bring up one these affected tabs, the diagram view "slips" a bit. It moves up progressively, every time the tab is activated, until the drawing is completely off the top of the screen.

I can hit Enter to center the drawing, but then I click on a different tab and come back, and the drawing has moved up and is not centered anymore.

**To Reproduce**
1. Go to one of the affected tabs
2. Hit the Enter key to center the drawing
3. Navigate away from the tab by clicking on another tab
4. Go back to the first tab and the drawing will have moved up.

**Expected behavior**
If I center the drawing on a particular tab I would expect that view to remain the same if I click away and then back to that tab. This is how most of the tabs are behaving, only a couple are having this issue.

**Screenshots**
These three screenshots are from 1) centering the drawing, 2) navigating away and back to the tab once, and 3) navigating away and back again:
![image](https://github.com/jgraph/drawio/assets/1620509/7e6ff6f1-2fc4-4635-8094-9aa0879255bb)

![image](https://github.com/jgraph/drawio/assets/1620509/7ca53eef-dd78-4af9-a721-5e31e8d10a3a)

![image](https://github.com/jgraph/drawio/assets/1620509/98371381-fbbe-48f0-82e6-1facd9a25c96)

**draw.io version (In the Help->About menu of the draw.io editor):**

- 21.6.5 (desktop version)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser - NA - desktop version

**Additional context**

**Comment by alderg** [comment]
Can you attach the diagram in the affected tab so we can check what the problem is?

**Comment by MScoutsDCI** [comment]
[SDWAN current state.txt](https://github.com/jgraph/drawio-desktop/files/12207090/SDWAN.current.state.txt)

Here you go. I had to rename it to .txt in order to attach it so just rename it back to .drawio

I deleted everything except 4 tabs. The first 2 are acting as expected, the second two are exhibiting the issue I described.

**Comment by seahow** [comment]
I have the same problem, only my cursed tab is offset to the right by about half a page.  Somehow its the content of that tab as the problem moves with it if I select all and cut/paste to a new diagram entirely.

**Comment by davidjgraph** [comment]
We will take a look, but are currently largely shut down for August. Any further reports please thumbs up the original post, rather than write "me too".

**Comment by MScoutsDCI** [comment]
Was this resolved in an update? It's not happening anymore.

**Comment by MScoutsDCI** [comment]
I'm not sure what changed but this apparently was not fixed in an update. Not sure what caused it to stop happening but it's back now.

**Comment by MScoutsDCI** [comment]
Ok, I found the trigger, though not the root cause. This issue seems to be caused by an item's text label sitting on a page break line like this (just realized the vertical dotted line at the bottom might cause confusion. This is just a connector, ignore it):

![image](https://github.com/jgraph/drawio-desktop/assets/1620509/033854ee-1616-4dfc-b39b-72bc38170a99)

Strangely it only seems to happen when the text is on top (top-right and top-left included). And it is only triggered by text, not by the item itself sitting on the line. Deleting the text label stops the issue. Though moving the text up using the spacing controls does not make a difference.

I've been able to replicate the issue in a brand new tab, placing one item at random (any items seems to work), double clicking the item and typing anything, putting the text on top, then dragging the item to the top of the current area, forcing an additional section to appear. If the text sits on the dotted line (whether or not the page line is visible), the issue occurs. Moving the item up just enough so the text is fully over the line stops the issue from occurring.

**Comment by davidjgraph** [comment]
Could you update to 21.7.5 please and test again?

**Comment by borazem** [comment]
I have similar issue and there is no change in 21.7.5.

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/dcafed05999b8d5b94210f3da0669a2f81401a33

**Comment by timblaktu** [comment]
Same happening here, even with 21.7.5. I've seen this with many shapes, but right now I'm reproducing it by placing a standard cloud shape (which has an insanely large empty perimeter around it) right at one or more page edges. The aforementioned behavior happens, then goes away if I move the shape just a few pixels so it's completely inside the page and not overlapping any page boundaries.

EDIT: the behavior is not consistent across all the objects in all my tabs, which are all identical in terms of the cloud shape approaching page edge. On Some pages I can put the object at 6,6 to workaround the problem, but on other pages, I have to move the object to ~10,10. This is very undesirable bc I'm using pages to generate an "animation" by flipping adjacent and mostly-identical pages to create a sort of motion picture.

**Comment by davidjgraph** [comment]
There's an intended fix in 21.8.2.

**Comment by borazem** [comment]
it is, indeed, thank you very much.
