### ISSUE TITLE
Symantec blocks draw.io-11.1.4 windows desktop applications, described as "Insight Network Threat" 

### ISSUE THREAD

**Issue by jarciolo** [jgraph/drawio-desktop#142]
Symantec blocks draw.io-11.1.4 (windows-installer, no-installer, standalone-exe) windows desktop applications, described as "Insight Network Threat" 

![image](https://user-images.githubusercontent.com/44602963/62753647-18ca7a80-ba9f-11e9-8c87-8f10c0269121.png)

**Comment by davidjgraph** [comment]
Some anti virus will flag us at any given point. Someone need to submit it as a false positive.
