### ISSUE TITLE
When formulas are included, the exported PDF is fuzzy in latex

### ISSUE THREAD

**Issue by XinliHao** [jgraph/drawio-desktop#1420]
For versions 26.6.5 and 21.2.8,  the exported PDF is fuzzy in latex if formulas are included.  When I use version 13.9., this bug is disappeared.

**Comment by Raiden-cn** [comment]
Same question. like this:
![image](https://github.com/jgraph/drawio-desktop/assets/82763858/8465fc3b-1507-4e89-a3a3-b4f505ff9bba)
the $x$ is fuzzy with wired edge color.
It will be fine in version 13.9.
I think it is a bug.
