### ISSUE TITLE
Import CSV and export to another format via command line stopped working since version 20.7.4

### ISSUE THREAD

**Issue by glisterGIT** [jgraph/drawio-desktop#1423]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
the command line capability that allows a text / csv file to be imported and then exported to another drawio format 
 seems to have stopped working since version 20.7.4 

**To Reproduce**
run a command like 
& "C:/Program Files/draw.io/draw.io.exe" -x C:\Temp\draw\test.csv -f xml 

works on 20.7.4 but not a version since

**Expected behavior**
Drawio imports my csv text file like using the arrange  >> import >> adnvanced >> csv option then creates the output file in the desired format

**Desktop (please complete the following information):**
 -im using the windows desktop version

**Comment by emptaj** [comment]
I get the same behaviour on Mac OS. Importing by GUI works fine when using command line just stuck drawio process in background.

**Comment by m-mohamedin** [comment]
Unfortunately, we cannot reproduce in the latest version. Please try and if the issue persists, send us the csv file

**Comment by GordianDziwis** [comment]
Can confirm:

```
❯ drawio -x car-partial-supply-chain.txt
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
Error: Export failed: car-partial-supply-chain.txt
❯ drawio -V
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
22.1.21
```

And it is not a config error on my machine:

```
❯ docker run -it -w /data -v $(pwd):/data docker.io/rlespinasse/drawio-desktop-headless -x basic.txt
Error: Export failed: basic.txt
❯ docker run -it -w /data -v $(pwd):/data docker.io/rlespinasse/drawio-desktop-headless:latest -V
22.1.18
```

**Comment by GordianDziwis** [comment]
Problem is the file suffix `txt`, it works with `csv`.

```bash
mv car-partial-supply-chain.text car-partial-supply-chain.csv
drawio -x car-partial-supply-chain.csv
```
