### ISSUE TITLE
Can't share a file that is located on SharePoint

### ISSUE THREAD

**Issue by shirAsperii** [jgraph/drawio-desktop#1424]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I created a drawing and saved it on OneDrive - On a SharePoint folder.
When clicking the "Share" button available in the app, I receive an error message.

**To Reproduce**
1. Create a drawing and save it on a OneDrive - SharePoint folder
2. Open the drawing
3. Click on the Share button in the app
4. See error message received (screen shot attached)

**Expected behavior**
I would have expected that clicking the Share button, would enable me to share the drawing with other users in my organization.
I would like them to be able to then open the drawing and edit it.

**Screenshots**
Screenshot of the error message is attached.

**draw.io version (In the Help->About menu of the draw.io editor):**
<img width="468" alt="Screenshot_1" src="https://github.com/jgraph/drawio-desktop/assets/111966605/3c688e2b-4341-43fa-a267-6f29574ecbe8">

- draw.io version 21.6.6

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise

**Additional context**

**Comment by davidjgraph** [comment]
drawio desktop can't share files.

**Comment by shirAsperii** [comment]
Is there any other version that does?
What would be the way you recommend for sharing drawings with other users, except for putting the file on Google Drive?

**Comment by davidjgraph** [comment]
The online version can share files.
