### ISSUE TITLE
Drawing is too large

### ISSUE THREAD

**Issue by woerrr** [jgraph/drawio-desktop#1428]
This is a duplicate of a closed ticket: jgraph/drawio#1061

*Update - This error does not happen for my friend when exporting the same file, he is on version 20.3.0

Error when using export as -> FDF -> all pages

Error: Drawing is too large

Steps to reproduce the behaviour:
When using Desktop App (dont use the web version)
1. Go to 'File'
2. Click on 'Export as'
3. Scroll down to 'PDF'
4. Select all pages in a large file

- draw.io version 21.6.8

 - OS: Windows 11

**Comment by AlvaroFierro** [comment]
I'm also facing the same problem, but here's what I did as a temporary solution 

Using desktop app

1. File
2. Export as
3. Advanced
4. Format > PDF
5. Export 

This is only gonna export the tab you're using, but then you can merge those PDFs using a tool like [ilovepdf.com](https://www.ilovepdf.com/). And yes, I know this can be a little tedious, but it works. I'm pretty sure the draw.io team is working on this

- draw.io v21.8.2
- OS: Windows 11 22H2 
- OS Build: 22621.2283

**Comment by woerrr** [comment]
I found a better solution.

I reverted back to version 20.3.0 and now I can export no problem.

**Comment by giedrius15004** [comment]
v22.0.0 same issue. Cannot export larger PDF. Downgraded at the moment to v20.3.0 as @woerrr suggested and it works now.

**Comment by ccgeraldes** [comment]
I have this problem on mac. But in reality drawing is slow as hell, images are really to large. How to relief file size by resizing images? I can't do that it seems

**Comment by AlvaroFierro** [comment]
@ccgeraldes You can try by compressing the file 
Files >> Properties >> Compress

**Comment by ccgeraldes** [comment]
I already did. No success :/

**Comment by AlvaroFierro** [comment]
@ccgeraldes I think is drawio performance, but idk maybe [this could help you](https://github.com/jgraph/drawio/issues/1061#issuecomment-663308250) or maybe uploading the images to some service like imgur or smth similar, and don't use local images

**Comment by woerrr** [comment]
I usually compress the images before I pull them in, 720 kb seems to be the
sweet spot.

**Comment by ccgeraldes** [comment]
My drawing is 32 mb with about 15 images. So I think that's the problem.
But I would expect the app to handle it.

I mean in Visio worked well. Obviously the import didn't down convert
properly enough.

It was a nightmare during last 3 days lol

**Comment by m-mohamedin** [comment]
Limits will be removed in the next release

**Comment by davidjgraph** [comment]
In desktop release 22.1.16.
