### ISSUE TITLE
Remember zoom levels

### ISSUE THREAD

**Issue by andrewslavin** [jgraph/drawio-desktop#1429]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open a diagram I created earlier, and the zoom level for all pages is reset to 100%.

**Describe the solution you'd like**
Please save the last selected zoom level for each page, and apply it when the diagram is reopened.

**Describe alternatives you've considered**
Currently I just zoom in or out as needed each page I need to work on, every time I reopen a diagram.

**Additional context**
None.

**Comment by davidjgraph** [comment]
If multiple people have opened that same diagram, which zoom level is saved?

**Comment by andrewslavin** [comment]
Good question! It would be nice to remember each user's setting, but this is not a cloud product backed by a database. So either the files will have to keep per-user settings, or users' local machines will have to keep per-file settings.

I believe both options are an overkill, and for most use cases just remembering the last zoom level set any user will be enough. Treat zoom level changes the same way as page content edits. I think it's still better than always returning to 100% upon file open.

**Comment by Ragiton** [comment]
this is similar to https://github.com/jgraph/drawio-desktop/issues/1382
