### ISSUE TITLE
Enable layer selection for command-line export

### ISSUE THREAD

**Issue by kanaka** [jgraph/drawio-desktop#143]
The ability to do exports from the command line is a great feature. However, I've run into a limitation with a common workflow. I have some fairly layered diagrams that I would like to export with various layers enabled/disabled (one diagram that is exported in multiple ways with different layer combinations). It would be great to be able to select layers for export via the command line. The command-line currently supports page index and range and it would be great to be able to do a similar thing for layers. The interaction of page selection and layer selection could get complicated but I would settle for layer selection implying a single page.

**Comment by ebousse** [comment]
This would be extremely useful for me as well to create "step-by-step" animated diagrams, where parts of a diagram are uncovered one after another. In the past I had written a script to automatize the creation of each animation step from a Dia file with numbered layers. I would enjoy doing the same with drawio :)

**Comment by ebousse** [comment]
Addendum: the use case I describe just above (exporting layers separately to produce frames of an animated figure) would also be covered by this feature request I had made some time ago: https://github.com/jgraph/drawio/issues/213

**Comment by ebousse** [comment]
:(

**Comment by m-mohamedin** [comment]
Will be added to the next release
-l <comma separated layers indexes>

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/d6e60f9ba3fd1e2b9096a43d8cb9abefbeac977a

**Comment by ebousse** [comment]
Thank you! Would it be complicated to add the same feature for "tags"? It's the same idea, with a different source of data.
