### ISSUE TITLE
Allow configuring default file type (to .drawio.svg)

### ISSUE THREAD

**Issue by shoffmeister** [jgraph/drawio-desktop#1430]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Please add functionality that allows configuring the default file type for new diagrams.

Right now, the "Create New Diagram" dialog always opens with "XML file (.drawio)". Other diagram file types - e.g. `.drawio.svg` are much more convenient to work with when that diagram is embedded into, say, markdown files.

The current behaviour adds a "oh, I need to change the file type" action to creating diagrams; this adds friction.

This is what I would love to see on "Create new diagram":
![image](https://github.com/jgraph/drawio-desktop/assets/3868036/97c0f800-06bd-48f9-bc23-49dce652f3d5)

**Comment by davidjgraph** [comment]
Added in 29.7.8
