### ISSUE TITLE
vsdx files won't load on windows 10

### ISSUE THREAD

**Issue by Urusaitech** [jgraph/drawio-desktop#1431]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Since 21.6.8 release on windows, i can no longer open some vsdx files - the programm stucks on infinite loading screen.

**To Reproduce**
1. On startup page choose "open existing diagram"
2. Choose "all files" in file extention drop_down menu
3. Double click on a vsdx file
4. Startup screen remains

**Expected behavior**
After a file is choosed, loading screen replaces the startup screen, later file opens

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/100962655/4718f9e1-c210-4954-8553-b2a5bade6883)

**To Reproduce in another way**
1. Open windows file explorer
2. Navigate to vsdx file
3. Double click on the file
4. Drawio launches
5. Infinite loading screen

**Expected behavior**
Loading screen passes and file opens

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/100962655/834d80fe-08b2-4bf5-8948-542daac0df74)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.6.8

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 22H2, 19045.3324, Windows Feature Experience Pack 1000.19041.1000.0

**Additional context**
drawio files are opening without issues, previous release 21.6.5 doesn't have this issue.

**Comment by Rick-de-Vries** [comment]
I experience the same issue with this version of draw.io (21.6.8) on MacOS Ventura 13.5. Version 21.6.5 does not have this issue.

**Comment by davidjgraph** [comment]
I can't repeat this with the universal ARM Mac build 21.6.8 and a .vsdx file I have lying around. You say you can't open "some" vsdx files, can you attach such a file?

**Comment by GypsIT** [comment]
I'm experiencing the same issue with the UWP App in Version v21.7.5 on Windows 10.

**Comment by ibbcall** [comment]
I experience the same issue with this version of draw.io (22.0.0) on MacOS Sonoma 14.0.

**Comment by davidjgraph** [comment]
Anyone want to share a file that reproduces the problem...

**Comment by adi-garg** [comment]
[aks-reference-architecture.zip](https://github.com/jgraph/drawio-desktop/files/12796088/aks-reference-architecture.zip)

Please unzip the file and try to open using drawio/use File>Import option of drawio.
It gets stuck in infinite loop.
Using v21.7.5 of drawio here.

Regards,
Aditya Garg

**Comment by majidstd** [comment]
same thing happening to me on macos 14.0 and macbook pro M1. Also, when I am trying to open an existing vsdx files nothing happening.
![image](https://github.com/jgraph/drawio-desktop/assets/22521196/aad5f8d2-f66d-424d-87de-526e44dcbe79)

**Comment by majidstd** [comment]
I tested with other version. 21.6.5 is working. all higher versions are broken. Aslo, in this version images are not loading. mac os 14.0 macbook pro m1.

**Comment by ipnetxyz** [comment]
I can confirm the above 22.0.2 on Macbook Pro 13 (2020, Intel CPU) with MacOS Ventura 13.6 fails to import vsdx files. I've installed 21.6.5 and is working.

**Comment by m-mohamedin** [comment]
Fixed in v22.1.15
