### ISSUE TITLE
pasting from the clipboard makes the cursor jump to beginning of the text field

### ISSUE THREAD

**Issue by christiansievers** [jgraph/drawio-desktop#1432]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
pasting from the clipboard makes the cursor jump to beginning of the text in the same field, or to the beginning of another paragraph in the text 

**To Reproduce**
1. Create a text field
2. enter some text
3. copy some text from somewhere else. It doesn't matter if plain text or formatted text.
4. paste the text. 

**Expected behavior**
The cursor should be at the end of the pasted text

**Screenshots**
n/a

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version v21.6.8

 

**Desktop (please complete the following information):**
 - OS: MacOS 13.4.1

**Additional context**
this might be connected or not: sometimes when undoing the paste (for example when I forgot to paste without formatting (Shift-option-cmd-V), the entire field disappears, with no way to get it back. Its contents are then lost.

**Comment by ThenTech** [comment]
Also similar to https://github.com/jgraph/drawio-desktop/issues/898

This is a very common occurrence for me as well, and very annoying.

Other things that happen:
- Sometimes pasting text inserts the text with a new line after, and the text has the default styling and not the copied styling;
- Sometimes pasting inserts the text on a new line with some hidden object between the previous line and the inserted text that cannot be removed, and then pressing CTRL+Z will remove the text, but insert it somewhere else or let things disappear entirely

In the second example, I think the text is pasted as-is, while the surrounding text is wrapped in divs, so pressing backspace before the just pasted text doesn't merge it with the div on the previous line or something.

**Comment by m-mohamedin** [comment]
I think this is an Electron issue as we cannot reproduce online.

**Comment by alderg** [comment]
Issues with cursor position and pasting have been fixed. Please report new issues here. We'll reopen this if needed.
