### ISSUE TITLE
Remember window state

### ISSUE THREAD

**Issue by andrewslavin** [jgraph/drawio-desktop#1433]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I click on a `.drawio` file and `draw.io` opens as a window, though when I was closing it I had it maximised.

**Describe the solution you'd like**
Remember `draw.io`'s window state at the time it's closed - pretty much all Windows applications do that. Also remember the window's position - I noticed that `draw.io` remembers the window size if I resize it, but not the position.

**Describe alternatives you've considered**
I just maximise the window every time I open a diagram.

**Additional context**
I know I can customise a shortcut to open `draw.io` as maximised. This request refers specifically to starting `draw.io` by clicking on `.drawio` files in File Explorer.

**Comment by m-mohamedin** [comment]
Will be added to the next release

**Comment by davidjgraph** [comment]
In desktop release 22.1.16.
