### ISSUE TITLE
CLI option to control links behaviour in SVG

### ISSUE THREAD

**Issue by Matze693** [jgraph/drawio-desktop#1434]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
/

**Describe the solution you'd like**
As a CLI user, I want to export a diagram as SVG in a CI/CD environment. There is no CLI option to set the behaviour for Links. In my case, I need the option “Open in New Window”.

**Describe alternatives you've considered**
/

**Additional context**
![image](https://github.com/jgraph/drawio/assets/20745992/8bbab203-c4f3-401f-8544-dff6076d25b4)

**Comment by m-mohamedin** [comment]
Will be added to the next release (--svg-links-target (auto [default], new-win, same-win))

**Comment by davidjgraph** [comment]
In desktop release 22.1.16.
