### ISSUE TITLE
Progress bar not shown when downloading new version

### ISSUE THREAD

**Issue by saf-dmitry** [jgraph/drawio-desktop#1436]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Progress bar not shown when downloading new version.

**To Reproduce**
1. Start the app.
2. When a new version is available, you will be asked if you want to download and  install it. Confirm the download.
3. See a little dialog window for showing download progress with a window title stating "draw.io Update" but no "progress" bar or other content, i.e. completely blank.

**Expected behavior**
The download window displays a progress bar like in previous versions.

**Screenshots**
![Screen Shot 2023-09-29 at 16 33 23](https://github.com/jgraph/drawio-desktop/assets/30050534/2cd56be5-e0be-4538-954a-cf7631b6ad58)

**draw.io version:**

- draw.io version 21.7.5

**Desktop:**
 - OS: MacOS

**Additional context**

**Comment by Dominik-H** [comment]
I am observing the same issue on Windows 10 as well.

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
