### ISSUE TITLE
drawio-desktop about line and arrow anchoring

### ISSUE THREAD

**Issue by ouyang7923** [jgraph/drawio-desktop#1441]
![image](https://github.com/jgraph/drawio-desktop/assets/105358618/b6f846b3-2491-4db7-bddf-430a7bf3c957)

It is often necessary to use straight lines and arrows to point to certain positions arbitrarily, but they can only point to fixed anchor points. Can the function of pointing to any position freely be realized?

**Comment by davidjgraph** [comment]
Press and hold the shift key while positioning.

**Comment by ouyang7923** [comment]
> 



> Press and hold the shift key while positioning.

Thank you, it is a little unsatisfactory, the length and angle need to be adjusted in the blank space, and finally move to the target anchor point

**Comment by davidjgraph** [comment]
Not for me, I just hold shift and I can drop anywhere inside the shape boundary. If you see something else you need to fill in the bug template properly.

**Comment by ouyang7923** [comment]
> Not for me, I just hold shift and I can drop anywhere inside the shape boundary. If you see something else you need to fill in the bug template properly.

After getting used to it, there is no problem
