### ISSUE TITLE
--page-range option does not allow to select only the first page

### ISSUE THREAD

**Issue by FrederikWolter** [jgraph/drawio-desktop#1443]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Using the command line option `--page-range <from>..<to>` of the draw.io.exe produces an unexpected behavior:

Exporting a drawing as PDF using the command line works great. But using `--page-range` option does not behave like i would expect. 
Setting the option to `--page-range 1..1` causes a the **second** page of a multipage diagram to be exported (so i guess it is 0 indexed).
**But** setting the option to `--page-range 0..0` causes **all pages** to be exported instead of the first one.

**To Reproduce**
1. Execute `C:\Program Files\draw.io\draw.io.exe .\images --crop --export --recursive --format pdf --page-range 1..1`
2. Execute `C:\Program Files\draw.io\draw.io.exe .\images --crop --export --recursive --format pdf --page-range 0..0`

**Expected behavior**
I would expect `0..0` to export the **first** page and `1..1` to export the **second** page.
If **all pages** are wanted the option `--all-pages` should be used.

**draw.io version:**

- draw.io version **v21.6.8**

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by m-mohamedin** [comment]
Will be fixed in the next release

**Comment by davidjgraph** [comment]
In desktop release 22.1.16.
