### ISSUE TITLE
Searching for import library/icons

### ISSUE THREAD

**Issue by wenjian80** [jgraph/drawio-desktop#1444]
When import a library/icons on drawio web, the "search" is working fine.
However for offline draw io, "search" cannot pick up the imported library/icons.

**Comment by RSwarnkar** [comment]
Yes, I agree with this issue. @wenjian80 

I have imported about 800+ [Azure Icons](https://learn.microsoft.com/en-us/azure/architecture/icons/) but the search function is quite poor when I try to search imported icon.

For example, While searching for`Azure Event Grid`, the expected search function should work for any substring e.g. `Grid`, `event`, `eventGrid`, `entGri` etc. 

Can we please consider beefing up the search ?
