### ISSUE TITLE
Built-in plugin Flow stopped working

### ISSUE THREAD

**Issue by saf-dmitry** [jgraph/drawio-desktop#1446]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The built-in JavaScript plugin flow.js stopped working.

**To Reproduce**

1. Run the app.
2. Select "Extras > Plugins > Add", select "flow" from the drop-down list and hit "Add".
3. Restart the app.
4. Create a connector and select it.
5. Right click to get context menu
6. Notice the "Toggle Flow" option is not available.

**Expected behavior**
The option "Toggle Flow" is available in the context menu when a connector is selected.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.6.8

**Desktop (please complete the following information):**
 - OS: macOS 10.15

**Additional context**

**Comment by davidjgraph** [comment]
Have you enabled plugins on the app parameters?

**Comment by saf-dmitry** [comment]
> Have you enabled plugins on the app parameters?

If you mean the `--enable-plugins` CLI flag, it has no effect.

I tried various other built-in plugins and they do work, but Flow doesn't even appear in the list of added plugins.

**Comment by davidjgraph** [comment]
See https://github.com/jgraph/drawio/issues/3840

**Comment by Nainsar101** [comment]
Can anyone help me on this 
After installing latest version flow plugin is not visible in dropdown
