### ISSUE TITLE
Screen style changes after printing.

### ISSUE THREAD

**Issue by JonRobert** [jgraph/drawio-desktop#1449]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I have version:  21.6.8  (same issue on previous version), Windows 11
I have a simple flowchart, one page.  I am using the style with:
Background white, symbols and lines are black.
I'm using the Automatic theme and with my windows settings, the screen is: dark background, symbols have white background and black text. LINES ARE WHITE.

I print to my laser printer.  Canon if it makes a difference.
When I return to the screen all is the same EXCEPT the lines are black

**To Reproduce**
Create a simple flow chart.  Print it to a real printer.  I don't know if printing to file has the same issue.

**Expected behavior**
I expect the screen to return with white lines.  Even if I reapply the style (orange circle) the lines stay black.  I can get them to return to white by closing the file and reopening.  Likely another way but this is what I'm doing

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/15662501/8bb2d37f-36db-484c-a322-08eb54ed2017)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.6.8

**Desktop (please complete the following information):**
 - OS: Windows 11
**Additional context**
I want to say I love your program and many thanks for making it availiable.
John

**Comment by m-mohamedin** [comment]
Unfortunately, we couldn't reproduce the issue. Can you please share the file with us

**Comment by JonRobert** [comment]
Hi m-mohamedin,

After uninstalling and reinstalling I too cannot or have not been able to repeat this condition.  I will close this item.
Thank you for you attention to this.
John
