### ISSUE TITLE
CLI option to control appearance for export

### ISSUE THREAD

**Issue by johannst** [jgraph/drawio-desktop#1452]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
As a CLI user to export SVGs in CI setups and by manually invoking scripts, I'd like to be able to specify the appearance `{light, dark}`.

![image](https://github.com/jgraph/drawio-desktop/assets/13176832/582d02a6-e84e-4280-a087-21633606404c)

**Describe the solution you'd like**
Add CLI option to pass the appearance when exporting SVGs.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by m-mohamedin** [comment]
Will be added to the next release (--svg-theme dark)

**Comment by davidjgraph** [comment]
In desktop release 22.1.16.
