### ISSUE TITLE
Dev Tools Context Menu Issue

### ISSUE THREAD

**Issue by ForbiddenEra** [jgraph/drawio-desktop#1457]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When trying to hack preview scaling into the shape library with devtools, I noticed that devtools context menus are rendering underneath the devtools window!

![image](https://github.com/jgraph/drawio/assets/7980490/727c7a04-e28a-4b26-a4ed-b6fd529756fa)

I was baffled at first when trying to right click to edit an element and the context menu wasn't showing; initially I thought that the event was being `.preventDefault()`'d or something, then I happened to right click closer to the edge of the window and noticed the context menu rendering under it!

Edit: I just noticed this doesn't happen when DevTools is docked, only when it's popped out as a separate window.

**To Reproduce**
1. Open App
2. Create New Diagram
3. Open DevTools as separate window
4. Right anywhere in DevTools where a context menu would be expected to pop up.

**Expected behavior**
It should render above the window. I would initially think it's a `z-index` issue..perhaps that's a factor, while I've been doing JS/CSS as long as both have existed and started coding HTML before CSS was even a thing, I don't have much experience with Electron-type apps thus I'm not sure how that might be handled in this case or whether the context menu is handled in the same window context or what.

This is also possibly an issue with Electron (or whatever Chromeless DesktopWebApp thing this is based off if not that) but, even if that is the case, is likely exasperated by the use/configuration/implementation here.

**Screenshots**
One is included in the above description.

**draw.io version + platform:**
This is on v21.6.8 on Windows 10.

**Comment by m-mohamedin** [comment]
Unfortunately, this is an electron issue. Please report it there.

**Comment by ForbiddenEra** [comment]
> Unfortunately, this is an electron issue. Please report it there.

I don't know if I'm convinced as I am unable to reproduce in any other Electron apps.
