### ISSUE TITLE
version 21.7.5 stuck on loading screen (on Ubuntu 22.04.3 using snap )

### ISSUE THREAD

**Issue by angcap** [jgraph/drawio-desktop#1459]
drawio stuck on loading page,running from terminal with

`DRAWIO_ENV=dev drawio`

the devtools console shows a CSP error

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-PDJOTCOfwIg8Ri7U2PH1pIpx+haCyKsJEbFxlW6hdSI=' 'sha256-6g514VrT/cZFZltSaKxIVNFF46+MFaTSDTPB8WfYK+c='". Either the 'unsafe-inline' keyword, a hash ('sha256-dLMFD7ijAw6AVaqecS7kbPcFFzkxQ+yeZSsKpOdLxps='), or a nonce ('nonce-...') is required to enable inline execution.`

**Comment by dhaugli** [comment]
I have the same issue, I got Apparmor errors:
audit: type=1400 audit(1694688888.138:237): apparmor="DENIED" operation="symlink" class="file" profile="snap.drawio.drawio" name="/dev/char/195:0" pid=20186 comm="drawio" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000

**Comment by davidjgraph** [comment]
That release was a little premature, sorry about that... Uninstall and reinstall and you'll get 21.6.5 again.

**Comment by dhaugli** [comment]
Its a bit difficult through snap in Ubuntu. Could you guys make a new bug fix release and push it to snap?

**Comment by davidjgraph** [comment]
Unfortunately, that a long process also. We have to make a new core release. Snap really doesn't provide a mechanism to uninstall?
