### ISSUE TITLE
Ubuntu 22.04 - snap - v21.7.5 - Launch stuck at "Loading". 

### ISSUE THREAD

**Issue by radhakrisri** [jgraph/drawio-desktop#1461]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Launching drawio on Ubuntu 22.04 gets stuck in "Loading screen". 

**To Reproduce**
1. Install drawio from Ubuntu 22.04's default snap
2. Launch drawio
3. A window pops up as shown here: ![image](https://github.com/jgraph/drawio/assets/125212515/f6b76d1a-21ee-4470-984e-3905036f2ee2)
4. Closing the window doesn't terminate the application.
5. Command line execution points to this:
![image](https://github.com/jgraph/drawio/assets/125212515/80b8063e-d215-454f-badc-80a35df00292)
and
![image](https://github.com/jgraph/drawio/assets/125212515/c1b40eda-83da-48e7-8952-eb2ed68b493c)
6. Here are the errors from the developer console
![image](https://github.com/jgraph/drawio/assets/125212515/5fe83b16-4887-47fe-878f-261b57274390)
and 
![image](https://github.com/jgraph/drawio/assets/125212515/3534a8a1-d4a2-4766-8661-3c2172c8f229)

**Expected behavior**
drawio should launch properly and offer to load a file.

**Screenshots**
Provided

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.7.5

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Browser Version: Version 116.0.5845.187 (Official Build) (64-bit)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
yes

**Additional context**

**Comment by davidjgraph** [comment]
Duplicate #1459
