### ISSUE TITLE
Sharing diagram via Google Drive

### ISSUE THREAD

**Issue by DmitryDrozdUA** [jgraph/drawio-desktop#1462]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Sharing diagrams via Google drive doesn't work. It returns the 400 response and popup related

**To Reproduce**
1. Click Share button in diagram.net
2. I am redirected to Google drive
3. Click on three dots and then on the Share button
4. See loading popup
5. See error message: Sorry, sharing is unavailable at this time. Please try again later.

**Expected behavior**
Can share the file via Google Drive

**Screenshots**
https://prnt.sc/WmY7ZHcf6V5T

**draw.io version (In the Help->About menu of the draw.io editor):**
draw.io version 21.7.5

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Nothing else

**Comment by davidjgraph** [comment]
There is no Google Drive support in draw.io desktop.

**Comment by CarterSnich** [comment]
@davidjgraph why? Will it ever be implemented? Or is it impossible?

**Comment by davidjgraph** [comment]
Read the project README. "draw.io Desktop is designed to be completely isolated from the Internet"
