### ISSUE TITLE
Background color is not working properly 

### ISSUE THREAD

**Issue by JuanAraujoNexplore** [jgraph/drawio-desktop#1464]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When I choose this specific color background R37 G48 B150 (A dark blue) I am getting a very light blue as a color in the background. 
**To Reproduce**
1. Go to 'background option '
2. Click on 'color picker'
3. Enter RGB code  R37 G48 B150 
4. Color picker shows the correct color.
5. Once you apply that color to the background, the background switch to some other color

**Expected behavior**
The same color shown on the color picker should be apply to the background of my canvas

**Comment by davidjgraph** [comment]
Are you in dark mode?

**Comment by JuanAraujoNexplore** [comment]
I am !

***@***.***

**Comment by RubaEgbaria** [comment]
same here, in both modes.
but it works properly when I change the window size to anything except 100%.

https://github.com/jgraph/drawio-desktop/assets/54721790/dfdadd85-a697-4763-a846-65eab22be261

**Comment by m-mohamedin** [comment]
Is this still affecting the latest version?
Is "Improve Contrast" checked?

**Comment by RubaEgbaria** [comment]
It should be the latest version I am using the web.
To reproduce it, open the website select the other mode option, and then reload the screen, the bug should be there.

**Comment by davidjgraph** [comment]
If you want to report an issue with the online version, please use https://github.com/jgraph/drawio/issues. The original report relates to the desktop version.
