### ISSUE TITLE
support for github storage

### ISSUE THREAD

**Issue by introom** [jgraph/drawio-desktop#147]
Is it possible to support for github storage as in the online webpage version?

**Comment by davidjgraph** [comment]
No, the desktop version is locked down for security reasons. You're better hosting the online version locally and accessing from there, if you have security constraints.

**Comment by introom** [comment]
btw, is it possible for the online version of draw.io to remember the last used github repo?  so that when creating a new graph, it will default to using that repo instead of let the user choosing from a ton of repos from the top-level.
