### ISSUE TITLE
Switching theme also switches connection behaviour

### ISSUE THREAD

**Issue by dr3adl0rd** [jgraph/drawio-desktop#1472]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Switching theme from Classic to Simple also changes the way connections are drawn. I can no longer draw orthogonal connections when Simple theme is enabled.

**To Reproduce**
1. Go to Menu Extras -> Theme
2. Click on Classic
3. Add two nodes, and draw connection between them in orthogonal mode (picture attached)

![Classic](https://github.com/jgraph/drawio-desktop/assets/12574646/fb9355c2-a78a-427f-a81f-d8021565898b)

4. Go to Menu Extras -> Theme
5. Click on Simple
6. Add two nodes, and draw connection between them - no orthogonal mode possible (picture attached)

![Simple](https://github.com/jgraph/drawio-desktop/assets/12574646/02c481b7-463f-424a-adce-78f0c5dbe32c)

**Expected behavior**
Orthogonal connections should be available no matter which UI theme is selected.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.8.2

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by davidjgraph** [comment]
Did you explicitly select the edge and pick orthogonal in the format panel?

**Comment by dr3adl0rd** [comment]
> Did you explicitly select the edge and pick orthogonal in the format panel?

Nope, just default behaviour, I didn't change the format.

**Comment by davidjgraph** [comment]
Your expected behaviour is "Orthogonal connections should be available no matter which UI theme is selected.". Is it available, it's just not the default.

**Comment by dr3adl0rd** [comment]
Ok, but where can I change it so that the ortho is the default in the Simple theme for all new connections? Currently the only option I see is select all edges after drawing and change it.
