### ISSUE TITLE
PERMANENT LOSS OF DATA when Copy-Paste (or Import) vector graphics from PowerPoint DrawIO Desktop (all vector graphic data and editability lost)

### ISSUE THREAD

**Issue by richlysakowski** [jgraph/drawio-desktop#1475]
**Describe the bug**

Copy-Paste (or Import) vector graphics from PowerPoint to DrawIO (desktop) PERMANENTLY LOSES DATA (vector graphics data is stripped (and lost) and vector graphics object is converted to image object).

All vector graphics drawing data (WMF object data?) are deleted.  
Graphic is permanently loses vector data 

We are left with a non-editable image object.

This is TOTALLY unacceptable.  On the Windows Clipboard the data is a vector graphic.  

################################
**To Reproduce**
1. Create a diagram or vector graphic in PowerPoint. 
2. Copy to Clipboard.
3. Switch to Draw.io and paste vector graphics drawing into Draw.IO
4. See non-editable image appear.  All graphics data is deleted permanently.
5. No "Ungroup" functionality is available, because graphics data was deleted.  

**Expected behavior**
No third party tools are needed to convert back to editable vector graphics format. 
Copy and paste from PowerPoint to Draw.io retains all vector graphics data.  
Graphic retains full editability. 

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net 20.8.16

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional

Is there a FOSS converter plugin to prevent this data loss by reading the clipboard correctly, and then invoking a WMF to draw.io converter?

**Comment by davidjgraph** [comment]
We don't support copy and paste from Powerpoint.
