### ISSUE TITLE
Font settings no longer allows to select web or Google fonts

### ISSUE THREAD

**Issue by sergiof-snps** [jgraph/drawio-desktop#1476]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

**To Reproduce**
1. Select a shape that contains text
2. Double click or press F2 to edit the text
3. On the side bar, open the drop down to select a font face, then choose the option `Custom...`

**Expected behavior**
The produced dialog used to show three ways to configure a font: system fonts, Google fonts and web fonts. Now, only system fonts are available.

**Screenshots**
<img width="220" alt="image" src="https://github.com/jgraph/drawio-desktop/assets/146454385/878a8b9e-45fd-44a4-9758-474479c743b2">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.0

**Desktop (please complete the following information):**
 - OS: Windows 11, Fedora (using Flatpak)

**Additional context**
I don't know if this is an intentional regression or a bug, but I have failed to find references to it in the issue tracker, the website or on Internet forums.

**Comment by davidjgraph** [comment]
This was removed as part of https://github.com/jgraph/drawio-desktop/issues/1409.

Enable under Extras->Google Fonts.

**Comment by sergiof-snps** [comment]
Thanks for the explanation! Sorry if this is the wrong space to ask, but I have a follow up question:

I create and distribute templates for my company, and recently started using Google Fonts as a way to keep the look and feel consistent regardless of the system fonts installed on the user's computer. Based on my tests, it seems this is gone now: every user would now need to actively enable the Google Fonts extra. Is there a way around this? Some ideas that come to mind as an user are:

- Link the activation of Google Fonts to the document (if the document uses Google Fonts, Draw.io should retrieve them)
- Allowing to bundle a font with the diagram, so that it is available to the user without installing and without fetching online

**Comment by MilanObrenovic** [comment]
> This was removed as part of #1409.
> 
> Enable under Extras->Google Fonts.

I enabled it, restarted draw.io and still there are no google fonts, plus the Extras->Google Fonts gets reverted back to unchecked as if i did nothing.

Edit: google fonts appear only when i open a new project in draw.io, but opening my existing projects does not remember enabling google fonts, always defaulting to hidden/disabled
