### ISSUE TITLE
Copy (Ctrl+C) and Cut (Ctrl+X) Not Working in v22.0.1

### ISSUE THREAD

**Issue by volnet** [jgraph/drawio-desktop#1479]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I have downloaded the v22.0.1 version ([windows installer](https://github.com/jgraph/drawio-desktop/releases/download/v22.0.1/draw.io-22.0.1-windows-installer.exe)) of the draw.io software and encountered an issue where the Copy (Ctrl+C) and Cut (Ctrl+X) keyboard shortcuts are not functioning as expected.

**To Reproduce**

1. Open draw.io v22.0.1.
2. Create or open a diagram.
3. Attempt to use Ctrl+C to copy selected elements or Ctrl+X to cut selected elements.

**Expected behavior**

The copy and cut functionalities should work as usual, similar to previous versions.

**Actual Behavior**

The copy (Ctrl+C) and cut (Ctrl+X) functions do not seem to work. Content cannot be copied or cut to the clipboard.

**Screenshots**
[NONE]

**draw.io version (In the Help->About menu of the draw.io editor):**

v22.0.1 version ([windows installer](https://github.com/jgraph/drawio-desktop/releases/download/v22.0.1/draw.io-22.0.1-windows-installer.exe)) 

**Desktop (please complete the following information):**
 - OS: Windows
 - Windows 10 Professional 22H2 19045.3448

**Additional context**

I have tried restarting draw.io, but the issue persists.
My keyboard shortcuts work fine in other applications, so it may not be a keyboard settings issue.

**Comment by davidjgraph** [comment]
Wrong repo, follow as https://github.com/jgraph/drawio/issues/3903

**Comment by davidjgraph** [comment]
Oops, wrong way around...

**Comment by davidjgraph** [comment]
Fixed in 22.0.2. Thanks for report.
