### ISSUE TITLE
Partial concentric ellipse bug

### ISSUE THREAD

**Issue by srfiorini** [jgraph/drawio-desktop#148]
I am having some problems with the shape called Partial Concentric Ellipse (the last shape in Basic Shapes) in draw.io desktop version in macos (Mojave 10.14). The shape is not rendering correctly. It is rendering as a closed donut, with an internal shaded circle. Tried in different computers (Mojava 10.14) and had the same problem.

The style is: `verticalLabelPosition=bottom;verticalAlign=top;html=1;shape=mxgraph.basic.partConcEllipse;startAngle=0.25;endAngle=0.1;arcWidth=0.5;fillColor=#ffffff;`

**Comment by kutya** [comment]
Should be fixed in next update
