### ISSUE TITLE
Double-clicking on .drawio Files Fails to Open Properly

### ISSUE THREAD

**Issue by volnet** [jgraph/drawio-desktop#1480]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

1. I found the same issue: https://github.com/jgraph/drawio-desktop/issues/1400 , but it's taged:  #[blocked/need-repro](https://github.com/jgraph/drawio-desktop/labels/blocked%2Fneed-repro) , #[issue template not filled](https://github.com/jgraph/drawio-desktop/labels/issue%20template%20not%20filled), #[low quality](https://github.com/jgraph/drawio-desktop/labels/low%20quality).
2. It's appear in macOS earlier: https://github.com/jgraph/drawio-desktop/issues/272 , but I'm windows.
3. No others issues to found.

**Describe the bug**
I encountered a bug where double-clicking on a *.drawio file fails to open it properly. Instead, draw.io only displays the Windows frame with a blank interior. I tried creating a new "a.drawio" file to rule out version issues, but the problem persists. I also attempted changing the file name to pure English ("a.drawio"), pure numbers ("1.drawio"), and mixed Chinese and English ("2013-10-03_测试.drawio"), but the issue remains. In this state, I need to use the Task Manager to kill the process. 

The only working method is to first open the draw.io software and then open the file.

**To Reproduce**
1. Double-click on a *.drawio file.
2. Observe that draw.io fails to open the file correctly.

**Expected behavior**
I expected draw.io to open the file when I double-click it, just like other file types.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v22.0.1 ([windows installer](https://github.com/jgraph/drawio-desktop/releases/download/v22.0.1/draw.io-22.0.1-windows-installer.exe))

**Desktop (please complete the following information):**
 - OS: Windows
 - Windows 10 Professional 22H2 19045.3448

**Additional context**
This issue also existed in the previous version.

**Comment by davidjgraph** [comment]
Duplicate #1479 , maybe search a bit harder next time.

**Comment by volnet** [comment]
@davidjgraph #1479 is an issue about copy&paste, this issue is double-click to open file.

**Comment by davidjgraph** [comment]
Oops, sorry.

**Comment by volnet** [comment]
**Additional context**
1. I open the **drawio-desktop-windows** with/without file(*.drawio).
2. Then I double click the file named "*.drawio", **It is properly**.

**Comment by np-jiang** [comment]
![20231007_211649](https://github.com/jgraph/drawio-desktop/assets/132221288/5184e34b-9e23-4b2d-88a8-7ffcf9e0cc6f)

I have the same problem on the no-install-win version, both 22.0.0 and 22.0.2.
When I used 21.2.1 at first, there seemed no such a problem and I don't know whether I delete some necessary files.
