### ISSUE TITLE
unrecognized fonts on the dialog boxes

### ISSUE THREAD

**Issue by TCPuniverse** [jgraph/drawio-desktop#1483]
Hey!
All the menus and texts on the main window of the Draw.io app on my RHEL 9.2 are being displayed without any issue, but when I want to save or export the diagram, the dialog boxes shows weird and unrecognized characters as shown in the screenshot. I have not any issues on any other app on my Linux machine.  
![drawio screenshot](https://github.com/jgraph/drawio-desktop/assets/74060306/4586e8a4-fc43-4dfb-a489-a8245f8862b0)

**Comment by davidjgraph** [comment]
Duplicate https://github.com/jgraph/drawio-desktop/issues/368
