### ISSUE TITLE
Getting not a diagram file error while opening

### ISSUE THREAD

**Issue by rajesh2675** [jgraph/drawio-desktop#1485]
When opening the file getting 

Not a diagram file (error on line 1 at column 524289: Extra content at the end of the document)

Please help

I could not attach the draw io file as is , hence zipped and attaching
[S2P Integration & Data Platform - Copy - Copy.zip](https://github.com/jgraph/drawio-desktop/files/12840390/S2P.Integration.Data.Platform.-.Copy.-.Copy.zip)

**Comment by rajesh2675** [comment]
Any help to support would be appreciated

**Comment by davidjgraph** [comment]
Can you attach the file?

**Comment by rajesh2675** [comment]
From: David Benson ***@***.***>
Sent: Sunday, October 8, 2023 3:55 PM
To: jgraph/drawio-desktop ***@***.***>
Cc: Rajesh Sharma ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [jgraph/drawio-desktop] Getting not a diagram file error while opening (Issue #1485)

Can you attach the file? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <jgraph/drawio-desktop/issues/1485/1751987471@ github. com> ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
    Report Suspicious  <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2M-qiFY1YrKZUK3x8GpubZY-emGNDI5e3jYclX6Msegrpc0UWD97MKrTZGHhU4tHnhsQZBNDOoRvRCZSS8Ll5F7x_0I6Ni3kWl9x-Jg5Zs51CQQ$>   ‌
ZjQcmQRYFpfptBannerEnd

Can you attach the file?
