### ISSUE TITLE
Dissaparece of 'endArrow' information

### ISSUE THREAD

**Issue by kikemiya** [jgraph/drawio-desktop#1489]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I have encountered an issues with the arrow object. Occasionally, the formatting data of the arrow, specifically the "endArrow" data, dissapears. I'd like to know how to fix this problem. Thank you.

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by kikemiya** [comment]
<img width="553" alt="endArrow" src="https://github.com/jgraph/drawio-desktop/assets/147697053/27aa3260-e5b3-4471-a969-ac84696b9ea0">

EndArrow information dissapeared like this picture. It sometimes occure, but I don't know how to reproduce this.

**Comment by davidjgraph** [comment]
This is expected. Edges inherit from the defaultEdgeStyle which contains the endArrow value. The style output only shows the style specifical for that shape, it doesn't include inherited styles.
