### ISSUE TITLE
Avast reports drawio as infected - Win32:MdeClass

### ISSUE THREAD

**Issue by valasek** [jgraph/drawio-desktop#149]
When I download the version 11.1.4 Avast antivirus blocks the program from running.
I already reported it as a false positive to Avast but want to double-check via this issue with the authors that all is safe and correct in the binary files.

**In no installer version exe is moved to the virus chest**
![no-installer](https://user-images.githubusercontent.com/1046787/63257484-2a1f3e00-c27a-11e9-93d2-4533aef09f5f.PNG)

**In the installer version, I expect that Avast removes the exe file, so lnk is not usable**
![installer](https://user-images.githubusercontent.com/1046787/63261918-ef6ed300-c284-11e9-9046-80d36bb8a335.PNG)

**Verified on**
* MS Windows 10 Pro
* AVG:
![Avast](https://user-images.githubusercontent.com/1046787/63262035-3ceb4000-c285-11e9-9a3e-0bca725c18ac.PNG)

**Comment by davidjgraph** [comment]
Click the "report as false positive" link, which is what it is.
