### ISSUE TITLE
Linux version does not open files directly

### ISSUE THREAD

**Issue by Rik44444** [jgraph/drawio-desktop#1490]
On Kubuntu 23.04
Draw.io 21.3.7 

When I open draw.io files from a folder (Dolphin), eg by double clicking, the file does not open directly, instead draw.io starts and asks if I want to start a new diagram or load an existing one. 

Expected: file is opened after double click
Actual: draw.io starts but does not open the file and asks if I want to start a new file or open existing one

PS: it does work correctly when you already have ANOTHER draw.io file open

**Comment by rbarzic** [comment]
The problem still present with  drawio 22.0.2 on Ubuntu 22.04.3 LTS

**Comment by rbarzic** [comment]
After further debugging:
drawio test.drawio => does not open the file
drawio ./test.drawio => does not open the file
drawio /full/path/to/test.drawio => file is open correctly

so something is wrong in the handling of local files/relative path

**Comment by Vaisakhkm2625** [comment]
I am using nixos and i have the same issue.
![image](https://github.com/jgraph/drawio-desktop/assets/68694876/1df9f35a-38ea-41ba-9544-0c5993ad7b14)


edit:

btw, we can use 
```
env -u WAYLAND_DISPLAY drawio ./hello.drawio.png

```
to run it with xwayland as a work around

**Comment by mrnicelliott** [comment]
I'm on Manjaro +Plasma.  It was fine with the snap install, but I've moved to the flatpak due to problem of drop downs freezing.  That issue isn't present in the flatpak but the file association problem is.

**Comment by mrnicelliott** [comment]
By the way, when I already have a draw file open, the problem still persists on other files I double click

**Comment by asoltesz** [comment]
Doesn't work on OpenSUSE Tumbleweed flatpack either.

**Comment by joezhouchenye** [comment]
It is only a problem with flatpak version. Switch to deb version and everything works fine.

**Comment by igorpupkinable** [comment]
This is an issue using Snap package on Ubuntu 22 LTS as well.

**Comment by skjerns** [comment]
Still an issue on Kubuntu 26.04 with snap installation

switching to flatpak fixed the issue
