### ISSUE TITLE
Problem with soft

### ISSUE THREAD

**Issue by Iffpl** [jgraph/drawio-desktop#1492]
Version: 22.0.2 lang: pl
win: 8

I downloaded soft on desktop. When I change my diagram and save I got information that saved but when I open all again (soft -> diagram) don't see change. 

I think problem is with "save" because when I working on on-line version and next open diagram on desktop soft I see all.
But when I work on only desktop version don't save any change..

**Comment by davidjgraph** [comment]
WIndows 8 is not a supported OS.
