### ISSUE TITLE
Background colors are wrong for network racks and other shapes in dark mode, but only for desktop app

### ISSUE THREAD

**Issue by JohnstonJ** [jgraph/drawio-desktop#1502]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The network rack shape and other related shapes have a white background in dark mode, but only in the desktop app.  The web app seems to work fine.  The impact is particularly bad given that the font color in dark mode is _also_ white, leading to unreadable text.

**To Reproduce**
1. Open the draw.io desktop app on Windows.
2. Create a new Blank diagram.
3. Switch to dark mode.
4. Click "More shapes" and pick "Networking: Rack" to make those shapes available.
5. Add a "Numbered rack cabinet" to the diagram, from "Rack / General" section of shapes.
6. Double-click the center of the rack cabinet and type "My rack" to give the rack some text.
7. Observe the following problems: (a) the background of the rack area is white, not black, (b) the background of the text caption is white, not black.  Furthermore, the font color of the caption is unreadable.

NOTE: If the steps are repeated on the web app at https://app.diagrams.net/, the problem does not occur.

**Expected behavior**
The web app demonstrates expected behavior, as shown in the screenshot below.  Note the dark background inside the rack, as well as the dark background behind the white "My rack" caption text.

![Web app screenshot](https://github.com/jgraph/drawio-desktop/assets/13113915/6917f816-be89-478e-99ae-76acab663bb1)

**Screenshots**
The screenshot below demonstrates the problem on the desktop app:

![Desktop app screenshot](https://github.com/jgraph/drawio-desktop/assets/13113915/c6b94053-f7e3-4a35-914c-b83b747ae2f8)

**draw.io version (In the Help->About menu of the draw.io editor):**

Windows desktop app (broken): 22.0.2
Web app (working): 22.0.4

**Desktop (please complete the following information):**
 - OS: Windows 10 version 22H2, OS Build 19045.3570
NOTE: the operating system was globally configured to run in dark mode.

**Comment by m-mohamedin** [comment]
We have the "Improved Contrast" mode which fixes this issue (https://github.com/jgraph/drawio/discussions/3701)

![Screenshot 2023-12-27 at 2 49 30 PM](https://github.com/jgraph/drawio-desktop/assets/24944765/e8f22141-4347-46e6-8639-7eec64167232)
