### ISSUE TITLE
Long freezes every few seconds

### ISSUE THREAD

**Issue by mattalxndr** [jgraph/drawio-desktop#1504]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

I'm working with a 10 MB file (mostly, the size is from imported PNGs), and I'm experiencing freezing every few seconds, on mouse up. 

The problem happens whether autosave is enabled or not.

The issue seems related to #173.

**To Reproduce**
1. Open [file].
2. Resize things to trigger mouse up event.
3. Notice the long freezes.

**Expected behavior**

No freezing, with long tasks happening asynchronously.

**Screenshots**

![](https://i.imgur.com/mtlMSiU.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.2

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
Here's the [file] I'm loading

[file]: https://fastupload.io/6m1How2cmJ2sV77/file

**Comment by davidjgraph** [comment]
Try going to extras->drafts and set the draft save interval to 0.

**Comment by soundsbeard** [comment]
> Try going to extras->drafts and set the draft save interval to 0.

omg, thank you so much. i've been struggling for a while with this.
now i reached freeze time to unusable state
just recorded video for bug report
https://youtu.be/9ffwgKuptvs
disabling drafts fixed these freezes

**Comment by mattalxndr** [comment]
Thank you for the workaround, it seems to work.

Since the default setting of Draft Save Interval is not zero, this bug affects every new user with a file of a certain size. Issue #173 seems like the ticket that should have covered this fix, but it has been closed. So I will refrain from closing this ticket. Hopefully the actual fix to this ongoing problem can be tracked here.

Thanks for providing this valuable product free of charge.

**Comment by evlo** [comment]
But I do not have any drafts In extras, only auto save, which I _disabled,_ but still do have freezes

Which I very much suspect are related to some kind of backup saving 

Update: there is option in desktop app and disabling autosave AND drafts = 0 seems, so far, to make application usable again

**Comment by davidjgraph** [comment]
Try 24.1.0, we think we might have found the underlying issue to this.
