### ISSUE TITLE
Block size

### ISSUE THREAD

**Issue by Bekasas** [jgraph/drawio-desktop#1507]
Feature：Select multiple modules at the same time to set the size of all modules to the same width/height as one of them. Or adjust the height and width of all modules in batches.

**Comment by m-mohamedin** [comment]
![Screenshot 2023-12-27 at 2 40 42 PM](https://github.com/jgraph/drawio-desktop/assets/24944765/9def44a3-b5f8-401d-a0ed-89785578cc2d)
You can that using the Arrange tab (set width/height)
