### ISSUE TITLE
Unable to load plugin if opening a new project

### ISSUE THREAD

**Issue by dzylikecode** [jgraph/drawio-desktop#1508]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

Plugins work fine after the first time restarting to take effect. But if opening another project or reopening the current project, plugins don't work. The board of plugins shows all is loaded, but the developer's tool doesn't list the folder `plugins`. 

**To Reproduce**
1. Go to 'Extras'
2. Click on 'plugin' and add any plugins (like text.js)
3. Restart to take effect -> board list text.js | Adds Extras > Extract Text  | develop tools list all plugins loaded (plugins/text.js)
4. Close the project and open another project
5. Click Extras > Plugin -> list text.js
6. Click Extras -> **Extract Text** Not found
7. Open develop tools -> plugins/text.js not loaded

**Expected behavior**

The plugin should work for all the projects after it's loaded. It's contradictory that the board shows the plugin loaded but it doesn't work. And it saves much time if it takes effect for all instead of just the current project.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.2

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by davidjgraph** [comment]
And you've enabled plugins in the command parameters to run desktop?

**Comment by dzylikecode** [comment]
yes, here was the command I used.

'C:\Program Files\draw.io\draw.io.exe' --enable-plugins \"d:\FDU\FDU-Course\docs\HW\02\HW-02-04.drawio.svg\"

**Comment by m-mohamedin** [comment]
Unfortunately, we couldn't reproduce.
Is there any errors in the developer tools?

**Comment by maochunguang** [comment]
I think plugin path may be not right. when you first added the plugin ,path is 'plugin/sql.js'; but when you restart app the plugin path is './plugin/sql.js'. now plugin cannot work, dev tool can not find plugin sql.js.
<img width="312" alt="draw io_UW9xNO7K7W" src="https://github.com/jgraph/drawio-desktop/assets/11879404/a85ea64c-55eb-437a-93b9-329047c13f96">

**Comment by m-mohamedin** [comment]
> I think plugin path may be not right. when you first added the plugin ,path is 'plugin/sql.js'; but when you restart app the plugin path is './plugin/sql.js'. now plugin cannot work, dev tool can not find plugin sql.js. <img alt="draw io_UW9xNO7K7W" width="312" src="https://private-user-images.githubusercontent.com/11879404/293436732-a85ea64c-55eb-437a-93b9-329047c13f96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDQxMDcsIm5iZiI6MTcwMzkwMzgwNywicGF0aCI6Ii8xMTg3OTQwNC8yOTM0MzY3MzItYTg1ZWE2NGMtNTVlYi00MzdhLTkzYjktMzI5MDQ3YzEzZjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAyMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZTNlNzA0MTA2MjI3N2IzMDFkY2ZlODYwMGU1NTM4OTI4MjE5NTVmYThmZjM1NzZmY2ZjOWFlMjBjZWY4YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BbiuTdkFsumYomzFsnShhTGJSBhSa8Wn0Q5wqIcEakE">

Did you run the app with `--enable-plugins` parameter?

**Comment by maochunguang** [comment]
> > I think plugin path may be not right. when you first added the plugin ,path is 'plugin/sql.js'; but when you restart app the plugin path is './plugin/sql.js'. now plugin cannot work, dev tool can not find plugin sql.js. <img alt="draw io_UW9xNO7K7W" width="312" src="https://private-user-images.githubusercontent.com/11879404/293436732-a85ea64c-55eb-437a-93b9-329047c13f96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDQxMDcsIm5iZiI6MTcwMzkwMzgwNywicGF0aCI6Ii8xMTg3OTQwNC8yOTM0MzY3MzItYTg1ZWE2NGMtNTVlYi00MzdhLTkzYjktMzI5MDQ3YzEzZjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAyMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZTNlNzA0MTA2MjI3N2IzMDFkY2ZlODYwMGU1NTM4OTI4MjE5NTVmYThmZjM1NzZmY2ZjOWFlMjBjZWY4YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BbiuTdkFsumYomzFsnShhTGJSBhSa8Wn0Q5wqIcEakE">
> 
> Did you run the app with `--enable-plugins` parameter?

yes, I start app with command line with  `--enable-plugins` parameter , but plugins can not work. The plugins only work in your first time, when you create new file  plugin can not work.

**Comment by maochunguang** [comment]
I record a gif. 
![draw io_jmK5GK2HzZ](https://github.com/jgraph/drawio-desktop/assets/11879404/1214b57e-bedb-47cb-aa4d-b9f308e803ed)

**Comment by dzylikecode** [comment]
> > > I think plugin path may be not right. when you first added the plugin ,path is 'plugin/sql.js'; but when you restart app the plugin path is './plugin/sql.js'. now plugin cannot work, dev tool can not find plugin sql.js. <img alt="draw io_UW9xNO7K7W" width="312" src="https://private-user-images.githubusercontent.com/11879404/293436732-a85ea64c-55eb-437a-93b9-329047c13f96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDQxMDcsIm5iZiI6MTcwMzkwMzgwNywicGF0aCI6Ii8xMTg3OTQwNC8yOTM0MzY3MzItYTg1ZWE2NGMtNTVlYi00MzdhLTkzYjktMzI5MDQ3YzEzZjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAyMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZTNlNzA0MTA2MjI3N2IzMDFkY2ZlODYwMGU1NTM4OTI4MjE5NTVmYThmZjM1NzZmY2ZjOWFlMjBjZWY4YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BbiuTdkFsumYomzFsnShhTGJSBhSa8Wn0Q5wqIcEakE">
> > 
> > 
> > Did you run the app with `--enable-plugins` parameter?
> 
> yes, I start app with command line with `--enable-plugins` parameter , but plugins can not work. The plugins only work in your first time, when you create new file plugin can not work.

This is the problem I'm encountering. So I have to uninstall the plugin, then reload it and restart the software each time.

**Comment by m-mohamedin** [comment]
As a workaround, please try editing the shortcut and add --enable-plugins to the Target
![Screenshot 2023-12-31 at 5 10 50 PM](https://github.com/jgraph/drawio-desktop/assets/24944765/9fc87fc4-d1e9-4cd7-8c67-854e61f2ed30)

**Comment by maochunguang** [comment]
> As a workaround, please try editing the shortcut and add --enable-plugins to the Target ![Screenshot 2023-12-31 at 5 10 50 PM](https://private-user-images.githubusercontent.com/24944765/293524883-9fc87fc4-d1e9-4cd7-8c67-854e61f2ed30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwODkzMjEsIm5iZiI6MTcwNDA4OTAyMSwicGF0aCI6Ii8yNDk0NDc2NS8yOTM1MjQ4ODMtOWZjODdmYzQtZDFlOS00Y2Q3LThjNjctODU0ZTYxZjJlZDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA2MDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNjliOGU0YjMxYTEyODg4YzZhOTIyZTNlYmE2OTYzNDIyZGFiM2U0ZTU2NjI5YzhmMWRjYmI4MzQ2Y2E5Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M3gOjbl72bo_m361cSDk2vuyYy-BXH3ZfTrh-_JvQlY)

It is the same things as before.

**Comment by m-mohamedin** [comment]
> > As a workaround, please try editing the shortcut and add --enable-plugins to the Target ![Screenshot 2023-12-31 at 5 10 50 PM](https://private-user-images.githubusercontent.com/24944765/293524883-9fc87fc4-d1e9-4cd7-8c67-854e61f2ed30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwODkzMjEsIm5iZiI6MTcwNDA4OTAyMSwicGF0aCI6Ii8yNDk0NDc2NS8yOTM1MjQ4ODMtOWZjODdmYzQtZDFlOS00Y2Q3LThjNjctODU0ZTYxZjJlZDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA2MDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNjliOGU0YjMxYTEyODg4YzZhOTIyZTNlYmE2OTYzNDIyZGFiM2U0ZTU2NjI5YzhmMWRjYmI4MzQ2Y2E5Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M3gOjbl72bo_m361cSDk2vuyYy-BXH3ZfTrh-_JvQlY)
> 
> It is the same things as before.

What's your version, I cannot reproduce?

**Comment by maochunguang** [comment]
I resolved this by delete appdata cache. I think drawio can not load plugin because of app cache in windows.

**Comment by davidjgraph** [comment]
@dzylikecode as the OP, what is the status of your issue?

**Comment by dzylikecode** [comment]
I have not resolved it yet, and I am still using the approach I mentioned earlier.

**Comment by filantus** [comment]
Same thing.

Draw.io: v24.2.5
OS: Win11

Steps to reproduce:

  1) Add any plugin (e.g. "anon", as it's easy to see difference. it's adds menu item to "Extras").
2) Get warning that changes will be applied after restart.
3) Close the app. **!Important!** Do not run Draw.io by shortcut on desktop or start menu! Instead of that open some .drawio file.
4) Plugin is works. But not so long.
5) Close the app. Open some .drawio file again.
6) Plugin is not works!

**Comment by davidjgraph** [comment]
12.4.0

**Comment by luck71** [comment]
> 12.4.0

Excuse me, what does "12.4.0" refer to? I have tried the release version 24.5.3, and I am still encountering the same issue. I continue to use the method described by dzylikecode to reload plugins. Additionally, could you please tell me how to clear the application's cache? This might help to alleviate the problem by using a script to delete the cache, but reloading plugins only requires manual operations.

**Comment by luck71** [comment]
Excuse me, Are you referring to the version 12.4.0 from five years ago? m-mohamedin mentioned in May of this year that 12.4.0 was the new version at issue #1619. Is there another release page? I have tried the release version 24.5.3, and I am still encountering the same issue. I continue to use the method described by dzylikecode to reload plugins.

**Comment by luck71** [comment]
> 12.4.0

Excuse me, Are you referring to the version 12.4.0 from five years ago? m-mohamedin mentioned in May of this year that 12.4.0 was the new version at issue https://github.com/jgraph/drawio-desktop/issues/1619. Is there another release page? I have tried the release version 24.5.3, and I am still encountering the same issue. I continue to use the method described by dzylikecode to reload plugins.
