### ISSUE TITLE
Dissaparece of 'endArrow' information (the bug is reproduced)

### ISSUE THREAD

**Issue by kikemiya** [jgraph/drawio-desktop#1509]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The 'EndArrow' information is not in the 'format', if I put the cursor over the object and extend the arrow to the other object. The 'EndArrow' information is in the 'format', if I select the arrow from the 'General' and connect it to two objects.

**To Reproduce**
1. Put the cursor over the object.
2. Extend the arrow to the other object.
3. See "format" of the arrow.

**Expected behavior**
The 'EndArrow' information is in the 'format', when I put the cursor over the object and extend the arrow to the other object. 

**Screenshots**
as below

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v22.0.2

**Desktop (please complete the following information):**
 - OS: Windows, MacOS

**Additional context**
This issue is related to https://github.com/jgraph/drawio-desktop/issues/1489. Since I have been able to reproduce the bug, I am re-posting it here.

![image](https://github.com/jgraph/drawio-desktop/assets/147697053/15edb473-a6de-4f2c-a366-c54735719867)

**Comment by davidjgraph** [comment]
This is expected. Edges inherit from the defaultEdgeStyle which contains the endArrow value. The style output only shows the style specifical for that shape, it doesn't include inherited styles.

**Comment by kikemiya** [comment]
Thank you for your reply. I understand.
