### ISSUE TITLE
Toggle between fullscreen and normal mode on Mac OS

### ISSUE THREAD

**Issue by ssravjee** [jgraph/drawio-desktop#1510]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
1. Download/Install/Launch Draw.io desktop for Macbook Pro (Apple M2 chip) OS Ventura 13.6
2. In order work in **fullscreen** mode you have to use the trackpad or mouse to click on the green button far right.
3. To exit **fullscreen** mode there is no simple way using the keyboard or trackpad or mouse.

**Describe the solution you'd like**
1. Use **Globe fn + f** key to go into Fullscreen mode.
2. Use **Globe fn + f** key to exit Fullscreen mode.

**Describe alternatives you've considered**
You have to quit the app and re-launch and work in normal (not full screen mode, which is a shame really, IMHO)
**Additional context**
On Windows there is no such problem.

**Comment by sivaswami** [comment]
I initially thought full screen is provided by mac OS by default. But the problem is fn + f key is taken by find dialog in Draw.io.
its must to have feature. adding my vote.
