### ISSUE TITLE
Timeline and axis graphics presets

### ISSUE THREAD

**Issue by KumoKyaku** [jgraph/drawio-desktop#1512]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

![image](https://github.com/jgraph/drawio-desktop/assets/15962980/c4726629-7d50-490c-9867-f790f851f41b)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
These features are nothing to do with a diagramming app.
