### ISSUE TITLE
How to update draw.io desktop? 

### ISSUE THREAD

**Issue by jhon65496** [jgraph/drawio-desktop#1517]
How to update draw.io desktop? 
Installed 21.6.1
I did:
  - draw.io desktop ->  Help ->  Check for Update;
  - draw.io what downloaded;
  - clicked install.
  - Opened it draw.io . Installed 21.6.1.

**Comment by davidjgraph** [comment]
If it doesn't update install the latest from https://github.com/jgraph/drawio-desktop/releases

**Comment by ZazziDBeast** [comment]
From an sys admin perspective, it would be great if you could add a Microsoft scheduled task which binds to the local system user (privileged) and automatically makes the updates.

**Comment by davidjgraph** [comment]
Closing as the original question is answered.
