### ISSUE TITLE
Cannot associate .drawio files with DrawIO desktop

### ISSUE THREAD

**Issue by agulabon11** [jgraph/drawio-desktop#1518]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When I open a ".drawio" file it will open in Notead, instead of DrawIO Desktop.
When I try to "open with" the right app, windows will NOT offer me the option to "always open with".

**To Reproduce**
1. Go to file explorer
2. Right click on a .drawio file
3. Scroll down to "open with"
4. It will let me open "once", but not "always".

**Expected behavior**
I should be able to always open with what I wanted.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.2
Installed from Microsoft Store

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

I was finally able to fix it bye removing these registry keys:

PC\HKEY_CURRENT_USER\Software\Classes\.drawio
PC\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.drawio

**Comment by deanrih** [comment]
Can also confirm on Linux using AppImage

**Comment by m-mohamedin** [comment]
Unfortunately we couldn't reproduce
As for Linux AppImage, it is a known issue with electron-builder (the packaging system we use)
