### ISSUE TITLE
GitHub no longer supports your web browser

### ISSUE THREAD

**Issue by ilyaem** [jgraph/drawio-desktop#152]
Hi guys, is that for me only, recently desktop version stopped working, displaying this page (attached below).

The only something I found related is https://help.github.com/en/articles/limits-for-viewing-content-and-diffs-in-a-repository though I hadn't check the page that's loaded into drawio desktop container. Anybody encountered this?

![image](https://user-images.githubusercontent.com/10225184/63292104-ed137580-c292-11e9-9e4b-8546e5a9ca88.png)

**Comment by davidjgraph** [comment]
It should be directing you to https://github.com/jgraph/drawio-desktop/releases to download a new release. That's the action you need to take, we'll see why it's showing the wrong page.
