### ISSUE TITLE
Can' open Visio 2010 created .VSD file.

### ISSUE THREAD

**Issue by q9HugW** [jgraph/drawio-desktop#1520]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.
**Agreed**

**Describe the bug**
I am trying to open a .VSD(not .vsdx) network diagram file created by Visio 2010. it shows "Error, Invalid File Data".

**To Reproduce**
1. Go to 'File -> Open -> Choose the file -> click open button'
2. 
3. Scroll down to 'All Files', and click on 'open button'

**Expected behavior**
Normally open the file.

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/142524387/537217eb-cdf5-4d2d-b174-b3fe6abe771d)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.3

**Desktop (please complete the following information):**
 - OS: Windows 11 and Linux(Debian 12)

**Additional context**

**Comment by q9HugW** [comment]
@davidjgraph Sorry why this issue was labled as "blocked"?

**Comment by davidjgraph** [comment]
Because it doesn't contain full, precise details of the environment and how to reproduce the error.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio-desktop/issues/521
https://github.com/jgraph/drawio-desktop/issues/281
https://github.com/jgraph/drawio-desktop/issues/118
