### ISSUE TITLE
Excel-like "Freeze panes"

### ISSUE THREAD

**Issue by lfnasser** [jgraph/drawio-desktop#1521]
* [y ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ y] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When designing flowcharts with horizontal lanes, as you move to the right, the "heads" of the lanes indicating a person, a department, or an organization disappear from the screen. I suggest the possibility that the user "freezes" part of the page so that the heads of the lanes remain visible even when moving a flowchart to the right. Similar feature could be extended to "freeze" the upper part of a page when one is drawing vertical lanes.

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
Thanks for the suggestion, however the effort to implement doesn't justify the gain in this case.

**Comment by geoffreyrhicks-art** [comment]
I would be willing to fund a freeze function - it would make product significantly better

**Comment by davidjgraph** [comment]
We've discussed this within the senior team, we all have the view this is outside the scope of the product.
