### ISSUE TITLE
Serious Rendering issue on Flathub version (Fedora 38/39)

### ISSUE THREAD

**Issue by siddheshgunjal** [jgraph/drawio-desktop#1522]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
After the recent system update there are serious rendering issues. The app is completely unusable. I love using this app and shifting again to web version is hassle.

**To Reproduce**
1. Go to  Draw.io in Fedora Software app or in Flathub
2. Install the Flathub version
3. Launch the application
4. You will see app is not rendering anything properly

**Expected behavior**
Render everything properly as its seen on webapp on browser

**Screenshots**
![Screenshot from 2023-11-09 11-06-46](https://github.com/jgraph/drawio-desktop/assets/37741186/7ec03da0-8c0c-4fe7-9f45-dad260d0cac5)
![Screenshot from 2023-11-09 11-07-38](https://github.com/jgraph/drawio-desktop/assets/37741186/38b32e74-2fbd-432c-8526-053b0a42679f)
![Screenshot from 2023-11-09 11-07-56](https://github.com/jgraph/drawio-desktop/assets/37741186/8ef842b0-7ecd-4e31-9aa9-f65b9576d534)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 22.0.3

**Desktop (please complete the following information):**

#### Hardware Information:
- **Hardware Model:**                              Lenovo Lenovo ideapad 330S-14IKB U1
- **Memory:**                                      8.0 GiB
- **Processor:**                                   Intel® Core™ i5-8250U × 8
- **Graphics:**                                    Intel® UHD Graphics 620 (KBL GT2)

#### Software Information:
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.1
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.5.10-300.fc39.x86_64

**Additional context**

**Comment by davidjgraph** [comment]
We are not the authors of the flatpak distro, the repo is https://github.com/flathub/com.jgraph.drawio.desktop
