### ISSUE TITLE
InternalError: too much recursion on simple math expression in firefox

### ISSUE THREAD

**Issue by rlezuo1** [jgraph/drawio-desktop#1525]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Pop-up
![image](https://github.com/jgraph/drawio-desktop/assets/86478348/b72d0c2f-a93d-4630-805b-35f73116bafb)
is shown with this math-expression `text{Fixkosten}/(sum_(text{MA})text{potentiell verrechenbaren Stunden})` in firefox 118.0.2 (64-bit) (Ubuntu 22.04.3)

**To Reproduce**
1. Load the attached drawio file (from device), error will pop up
[minimal.drawio.txt](https://github.com/jgraph/drawio-desktop/files/13346404/minimal.drawio.txt)

**Expected behavior**
Math formula is rendered correctly, the very same file renders correctly in chromium browser.

**Screenshots**
attached

**draw.io version (In the Help->About menu of the draw.io editor):**
16.5.6 (online)

**Desktop (please complete the following information):**
 - OS: Linux...

**Additional context**

**Comment by davidjgraph** [comment]
That's a rather old version, please update and test again.

**Comment by rlezuo1** [comment]
I guess you refer to the draw.io version,  was using the online version, on a different PC I now have version v22.1.0 which does render the formulae as expected. I'll close this one, I however wonder how I've ended with the old version ...
