### ISSUE TITLE
The app doesn't launch under Windows 8.1 x64

### ISSUE THREAD

**Issue by FonariK469** [jgraph/drawio-desktop#1527]
Description: After a fresh install (I've tried both Windows Installer and Windows No Installer EXEs and *.msi) the application doesn't launch - an error message pops up.
All information collected in the attachment - logs of Windows Events, crash description, image of an error message and info about installed MS Visual C++ components (I decided it may be useful).
Error message: "The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library C:\Users\Yui\AppData\Local\Programs\draw.io\draw.io.exe.".
[crash of drawIO.zip](https://github.com/jgraph/drawio/files/13326224/crash.of.drawIO.zip)

**Comment by davidjgraph** [comment]
Duplicate #1358
