### ISSUE TITLE
How do I set a default font size

### ISSUE THREAD

**Issue by supengxu** [jgraph/drawio-desktop#1528]
https://github.com/jgraph/drawio-desktop/assets/52996503/0f1eb65a-dbce-4d2d-9fde-3fa19556f7d0

**Comment by supengxu** [comment]
Uploading 未命名绘图.drawio - draw.io 2023-11-15 16-36-37.mp4…

**Comment by supengxu** [comment]
Whenever I click on the arrow to draw the flowchart the font always changes to size 20

**Comment by tmal-1** [comment]
When you add a new shape draw.io copies the default style for that shape.

Immediately after changing the font size, before a creating a new shape, select the Style tab.
In English the three tabs top right read Style, Text, Arrange. Yours appear to be labelled in
Chinese so I imagine it is the left of the three.

There should be a button within the Style tab that in English reads 'Set as Default Style'. Click that.

Now if you create a new copy of the same shape it should use the font size you chose.
