### ISSUE TITLE
11.1.4: file dialogues open in the background

### ISSUE THREAD

**Issue by Instagit** [jgraph/drawio-desktop#153]
Version: 11.1.4
OS: Ubuntu 16.04

Since upgrading to 11.1.4 (deb installer), the file open dialogues open in the background and block the foreground UI.

**Comment by davidjgraph** [comment]
Revert to a previous verison, for now, probably something relating to Electron 6

**Comment by shoffmeister** [comment]
Reproducible on Fedora 30, KDE 5.15, with draw.io Desktop 12.1.0 rpm

**Comment by sebvdk** [comment]
Draw.io 12.9.3 & 12.9.9
KDE Plasma 5.18.4
Archlinux

I'm having the same issue with drawio-desktop-bin deb package.

**Comment by Nicolas-Mariotti** [comment]
Reproducible in Fedora 31

Draw.io: 13.0.1
KDE Plasma : 5.17.5
KDE Frameworks : 5.68.0
Qt : 5.13.2
Kernel Version: 5.5.17-200.fc31.x86_64
