### ISSUE TITLE
Opening the Flatpak version of draw.io the window appears but the contents do not

### ISSUE THREAD

**Issue by ghost** [jgraph/drawio-desktop#1530]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When opening the Flatpak version of draw.io the window appears but the contents do not, making it unusable.

**To Reproduce**
Open the application either using the GUI or from the command line (`flatpak run com.jgraph.drawio.desktop`).

**Expected behavior**
I expect that the same welcome screen (as shown on the web application) displays.

**Screenshots**
Screenshot of the experienced error below.

![20231115-082211](https://github.com/jgraph/drawio-desktop/assets/73917048/36c888f1-8c98-4cf0-8898-f9541ed4849c)

**draw.io version (In the Help->About menu of the draw.io editor):**
- Flatpak draw.io v22.0.3

**Desktop (please complete the following information):**
 - OS: Linux (Fedora Kinoite)
 - DE: KDE Plasma

**Additional context**
This is a fragment of the error that I see from the command line. Note, this is only a subset of the errors however, looks to be multiple variations of the same error in the `void main() {...}` block.

```bash
[user@host]$ flatpak run com.jgraph.drawio.desktop
[2:1115/082317.784531:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1115/082318.152610:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1115/082318.152633:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[52:1115/082318.317830:ERROR:shared_context_state.cc(81)] Skia shader compilation error
------------------------
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;in float2 position;in half4 color;flat out half4 vcolor_S0;void main() {// Primitive Processor QuadPerEdgeAAGeometryProcessor
vcolor_S0 = color;sk_Position = position.xy01;}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
flat in half4 vcolor_S0;void main() {// Stage 0, QuadPerEdgeAAGeometryProcessor
half4 outputColor_S0;outputColor_S0 = vcolor_S0;const half4 outputCoverage_S0 = half4(1);{ // Xfer Processor: Porter Duff
sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
// Vertex GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
uniform highp vec4 sk_RTAdjust;
in highp vec2 position;
in mediump vec4 color;
flat out mediump vec4 vcolor_S0;
void main() {
    vcolor_S0 = color;
    gl_Position = vec4(position, 0.0, 1.0);
    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
}

// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
flat in mediump vec4 vcolor_S0;
void main() {
    mediump vec4 outputColor_S0;
    outputColor_S0 = vcolor_S0;
    {
        sk_FragColor = outputColor_S0;
    }
}


Errors:
link failed but did not provide an info log
[52:1115/082318.319209:ERROR:shared_context_state.cc(81)] Skia shader compilation error
------------------------
<... and so on ...>
```

**Comment by cxbignekoc** [comment]
use DEB installer, i got the same issue, DEB works flawless...

**Comment by ghost** [comment]
> use DEB installer, i got the same issue, DEB works flawless...

I run Fedora Linux which uses RPM. I did try using the AppImage binary (same version) but the results were the same.

Instead, I tried uninstalling draw.io Flatpak, removing user data (nothing there of importance), and then reinstalling it. Voila, it now works again. I am guessing there might have been an erroneous setting on my side that was causing it to fail, which was inconsistent with a newer install. Note, I have not updated settings between updates so ...? 

In this case, I am closing since the issue is resolved for me.
