### ISSUE TITLE
Microsoft CodeIntegrity - Error

### ISSUE THREAD

**Issue by ZazziDBeast** [jgraph/drawio-desktop#1533]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I have Microsoft CodeIntegrity enabled in my Intune managed environment.  All other apps work correctly, chrome, keepass, etc,  except for DrawIO.  When I try to lunch it, I get an error.

CodeIntegrity: https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-app-control-policy

"Code Integrity determined that a process (\Device\HarddiskVolume3\Users\USERNAME\AppData\Local\Programs\draw.io\draw.io.exe) attempted to load \Device\HarddiskVolume3\Users\USERNAME\AppData\Local\Programs\draw.io\ffmpeg.dll that did not meet the Enterprise signing level requirements or violated code integrity policy (Policy ID:{63d1178a-816a-4ab6-8ecd-127f2df0ce47}).

**To Reproduce**
Within Microsoft Intune create a new App Control for Business policy and apply it to a computer.
Still within Intune and for CodeIntegrity, create an exception to whitelist, therefore allowing, the digital certificate used to sign the drawio exe.

Still the DrawIO app would not run because CodeIntegrity sees that the DLL are not digitally signed?  Would it be possible to digitally sign the DLLs too?

**Expected behavior**
Lunch the app.

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/102458650/24a85d4e-d9d1-4f09-bbba-8cd228c1de6b)

- draw.io version 22.1.2.0

**Desktop (please complete the following information):**
 - OS: Windows 23H2

**Comment by m-mohamedin** [comment]
Unfortunately, our app is packaged by electron-builder and we don't have control over how it works. If possible, please report the issue there.
