### ISSUE TITLE
22.1.2 windows-installer stuck in update request cycle

### ISSUE THREAD

**Issue by adeturner** [jgraph/drawio-desktop#1534]
**Describe the bug**

22.1.2 stuck in infinite popup request to update loop

**To Reproduce**

Win10 - originally installed using windows-installer
First popup request to update to 22.1.2 (latest) - accepted and installed
Now have continual request to update. 
Neither updating nor uninstalling/reinstalling 22.1.2 helps

**Expected behavior**

Update works the first time.

**Comment by m-mohamedin** [comment]
Is this x32 or x64? Please send us the exact name of the installation file
