### ISSUE TITLE
update windows display blank

### ISSUE THREAD

**Issue by zyxasta** [jgraph/drawio-desktop#1536]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
update windows display blank

**Expected behavior**
can display update ststua

**Screenshots**

<img width="1070" alt="截屏2023-11-18 14 23 11" src="https://github.com/jgraph/drawio-desktop/assets/116530112/a604637b-2080-4cf7-abd1-c455e5010f71">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.2

**Desktop (please complete the following information):**
 - OS: macos 14.1.1

**Comment by cxbignekoc** [comment]
same on Linux Mint 21.2 MATE installed via *.deb

it also running in a loop.

1. update available ->OK
2. blank white Popup
3. A new versio has been downloaded ->install
4. drawio closed and open
5. --> 1. Update available

**Comment by davidjgraph** [comment]
And if youdownload and update to 22.1.2 manually?

**Comment by zyxasta** [comment]
the proble also happen  when i update from 22.1.2. to 22.1.11

**Comment by davidjgraph** [comment]
Workaround is to download the latest build and manually install.

**Comment by m-mohamedin** [comment]
Will be fixed in the next release

**Comment by davidjgraph** [comment]
In 22.1.15.

Note that versions prior to 22.1.15 may still experience this. Please don't report the error if you're using an earlier version. 

If you experience it on 22.1.15 or later, please open a new ticket.
