### ISSUE TITLE
Customs Links dont work

### ISSUE THREAD

**Issue by dralthan** [jgraph/drawio-desktop#1539]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
If a diagram has custom links, interacting with layers or tags, clicking the element produces an exception: Cannot read properties of undefined (reading 'concat')

**To Reproduce**
1. Open Draw.IO (v 22 onwards) works in 21.2.1
2. Click on an object with a custom link that interacts with the diagram (hiding layers, selecting tags)
3. Error is launched

**Expected behavior**
The action should be executed

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/2159267/9bd1d92d-c660-48cc-b88e-cc72680b4d3a)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.2

**Desktop (please complete the following information):**
 - MacOS

**Additional context**
This problem also occurs on the web viewer (app.diagrams.net)

**Comment by m-mohamedin** [comment]
Cannot repeat in the latest version, can you please share the diagram
