### ISSUE TITLE
 Theme settings are not saved, app always starts up in Light mode

### ISSUE THREAD

**Issue by TheEmbracedOne** [jgraph/drawio-desktop#1540]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I have the desktop app installed and every time I start up the application, it starts up in Light theme, making it so I always have to select the Dark mode every time.

**To Reproduce**
1. Go to Extras > Theme > Dark
2. Restart the app

**Expected behavior**
 Selected theme should be applied after drawio io desktop app is restarted.

**Screenshots**
![draw io_yGXbOCOaVr](https://github.com/jgraph/drawio-desktop/assets/16197906/e3809086-439e-4721-b866-1679204c303c)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 22.1.2

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by m-mohamedin** [comment]
Will be fixed in the next release

**Comment by davidjgraph** [comment]
In 22.1.15

**Comment by TheEmbracedOne** [comment]
Can confirm, this is now fixed in the last update.
