### ISSUE TITLE
right clicking selected text to copy/paste/cut

### ISSUE THREAD

**Issue by BenSoruklu** [jgraph/drawio-desktop#1541]
I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
 I have searched the issue tracker for a feature request that matches the one I want to file, without success.

It would be incredibly convenient and beneficial if text within chart containers, such as notes or square shapes, could be copied to the Windows clipboard by right-clicking the mouse. A context menu would appear with options for copying, cutting, and pasting. Currently, after selecting the text, I must use the keyboard to perform these functions (CTRL + X, CTRL + C, CTRL + V), which is slow and cumbersome.
<img width="145" alt="Screenshot 2023-11-28 012717" src="https://github.com/jgraph/drawio-desktop/assets/152234035/abc3198a-6244-4bc1-afd2-65979adaf4bf">

Note: I'm using the desktop application - draw.io-22.1.2
Thank you

**Comment by m-mohamedin** [comment]
Will be added to the next release

**Comment by davidjgraph** [comment]
In 22.1.15
