### ISSUE TITLE
Loading of vsdx-file stuck 

### ISSUE THREAD

**Issue by jhalldn** [jgraph/drawio-desktop#1542]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When clicking on a vsdx-file, to start editing the file - the loading never ends.  Hence some kind of loop, loading the file. It's probably the in the same ballpark as stated in issue #1431.

**To Reproduce**
1. Click on *.vsdx
2. Loading-screen and the never ending wheel appear.

**Expected behavior**
The vsdx-file should load and possible to edit.

**Screenshots**
<img width="853" alt="Skärmavbild 2023-11-28 kl  16 25 15" src="https://github.com/jgraph/drawio-desktop/assets/8028630/054e4b9c-22ae-48b4-9269-87db49ad4d87">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.2

**Desktop (please complete the following information):**
 - OS: MacOS 14.1.1

**Additional context**

**Comment by davidjgraph** [comment]
Please attach the file used.

**Comment by jhalldn** [comment]
Does not matter which files i use. I can not attach files, due to company restrictions.

**Comment by davidjgraph** [comment]
I cannot repeat this with the vsdx file I used.
