### ISSUE TITLE
unable to open 'graphml' files 

### ISSUE THREAD

**Issue by afpd** [jgraph/drawio-desktop#1544]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
drawio-desktop is unable to open 'graphml' files

**To Reproduce**
1. Click 'Open Existing Diagram'
2. Click 'Show Options' then select 'All files'
3. Select any 'graphml' files
4. See error 'Error loading file Not a diagram file'

**Expected behavior**
Expected behaviour is to display a graph.
Web version is showing 'graphml' files correctly

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v22.1.2 

**Desktop (please complete the following information):**
 - OS:  MacOS

**Additional context**
I have variety of 'graphml' files and all of them produce the same error in the desktop application, while at the same time are rendered correctly is opened through https://app.diagrams.net/. I need to mention that site says v22.1.5, while desktop latest desktop version is v22.1.2 (as for 01-Dec-2023) .

**Comment by davidjgraph** [comment]
GraphML import is written in Java and runs server-side. The desktop version is isolated, no data is transmitted.
