### ISSUE TITLE
Not a diagram file 

### ISSUE THREAD

**Issue by lowrenz998** [jgraph/drawio-desktop#1548]
I opened the file yesterday but today i cant.
This is the error: 
![image](https://github.com/jgraph/drawio-desktop/assets/153390356/57a4d522-5979-44e8-9598-db7e4f64ecf4)

draw v 22.1.2

Please help
[antibiotici.zip](https://github.com/jgraph/drawio-desktop/files/13625404/antibiotici.zip)

**Comment by davidjgraph** [comment]
This has been cut off. It was saved with 22.0.2. Are you saving to a sync'ed cloud folder, like Google Drive or OneDrive?
