### ISSUE TITLE
Can't install youtube-music rpm opensusetw failed unpacking archive

### ISSUE THREAD

**Issue by Soymilkrice** [jgraph/drawio-desktop#1549]

**Comment by davidjgraph** [comment]
Probably in the top 5 most bizarre issues ever opened here...

**Comment by Soymilkrice** [comment]
Why ?
I'm a noob so I dont really understand why it isnt working.

**Comment by Soymilkrice** [comment]
@davidjgraph I'm so dumb, I've post this issue in the wrong project page, I am so sorry and I will rework this issue in the right github.
