### ISSUE TITLE
Not a diagram file

### ISSUE THREAD

**Issue by PovedaAqui** [jgraph/drawio-desktop#1553]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

I can't open any document created with a previous version of the Application, all of them give me an loading file, Not a diagram file (error on line '12745 at column 19): AttValue: ' expected)

**To Reproduce**
1. Go to 'Open a file'

**Expected behavior**

It should be opened as usual.

**Screenshots**

![image](https://github.com/jgraph/drawio-desktop/assets/9494679/b2774f7a-896e-4582-a693-008b9b2228d7)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.2

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

Last time the document was edited: 29 Nov 2023.
I can't upload the file, it contains sensitive information.

**Comment by PovedaAqui** [comment]
Importing rather than opening did the trick.

**Comment by m-mohamedin** [comment]
Without the files, it's difficult to analyze. But since the problem has a workaround, we'll close
