### ISSUE TITLE
Custom libraries disappear after changing light/dark mode 

### ISSUE THREAD

**Issue by kartun83** [jgraph/drawio-desktop#1556]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Custom libraries disappear from left menu after changing dark/light modes

**To Reproduce**

1. Open Draw.io
2. Load custom shapes library
3. Shapes are displayed in toolbox
4. Change mode via icon in top right corner
5. Custom libraries aren't in toolbox anymore

**Expected behavior**
Custom shapes are in toolbox

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.8.16

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.2

**Additional context**
![drawio_custom_shapes](https://github.com/jgraph/drawio-desktop/assets/5894573/7163ca73-2078-4464-8c07-8e3849fc122f)

**Comment by m-mohamedin** [comment]
Unfortunately, we couldn't reproduce on the latest version. Can you please upgrade and try again
