### ISSUE TITLE
Lost my drawio file and one-week job down drained..

### ISSUE THREAD

**Issue by jquanC** [jgraph/drawio-desktop#1558]
**Describe the bug**
I have a big drawio file which contains my one-week job! Today I opened it as usual from desktop.app and failed. The file had been lost and only a  ".bkp" existed.
I tried to modify the filename by removing the suffix '.bkp' and then open it, but it turned to a very very early stage and I found that bkp file size was 14kb, which is abnormal( compared to other bkp file) since my original drawio file is big.
Can I recover it? It is really important for me!

**To Reproduce**
1. Just as described, I lost the file and can not open it;
2. And I am not sure whether I saved the file or not before my PC shut down last night.

**Screenshots**
I worked with this file last day.
![image](https://github.com/jgraph/drawio-desktop/assets/80034496/585f370f-c0a5-4805-9f81-4e19283094ff)

Only the corresponding '*.bkp' file exists now.
![image](https://github.com/jgraph/drawio-desktop/assets/80034496/093c9c20-70fd-48dd-8b62-706d259f5ec1)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.3

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by m-mohamedin** [comment]
Unfortunately, we take a copy of the file before saving (.bkp files) and we overwrite the original file on saving (we don't delete). Is auto-save enabled (.tmp file)? If not, I'm afraid the file is lost if not saved before shutting down the PC.
Sorry about that

**Comment by jquanC** [comment]
Yeah, I enabled the auto-save all the time,  but it seems does not work well before the last time I upgraded the software.  What I mean is that sometimes the client will remind you to save the file, instead of saving automatically, especially when I am editing a large file. By the way, does the auto-save setting take effect on all files?
Currently, I have enabled a cloud sync of my whole folder to avoid such an accident again.

**Comment by jquanC** [comment]
Is the  '.tmp'  file saved in the working folder?

**Comment by jquanC** [comment]
Is the  '.tmp'  file saved in the working folder?

**Comment by m-mohamedin** [comment]
Yes, next to the file. Autosave affects all files
I made a mistake, it is the Drafts settings (Extra->Drafts...) and it saves to the .tmp file based on the interval set in that dialog. It is independent from the autosave which saves to the actual file

**Comment by jquanC** [comment]
Well, I haven't enabled the Drafts setting and I enabled it now.

**Comment by m-mohamedin** [comment]
I'll close the issue. Sorry for not being able to help

**Comment by jquanC** [comment]
It is ok. Thanks for your notice and advice. I appreciate it~
