### ISSUE TITLE
confusion code show up when I'm going to save my file.

### ISSUE THREAD

**Issue by HuXinjing** [jgraph/drawio-desktop#1559]
[](url)### Preflight Checklist

![Uploading Screenshot from 2023-12-25 18-40-09.png…]()

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
when I save my file, all the character in saving messagebox become something like "口".

**To Reproduce**
just save file created by draw.io in ubuntu 23.04

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.11

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by HuXinjing** [comment]
![Screenshot from 2023-12-25 18-40-09](https://github.com/jgraph/drawio-desktop/assets/49928618/80713f9b-b25e-4496-bda9-8601cf7cbb1b)

**Comment by davidjgraph** [comment]
Duplicate https://github.com/jgraph/drawio-desktop/issues/368
