### ISSUE TITLE
windows plugins load failed, when I restart the app.

### ISSUE THREAD

**Issue by maochunguang** [jgraph/drawio-desktop#1566]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

**To Reproduce**
1. add plugin
2. restart app
3. exist app and reopen app
4. plugin not work

**Expected behavior**
plugin added can work until I remove it.

**Screenshots**
<img width="312" alt="draw io_UW9xNO7K7W" src="https://github.com/jgraph/drawio-desktop/assets/11879404/18f29da6-ee7b-4d48-b1c3-e98483f93bf7">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.16

**Desktop (please complete the following information):**
 - OS: Windows, 
 - 
**Additional context**

**Comment by maochunguang** [comment]
please delete your appdata cache ,then add --enable plugin param start app;

**Comment by JingyangXiang** [comment]
> please delete your appdata cache ,then add --enable plugin param start app;

Could please introduce how to delete appdata cache for drawio? Thank you very much!

**Comment by maochunguang** [comment]
cache dir is in   C:\Users\userName\AppData\Roaming\draw.io.  if your plugin can not work , you can delete cache dir then restart app.

**Comment by m-mohamedin** [comment]
Please try the new release 12.4.0
