### ISSUE TITLE
application crash attempting to save to samba share

### ISSUE THREAD

**Issue by mMerlin** [jgraph/drawio-desktop#1567]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Unable to open from or save to a samba share using Linux desktop app

**To Reproduce**
1. Open existing drawing file
2. Click on 'File | Save As'
[2:1229/222824.078914:ERROR:browser_main_loop.cc(276)] GLib-GObject: invalid cast from 'GtkFileChooserNative' to 'GtkWidget'
3. Other Locations | «shared_folder» on «samba_share».local | …
4. Click Save
drawio quit unexpectedly 
--- Running report_uReport ---
Error: No segments found in coredump './coredump'
('report_uReport' exited with 1)

1. Copy drawio file to samba share outside of app
2. Click on 'File | Open…
[2:1229/222619.317409:ERROR:browser_main_loop.cc(276)] GLib-GObject: invalid cast from 'GtkFileChooserNative' to 'GtkWidget'
3. Other Locations | «share_name» on «samba_server».local | … | «file».drawio | Select
[2:1229/222743.914774:ERROR:browser_main_loop.cc(276)] GLib-GObject: ../gobject/gsignal.c:2778: instance '0x26e40255a750' has no handler with id '18085'
The file does not open

**Expected behavior**
The file should be saved to the folder on the samba share
The file on the samba share should be openned

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.15

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**

6.6.8-100.fc38.x86_64
Gnome 44.7
Wayland
Flatpak

A search in issues found #1070 asking about using all registered url schemes. Declined for security reasons. Does smb specifically fall into that deliberately not supported for security? Is it a bug?

**Comment by davidjgraph** [comment]
If you're using the flatpak distro please file with the flatpak distro author, https://github.com/flathub/com.jgraph.drawio.desktop

We cannot support versions that we don't create.

**Comment by mMerlin** [comment]
Sure. Does the version you do support handle samba shares? Flatpak will not add new features, but it is quite possible that it breaks something.

EDIT:
It does. AppImage works.

**Comment by marek22k** [comment]
@mMerlin Did you find a solution? I get the same error.

Edit: After executing `systemctl --user restart xdg-desktop-portal.service` and `systemctl --user restart xdg-desktop-portal-gtk.service` it works for me.

**Comment by mMerlin** [comment]
My 'solution' was to use the AppImage instead of flatpak.
