### ISSUE TITLE
File chooser broken on Ubuntu

### ISSUE THREAD

**Issue by mrm1st3r** [jgraph/drawio-desktop#1568]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When opening or saving files, the file chooser does not render fonts correctly.

**To Reproduce**
1. Open Draw.io
2. Click 'File > Open'
3. wait for system file chooser to appear

alternatively
1. Open Draw.io
2. create any new diagram
3. click 'File > save' or press CTRL+S
4. wait for system file chooser to appear
5. See error

**Expected behavior**
the file chooser displays readable text

**Screenshots**
![Bildschirmfoto vom 2024-01-03 13-07-13](https://github.com/jgraph/drawio-desktop/assets/4249334/2e1ab19a-99f7-4736-962e-5e70af165194)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.16

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10

**Additional context**
When saving a diagram with the broken file chooser, the file name will be correctly written, while not being displayed in the file chooser.

Draw.io language is set to german, OS language as well.

**Comment by davidjgraph** [comment]
Duplicate https://github.com/jgraph/drawio-desktop/issues/368

**Comment by aldas** [comment]
This helped me to get it working https://github.com/electron-userland/electron-builder/issues/5217#issuecomment-700707564

```bash
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```

**Comment by DeadlyChambers** [comment]
If you installed drawio with snap, ensure the drawio app is closed, and you will need to additionally clear snaps cache

```shell
rm -rf ~/.cache/fontconfig
rm -rf ~/snap/drawio/common/.cache/fontconfig
```

Then open it again and try to load an existing diagram. It initially gave me an error, but then it worked after that.
