### ISSUE TITLE
Linux Ubuntu 23.10 - PDF export and print to file - extra pages or crash 

### ISSUE THREAD

**Issue by CoolGames** [jgraph/drawio-desktop#1569]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Attempting to resize Page Setup from A4 to US-Letter then export or print to PDF is unsuccessful with out work around.

 
**To Reproduce**
1. Open existing A4  Landscape draw.io source
2. Modify Page Setup to US-Letter
3. Select All and Group
4. Move to left to fit on shorter  page width.
     Luckily this works without scaling.
6. Save
7. Print to File crashes Draw Desktop before creating PDF 
    Export to PDF adds blank pages already reported at
    jgraph/docker-drawio#147 but work around by omitting blank pages when printing to new PDF.

**Expected behavior**
I expect a US-Letter PDF to Preview or print without resize to fit and pass on to others

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v22.1.15

**Desktop (please complete the following information):**
 - OS: Linux - [Ubuntu Studio 23.10](https://ubuntustudio.org/download/)
 -  Draw IO: [Draw IO Desktop v22.1.15 ](https://github.com/jgraph/drawio-desktop/releases/download/v22.1.15/drawio-amd64-22.1.15.deb)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Not Applicable

**Additional context**
I began with Chrome Browser on Linux but prefer local desktop version if available.
I will be trying other versions on Raspberry Pi 400 Bookworm, ASUS  Chromebook and Windows 11 laptop to isolate or confirm dependencies.
I used  this [Roland s-1 diagram at GitHub
](https://github.com/candlerb/roland-s1-quick-reference) on A4 page but use US-Letter on printer

**Comment by m-mohamedin** [comment]
Unfortunately, we cannot reproduce. We doubt it is due to large diagram size and limited raspberry pi resources.
Can you repeat on a larger machine?
