### ISSUE TITLE
Possible wrong download links for 11.2.5

### ISSUE THREAD

**Issue by LionNatsu** [jgraph/drawio-desktop#157]
![image](https://user-images.githubusercontent.com/6694582/64225624-b5513280-cf0e-11e9-81fd-c1d9cac355a5.png)
"Windows Installer" and "Window No Installer" links are identical to those links in release version 11.2.4.

At the same time https://github.com/jgraph/drawio-desktop/releases/download/v11.2.5/draw.io-11.2.5-windows-installer.exe does not exist.

**Comment by davidjgraph** [comment]
Yes, that's correct. The windows version will update once you install it.
