### ISSUE TITLE
Corrupted files window when opening a file

### ISSUE THREAD

**Issue by Aldisti** [jgraph/drawio-desktop#1574]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When I try to open an existing file it opens a files window where every character of the file/folder names are replaced with rectangles.

**To Reproduce**
1. Open draw.io app
2. Click on 'Open Existing Diagram'
3. See error

**Expected behavior**
It should open a files window with the readable names of my files and folders.

**Screenshots**
![Screenshot from 2024-01-05 11-22-39](https://github.com/jgraph/drawio/assets/76822748/2eda9d9b-d7cf-4e04-b26e-0521b7a00234)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.16

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-

**Additional context**
I tried to restart different times my pc and to reinstall the program, but nothing worked out.

**Comment by m-mohamedin** [comment]
Unfortunately, we cannot reproduce the issue. Please give us more details (e.g, the language of the OS, the package used for installation (dep, AppImage, ...) ...)

**Comment by Aldisti** [comment]
I understand, and I think this is a very particular and specific problem. Anyway, these are the more details:

**OS language**
English(US)
**Installation package**
[Ubuntu App Center](https://github.com/ubuntu/app-center)
Version 1.0.0-alpha
**OS installation type**
Dual-boot with Windows

I can't think of any other detail.

**Comment by Aldisti** [comment]
I solved the problem, or at least got around it. I installed draw.io manually with these commands:
```bash
curl -s https://api.github.com/repos/jgraph/drawio-desktop/releases/latest | grep browser_download_url | grep 'amd64.*.deb' | cut -d '"' -f 4 | wget -i -
```
```bash
sudo apt -f install ./drawio-amd64-*.deb
```
Sorry for the trouble.

**Comment by davidjgraph** [comment]
Also see https://github.com/jgraph/drawio-desktop/issues/368.
