### ISSUE TITLE
White text change to grey when exported to PDF

### ISSUE THREAD

**Issue by adithyaappu** [jgraph/drawio-desktop#1576]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
In the desktop version when I export to PDF, white text becomes grey. #1050 describes similar issue while printing, but I experience the same in exporting.

**To Reproduce**
1. Add shape
2. Select a high saturation style
![image](https://github.com/jgraph/drawio-desktop/assets/37062841/2f29321b-9244-447f-9698-2aa1e35bbaa0)
3. File > Export As > PDF
4. 'Selection Only': Export
5. View the export

**Expected behavior**
Text color remains white while exporting.

**Screenshots**
Diagram
![image](https://github.com/jgraph/drawio-desktop/assets/37062841/fb2ac526-ad8c-4e5c-85a2-0ccb7a17e29b)

PDF Export
![image](https://github.com/jgraph/drawio-desktop/assets/37062841/b17e3678-3344-4f61-92ec-7a483b98fe7f)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.16

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
A work around I found out from draw.io article is to uncheck both 'Word Wrap' & 'Formatted Text'. When unchecked the export retains the white colour. 

![image](https://github.com/jgraph/drawio-desktop/assets/37062841/456da268-bcb1-4df5-a395-5e2a45d9821a)

**Comment by davidjgraph** [comment]
Can you attach the PDF exported please?

**Comment by adithyaappu** [comment]
Sure. 
[white-text-issue-grey.pdf](https://github.com/jgraph/drawio-desktop/files/13888285/white-text-issue-grey.pdf)

**Comment by LinguaOccultus** [comment]
Can confirm this issue. There have been several issues over the last major versions, especially when using the dark mode, but while those seemed to have been fixed, this came up a new with one of the last ones. I regularly export PDFs and always use the dark mode so I would have become aware of this and it cannot be too long standing again now.

It also changes some color values for me aside the text color issue described above.

Current version: 22.1.18

**Comment by ch-andrei** [comment]
Also have this issue.

@adithyaappu thank you for sharing a workaround

**Comment by pierre-haessig** [comment]
I got caught by this bug on 23.0.2 (_not using dark mode_). I thought that adding a black text background would make things better (in case it was some kind of buggy contrast enhancement), but in fact the white text on black background becomes in the pdf export light gray on white!

Png export:

![test_white_font](https://github.com/jgraph/drawio-desktop/assets/1010404/5ce23a8e-0eec-4fe3-9dcc-6c327cf51470)

Pdf export:

[test_white_font.pdf](https://github.com/jgraph/drawio-desktop/files/14141457/test_white_font.pdf)

Screenshort of Pdf export:

![test_white_font pdf_screenshot](https://github.com/jgraph/drawio-desktop/assets/1010404/fe0b4780-0ac1-4a86-a5c8-a68d7bf78655)

**Comment by Norbert80** [comment]
I just filed a duplicate issue: #1630
#1630 has a testkit attached.

**Comment by Norbert80** [comment]
This issue really affects productive work. Is it possible to set a milestone?

**Comment by davidjgraph** [comment]
This is an open source project, asking for "milestones" and "ETAs" isn't really appropriate.

There's a release currently built, you can see if that improves the issue.

**Comment by Norbert80** [comment]
> This is an open source project, asking for "milestones" and "ETAs" isn't really appropriate.
> 
> There's a release currently built, you can see if that improves the issue.

Thanks for the hint... where can I find additional info? Which build should address this issue? Which path has been identified to cause this regression?

**Comment by adithyaappu** [comment]
@Norbert80 use the work around specified in the original issue, under "Additional Context" until there is a fix. Don't bug developers with specific issues. Priorities are set considering many factors.

**Comment by LinguaOccultus** [comment]
I can confirm the color issues for PDF export are solved for me in 23.1.5 – however, since the custom fonts are still ignored (#1604) it does not help much so far ... (as both need to be fixed to make exporting work again).

**Comment by LennonReid** [comment]
It was initially resolved in v23.1.5, but unfortunately, the issue persisted and resurfaced again in v24.0.4. Further investigation is required to address it at a deeper level. Thank you for your contribution to this open-source project. @davidjgraph

**Comment by alderg** [comment]
This works for me, exporting [this test case](https://app.diagrams.net/#RzZVBb4MgFMc%2Fyw4emyjU1l5nW3vYkiUemh1ZQSVBn6F02n36gWDVbEu2w9rCQfjx3hPe%2FxE8HJdtIkldPANlwkM%2BbT289hAKggXWH0POlqzClQW55NQifwAp%2F2DOs6cnTtnRMYsUgFC8nsIDVBU7qAkjUkIzNctA0AmoSc4m2zAgPRDBvpjtOVWFpRFaDnzHeF6oy4Hd%2BUrSG7vAx4JQaEYIbzwcSwBlR2UbM2GSN83L9ofVy8Ykq9RvHJIyk2%2Fr15niSfvyhIoqEtnMRXkn4uQOvNNe4KFY0z1IQR%2Fc7tW5T4mEU0WZiep7%2BLEpuGJpTQ5mtdFFoFmhSqFngR5mXIgYBMjOF%2FtdMxwqNeLbrjnuqiDs7VL372%2BO3O%2BfScXaEXIpSBiUTMmzNulXI2RdXD2GLkIziDv3Q8uKsbBLpytxBZVfQg851wOX9j9IgK4swaprdyQBmqNba4CvrMFmYfoNNVgE%2BM6uwfzKEkS%2B6Xckwb9eAz0dXppubfRe480n#%7B%22pageId%22%3A%22qRj52YWzYXG7DPhgwWa0%22%7D) via File, Export as, PDF with default settings.

**Comment by davidjgraph** [comment]
Does 24.0.6 show this issue?

**Comment by LennonReid** [comment]
Hi @davidjgraph,

Apologies for the delay in getting back to you on this!

I just tested it on version 24.1.0, and the issue seems to be resolved there. Looks like the fixes implemented after 24.0.4 did the trick.

Thanks for checking in and for your ongoing support of this project.

Cheers!
