### ISSUE TITLE
Slowness/Holding when editing Shared Diagram in real time

### ISSUE THREAD

**Issue by alvescps** [jgraph/drawio-desktop#1579]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When I have 1 person or more editing a diagram in real time, there are slowdowns and crashes when I move/add/remove objects!
I have 16GB of RAM and it is not overloading the processing.

This problem also occurs with other people who are editing with me.

-----------------

This occurs on Draw.io (Web) and I share my diagram for sharing via the "Share" button (Google Drive)

**To Reproduce**
1. Create a diagram
2. Click "Share"
It is. Add people to the Diagram to edit with you
4. When editing files, it slows down and freezes (around 10~15 seconds)

**Expected behavior**
These crashes should not occur, it should be fluid.

**Screenshots**
a screenshot fails to demonstrate the problem.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v22.1.17

**Desktop (please complete the following information):**
 - OS: Windows (accessing Web "Draw.io")

**Additional context**
Nothing more to report...

**Comment by alvescps** [comment]
Nothing?

**Comment by davidjgraph** [comment]
No, because you're talking about sharing with a tool that doesn't support sharing.

**Comment by alvescps** [comment]
![colaborativo (1)](https://github.com/jgraph/drawio-desktop/assets/156326508/fa6d8e4a-77aa-4d1d-b743-630d09215071)

**Comment by davidjgraph** [comment]
That's not the desktop app, this is the repo of the desktop app.
