### ISSUE TITLE
Mac OS: unable to exit fullscreen window

### ISSUE THREAD

**Issue by gcmartijn** [jgraph/drawio-desktop#1585]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Apple M1 Sanoma 14.2.1

**To Reproduce**
1. Start the program
2. Maximise the window (using the window green icon)

**Expected behavior**
Possibility to undo maximise the window and make it smaller again.

**Screenshots**
<img width="442" alt="Screenshot 2024-01-14 at 10 49 08" src="https://github.com/jgraph/drawio-desktop/assets/6859464/b8377a82-d98b-4f57-b4ba-88bc490291a1">

As you can see, only a window close button.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 22.1.18

**Desktop (please complete the following information):**
 - OS: MacOS

There is no fix, it will start full screen after I quit and close the program.

**Comment by lstpsche** [comment]
@gcmartijn
found a workaround, you can exit the fullscreen mode from Mission Control, when you hover the screen with draw.io at the top bar, it'll show you a button for unmax in the top left corner of the tile.

**Comment by blinq-erik** [comment]
Extra information "fn +f" does not work for enter/exit full screen.
version v22.1.18

**Comment by sivaswami** [comment]
Noticed  3 issues which is causing this issue in Mac
#1. Fn+F key is configured to "Draw Eclipse". "Fn" key is not interpreted inside DrawIO.
#2. Command + Ctrl + F  is bound to "Find window" 
#3. "Draw IO" menubar is not in sync with MacOS topbar and not globally configurable. this is main reason all MacOS shortcuts like full screen are not working and customizable. Created a separate issue for that.

**Comment by gcmartijn** [comment]
> @gcmartijn found a workaround, you can exit the fullscreen mode from Mission Control, when you hover the screen with draw.io at the top bar, it'll show you a button for unmax in the top left corner of the tile.

Yes thanks !

**Comment by m-mohamedin** [comment]
https://github.com/electron/electron/issues/41023
We'll revert to older version of electron to avoid this problem

**Comment by davidjgraph** [comment]
Fix in 22.1.21.

**Comment by jvcdk** [comment]
I have this issue on Linux (Ubuntu 22.04). Draw.io version 24.1.0.
