### ISSUE TITLE
DrawIO MenuBar is  showing only Edit menu  in MacOS

### ISSUE THREAD

**Issue by sivaswami** [jgraph/drawio-desktop#1588]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The MacOS top bar is showing only "Edit menu" for DrawIO. The other Menu's and Menu items are not available.

**To Reproduce**
1. Launch DrawIO with Menubar in MacOS

**Expected behavior**
The contents of DrawIO menubar to show in MacOS topbar

**Screenshots**
<img width="536" alt="image" src="https://github.com/jgraph/drawio-desktop/assets/1367716/f5a809be-011b-4877-834f-d1f2a36bdb34">
**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z
v22.1.18
**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...
 MacOS

**Additional context**

**Comment by nacho4d** [comment]
I also see this bug.

draw.io is a great tool and I would like it even more if it were a bit more native-ish when run in macOS.

Some suggestions:

See below screenshot, the entire red area can be removed always (not only in some themes). It will save space and let users focus in the content and not in the surroundings.

1. The menu items (blue area) should be moved to the macOS file menu (as this issue notes)
2. The file name inside the window is not needed (green area). It is already show in the window frame and the light/drak mode change button can be also accessed from the file menu. It is NOT something users change in very often. 
3. The icon of the file (orange area) show be moved to the center top of the window. Left to the name, in the purple area. In macOS, documents will only show the icon when the file is saved. 
4. Some icons looks blurred in retina displays. Would be great if you use svg icons.

Anyway, thank you for this great tool. I hope it gets even better in future releases! 

<img width="838" alt="Screenshot 2024-01-30 at 18 38 13" src="https://github.com/jgraph/drawio-desktop/assets/111651/2509ae70-e3a2-40eb-9cc6-22d005e24d13">

(PS: I wanted to contribute but saw the contributions policy so only writing some ideas here. )
