### ISSUE TITLE
Behavior Monitoring notification by Trend Micro Worry-Free Business Security

### ISSUE THREAD

**Issue by romavonk** [jgraph/drawio-desktop#159]
Using the latest desktop version for windows 10 64 bit 11.2.4 build 284.
Getting a notifications by Trend Micro during startup for 6 times. 
All notifications are the same:

- Security threat:    Program Library Injection 
- Subject:               C:\Program Files\draw.io\draw.io.exe
- Target:                 ZwWriteVirtualMemory
- Operation:           Invoke API

![FalsePositive](https://user-images.githubusercontent.com/49060089/64604286-2aff4780-d3c2-11e9-81e1-5469e7abf1bb.png)

**Comment by davidjgraph** [comment]
It's false positive, you can report it as such.
