### ISSUE TITLE
Full screen mode of draw.io v22.1.18 can no longer be deactivated on the Mac with macOS Sonoma 14.2.1 (23C71). 

### ISSUE THREAD

**Issue by janismerg** [jgraph/drawio-desktop#1591]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Full screen mode of draw.io v22.1.18 can no longer be deactivated on the Mac with macOS Sonoma 14.2.1 (23C71). As soon as I have activated it, the full screen mode can no longer be deactivated, the function key is grayed out, only the exit button still works.
**To Reproduce**
1. Go to draw.io
2. Click on the green maximize button
3. See that the button is grey and you can't exit the fullscreen mode
4. Even when you new start the program, the fullscreen mode is still activated

**Expected behavior**
Normally the button to deactivate the full screen mode is not grayed out and can be pressed, unfortunately this does not work at the moment.

**Screenshots**
<img width="1512" alt="draw io_Fullscreen" src="https://github.com/jgraph/drawio/assets/82587971/05a38f4e-f48b-4b0a-bcf1-9fe3b0e696a5">
<img width="245" alt="draw io_grey_button" src="https://github.com/jgraph/drawio/assets/82587971/8759df59-d0fe-4a1a-8ec6-1944c8581a63">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v22.1.18

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: MacBook Pro 14" M3
 - OS: macOS Sonoma 14.2.1
 - Desktop version
 - Version 22.1.18

**Comment by davidjgraph** [comment]
Duplicate #1585

**Comment by jvcdk** [comment]
I have this issue on Linux (Ubuntu 22.04). Draw.io version 24.1.0.

Found a work-around, though:

- Find your draw.io config file. On Linux it is `$HOME/.config/draw.io/config.json`
- Edit the file, changing the booleans of `lastWinSize` to false.

Example... from:
```
"lastWinSize": "3440,1440,0,0,false,true"
```

to:
```
"lastWinSize": "3440,1440,0,0,false,false"
```

**Comment by elca2712** [comment]
> I have this issue on Linux (Ubuntu 22.04). Draw.io version 24.1.0.
> 
> Found a work-around, though:
> 
> * Find your draw.io config file. On Linux it is `$HOME/.config/draw.io/config.json`
> * Edit the file, changing the booleans of `lastWinSize` to false.
> 
> Example... from:
> 
> ```
> "lastWinSize": "3440,1440,0,0,false,true"
> ```
> 
> to:
> 
> ```
> "lastWinSize": "3440,1440,0,0,false,false"
> ```
Since a while I had this problem and it works also for Windows, thanks
