### ISSUE TITLE
The rtl future in app is not working properly.

### ISSUE THREAD

**Issue by kianoosh** [jgraph/drawio-desktop#1592]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
in view mode the rtl future is not working properly

**To Reproduce**
1. use a text box to start writing
2. add a number before text
3. exit edit mode 

**Screenshots**
<img width="433" alt="Screen Shot 1402-10-27 at 4 13 30 PM" src="https://github.com/jgraph/drawio-desktop/assets/1878365/ef0bfa18-0947-489c-9400-a4f9d6b1b290">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.18

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by m-mohamedin** [comment]
Hi,

I've tried the same and I see the Automatic text direction doesn't work in this case and you must explicitly use the Right to left one

![Screenshot 2024-05-05 at 10 05 24 PM](https://github.com/jgraph/drawio-desktop/assets/24944765/db8ba39f-49be-46f4-a325-7c87bc40c28b)
