### ISSUE TITLE
Poor image quality when embedding drawio into a word file and printing it to pdf

### ISSUE THREAD

**Issue by XaviVilassar** [jgraph/drawio-desktop#1598]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I get a very poor image quality when embedding drawio diagram into a word file and printing it to pdf. If I either export it or print it to pdf directly from Drawio the result is perfect, but when printing to pdf the Word file containing drawio on it the outcome is really poor. Exporting from drawio to png and then inserting it to the word also looks very poor although the image in the Word file looks fine.

**To Reproduce**

**Expected behavior**
I expected a good quality image.

**Screenshots**
To pdf from Drawio:
![imatge](https://github.com/jgraph/drawio-desktop/assets/157006841/b3f46c63-8a9d-46e0-be8f-bcaa84124342)

To pdf from Word file with embedded diagram:
![imatge](https://github.com/jgraph/drawio-desktop/assets/157006841/721159be-c5b1-43a2-a743-15d484dc7a27)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io online

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by davidjgraph** [comment]
If the PDF output from draw.io is correct, how does the issue with PDF to word conversion relate to draw.io?

**Comment by HereComesWalrus** [comment]
I think you just need to export the image with higher zoom, like 300%. The resolution is increased in my experience

**Comment by lni-dev** [comment]
@XaviVilassar did you fix it somehow?
