### ISSUE TITLE
Mathjax support

### ISSUE THREAD

**Issue by languitar** [jgraph/drawio-desktop#16]
Is there a chance to get mathjax support in the desktop version?

**Comment by alderg** [comment]
Via Extras, Mathematical Typesetting (only available when online for technical reasons).

**Comment by languitar** [comment]
Sorry, I was explicitly requesting this for the desktop version. I know that this exists in general.

**Comment by alderg** [comment]
I mean the desktop version. But it needs to be online on startup. Please check the Extras menu to enable the feature.

**Comment by languitar** [comment]
Ok, strange, I can't find that entry there and it definitely was online while starting.

**Comment by davidjgraph** [comment]
What version of the desktop have you got (about dialog)?

**Comment by languitar** [comment]
This was 7.8.7, but now it works. So I don't know.

Isn't there a chance to just bundle mathjax and all the required libraries with the drawio code locally, so that there is no need for an online connection?

**Comment by davidjgraph** [comment]
Try the exercise yourself, you'll see the problems.

**Comment by cvanelteren** [comment]
Is there any updates on adding this to the desktop version?

**Comment by davidjgraph** [comment]
@cvanelteren What have you tried? What environment do you have? What results did you see?
