### ISSUE TITLE
Application resets maximized window (Windows)

### ISSUE THREAD

**Issue by LinguaOccultus** [jgraph/drawio-desktop#1600]
**Describe the bug**
Whenever I set the applications window to maximized on Windows, it immediately loses this setting again and again when one of the following happens: a) application is simply closed and opened again (sometimes) b) a Draw.io file is opened by double-clicking it in the Windows File Explorer (close to each time). The window size is then set to a large value but with a gap of around 50-100 px or so all around it from the screen size. It is the only app that behaves this way and I know this was once fixed and also often reported before and is now an issues again for many major version now.

**To Reproduce**
1. Open the app
2. Set window to maximized
3. Close the app
4. Re-open the app by shortcut or double-clicking a file linked to it

**Expected behavior**
Obvious. The preferred setting for the window size should be persistant as with all other apps.

**Screenshots**
Not needed, I guess (can provide one if desired).

**draw.io version (In the Help->About menu of the draw.io editor):**
- Draw.io version: Draw.io Desktop 22.1.21 (currently; many major version back also)

**Desktop (please complete the following information):**
- OS: Windows 11 Pro 23H2

**Additional context**
None needed, I guess. Long standing and always retuerning issue ... =(

**Comment by davidjgraph** [comment]
Please re-test in 24.4.0.

**Comment by LinguaOccultus** [comment]
-

**Comment by davidjgraph** [comment]
OK, if you see it again comment and we'll reopen.
