### ISSUE TITLE
Embedding Japanese OTF fonts

### ISSUE THREAD

**Issue by KeizoYamamoto** [jgraph/drawio-desktop#1603]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I have some Japanese OTF fonts installed and have set them to custom fonts in draw.io.
When I create a diagram and export it as PDF, these fonts become Type 3 fonts.

**Describe the solution you'd like**
I would like them to become embedded subset fonts of Type 1 (CID).

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
Use print to PDF, rather than our PDF export.

**Comment by KeizoYamamoto** [comment]
When I printed it to PDF, it became a Type 1 font. Also, when I exported it as a PDF, it became a Type 1 font, so I think that something has been improved with the update.

Thank you!
