### ISSUE TITLE
Argo Tunnel Error when Exporting as PDF

### ISSUE THREAD

**Issue by edu24ylee** [jgraph/drawio-desktop#1609]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When exporting a .drawio file as a PDF, an Argo Tunnel error is encountered at convert-eu.diagrams.net. Cloudflare gives the following error and message: "Error 1033: You've requested a page on a website (convert-eu.diagrams.net) that is on the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. The host (convert-eu.diagrams.net) is configured as an Argo Tunnel, and Cloudflare is currently unable to resolve it."

**To Reproduce**
1. Create a new diagram on the online tool
2. Go to "File" then "Export as"
3. Export as either a PDF, or choose "Advanced" then PDF.
4. Select settings and download location
5. Press "Save"

**Expected behavior**
The file should export as a PDF and download automatically.

**Screenshots**
![Screenshot 2024-01-24 132832](https://github.com/jgraph/drawio-desktop/assets/114205796/23858c32-25d3-4c82-bfad-c5b496d6734c)

**draw.io version (In the Help->About menu of the draw.io editor):**
v.22.1.22

**Desktop (please complete the following information):**
 - Windows 11 -- Google Chrome

**Additional context**
This issue has been ongoing since at least yesterday, if not longer than that.

**Comment by davidjgraph** [comment]
Is this still happening?

**Comment by edu24ylee** [comment]
Nope, actually, it appears to be working again now. I can delete or close the issue
