### ISSUE TITLE
Change the default file extension on all platforms to ".drawio"

### ISSUE THREAD

**Issue by ratermir** [jgraph/drawio-desktop#161]
"draw.io" is the great tool, but I would propose one (I belive small) change. 
I vote for changing file extension to ".drawio" anywhere it is possible. The ".xml" extension was an unfortunate choice (this extension is very generic, and many other tools / apps use, which causes issues in opening).

Setting the ".drawio" extension as an default and only used will be much better choice. In case someone has an old files (with ".xml" extensions), he/she can either rename them or open manually to the app. 

I know there is similar issue #120 , but it relates only to the desktop app. My proposal is to change it everywhere (for example in nextcloud application, download files etc ...) and set it as a default and only used extension.

**Comment by davidjgraph** [comment]
It is the default extension everywhere that I know of, where are you not seeing that?

**Comment by ratermir** [comment]
When I download the schema from online tool, the downloaded file gets "xml" extension. Also, nextcloud application that integrates draw.io into nextcloud (also great tool :) ) uses "xml" extension (but it may be case of the application - I am not sure here).

**Comment by davidjgraph** [comment]
For NextCloud you would need to contact the author of that plugin. By online you mean www.draw.io? What steps do you follow?

**Comment by ratermir** [comment]
Hm I tried it again in online "draw.io" and now it saved the file as "drawio". So sorry for misinformation. 
I don't remember exactly what I did before, but in some situation (I guess il was a chrome browser extension) it saved a XML file. I have it in my computer at work, I'll try it on Monday.
And about "nextcloud" app - I'll look at bugs there, eventually create one. Thank you
