### ISSUE TITLE
[MacOS] button for disabling fullscreen mode not working

### ISSUE THREAD

**Issue by Makki93** [jgraph/drawio-desktop#1611]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

Button for disabling fullscreen mode on macOS not displayed.

**To Reproduce**
1. Go FullScreen on MacOS.

**Expected behavior**
Button should be showed

**Screenshots**
How it should be (comparison with chrome)
![image](https://github.com/jgraph/drawio/assets/44347047/3c087075-b319-4816-99a2-af628e3a8d4c)

How it is
<img width="208" alt="image" src="https://github.com/jgraph/drawio/assets/44347047/48624d21-7520-418c-ac24-624f6b66bd02">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.18

**Desktop (please complete the following information):**
 - OS: macOs 14.3
 - Browser Version [e.g. 22]

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-

**Additional context**

**Comment by davidjgraph** [comment]
Dupilcate #1585
