### ISSUE TITLE
Print job add an additional blank page

### ISSUE THREAD

**Issue by dunxd** [jgraph/drawio-desktop#1615]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When printing from draw.io desktop app in Windows an additional blank page is included.  This is the case for both paper and PDF printing.

**To Reproduce**
1. Create drawing with a single page - don't add items close to the page margins
2. Click on File > Print...
![image](https://github.com/jgraph/drawio-desktop/assets/16608541/9294e21e-0a83-4249-820f-01d69bef24e2)
3. Select adjust to 100%
5. Click Ok
6. Complete print using system print dialog
7. Check for blank page added at the end - or page with cut off image

**Expected behavior**
Print only the pages included in the drawing, and no extra ones.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.21

**Desktop (please complete the following information):**
 - OS: Windows 11 and macOS 14.2.1

**Additional context**

**Comment by dunxd** [comment]
I just checked this on my Mac with v23.0.2 and exactly the same issue.  It happens with blank document created by default.  It's only one page but two are printed.

**Comment by davidjgraph** [comment]
Please re-test with 24.4.13.
