### ISSUE TITLE
Selecting fit to 1 x 1 page in print makes the drawing larger than 1 page

### ISSUE THREAD

**Issue by dunxd** [jgraph/drawio-desktop#1616]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When selecting Fit to 1 sheet across, by 1 sheet down, print size should be reduced to fit on a single page.  For an image that prints on a single page (ignoring the related bug #1615) when set to 100% this should not result in a print job that splits the image across multiple pages.

**To Reproduce**
1. Create drawing with a single page, no items close to the margins
2. Click on File > Print
![image](https://github.com/jgraph/drawio-desktop/assets/16608541/f3468d5d-09f8-4696-aee5-76398a7d2c02)
4. Select Fit to 1 sheets across by 1 sheets down then click Ok
5. Complete print job using system OS.
6. Check print job for additional page.
![image](https://github.com/jgraph/drawio-desktop/assets/16608541/cf5d218f-cbb5-4cd2-b8c1-81bac2f0172e)

**Expected behavior**
Reduce print size so it fits on the number of sheets specified.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.21

**Desktop (please complete the following information):**
 - OS: Windows and macOS

**Additional context**

**Comment by dunxd** [comment]
Just tested this on my Mac with version 23.0.2.  Selecting 100% keeps image on a single page (but prints extra blank page).
<img width="858" alt="image" src="https://github.com/jgraph/drawio-desktop/assets/16608541/1632f9da-553c-44b0-8379-360a45dab4e7">
Setting it to fit on 1 x 1 sheets, splits the same image across two pages.
<img width="858" alt="image" src="https://github.com/jgraph/drawio-desktop/assets/16608541/a08c58c9-d51e-4f08-a15a-260b6834f976">

**Comment by davidjgraph** [comment]
Please re-test with 24.4.13
