### ISSUE TITLE
Can we change the center point of rotation?

### ISSUE THREAD

**Issue by together00** [jgraph/drawio-desktop#1617]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
By default, the center point of rotation (or pivot point) in drawio is the center of the shape, and we can not the change the center point of rotation.

**Describe the solution you'd like**
Let us change the center point of rotation.

**Describe alternatives you've considered**
I can not find any other good alternatives yet.

One ok (yet not good) alternative is to group another shape to make the pivot point of the group shape be your required pivot point of the original shape. However, according to [groups only can be rotated by dragging the curved arrow](https://github.com/jgraph/drawio/issues/4463), it is quite limited for this alternative, since it is hard for us to control the angles of rotation by only dragging the curved arrow manually.

**Additional context**
In drawio, we can only rotate the shape around the green point. Now, we want to rotate the shape around the red point with arbitrary angles.

<img src="https://github.com/jgraph/drawio-desktop/assets/150029146/f538e96d-0def-4af3-8cbb-d603114ec389" width=30%>

**Comment by davidjgraph** [comment]
Thanks for your suggestion, but the complexity of implementation overrides the advantages in this case, so we decline the request.
