### ISSUE TITLE
chocolatey integration

### ISSUE THREAD

**Issue by UsernameIsAlreadyTakenByMe** [jgraph/drawio-desktop#162]
Hi, can we automate updating choco packages from github releases?

**Comment by davidjgraph** [comment]
Hmmm, I guess, though never heard of it until now. What's the process?

**Comment by digitalcoyote** [comment]
I'd be willing to create a chocolatey package and add it to my AU repo (automatically updates chocolatey based on when you publish new releases)

**Comment by davidjgraph** [comment]
Cool, if there's something to add to our release process, just shout.

**Comment by digitalcoyote** [comment]
Somehow I missed that there is already a package (outdated) on Chocolatey. I'm now going through the process of contacting the maintainer to see about getting updates pushed.

**Comment by davidjgraph** [comment]
That's https://github.com/DarwinJS

**Comment by digitalcoyote** [comment]
DarwnJS added me as a maintainer. I've gotten a bit swamped by work this week, so it will probably be this weekend before I can hook the original package into my CI (updates versions and links) and test it.

**Comment by hholst80** [comment]
Suggestion: Make a dependent project and do some gitops automation to automatically build a chocolatey package without bothering upstream repo with packaging.
