### ISSUE TITLE
Importing MS Visio shapes won't work (MacOS ARM) 

### ISSUE THREAD

**Issue by Ph-Red** [jgraph/drawio-desktop#1620]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When I try to import a new shape (Those : https://support.zpesystems.com/portal/en/kb/articles/how-to-download-stencils-for-ng-devices). It just doesn't happen on the desktop app. I've tried on the web app, and it does work.  

**To Reproduce**
1. Go to 'File > Import'
2. Select the .vssx file
4. Nothing happens, no message (error or success) and the shapes aren't added to the library.

**Expected behavior**
Expected to get the shapes added to my library 

**Screenshots**
Desktop version : 
![image](https://github.com/jgraph/drawio-desktop/assets/72567206/872b65d0-6474-44d7-a1c2-f94365fca47a)
![image](https://github.com/jgraph/drawio-desktop/assets/72567206/4ae84471-5190-4094-9289-8ca02a73da74)

From the web, imported the .vssx file and got the shapes added to the library:  

![image](https://github.com/jgraph/drawio-desktop/assets/72567206/7e2f9625-03c5-436c-ae53-0372b0fbd76c)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.0.2

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1 (23C71)

**Additional context**

Tried to restart and update (and restart again) the app, download the vssx file again, but not luck.

**Comment by davidjgraph** [comment]
The stencil file contains something that requires a server to convert it. The desktop app is designed to be isolated.

The workaround is to import on the web version and copy to desktop.
