### ISSUE TITLE
Make undo work per page rather than for the whole file.

### ISSUE THREAD

**Issue by andrewslavin** [jgraph/drawio-desktop#1621]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Most `.drawio` files I work with have multiple pages, and I usually make changes to several pages at a time, switching between them back and forth. I'm always frustrated when I start clicking `Undo` e.g. on `Page-1`, and suddenly the UI takes me to `Page-2` and starts undoing my actions on `Page-2`.

**Describe the solution you'd like**
When I start undoing my actions, `draw.io` should only undo the ones I applied to the page I'm currently on, without affecting other pages.

**Describe alternatives you've considered**
Currently I do not have a workaround for this. If clicking `Undo` takes me to another page, I stop, return to the original page, and start editing it to get it to the desired state by moving forward.

**Comment by davidjgraph** [comment]
Thanks for the suggestion, however this is the intended design on the app.

The app is primarily a web application that was ported to desktop. In a browser you could have several browser tabs open to achieve the result you want. One file is designed to be a single, coherent entity. Undo/redo follows that design decision. 

Changing that at this point of product maturity is simply impossible. Supporting both behaviours within the app using a switch is so complex to be effectively impossible as well.
