### ISSUE TITLE
Wrong font color in exported PDF (regression)

### ISSUE THREAD

**Issue by Norbert80** [jgraph/drawio-desktop#1630]
In the attached ZIP archive you find a drawio-file as testkit and PDFs exported by v22.0.3 and v23.0.2.

The PDF created by v22.0.3 correctly has white text while the PDF exported by v23.0.2 has grey text.

Thus, somewhere between these two builds there is a regression.

**Comment by Norbert80** [comment]
[testkit.zip](https://github.com/jgraph/drawio-desktop/files/14302246/testkit.zip)

**Comment by Norbert80** [comment]
Seems to be a duplicate of #1576.

**Comment by davidjgraph** [comment]
Closing, template not filled.

**Comment by Norbert80** [comment]
> Closing, template not filled.

I don't understand your reply. We have a regression here with several drawings having wrong font colors now in exported PDFs.
