### ISSUE TITLE
Element Search not available

### ISSUE THREAD

**Issue by a-nassif** [jgraph/drawio-desktop#1632]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I am sure I remember there was a search bar in the elements left side menu. Its not visible anymore. Not sure if this is intentionally removed or just happening on my end.

**To Reproduce**
1. Open a new drawio document

**Expected behavior**
A way to search for elements instead of navigating through the menus

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.1.4

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 22.04

**Additional context**
Firefox 122.0 (64-bit)

**Comment by davidjgraph** [comment]
<img width="592" alt="Capture d’écran 2024-02-16 à 10 16 06" src="https://github.com/jgraph/drawio-desktop/assets/1761087/04644e42-6b86-4d5e-9d29-de7e8003fa09">
