### ISSUE TITLE
[a paid user of Jira and have purchased your plug-in] CANNOT EDIT existing files or add new files, pls help ASAP

### ISSUE THREAD

**Issue by gracechangyc** [jgraph/drawio-desktop#1635]
### Preflight Checklist

* [Ｘ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [Ｘ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I am a jira user who purchased your plug-in and use the web page (Chrome) to operate your service. I found that when I want to edit an old file or create a new file, it will stop at the initial loading screen and cannot be edited. (The webpage asked me to install JavaScript, and I already installed JavaScript)

**To Reproduce**
1. Go to 'Jira confluence page'
2. Click on 'edit'
3. Scroll down to '--'
4. See error : Stay on the loading page

1. Go to 'your official website' https://www.drawio.com/
2. Click on 'start'
3. Scroll down to '--'
4. See error : Stay on the loading page

**Expected behavior**
Normal use to edit old files and new files

**Screenshots**
Link (Chrome): https://drive.google.com/file/d/1jvTPpDR1yqzq4XX8ZywRl9Ppzl3tOhbF/view?usp=sharing
Link (Jira): https://drive.google.com/file/d/10dS5Mk3ElU0LpnKctbd62C1jwRL8UIbB/view?usp=sharing
<img width="1368" alt="Screenshot at Feb 17 18-09-20" src="https://github.com/jgraph/drawio-desktop/assets/75288952/b20499fd-5b7c-4572-a687-cab68e2b9d91">
<img width="1270" alt="Screenshot at Feb 17 18-09-08" src="https://github.com/jgraph/drawio-desktop/assets/75288952/53d8b37a-89fa-4bb6-8455-9fb2b80eebb8">

**draw.io version (In the Help->About menu of the draw.io editor):**
cant see it

**Desktop (please complete the following information):**
 - MacOS

**Additional context**
Hope it will be fixed as soon as possible, thank you very much

**Comment by davidjgraph** [comment]
If you are using drawio for jira or confluence the correct support channels are described in https://marketplace.atlassian.com/apps/1210933/draw-io-diagrams-whiteboards?hosting=cloud&tab=support.

See the project README, https://github.com/jgraph/drawio-desktop:

_Support is provided on a reasonable business constraints basis, but without anything contractually binding. All support is provided via this repo. There is no private ticketing support._

_Purchasing draw.io for Confluence or Jira does not entitle you to commercial support for draw.io desktop. The draw.io integrations for Atlassian are sold by Seibert Media, they have no involvement with this project._
