### ISSUE TITLE
Fullscreen option does not work: cannot return to windowed mode

### ISSUE THREAD

**Issue by BasVink77** [jgraph/drawio-desktop#1638]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When using the option View -> Fullscreen, I can set the application to fullscreen. But when I select the option again (to exit fullscreen) it does not exit fullscreen. The tick mark does disappear, but application stays in fullscreen. Using local app on Win11.

**To Reproduce**
1. Go to 'View'
2. Click on 'Fullscreen'
3. Repeat 1 and 2
4. Observe application still in FullScreen mode.

**Expected behavior**
I expected the application to exit fullscreen mode when I click on fullscreen again and the tick mark is gone.

**Screenshots**
none

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.1.5

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by BasVink77** [comment]
This options is mainly irritating, the application is still usable. Just cannot move the application to another screen when using multiple monitors 😄

**Comment by davidjgraph** [comment]
It works for me. Pressing Esc also works.

draw.io-23.1.5-windows-installer.exe 
Windows 11 10.0.22631
Surface Book 2

**Comment by alekonko** [comment]
same problem, "Esc" pressure don't fix.

Win 10 22H2   
draw.io:23.1.5

**Comment by mataiotes** [comment]
After the update
I ran the program again and it was fullscreen and
ESC doesn't work.

**Comment by mataiotes** [comment]
> After the update I ran the program again and it was fullscreen and ESC doesn't work.

I did it, just delete appdata
delete folder "draw.io" in 'Users\AppData\Roaming'

**Comment by Corginyan** [comment]
I also encountered this problem and did some research. At first glance it looks like this:

Whenever the position or size of a window is changed, its state, including full-screen mode, is written to %appdata%\draw.io\config.json. After the application is launched again, the data is read and if the window was full screen before, the window state is applied via setFullScreen(true) for the electron window in the main process. This prevents the fullscreen api from functioning from the renderer process. Accordingly, we cannot change the state of the fullscreen electron window from the renderer process and config.json does not change either. We are locked in this state.

Accordingly, one solution for developers is to use additional ipc events to change the full-screen state in the main process from the renderer process.

A temporary solution for users to avoid deleting all application data is to delete config.json and restart the application, this will reset the fullscreen state and window position.

**Comment by alekonko** [comment]
> I also encountered this problem and did some research. At first glance it looks like this:
> 
> Whenever the position or size of a window is changed, its state, including full-screen mode, is written to %appdata%\draw.io\config.json. After the application is launched again, the data is read and if the window was full screen before, the window state is applied via setFullScreen(true) for the electron window in the main process. This prevents the fullscreen api from functioning from the renderer process. Accordingly, we cannot change the state of the fullscreen electron window from the renderer process and config.json does not change either. We are locked in this state.
> 
> Accordingly, one solution for developers is to use additional ipc events to change the full-screen state in the main process from the renderer process.
> 
> A temporary solution for users to avoid deleting all application data is to delete config.json and restart the application, this will reset the fullscreen state and window position.

i did same test! :)  Confirm that it works for me. Preserved prefs and notes.

**Comment by BasVink77** [comment]
Thanks for the responses, I was able to get out of fullscreen with the suggestions.

**Comment by creeper12356** [comment]
This issue is all about Windows OS, I'd provide a Linux workaround here, similar to what @Corginyan said.
```bash
rm ~/.config/draw.io/config.json
```

**Comment by m-mohamedin** [comment]
The Fullscreen menu option will be fixed in the next release.
Thanks for the report

**Comment by davidjgraph** [comment]
12.4.0
