### ISSUE TITLE
Incorrect import of .vsdx file

### ISSUE THREAD

**Issue by VinaySE1** [jgraph/drawio-desktop#1639]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
While I tried to open .vsdx file in the draw.io desktop application, there is a loss in the image from original .vsdx file.
Drawio-desktop - Installed version -23.0.2.0
**Laptop make and its operating system version.**
Device name [SE-5](https://jira.siemens-energy.com/browse/CSSDEV-1610)CG3050NV2
Processor 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz   2.61 GHz
Installed RAM 32,0 GB (31,7 GB usable)
Device ID 1F94D6E4-3B9D-4185-BF1D-1175EA14B0D8
Product ID 00330-80000-00000-AA680
System type 64-bit operating system, x64-based processor
Edition Windows 10 Enterprise
Version 22H2
Installed on ‎16.‎06.‎2023
OS build 19045.3930
Experience Windows Feature Experience Pack 1000.19053.1000.0

**To Reproduce**
1. Navigate to .vsdx file
2. Click on open with draw.io desktop version
3. The image wont load

**Expected behavior**
It should load full image.

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/158268739/73fb87fa-c2ec-4e68-81dc-adddd119f840)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.0.2.0

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
NA

**Comment by davidjgraph** [comment]
Please include the vsdx file.

**Comment by VinaySE1** [comment]
Hi David,
Thanks for the prompt reply. I've enclosed a zip file since the system doesn't permit the upload of **vsdx** files. Kindly take the necessary actions.

[PLM2020_IT_Support_Org_FULL_V000.zip](https://github.com/jgraph/drawio-desktop/files/14343015/PLM2020_IT_Support_Org_FULL_V000.zip)

**Comment by davidjgraph** [comment]
It imports correctly for me, did you pick the correct page tab?

**Comment by VinaySE1** [comment]
Hello David,

Would it be acceptable to include my customer in the call? 
This way, we can test things during the screen sharing session. I believe this could help and save some time.

Best regards,
Vinay

**Comment by davidjgraph** [comment]
I've no idea what you mean regarding a call. Did you pick the correct page tab?

**Comment by VinaySE1** [comment]
Hello David,

To clarify, I suggest that we all join a Teams/Zoom call to replicate the issue from our end. 
I am curious to know if your team provides on-call support.

Kindly confirm!

**Comment by davidjgraph** [comment]
Did you pick the correct page tab?

**Comment by VinaySE1** [comment]
Hello David,

Apologies for the delayed reply.

I believe we're doing something wrong from our end. 
Could you please provide us with step-by-step instructions to follow? 
This would greatly assist us in identifying the root cause.

Best regards,
Vinay

**Comment by davidjgraph** [comment]
At the bottom of the draw.io app there are page tabs. When importing from Visio, there may be more than one tab. Have you checked all the tabs? In the diagram you attached, page 1 contains the diagram.

<img width="422" alt="Capture d’écran 2024-03-18 à 15 56 51" src="https://github.com/jgraph/drawio-desktop/assets/1761087/2c0e607c-e225-4ebc-a0ac-2a867cdeec9c">

**Comment by VinaySE1** [comment]
Hello David,

I am just back from my sick leave.

I will ask the same with user and let you know if we find any success.

BR, Vinay

**Comment by VinaySE1** [comment]
Hello David,

User has verified for any additional tabs and closed all excess tabs. As per your instruction, the diagram is indeed in the page-1 tab exclusively.

However, the issue persists. Are there any other potential checks that could be performed to resolve this?

**Comment by davidjgraph** [comment]
The diagram opens correctly for all of us, without being able to recreate there is nothing further we can do.

<img width="1508" alt="Capture d’écran 2024-04-14 à 22 13 27" src="https://github.com/jgraph/drawio-desktop/assets/1761087/db247d9b-6a02-4f73-b495-c618069e0afb">
