### ISSUE TITLE
Mojave is not supported in versions >=22.1.15

### ISSUE THREAD

**Issue by chris-sophos** [jgraph/drawio-desktop#1640]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
MacOS Mojave (and lower) is not supported in versions >=22.1.15, as the app specifies a minimum version of 10.15.

**To Reproduce**
1. Download draw.io in a version >=22.1.15 OR update from an prior version.
2. Open draw.io
3. See message "You can’t use this version of the application “draw.io.app” with this version of macOS. You have macOS x. The application requires macOS 10.15 or later."

**Expected behavior**
One or more of the following:
- App does not attempt to update to an incompatible version.
- App notifies user about unmaintained version.
- Blog post or release note about dropping support for Mojave or lower.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.15

**Desktop (please complete the following information):**
 - MacOS Mojave

**Additional context**
Last working version I could test was [v22.1.11](https://github.com/jgraph/drawio-desktop/releases/tag/v22.1.11).
To be clear, I'm not asking for later versions to support Mojave, I'm asking for a clear indication of when support will be/was dropped, and the last version that supports it.

**Comment by davidjgraph** [comment]
This is electron behaviour, not specific to draw.io desktop. The electron blog does mention it, https://www.electronjs.org/blog/electron-27-0.

**Comment by chris-sophos** [comment]
Is the electron version bump noted anywhere?

**Comment by davidjgraph** [comment]
No, we'll add the electron version used to the release notes.
