### ISSUE TITLE
Grouping shapes messes up waypoints

### ISSUE THREAD

**Issue by mosiser** [jgraph/drawio-desktop#1646]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Grouping two or more shapes connected with lines changes the position of the waypoints of the lines (lines that are not part of the group, but connect two elements of the group).

**To Reproduce**
1. Create two shapes (e.g. two rectangles)
2. Connect them with a line
3. Add a waypoint to the line (creating an elbow)
4. Select the two shapes (not the line) and group them

**Expected behavior**
The two shapes become a group, and the connected line doesn't move.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.1.5

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
Same behavior with the online version.
If the line is grouped together with the shapes, the problem doesn't occur.

**Comment by davidjgraph** [comment]
Fix in 24.0.4

**Comment by mosiser** [comment]
Thanks.
There is still one behavior, I don't know if it's a wanted or unwanted one.

If I select the two shapes (before grouping them) and move them around, the waypoint (elbow) of the line remain still.
Instead, if I select the group and move it around, the waypoint of the line (not grouped with the shapes) moves together with the group.

Not a real problem, but i think the user expects that the waypoints remain still when he moves objects (or groups).
If the user wanted to move those too, he would probably group the line together with the shapes.
