### ISSUE TITLE
Unable to log in with Google Drive

### ISSUE THREAD

**Issue by greenbueller** [jgraph/drawio-desktop#1648]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

I am trying to log into my google drive account from the website. I am able to successfully have draw.io connect with my google drive account, but after giving it permission I am getting the following error

`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

As well as a Internal server error. I am still able to access the site without this, as I can make a blank document. I cannot, however, view any of my prior documents.

This only happened for a short period of time, but it may happen again.

**To Reproduce**
1. Go to 'https://www.draw.io'
2. Click on 'Open existing diagram'
3. Click on 'Authorize'.
4. Log into google account
5. Click on continue x2
6. See error

**Expected behavior**

I should have been able to see my previous documents after logging in, however it did not work.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.0.1

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...
Windows 10, Firefox version 123.0

**Additional context**

This problem stopped happening in the middle of writing this bug report. I'm unsure if it was on googles end or draw.io's, but it did last through multiple login attempts.

**Comment by davidjgraph** [comment]
This is the draw.io desktop project.
