### ISSUE TITLE
name issue when exporting from command line

### ISSUE THREAD

**Issue by JulienDiTria** [jgraph/drawio-desktop#165]
With version 11.3.0, when exporting a folder or a single file to any format ( png for example ) with the command line, without specifying the name of the output, but only the output folder, the name of each diagram is then "nameOfDiagram.drawio.png" instead of the expected "nameOfDiagram.png".

The command line i use is : 
draw.io -x -f png -o .\ nameOfDiagram.drawio
draw.io -x -f png -o .\ folderPath

Is this a desired feature or not ? 
Would it be possible to revert this as it was correctly done in version 10.7.7?
Would it be possible to have the option to not have the .drawio in the name ?

**Comment by alderg** [comment]
Thanks for the report, the file extension will be replaced with the export format extension in the next release.
