### ISSUE TITLE
Drawio not starting

### ISSUE THREAD

**Issue by jpsdr** [jgraph/drawio-desktop#1654]
Hello.

I've tried with both the installed and no-installer version, but drawio doesn't start, i have the following error message (translated from french) : The entry point of the procedure DiscardVirtualMemory cannot be found in KERNEL32.dll.

Version : draw.io-ia32-23.1.5-windows-32bit-no-installer

OS : Windows 7 x86.

If current version doesn't work anymore with Windows 7, i think you should write a warning. Also, if it's the case, what's the last version working with Windows 7 ?

**Comment by davidjgraph** [comment]
Duplicate https://github.com/jgraph/drawio-desktop/issues/1358

We can't display anything in windows 7, this breaks before we'd be able to.
