### ISSUE TITLE
Error at the time of creating a new diagram

### ISSUE THREAD

**Issue by khhizr007** [jgraph/drawio-desktop#1656]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When creating a new diagram from the file dropdown, we get the following error message 'o.url is not a function'.

**To Reproduce**
1. Go to file
2. Click on new
3. Select any diagram and click on create.

**Expected behavior**
A new diagram should open in a new tab.

**Screenshots**

![Screenshot from 2024-03-08 10-05-05](https://github.com/jgraph/drawio-desktop/assets/162679787/edc07604-4728-4c38-9718-7fbf98f884c9)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.0.2

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
In the developer console I am able to see the error stemming from the dropins.js file.

**Comment by davidjgraph** [comment]
We never realised 24.0.2 as a desktop version.

**Comment by davidjgraph** [comment]
Please open an issue in https://github.com/jgraph/drawio/issues/new?assignees=&labels=&projects=&template=bug_report.md .

Please also include the developer console output.
