### ISSUE TITLE
Dark Mode renders differently between web and desktop app, specifically in filled shapes and their text

### ISSUE THREAD

**Issue by dsorak** [jgraph/drawio-desktop#1659]
See below image, side by side comparison:

![image](https://github.com/jgraph/drawio-desktop/assets/25508845/74239901-e0cd-4490-8374-ad6f6f67c585)

**Comment by dsorak** [comment]
Desktop app is running on Windows, 64bit
Desktop drawio app version is: 24.0.4

**Comment by davidjgraph** [comment]
Make sure the improve constant setting (https://github.com/jgraph/drawio/discussions/3701) is the same on both platforms.
