### ISSUE TITLE
Environment variable that disables auto-update

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio-desktop#166]
For https://github.com/flathub/com.jgraph.drawio.desktop/issues/24

**Comment by x80486** [comment]
...well, you can also check for the presence a `.flatpak-info` file and take an action accordingly. This would work consistently for any other configuration toggle that you might need in the future.

**Comment by ghisvail** [comment]
Possible actions could be to disable the auto-update and instead show a message like "It appears you are running a Flatpak build of drawio-desktop. Please contact the Flathub maintainers to request an update of the software to the latest version available".

**Comment by ashrafteleb** [comment]
DRAWIO_DISABLE_UPDATE environment variable will be available in the next release.

@x80486 What is the exact location of `.flatpak-info` relative to the running app

**Comment by x80486** [comment]
@ashrafteleb, it will be `/.flatpak-info`...and yes, that's not a typo :wink:

**Comment by ashrafteleb** [comment]
Interesting :)
Thanks. It will be available in the next release.

**Comment by KSA001** [comment]
It was said it will be available in the next release... But it is still open unfortunately? :/ Or was it just forgotten to close the issue? Thanks for any update!

**Comment by KSA001** [comment]
Many thanks for the update! Unfortunately, though, my first test (with V.13.3.5) did fail. The update message still appeared.
On the other hand maybe I am not correctly addressing the variable, where is a documentation describing how to do it? (Did search a lot, but did not find a complete description).  Can you give me feedback on that please? Thanks!

This is way I got so far: I set DRAWIO_DISABLE_UPDATE as a system env var to 1. Right or wrong?

![grafik](https://user-images.githubusercontent.com/63714644/87034535-40165400-c1e8-11ea-8bd1-b657fd4f88c0.png)


![grafik](https://user-images.githubusercontent.com/63714644/87034355-fa598b80-c1e7-11ea-8ca1-0b45d2f17736.png)

**Comment by ashrafteleb** [comment]
This environment variable was added such that other forks doesn't update. This is why it is undocumented and only found in the code.

You can set the value to "true" and it should work. Also, did you try "Don't Ask Again" button? Does it have any issues?
Thanks

**Comment by KSA001** [comment]
Many thanks that did help! With DRAWIO_DISABLE_UPDATE="true" it works... :)
