### ISSUE TITLE
add keyboard shortcuts to "Bring forward" and "send backward" 

### ISSUE THREAD

**Issue by lumos0** [jgraph/drawio-desktop#1662]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
add keyboard shortcuts to "Bring forward" and "send backward" 

**Describe the solution you'd like**
add keyboard shortcuts to "Bring forward" and "send backward" 

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
Added in 24.0.8.
