### ISSUE TITLE
drawio prompts on Windows 7 that entry cannot be found

### ISSUE THREAD

**Issue by flyratlove** [jgraph/drawio-desktop#1664]
- draw.io version 24.0.4
 - OS: win7 sp1

**Additional context**
After the installation is complete, when double-clicking to start, it is prompted that the program input point DiscardVirtualMemory cannot be located on the dynamic link library Kernel32.dll

<img width="312" alt="无标题" src="https://github.com/jgraph/drawio-desktop/assets/47129492/95649932-b597-4e06-92cd-8fd1d9d29822">

**Comment by davidjgraph** [comment]
Windows 7 isn't supported. Duplicate #1358
