### ISSUE TITLE
can`t scroll to left/right - horizontal with mx-master 3s

### ISSUE THREAD

**Issue by cracky22** [jgraph/drawio-desktop#1665]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I can't scroll horizontally in drawio with my logitech mx-master 3s (mouse wheel on the side)

**To Reproduce**
1. Go to 'draw.io desktop'
2. Scroll horizontal
3. See error

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.1.5

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by davidjgraph** [comment]
Unfortunately, we don't have a device with a side wheel to test this. I'll leave it open, but it's very unlikely to be looked at.

**Comment by pmankow** [comment]
Please fix. Nobody has a mouse with horizontal scroll? It doesn't have to be the same model to verify if the bug is no model dependent.
