### ISSUE TITLE
Containers do not collapse when clicking their minus sign.

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [jgraph/drawio-desktop#1666]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Containers do not collapse when clicking their minus sign.

**To Reproduce**
1. Drag a container shape from the library onto the canvas.
A minus sign appears in the top left corner.

2. Click the minus sign
Briefly, dots appear on the corners of the container and some controls flicker in the tool- and sidebar. But the container does not collapse and the minus sign doesn't change into a plus sign.

The same happens with shapes that are turned into a container by Grouping the empty container.

**Expected behavior**
The container should change from expanded to collapsed state and the minus sign should to a plus sign to indicate that state. 

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.0.4

**Desktop (please complete the following information):**
 - OS: macos 14.3.1
 - draw.io macos standalone application

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-

**Additional context**

**Comment by KerryDJones** [comment]
I was having a problem getting the container to collapse on the desktop. I tried it from an icognito browser and my container collapsed and opened as expected. I tried it on Chrome without incognito and my container collapsed and opened as expected. Do containers not work in desktop mode?

**Comment by davidjgraph** [comment]
Versions of each?

**Comment by KerryDJones** [comment]
![2024-06-05_14-40-41](https://github.com/jgraph/drawio-desktop/assets/37348051/94cbbf24-6223-4800-84db-9d63920c2d3f)
![2024-06-05_14-48-15](https://github.com/jgraph/drawio-desktop/assets/37348051/4e92bdcc-bd31-47d8-b2da-ef0012d1bb04)
v24.4.14 incognito
V23.4.13 Desktop

**Comment by alderg** [comment]
[This test case](https://app.diagrams.net/#RlZPJTsMwEEC%2FJkekxq5Kc63ZLgiJSiBOyMRDbPASHIek%2FXqmxNkoleASzbzZPEsSykx77Xkpb50AnZCFaBN6kRCSrQl%2BD2DXgfVq2YHCK9GhdARbtYcIF5HWSkA1cwzO6aDKOcydtZCHGePeu2bu9ur0vGrJCzgC25zrY%2FqoRJCxC3I%2B8htQhewrp6ussxjeO8dOKsmFayaIXiaUeedCJ5mWgT7Mrp9LF3d1wjo8zIMNfwnYs4q9tM%2Fa%2BHf2ltV3T%2BTDnKVxG59c17HjB%2FBB4QCQMmcDVxZ87CDs%2BrFUjTKaW9Q2jVQBtiXPD6YGjwCZDEajlqIY82NSaE%2B%2BPB3mgXcEzkDwO3SJAZTGEcYbyqLajAshi8jkZBkD5PEIiiH1UO0ej4bbAvv6T7l0%2BUs5%2BqMa1wG85QE2rraimi4HhUmjI%2FpeWa%2BOp9G5j%2F8XvfwC#%7B%22pageId%22%3A%22FknE6mW1S3GNZ7STA6yV%22%7D) works for me in desktop v23.4.13 on macOS.
