### ISSUE TITLE
ctrl c, ctrl v to paste something and old object is still on top making drag harder

### ISSUE THREAD

**Issue by erictioh** [jgraph/drawio-desktop#1667]
### Preflight Checklist

* [ y] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [y ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I oftenly quickly cloning an object using CTRL+c then CTRL+v, however after the clone, 2nd object appeared, but the first object is still on top and when i drag it away 90% of chances i will be dragging the original object or worse creating a line of the first object (not the 2nd object that i have just cloned).

**To Reproduce**
See my video it tells everything. 

**Expected behavior**
So the use case is to quickly clone an object and drag that object away to the desired location, however the has got a bug which the old object keep going on top. Expectation is the cloned object should became on top and when i drag it away i'm dragging this cloned object precisely.

**Screenshots**
Video attached. 

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 24.0.4

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Desktop app]

**Comment by davidjgraph** [comment]
Use ctrl+D to clone.
