### ISSUE TITLE
--crop parameter breaks export to pdf when there are clear pages

### ISSUE THREAD

**Issue by Korstek** [jgraph/drawio-desktop#1669]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
In the command line --crop parameter breaks export to pdf when one of the pages is empty - this behaviour is understandable, but maybe add some kind of warning? Because I had to debug it myself by deleting page by page until I found this empty one was causing an issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new file
2. Save it as test.drawio (without any shapes or objects inserted or with few filled pages, but also with at least one empty)
3. Open the terminal in the file location
4. Run `draw.io --crop --export --format pdf --output all.pdf test.drawio`
5. Program returns "Error: Export failed: test.drawio"

**Expected behavior**
The best way would be to skip empty pages or export them in standard size (for example A4).
A simple warning would also be plenty enough.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.0.4

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by davidjgraph** [comment]
Please re-test with 24.4.13.

**Comment by Korstek** [comment]
> Please re-test with 24.4.13.

Indeed, now it performs as expected. Although before I added a new argument (--all-pages), I had a little stroke because I thought my scripts stopped working 😅 . Thanks!
