### ISSUE TITLE
unable to download stand alone apps, getting TLS handshake timeout for 2 strait days

### ISSUE THREAD

**Issue by moliad** [jgraph/drawio-desktop#167]
sorry for using this channel to report this problem, but I've been unable to download the Windows binaries after a forced update from the desktop version.

I get a timeout on all links redirected to the S3 AWS bin server while its doing its https TLS handshake.  

I got the problem on Chrome and Firefox and from 3 different physically different networks.  I have not had this problem on any other site visited link ever.  Maybe there is a typo in the link or the server itself isn't responding.

**Comment by davidjgraph** [comment]
It's the correct place to report issues, but the releases only exist on Github, we don't have mirrors.
