### ISSUE TITLE
The text is out of shape area

### ISSUE THREAD

**Issue by RNSS** [jgraph/drawio-desktop#1670]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The text is outside of shape area

**To Reproduce**
1. insert any shape not in square format
2. write any text fulling the shape

**Expected behavior**
A text be inside the shape

**Screenshots**
<img width="186" alt="Screenshot 2024-03-23 at 9 11 02 PM" src="https://github.com/jgraph/drawio-desktop/assets/40342056/cabbf3a6-f81f-4a80-9a95-948e6d11fb44">

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 24.0.4

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**

**Comment by davidjgraph** [comment]
You can use line feeds. We've gotten away with this for 13 years, I think we'll manage another 10.
