### ISSUE TITLE
Diagram visuals

### ISSUE THREAD

**Issue by RNSS** [jgraph/drawio-desktop#1671]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
- The text is very close to borders
- Ability to change default font
- Ability to change default shape borders thickness 

**Describe the solution you'd like**
- Add more space in all directions
- Ability to change default font
- Ability to change default shape borders thickness 

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
This is too vague and contains multiple issues. I can convert this is to a discussion, but it's zero use to anyone in it's current form.
