### ISSUE TITLE
The error message is not translated when opening a recent file fails

### ISSUE THREAD

**Issue by FarSeeing** [jgraph/drawio-desktop#1676]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The error message is not translated when opening a recent file fails

**To Reproduce**
1. Save a diagram to some file
2. Delete the file
3. Try to open the diagram via the "File - Open Recent" menu item

**Expected behavior**
Error message should be translated

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/559569/c408c5e8-62ea-4235-b49e-ed1000ebf060)
![image](https://github.com/jgraph/drawio-desktop/assets/559569/566a7385-242c-4a9e-a6da-0e5933c17099)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.0.4

**Desktop (please complete the following information):**
Windows 10, happens on Linux as well

**Additional context**

**Comment by davidjgraph** [comment]
It's not our error message, that's a message from the OS.

**Comment by FarSeeing** [comment]
@davidjgraph - well, yes, but wouldn't it make sense to have a consistent (OS-independent) message?
Especially considering that you already [try to handle it](https://github.com/jgraph/drawio/blob/4a108b23430de9f0b366f4006671b3af938d0903/src/main/webapp/js/diagramly/ElectronApp.js#L855)

**Comment by davidjgraph** [comment]
We don't want to start translation of OS messages, it's just too much work.

**Comment by FarSeeing** [comment]
Sorry, it's me again.
I don't even suggest to translate every single message, but
- you already have several tranlsation entries that could be applied (like `cannotOpenFile=Cannot open file`)
- the solution for this particular case is trivial - just change [this line](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/diagramly/ElectronApp.js#L870) from `this.handleError(e)` to `this.handleError(mxResources.get('cannotOpenFile'))`.
