### ISSUE TITLE
Adding contributors to the study not possible

### ISSUE THREAD

**Issue by MartinRmayti90** [jgraph/drawio-desktop#1678]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I am an owner of a drawio study, and I want to give access to contributors and readers, but I got the following error message in the "Right access" tab:
{"error":"ExecutionException/https://as0-72953-api.gke2.ope.gcp.renault.com/architecture-studies/v2/users/929 e=java.lang.NullPointerException: value","status":500} (500)

**To Reproduce**
1. Go to 'Renault Studies'
2. Click on 'Edit a study'
3. See error

**Expected behavior**
By clicking on this button, I have usually the list of different users owners, contributors and readers. Now, these lists are empty, I can't show the user that have access.

**Screenshots**
![Drawio_error](https://github.com/jgraph/drawio-desktop/assets/165291967/f1574dfc-98f3-41a4-9ac6-8d5ecbf3f374)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 1.6.2

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by davidjgraph** [comment]
This isn't our software.
