### ISSUE TITLE
Grid is not shown in PDF

### ISSUE THREAD

**Issue by megamilg** [jgraph/drawio-desktop#1679]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I use File>Export As>PDF, and check the 'Grid' option, the grid is not included in the output file.

**To Reproduce**
1. Open the desktop version of draw.io
2. Click on 'Create New Diagram'
3. Click on 'Create' to start with the default blank diagram
4. Click on File>Export As>PDF, and check the 'Grid' option
5. Click on 'Export'
6. Click on 'Save'

**Expected behavior**
I would expect the grid to be visible in the output PDF file.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.0.1 on desktop

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
This functionality used to work correctly for me in a previous version of draw.io, but I don't recall the version number.

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
Thanks for the report
