### ISSUE TITLE
VSSX is not importing on Desktop draw.io version

### ISSUE THREAD

**Issue by RISTO10** [jgraph/drawio-desktop#168]
Hi,

I can´t to import a vssx stencil file to use with desktop draw.io, but is not running, the app can´t import the stencil.

However, the same stencil, vss & vssx, is running ok on the web draw.io version.

previously, i convert the original vss to vssx with VISIO.

12.1.0 draw.io Version

BR,

**Comment by RISTO10** [comment]
These are the vssx that not running.

[01_VSSX.zip](https://github.com/jgraph/drawio-desktop/files/3754142/01_VSSX.zip)

**Comment by RISTO10** [comment]
In 12.2.2 the issue, persists.

**Comment by davidjgraph** [comment]
We never said it was fixed, you don't need to test anything until we change the status.

**Comment by RISTO10** [comment]
OK, thanks for the answer. I comment this because i don´t have any answer still.

Thanks!!! I'll be attentive if you comment that.

**Comment by likaozheng** [comment]
Same situation, on MacOS.

**Comment by davidjgraph** [comment]
@likaozheng if you have a specific failure case, please including the vssx.

**Comment by ashrafteleb** [comment]
Some VSSX files contain graphics in EMF format and currently it can only be converted using the online version of draw.io since the desktop version works offline

**Comment by davidjgraph** [comment]
If there's a case without EMF images of vssx not converting, please attach.

The workaround for stencils that include EMF images is to use the online version. Yes, the EMF images have to be sent to our servers. No, we don't store or see your diagram under save/load using the online version.
