### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by Rock3Yu** [jgraph/drawio-desktop#1681]
Please add multi-language supports for the macOS desktop version. Thanks a lot!

E.g. Chinese

**Comment by alderg** [comment]
Try Extras, Language:

<img width="534" alt="Screenshot 2024-03-31 at 15 59 41" src="https://github.com/jgraph/drawio-desktop/assets/921200/2f49e9ad-9f75-4c71-9f83-2db94548834e">
