### ISSUE TITLE
Selection could be improved, when a background shape is locked

### ISSUE THREAD

**Issue by miracuruzrh** [jgraph/drawio-desktop#1684]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When a shape is used as a background to visually group other shapes, then the selection of the shapes which are in the foreground is a bit tricky. When the I want to select multiple objects which are in the area of the greater shape in the background, then the background shape is draged around.

**Describe the solution you'd like**
Maybe this could be considered as an improvement.
When the background shape is free to move (not locked), then the behavior should be the same as it is now.
But when the background shape is locked (ctrl + L), then the selection could be made already startable within the background shape.
Because the background shape is locked anyway. Otherwise the selection must be started outside the background shape everytime.

This is not a problem, as long as the background shape is relatively small. But when it becomes bigger, the user has to zoom more often, to be able to start the selection outside the shape.

**Describe alternatives you've considered**
Currently no idea of an alternative. I think there can't be much done otherwise.

**Additional context**
Here an example. To be able to select the four circles, the selection has to be started currently everytime outside of the purple box.
It would be comfortable, to start the selection box within the purple box, when the purple box is locked.

![image](https://github.com/jgraph/drawio-desktop/assets/44341190/a9f0dc8b-33df-4cfb-8656-19276d7ee73a)

**Comment by davidjgraph** [comment]
Any improvement in 24.2.3?

**Comment by miracuruzrh** [comment]
> Any improvement in 24.2.3?

Hi, first of all, Please excuse my very late reply. I just stumbled over my own post again. I'm now at version v24.7.17 on Windows. It works perfectly. Very much comfortable. Have many thanks for your work.
