### ISSUE TITLE
Add list of recent diagrams to the start window for less clicks 

### ISSUE THREAD

**Issue by dmitriyteteruk** [jgraph/drawio-desktop#1687]
* [yes] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [yes] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Every time I open Draw.io Desktop to work with recent diagram I need to click first on 1) "Create New Diagram" button then 2) double click on empty diagram and then 3) File-> 4) Open Recent -> 5) Choose file name. So, I need to make four clicks every time. At same time "Open Existing Diagram" button is not convenient because I need to search a diagram for particular project in different folders.

**Describe the solution you'd like**
Adding list of Recent Diagrams to start window will reduce number of clicks/actions from five to one and this may save a lot of time for all drawers. See attached screenshot with offered idea.
![image](https://github.com/jgraph/drawio-desktop/assets/34028526/896024fe-7954-4f2f-bac0-0adaae524c74)

**Describe alternatives you've considered**
Currently there is an option to open recent diagrams using Right Click on Draw.io symbol linked to taskbar, but it's not convenient. 

**Additional context**

**Comment by davidjgraph** [comment]
Untick "show splash screen" in extras.

Select from file->open recent. 2 clicks.
