### ISSUE TITLE
Error when downloading exported data

### ISSUE THREAD

**Issue by FarSeeing** [jgraph/drawio-desktop#1688]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
An attempt to download the exported data results in the error shown (file not saved)

**To Reproduce**
1. Create/open a diagram
2. Right-click on any element and select "Edit Data"
3. Click "Export" button
4. Click "Download" button
5. Select any folder/file
6. See the error shown

**Expected behavior**

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/559569/71a042f4-7a80-447a-8337-c91f0b91d72b)
![image](https://github.com/jgraph/drawio-desktop/assets/559569/20ab9786-ed6e-4862-b6f4-5ad040ee9d53)
![image](https://github.com/jgraph/drawio-desktop/assets/559569/87d70f85-ffbc-4811-bd7c-ee3fcd6d339a)
![image](https://github.com/jgraph/drawio-desktop/assets/559569/97979cbb-fcf8-444a-be68-cf693311cf7b)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.0.4

**Desktop (please complete the following information):**
 - OS: any

**Additional context**

**Comment by davidjgraph** [comment]
Fix in [24.2.5](https://github.com/jgraph/drawio-desktop/releases/tag/v24.2.5).
