### ISSUE TITLE
Bug with named Data Container in C4

### ISSUE THREAD

**Issue by JiGaNn** [jgraph/drawio-desktop#1691]
I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I have bug in C4. When I used container for description of storage than I couldn't set my c4Name. At the name of block uses field c4Type. Why?

**To Reproduce**
1. Go to C4
2. Click on Data Container
3. Set c4Name

![image](https://github.com/jgraph/drawio-desktop/assets/88924377/df773b25-5e84-41ef-bbaa-34d73d806277)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.1.0

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by davidjgraph** [comment]
This is fixed in the core, you'll see the fix on the next desktop release.
