### ISSUE TITLE
Preview or Quick look for drawio on macos

### ISSUE THREAD

**Issue by trotyoung** [jgraph/drawio-desktop#1697]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the solution you'd like**
It would be very helpful if user can use quick look function to preview drawio files in macos system.

**Additional context**
Files such as docx and xlsx can be previewed without opening them by simply pressing the space key, which is a useful feature.

**Comment by davidjgraph** [comment]
Duplicate #331
