### ISSUE TITLE
Desktop: Draw.io opens on removed monitor and can't be accessed

### ISSUE THREAD

**Issue by kiu** [jgraph/drawio-desktop#1699]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Draw.io remembers the last location it has been used on the desktop. If the location no longer exists (2nd monitor is removed) it will still open where the 2nd monitor used to be, making it unreachable. There seems to be no windows mechanism to force an app to go back to a visible portion of the desktop.

config.json:
```
{
	"lastWinSize": "974,1087,4393,0,false,false",
	"dontCheckUpdates": true
}
```

Fixed for me by editing the 4393 in the config.json but for the layman impossible to solve.

**To Reproduce**
1. Connect two monitors on a Windows 11 machine
2. Extend your desktop to the additional monitor
3. Use the draw.io desktop client on the second monitor and close it
4. Disconnect the second monitor
5. Anytime you open draw.io it is placed on a non-existent monitor and can't be accessed

**Expected behavior**
Draw.io figures out that the monitor doesnt exist anymore or that the current desktop resolution would put the app outside the desktop, both leading to that draw.io is visible.

**Screenshots**
Could post a screen recording if this helps.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Draw.io: v23.0.2

**Comment by mtnholt** [comment]
Just experienced the same bug. Found this issue, and tried the fix @kiu described, and it worked fine.

**Comment by m-mohamedin** [comment]
The bug will be fixed in the next release
Thanks for the report

**Comment by davidjgraph** [comment]
12.4.0
