### ISSUE TITLE
Support Flatpak

### ISSUE THREAD

**Issue by nielsdg** [jgraph/drawio-desktop#17]
[Flatpak] is a new way of easily distributing executables on Linux. Having support for it would be great, and would allow for example Draw.io to show up in the list of apps on [Flathub].

[Flatpak]: https://flatpak.org/
[Flathub]: https://flathub.org/

**Comment by nielsdg** [comment]
I don't mind taking a look into this  sometime, but atm I'm a bit busy.

**Comment by ghisvail** [comment]
See https://github.com/flathub/flathub/pull/358

**Comment by davidjgraph** [comment]
https://flathub.org/apps/details/com.jgraph.drawio.desktop

**Comment by 4jNsY6fCVqZv** [comment]
Good afternoon, since Flathub is unfortunately not a FLOSS solution yet, but I only use 100% FLOSS, my question is whether you can publish a self-signed .flatpakref in your repository as well? https://github.com/jgraph/drawio-desktop/releases

**Comment by ghisvail** [comment]
> since Flathub is unfortunately not a FLOSS solution yet
>
How so?

**Comment by 4jNsY6fCVqZv** [comment]
You can find more information about the discussion here:
https://github.com/flathub/flathub/issues/691
So my request is about an Flatpak alternative in addition to Flathub. At least for the transition until Flathub also works for users like me.
I know it is extra work, and I would be very grateful to see a solution!

**Comment by septatrix** [comment]
Flathub itself is FOSS, only some software hosten on there is not. If you do not want to use Flathub you can also just download the manifest file and build the flatpack youself.
