### ISSUE TITLE
drawio GUI app writing to parent process console causes distorted view there

### ISSUE THREAD

**Issue by tbali0524** [jgraph/drawio-desktop#1700]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
This is not really a bug, but a behaviour that is a bit annoying, so I just kindly ask to check if anything can be done on drawio side. (I understand if you decide not to).
The problem comes from the fact that even if drawio is a GUI app, it writes output to the parent process's console that started it. 
That causes problem when I open it just by clicking on a local .drawio file in a Far Manager, which is a file manager with both UI and console.  After closing the drawio app, the Far manager panel becomes distorted and needs manual reset. 
I opened ticket at Far manager github, here is their explanation of the problem:
https://github.com/FarGroup/FarManager/issues/495#issuecomment-987448110

**To Reproduce**
1. Use Far manager
2. Open drawio app pressing enter on any local .drawio file (file extension associations take effect)
3. Close the drawio app
4. the Far Manager panel gets distorted by drawio console output

**Expected behavior**
Drawio GUI app does not write to parent process console, especially when there were NO errors.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v24.2.5

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
N/A

**Comment by m-mohamedin** [comment]
We've increased the logging level to error only. It will be available in the next release
Thanks for the report

**Comment by phiway** [comment]
hey can you please help i need to M1 project on c# the project is between student  and tutor booking system where  admin make booking for a student and  where one and only student can make one or many booking and   one or many  booking can have one tutor schedule and  each student can taught by many tutors  each student can also go through individual assessment to check a progress where grades are stored and each student can do many subject please help me to construct analyses diagrams and ERD diagrams   include make payment usecase

**Comment by phiway** [comment]
hey can you please help i need to M1 project on c# the project is between student and tutor booking system where admin make booking for a student and where one and only student can make one or many booking and one or many booking can have one tutor schedule and each student can taught by many tutors each student can also go through individual assessment to check a progress where grades are stored and each student can do many subject please help me to construct analyses diagrams and ERD diagrams include make payment usecase
