### ISSUE TITLE
Error loading file Not a diagram file data missing

### ISSUE THREAD

**Issue by mini-dota** [jgraph/drawio-desktop#1701]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Error loading file Not a diagram file (error on line 540 at column 11257 : AttValue : ' expected)

**To Reproduce**
1. Opening the file

**Expected behavior**
Opened file.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version v22.1.21

**Desktop (please complete the following information):**
 - OS: Windows
![obraz_2024-04-19_131657958](https://github.com/jgraph/drawio-desktop/assets/105448809/24f683b2-0d71-472f-ab89-7579d9065147)

**Additional context**
Trying to open my file and I can't. I opened it in text editior and fixed the problem but a lot data are lost.

[MD.zip](https://github.com/jgraph/drawio-desktop/files/15039507/MD.zip)

**Comment by davidjgraph** [comment]
Attach the file, zipped.

**Comment by mini-dota** [comment]
[MD.zip](https://github.com/jgraph/drawio-desktop/files/15039499/MD.zip)

**Comment by davidjgraph** [comment]
Is this saved to a locally sync'ed OneDrive folder? 

[MD.drawio.zip](https://github.com/jgraph/drawio-desktop/files/15177105/MD.drawio.zip)

**Comment by mini-dota** [comment]
Yes

**Comment by davidjgraph** [comment]
OK, we're looking into a warning not to use a locally sync'ed OneDrive folder. https://github.com/jgraph/drawio-desktop/discussions/1706
