### ISSUE TITLE
Allow to use export advanced with selection only

### ISSUE THREAD

**Issue by BoKKeR** [jgraph/drawio-desktop#1703]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
The default export for PDF and PNG supports exporting only the selection. The problem is that I would like to adjust the size of the export, since the PDF gets broken into many smaller pdf-s when exported at 100%. This can only be done in the advanced export. Which does not support exporting selection only
![image](https://github.com/jgraph/drawio-desktop/assets/2664857/05448641-9d69-45f6-a7be-30ee96707c2c)
![image](https://github.com/jgraph/drawio-desktop/assets/2664857/63c6ba58-f67c-47cf-8f7a-59f405ebeeb8)

**Describe the solution you'd like**
I would like to have the option to export only selection from the advanced page

**Describe alternatives you've considered**
An alternative is copying all the content to a new page and exporting that with advanced.

**Additional context**
I tried this only on desktop draw.io!

**Comment by davidjgraph** [comment]
The advanced section has been removed.
