### ISSUE TITLE
in last release where is drawio-x86_64-24.2.5.deb

### ISSUE THREAD

**Issue by lorens-osman-dev** [jgraph/drawio-desktop#1708]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
in release page there is no drawio-x86_64-24.2.5.deb package there is only arm64 ones but i tested the [drawio-amd64-24.2.5.deb](https://github.com/jgraph/drawio-desktop/releases/download/v24.2.5/drawio-amd64-24.2.5.deb)  with size 91.7 MB and worked will on my machine i think there is a wrong naming there.

**Describe the solution you'd like**
just rename [drawio-amd64-24.2.5.deb 91.7MB ] to [drawio-x86_64-24.2.5.deb]

**Comment by m-mohamedin** [comment]
https://github.com/electron-userland/electron-builder/issues/8197

**Comment by m-mohamedin** [comment]
Hi,

When was the last time the file named x86_64. I've check our releases up to 2017 and all are named amd64

We got this reply from electron builder team:
"What version was this previously working on? I can try git diff-ing when time allows me to return to this project"

**Comment by lorens-osman-dev** [comment]
Upon further reflection, I realized that I confused the terms arm64 and amd64 in my request. I mistakenly suggested renaming the drawio-amd64-24.2.5.deb package to drawio-x86_64-24.2.5.deb, not recognizing at the time that both terms refer to the same architecture and that the naming was indeed correct.

I understand that maintaining a project on GitHub involves dealing with a myriad of details and that clarity in communication is paramount. My intention was to contribute positively to the project, and I regret any confusion my error may have caused.
