### ISSUE TITLE
Failed to execute 'btoa' on 'Window when trying to import svg file

### ISSUE THREAD

**Issue by mapl** [jgraph/drawio-desktop#171]
I am getting the below error message when trying to import a certain svg file.

"Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range."

I have enable the dev tools using NODE_ENV=development, but no error message appears in the dev console track the issue down.

What is the best way to troubleshoot this error which exact character(s) causing this?

**Comment by mapl** [comment]
I think I have found the non-latin character. However now, nothing happens when trying to import the corrected svg file. No error message in the gui or dev tools at all.

**Comment by mapl** [comment]
some more progress. I have substituted german umlauts (ä,ö,ü) with a test ascii char.

Now draw.io imports the svg file but converts it automatically to an image.  
"data:image/png;base64,iV...."

What is the explanation for that?

**Comment by alderg** [comment]
Could you attach the SVG file please?

**Comment by mapl** [comment]
not applicable anymore.
