### ISSUE TITLE
Stuck in full screen after closing flatpak while in full screen

### ISSUE THREAD

**Issue by clezag** [jgraph/drawio-desktop#1711]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Flatpak on Linux (Fedora 39 and 40 Wayland GNOME):  
If the app is closed while in full screen mode, it remains locked in full screen mode without any option to change it across successive restarts

Reinstalling the app or manually setting the last boolean of `lastWinSize` in `config.json` to `false` fixes it

**To Reproduce**
1. View -> Fullscreen
2. File -> Exit
3. Start app again
4. View -> Fullscreen

**Expected behavior**
The `Fullscreen` option should have a checkmark when starting in full screen mode, and it should toggle to non-fullscreen when pressed.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.2.5

**Desktop (please complete the following information):**
 - OS: Fedora Workstation GNOME 40 (also pre upgrade on 39)

**Comment by m-mohamedin** [comment]
The Fullscreen menu option will be fixed in the next release.
Thanks for the report
