### ISSUE TITLE
Not a diagram file error 

### ISSUE THREAD

**Issue by 3insysPhillip** [jgraph/drawio-desktop#1714]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...

**Additional context**

**Comment by 3insysPhillip** [comment]
Hello, 

I am having some of the previously observed bugs when using different Cloud Services and such. I am using Google Drive in order to collaborate on some diagrams with a few people but I recently have had more and more issues with a rather large file. I am now at the point where it will not open, error: "Not a diagram file (error on line 654 at column 1: Extra content at the end of the document)". If I open the file in Notepad++ I am seeing that there does seem to be some junk values being appended, incorrect tags, duplicate tags, words, etc. (values seem to be random after different attempts to open always resulting in error). I will be attaching screenshots of what I can. I am totally fine reverting to an older version or losing a lot of the content on the file, as I was leaving previous work for reference and notes. Would really appreciate help as I just need ACCESS to a portion of the work I had on the file at this point. Please and thank you!

- Phillip 
![draw notepadpp error](https://github.com/jgraph/drawio-desktop/assets/168670303/636003f7-1460-49ec-bace-21b9c4a2ad6b)
![draw error](https://github.com/jgraph/drawio-desktop/assets/168670303/3355ee7f-c84a-4d50-922a-c6dc43a4016e)
[Postman Process UI & Flowchart TXT.txt](https://github.com/jgraph/drawio-desktop/files/15179675/Postman.Process.UI.Flowchart.TXT.txt)

**Comment by davidjgraph** [comment]
[Postman.Process.UI.Flowchart.txt](https://github.com/jgraph/drawio-desktop/files/15179785/Postman.Process.UI.Flowchart.txt)

There's junk at the end of the original file.

<img width="362" alt="Capture d’écran 2024-05-01 à 19 10 07" src="https://github.com/jgraph/drawio-desktop/assets/1761087/228b97d0-6087-4c5d-9f2d-745643db6c30">
