### ISSUE TITLE
Conversion of Valves in a Visio Piping and Instrumentation Diagram is incomplete

### ISSUE THREAD

**Issue by ber999** [jgraph/drawio-desktop#1716]
Conversion of Valves in a Visio Piping and Instrumentation Diagram is incomplete.

Convert a Visio Ping and Instrumentation Diagram.
Please support upload of *.drawio and *.vsdx files.

**Comment by ber999** [comment]
Please support upload of *.drawio and *.vsdx files, so that I can provide all the details neccessary in Github.
Image of the Visio file is as follows:
![image](https://github.com/jgraph/drawio-desktop/assets/24701537/0bcdf0cc-818f-446a-928d-a5aa9275314c)

**Comment by ber999** [comment]
[proceng.zip](https://github.com/jgraph/drawio-desktop/files/15258797/proceng.zip)
Please find conversion result drawio file attached in the zip file above.

**Comment by staroverworld** [comment]
成云


-------- 原始邮件 --------
发件人： ber999 ***@***.***>
日期： 2024年5月9日周四 15:04
收件人： jgraph/drawio-desktop ***@***.***>
抄送： Subscribed ***@***.***>
主 题： Re: [jgraph/drawio-desktop] Conversion of Valves in a Visio Piping and Instrumentation Diagram is incomplete (Issue #1716)

proceng.zip<https://github.com/jgraph/drawio-desktop/files/15258797/proceng.zip>
Please find conversion result drawio file attached in the zip file above.
