### ISSUE TITLE
[MacOS] Zoom In/Out Keyboard Shortcuts not work.

### ISSUE THREAD

**Issue by datgausaigon** [jgraph/drawio-desktop#1721]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Hi, Zoom In/Out Keyboard Shortcuts not work on MacOS.
In MacOS, Zoom In/Out Keyboard Shortcuts draw.io is [command] + [+] and [command] + [-]. But they don't work.
I got issue in draw.io desktop app for MacOS latest version.
Please fix, Thanks ❤️

**Comment by davidjgraph** [comment]
Duplicate https://github.com/jgraph/drawio/discussions/4159
