### ISSUE TITLE
Export as last time

### ISSUE THREAD

**Issue by liuzikai** [jgraph/drawio-desktop#1724]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I use draw.io to draw diagram and export PDFs to be used in LaTeX. It works well except I need to go through the export dialog (and the macOS file selection dialog, which is _buggy_) every time I make a change, before I can see how it appears in LaTeX. 

**Describe the solution you'd like**
I would like to have a "export as last time" function, preferably with a shortcut. There can be a pop-up warning about overwriting the file, but still it would be faster.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Yes, the buggy macOS file selection dialog makes things worse... Sometimes the save button is unclickable until I restart draw.io. It's a system-wide bug.

And thanks again for making this amazing tool!

--Zikai

**Comment by alderg** [comment]
What version are you using?

**Comment by liuzikai** [comment]
> What version are you using?

v24.4.0

**Comment by alderg** [comment]
The PDF dialog should remember all settings used in the last export in v24.4.0. The system dialog to select the file is needed to get permission to write to the filesystem and is provided by the operating system. Unfortunately, we have no control over this dialog.
