### ISSUE TITLE
Background saving

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio-desktop#173]
Can we avoid locking the UI when saving?

Will there be issues with the unsaved flag if it can change while a save is in progress?

Need to push back the autosave timer if a save is in progress when it fires.

**Comment by davidjgraph** [comment]
Testing 12.4.2 shows none of these issues. If you experience them on our official release, please provide details.

**Comment by myloginid** [comment]
On 13.0.3 version, the UI lock for almost 3 minutes on every change. The file size is 4MB


![image](https://user-images.githubusercontent.com/2422057/82979716-57bfc180-a01a-11ea-9c69-a49e3828755a.png)

**Comment by davidjgraph** [comment]
Are you able to share the file? Which OS?

**Comment by myloginid** [comment]
MacOS Catalina. Sorry cannot share the file.
