### ISSUE TITLE
Custom paper size units always imperial

### ISSUE THREAD

**Issue by tomikaa87** [jgraph/drawio-desktop#1731]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Custom paper size units are always imperial and don't respect the application language, the diagram's unit configuration or the regional settings of the OS.

**To Reproduce**
1. Change the units to "metric" in the OS's regional settings
2. Change the application language to a metric country's (e.g. Hungarian)
3. Quit draw.io 
4. Start draw.io
1. Go to File > Page setup
6. Select "Custom"
7. Custom paper size units are still imperial

**Expected behavior**
Custom paper size units are metric when the diagram's units are set to metric, or the application language set to one of the metric countries (e.g. Hungarian), or the regional settings of the OS set up as such.

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/15613825/96ef9b61-fadf-4c5b-aeb5-153b269ac9a5)  
![image](https://github.com/jgraph/drawio-desktop/assets/15613825/86921427-3f92-402b-b8fd-07ac7a2c2f2b)  
![image](https://github.com/jgraph/drawio-desktop/assets/15613825/06832012-5327-4c15-90da-ed088e8d895f)  

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.4.0

**Desktop (please complete the following information):**
 - Operating System: Kubuntu 22.04
- KDE Plasma Version: 5.27.11
- KDE Frameworks Version: 5.104.0
- Qt Version: 5.15.3
- Kernel Version: 5.15.0-107-generic (64-bit)
- Graphics Platform: X11

**Additional context**
None.

**Comment by davidjgraph** [comment]
Fix in 24.4.6.
