### ISSUE TITLE
Disable Auto Update Check startup

### ISSUE THREAD

**Issue by pieewiee** [jgraph/drawio-desktop#1734]
**Is your feature request related to a problem? Please describe.**
we would like to rollout draw.IO in our environment and don't want to users to see that there is a new version available. This would limit the support requests.

**Describe the solution you'd like**
Disable the Update for a new version check on startup. This setting need to be defined on a machine level.

- a registry key in HKLM
- a config file in the installation dir
- a startup option drawio.exe --noupdatecheck

![Unbenannt](https://github.com/jgraph/drawio-desktop/assets/8495504/6d622af6-259f-48be-9a7a-97c6615a51d5)

**Comment by m-mohamedin** [comment]
This can be achieved via an environment variable
DRAWIO_DISABLE_UPDATE=true

**Comment by davidjgraph** [comment]
24.5.1 adds the startup parameter --disable-update.

**Comment by KRread** [comment]
Thanks David for the update. The startup parameter does work in v24.5.1+ . Do you have any recommendation/leads on how this startup parameter can be defaulted in the package for macos or something similar to environment variables in windows that can be used for mac users ?  thanks

**Comment by davidjgraph** [comment]
https://www.google.com/search?client=firefox-b-d&q=setting+environment+variables+macos

https://www.google.com/search?q=how+to+start+app+on+macos+with+parameters

**Comment by guillaume-mueller** [comment]
I use version 26.0.9. What means this message ?

```bash
$ drawio  --disable-update
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
```

**Comment by vitlav** [comment]
It doesn't work as for me on Linux, nor --disable-update, nor DRAWIO_DISABLE_UPDATE=true
