### ISSUE TITLE
Start screen is shown for secondary windows even if disabled

### ISSUE THREAD

**Issue by lvmm** [jgraph/drawio-desktop#1738]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Start Screen is disabled (Extras-Show Start Screen is unchecked). This works when the draw.io is started but when another window is opened Start Screen still pops up.

**To Reproduce**
prerequisites: Extras-Show Start Screen is disabled

* start draw.io - no start screen
* press ^N or file-new - new window opens and shows the start screen

**Expected behavior**
There should've been no start screen after ^N - just a new blank window.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.4.0

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by m-mohamedin** [comment]
Thanks for the report. It will be fixed in the next release.

**Comment by davidjgraph** [comment]
24.5.3
