### ISSUE TITLE
Update Azure Icons

### ISSUE THREAD

**Issue by VeitSanner** [jgraph/drawio-desktop#174]
The currently included icons for Microsoft Azure are a few years old and do not match the icons used on the Azure website. Microsoft regularly updates the Azure Icon library. The most current version is available on [Microsoft Azure Cloud and AI Symbol / Icon Set - SVG](https://www.microsoft.com/en-us/download/details.aspx?id=41937).

Would it be possible to update the included Azure library with this new set?

**Comment by alderg** [comment]
Broken link. Is the icon set still available for download?

**Comment by kutya** [comment]
You can find a superset of the Azure stencils here:
https://github.com/jgraph/drawio-libs/tree/master/libs/integration

We will update it with the latest stencils.

**Comment by kutya** [comment]
Added a couple stencils to the Azure group
