### ISSUE TITLE
try to save and this error appears: "EBADF: bad file descriptor, write"...what to do?

### ISSUE THREAD

**Issue by dudumello** [jgraph/drawio-desktop#1743]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...

**Additional context**

**Comment by davidjgraph** [comment]
Could you attach a zipped copy of the file please?

If you haven't saved one, go to extras->edit diagram and copy the contents of the main area, paste that into a text editor and try to save.

**Comment by davidjgraph** [comment]
Maybe also try the solution suggested in https://forum.obsidian.md/t/cannot-resolve-error-failed-to-save-file-filepath-ebadf-bad-file-descriptor-write-make-a-backup/60017.

**Comment by dudumello** [comment]
I noticed that I can save the file in the desktop area but whenever I try to save it in my documents folder that error appears :/
