### ISSUE TITLE
Config option to allow zoom with mouse wheel without keyboard

### ISSUE THREAD

**Issue by Imerion** [jgraph/drawio-desktop#175]
I use drawio for all sorts of work and it works great! Most other programs in my workflow: image editors, 3D editing software, game development tools, vector graphic editors, etc either has zooming with the mouse wheel as default or an option to toggle it. This method works very well for me as I use middle-click to pan around and move up down and mouse wheel and pointer to pinpoint a certain area and zoom in on to work on detail and then zoom out to quickly see the whole picture again. Drawio is one of the few apps that doesn't support this, so therefore I am kindly requesting an option for this. Thanks!

**Comment by alderg** [comment]
Try Alt+Mousewheel (Option+Mousewheel on a Mac).

**Comment by Imerion** [comment]
Thanks, I know that is an option. But it is not as smooth, practical and friction-free as having it set as default (as an option). Especially considering that is not how it works in all the other programs (which makes it harder to transition from one program to the next.)

**Comment by davidjgraph** [comment]
Diagramming software is a specific domain of apps, is it the standard in diagramming software?

**Comment by Imerion** [comment]
It might be standard, or at least common. I suggest the default behavior should be Alt + Zoom and an option for using Zoom as default without any key combo instead.

**Comment by davidjgraph** [comment]
We'd need specific evidence it's a standard for diagramming software.

**Comment by DavidHJong** [comment]
Is there an option to zoom in/out with only scrolling the mouse wheel now?

**Comment by Cazman80** [comment]
Yes can we please have this implemented as an option?
I come from a CAD background, and the CAD programs use the middle mouse wheel to zoom by default.
I see middle mouse button pans by default, which is great, but this with zoom without having to press a key makes it really fast to move around large complex pages to specific details.
Thank you

**Comment by alderg** [comment]
Thanks for the report, the next release will support the zoomWheel option. See https://www.diagrams.net/doc/faq/configure-diagram-editor

**Comment by spacetaxi2100** [comment]
I am using the desktop version 20.8.16 and I tried to change configuration of mouse wheel behavior to 
  "zoomWheel": true
...but it did not have any effect. After restart I still have to press the ctrl-key to zoom by mouse wheel.
Did I apply the configuration correctly?
Thank you

**Comment by alderg** [comment]
This works for me:
<img width="215" alt="Screenshot 2023-05-11 at 08 22 07" src="https://github.com/jgraph/drawio-desktop/assets/921200/3c95adf4-ccfa-43c6-870e-f5f5e7fbec90">

**Comment by spacetaxi2100** [comment]
Thanks a lot! That helped and works for me as well.

The reason it did not work before was, I have mistakenly tried to append the configuration string directly to the complete "settings" list (which is accessed by pressing the settings button).

**Comment by robocat-studios** [comment]
> The reason it did not work before was, I have mistakenly tried to append the configuration string directly to the complete "settings" list (which is accessed by pressing the settings button).

I made the same mistake. Thanks for the help alderg!

**Comment by Arkemlar** [comment]
Looks like with this option, touchbar while dragging not working as scroll and works as zoom too. Any solutions?

**Comment by alderg** [comment]
> Looks like with this option, touchbar while dragging not working as scroll and works as zoom too. Any solutions?

Unfortunately, there is no way in JavaScript to distinguish the two events.
