### ISSUE TITLE
Release v24.4.6 and above kills all default shadow opacity

### ISSUE THREAD

**Issue by felixhix** [jgraph/drawio-desktop#1750]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Opening existing drawio files with the new release v24.4.6 and above will modify all "default" shadows from 25% to 100% in the whole file. The modification is permanent (opening the file with older releases will result in shadow of 100% on all elements). 

**To Reproduce**
1. Create a new file with older release
2. Place box in the diagram
3. Enable shadow (should be 25% by default)
4. Save file and open it with newer release (v24.4.6/*.7)
5. Box shadow opacity is set to 100% (see screenshots below)

**Expected behavior**
No modification on existing elements (should be left by 25%)

**Screenshots**
_v24.4.0 vs v24.4.6 and v24.4.7_
![drawio-issue-shadowopacity-example-v24 4 6](https://github.com/jgraph/drawio-desktop/assets/8451980/f6f477a9-d5ec-4436-af03-11677d9c2365)
![drawio-issue-shadowopacity-example-v24 4 0](https://github.com/jgraph/drawio-desktop/assets/8451980/098b273c-39b2-4c12-876a-75ca74c21aef)
![drawio-issue-shadowopacity-v24 4 0](https://github.com/jgraph/drawio-desktop/assets/8451980/d68e6472-b7a4-4a8f-b04e-6b9009885791)
![drawio-issue-shadowopacity-v24 4 6](https://github.com/jgraph/drawio-desktop/assets/8451980/a8f85644-2b65-4710-8c0e-1c5bbb64639d)

**draw.io version (In the Help->About menu of the draw.io editor):**
v24.4.6 and v24.4.7

**Desktop (please complete the following information):**
 - Desktop / MacOS

**Comment by davidjgraph** [comment]
Fix in 24.4.8, thanks for report.
