### ISSUE TITLE
Not a diagram file error

### ISSUE THREAD

**Issue by CarlosRega** [jgraph/drawio-desktop#1752]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
After accepting an automatic upgrade prompt this morning my file saved yesterday fails to open with a Not a diagram file error

**To Reproduce**
1. Go to File -> Open
2. Select the file attached
3. The following error shows:
![image](https://github.com/jgraph/drawio-desktop/assets/170741864/82a5e71e-e95a-470a-8e20-fe1d69af23d9)

**Expected behavior**
This file was opening fine until the upgrade this morning

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.4.8

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
N/A
[IsoTestsFlow.zip](https://github.com/jgraph/drawio-desktop/files/15436067/IsoTestsFlow.zip)

**Comment by davidjgraph** [comment]
Open the file in a text editor and delete the first diagram element:

`  <diagram id="C5RBs43oDa-KdzZeNtuy" name="Start Up Cycle" />`

then save and load it. You saved the file with 24.4.6, which had this issue. 24.4.8 has it fixed.

**Comment by CarlosRega** [comment]
Thank you for the really fast response and solution. And thank you too for this great software.
