### ISSUE TITLE
Make auto grouping optional by setting

### ISSUE THREAD

**Issue by LinguaOccultus** [jgraph/drawio-desktop#1755]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Partly. I very often accidently group elements even though not intended when placing them over each other or just close to each other. This happens much more often as intended as I manually group where wanted. Thus, overriding it temporarily is extremely annoying as I have to do this all the time. And with less complex drawings it makes no sense to use layers to fix this.

**Describe the solution you'd like**
I would like an option to simply say which behaviour is the default one: auto-grouping or not. So, everyone can set it for his use case as desired.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by alderg** [comment]
Try uncheck Drop Target:
<img width="237" alt="Screenshot 2024-05-27 at 10 27 23" src="https://github.com/jgraph/drawio-desktop/assets/921200/a147ae5a-545a-4b17-898f-2f2f530998f6">

**Comment by LinguaOccultus** [comment]
-

**Comment by alderg** [comment]
The search field on top of the library should stay hidden. How are you hiding it?

**Comment by LinguaOccultus** [comment]
-

**Comment by alejandroarevalo** [comment]
I think the feature to disable this behaviour should be added in the core project https://github.com/jgraph/drawio , it is indeed annoying that components get grouped when it is not intended. I work mostly with drafting AWS architectures in the browser based draw.io, and it is quite troublesome when elements get grouped by placing them "inside" the container, sometimes restricting their placement or even their selection.

**Comment by jeroenhabets** [comment]
TBH this is currently my major gripe with draw.io 😱. If only you could turn this off... Too bad I only stumbled upon this issue after it was closed by @davidjgraph
