### ISSUE TITLE
Request - Rearrange diagram when containers collapsed / expanded

### ISSUE THREAD

**Issue by annaghi** [jgraph/drawio-desktop#176]
This software is beautiful, thank you very much for making it free and open-source.

I would like to model our system according to [C4 model](https://c4model.com) with draw.io with heavy usage of containers. The model quickly grows, and when collapsing all containers it becomes sparse, and the arrows with waypoints are stucked.

This is how it looks like:

![draw-io 2019-11-02 09-44](https://user-images.githubusercontent.com/8246853/68068653-4bf76f80-fd57-11e9-8d03-ebe0298c0f5b.gif)

And if you do not mind I am linking another tool's example to show you what I am asking for:
https://gojs.net/latest/samples/grouping.html

**Comment by tkisch** [comment]
I'm struggeling with a similar problem. Is there a feature in planning? Or did somebody find a workaround?
