### ISSUE TITLE
Draw.io does not start on Ubuntu (installed via snap)

### ISSUE THREAD

**Issue by mydeveloperplanet** [jgraph/drawio-desktop#1760]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Try to start draw.io on Ubuntu 22.04.4 LTS. Draw.io is installed via snap. 

**To Reproduce**
1. Go to 'Applications'
2. Click on 'draw.io'
3. draw.io does not start.
4. Start a terminal and type `drawio`, the following error is shown.
```shell
A JavaScript error occurred in the main process
Uncaught Exception:
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at new SystemError (node:internal/errors:259:5)
    at new NodeError (node:internal/errors:370:7)
    at Object.userInfo (node:os:365:11)
    at file:///snap/drawio/214/resources/app.asar/node_modules/atomically/dist/constants.js:10:29
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async node:electron/js2c/browser_init:2:125628
    at async loadESM (node:internal/process/esm_loader:28:7)
```

**Expected behavior**
Draw.io starts successful

**Screenshots**
N/A

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version , I guess the latest snap version, but I cannot verify this

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**

**Comment by davidjgraph** [comment]
https://stackoverflow.com/questions/61961485/a-system-error-occurred-uv-os-get-passwd-returned-enoent-no-such-file-or-direc

Is it a docker image?

**Comment by mydeveloperplanet** [comment]
No, I have installed it a long time ago via snap on Ubuntu, and now it suddenly fails

**Comment by davidjgraph** [comment]
The error is an operating system error. What did you determine from googling the error?

**Comment by mydeveloperplanet** [comment]
Nothing unfortunately

**Comment by davidjgraph** [comment]
OK, but I'm afraid we don't have the resources to research this in-depth, as it's specific to your machine, rather than a general draw.io issue.

**Comment by kitos9112** [comment]
We're also encountering this issue on Ubuntu22 boxes where drawio is installed using snap

**Comment by mydeveloperplanet** [comment]
This is not an issue with drawio, rather with snap. I raised an issue at snap: https://github.com/canonical/snapcraft.io/issues/4662 
Also, a workaround is added in that issue.
