### ISSUE TITLE
Cannot Set Background Color in Hex Mode by Pasting Hex Code via Ctrl+V

### ISSUE THREAD

**Issue by achieve-dream1221** [jgraph/drawio-desktop#1762]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/jgraph/drawio-desktop/assets/57209087/223c4367-0cd8-457e-b42a-aa08b1fb3c16)

**Comment by davidjgraph** [comment]
That doesn't look like our software. You haven't provided any environment details or versions.

**Comment by alderg** [comment]
<img width="247" alt="Screenshot 2024-05-31 at 10 47 28" src="https://github.com/jgraph/drawio-desktop/assets/921200/d6448f5a-4cc0-4bba-a39b-dfc8e06f0cfe">

Try click the color box instead of the dropper icon and paste in that dialog.
