### ISSUE TITLE
MacOS zooming shortcut not working

### ISSUE THREAD

**Issue by qq253498229** [jgraph/drawio-desktop#1765]
I am using the drawio desktop client on the macOS operating system. 

Currently, the default zoom in and zoom out shortcuts Command+/- are not working; only option+MouseWheel is work.

Since I am using Apple's official mouse and keyboard, using option+MouseWheel for zooming is very sensitive and difficult to control. 

If Command+/- worked, it would greatly improve my use experience.

**Comment by davidjgraph** [comment]
Duplicate #978
