### ISSUE TITLE
File open failure, "not a diagram file"

### ISSUE THREAD

**Issue by ozzynotwood** [jgraph/drawio-desktop#1769]
![2024-06-04   -   19-06-10](https://github.com/jgraph/drawio-desktop/assets/48989097/53df502a-3c66-48d8-9e18-72737a23b486)

When opening a file, error shows: 
Not a diagram file (error on line 211 at column 1: Premature end of data in tag mxCell line 208)

**To Reproduce**
Open file directly in the desktop app OR by file association. 

**Expected behavior**
File to open.

**draw.io version (In the Help->About menu of the draw.io editor):**
24.4.13

**Desktop (please complete the following information):**
Windoes, Desktop version of Drawio

**Additional context**
My drawio project saved normally. When I try to open the file the next day, I get the error stated above. I looked at the source code of the saved file & found the last 4 lines were missing:

![2024-06-04   -   19-08-36](https://github.com/jgraph/drawio-desktop/assets/48989097/6b1fc8a7-110f-4505-8203-5d6d3e71cf7a)

I noticed this because I compared to a different file. When adding this lines in manually, the saved file was able to open. As I was able to open my document, make edits & save Monday then have the error appear on Tuesday I thinking there is a fault in the save process. I don't know if this is connected, but this happened around the same time I imported 2 PNG images to my project.

I would like a fix for this bug however look at the look it seems there have been file open issues for years. Can we at least have a method for recovering projects?

**Comment by davidjgraph** [comment]
Is your save folder a OneDrive sync folder?

**Comment by ozzynotwood** [comment]
> Is your save folder a OneDrive sync folder?

No, this was on a flash drive.

**Comment by davidjgraph** [comment]
The latest desktop version has some functionality to improve loading of corrupted files. But overall, I'd avoid the use of a flash drive in this way. Saving from electron doesn't seem fully robust over less conventional media.
