### ISSUE TITLE
12.1.7 not working on macOS Catalina 10.15.1, showing dev tools with errors when loading

### ISSUE THREAD

**Issue by dadvir** [jgraph/drawio-desktop#177]
Please see attached image. There some js files not loading.
I used the installer (dmg file) downloaded from here https://github.com/jgraph/drawio-desktop/releases
<img width="1440" alt="draw_io_error_macos" src="https://user-images.githubusercontent.com/1744024/68069980-933e2a00-fd70-11e9-90d4-459c9f808db9.png">

**Comment by davidjgraph** [comment]
do you have "NODE_ENV=development" defined on your shell?

**Comment by dadvir** [comment]
Of course.... I’m a developer... may I suggest that in release you’ll ignore this variable (or any other that is special for development mode)?

**Comment by davidjgraph** [comment]
We'll change it to something less likely to clash.

**Comment by dadvir** [comment]
I suggest to use it but set it per the app... when it starts in release mode. Because this is a common variable used probably by libs you use.

**Comment by davidjgraph** [comment]
Fixed in repo, will be available in next release.
