### ISSUE TITLE
Draw Desktop Windows no installer does not keep added Libraries when reopen the app, even Remember this setting checkbox is checked.

### ISSUE THREAD

**Issue by dpapis** [jgraph/drawio-desktop#1773]
Greetings all,
hope does not been reported until now,
 
Draw Desktop Windows no installer, does not keep added libraries from menu--> more shapes libraries when reopen, even Remember this setting checkbox is checked.
If i open the new version 24.5.1 and add the libraries, the next time i open the previous version e.x. 24.4.8 the added libraries are also gone, If i add the libraries in older version e.x. 24.4.8, close and reopen the no installer old version windows desktop app, the libraries are active and there is no need to re-add them.
If i reopen the 24.5.1 the libraries are missing also not only the new one 24.5.1 but also from older versions 24.4.8.
Thanks in advance.

Windows 10 Pro

**Comment by christogav** [comment]
Same problem confirmed on MacOS v24.5.3. Last version it appears to be working in is release v24.4.13.

If it helps, I appeared to observe when I downgraded, the last selected shape libraries that were not reloading in the higher version, reloaded automatically in v24.4.13. I suspect the issue is when loading state, not saving.

**Comment by dpapis** [comment]
Draw Desktop (no installer) do not keep the added libraries from older version (24.4.8) exactly like the 24.5.1 version.
Do i need to open a new issue also?

**Comment by m-mohamedin** [comment]
Hi, is this issue still occurring in the latest version?
Also, is there a reason to use two versions at a time, or the libraries just stopped loading after the upgrade?
Thanks

**Comment by christogav** [comment]
Issue not occurring in latest version.

**Comment by davidjgraph** [comment]
I'll close, if the OP comes back and says it's working, I'll repoen.
