### ISSUE TITLE
Severe lag moving the drawio window

### ISSUE THREAD

**Issue by jeroenvriesman** [jgraph/drawio-desktop#1780]
All drawio versions 22.1.16 and higher show a severe lag when moving the drawio window under Windows.
All versions 22.1.15 and lower don't have this problem.

The effect is the strongest when there are pictures in the drawing, any of the cloud IBM examples will do.
I've attached an example, which is just one of the IBM examples copied 5 times.
[lag_test_drawing.zip](https://github.com/user-attachments/files/15612274/lag_test_drawing.zip)

My laptop is i5-1135G7, 2.4GHz, 8GB windows 10 enterprise 22H2.

Also tested on an i7, same problem. 

On Linux drawio does not have this problem.

Disabling automatic backup doesn't fix the problem.
Maybe the windows related change https://github.com/jgraph/drawio-desktop/1433 introduces the problem.

From previous posts in https://github.com/jgraph/drawio/issues/3636 it's clear that the macOS version doesn't have this problem.

**Comment by davidjgraph** [comment]
We have millions of users on windows, if it were a widespread issue this repo would be underwater. There's something specific to your machine.

Either something like a virus checker that doesn't like a new signature on later releases, or the storage used doesn't like a write or flush change in 22.1.5.

**Comment by davidjgraph** [comment]
We still cannot repeat. I would suggest to find an alternative tool given the problems you're having.

**Comment by jeroenvriesman** [comment]
Update, I found the cause by measuring the cpu/mem/net stats when moving teh drawio window.
In is indeed related to https://github.com/jgraph/drawio-desktop/1433.
drawio is updating the config.json continuously when the window is moving. For a local filesystem or a high performance network this is fine, but when the config.json is on a network with lower throughput and/or higher latency (for example , working over a company vpn ) this causes the severe lag in window operations like moving or resizing.
Possible solutions:
a) a feature to turn off writing the window position to the json.
b) a feature to choose a local location for the config.json (we also have diskless clients, so this doesn't solve all the problems)
c) make the write to the config.json asynchronous so write latency doesn't affect the application

I think option c is the most general solution. Maybe option a is easy to implement, it would just disable 1433 which is not that important.

**Comment by davidjgraph** [comment]
Cool, thanks for taking the time to investigate and report back.

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
Thanks for the report

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio-desktop/commit/fb6a654be457e1af2ddd058bad9e9e1331d8fc4d

**Comment by jeroenvriesman** [comment]
Thanks for the fix Mohamed.
Only writing the window info upon close is a indeed a better idea than my suggestion.

**Comment by davidjgraph** [comment]
Fix in 24.6.1

**Comment by Iorek73** [comment]
Hello, still seeing extreme lag in 24.7.8 desktop windows installer.
i7, 32GB RAM, Diagram has ~50 tables.

**Comment by alderg** [comment]
Are you moving or resizing the window? Is it faster with a blank diagram?
