### ISSUE TITLE
Database of diagrams in other languages

### ISSUE THREAD

**Issue by BenoitSeydoux** [jgraph/drawio-desktop#1782]
Hello,
I would like to know how to obtain the diagram templates in the database in French (or other).
Thanks
![image](https://github.com/jgraph/drawio-desktop/assets/172587257/113bca37-89e1-426c-830f-420c876480eb)

**Comment by davidjgraph** [comment]
On n'a pas traduit du contenu des formes dans les modèles dans d'autres langues.
