### ISSUE TITLE
The selected shape groups are not "remembered"

### ISSUE THREAD

**Issue by akinuri** [jgraph/drawio-desktop#1783]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Recent versions of the desktop app do not remember the selected shape groups in the shapes panel.

**To Reproduce**
1. Launch draw.io desktop app.
2. Notice there are no shape groups in the shapes panel.
3. Click on "+ More Shapes"
4. Select "General", "Basic", "Arrows", "Entity Relation", "UML"
5. Check the "Remember this settings" (it already is)
6. Click "Apply"
7. Notice the selected shape groups appear in the shapes panel.
8. Close the app.
9. Launch agaiin.
10. Shape groups are gone.

**Expected behavior**
I expect the "Remember this settings" option to work and keep the selected shapes.

**Screenshots**
Since there's no error, a screenshot won't help.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.5.3

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2 19045.4529

**Additional context**
I'm not sure when this started, but recent. I suspect that the user settings/preferences are stored somewhere. I want to know and check where they are stored. This might be a permission issue. I want to make sure that the settings are actually stored, and can be read later.

Also, the scratchpad seems to work just fine.

**Comment by davidjgraph** [comment]
Which file from the releases section did you install?

**Comment by akinuri** [comment]
I'm not sure. I installed few months ago, and auto-updated since then.

Also, I didn't test reinstalling. While it might help, I'll do that as a last resort.

**Comment by richardwhitehead** [comment]
I am seeing this too, as of the last few days. I am using the desktop version, v24.5.3. I am on Windows 11.

**Comment by akinuri** [comment]
I just uninstalled what I had, and installed [Windows Installer](https://github.com/jgraph/drawio-desktop/releases/download/v24.6.1/draw.io-24.6.1-windows-installer.exe) from [Release 24.6.1 · jgraph-drawio-desktop](https://github.com/jgraph/drawio-desktop/releases/tag/v24.6.1). The issue persist.

**Comment by richardwhitehead** [comment]
This is fixed for me in 24.6.1.

**Comment by akinuri** [comment]
I was kind of annoyed that this was closed without any investigation. Seeing that I won't be getting any help here, I did a reinstall again, and it worked.

However, this time, I had to delete some files manually. The uninstall didn't remove everything. There were still some files in `C:\Users\{user}\AppData\Roaming\draw.io`. Also, just to be sure, I did a clean up with CCleaner after the uninstall (for regkeys, etc.).

**Comment by akinuri** [comment]
Frack. It worked once, and then it just went back to its problematic state.

Upon some experimentation, it seems there's some pattern to this madness.

**The usual/first test:**

1. Launch draw.io
2. Create New Diagram
3. Blank Diagram > Create
4. Shapes are empty
5. \+ More Shapes > ✓ General > Apply
6. General, Misc, and Advanced shape groups are visible
7. Close app
8. Launch again
9. Create New Diagram
10. Blank Diagram > Create
11. **Shape groups are gone**
12. Close app

**The weird/working case:**

1. Launch draw.io
2. Create New Diagram
3. Blank Diagram > Create
4. Shapes are empty
5. + More Shapes > ✓ General > Apply
6. General, Misc, and Advanced shape groups are visible
7. Add Rectangle to page
8. Save to desktop > Untitled Diagram.drawio
9. Close app (while the page is open)
10. Launch again
11. The last page is reopened as a new page (title is Untitle Diagram)
12. **Shape groups are visible**
13. Close app > Discard Changes
14. Launch draw.io
15. Create New Diagram
16. Blank Diagram > Create
17. **Shape groups are gone**

**The working case again:**

1. Launch draw.io
2. Create New Diagram
3. Blank Diagram > Create
4. Shapes are empty
5. Add Rectangle to page
6. Save to desktop > Untitled Diagram.drawio
7. Close app (while the page is open)
8. Launch again
9. The last page is reopened as a new page (title is Untitle Diagram)
10. **Shape groups are visible** (although I didn't select any in previous attempt)
11. Close app > Discard Changes

### Takeaways

- Adding a shape to the page before saving to file seems necessary. Saving the empty page doesn't work.
- The `Discard Changes` (or starting from scratch) seems to be the cause.
- When the saved file on the desktop is opened, the previously selected shape groups are visible.
- There's clearly a problem here.

**Comment by akinuri** [comment]
This seems to be solved in the recent [24.6.4](https://github.com/jgraph/drawio-desktop/releases/tag/v24.6.4) release.
