### ISSUE TITLE
I have verified that after version 23.1.5, every time I export a PDF from drawio, opening the PDF afterwards is very slow.

### ISSUE THREAD

**Issue by LeeSyan** [jgraph/drawio-desktop#1784]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I have verified that after version 23.1.5, every time I export a PDF from drawio, opening the PDF afterwards is very slow.

**To Reproduce**
1. Install all versions of drawio after 23.1.5 on Windows
2. Create a file in drawio and export it to a PDF document
3. Open the PDF document and browse it. The PDF document is very laggy

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
All versions after 23.1.5

**Desktop (please complete the following information):**
 - OS: Windows
**Additional context**

**Comment by LeeSyan** [comment]
Version 23.1.5 is normal, all versions after 23.1.5 have problems

**Comment by alderg** [comment]
Please attach the PDF before and after v23.1.5. What PDF viewer did you use?

**Comment by LeeSyan** [comment]
> Please attach the PDF before and after v23.1.5. What PDF viewer did you use?
PDF viewer:    Adobe Acrobat DC

**Comment by LeeSyan** [comment]
> Please attach the PDF before and after v23.1.5. What PDF viewer did you use?

![drawio to pdf](https://github.com/jgraph/drawio-desktop/assets/102131227/e00c9576-3cb5-43e8-8e32-dba289953aa3)
[20240520（23.1.5 to pdf）.pdf](https://github.com/user-attachments/files/15900350/20240520.23.1.5.to.pdf.pdf)
[20240520（24.5.3 to pdf）.pdf](https://github.com/user-attachments/files/15900529/20240520.24.5.3.to.pdf.pdf)

**Comment by LeeSyan** [comment]
If necessary, I can give you the original document. However, GitHub does not support uploading documents in drawio format.

**Comment by LeeSyan** [comment]
[20240520（24.5.3 to pdf）.pdf](https://github.com/user-attachments/files/15900414/20240520.24.5.3.to.pdf.pdf)

**Comment by LeeSyan** [comment]
> Please attach the PDF before and after v23.1.5. What PDF viewer did you use?

This is the original document, you need to change pdf to drawio
[20240520.pdf](https://github.com/user-attachments/files/15900601/20240520.pdf)

**Comment by LeeSyan** [comment]
Version 24.5.3 also has the following issues:
1. Document shortcut icons cannot be displayed
2. Drawio shortcut icons are not displayed on the computer desktop
![The 24 5 3 version cannot display the shortcut icon](https://github.com/jgraph/drawio-desktop/assets/102131227/6cbaed9b-af90-4612-9923-1fee7c896057)
![Version 24 5 3 does not display shortcut icons on the computer desktop](https://github.com/jgraph/drawio-desktop/assets/102131227/3d573675-ca9e-4fd6-91fe-0eb4327191f1)

**Comment by davidjgraph** [comment]
One issue per thread only please.

**Comment by davidjgraph** [comment]
Fix in 24.6.1.

**Comment by LeeSyan** [comment]
24.6.1 did not solve the problem

**Comment by LeeSyan** [comment]
> Fix in 24.6.1.

24.6.1 did not solve the problem
