### ISSUE TITLE
[MacOS] Zoom Out (cmd +) shortcut not work drawio 24.6.1

### ISSUE THREAD

**Issue by datgausaigon** [jgraph/drawio-desktop#1792]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

In new version 24.6.1 drawio (Web & Desktop) has fixed the zoom in/out shortcuts error in MacOS, Thanks ❤️. Related Issues and Discussions:

https://github.com/jgraph/drawio-desktop/issues/978
https://github.com/jgraph/drawio/discussions/4159

### But Zoom Out (cmd and +) shortcut is currently not working.

**To Reproduce**
1. Go to drawio app (Web or Desktop)
2. Create new Diagram
3. Use shortcut to Zoom In (cmd -) -> Work well
4. Use shortcut to Reset View (return button on MacBook) -> Work well
5. Use shortcut to Zoom Out (cmd +) -> Not work

**Expected behavior**

Zoom In, Zoom Out, Reset View shortcuts (cmd -, cmd +, return/enter/home) must work on MacOS

**draw.io version:**

- draw.io version 24.6.1 (Web and Desktop)

**Desktop:**
 - OS: MacOS (14.5)
 - Browser: Safari (17.5)
 - Device: MacBook

Thanks ❤️

**Comment by OliverPearmain** [comment]
Confirmed working in v24.6.4. Thank you @davidjgraph

**Comment by datgausaigon** [comment]
Thank you @davidjgraph ❤️
