### ISSUE TITLE
It is not possible to use <include-shape>

### ISSUE THREAD

**Issue by aleksandarsusnjar** [jgraph/drawio-desktop#1806]
### Discussed in https://github.com/jgraph/drawio-desktop/discussions/1439 and https://github.com/jgraph/drawio/discussions/4517

`<include-shape>` has a passing mention in documentation and can be found in code. However, there are no examples to be found anywhere, either as documentation or as a part of some exiting shape/stencil library. There isn't a reference/list of usable shape names. There isn't even an error stating that whatever is referenced is invalid, it simply doesn't show up.

<div type='discussions-op-text'>

<sup>Originally posted by **LubaaBalakhashvili** August 21, 2023</sup>
I want to create shapes with same base and if I change that base, new shapes to be changed too. In documentation I read about<include-shape> but I can't understand how to use this and can't find anything else about it. How can I use this sub-shapes?

Link of documentation: https://www.drawio.com/doc/faq/shape-complex-create-edit
![image](https://github.com/jgraph/drawio-desktop/assets/102235002/0d24b85f-ae66-426e-936c-fe0d09c66b6a)
</div>

**Comment by davidjgraph** [comment]
This isn't a bug report or a feature request, it should be a discussion.
