### ISSUE TITLE
Change Theme requires screen refresh - but how?

### ISSUE THREAD

**Issue by Treverix** [jgraph/drawio-desktop#181]
Hi,

when we select a different theme we're asked to refresh the page. I tried to refresh with the usual way (CTRL+R or F12 shortcut) which didn't work and I couldn't find a menu action to do such a refresh, neither on the menu, nor on the context menu.

It should be obvious to the user how to proceed when the application requires a user action.

Version: V.12.2.2, windows executable w/o installer

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by lians0** [comment]
I have the same problem as the subject, the version still does not have a clear refresh button.

Version: V.17.2.4, windows executable w/o installer
windows Version: windows 11
