### ISSUE TITLE
Colors (default »white«/»black«) are inverted after export/print (maybe dark theme related) again

### ISSUE THREAD

**Issue by LinguaOccultus** [jgraph/drawio-desktop#1816]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Just wanted to report the return of the old bug that »white« objects are black after export/print, which occured several times before already, in the current version (see below). Which means, that »white« elements (dark theme enabled) are by default using the color »F0F0F0« but are black after export/print. Setting it to pure white like »FFFFFF« (or any other color) works, so this maybe is also again related to the dark them issues from the past. This means, that all elements need to become an explicitely defined custom color even though F0F0F0 (and maybe there is a reason, this is the default color)is visually fine as »white« the same as FFFFFF is. But for just a quick diagram, this is unnecessarily complicated. Same for the default »black«.

**To Reproduce**
1. Place an object with the default colors into the document
2. Eport (for example as PDF) or print the document

**Expected behavior**
Obvious.

**Screenshots**

Document:
![image](https://github.com/user-attachments/assets/6447c6b9-5cc1-4910-9e06-0f82c2a19381)

Result after PDF export:
![image](https://github.com/user-attachments/assets/bae83469-91fc-43f4-92e3-82f9b52a5112)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.6.4

**Desktop (please complete the following information):**
- OS: Windows 11 Pro 23H2

**Additional context**
N/A

**Comment by brightsparkey** [comment]
I can confirm this is an issue.

This can be worked around - after export change theme to light and then back to dark again, and it should sort itself out.

OFC it should be sorted out as its annoying.
