### ISSUE TITLE
Adding freeform tool to top tool bar

### ISSUE THREAD

**Issue by gomarcus** [jgraph/drawio-desktop#1819]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Opening the freeform (pen input) tool is currently buried in the menus. Finding and even opening it is unnecessary complicated.

**Describe the solution you'd like**
Would love for the freeform tool to get added to the top tool bar. Or would love to get a simple method for the user to customize the tools presented in the top tool bar.
![grafik](https://github.com/user-attachments/assets/736bae12-3011-426a-8d68-95a7fe3239e4)

**Comment by alderg** [comment]
Try the simple theme.
<img width="171" alt="Screenshot 2024-07-18 at 16 53 10" src="https://github.com/user-attachments/assets/5c8c1e25-fb77-4863-91e1-fa39cc6b4bc8">

<img width="226" alt="Screenshot 2024-07-18 at 16 53 14" src="https://github.com/user-attachments/assets/fae5efd5-b709-4a11-a03c-b0b9517e9cf5">

**Comment by gomarcus** [comment]
thanks for the suggestion, I actually did manage to find that, but it also removes some other tool icons, and is thus sadly not feasible for my application.

**Comment by gomarcus** [comment]
@davidjgraph may I ask why no new basic frontend features are planned? The ability to customize the tool bar, may be considered quite an essential feature for most users. I would love to help adding such a feature, but I did not yet manage to fully grasp the code base.

**Comment by davidjgraph** [comment]
Because we have to be selective about what we can do with limited resources. We have about 60 million users and one asked for a change. UI changes are a major thing, they cannot be done for single requests.

**Comment by gomarcus** [comment]
Like I stated, this might actually meet the need of more users than just me. Working in a more and more tablet/touch oriented world, navigating through deep nested menus is less optimal.

Speaking about touch and tables, would also love to see Stylus support for automatic freeform tool activation+input and stylus eraser (like MS Surface Pen) detection. May I inquire whether improved touch/stylus support is maybe already planned?

**Comment by davidjgraph** [comment]
I understand the request, but I decide what does and doesn't go into the product based on a number of things. My decision is final once I make it.
