### ISSUE TITLE
Unintuitive behavior handling read-only files

### ISSUE THREAD

**Issue by maxsenft** [jgraph/drawio-desktop#1821]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When a read-only file will be opened by draw.io, the user is not able to click anything on the sheets or even disable/enable layers. This behavior is unintuitive and draw.io only shows a tiny hint "Read only" next to the menu bar:

![image](https://github.com/user-attachments/assets/7cf402af-097b-425d-a33b-699b12457810)

Currently the user needs to save the file using the "Save As..." dialog first and then do any kinds of changes.

**To Reproduce**
1. Set the "read-only flag" for a .drawio file in your file system.
2. Open the file with draw.io
3. Try to click any object or enable/disable a layer using the layer window

**Expected behavior**
Being able to do changes to the drawing even if the file on the filesystem is read-only. In case the user tries to save the file, draw.io should inform that the original file is read-only and the "Save As..." dialog should open.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.6.4

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (22H2)

**Comment by davidjgraph** [comment]
We can make the message bigger, but I don't agree with allowing editing. If do that someone will complain about allowing edits to a read-only file. We don't know if the user is using an OS or device that allows them to save.
