### ISSUE TITLE
Please update Mermaid support to support Math inpout and display

### ISSUE THREAD

**Issue by idealkindom** [jgraph/drawio-desktop#1824]
* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by m-mohamedin** [comment]
A basic experimental support (in Diagram mode only) will be added to the next release
Please note draw.io Mathematical typesettings needs to be enabled also

**Comment by idealkindom** [comment]
Thks a lot for letting me know this good news.

在 2024-08-16 17:41:57，"Mohamed Mohamedin" ***@***.***> 写道：


A basic experimental support (in Diagram mode only) will be added to the next release
Please note draw.io Mathematical typesettings needs to be enabled also
