### ISSUE TITLE
Hiding the search form field is reset when re-opening the application.

### ISSUE THREAD

**Issue by LinguaOccultus** [jgraph/drawio-desktop#1825]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The search field to search forms can be hidden by unchecking »Search forms« in the appropriate menu. However, when you restart Draw.io Desktop, it is visible again. All other user interface elements keep this setting so far.

**To Reproduce**
1. Start Draw.io Desktop
2. Hide the forms search field by unchecking the appropriate menu entry
3. Restart Draw.io Desktop
4. Search field is visible again without changing the setting.

**Expected behavior**
Obvious.

**Screenshots**
N/A

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.5 (and many, MANY major versions back – as long as I use the application, years ...)

**Desktop (please complete the following information):**
- OS: Windows 11 Pro 23H2

**Additional context**
None.

**Comment by m-mohamedin** [comment]
Cannot reproduce. Is this regarding View -> Search Shapes?

**Comment by LinguaOccultus** [comment]
Exactly. There only is one filed to search forms. It always reappears. After updates, after restarting app and so forth. But it does not matter anymore; I am looking for a Draw.io replacement now instead. Too much bugs all the time.
