### ISSUE TITLE
File->Embed -> IFrame... export, All Page flag missing or not works

### ISSUE THREAD

**Issue by seregreV** [jgraph/drawio-desktop#1831]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
File->Embed -> IFrame... export, All Page flag missing or not works

**Screenshots**
![image](https://github.com/user-attachments/assets/41b8cae2-4625-45c0-af2c-9e56f2b92561)
V22.1.16
![image](https://github.com/user-attachments/assets/1b54680d-8c9a-4642-a6ec-b2dfbe16eadf)
V24.7.5

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.5 and 24.7.6

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by m-mohamedin** [comment]
Currently, the IFrame option always include all pages (with an option to select a different page on Open)
