### ISSUE TITLE
yarn.lock problems

### ISSUE THREAD

**Issue by tleepa** [jgraph/drawio-desktop#1832]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I am trying to update [flatpak build](https://github.com/flathub/com.jgraph.drawio.desktop/) and in order to do so, I have to update the `generated-sources.json` using [`flatpak-node-generator`](https://github.com/flatpak/flatpak-builder-tools/tree/master/node).

Usually, it works just fine, but with 24.7.5 [update](https://github.com/jgraph/drawio-desktop/commit/250e02f0e801b411ae6773f7f26f0b75c9531c7d#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de), I am getting error:
```shell
❯ flatpak-node-generator yarn yarn.lock                                                     
Reading packages from lockfiles...
Traceback (most recent call last):
  File "/home/[redacted]/.local/bin/flatpak-node-generator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/[redacted]/.local/pipx/venvs/flatpak-node-generator/lib64/python3.12/site-packages/flatpak_node_generator/main.py", line 277, in main
    asyncio.run(_async_main())
  File "/usr/lib64/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/[redacted]/.local/pipx/venvs/flatpak-node-generator/lib64/python3.12/site-packages/flatpak_node_generator/main.py", line 198, in _async_main
    packages.update(lockfile_provider.process_lockfile(lockfile))
  File "/home/[redacted]/.local/pipx/venvs/flatpak-node-generator/lib64/python3.12/site-packages/flatpak_node_generator/providers/yarn.py", line 107, in process_lockfile
    yield self.process_package(lockfile, name_line, package)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[redacted]/.local/pipx/venvs/flatpak-node-generator/lib64/python3.12/site-packages/flatpak_node_generator/providers/yarn.py", line 92, in process_package
    if self.is_git_version(entry['resolved']):
                           ~~~~~^^^^^^^^^^^^
KeyError: 'resolved'
```

It seems to me (but by all means, I am not a developer, so this is only my best guess), that yarn.lock is missing some data. Few packages do not have `resolved` and `integrity` properties:
- @electron/get@^2.0.0
- @types/http-cache-semantics@*
- @types/responselike@^1.0.0
- @types/yauzl@^2.9.1
- define-properties@^1.1.3
- function-bind@^1.1.1
- get-intrinsic@^1.1.1
- has-property-descriptors@^1.0.0
- has@^1.0.3
- keyv@^4.0.0
- punycode@^2.1.0
- sprintf-js@^1.1.2
- universalify@^2.0.0

Also, URLs point to `registry.npmjs.org` instead of previous `registry.yarnpkg.com`, but I am not sure if this is related.

**To Reproduce**
1. Install flatpak-node-generator
2. Clone drawio-desktop repo
3. Run `flatpak-node-generator yarn yarn.lock`

**Expected behavior**
flatpak-node-generator should produce `generated-sources.json` without any errors.

**Screenshots**
N/A

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.5

**Desktop (please complete the following information):**
 - OS: Linux Fedora 40

**Additional context**
N/A

**Comment by davidjgraph** [comment]
Does https://github.com/jgraph/drawio-desktop/commit/5bdfb0936b1eff9c4c3cd76ddfc86b36eb9aee49 fix that for you?

**Comment by tleepa** [comment]
Yes, running my command on `dev` branch is working fine.

**Comment by tleepa** [comment]
Can I ask, when this would be merged to release branch?

**Comment by tleepa** [comment]
Please, note that the problem is back after commit https://github.com/jgraph/drawio-desktop/commit/3ac88c4fef7d893654ce1ae0ec15b401bcf20df3 - would be great if this could be fixed before merging with release branch.

@m-mohamedin maybe you could look at this, since the problem occurred after your updates to yarn.lock?
