### ISSUE TITLE
Cannot Delete Scratchpad Items once added

### ISSUE THREAD

**Issue by Jaxon-Claw** [jgraph/drawio-desktop#1833]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Cannot delete items from the Scratchpad once they are added.

**To Reproduce**
1. Go to 'Scratchpad' toolbar
2. Click on 'Edit' icon, dialog appears (see attached screenshot)
3. Attempted to delete an item (the middle green circle with the x) by clicking on the X above the item in the upper right corner just above the item.
4. Item gets deleted (as expected) from the dialog box
5. Click Save (to save changes)
4. Error Saving File - Not a diagram file

**Expected behavior**
Expected the dialog box to close, effectively saving the scratchpad edits that were made.

**Screenshots**
![image](https://github.com/user-attachments/assets/4ac4457d-3870-4cbc-8177-7438d54dd95b)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.5

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Additional context**
None

**Comment by m-mohamedin** [comment]
Thanks for the report, it will be fixed in the next release

**Comment by davidjgraph** [comment]
In 24.7.8

**Comment by Jaxon-Claw** [comment]
Thanks for addressing this issue. This is a remarkable piece of software, and quite impressive. 🥇
