### ISSUE TITLE
The color picker in APP cannot pick colors outside the APP page, but the one in web can pick color outside web page.

### ISSUE THREAD

**Issue by Windrain7** [jgraph/drawio-desktop#1842]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The color picker in APP cannot pick colors outside the APP page.

**To Reproduce**
1. Create a shape and change its line or background color
2. In the color palette, click on the pipette
3. Move the color picker outside APP page.
Problem: The color picker changes to the mouse and cannot pick colors.

**Expected behavior**
The color picker can pick colors outside APP page.

**Screenshots**
![image](https://github.com/user-attachments/assets/b2540a19-6e35-4232-ae65-d4de808a3388)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.5

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
The color picker in web can pick colors outside the web page. Just like below:
![image](https://github.com/user-attachments/assets/2e1d0438-4a5f-44d3-98ec-eb5bd10c958a)

**Comment by davidjgraph** [comment]
That's an expected limitation, there's nothing we can do about that.
