### ISSUE TITLE
On the Raspberry Pi 5, it doesn't work properly.

### ISSUE THREAD

**Issue by editfund-founder** [jgraph/drawio-desktop#1843]
OS = `2024-07-04-raspios-bookworm-arm64.img.xz`

![Screenshot_20240826-122735.png](https://github.com/user-attachments/assets/f3cdb27f-3329-410a-b4e6-7aeeb07a68bc)

**Comment by davidjgraph** [comment]
"It doesn't work"

https://www.danclarke.com/it-doesnt-work

**Comment by editfund-founder** [comment]
![Screenshot_20240826-122735.png](https://github.com/user-attachments/assets/df67324e-3226-4778-b3f2-ea6e39563d55)

**Comment by editfund-founder** [comment]
Solved,adjust the screen resolution.
