### ISSUE TITLE
DrawIO v19 to v24 loses Win10/Win11 Jump List

### ISSUE THREAD

**Issue by zipacna** [jgraph/drawio-desktop#1844]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
    * only found (with cleared isopen, isissue) one issue "jump list" which only mentioned the word "jumping" not the win10 jump list.

**Describe the bug** / **To Reproduce**
After upgrading from an old DrawIO Version (v19) to the most recent (v24) I noticed the Jump List under Win10 is no longer filed with the recently open files. The Upgrade cleared the Taskbar Icon, but did not reattach a new one, after manually reattaching it, opening a file from the "File -> Recently opened" Menu within DrawIO, saving it, shutdown for the day and starting Win10 again, the Jump List did not reappear.

**Expected behavior**
The Jump List should recreate itself (or at least start to populate itself again) after saving a DrawIO file again.

**Screenshots**
![2024-08-24_DrawIO-no-more-Win10-JumpList-even-after-redowngrade](https://github.com/user-attachments/assets/7c0823e5-613d-4ab2-8394-2415fc308a76)
![2024-08-24_JumpList-Example-RecentlyUsed-NotepadPlusPlus](https://github.com/user-attachments/assets/cc550b20-5e28-4845-977c-9edc0bcb28ba)

**draw.io version (In the Help->About menu of the draw.io editor):**

- Upgraded from draw.io version 19 (exact minor version no longer known) to v24.7.5, retested with downgrade from 24.7.5 to 19.0.3

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 22H2 (19045)

**Additional context**
After searching the internet and my registry for a bit, some Registry Entries I found:
- Some Binary Registry Entries. Is it a Entry from DrawIO or Windows? `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\RecentDocs\.drawio`
- [StackExchange about Jump List Sizes](https://superuser.com/questions/1035179/how-do-i-increase-the-number-of-items-on-a-jump-list-in-windows-10)

**Comment by davidjgraph** [comment]
Windows 10 is coming to end of life. We're not going to fix win 10 related issues at this point if they are minor, like this one. If it repeats in win 11, we can consider the issue.

**Comment by zipacna** [comment]
Reproduced under Windows 11 (work laptop), had an even older DrawIO Version (v15.2.7) upgraded to v24.7.5 Jump List stays empty.

Before upgrade
![2024-08-26_DrawIO-pre-Upgrade](https://github.com/user-attachments/assets/809dab13-542c-4f0e-a0ed-80c072f614ec)

after upgrade and reattaching to taskbar
![2024-08-26_DrawIO-post-Upgrade-JumpList-Empty](https://github.com/user-attachments/assets/3da11223-7192-4969-9c83-e7720cc6864d)

Using the menu (after closing the popup "create new or open existing") still lists the recent files. Maybe add the 3-10 most recent to the popup (for Quick Access).
![image](https://github.com/user-attachments/assets/24433069-c439-4f08-8b63-a3370918be44)

![image](https://github.com/user-attachments/assets/711e4b89-e888-4072-955c-dee896e2d172)

**Comment by zipacna** [comment]
Could be Windows behaviour, but only Files (newly created after changing a Version) seem to show up.
![image](https://github.com/user-attachments/assets/ebbbbe6f-5154-4c17-a8bc-a5e204b4e564)

**Comment by m-mohamedin** [comment]
We couldn't reproduce. Also, this list is handled by Windows
