### ISSUE TITLE
Hosted app has plantuml support but not the downloadable app

### ISSUE THREAD

**Issue by bdutta** [jgraph/drawio-desktop#1848]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The hosted online app does seem to have a mechanism to import PlantUML text description to generated artefacts, just like it does for mermaid, but the downloadable offline app doesn't seem to support PlantUML but only mermaid.

**To Reproduce**
1. Go to "https://app.diagrams.net/"
2. Click on '+' icon, then on 'Advanced', then on 'PlantUML...' indicating one can add PlantUML text description to generate PlantUML graphical artefacts
3. However, if I download the offline app from "https://get.diagrams.net/", install it on my Windows10 Enterprise Edition PC, and start the app, I don't see similar behaviour
4. Click on '+' icon, then on 'Advanced', then we see 'mermaid' option but not 'PlantUML'

**Expected behavior**
Expect to see PlantUML option in offline downloaded app too

**Screenshots**

![image](https://github.com/user-attachments/assets/7c3a58ea-0118-4e85-bb63-b5b3215f913b)

- draw.io v24.7.5 (offline app)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64bit) Enterprise Edition

**Additional context**

**Comment by davidjgraph** [comment]
"I have searched the issue tracker for a feature request that matches the one I want to file, without success."

That doesn't mean tick it and don't actually search.

https://github.com/jgraph/drawio-desktop/issues?q=plantuml+

**Comment by bdutta** [comment]
Please note that the screenshot attached is that of the online hosted app, not of the offline app. The offline app is simply missing the 'PlantUML...' option.

**Comment by davidjgraph** [comment]
fair enough.

**Comment by davidjgraph** [comment]
Adds client-side PlantUML parser in 30.3.6.
