### ISSUE TITLE
Outputting with LaTeX TikZ code format

### ISSUE THREAD

**Issue by goodgoodcat** [jgraph/drawio-desktop#1851]
Could you please add a feature for outputting in LaTeX TikZ code format?
It would be fantastic if that could be achieved! 
I want to insert some reference articles in the graph but the pdf format draw.io outputs cannot adjust the refs no. while the order change, at the same time ,drawings are all code-based, making it hard for me to adjust the positions of the graphs as a beginner.
I prefer use UI for creating graphs

**Comment by davidjgraph** [comment]
No, that's too much work. You need to find something that converts from one of our output formats to the format you want.
