### ISSUE TITLE
When I click the line connector, the position of the text on the line and the line shape always change.

### ISSUE THREAD

**Issue by zhufeizzz** [jgraph/drawio-desktop#1854]
### Preflight Checklist

* [yes] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [yes] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When I click the line connector, the position of the text on the line and the line shape always change.

**To Reproduce**
1. Try to click the text on the line connector. (I just want to select the line connect)
2. Text position changes everytime.
3. And the shape of line connector also changes.

**Expected behavior**
Never change shape or position when I first click on line connector.

**Screenshots**
![image](https://github.com/user-attachments/assets/b9b28de4-ddf3-422d-82c0-af3a8a511106)

**draw.io version (In the Help->About menu of the draw.io editor): 24.7.8

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...

**Additional context**

**Comment by zhufeizzz** [comment]
Can anyone fix this issue?

**Comment by zhufeizzz** [comment]
This issue seriously affects daily use and always leads to misoperations. Can it be resolved?

**Comment by alderg** [comment]
We're unable to reproduce this issue.

**Comment by zhufeizzz** [comment]
@alderg @davidjgraph  
Here's the problem reproduction screen recording using the latest version(v26.0.2) of https://app.diagrams.net/.

![动画](https://github.com/user-attachments/assets/2465ec16-e1b0-4953-ad9d-8298e861a2ca)

**Comment by alderg** [comment]
What browser, operating system and versions and are you using a mouse, touch screen or a pen?

**Comment by zhufeizzz** [comment]
Browser：Edge 131.0.2903.99
OS：Windows 11 Professional 23H2
Operation method：Mouse

**Comment by alderg** [comment]
Are you also getting this in incognito mode, ie. with all browser extensions disabled?

**Comment by zhufeizzz** [comment]
I tried using incognito mode and disabled all browser extensions, cleared the browser cache, and tested it on another Windows PC and mouse. The issue can still be reproduced. 
Additionally, there are no JavaScript errors or network loading errors in the browser console.

**Comment by alderg** [comment]
We're still unable to reproduce this. If you are technical you could set a breakpoint in mxEdgeSegmentHandler.prototype.start on line 1847 in app.min.js and check why this is called from mxEdgeHandler.mouseMove without checking `this.graph.tolerance` (default value 4), which is the minimum amount of pixels before we start moving anything on the edge after a mouseDown event). Since we're unable to reproduce this, that's all I can say.

<img width="615" alt="Screenshot 2024-12-30 at 08 14 07" src="https://github.com/user-attachments/assets/9563120d-b78e-47c3-bc08-c0fdd1f03231" />

**Comment by zhufeizzz** [comment]
I am not very skilled in JS. From the screenshot, can you identify any information?
![image](https://github.com/user-attachments/assets/e0246871-d49a-479f-8d27-0ef923d43979)

**Comment by alderg** [comment]
Unfortunately not, and this is the wrong function. You want to look for `mxEdgeHandler.prototype.mouseMove`.
