### ISSUE TITLE
windows 32 bit installation fails

### ISSUE THREAD

**Issue by SteveLWC** [jgraph/drawio-desktop#1858]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

Installing different versions of draw.io on my old windows 32 bit laptop I found that at a certain point some versions will open, while others will not. The most recent version ~26 gives an error saying to choose the correct version for the computer, while older versions give an error when opening draw.io from the installer of something not working with the dynamic linking library - imaged attached below. This happens with some versions down to 21.5.1. However, version 20.8.10 does install, open, and seems to work correctly.

**To Reproduce**
1. Attempt to install draw.io-ia32-21.5.1-windows-32bit-installer and newer, except the newest versions 26 or so.
2. Once installed, ask it to open draw.io from the installer.
3. See error
4. Also, attempting to run draw.io fails.

**Expected behavior**
I expect the newest version to install on this machine using the 32 bit installer the same as version 20.8.10.

**Screenshots**
![draw io_installation_error_v_21 5 1](https://github.com/user-attachments/assets/1a9e6864-a99b-454e-baed-6d4beeb42e55)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: Windows 32 bit

**Additional context**

**Comment by davidjgraph** [comment]
32 bit windows isn't supported any longer. I would stick to the working version.
