### ISSUE TITLE
Баги в draw.io 24.7.8: невозможность изменения шрифта и перенос слов

### ISSUE THREAD

**Issue by viacheslaw-design** [jgraph/drawio-desktop#1859]
“Здравствуйте! Я использую draw.io версии 24.7.8 на Windows 11 Pro и столкнулся с двумя проблемами: не могу изменить шрифт внутри фигуры и не работает перенос слов. Можете ли вы помочь решить эти проблемы?”

**Comment by alderg** [comment]
Make sure these two are checked:

<img width="243" alt="Screenshot 2024-09-04 at 09 12 06" src="https://github.com/user-attachments/assets/ae7d011e-a68a-4204-9dc4-68d93c696de3">

**Comment by viacheslaw-design** [comment]
Обновил Windows 11 Pro, затем переустановил draw.io версии 24.7.8, все заработало!!!  Спасибо за одну из самых лучших программ.
