### ISSUE TITLE
Unable to install in 32-Bit Windows

### ISSUE THREAD

**Issue by mdkaleel** [jgraph/drawio-desktop#186]
Hi,

Unable to install in 32-Bit Windows.

Thanks,
Kaleel

**Comment by davidjgraph** [comment]
There isn't a 32 bit windows.

**Comment by rawbone62** [comment]
@davidjgraph Microsoft tells me that there is a Windows 32 bit version
https://support.microsoft.com/en-us/help/15056/windows-32-64-bit-faq

**Comment by davidjgraph** [comment]
There isn't a 32 windows version of draw.io.

**Comment by rawbone62** [comment]
Hence Kaleel can't install draw.io on his Windows 32-bit computer.

**Comment by davidjgraph** [comment]
And we cannot make one. A google for "draw.io 32bit windows" gives https://desk.draw.io/support/solutions/articles/16000078648-is-there-or-will-there-ever-be-a-32bit-windows-version-of-draw-io-desktop as the first result.
