### ISSUE TITLE
Animated flow support in confluence

### ISSUE THREAD

**Issue by n-gtm** [jgraph/drawio-desktop#1860]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I design a beautiful animated flow but end up with a still flow in confluence, Removes the charm and presentability. Request you to provide the necessary support to have this done.

**Describe the solution you'd like**
I would like to have Draw io enable the ability to insert animated flow in confluence thereby allowing it to edit at least the text within the boxes for maintainability. 
Just a thought - There could be an option of donation of minimum dollar amount if needed to get a point which can be used while having the flowchart enabled. A dollar per flowchart should be feasible.

**Describe alternatives you've considered**
There is no clear alternatives for this. I love Draw io but what is the point of having such a wonderful feature and unable to have it in confluence.

**Additional context**
This is a wonderful way of increasing the usage of draw.io and would eventually lead to a dominating segment in the area of flowchart software.

**Comment by davidjgraph** [comment]
For confluence requests please file a support via https://marketplace.atlassian.com/apps/1210933/draw-io-diagrams-whiteboards?hosting=cloud&tab=support including your SEN for drawio.
