### ISSUE TITLE
When number plugin is used, arrows don't show

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio-desktop#187]
Issue reproduced in draw.io online (Chrome and Incognito) and desktop app 12.2.2
Win10 and a user reported this issue in MacOS. 

When number plugin is used, arrows don't show. This happens when a number plugin is added and then a diagram is created or imported.
Video attached in the ticket 36031

I checked Anonymize plugin in draw.io online and desktop app (in order to see if other plugins work) and this one is working.

**Comment by ashed** [comment]
Yes, I saw it too. Arrows don't show when "number" plugins is used.
