### ISSUE TITLE
The "drawio.bkp" file does not disappear automatically

### ISSUE THREAD

**Issue by kdyzm** [jgraph/drawio-desktop#1872]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Whenever I create a new drawing project, a .drawio.bkp file is automatically generated. Even after I close the drawio software, the file remains and does not disappear automatically.

**Expected behavior**
I hope that after closing the drawio software, the .drawio.bkp file will disappear automatically, or is there a switch to control it?

**Screenshots**
![image](https://github.com/user-attachments/assets/4b85a2b8-4026-4da6-aa98-0364e59b4b53)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v22.1.16

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by kevinvankeer** [comment]
Disabling the following option worked for me: Extras -> Automatic backup

The bkp will never be created in the first place, but this is OK for my personal workflow.

Based upon https://github.com/jgraph/drawio-desktop/discussions/1003 :)

**Comment by kdyzm** [comment]
Thank you ! this solved my problem .

**Comment by kdyzm** [comment]
> Disabling the following option worked for me: Extras -> Automatic backup
> 
> The bkp will never be created in the first place, but this is OK for my personal workflow.
> 
> Based upon #1003 :)


Thank you ! this solved my problem .

**Comment by m-mohamedin** [comment]
Due to some error reports, we're not deleting the backup file to give users another option to recover the file.
Disabling the automatic backups is always an option

**Comment by kdurasie** [comment]
It's still an issue, but .bkp files are not the problem. 
Drawio just after run sometimes open it by default, sometimes doesn't recognize it's name and says that "there are some unsaved changes...". But it's not true, it's confusing.

Windows 11, desktop app.
