### ISSUE TITLE
Open multiple files at the same time (MACOS)

### ISSUE THREAD

**Issue by Scott-GT** [jgraph/drawio-desktop#1873]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
No, We can't appear to open drawio on the Mac more than once, meaning I can't copy/paste content from one file to another or even compare them.

**Describe the solution you'd like**
Be able to open multiple files at the same time. Ideally as tabs within the application with the ability to drag a tab to the side to have two windows/apps displaying at the same time

**Describe alternatives you've considered**
You have to use a browser to have more than one file open at a time.

**Additional context**

**Comment by m-mohamedin** [comment]
Can you please describe in more details how it's not possible in your system to open multiple files. I've tried by double clicking multiple files and here is the result:

![Screenshot 2024-09-30 at 6 55 38 PM](https://github.com/user-attachments/assets/f3146f4f-0aab-425d-84ab-53c1490e954c)
![Screenshot 2024-09-30 at 6 55 59 PM](https://github.com/user-attachments/assets/33e76ac9-139d-43f7-b188-6f3fc15f75b3)

Which method did you use?

Thanks

**Comment by Scott-GT** [comment]
Hi, When using the Drawio app on my Mac (M3 if it matters), you only get the option to create a new file or open an existing file. Once you open an existing file, I can’t find a way to open another file. There is no option in the app to open ‘another’ file in a new tab at the same time:   Using ‘’New’ or ‘Open’ will close the current drawing and open the other. If I return to Launchpad and click the Drawio app (i.e. a second time), it just returns me to the already open app rather than opening a second instance of the application. Regards, Scott From: Mohamed Mohamedin ***@***.***>Date: Monday, 30 September 2024 at 23:58To: jgraph/drawio-desktop ***@***.***>Cc: Scott-GT ***@***.***>, Author ***@***.***>Subject: Re: [jgraph/drawio-desktop] Open multiple files at the same time (MACOS) (Issue #1873)Can you please describe in more details how it's not possible in your system to open multiple files. I've tried by double clicking multiple files and here is the result:Screenshot.2024-09-30.at.6.55.38.PM.png (view on web)Screenshot.2024-09-30.at.6.55.59.PM.png (view on web)Which method did you use?Thanks—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by m-mohamedin** [comment]
Hi,

To open a new window with a new file, you'll need first to use File -> New (which always opens a new window) then in the new window File -> Open (or if the start screen is enabled, click "Open existing diagram"

Let me know if that works for you
Thanks

**Comment by Scott-GT** [comment]
I have no idea what I must have been doing, but it’s working….thank you. I’m sure that before, the new window would open up, replacing the existing open file.  From: Mohamed Mohamedin ***@***.***>Date: Tuesday, 1 October 2024 at 14:25To: jgraph/drawio-desktop ***@***.***>Cc: Scott-GT ***@***.***>, Author ***@***.***>Subject: Re: [jgraph/drawio-desktop] Open multiple files at the same time (MACOS) (Issue #1873)Hi,To open a new window with a new file, you'll need first to use File -> New (which always opens a new window) then in the new window File -> Open (or if the start screen is enabled, click "Open existing diagram"Let me know if that works for youThanks—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by TheKevinWang** [comment]
> Hi,
> 
> To open a new window with a new file, you'll need first to use File -> New (which always opens a new window) then in the new window File -> Open (or if the start screen is enabled, click "Open existing diagram"
> 
> Let me know if that works for you Thanks

This works, but I don't think is the most intuitive. For example, intellij will prompt whether to open in a new window or use existing, while O365 apps will open in a new window with file->open.
