### ISSUE TITLE
Font change does not apply to all selected lines in a Text shape

### ISSUE THREAD

**Issue by dgillman** [jgraph/drawio-desktop#1880]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When editing the text entered into a Text shape, it does not appear possible to apply a font change to all selected lines. Instead, the font is only applied to the first line of the selected text. The remaining lines must be individually selected to apply font changes.

**To Reproduce**
1. Drag a Text shape onto the canvas
2. Enter multiple lines of text into the Text shape
3. Select all lines of text in the Text shape
4. In the Format pane at the right, in the Text section, select "Courier New" in the font dropdown (it should be "Helvetia" by default, so this is a change of font family)

**Expected behavior**
All selected lines of text should now render in "Courier New" instead of "Helvetia".

**Screenshots**
#### Step 1: create Text shape
<img width="568" alt="Screenshot 2024-10-04 at 10 36 39 AM" src="https://github.com/user-attachments/assets/6f97667e-0b70-4bc9-abe3-5c4c1a8858fc">

#### Step2: highlight all text
<img width="556" alt="Screenshot 2024-10-04 at 10 36 55 AM" src="https://github.com/user-attachments/assets/efc7b9b9-3568-4ddf-a2c4-58c298e4a854">

#### Step 3: select a new font
<img width="569" alt="Screenshot 2024-10-04 at 10 37 06 AM" src="https://github.com/user-attachments/assets/95fb8ee2-cab8-4cdb-a29f-3b2f04da1738">

#### Step 4: font is only applied to line 1
<img width="571" alt="Screenshot 2024-10-04 at 10 37 15 AM" src="https://github.com/user-attachments/assets/74c6d72a-b376-46dd-a592-3a2852890e37">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.17

**Desktop (please complete the following information):**
 - OS: MacOS 14.6.1
 - Chrome: Version 129.0.6668.71 (Official Build) (arm64)

**Additional context**

**Comment by daniel-wrench** [comment]
There is a similar problem with font *size*. The first line changes correctly, but the following lines all change to a different size.

**Comment by m-mohamedin** [comment]
Should be fixed now
