### ISSUE TITLE
Canvas moves on mouse hover

### ISSUE THREAD

**Issue by ErikJamesRobles** [jgraph/drawio-desktop#1882]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
On load when you place your mouse over the canvas the canvas moves to the left.
**To Reproduce**
1. Go to 'either the online site or the desktop version'

**Expected behavior**
The canvas should stay stationary on load and move specifically when the user drags the canvas with the mouse drag button. 
**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z
v24.7.17
**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...
mac os 15.0.1 (24A348) chipset M2
**Additional context**
If this was the inteded behaviour of the developers then please feel free to close this issue.

**Comment by davidjgraph** [comment]
I cannot repeat using 24.7.17 universal on an M2 15.0.1.

I have a single rectangle in a diagram, I'm opening from finder, letting the file load and bringing the mouse into the canvas area after loading. I cannot see any shit.

**Comment by ErikJamesRobles** [comment]
Faulty mouse was causing the issue.
