### ISSUE TITLE
ALIGN OBJECTS ON PAGE

### ISSUE THREAD

**Issue by Levy0162** [jgraph/drawio-desktop#1887]
Hi developer, I have a feature suggestion for this software!!
I found that when I align an object on the page, it is suggested to link to an existing object or 2 vertical/horizontal lines in the middle of the page. Sometimes this is good but sometimes it is not for me. I think there should be a mode for this and I can turn it off. In simple terms, I would like to have a mode that can align objects based on the existing grid (4 small boxes make 1 large box) without depending on the existing objects or 2 vertical lines in the middle of the page. Anyway, I thank the people who created this software and those who suggested useful changes. Thanks.
![z5922270828020_9a4d2923e4cbf5479ce3b5ec8590bbba](https://github.com/user-attachments/assets/377accc2-9617-47ef-8c82-e6e691c105a8)
![z5922274425882_3ba382643cc2fb7764ff40c69e2f0996](https://github.com/user-attachments/assets/ddf840ea-5286-4e20-a320-b076ef456eb5)
![z5922279493596_d8d80374dc50d3f8544d3aa107eeb526](https://github.com/user-attachments/assets/dfc0b75f-d933-45cc-a087-6df63ed5c897)

**Comment by alderg** [comment]
Try uncheck "Guides":
<img width="238" alt="Screenshot 2024-10-12 at 08 10 01" src="https://github.com/user-attachments/assets/c24483fe-4fbe-4b42-ae10-34b32d4b7fe7">

**Comment by Levy0162** [comment]
I really thank you, it helped a lot with my project.

**Comment by Levy0162** [comment]
I really thank you, it helped a lot with my project.

**Comment by Levy0162** [comment]
I really thank you, Alderg. It helped a lot with my project.
