### ISSUE TITLE
Page size is not passed on the printing

### ISSUE THREAD

**Issue by FarSeeing** [jgraph/drawio-desktop#1893]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The `pageSize` parameter for the `.print` call was replaces with the `preferCSSPageSize` one in 40034f66faf93bd49b1fb22fe6c3b9d0e7100070
The issue is that this `preferCSSPageSize` is supported in `printToPDF` method only - https://www.electronjs.org/docs/latest/api/web-contents#contentsprintoptions-callback

**To Reproduce**
1. Set page size to anything but a default A4 one
2. Print the diagram
3. The printer settings will get A4 format

**Expected behavior**
Pass page size to the printer

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.17

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...

**Additional context**

**Comment by m-mohamedin** [comment]
A fix will be in the next release
