### ISSUE TITLE
In custom fonts the specified weights are not being taken into account. It is always the lightest weight

### ISSUE THREAD

**Issue by briandaya** [jgraph/drawio-desktop#1899]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When using custom fonts from Google Fonts, such as Montserrat or Lexend, the draw.io editor consistently displays the font in the thinnest weight (Thin 100) instead of Regular 400. This behavior persists across the "Google Fonts," "System Fonts," and "Web Fonts" options (e.g., by forcing https://fonts.googleapis.com/css2?family=Montserrat:wght@400), making text difficult to read at smaller sizes. The default weight should be 400, especially when specified.

**To Reproduce**
1. Go the font selection settings/font names/Custom.
2. Type "Montserrat" in "Google Fonts", or specify it through "System Fonts" if installed locally.
3. Alternatively, use "Web Fonts" and set the URL to force Regular 400 (e.g., https://fonts.googleapis.com/css2?family=Montserrat:wght@400). In that case, I can see in the diagram code:
`
style="text;html=1;whiteSpace=wrap;overflow=hidden;rounded=0;fontFamily=Montserrat;fontSize=12;strokeColor=none;sketch=1;curveFitting=1;jiggle=2;sketchStyle=comic;spacing=2;comic=1;verticalAlign=middle;fontStyle=0;fontSource=https%3A%2F%2Ffonts.googleapis.com%2Fcss2%3Ffamily%3DMontserrat%3Awght%40400;"
`
5. Observe that the font displays in Thin 100, regardless of the specified weight.

**Expected behavior**
The font should display at weight 400 by default, particularly if explicitly specified as Regular 400.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v24.8.3

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro, Versión	10.0.22631 comp 22631

**Additional context**
- Chrome Version 130.0.6723.70 (Build oficial) (64 bits)

**Comment by alderg** [comment]
See https://github.com/jgraph/drawio/issues/4465#issuecomment-2162969162
