### ISSUE TITLE
ERR_HTTP_RESPONSE_CODE_FAILURE on startup

### ISSUE THREAD

**Issue by hartzd** [jgraph/drawio-desktop#190]
Dear Guys, 

im using draw.io behind a proxy/sometimes offline. Somhow, the tool tries to establish a http connection, which is not working. 
Please see the error 
![image](https://user-images.githubusercontent.com/7710143/70241872-1982cd00-1770-11ea-8d61-873232dd84d7.png)

I would be appreciate if you can advise what todo. 
Im using 12.3.2 via windows installer. 

Kind Regards,
Dominik

**Comment by davidjgraph** [comment]
I just tried 12.3.2 with an offline windows 10 box, it works. Are you sure this problem isn't specific to the proxy case?

**Comment by hartzd** [comment]
Ok, I checked this right now. With a deactivated network card, I cant reproduce the error message. So it looks like its only a problem specific to the proxy case.
I googled a bit and found an interesting topic of electron : https://github.com/electron/electron/issues/21046

**Comment by davidjgraph** [comment]
Thanks for the link. I'll close this for now, but we can re-open if others see it.
