### ISSUE TITLE
can't rename the title

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [jgraph/drawio-desktop#191]
MacOs Mojave 10.14.6, just downloaded from the repo and i can't rename a already created opened project by clicking the title on the top right corner like in the website

**Comment by JokerYan** [comment]
Experiencing exactly the same issue on Windows 10.

**Comment by davidjgraph** [comment]
The convention in desktop apps is to use Save As to rename/copy. In web apps you have a fixed file ID in the cloud storage location, so renaming still applies to the same file.

On a file system when you rename do you save to a new file and delete the old one? It's best not to mix web app and desktop paradigms. I would need to see a convincing arguement for this. Not behaving the same over web and desktop is correct, there needs to be an additional point.
