### ISSUE TITLE
"unsaved changes system timed out" can't resolve regardless of what I try

### ISSUE THREAD

**Issue by LeMizukiHibiki** [jgraph/drawio-desktop#1917]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

I am hosting a draw.io project out of my google drive. 
It tries to save in real time, but fails (timed out). I try to manual save and it fails (timed out). I'm familiar with google drive and google suite and they save just fine, but draw.io can't for some reason. It will periodically catch up to what I'm doing without telling me it saved (same error message) of about max 5 min behind what I actually was doing which isn't so bad. My friend who is working on this with me has no issues, although they are in Germany with less internet connection and I am in USA with great connection as the host of this document.  I was working on this document for 4 hours yesterday and the last 90 minutes didn't save. I was working in different textboxes, assuming it would just periodically save and not tell me it was actually saving per the usual, but it wasn't. I hit "ctrl-z" to undo something in a text box and it applied an "undo" to everything I did in the last 90 minutes and disabled "redo" because it "didn't save." There was no record in revision history of what I had done in those last 90 minutes (last change I actually made was after 1AM MST and the last recorded change was after 11PM MST). Clicking on revisions close to 1AM were not the actual revisions I had been making. It was the old version from > 90 min before that.

**To Reproduce**

Opening my document on my end and trying to type does not save, gives error message. 

**Expected behavior**

The document to save, automatically or manually.

**Screenshots**
![image](https://github.com/user-attachments/assets/538be944-b645-4062-9264-b5dc3d8f8a0c)
![image](https://github.com/user-attachments/assets/0bfa8d4e-c7e8-4bc6-8e56-16bec7d3aa4f)
![image](https://github.com/user-attachments/assets/8adbc981-6539-492a-bb86-a77caa4c106e)
![image](https://github.com/user-attachments/assets/45200506-baa7-4854-b72e-a79410ab88b5)
![image](https://github.com/user-attachments/assets/5c8c224d-daa2-4e0e-a306-0d23dedc293e)
![image](https://github.com/user-attachments/assets/67d273a6-ddf4-42fe-a408-7f07f8272f34)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version v24.9.1

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

Main notes:
- I consistently get the error "unsaved changes system timed out" for the auto save. 
- I try to manually save and it spins then provides me the same error "timed out"
- My internet speed is fast and consistent
- Getting a new error "cannot read properties of undefined (reading '0')"

Other notes:
- My drive is not full of memory, it's quite empty actually.
- Compression is off on draw.io (was never on, but I turned it on then off to see if it would make a difference with no change)
- Neither I nor my friend are using a VPN
- I tried disabling add blocker extensions, no change
- I tried enabling / disabling chromes "accelerated graphics" feature (some browsers require this on/off), no change
- I tried on Microsoft Edge, issue persists
- I tried with a different google account by sharing the document, issue persists
- I tried looking to see if images were too big so I reduced file sizes, issue persists.
- I cleared my cookies/cache from "all time," issue persists.
- I also tried disabling "real time collaboration," issue persists.
- I installed "draw.io" on google workspace just in case it would fix it, no change.

My friend does not have any problems with this, please assist. Not sure what else to try at this point.

**Comment by davidjgraph** [comment]
Saving to local disk sync'ed to cloud storage has always been not 100% stable. It's something to do with the sync client changing something while we have a file handle open. How big is the file?

The best option is just to use app.diagrams.net if you want to save to Google Drive.

**Comment by LeMizukiHibiki** [comment]
That’s the thing is i am saving to google drive. Its only saving to google
drive. The file size if i recall is something like 16mb. Also, i am only
using the website.

**Comment by davidjgraph** [comment]
ok, well this is the desktop repo...

**Comment by LeMizukiHibiki** [comment]
Ah, this is where it lead me when i requested support. Can this be
transferred to the correct category / do you have a link for the correct
one?

**Comment by LeMizukiHibiki** [comment]
I've re-opened in the general draw.io bug report thank you. (https://github.com/jgraph/drawio/issues/4771)
