### ISSUE TITLE
AWS19 shape preview showing wrong icons

### ISSUE THREAD

**Issue by Kirizan** [jgraph/drawio-desktop#192]
When going to the add more shapes section, if you select the AWS19, it shows the black and white shapes that are actually AWS18. I checked both the MacOS Desktop version and the online version and they are the same. Once the shapes are added to the diagram, the correct versions are shown, it's on the preview section in the selector that has the incorrect icons displayed.

**Comment by egrimate** [comment]
It is intended as the code for the preview doesn't render these stencils correctly, so we used the older stencils for the preview.
