### ISSUE TITLE
Unintuitive Drag Behaviour

### ISSUE THREAD

**Issue by hendrysudrajat** [jgraph/drawio-desktop#1922]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Previously, to drag the canvas, I can press and hold the right mouse button, and once I am done just release.
Now, to start drag, click the right mouse button, and to stop dragging click on the left mouse button.

**To Reproduce**
1. Right click and hold the mouse button, Canvas won't move
2. When you let go of the right mouse button, canvas will move and jump to the current mouse position
3. To stop dragging, need to click on the left mouse button

**Expected behavior**
Press and hold right mouse button should start dragging the canvas. When done dragging, just release the right mouse button

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 25.0.1

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...

**Additional context**

**Comment by hendrysudrajat** [comment]
In addition, because the right mouse button is now used to trigger the start of the drag, the context menu is now gone.

**Comment by alderg** [comment]
What operating system and version are you using? Are you using a touchpad, touch screen, pen or other special pointer device?

**Comment by alderg** [comment]
Fix will be in 25.0.2.

**Comment by davidjgraph** [comment]
Caused https://github.com/electron/electron/issues/44898. Reverting electron from 32.2.6 to 32.2.5 fixes the problem.
