### ISSUE TITLE
Lock file needs a refresh

### ISSUE THREAD

**Issue by ghisvail** [jgraph/drawio-desktop#193]
Your package.json file lists a dependency on Electron version 7 or later, whilst your yarn.lock provides Electron version 6. This inconsistency prevents builds from source of the current version of the software. Please consider refreshing your lock file.

**Comment by davidjgraph** [comment]
Pushed, thanks for report.

**Comment by ghisvail** [comment]
Thanks. The Flatpak build is now up to date.
