### ISSUE TITLE
Save a svg file like export file

### ISSUE THREAD

**Issue by jianmj** [jgraph/drawio-desktop#1933]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
i  import svg file which export from draw.io desktop ,  after modifying and saving the file, the shape lost in SVG，i found browser tip reference  image not found

show on  draw.io desktop

![image](https://github.com/user-attachments/assets/f306450d-f371-4b8d-929b-f96fee427d17)

show on browser

![image](https://github.com/user-attachments/assets/20a32d40-a61f-478f-953f-e2118f3c812a)

**Describe the solution you'd like**
Is it possible to add a parameter that saves the file without using a reference file and embeds the image into the file, just like the export function

**Describe alternatives you've considered**
The export function can meet my needs, but it is relatively troublesome to use export and choose a file path to overwrite the original file every time I save. 

draw.io desktop version :  v25.0.2  on windows

**Comment by davidjgraph** [comment]
"Saving" to SVG without the data isn't saving, it's exporting. Trying automating it via the command line.
