### ISSUE TITLE
broken fonts (Tofu) by open/save/save as dialog

### ISSUE THREAD

**Issue by robertmeggle** [jgraph/drawio-desktop#1938]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If I open the dialog open, save or save as, the fonts are not available. 
I tried to add windows fonts by
~~~
sudo apt install fonts-noto fonts-noto-cjk fonts-noto-color-emoji
sudo apt install fonts-dejavu fonts-liberation fonts-droid-fallback
~~~

**Screenshots**
Screenshots to help explain my problem:
![2024-12-16 11-27-15-screenshot](https://github.com/user-attachments/assets/8bfd579c-30d6-4d4a-815f-afc711bd3518)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 25.0.1

**Desktop (please complete the following information):**

 - OS: Ubuntu 24.04.1 LTS
 - Browser: firefox
 - Browser Version: 133.0.3 (64-Bit)

**Additional context**

Is there any workaround?

**Comment by davidjgraph** [comment]
Duplicate https://github.com/jgraph/drawio-desktop/issues/368
