### ISSUE TITLE
Exporting diagrams to PNG/JPEG with Google fonts

### ISSUE THREAD

**Issue by aprasadh** [jgraph/drawio-desktop#194]
When exporting diagrams with Google fonts, it is not exported with the selected Google font.

**Comment by ashrafteleb** [comment]
We cannot reproduce in 12.6.5, if you still having this issue, let us know and we will re-open the issue

**Comment by kaimast** [comment]
Is there a separate bug like this for the web version? I am trying to export a pdf with the "Linux Libertine Display O" font.
It display fine on the web, but when exporting it seems to switch back to what looks like "times new roman".

**Comment by fernando-mc** [comment]
@ashrafteleb I have a reproduction for this issue with the desktop version on Mac. See the "processImage" text:

[template.drawio.zip](https://github.com/jgraph/drawio-desktop/files/6034049/template.drawio.zip)
![template](https://user-images.githubusercontent.com/6182464/108962076-156cf480-762d-11eb-9d4c-73a8bc6ad500.png)

This uses Google Fonts: `Roboto Mono`

**Comment by ashrafteleb** [comment]
Unfortunately, I couldn't reproduce also. This is what I got
![template](https://user-images.githubusercontent.com/24944765/109004013-2857e700-7676-11eb-92db-ce3e4d42610e.png)
