### ISSUE TITLE
System appearance preset (light mode) not respected for new diagrams

### ISSUE THREAD

**Issue by xanadiu** [jgraph/drawio-desktop#1940]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
My system appearance defaults to light mode. When I launch draw.io or want to create a new diagram, the new document window always uses dark mode.

**To Reproduce**
1. Ensure your system appearance (macOS) is set to light mode
2. Launch the app
3. The welcome screen appears in light mode
4. The dialog (new / open diagram) appears in dark mode
5. The document also appears in dark mode
6. The appearance setting (moon icon in the upper right) shows "automatic" as the selected value
7. After clicking on the selected entry, the appearance switches to light mode

**Expected behavior**
The application respects the system preset right when showing the first dialog (new / open document).

**Screenshots**
![Bildschirmfoto 2024-12-18 um 10 18 09](https://github.com/user-attachments/assets/6fef2ca2-5c3f-4a54-a0fa-39d7014c1156)
![Bildschirmfoto 2024-12-18 um 10 18 31](https://github.com/user-attachments/assets/bd50d626-b4ad-4a6e-8b8d-675b5ae1b642)
![Bildschirmfoto 2024-12-18 um 10 18 40](https://github.com/user-attachments/assets/30578752-aa14-4c5e-ba99-dfa3e70dabe6)
![Bildschirmfoto 2024-12-18 um 10 18 53](https://github.com/user-attachments/assets/410ba9f7-aa55-44c1-9d01-a9ed35e21707)
![Bildschirmfoto 2024-12-18 um 10 19 09](https://github.com/user-attachments/assets/93fbe5ae-23bf-4c24-b0b0-397464aad8fc)
![Bildschirmfoto 2024-12-18 um 10 19 19](https://github.com/user-attachments/assets/07039bd6-d0a5-4973-a4f1-ce5e605f00be)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version v25.0.2

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.7.1, Apple M2

**Additional context**
n/a

**Comment by m-mohamedin** [comment]
Hi,

Unfortunately, we couldn't reproduce on macOS 15.1.1

**Comment by davidjgraph** [comment]
We can't test 13.x, unfortunately.
