### ISSUE TITLE
Changing the scale of the interface.

### ISSUE THREAD

**Issue by SterhLight** [jgraph/drawio-desktop#1941]
Perhaps my question is primitive, but I could not find an answer to it. How to increase the scale of the user interface in the desktop version? The icons and text are too small and my eyes get tired quickly.

**draw.io version:**
- draw.io version 25.0.2

**Desktop:**
 - OS: Windows

**Comment by alderg** [comment]
Try Help, Zoom In

<img width="343" alt="Screenshot 2024-12-22 at 10 03 15" src="https://github.com/user-attachments/assets/6ca4a911-4227-46da-ad56-877b4b88389e" />

**Comment by SterhLight** [comment]
> Try Help, Zoom In
> 
> <img alt="Screenshot 2024-12-22 at 10 03 15" width="343" src="https://private-user-images.githubusercontent.com/921200/397974638-6ca4a911-4227-46da-ad56-877b4b88389e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTg3MzEsIm5iZiI6MTczNDg1ODQzMSwicGF0aCI6Ii85MjEyMDAvMzk3OTc0NjM4LTZjYTRhOTExLTQyMjctNDZkYS1hZDU2LTg3N2I0Yjg4Mzg5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQwOTA3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjllMzZhMmM2M2Y3OTA0MTZhZTcwOTU4MGI0MTdjYTE2MzQyZWJiNDFjMThiNzk0OGNmYTE5NDFjNGRjYWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xeJoT21SvfIU_LxKJRHOntfnX0SLbZXic4jAag2jlxM">

I see! Finally! Thank you!

**Comment by c02y** [comment]
Is it able to save the zoom level in Settings/Preferences? Since after I restart drawio-desktop, the zoom-level is back to the default one which is quite big

FYI:
Archlinux
Wayland/Hyprland
drawio-desktop-bin 28.0.4-1

**UPDATE**:
Run the application like `ELECTRON_OZONE_PLATFORM_HINT=auto /opt/drawio/drawio` or set `ELECTRON_OZONE_PLATFORM_HINT=auto` env, since drawio-desktop is using Electron, this works for other Electron programs like VSCode as well.

**Comment by alderg** [comment]
The interface zoom from Help > Zoom In/Out isn't saved, but you can start the app with a fixed interface scale using the `--zoom` command line option, e.g. `drawio --zoom 1.25` (on Windows, add it to the shortcut target). Thanks for sharing the `ELECTRON_OZONE_PLATFORM_HINT=auto` tip for Wayland.
