### ISSUE TITLE
Copy/export image to clipboard

### ISSUE THREAD

**Issue by fennibay** [jgraph/drawio-desktop#195]
Please provide an export option that exports the whole page or the selected portion to the clipboard as an image.

Copy (ctrl+c) command would also address the need, but I understand draw.io is using a text-based internal representation of the selection for internal copy-paste purposes.

# Details

When working with other desktop tools (e.g. Powerpoint, Word) it helps to be able to copy-paste the draw.io diagrams as images.

Currently draw.io provides its internal text-based representation of the diagram in the clipboard when the image is copied.

Workaround is to export to a temporary image file and embed this image in the target document.

Previously https://github.com/jgraph/drawio/issues/290 was logged, but could not be resolved as accessing the clipboard is not possible from inside the browser. On Electron this would be hopefully possible.

**Comment by fennibay** [comment]
Electron does offer an API for accessing the system clipboard: https://electronjs.org/docs/api/clipboard#clipboardwriteimageimage-type

I'm not sure though if draw.io's architecture allows easy access to this API.

**Comment by ashrafteleb** [comment]
Added, will be available in the next release

**Comment by parthi2929** [comment]
This seems to be not available still.

**Comment by fennibay** [comment]
It's under Edit->Copy as Image

**Comment by parthi2929** [comment]
I see it in 13.6.2 and not in 13.7.2

**Comment by ashrafteleb** [comment]
I've just tried it on 13.7.3. What is your OS?

**Comment by parthi2929** [comment]
Win 10, but I checked directly online in browser. could not find that option.. now that says 13.7.5
![image](https://user-images.githubusercontent.com/11896263/94646739-86bdab00-030c-11eb-9c1b-e2c5fe49e018.png)

**Comment by ashrafteleb** [comment]
Unfortunately, this is a desktop only feature. Online, you'll need to use the export
