### ISSUE TITLE
Printing from Mac OS desktop version, I can only print the diagram once

### ISSUE THREAD

**Issue by see3d** [jgraph/drawio-desktop#196]
Running  MacOS 10.14.6 and draw.io 12.4.2 desktop version.
I can print the diagram once, but trying to print after that does not actually print anything.  
I have to quit, restart draw.io, reload my diagram and I get one more print operation. 
It does not matter if it is a print to device, print to PDF or open in Preview.  

Steps to reproduce issue (without wasting paper):
   -Open draw.io desktop and document.
   -Cmd p
   -click Ok to defaults in dialog box
   -select Open in Preview
print dialog closes
Preview opens with the image

   -return to draw.io window
   -Cmd p
   -click Ok to defaults in dialog box
   -select Open in Preview
print dialog closes
Preview does not open

The same thing happens with actual printing to a device.
Closing draw.io  and starting again allows one print operation again.

**Comment by ashrafteleb** [comment]
It's a bug in Electron itself https://github.com/electron/electron/issues/14705

As a workaround, please use File -> Export as -> PDF...

**Comment by ashrafteleb** [comment]
Also https://github.com/electron/electron/issues/21195

**Comment by davidjgraph** [comment]
There is a PR submitted upstream for https://github.com/electron/electron/issues/21397 to address the issue

**Comment by davidjgraph** [comment]
Apparently fixed in Electron 8.0.0 https://github.com/electron/electron/issues/21195
