### ISSUE TITLE
Translation of individual program locations

### ISSUE THREAD

**Issue by vovka3003** [jgraph/drawio-desktop#197]
Hello!
Is it possible to somehow translate this part (parameter names and some values)?:
![Screenshot](https://i.imgur.com/vfd1dAg.png)

**Comment by ashed** [comment]
Agree with this issue author. This is lack in i18n

**Comment by davidjgraph** [comment]
@ashed Please stop making comments that add nothing to the thread. If you agree, thumbs up the original post, don't spam people with noise.
