### ISSUE TITLE
plugins are not loaded in export/batch/cli mode

### ISSUE THREAD

**Issue by udrechsler** [jgraph/drawio-desktop#206]
plugins are not loaded when drawio is started in batch mode.
i.e.  `electron drawio/src/main/webapp  file.drawio -x -f svg -o file.svg` won't load any plugins,
making the batch mode unusable if custom shapes are injected via plugins.

**Comment by ashed** [comment]
Maybe this is not implemented feature?
Besides it is very useful.

**Comment by BlueManiac** [comment]
I need to convert several hundreds of maps to svg with the svgdata plugin. Are there any possible workarounds?
It would be nice if you could pass the plugins to use as command line parameters.

**Comment by nopeslide** [comment]
> I need to convert several hundreds of maps to svg with the svgdata plugin. Are there any possible workarounds?
> It would be nice if you could pass the plugins to use as command line parameters.

see #406

**Comment by Mq89** [comment]
Is there an update on this matter?
We are using custom shapes based on a plugin and would profit from a working export in the desktop app.
