### ISSUE TITLE
When multi instances don't load settings

### ISSUE THREAD

**Issue by Kapparina** [jgraph/drawio-desktop#207]
Hi,
When I open draw-desktop multiple time the settings are loaded just for the first instance.

![2020-01-29 19_18_15-](https://user-images.githubusercontent.com/32843752/73384848-609ec180-42cc-11ea-8e02-6f0244c6395f.png)

draw.io-12.5.3
Windows 10

If you want more info, ask me.

Edit : 
1 - Run both as Admin don't work
2 - If I open a file that **doesn't exist** from File ->Open Recent , this open a new instance with the good settings

**Comment by ashrafteleb** [comment]
Fixed, will be available in the next release
