### ISSUE TITLE
import and export extension of existing commands for commnd line

### ISSUE THREAD

**Issue by gitsammas** [jgraph/drawio-desktop#208]
Feature request
Hello I want to ask for more commandine export functionalities. I found: https://j2r2b.github.io/2019/08/06/drawio-cli.html, so export to pdf/images is possible. My new feature wishes for command line would be:
export to xml (options: all pages and not compressed)
export to html file (options: all of gui selected: Include a copy of diagram, zoom 100%, all pages,Layers, lightbox)
last point saveas, when I open e.g. not the original file, but the exported xml-File I wish to save it as drawio again. This features are all available via GUI, I need those functionalities via cli. Idea is that document could be edited via (Human)-user and on the otherside autoupdates via powershell, so I need both original drawio for humans and uncompressed xml for computer. The htmlexport would be for a kind of preview.
Thanks

**Comment by ashrafteleb** [comment]
XML export is added

**Comment by gitsammas** [comment]
Thanks for updating, I just download the newest version and tested it - xml uncompressed works fine :)
