### ISSUE TITLE
Shapes can't be moved freely (they snap to the top of the diagram) when opened in draw.io online and desktop app

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio-desktop#209]
The issue is reproduced in draw.io online and desktop app 12.5.3. (the latest version)

When a file is opened via File > Open from (both in draw.io online and desktop app), there are 2 layers and all shapes really snap to the top of the diagram when moved via mouse cursor.

When a file is imported via File > Import from (both in draw.io online and desktop app), there are 3 layers (two background layers - one of them changes nothing when unticked) and a shape acts normally i.e it can be moved freely across the diagram without snapping.

Drag&drop also works well.

A user diagram + video are in the ticket 37040

**Comment by davidjgraph** [comment]
Still in 12.6.5?

**Comment by mararad** [comment]
Yes, still in 12.6.5

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release. The shape will snap in all cases regardless of the selected layer in the layers dialog. To avoid this, hold down the Alt key while moving the cell.
