### ISSUE TITLE
Command line export to image

### ISSUE THREAD

**Issue by ddmng** [jgraph/drawio-desktop#21]
Hi. I currently store all my draw.io diagrams in GitLab and I'd like to convert the xml files to .png just before git-pushing the new version of the diagrams. In this way I can include the .png in the commit and view the diagram easily in the GitLab interface without opening the xml with draw.io.
Therefore I'm searching for a command-line export/convert feature in order to make all these steps automatic (e.g. in a git commit-hook). As far as I can see there's no such feature in draw.io, do you know if it could be accomplished in some way or a new product feature is the only way?

**Comment by languitar** [comment]
Exactly for such purposes I have created [drawio-batch](https://github.com/languitar/drawio-batch). Maybe you can use this in the meantime until an officially supported feature exists.

**Comment by ddmng** [comment]
@languitar thanks, I will try it!

**Comment by ashrafteleb** [comment]
Feature added, will be available in next release

**Comment by davidjgraph** [comment]
Added in https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5

**Comment by languitar** [comment]
I will deprecate my drawio-batch now that this is available.

**Comment by davidjgraph** [comment]
Well, someone should double check it's working as expected :D

**Comment by languitar** [comment]
Ok, it doesn't work, at least in the packaged deb file ;-) #107

**Comment by davidjgraph** [comment]
Is this now resolved?

**Comment by languitar** [comment]
At least #107 is solved as expected. I didn't try other features so far.

**Comment by paul-cleverley** [comment]
13.0.1 command line interface exports a drawio file to PDF when XML format is specified
