### ISSUE TITLE
Error "File already exist" when uploading 2 files with the same file size

### ISSUE THREAD

**Issue by enricovicari** [jgraph/drawio-desktop#216]
When creating a new Library I get the error "File already exist" if I'm uploading X number of files and 2 of these files happen to have the exact same file size.

e.g. if I have 2 .PNG files with different names and different content but exact same file size, when I try to upload them at the same time to create a new Library in Draw.io (Mac) I will get the error message "File already exist" and only 1 of those 2 files will get uploaded.

**Comment by ashrafteleb** [comment]
These two files are indeed identical. In draw.io we compare file contents. Different names are not enough. Contents should also be different.

**Comment by enricovicari** [comment]
The error message appears when 2 files with the same identical file size are uploaded.
@ ashrafteleb closed the issue but this is not resolved.

I have 2 icons that look identical but can be used by our marketing team for 2 different reasons. They represent 2 of our products (hardware) that look identical on the outside but have different software installed. Hence why having 2 "identical" files with different names is something we need in our library.

Please reconsider this as the current behaviour is not allowing me to make something useful for my team.

**Comment by ashrafteleb** [comment]
The only workaround I can think of is to save with a different file format. Say, jpeg and png
