### ISSUE TITLE
Windows Installer hangs around 30%

### ISSUE THREAD

**Issue by dunxd** [jgraph/drawio-desktop#217]
When running the installer for Windows, it never progresses past around roughly 30%.  I am running Windows 10 Enterprise 1909 build 18363.628 64-bit.  

Windows Defender anti-virus is running, but doesn't report anything. The same occurs with Controlled folder access switched on or off - nothing reported here either.

**Comment by davidjgraph** [comment]
Maybe try a fresh download in case the download was corrupted somehow

**Comment by dunxd** [comment]
I've done that.  I also tried the previous version (12.5.3), and same issue. Reboot, same issue.

No-installer version works ok for me.

**Comment by dunxd** [comment]
Also tried in safe mode, but same thing happened. I noticed that Task Manager reports the installer as 32-bit. Is that intended?

I can copy the No installer exe to Program Files but not sure what else the installer does. Register default file types seems likely. What else?

**Comment by davidjgraph** [comment]
Probably some windows registry writes. It needs admin permissions, so the user installing probably doesn't have some permission. We just use electron builder to create it, it's not subject we have in depth knowledge of.

**Comment by dunxd** [comment]
User is an Admin, and granted admin rights to the installer when prompted. It's not working for me.

**Comment by davidjgraph** [comment]
Best place to submit is upstream at https://github.com/electron-userland/electron-builder/issues , since just take their code as-is.

There is a feature request for checksums at https://github.com/jgraph/drawio-desktop/issues/43

**Comment by dunxd** [comment]
What I meant was that you could publish a checksum of each draw.io download so that people can compare it with a checksum of what they downloaded. That's not uncommon.

You suggested that I may have got a corrupted installer. I have no way of confirming it. If checksums where available that would answer the question.

--
Duncan

________________________________

**Comment by SeungHuLee** [comment]
I'm experiencing same issue here. I had the same issue last year with different version and now it's still there. Well, you provide no Installer version so.. whatever.
