### ISSUE TITLE
Error "File already exist" when uploading 2 files with the same file size

### ISSUE THREAD

**Issue by enricovicari** [jgraph/drawio-desktop#218]
As already explained here: [Issue#216](https://github.com/jgraph/drawio-desktop/issues/216)

The error message appears when 2 files with the same identical file size are uploaded.
@ ashrafteleb closed the issue but this is not resolved.

I have 2 icons that look identical but can be used by our marketing team for 2 different reasons. They represent 2 of our products (hardware) that look identical on the outside but have different software installed. Hence why having 2 "identical" files with different names is something we need in our library.

Please reconsider this as the current behaviour is not allowing me to make something useful for my team.

Thank you.

**Comment by davidjgraph** [comment]
please continue that issue, rather open a new one.
