### ISSUE TITLE
Enable plant UML for offline desktop mode

### ISSUE THREAD

**Issue by ericis** [jgraph/drawio-desktop#219]
Enable `Arrange -> Insert -> Advanced -> Plant UML` in the desktop offline mode. Currently available on draw.io website.

**Comment by davidjgraph** [comment]
PlantUML requires a server.

**Comment by carlo-quinonez** [comment]
Can we provide a server URL in the config? It could default to the public plantuml server.

**Comment by davidjgraph** [comment]
No, the desktop tool is designed for offline, that's a basic design decision. If you want something that talks remotely, use the online app.

**Comment by ruudsieb** [comment]
What about running a server locally? 
`java -jar plantuml.jar -picoweb`

**Comment by davidjgraph** [comment]
Possible. But someone needs to submit the PR, perform a security review and take responsibility for maintaining the feature.

**Comment by CV-engineer-CDD** [comment]
Hi ,is there any solution about use  plantuml  in drawio offline  ?  Where and How to  edit drawio's config  ?

**Comment by davidjgraph** [comment]
All update to this issue are in this thread.

**Comment by tangoalx** [comment]
This feature would be really nice. It would be great to find more supporters.

Note that plantuml also exists as stand-alone jar executable. A server is not necessarily required.

**Comment by davidjgraph** [comment]
This isn't possible for security reasons, even with a local jar.

**Comment by a-patel** [comment]
This feature would be really nice.

**Comment by davidjgraph** [comment]
Adds client-side PlantUML parser in 30.3.6.
