### ISSUE TITLE
Unexpected behavior of CLI --version option on macOS

### ISSUE THREAD

**Issue by 3TUSK** [jgraph/drawio-desktop#220]
Executing the following:

```bash
/Applications/draw.io.app/Contents/MacOS/draw.io --help
```

results into the following console output:

```
12.6.5
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
12:02:58.196 › Checking for update
Segmentation fault: 11
```
plus the program crashes (exit with non-zero status code). To verify that it crashes with non-zero status code, use

```bash
/Applications/draw.io.app/Contents/MacOS/draw.io --help && echo "Exits with 0"
```

and notice that the `echo` part is not executed.

My environment is as follow:

  - macOS High Sierra 10.13.6
  - draw.io desktop 12.6.5

As in the console output, the `--version` option works as expect, however it still attempts to launch the app for some reason and results in a seg. fault.  
I believe that `--version` option should not cause the app to launch, but simply exit after printing the version number. At the very least, the seg. fault is definitely unexpected.

**Comment by ashrafteleb** [comment]
Fixed, will be available with next release
