### ISSUE TITLE
Icon colour intensity

### ISSUE THREAD

**Issue by celynwalters** [jgraph/drawio-desktop#221]
This is a strange one, I thought I was going crazy.

The draw.io icons colours are inconsistent.
For instance, on the web in a browser:

![browser](https://user-images.githubusercontent.com/3299161/74551114-85409d80-4f4a-11ea-91f6-9468ca424b7a.png)

In the desktop app:

![desktop](https://user-images.githubusercontent.com/3299161/74551136-8d98d880-4f4a-11ea-9110-aec612cfbfd4.png)

I first noticed it on the desktop app, but it also seems to be on the main site!

![home](https://user-images.githubusercontent.com/3299161/74551155-9689aa00-4f4a-11ea-998e-1713b591791e.png)

This applies to the favicons too:

![favicons](https://user-images.githubusercontent.com/3299161/74552319-da7dae80-4f4c-11ea-8422-9d3e2e2a38d4.png)

For reference, my environment:

> OS: Ubuntu 16.04
> Browser: Firefox 72.0.2
> Desktop version: `draw.io-x86_64-12.6.5.appImage`

**Comment by ashrafteleb** [comment]
I cannot reproduce, on my machine, all look the same

<img width="772" alt="Screen Shot 2020-03-10 at 9 28 38 AM" src="https://user-images.githubusercontent.com/24944765/76316798-877bea80-62b1-11ea-8002-f3040d29ff25.png">

<img width="783" alt="Screen Shot 2020-03-10 at 8 32 09 AM" src="https://user-images.githubusercontent.com/24944765/76312519-a4142480-62a9-11ea-97fc-8330762bf0fb.png">

**Comment by celynwalters** [comment]
Now I can't reproduce either... although since opening the issue, I've reinstalled Windows/Ubuntu.
It _was_ happening reliably enough for me to open the issue in the first place.
I'll put it down to something related to the rebranding and old cache. Closing.
