### ISSUE TITLE
CLI export of diagrams with mathematical typesetting to SVG does NOT render math formulas

### ISSUE THREAD

**Issue by kammoh** [jgraph/drawio-desktop#223]
Export of diagrams to SVG from command line when a diagram has mathematical typesetting, does render math formulas, i.e. raw AsciiMath or Latex appears in the SVG, e.g. ``  `a^2+b^2 = c^2` `` . Export to PDF or PNG from command line or export using GUI to SVG or other formats works fine.

command used:
`drawio -x -o out.svg diagram.drawio`

drawio-desktop version: 12.6.5
OS: Ubuntu 18.04.4

**Comment by ashrafteleb** [comment]
Fixed, will be available in the next release
