### ISSUE TITLE
Draw.io Desktop PNG Export External Server

### ISSUE THREAD

**Issue by exziled** [jgraph/drawio-desktop#23]
Version: 8.2.1

When using Draw.io desktop, certain export configurations trigger connections to externally hosted draw.io services.  I have clients that require no "cloud" services be used with all data processed locally. draw.io desktop mostly solves that problem.  Is this external connection intentional and required or an accidental inclusion in the desktop version?

Steps to Reproduce:
- Create any diagram, a rectangle for example
- File -> Export as -> PNG
- Set Zoom to 10000% (I haven't tried to find the switch over point between local and remote, but larger zooms seem to trigger the remote connection)
- draw.io makes request to 199.38.86.62

**Comment by davidjgraph** [comment]
Any zoom other than 100% needs an external server, currently. Need an issue in the core project to investigate whether canvas can do zoomed image export

**Comment by davidjgraph** [comment]
No externally requests in https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5
