### ISSUE TITLE
Draw.io shows blank screen only

### ISSUE THREAD

**Issue by Philipp574** [jgraph/drawio-desktop#234]
Hi! After using draw.io in confluence for a few months, we now want to use the desktop app again.
Draw.io 8.8.0 still runs on our Windows Server 2012. But the other versions don't work
Draw.io 12.6.5 shows blank screen only.
Draw.io 12.5.3 shows blank screen and crashed.

Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	draw.io.exe
  Anwendungsversion:	12.5.3.328
  Anwendungszeitstempel:	5e1caadb
  Fehlermodulname:	Sfrhook64.dll
  Fehlermodulversion:	7.16.0.21
  Fehlermodulzeitstempel:	5a0a475b
  Ausnahmecode:	c0000005
  Ausnahmeoffset:	000000000000d003
  Betriebsystemversion:	6.3.9600.2.0.0.144.8
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	8f3c
  Zusatzinformation 2:	8f3cc86f965d1a85ac8992f8690100cc
  Zusatzinformation 3:	d686
  Zusatzinformation 4:	d686a982821d84fde37525c430482797

Whats going wrong? Is there an internet connection needed to start?

Thanks!

**Comment by davidjgraph** [comment]
No connection is needed, but we don't test on Windows Server 2012. Is it a 32 bit instance?

**Comment by Philipp574** [comment]
Yes it is a 32 bit instance. It looks like a citrix problem to me.
Everything works fine on other windows server 2012 machines.

**Comment by davidjgraph** [comment]
Possible, but outside our expertise. Try searches for "citrix electron", like https://discuss.atom.io/t/how-to-develop-electron-application-which-is-citrix-compatible/20708/7

**Comment by Philipp574** [comment]
Now we have it! Citrixs hooks the application:
https://support.citrix.com/article/CTX107825

`
[HKEY_LOCAL_MACHINE\SOFTWARE\Citrix\CtxHook]
"ExcludedImageNames"="draw.io.exe"

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\citrix\CtxHook]
"ExcludedImageNames"="draw.io.exe"
`
