### ISSUE TITLE
unable to load libs from url

### ISSUE THREAD

**Issue by jgroom33** [jgraph/drawio-desktop#235]
[these](https://desk.draw.io/support/solutions/articles/16000058316-how-to-configure-draw-io-) docs suggest one of these configs should work:

* libs.url

<details>

```json
{
  "libraries": [
    {
      "title": {
        "main": "Ciena"
      },
      "entries": [
        {
          "id": "ciena-graphics",
          "title": {
            "main": "Graphics"
          },
          "desc": {
            "main": "Collection of Graphics for Ciena"
          },
          "libs": [
            {
              "title": {
                "main": "Graphics for Ciena"
              },
"url":"gist.githubusercontent.com/jgroom33/fb2ab4a478547ca1fc5e0c292ca08ea7/raw/135c78ba8cd82f469d88b36024864a0bfe35388a/ciena.xml"
            }
          ]
        }
      ]
    }
  ],
  "defaultCustomLibraries": ["ciena-graphics"]
}
```
</details>

* defaultCustomLibraries

<details>

```json
{
  "defaultCustomLibraries": [ 
"gist.githubusercontent.com/jgroom33/fb2ab4a478547ca1fc5e0c292ca08ea7/raw/135c78ba8cd82f469d88b36024864a0bfe35388a/ciena.xml"
  ]
}
```

</details>

I attempted the following modifications:

* url encoded/not
* with/without https
* raw gist with/without `<mxlibrary>` wrapper

**Comment by md2k** [comment]
Have same problem with MacOs version. 
```json
{
  "libraries": [
    {
      "title": {
        "main": "Collection"
      },
      "entries": [
        {
          "id": "test-collection",
          "title": {
            "main": "Collection"
          },
          "desc": {
            "main": "My personal collection for Draw.Io/Diagrams.net"
          },
          "libs": [
            {
              "title": {
                "main": "Azure Compute"
              },
              "prefetch": true,
              "url": "Uhttps%3A%2F%2Fraw.githubusercontent.com%2Fpacodelacruz%2Fdiagrams-net-azure-libraries%2Fmaster%2FAzure-Compute.xml"
            }
          ]
        }
      ]
    }
  ]
}
```
But have this strange error when Shape collection selected:
![image](https://user-images.githubusercontent.com/195619/94594787-36056e00-028a-11eb-8e49-9b0f51a2ad6f.png)

**Comment by jgroom33** [comment]
a similar behavior exists in the vs-code extension: https://github.com/hediet/vscode-drawio/issues/210

**Comment by davidjgraph** [comment]
This is expected, the desktop is designed to be network isolated for security reasons, remote calls shouldn't work.

**Comment by Mikecom32** [comment]
@davidjgraph Could this be reconsidered? We have a very similar use case to the functionality @jgroom33 described in https://github.com/hediet/vscode-drawio/issues/210

For what it's worth, there is other functionality inside the desktop app that accesses network resources. For instance, importing fonts via the `customFonts` and `fontCss` configuration attributes happily imports fonts from public URLs. This functionality also exists in the GUI. The client also includes a "From Template URL" button in the new diagram dialog that specifically imports from a network resource.

**Comment by davidjgraph** [comment]
We have a CSP that controls access to specific domains. This would require all controls to be removed, we can't do that.
