### ISSUE TITLE
latest-mac.yml contains wrong sha512 codes

### ISSUE THREAD

**Issue by computeristic** [jgraph/drawio-desktop#236]
Hello everyone, this is my first time contributing so I'm not sure if this is the right place to post this issue. However, when I wanted to update draw.io desktop (mac) to v12.6.5 the .dmg sha512 provided in the latest-mac.yaml did not match that of the dmg file downloaded. Thank you for your work!

**Comment by ashrafteleb** [comment]
Is this still an issue with newer versions?
