### ISSUE TITLE
Only single (color, font size, etc.) within a given List?

### ISSUE THREAD

**Issue by TRSx80** [jgraph/drawio-desktop#237]
First off I must express my gratitude not only for your work on this tool, but especially for sharing it under an open license like civilized human beings. I have been looking for some sort of easy to grasp diagramming tool for literally years, so that I could focus on iterating my ideas instead of learning the tool. I have tried several, but found them all either wanting or clunky in some way or other. Finally, I stumbled across your tool and I have been thoroughly enjoying using it, it is the first time I actually produced anything useful (without investing an inordinate amount of time learning the tool) in literally years. I cannot thank you enough for this, and I have already been touting it's virtues to anyone who will stand still long enough. :smile: :beers: 

I did run across one minor niggle however, and after looking around a bit, could not seem to find anything about it, so I thought I would contact you.

I seem to be able to get multiple differently formatted (color, size, etc.) sections of text within a single Textbox (General -> Textbox), however not within a single List item (Advanced -> List). If I try to make a few words red for instance, it seems to work at first, but as soon as I de-select the text in the List box, everything within the whole box turns red.

I wasn't sure if this was a bug or a feature?

**Comment by ashrafteleb** [comment]
Yes, in order to have formatted text inside the list item, please add "html=1" to the cell style

For example, `text;strokeColor=none;fillColor=none;align=left;verticalAlign=top;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;` should be `text;strokeColor=none;fillColor=none;align=left;verticalAlign=top;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;html=1;`

**Comment by TRSx80** [comment]
OK, so then I assume I can do HTML formatting inside... Thanks! That should work!

I have yet to try this, but thank you for the information!

I wish I could again find reference to where I first heard the concept of essentially constantly doing a con job on yourself by always having so many projects going that no matter what you are working on, it is never what you are "supposed" to be working on at any given time, and thus you always stay busy working on "something" by semi-consciously tricking/deluding yourself... Anyway, yeah that's me, I adopted that method years ago and it works for me (YMMV). :smile:

Point being, I have not circled back to this yet in order to try it, but I suppose it sounds like it will work, now that I realize it's a supported feature... So I will close for now. If it doesn't work, I will re-open again later. Thanks again!

Cheers! :beers:
