### ISSUE TITLE
Pixellari custom font doesn't render in desktop 12.6.5 Win 10 Pro

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio-desktop#238]
Tested with Pixellari font. https://www.dafont.com/pixellari.font?text=TESTING&back=bitmap 

When font is installed, I chose Pixellari in "Custom", but nothing changed i.e the font remained Times New Roman.
Font can be changed to Pixellari in Paint and MS Word on line.  

A chat user reported this. He uses Win8.1 Pro x64

P.S it also failed in diagrams.net online (Chrome Version 80.0.3987.149 (Official Build) (64-bit)
and Chrome Incognito) 

![custom](https://user-images.githubusercontent.com/44292306/77757130-ecb13900-7030-11ea-9494-5d6bbb396400.PNG)
![paint](https://user-images.githubusercontent.com/44292306/77757141-f0dd5680-7030-11ea-8d71-03ef27f3afb4.PNG)
![word online](https://user-images.githubusercontent.com/44292306/77757143-f33fb080-7030-11ea-915f-31c5f91d7951.PNG)

**Comment by ashrafteleb** [comment]
I couldn't reproduce. Can you please confirm using Custom -> System Fonts (Pixellari) with capital letter?

**Comment by mararad** [comment]
All is working well now in diagrams.net online (12.9.9) and desktop app (12.9.3) in Win10 Pro
