### ISSUE TITLE
Support Copy PNG/SVG/.. to clipboard

### ISSUE THREAD

**Issue by myloginid** [jgraph/drawio-desktop#240]
Lot of times, we dont really want the images to be stored on the machine, just need to copy it to docs/excel/emails etc. It would help to have a copy image to clipboard option in this menu and a shortcut for it.

![image](https://user-images.githubusercontent.com/2422057/77845621-e95daf00-71e2-11ea-9595-ce28183e8422.png)

Currently when you do a ctrl+A & copy paste, it pastes the raw xml.

**Comment by ashrafteleb** [comment]
We have "Copy as Image" for the selected cells (you can select all to export the entire diagram). This new menu item is in the Edit and context menu

**Comment by gardner** [comment]
This works. The main difference is that one cannot specify a border.

**Comment by ozanaki** [comment]
Maybe there can be an "export to clipboard" option in the export options window. Thus, exporting to clipboard as any format and with any choices can be possible. When the "Export to clipboard" checkbox is selected, the drawing is just export to the clipboard with the selected file format and all desired choices without saving a file and asking for a filename. This may very practical for using drawings in any other applications by export/paste without saving every exported drawing part.
