### ISSUE TITLE
Update to version 12.9.3 broke folder memory on Mac

### ISSUE THREAD

**Issue by ashrafteleb** [jgraph/drawio-desktop#242]
Today’s update to version 12.9.3 for the downloadable Mac application broke the folder memory in the app.

Previously, when I opened a draw.io file from a particular folder on my Mac, it remembered the location of the file in that folder, and functions like “Save As…” would automatically show that folder so that I didn’t have to search for it, again. Now, when I open a file from a particular folder and click “Save As…,” the pop-up folder selection window takes me to my default “Documents” folder, and I have to search for the file every time.

**Comment by kfoerderer** [comment]
Same on Windows 10

**Comment by stigra** [comment]
Working folder resets to My Documents on Windows 10 using 12.9.3 on every file operation as well.

**Comment by ashrafteleb** [comment]
Fixed, will be available in the next release
