### ISSUE TITLE
Cannot exporting a diagram to pdf or png when mathematical typesetting is enabled (version 12.9.3)

### ISSUE THREAD

**Issue by ashrafteleb** [jgraph/drawio-desktop#243]
After upgraded to the version 12.9.3, I cannot exporting a diagram to pdf or png when mathematical typesetting is enabled. I am using Ubuntun 18.04. I have tried deb installation and snap installation, the same behavior. The screen is stuck on a rolling wheel. Any hint?

**Comment by greoff** [comment]
I am also experiencing this issue when running version 13.0.3 on Windows 10. Bug is present on both the desktop and web version.

**Comment by ashrafteleb** [comment]
@greoff I've just tested on windows and I couldn't reproduce, please share the file with that issue or steps to reproduce.
Thanks

**Comment by greoff** [comment]
OK. Here are two files from two seperate versions. The PDF created in 13.0.3 becomes skewed and the text is not markable. A PDF of the same diagram generated with 12.5.3 works as expected.

[
[13.0.3.pdf](https://github.com/jgraph/drawio-desktop/files/4561492/13.0.3.pdf)
[12.5.3.pdf](https://github.com/jgraph/drawio-desktop/files/4561493/12.5.3.pdf)
](url)

**Comment by davidjgraph** [comment]
That doesn't relate to the original issue, please open another issue for different problems.

**Comment by ashrafteleb** [comment]
Closed as we cannot reproduce
