### ISSUE TITLE
Opening multiple files from explorer (Win10, 12.9.3)

### ISSUE THREAD

**Issue by kfoerderer** [jgraph/drawio-desktop#244]
When a file is opened from the explorer in Windows 10, draw.io starts in a new window and loads the file. However, this works only once since the update. As long as another draw.io instance is running, the newly started draw.io instances will default to an empty and untitled document. Apart from that, the new instance works as expected.

**Comment by ashrafteleb** [comment]
Fixed, will be available in the next release
