### ISSUE TITLE
"Image too big" when trying to import an image

### ISSUE THREAD

**Issue by narczi** [jgraph/drawio-desktop#247]
**Is your feature request related to a problem? Please describe.**
**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**
I'm always frustrated when I want to import an image only to be met with "IMAGE TOO BIG" error. It seems like the limit is tiny, I can import images that are 200kbs or less. 
**Describe the solution you'd like**
**A clear and concise description of what you want to happen.**
Allow users to set the image size limit themselves or up the limit to something reasonable like 5mb.
**Describe alternatives you've considered**
**A clear and concise description of any alternative solutions or features you've considered.**
Compressing a JPEG with 0 quality just so I can import it.
**Additional context**
**Add any other context or screenshots about the feature request here.**
Screenshot attached.
![image_too_big](https://user-images.githubusercontent.com/25054997/78130418-902b9080-7419-11ea-8ee5-fe8282e1b008.png)

**Comment by torse** [comment]
Can confirm that error in version 13.7.3 (desktop linux). I am not able to import an image with 1200x900 pixels! Importing with the "resize" option make the image unreadable.

Can the size limit be increased in the configuration?
