### ISSUE TITLE
Desktop app don't save

### ISSUE THREAD

**Issue by stonewoodman** [jgraph/drawio-desktop#250]
I installed the desktop app.
I opened a existing diagram and modified it. After I want to save the diagram, the changes are not saved. Except, I choose "save as..." and save as a new file, then the diagram was saved. Only this works.
But when I choose "save as..." and save the diagram into the existing file, it won't work.

OS: Windows 10 (1909)
App: 12.9.3

**Comment by diegopau** [comment]
I lost a great deal of work due to this problem. 12.9.3, windows 10
I was constantly seeing "saving..." and then "all changes saved" so I thought it was fine. Today i opened the file and most of the work disappeared, I believe only what I had saved when I did "save as..." was saved. However today i did a quick test and seems to work, so it seems to not always file.

Another related thing I noticed is that when you click on Save as it doesn't propose to save the file as .drawio, instead you write a name and it saves a file without extension. FInally it would make sense that when you open the app it would open the last edited file or at least make it easy to load it, instead it offers "Open Existing Diagram" that never remembers the last used folder.

**Comment by cxobeckyklein** [comment]
My documents, whether they're edited/created in the app are saved with the draw.io extension but the icon looks like .pdf, but it doesn't open in acrobat or draw.io with a double click. I can only open them from within the program. When I do so, it opens it in the browser.

Very confusing.
[Curation Swimlane 2.0.zip](https://github.com/jgraph/drawio-desktop/files/4440530/Curation.Swimlane.2.0.zip)

**Comment by ckhall** [comment]
seeing the same thing after installing update on MacOS Catalina 10.15.3.  Changed the theme back to the Kennedy (was using Atlas).  Was able to create a new diagram and saving now works.  Maybe theme related?

**Comment by davidjgraph** [comment]
@diegopau The extension issue we'll fix.

**Comment by davidjgraph** [comment]
@cxobeckyklein The association for .drawio works correctly for me using 12.9.3. I don't think you have the same problem reported in this thread. Please open a new issue.

**Comment by davidjgraph** [comment]
Could someone record a video please? I cannot repeat this using 12.9.3 on Mac 10.15.3.

**Comment by cxobeckyklein** [comment]
![Opening drawio file](https://user-images.githubusercontent.com/57460182/78842905-292c4f80-79b6-11ea-8946-89323ab44a82.gif)

**Comment by cxobeckyklein** [comment]
![Opening from web](https://user-images.githubusercontent.com/57460182/78843290-3e55ae00-79b7-11ea-807c-a5ec067aa5ac.gif)

**Comment by davidjgraph** [comment]
@cxobeckyklein Your issue is not the one this thread is discussing, please open a different issue.

**Comment by harryhobson** [comment]
OS: Fedora 31 (64bit)
Version: 12.9.3 (flathub)
Similar issue here, but was not using a theme. I see the 'Saving...' text next to the Help button, but *.drawio file did not save. Only occurs intermittently.  Thankfully I received the prompt 'there are unsaved changes, do you want to discard?' which made me realise the save feature was not working.

I first tried to export the file as a different format - XML. This did not appear to work (created an empty file with 0kb). Following this I tried to export as vsdx. I then received an error that the XML file failed to save (did not exist). I re-attempted the XML save, this time it worked. I gather than XML is very similar to .drawio so I was able to open the XML file and save back to .drawio

Hopefully the above helps someone not lose their work.

**Comment by davidjgraph** [comment]
Assuming this is fixed with the draft handling we added. If anyone see it in latest we'll reopen.

**Comment by JanaranjaniPalaniswamy** [comment]
I am facing the issue again. When I tried to save the work. It shows "error saving the file"

**Comment by davidjgraph** [comment]
@JanaranjaniPalaniswamy Could you open a new ticket with version details and exact description of what you see please?

**Comment by Hygens** [comment]
I have problems on manjaro linux same problem yesterday no save diagrams and lost all work.

**Comment by davidjgraph** [comment]
@Hygens That's not the same issue as this one, please create a new issue.
