### ISSUE TITLE
Width and Height are not exact through CLI

### ISSUE THREAD

**Issue by Modelmat** [jgraph/drawio-desktop#254]
Running the command `/opt/draw.io/drawio --export --width 100 --output box.png box.drawio` on the attached box.drawio file creates a PNG of width 103.
A similar case occurs with a height of 100, which does not create a box of height 100.

attachments:
[box.drawio.txt](https://github.com/jgraph/drawio-desktop/files/4444148/box.drawio.txt)
[box.png](https://user-images.githubusercontent.com/25718989/78668625-54636000-791e-11ea-898d-00f376b76934.png)

**Comment by ashrafteleb** [comment]
Fixed, will be available in the next release
