### ISSUE TITLE
Differences between the Windows files to download

### ISSUE THREAD

**Issue by vivadavid** [jgraph/drawio-desktop#255]
Hello,

I'm writing this message because I use Windows, there are four different files that I could, in theory download, and I'm not sure if I understand the difference between them.

Since it's highlighted before the changelog of every version, I'm inclined to think that I should just download the windows installer (If I want to install the programme) or the Windows no installer (if I need a portable version, though I'm a bit confused about why this isn't called _portable version_).

Then, there is a ZIP file (which seems to be code) and, finally, there's an EXE file (currently draw.io-12.9.9.exe), which seems to be a portable version, but since there's Windows no installer, I don't know why it's there.

I apologize in advance if I'm asking something obvious, but I couldn't find the information.

**Comment by davidjgraph** [comment]
The links at the top of the release notes are there to point you at the two suggested windows binaries.

The zip is automatically generated as a zip of the tagged source version and the draw.io-12.9.9.exe file is update file for existing users.

**Comment by vivadavid** [comment]
Thank you, @davidjgraph 

I took into account the links, but I was curious about the other options. Thanks!
