### ISSUE TITLE
Bug: Fully working mathematical typesetting

### ISSUE THREAD

**Issue by adnion** [jgraph/drawio-desktop#26]
This article says the feature is not available in the apps: https://desk.draw.io/support/solutions/articles/16000032875

But it is available and it does work. The problem is as soon as mathematical typesetting is enabled I am no longer able to print the diagram using File > Print. The printing dialog of the OS (Linux) does not open anymore. Tested with latest 8.4.7 and appimage version.

**Comment by davidjgraph** [comment]
We'll may still have to remove it, there are a number of problems having it in the Desktop version. We'll address the issue if we manage to keep it.

**Comment by wwfung** [comment]
It appears that the Desktop version cannot render the math typsetting...

![image](https://user-images.githubusercontent.com/38495514/58325216-a06afa80-7e5b-11e9-8d64-a58eccaa7b9a.png)

**Comment by davidjgraph** [comment]
Does it work if you export to PDF then print?
