### ISSUE TITLE
Snap on Ubuntu creates a file named '--no-sandbox' at each startup

### ISSUE THREAD

**Issue by dlecan** [jgraph/drawio-desktop#260]
Using Drawio snap 12.9.9 on Ubuntu 18.04

When I open the snap from the app launcher, a new file named `--no-sandbox` located in `~/` is created.

This shouldn't be created, or not in this folder.

Thank you

**Comment by davidjgraph** [comment]
Should be a fix for this in tonight's release. Nag me tomorrow if not.
