### ISSUE TITLE
Option to Change Installation Location

### ISSUE THREAD

**Issue by ThomasOwens** [jgraph/drawio-desktop#261]
The installation process should include a step to choose the location where the desktop application should be installed.

My current computer has two drives - a smaller SSD and a much larger HDD. The OS and most critical applications are on the SSD while other applications are on the HDD. Fortunately, this is a relatively small application and doesn't take up too much room on the SSD. I do believe that it's generally a good practice to prompt users where the application should be installed, though.

**Comment by ashrafteleb** [comment]
I assume this is related to Windows version. The option for choosing installation folder will be available in the next release
