### ISSUE TITLE
[Math Processing Error] on export

### ISSUE THREAD

**Issue by Chritzel** [jgraph/drawio-desktop#262]
Hi all,

first of all, thanks for this amazing product!

I was using the draw.io-Desktop-Version without problems so far. Since today however, every time I export a drawing with Mathematical Typesetting, I get "[Math Processing Error]" all over the place in the produced file. This happens both for PDF and PNG. The preview in the application still works as expected, and I can also successfully export these drawings from the online version. I assume this has something to do with MathJax.

This is the result of a document with a text field of "$$a^2+b^2=c^2$$". I attached the document below.

![math_test](https://user-images.githubusercontent.com/16166683/79844807-764bf080-83bc-11ea-896c-e2a028725822.png)

[math_test.txt](https://github.com/jgraph/drawio-desktop/files/4508760/math_test.txt)

System details:
Ubuntu 16.04
tried drawio-desktop 12.6.5 and 12.9.13
Browser when using the web-version: Firefox 75.0

Let me know if you need any more information.

**Comment by jj0mst** [comment]
Same here.

The online version gives this error also in the preview if using Chrome.

I was able to correctly export to PDF using Firefox, where everything seems fine instead.

**Comment by davidjgraph** [comment]
Please try the 13.0.0 RC from https://github.com/jgraph/drawio-desktop/releases/tag/v13.0.0 to see if that fixes it.

**Comment by joaohis** [comment]
I had the same problem exporting a diagram today. The problem seems to have been fixed with the 13.0.0 RC, for both PDF and PNG.

**Comment by davidjgraph** [comment]
Fixed in 13.0.1
