### ISSUE TITLE
Desktop App does not start any longer

### ISSUE THREAD

**Issue by Ch-Fr** [jgraph/drawio-desktop#263]
I had installed the Desktop App (windows-no-installer, Version 12.9.3) which worked flawlessly until some day I got an update notification (Version 12.9.13) and updated it. After a while I found out I was installer version.

So I uninstalled the Desktop App again. Now the windows-no-installer application does not start any longer. After double-clicking the executable the blue circle appears (and I see a task in task manager) but after some time the task is gone and no window appears.

How can I get the windows-no-installer Desktop-App to work again?

Thanks!

**Comment by davidjgraph** [comment]
Might be a problem calling the certificate checking server, could you try again with 13.0.1?

**Comment by Ch-Fr** [comment]
Thanks for your feedback and your support. I already tried the new version, but without success. The strange thing is, that starting the app works with a different user (new) user profile (Windows 10). 

First guess was that during the installation something was written into the registry, the user's local app temp folder or something alike that now prevents the app from starting.

I also tried [Sysinternals Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) but the results were too much for me to analyse.

**Comment by Ch-Fr** [comment]
My guess was sort of right I think. I had everything from draw.io deleted out of the Windows 10 %appdata% folder. After the next start I saw Windows Defender SmartScreen come up and ask me if really wanted to start the app. Said yes and that's it. Hope this helps ...

**Comment by davidjgraph** [comment]
OK, I'll leave it up as helped wanted. I'm not a windows user, maybe someone who is knows more.

**Comment by Ch-Fr** [comment]
No, I don't need further help, thanks!. What I tried in fact fixed the problem. Just wanted to make people running into the same situation aware of my solution.

**Comment by davidjgraph** [comment]
Ah, OK, misunderstood. Thanks for taking the time to post your fix, most people don't...

**Comment by przemeqq** [comment]
I have same problem. Removed everything from %appdata%, reinstalled - still not working :(

**Comment by davidjgraph** [comment]
If you have a similar problem please open a new issue with full environment details.
