### ISSUE TITLE
Please Advise - Trying to Migrate from Crappy Lucidchart...

### ISSUE THREAD

**Issue by kfoody23** [jgraph/drawio-desktop#266]
My problem is that I have done a TON of work in Lucidchart but they keep raising prices, limiting abilities and marketing like freaking crazy to me! Drives me nuts!! 

I've probably got 200 documents and diagrams that I've created in Lucid and the best info I can find out so far is to open a doc, select all, copy and paste into a Diagrams.net doc - which doesn't ever translate the same way and I have to spend time cleaning it up anyways. 

I DO NOT have the time to do that for 200 documents. Anyone have a suggestion for me please?! Not a crazy techie, but I've got a tiny little ability I would say. 

Thanks so much - Ken

**Comment by davidjgraph** [comment]
We've a chrome extension for that you're welcome to test out.
