### ISSUE TITLE
File opening broken

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio-desktop#267]
I just updated Drawio. Now when I double click a .drawio file it launches the app but doesn't open the diagram. Instead I just see this:

<img width="506" alt="Screen Shot 2020-04-25 at 3 35 32 PM" src="https://user-images.githubusercontent.com/191903/80292287-6d378800-870a-11ea-9478-4f986df7ff39.png">

macOS Mojave 10.14.5
diagrams.net 13.0.1

**Comment by arshcaria** [comment]
Same here. 
Windows 10 build 18363
drawio version 13.0.1

**Comment by dg14** [comment]
same problem under linux. 
solved, with this modification to the .desktop file:

change 
Exec=/opt/draw.io/drawio %U
into 
Exec=/opt/draw.io/drawio '%U'
with single quotes.

**Comment by ashrafteleb** [comment]
Fixed, will be available in the next release
