### ISSUE TITLE
Custom Font - Font added under Google Fonts getting reset to System Fonts

### ISSUE THREAD

**Issue by dandgelb** [jgraph/drawio-desktop#268]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When a Google Font say `Quicksand` is added as a Custom Font for a Text, when draw.io  desktop application is opened with a new diagram - blank diagram in my case - the previously added Custom Font gets added to `Systems Fonts` in the configuration popup/modal. Which in effect makes it unavailable. 
The font and configuration work if the draw.io is started by opening the existing diagram which has the configured custom font used(even if it was applied to a text and the text is removed)

**To Reproduce**
1. Create a new diagram
2. Add a text element
3. Select the Custom Font Option to add the Google Font - `Quicksand`
4. Apply the added font to the text element
5. Save and Close draw.io
6. Open draw.io - create a new diagram - blank
7. Add a text element
8. Apply the previously added font - `Quicksand` to the text
9. Select the Custom Font Option
10. In the popup - `Quicksand` is under the `System Fonts` instead of `Google Fonts`

**Expected behavior**
Text font in 8, 9, 10 above should be `Quicksand`.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 13.0.1] - Desktop Application

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser - Not Applicable
 - Version - Not Applicable

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**
Reached here after following:
https://webapps.stackexchange.com/questions/93450/how-to-use-google-font-in-draw-io/141728#141728
https://github.com/jgraph/drawio/issues/577

**Comment by ashrafteleb** [comment]
It works but with a different steps (workaround). All previously used fonts are in the fonts drop-down menu. Click on the font name and it will be applied.
We will work on fixing the suggested font name in the custom dialog to fix this issue
<img width="237" alt="Screen Shot 2020-04-29 at 1 48 19 PM" src="https://user-images.githubusercontent.com/24944765/80629993-91081000-8a21-11ea-99dc-4c37aa75adb2.png">
<img width="368" alt="Screen Shot 2020-04-29 at 1 50 15 PM" src="https://user-images.githubusercontent.com/24944765/80630007-96655a80-8a21-11ea-9632-2dd46c24ffaa.png">
