### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by Marc-Macr** [jgraph/drawio-desktop#269]
Hello,

I've been using Draw.io for a couple years now but recently got a new laptop a Surface Pro x, and it no longer supports 64 bit programs. Is there a 32bit or an ARM version of draw.io for desktop?

**Comment by pcgeek86** [comment]
I'm also interested in ARM support. I have several Raspberry Pi 3 B+ devices, running Ubuntu Server Linux 64-bit. I'd like to use Docker to run Draw.io in a Linux container, so I can access it as a web application.
