### ISSUE TITLE
Not a diagram file

### ISSUE THREAD

**Issue by SanjayVyas** [jgraph/drawio-desktop#271]
Even since updating to v13.0.1, I have lost 2 drawing all of a sudden. After saving the file and opening them again, I got an error "Not a diagram file". When I open the file using another editor, I find it to be completely blank. I wonder what is causing this issue? I hope its not the new version of draw.io

**Comment by ashrafteleb** [comment]
What is the operating system? Any chance you have steps to reproduce?
Thanks

**Comment by SanjayVyas** [comment]
Catalina 15.0.4
I was using draw.io desktop in a webex session and suddenly lost 2 files, which became completely blank. This was after draw.io became suddenly slow and I was not even able to click on layers or draw any more. 

There are no steps to reproduce, as in middle of the demo the file vanished.

**Comment by SanjayVyas** [comment]
This also happened to a friend of mine using Mac and draw.io desktop 13.0.3.
After saving the file and reopening it, it said "Not a diagram file" and the contents of the file are blank. Hours of efforts wasted in one stroke

**Comment by davidjgraph** [comment]
We've added a draft file to counter this. The draft file writes and is confirmed before the main file writes. Once the main file writes and is confirmed, the draft file is deleted.

**Comment by john-blip** [comment]
I'm having this problem as well: I was editing a file in the draw.io desktop app, my computer froze and the diagram file is corrupted (it only contains blanks). I tried locating a 'draft' version of the file, but failed to find it. Where is it usually located?

**Comment by davidjgraph** [comment]
@john-blip What desktop version are you running?

**Comment by john-blip** [comment]
Thanks for your quick reply. The file was created (and corrupted) in v11.3.0, but I also tried loading it on another device with the most recent one (13.?). I also posted on the [Google support group](https://groups.google.com/forum/#!topic/drawio/iRkNpJwaJKA) with more details

**Comment by davidjgraph** [comment]
That version pre-dates the fix we mention above, unfortunately.

**Comment by john-blip** [comment]
I see, I was afraid it would... Well, lesson learnt on always keeping software up to date!
Do you perhaps have any other way I can recover my file?

**Comment by davidjgraph** [comment]
Not unless there was any versioning mechanism on your filesystem. Apologies for your wasted time.

**Comment by mpemburn** [comment]
Ran into the same issue today.  Using the example file (https://jgraph.github.io/drawio-integration/javascript.html), I dropped the SVG image into my test code, and it worked like a champ.  When I substituted the Base64 encoded part with my own encoded SVG file, it Draw.io reported "Not a diagram file".

The next thing I tried was to use the example, import my image, then save it.  I cut the resulting `img` out of the DOM, then pasted this into my code.  This worked.  After decoding the Base64 portion, I saw that it looked very different from my original SVG:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="521px"
     height="369px" viewBox="-0.5 -0.5 521 369"
     content="&lt;mxfile host=&quot;embed.diagrams.net&quot; modified=&quot;2021-01-26T22:24:57.009Z&quot; agent=&quot;5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36&quot; etag=&quot;76si1FBukvTN7HyBpFBu&quot; version=&quot;14.2.7&quot; type=&quot;embed&quot;&gt;&lt;diagram id=&quot;emYRSDDRkDP2Yd3EZy3r&quot; name=&quot;Page-1&quot;&gt;
```
...vs:
```
<svg height="2048" version="1.1" width="2896" xmlns="http://www.w3.org/2000/svg" id="temp" viewBox="214.99461364746094 0.0348576121032238 936.0107421875 661.9303588867188" xmlns:xlink="http://www.w3.org/1999/xlink">
```
Is there some way to properly encode an SVG for use in this context?

**Comment by mpemburn** [comment]
For anyone finding this thread: I figured out that the issue was that my original SVG, which was created by a different software package, was incompatible with draw.io.  What fixed this was to import my SVG into draw.io, then save it as a .svg .

**Comment by cvmiranda13** [comment]
Is there a solution for the not diagram file? Encountered this one now, and badly need to open my file.

**Comment by jamajamajaaama** [comment]
> For anyone finding this thread: I figured out that the issue was that my original SVG, which was created by a different software package, was incompatible with draw.io. What fixed this was to import my SVG into draw.io, then save it as a .svg .

No, it does not help. I exported my diagram from app.creately.com  as SVG, then the Import to Draw.io creates svg as an image. When Openning exportet SVG, it responds with "Not a diagram file"

**Comment by Masha2404** [comment]
People, help! I can not open my file, "Error loading file. Not a diagram file (error on line 1 at column 6291449: Extra content at the end of the document)" error appears, I do need to open it. Do you have any ideas how i can do it?

**Comment by JenyLombana** [comment]
Tengo el mismo problema estaba trabajando en la web en diagramas.net y se bloqueo mi computadora al intentar abrir nuevamente mi archivo me sale 
Error loading file
Not a diagram file

 hay alguna manera de recuperar lo por favor necesito ayudaa

![image](https://user-images.githubusercontent.com/87394437/125523070-e30c2a10-d0aa-40cf-9038-b09c3dab28ba.png)
