### ISSUE TITLE
version 13.0.1 cannot open a file by double clicking it

### ISSUE THREAD

**Issue by henry63** [jgraph/drawio-desktop#272]
version 13.0.1 macos cannot open a file by double clicking it

**Comment by davidjgraph** [comment]
Fixed in https://github.com/jgraph/drawio-desktop/releases/tag/v13.0.3

**Comment by gc-robotics** [comment]
I have the same problem on v14.5.1 on Ubuntu 20.04. 
DrawIO set as default app for .drawio files but when one asset is double clicked, I get the new/open dialog instead of my selected drawing.

**Comment by davidjgraph** [comment]
That is a different issue, this one relates to MacOS. Please open another ticket.
