### ISSUE TITLE
Uncaught TypeError: this.getFilename is not a function, when trying to add shapes to custom libraries

### ISSUE THREAD

**Issue by SanjayVyas** [jgraph/drawio-desktop#274]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Trying to add a shape to custom library in draw.io desktop v12.9.13 results in an error "Uncaught TypeError: this.getFilename is not a function"

**To Reproduce**
1. Open a new drawing (File>New)
2. Create a new library (File > New Library..)
3. Create a shape and select it
4. Add to new library by clicking on "+"
5. Save the library
6. Save the file
7. Exit draw.io desktop
8. Run draw.io desktop
9. Add another shape to drawing and select it
10. Add to the custom library by clicking on "+"

Results in an error
Uncaught TypeError: this.getFilename is not a function

**Expected behavior**
Shapes should get added to custom library even after draw.io is restarted.

**Screenshots**
![image](https://user-images.githubusercontent.com/1856233/79698956-def67880-82a9-11ea-8417-c2c83fbe056b.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 12.9.13 (edited from earlier typo)

**Desktop (please complete the following information):**
 - macOS Catalina 10.15.4
 - Using draw.io desktop

**Smartphone (please complete the following information):**
 - Not using smartphone

**Additional context**
- This seems to happen only on desktop version and not web version
- The standard "scratchpad" is unaffected, only custom lib, after saving once and reloading the desktop app start giving the error

**Comment by davidjgraph** [comment]
Fixed in https://github.com/jgraph/drawio-desktop/releases/tag/v13.0.3

**Comment by SanjayVyas** [comment]
Thank you so much... I can confirm that this has been fixed in 13.0.3 👍

**Comment by stevenilsen123** [comment]
Fixed for me too! Thanks!
