### ISSUE TITLE
Unable to load .drawio files from file manager on MAC

### ISSUE THREAD

**Issue by phoneline99** [jgraph/drawio-desktop#275]
Just updated the offline Mac version of drawio.  Now using 13.0.1.

When I try to open a .drawio file from file manager (actually from a sync folder from box), draw.io app starts but no files are opened.  It just sits at the screen asking for New or open an existing.  I can open an existing.

Thanks.
Rene

**Comment by davidjgraph** [comment]
Fixed in 13.0.3
