### ISSUE TITLE
Snap distribution crashes when interaction with file-system 

### ISSUE THREAD

**Issue by AGrzes** [jgraph/drawio-desktop#279]
The program crashes when trying to open or save file, with error:

    Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/drawio/29/data-dir/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
    Aborted (core dumped)

Version 13.0.3 package type snap system Ubuntu 20.04

**Comment by PaulWotruba** [comment]
Same problem here, I noticed that when you start it with `sudo snap run drawio` it works just fine, but that is no permanent solution.

**Comment by ashrafteleb** [comment]
I cannot reproduce with v13.6.2 on 20.04.1 LTS. Is this issue still affect anyone?

**Comment by brennerm** [comment]
Can reproduce the issue with version v13.7.9 running on Ubuntu 20.04.
```
(drawio:42218): Gtk-WARNING **: 21:50:49.267: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/drawio/60/data-dir/icons/Yaru/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
[1]    42218 abort (core dumped)  snap run drawio
```

**Comment by romanprocopie** [comment]
Hi all

Related to the above, but slightly different root cause
Kubunu 20.10, DrawIO snap distro, v 14.5.1 crashes on file open with

Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/drawio/105/data-dir/icons/Adwaita/16x16/status/image-missing.png: Unable to load image-loading module: /snap/drawio/103/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/drawio/103/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)

/snap/drawio contains only 105 and 104.
I was able to make it wok by fooling it with : "sudo ln -s /snap/drawio/current /snap/drawio/103"
but that is obviously only a workaround

**Comment by davidjgraph** [comment]
We've never been able to recreate this.

**Comment by wdoekes** [comment]
Perhaps this?

https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/159

I'm running into this right now on Ubuntu/Jammy.

Running the loader outside the snap yields lots of nice output:
```console
$ /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders
# GdkPixbuf Image Loader Modules file
# Automatically generated file, do not edit
# Created by gdk-pixbuf-query-loaders from gdk-pixbuf-2.42.8
#
# LoaderDir = /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders
#
"/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/io-wmf.so"
"wmf" 0 "gdk-pixbuf" "Windows Metafile" ""
"image/x-wmf" ""
"wmf" "apm" ""
"\327\315\306\232" "" 100
"\001" "" 100

"/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ani.so"
"ani" 4 "gdk-pixbuf" "Windows animated cursor" "LGPL"
"application/x-navi-animation" ""
"ani" ""
"RIFF    ACON" "    xxxx    " 100

...
```
Running inside the confinements of snap (`sudo nsenter -at SNAPPID bash`):
```console
# /snap/drawio/159/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders
# GdkPixbuf Image Loader Modules file
# Automatically generated file, do not edit
# Created by gdk-pixbuf-query-loaders from gdk-pixbuf-2.36.11
#
# LoaderDir = /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders
#

```
(A void document.)

I suspect that might have something to do with things.

I hate snap so much :weary:

**Comment by wdoekes** [comment]
Here's some more attempts at unbreaking this stuff:
```
# cat >> /etc/ld.so.conf.d/snap-gnome.conf
/snap/gnome-3-38-2004/112/usr/lib/x86_64-linux-gnu
```
```
# ldconfig
```
```
# GDK_PIXBUF_MODULEDIR=/snap/gnome-3-38-2004/112/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders /snap/drawio/159/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders
/snap/drawio/159/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /snap/gnome-3-38-2004/112/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0)
```
```
# ls -l /lib/x86_64-linux-gnu/libc.so.6
lrwxrwxrwx 1 root root 12 Jan 24 13:53 /lib/x86_64-linux-gnu/libc.so.6 -> libc-2.27.so
```
Ha ha ha. (Slow sarcastic laughter.)

Alas. The bundled gnome-3-38-2004 libglib-2.0.so.0 is not compatible with the bundled libc6.

Luckily there is the EDIT DIAGRAM so I can salvage my work.

`apt-get remove --purge-with-fire snap`

**Comment by sguillia** [comment]
@wdoekes How did you salvage your work in such a case?

I lost mine because of this, didn't find a way to salvage

Reproduces on drawio snap 22.0.2 2023-10-05 (id 84JReQ8pcNGJyAbT0gSDiW7OpDkrdaXp latest/stable)

`sudo snap run drawio` is not a work-around as it throws `mkdir: cannot create directory '/run/user/0': Permission denied`

stdout/stderr when running drawio and clicking "Open an existing diagram":

```
(drawio:549709): Gtk-WARNING **: 02:09:41.554: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/drawio/190/gnome-platform/usr/share/icons/Humanity/status/16/image-missing.svg: Unable to load image-loading module: /snap/drawio/168/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /snap/drawio/168/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
[1]    549709 abort (core dumped)  drawio
```

**Comment by wdoekes** [comment]
> How did you salvage your work in such a case?

I could start Drawio and it would still have the current diagram. From there I could click Edit to edit the SVG. And then copy the SVG to use elsewhere (outside of snap).

I'm sorry to hear that your work is gone.

Ultimate resolution: use Drawio from a .deb instead.
```
$ dpkg -l | grep -E 'draw.io|snap'
ii  draw.io                                    20.2.3                                      amd64        
ii  gir1.2-snapd-1:amd64                       1.60-0ubuntu1                               amd64        Typelib file for libsnapd-glib1
ii  libsnapd-glib1:amd64                       1.60-0ubuntu1                               amd64        GLib snapd library
ii  libsnappy1v5:amd64                         1.1.8-1build3                               amd64        fast compression/decompression library
ii  nosnap                                     0.1                                         all          Package to resolve Linux Mint firefox dependency
```
