### ISSUE TITLE
Unable to export PDF

### ISSUE THREAD

**Issue by ZichaoHuang** [jgraph/drawio-desktop#28]
The PDF exported from both macOS 10.13.4 and Windows 10 draw.io desktop app is always damaged.

**Comment by alderg** [comment]
What version number do you see in Help, About? (If earlier than 8.5.8, please open the app while online, give it a minute or two to update, restart and try exporting to PDF again.)

**Comment by ZichaoHuang** [comment]
The version number is v8.5.8 in Help-About draw.io

**Comment by alderg** [comment]
This works for me. @ZichaoHuang Could you attach the diagram that you are trying to export, please?

**Comment by ZichaoHuang** [comment]
I have been trying to export many of my diagrams but none of them works.
For testing, I start a new diagram containing only a single circle and try to export a PDF from it, but the exported PDF is also damaged.

**Comment by alderg** [comment]
Ah yes, we are able to reproce this now. Thanks for the report, we'll try and fix it ASAP.

**Comment by alderg** [comment]
Fixed. Thanks for the report!
