### ISSUE TITLE
Upgrading from 12.9.9 to 13.0.3 - Now requires Administrator privileges

### ISSUE THREAD

**Issue by dubasdey** [jgraph/drawio-desktop#280]
New version 13.0.3 requires Administrator privileges to run the installer. This blocks the install or 
update if the user with 12.9.9 installed has not administrator privileges when installed the package.

**Comment by davidjgraph** [comment]
The installer always required admin rights. What exact environment, versions, steps and results are you reporting?

**Comment by dubasdey** [comment]
- Windows 10 N 1909 in a Domain.
- User without Administrator privileges

Previous:
- Installer 12.9.9 executes and installs.
- no-installer 12.9.9 runs correctly

Current:
- Installer & no-installer 13.0.3 shows a UAC dialog requesting an administrator account. 
- The icon of 13.0.3 version shows the UAC shield

We investigated that is a change in our policy set that limits the privileged application installs in a recent policy update. Only applications that doesn't force to use elevation could be installed. Other applications without that requirement are installed without problems

It would be great if the application will not require the use of administrator privileges to be installed for the local user.

**Comment by davidjgraph** [comment]
If https://github.com/jgraph/drawio-desktop/issues/295 is true that's likely the cause.
