### ISSUE TITLE
Web does VSD import but desktop doesn't?

### ISSUE THREAD

**Issue by robhagopian** [jgraph/drawio-desktop#281]
I seem to be able to import .vsd files online at draw.io but I downloaded the desktop program and it only appears to import .vsdx files?

**Comment by davidjgraph** [comment]
https://desk.draw.io/support/solutions/articles/16000096984-why-can-i-not-import-vsd-files-in-the-desktop-version

**Comment by robhagopian** [comment]
Ah! Sorry I didn't locate that before opening this bug. Thank you!
