### ISSUE TITLE
Make matched node stand out more when doing a search

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio-desktop#283]
This screenshot shows me doing a Find for the query "emotion". It's very hard to see the matching node in the graph. If the node turned bright yellow or something that would be helpful.

<img width="1529" alt="Screen Shot 2020-05-08 at 12 25 59 PM" src="https://user-images.githubusercontent.com/191903/81441744-280e4f80-9127-11ea-92bc-d65bdcdc61f5.png">

**Comment by ashrafteleb** [comment]
Cannot reproduce. Matched node is selected and view is changed to make the node visible
Can you share the file and steps to reproduce.

**Comment by JesseAldridge** [comment]
If you look very closely you can see the selected node is the one in that top-right that reads "emotional". This is an edge case where the indicator icon is not visible because the node is near the right edge of the viewport.

It's also not such a big deal to me anymore because I don't have black borders on every anymore, which makes the blue dashed line easier to see.

**Comment by ashrafteleb** [comment]
OK, thanks. I'd close then.
