### ISSUE TITLE
Hanging for a few seconds with large images

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio-desktop#284]
If I put several images in a .drawio document the program tends to get slow. Especially when I do things like switching from one diagram tab to another. It doesn't always happen, but it happens pretty frequently. If I restart Drawio the problem goes away for a while but then comes back. 

Sounds like a memory leak, maybe? But my Activity Monitor doesn't show a large amount of memory being consumed.

I generally have to resort to using Figma to produce documents with many images. Figma somehow manages to handle tons of large images with no problem.

macOS Catalina
Drawio Desktop 13.0.3

**Comment by davidjgraph** [comment]
We think we've found this one in the 13.5.7 release.
