### ISSUE TITLE
opening *.drawio by default software is blank.

### ISSUE THREAD

**Issue by jiangqii** [jgraph/drawio-desktop#287]
drawio version:diagrams.net 13.0.3
os:deepin v20
kernel:4.19.0-6-amd64

When I open the *. Drawio file through the default program of deepin, it is blank after opening. 
![image](https://user-images.githubusercontent.com/45223669/81882328-131d3a80-95c5-11ea-9ade-390c39514ec0.png)

But by opening the existing document, that is, the saved file at that time, there is information in it.

![image](https://user-images.githubusercontent.com/45223669/81882367-28926480-95c5-11ea-8b8e-0691437216f9.png)

I don't know if it's a system or a software question.Maybe it is not issue.

**Comment by davidjgraph** [comment]
We're not going to install this OS to test, but I'll leave it open in case someone else wants to look.
