### ISSUE TITLE
"Copy as image" makes Image whose background color is black [Windows]

### ISSUE THREAD

**Issue by nkawakatsu** [jgraph/drawio-desktop#289]
Thank you for developing a great tool for drawing graphs.
I found a problem with the "copy as image" operation.
First, use the draw.io desktop tool to create a graph consisting of two rectangles and one arrow connecting them. After selecting them all, operate "copy as image" from the menu. Then open another editing tool (eg MS Powerpoint) and paste it as an image.
Looking at the pasted image, the background other than the rectangle and the arrow is filled with black. I think this background color should be transparent or white.

testing environment:
OS: Windows10 pro x64
Version: diagrams.net 13.0.3

**Comment by mikiqex** [comment]
I elaborated the issue little more in #302 (which is closed as duplicate, I didn't find this issue before for some reason...)

**Comment by ashrafteleb** [comment]
This issue is specifically for Windows Only

https://stackoverflow.com/questions/51537634/how-to-write-transparent-image-to-clipboard-in-electron

If someone want to help for porting this code to JS (PNG to DIB format) + using clipboard.writeBuffer(format, buffer[, type])
https://stackoverflow.com/questions/44177115/copying-from-and-to-clipboard-loses-image-transparency

**Comment by endo64** [comment]
I found a workaround for this issue,

1. Copy image from draw.io
2. Paste it into Paint.Net (https://www.getpaint.net/)
3. Press CTRL-C to copy on Paint.net, then paste into MS Office applications

This way image keeps the transparency.

**Comment by ondrejspilkaABB** [comment]
I believe the behavior might be preserved, good workaround would be  if diagram background is set to white, fill exported PNG with this background first.
No need to implement above suggestion, just fill the background first.

**Comment by fennibay** [comment]
I _believe_ the behavior was different before. When I tested after #195 was implemented, I don't remember seeing this black background problem. Sorry that I cannot offer definite information. Has something changed in the meantime?

**Comment by kevinctech** [comment]
I found this workaround that you can run after "copy as image" from draw.io It converts the clipboard DIB to PNG.
[https://github.com/skoshy/CopyTransparentImages](https://github.com/skoshy/CopyTransparentImages)

**Comment by mtausig** [comment]
> 
> 
> I _believe_ the behavior was different before. When I tested after #195 was implemented, I don't remember seeing this black background problem. Sorry that I cannot offer definite information. Has something changed in the meantime?

No. Problem still present in 14.1.8.

**Comment by fennibay** [comment]
I meant the problem wasn't there _before_. #195 was implemented on March 10th, 2020; and the release afterwards was [12.9.3](https://github.com/jgraph/drawio-desktop/releases/tag/v12.9.3). So I don't remember seeing this problem with that version.

Recent versions including 14.1.8 seem to have this problem.

**Comment by shineworld** [comment]
I'm used to creating a diagram with draw.io then "Copy as Image" in a LibreOffice document.
Is it a rapid way instead to export a single PNG and add it to LibreOffice as an external image.
Unfortunately, the direct copy of the clipboard content adds a black background in texts, etc.
Using Paint.net as a middle-man to paste/copy before pasting in LibreOffice seems the only way to resolve.
I'm using version 14.1.8 with W10.

**Comment by Petri-X** [comment]
Valid workaround on Windows is also: 
1. Remove the grid lines (if you like)
2. Take a area screen capture by the **Snip & Sketch** (or what is your preferable screen capture tool).
3. Done

But from the code point of view, isn't really an option to copy as the image and having background as it has been defined on the Diagram View

**Comment by OleBae** [comment]
Came across this is the Windows desktop app (14.5.1) copying to Word. When I instead used diagrams.net from Chrome 14.6.13 it worked fine. Upgrading the desktop app to 14.6.13 also fixed the problem.

**Comment by ChuckBryan** [comment]
One other idea...
Go to Page Setup
The Background was set to transparent. Changing this to white and then "copy as Image" and paste.
Should have a solid background color with no transparency

**Comment by xeno6696** [comment]
@ChuckBryan I've tried exactly this, and it doesn't work.

**Comment by xeno6696** [comment]
Oh weird... I tried it with a pale yellow and that failed, but it seems to work with straight-up white.

**Comment by MoSattler** [comment]
I have this issue in the web version when loading a file. anyone an idea?

**Comment by WiredWonder** [comment]
Was there a code change done to fix this issue? I am still seeing this problem on 26.0.9.

**Comment by alderg** [comment]
Works for me. What have you tried?

**Comment by WiredWonder** [comment]
Copy as image gives a black background behind shapes when pasting, unless the document has been set to white background.
