### ISSUE TITLE
Windows installer for release 13.0.3 is not signed

### ISSUE THREAD

**Issue by rhv-resideo** [jgraph/drawio-desktop#295]
The installer for this new version is not signed:
https://github.com/jgraph/drawio-desktop/releases/download/v13.0.3/draw.io-13.0.3-windows-installer.exe

This installer for this older version is signed:
https://github.com/jgraph/drawio-desktop/releases/download/v13.0.1/draw.io-13.0.1-windows-installer.exe

**Comment by davidjgraph** [comment]
Fixed in 13.2.2
