### ISSUE TITLE
Web Logos (Include Shapes library) wont export to svg

### ISSUE THREAD

**Issue by binarylandscapes** [jgraph/drawio-desktop#296]
Use a few of the included Web Logos shapes in my drawing like docker, Confluence, Jira Software and they work fine in desktop version and for jpg and png export but for svg export none of them seem to be able to be linked and I get empty squares

**Comment by binarylandscapes** [comment]
So is this not the proper repo for this issue? Not understanding why it was closed with no comment.

**Comment by davidjgraph** [comment]
It's not a complete report. Doesn't say how the project was accessed, what browser, what OS, what version of the project.

**Comment by davidjgraph** [comment]
No reproduction steps.

**Comment by binarylandscapes** [comment]
Apologies, you are correct. I create a new issue with the requested details.
