### ISSUE TITLE
Large amount of shapes from included Cloud & Enterprise shapes libraries) wont export to svg

### ISSUE THREAD

**Issue by binarylandscapes** [jgraph/drawio-desktop#297]
Using
- diagrams.net 13.0.3 Desktop Client (Windows)
- Windows 10 Business 2004 x64 19041.264

Reproduce issue
1. Create blank drawing
2. Load the following built-in Shape libraries Networking\ Cloud & Enterprise
3. Then drop shapes from these libraries CAE/Companies, CAE\Compue Service VM onto blank drawing (Seems to be a lot of the CAE)
4. File > Export to SVG with default settings
5. File > Export to PNG with default settings

PNG files show all graphics no issues while SVG export does not. Attached all files used in my reproduction.

[svgExportfail.zip](https://github.com/jgraph/drawio-desktop/files/4689939/svgExportfail.zip)

**Comment by ashrafteleb** [comment]
As a workaround, select "Embed Images"
<img width="403" alt="Screen Shot 2020-08-24 at 4 54 29 PM" src="https://user-images.githubusercontent.com/24944765/91095586-9faab080-e62a-11ea-8879-5b5535608b3d.png">
