### ISSUE TITLE
How/Where to set math-font to STIX-Web? How to set an URL parameter?

### ISSUE THREAD

**Issue by llvs** [jgraph/drawio-desktop#298]
Dear all,

[documentation here](https://desk.draw.io/support/solutions/articles/16000032875-how-to-use-mathematical-typesetting-) and [here](https://www.diagrams.net/doc/faq/supported-url-parameters.html) tells me to add the URL parameter math-font with value "STIX-Web" to get the STIX fonts as default math font.

Where do I have to put this URL parameter in the draw.io desktop version? 
I am using latest 13.0.3 which should support that feature. I have also installed the latest STIX 2.0.2 fonts package locally to the Windows fonts folder.

I tried to change the file `c:\Users\[username]\AppData\Roaming\draw.io\Preferences` according to the suggested parameter and I tried to add the parameter to `Extras-->Configuration`, which was completely empty initially. I then also inserted default JSON settings to the `Extras-->Configuration` lightbox from the Example section of [this FAQ page](https://desk.draw.io/support/solutions/articles/16000058316-configure-the-diagrams-net-and-draw-io-editor) and tried to add the math-font parameter there. 

Nothing helped and I fail to see where the draw.io desktop version stores its settings. I can't identify where the URL of the backend is called to add this URL parameter.

Best regards
llvs

**Comment by llvs** [comment]
This issue still persists with latest 13.3.1 on Windows. Where do I put the settings that the STIX-Web font is used in math mode?

**Comment by llvs** [comment]
I found that in the online version parameters are given in the form of
[https://app.diagrams.net/?math-output=html](https://app.diagrams.net/?math-output=html)
or
[https://app.diagrams.net/?math-font=STIX-Web](https://app.diagrams.net/?math-font=STIX-Web)
which uses the desired math font.

However, I tried calling the current (13.3.5) desktop version's draw.io.exe file with parameter 
`--math-font=STIX-Web`
 but this seems not the correct way to use the parameters, because the math font remains the same. 

How do I hand over a such a parameter to the desktop version?

**Comment by ashrafteleb** [comment]
In the next release, you can add url parameters using urlParams.json file in the working directory

**Comment by llvs** [comment]
Putting the following content into the file `c:\Program Files\draw.io\urlParams.json` seems to have the desired effect in version 13.7.3. Thank you!

> {
>	"math-font": "STIX-Web"
> }

I just write that comment as documentation how to use it, as people may come here through a google search.

**Comment by kqwyf** [comment]
Does anyone know where to put `urlParams.json` on Linux?

**Comment by gregwallan** [comment]
> Does anyone know where to put `urlParams.json` on Linux?

It goes in the user home directory: `/home/[user]`
Or at least I can confirm that works if you install via snap.
