### ISSUE TITLE
Hang when installing with Windows Installer

### ISSUE THREAD

**Issue by dunxd** [jgraph/drawio-desktop#300]
I still get a hang when installing using the 13.0.3 Windows Installer, whether I run it as Administrator or not. I am running Windows 10 Enterprise, with built in Defender Anti-virus.  When I run the installer the progress just stops about 1/3 of the way across and never progresses. I have to End Task from Task Manager.

I can run the no-installer, so I'm assuming I can just paste this into a folder Program Files to manually install, and there is just an issue with the installer running on my particular set up.  I don't know how to diagnose further, but with some guidance I would be happy to do some diagnostics.

**Comment by brenrich101** [comment]
Same here

**Comment by AranVinkItility** [comment]
Can confirm I also have the same issue. I'm also willing to help with any debugging :)

**Comment by cardassianscot** [comment]
I also confirm the same issue.

**Comment by dunxd** [comment]
I noticed that I had an old version of draw.io listed in uninstall programs, even though there was no trace in the program files folder. After uninstalling it I was able to install via the installer. I don't recall the version unfortunately.

**Comment by cardassianscot** [comment]
It was the same issue complicated by a previous version not uninstalling cleanly. I had to mess with regedit. But it now installs correctly. Thanks.

**Comment by ashrafteleb** [comment]
II'll close this issue. It's probably a bug with electron builder and it's windows installer.
