### ISSUE TITLE
Create ppa for Ubuntu

### ISSUE THREAD

**Issue by natrius** [jgraph/drawio-desktop#301]
Hello, 

are there any plans on creating a ppa on launchpad so its possible to get updates without having to download it again manually?

Best regards

**Comment by ghisvail** [comment]
You may use the flatpak or snap packages to get automatic updates.

**Comment by natrius** [comment]
I know i could use them, but i just want ppa and not snap or flatpak. Linux Mint drops Snaps completely btw. 

Nevermind, no ppa, got it, thanks for your amazing work anyway! :)
