### ISSUE TITLE
Can't create a new diagram when all files are closed in OSX

### ISSUE THREAD

**Issue by leonardochen** [jgraph/drawio-desktop#304]
If I close all diagrams with Cmd+W, I can't create a new one because there is no File menu
Cmd+N does nothing either.

![image](https://user-images.githubusercontent.com/495515/83758832-ae438600-a640-11ea-9323-a1c252fd23d6.png)

Can a new Menu be added to the application so I can access File > New Window?

**Comment by ashrafteleb** [comment]
You can click on the application icon in thee app drawer and a new window will open

**Comment by leonardochen** [comment]
Got it, thank you!
