### ISSUE TITLE
Drawio app in Microsoft Store does NOT have file association to .drawio file extension

### ISSUE THREAD

**Issue by triple-vee** [jgraph/drawio-desktop#305]
When you download Drawio from Microsoft Store, there is no EXE, only some container in a hidden folder (artifact of it being a Metro app).

I accidentally associated .drawio extension with wrong program. I tried to associate it back through Windows settings. But when I click on .drawio and try to set the app, I get only two options:

- Code (the app I mistakenly set)
- Pick an app from the Store
- App on file system (doesn't work because there is no EXE)

When I click on the second option, Windows pops up the store, then I get the error about .drawio file type not finding any app in the Store. So the solution would be to set the file extension in the meta data when you upload it to the Microsoft Store.

The only solution I found to this was to download the standalone installer which does install an EXE and associate the filetype with a local app in Program Files

**Comment by svendpetersen** [comment]
Me too. Mine ended up associated with Adobe Reader. Other than that I'm only getting an option to go to the app store. 
I saw a comment on another forum that it works by MIME type, not by extension. Not really the helpful answer I was hoping for.
