### ISSUE TITLE
Add "save as emf (Enhanced MetaFile)" to create high-quaility illustration in Word document

### ISSUE THREAD

**Issue by 3plus10i** [jgraph/drawio-desktop#311]
Word is not very compatible with svg file which is the only vectogram format supported by drawio now.

A possible approach is to export as VSDX and then open it with Visio and export as emf. (Or just copy and paste special with emf file) But this is obviously complex.

Maybe we could export diagram as emf so that a perfect vectogram can be inserted into a word doc with  only a copy&paste?

![Source](https://user-images.githubusercontent.com/58256978/84558196-a9c74d80-ad63-11ea-93de-e745add3a4d6.png)
_Source_

![Export as svg and paste into a word doc.](https://user-images.githubusercontent.com/58256978/84558234-e09d6380-ad63-11ea-8318-bdc3d1c5ac0b.png)
_Export as svg and paste into a word doc._

**Comment by Polyus-etf** [comment]
Поддерживаю. Очень не хватает возможности сохранения в .emf формате.

**Comment by renebeuchat** [comment]
We have add the same problem.
Our solution:

- Save or export as xx.pdf

- Use Inkscape program, open or Import the xx.pdf

- Select preference: Poppler/Cairo --> OK

- Save as... and select xx.emf --> OK
And it's done ! You can use it in word ans crop the expected area.

Yes, it would be better directly in drawio.


- 

-
