### ISSUE TITLE
wrong center grid in windows desktop

### ISSUE THREAD

**Issue by long76** [jgraph/drawio-desktop#312]
![2020-06-13_192632](https://user-images.githubusercontent.com/18124433/84573913-08b0b500-adac-11ea-81e1-357e3043d891.png)

**Comment by ashrafteleb** [comment]
I don't understand, the shape is centered correctly and grid starts from the beginning of the page correctly. Please explain more?

**Comment by long76** [comment]
> I don't understand, the shape is centered correctly and grid starts from the beginning of the page correctly. Please explain more?

Sides rectangle don't lie on the axes(on linux version all right)

**Comment by ashrafteleb** [comment]
On the given screenshot, the left and right space are the same. The grid follow the page not the shapes. Please if possible explain the current and expected behavior with a screenshot

**Comment by long76** [comment]
> On the given screenshot, the left and right space are the same. The grid follow the page not the shapes. Please if possible explain the current and expected behavior with a screenshot

i see. it's my mistake. please make the sides of the grid have an even number of squares and increase by an even number by default. thanks!

![Снимок экрана от 2020-08-25 10-19-10](https://user-images.githubusercontent.com/18124433/91145044-8737a600-e6bd-11ea-9dae-4cc2e92ce09b.png)

right have 2.7 square i think)
