### ISSUE TITLE
Add custom stencil support

### ISSUE THREAD

**Issue by thekalinga** [jgraph/drawio-desktop#314]
As of now, the shapes that are shipped are fixed

It would be quite helpful if custom stencil import is supported so that anyone can import common shapes from font awesome, material icons & many other icons as custom stencils

**Comment by ashrafteleb** [comment]
We already have shape libraries support. Does that work for your case?

**Comment by thekalinga** [comment]
Can you please point me to the documentation/samples on how to create one
