### ISSUE TITLE
No printers found with Ubuntu 20.04 snap

### ISSUE THREAD

**Issue by romandas** [jgraph/drawio-desktop#317]
I tried to print a drawing with the drawio snap application on Ubuntu 20.04 but the only printer it shows is "Print to File". I checked snap connections and snap interfaces and it appears that there are no connections for printing currently.

**Comment by AndreiCherniaev** [comment]
> I tried to print a drawing with the drawio snap application on Ubuntu 20.04 but the only printer it shows is "Print to File". I checked snap connections and snap interfaces and it appears that there are no connections for printing currently.

The same problem. Ubuntu 22.
