### ISSUE TITLE
Draw.io 13.2 desktop version is not starting, 13.0 works OK

### ISSUE THREAD

**Issue by przemeqq** [jgraph/drawio-desktop#318]
Windows 10 Prof insider preview (currently 19645.1)
it stopped staring several days ago. 
Possible infecting changes:
- upgrade to new Edge on Chromium.
- automatic update from 13.0 to 13.2

I did full draw.io reinstall, cleaned everything I could find in %AppData%.
Version without installer (no-install) is not working too.
Is there any log I can look in to?

**Comment by ChrisPVella** [comment]
Experiencing the same issue across my devices running W10 Enterprise Insider Preview since updating to v13.2.1. I reverted to v13.0.3 and it works fine.

**Comment by przemeqq** [comment]
Wow, downloaded 13.0 (no-installer) and it works!. So 13.2 @Windows is broken

**Comment by davidjgraph** [comment]
Is insider preview a production release?

**Comment by przemeqq** [comment]
> Is insider preview a production release?

I'm on fast

**Comment by davidjgraph** [comment]
So is that a production release of windows or not?

**Comment by przemeqq** [comment]
> So is that a production release of windows or not?

It's like beta

**Comment by davidjgraph** [comment]
OK, we can't test of every beta. Given it works on stable Win 10 I'll close.

**Comment by przemeqq** [comment]
> OK, we can't test on every beta. Given it works on stable Win 10 I'll close.

Checked on another machine (not insider build) and 13.2 works fine

**Comment by davidjgraph** [comment]
https://github.com/electron/electron/issues/23841 is the downstream issue.

**Comment by davidjgraph** [comment]
Try 13.2.4

**Comment by przemeqq** [comment]
It Works
![image](https://user-images.githubusercontent.com/28541099/84791883-8581a000-aff3-11ea-98e2-8cb8b24f1339.png)
