### ISSUE TITLE
Auto export

### ISSUE THREAD

**Issue by damianh** [jgraph/drawio-desktop#32]
Love this app and I'd actually pay for it if it were for sale :)

I regularly edit documents and then re-export them as png for viewing in github etc. I'd like to be able to define an auto export that saves a `.png` (or whatever format) along side the xml every time I save. 

Cheers.

**Comment by alderg** [comment]
Try saving the diagram with a .png extension, this will save it as a PNG image with the XML embedded.

**Comment by damianh** [comment]
TIL, thx.
