### ISSUE TITLE
Allow opening recent files from the startup window

### ISSUE THREAD

**Issue by thekalinga** [jgraph/drawio-desktop#320]
It would make user's life much simple if recent files can be opened initial screen itself

i.e By adding `5 recent files` option with clickable links to open the most recent files, as users would most often want to open most recent files

I'm talking about this screen

![image](https://user-images.githubusercontent.com/452518/84969334-1496d100-b136-11ea-99d6-fca84c5c26a1.png)

**Comment by eytanhanig** [comment]
Is there a timeframe for adding this feature?

**Comment by davidjgraph** [comment]
The workaround for this is to disable the splash screen and select from file->open recent. Changing the splash affects a lot of people, that's not a route I want to go down.
