### ISSUE TITLE
Desktop app for MacOS - About section either greyed out or takes me to drawio-app.com

### ISSUE THREAD

**Issue by tmoschou** [jgraph/drawio-desktop#321]
I have multiple versions of draw.io desktop apps on my Mac, the `About` menu item is either greyed out in one or navigates to https://drawio-app.com in the other.

The App named `diagrams.net Desktop` that I have had pinned in my Mac Dock since last year (previously named draw.io) has the `About diagrams.net Desktop` menu item greyed out from the Mac application menu - (I have since figured this to be the chrome app).

The latest version downloaded and installed from the new domain, http://get.diagrams.net/ using Mac installer (https://github.com/jgraph/drawio-desktop/releases/download/v13.2.4/draw.io-13.2.4.dmg) is named `draw.io` (the old name?). The `About draw.io` menu item in the Mac application doesn't show me the version, instead it takes me to https://drawio-app.com/ . Why not https://www.diagrams.net/ where I installed from? Is Drawio-desktop actually Drawio-app?

I would suggest to make user experience easier,
 * the chrome app about section should not be greyed out, but navigate to https://chrome.google.com/webstore/detail/diagramsnet/onlkggianjhjenigcpigpjehhpplldkc?hl=en
 * the about section of draw.io-x.y.z.dmg should at the least navigate to http://www.diagrams.net/ or better a dialog window with the version (which can then link to http://www.diagrams.net/)

**Comment by ashrafteleb** [comment]
Fixed, now all shows consistent results
