### ISSUE TITLE
command line export xml with options non compressed

### ISSUE THREAD

**Issue by hanbo1990** [jgraph/drawio-desktop#324]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I want to export xml from png formated draw.io graph. But cannot find the option to export non-compressed xml file. 

**Describe the solution you'd like**
It will be great to have this option in command line.

**Comment by ashrafteleb** [comment]
The ability to export to xml will be available in the next release (with -u for producing uncompressed xml)

**Comment by vulkanino** [comment]
Hello, I cannot find the option to export to uncompressed xml, I'm, using this:

`draw.io --export . --recursive --format xml -u --output /tmp/exp`

Thanks.
