### ISSUE TITLE
Why you don't make an android application?

### ISSUE THREAD

**Issue by bsimjoo** [jgraph/drawio-desktop#329]
@kant @hmalphettes @mediaslav @internetscooter @alderg  Hi, I like your site and I recommend you to release an official android and ios application. I also converted your website to a native application
https://gonative.io/share/mndqno
mail me to get manage link

**Comment by tthoma24** [comment]
I would really like to see a mobile app as well. Why was this issues closed?

**Comment by davidjgraph** [comment]
Because none of us want to write an android application. Nobody external to this project will do it, so there's no point leaving the ticket open pretending it'll be done.
