### ISSUE TITLE
CSV Import - Connect Labels Bug

### ISSUE THREAD

**Issue by pstefanov** [jgraph/drawio-desktop#330]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When trying to create a diagram based on a CSV import, specifying a variable for the label of the "connect" function causes an error.  The error message returned: "Unexpected token % in JSON at position 62".

It is easiest to verify by browsing to https://confluence.draw.io

**To Reproduce**
Steps to reproduce the behaviour:
- In the desktop version of Draw.io version 13.3.5, paste the content below in the CSV import function:
```
# label: %local_pe%
# identity: id
# style: shape=%shape%;html=1;pointerEvents=1;dashed=0;fillColor=#036897;strokeColor=#ffffff;strokeWidth=2;verticalLabelPosition=bottom;verticalAlign=top;align=center;outlineConnect=0;
# namespace: csvimport-
# connect: {"from":"remote_pe", "to":"local_pe", "invert":true, "label": %afis%, "style":"curved=0;endArrow=none;endFill=0;"}
# width: 64
# height: 82
# padding: 15
# nodespacing: 40
# levelspacing: 100
# edgespacing: 40
# layout: auto
# parent: rparent
# parentstyle: shape=rect;whiteSpace=wrap;html=1;horizontal=1;horizontalStack=0;resizeParent=1;fillColor=#F0F8FF;strokeColor=#666666;perimeter=rectanglePerimeter;container=1;recursiveResize=1;collapsible=0;
## CSV starts under this line
id,local_pe,local_as,shape,afis,remote_pe
1,router1,as-101,mxgraph.cisco.routers.atm_tag_switch_router,vpnv4,
2,router2,as-201,mxgraph.cisco.routers.atm_tag_switch_router,vpnv6,router1
2,router2,as-201,mxgraph.cisco.routers.atm_tag_switch_router,vpnv6,router4
3,router3,as-301,mxgraph.cisco.routers.atm_tag_switch_router,ipv6 unicast,router2
4,router4,as-401,mxgraph.cisco.routers.atm_tag_switch_router,ipv4 unicast,
```

**Expected behaviour**
Being able to use variables for the "connect" label key.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
13.3.5
**Desktop (please complete the following information):**

    OS: Windows 10 Home 64-bit

**Additional context**

**Comment by ashrafteleb** [comment]
It should be "label": "%afis%" (with quotes) such that the JSON is valid (but we don't support that)
The issue is which "afis" should be used (source or target)?
