### ISSUE TITLE
Remember if loaded file was uncompressed

### ISSUE THREAD

**Issue by mtikekar** [jgraph/drawio-desktop#332]
If I open an uncompressed xml file in the GUI and save it, it gets saved as compressed xml. Would it be possible to remember that it was uncompressed when loaded and save it back as uncompressed?

My use case is that I want to store these xml files in git and would prefer git to handle compression however it wants - e.g. either with zlib for individual files or with packfiles to compress multiple versions together. With the compressed xml format, git won't be able to use packfiles.

**Comment by SunSerega** [comment]
Had the same use case and problem. #200 actually mentions 2 workarounds for now.

But more importantly: wouldn't it be an easy fix to add `compressed="false"` when exporting uncompressed?

**Comment by davidjgraph** [comment]
Literally nobody seems to want compression, so we'll default to uncompressed in the next release. That will be fairly soon, but I'll close this issue up to make book keeping easier.
