### ISSUE TITLE
Removable pages pane

### ISSUE THREAD

**Issue by OverLordGoldDragon** [jgraph/drawio-desktop#333]
Also asked [here](https://webapps.stackexchange.com/q/143042/248363); I only work with one page, so below is completely redundant for me - I should be able to toggle it via `View`:

<img src="https://user-images.githubusercontent.com/16495490/87216644-9c958280-c352-11ea-9c59-cb801c4a979b.png" width="400">

**Comment by ashrafteleb** [comment]
In the next release, you can add url parameters using urlParams.json file in the working directory
```
{
    "pages": 0
}
```
