### ISSUE TITLE
Alt+Shift key combo not working after updating to 13.4.4

### ISSUE THREAD

**Issue by bt-tech-dd** [jgraph/drawio-desktop#334]
In the previous version of draw.io desktop for Windows I was able to use the shift key to select a group of object and then use alt+shift to deselect a subset of that selected group. This is no longer working with the current version.

**Comment by davidjgraph** [comment]
What was the previous version, what is the current version?

**Comment by davidjgraph** [comment]
Is this from the Window Store, or from get.diagrams.net?

**Comment by bt-tech-dd** [comment]
I used the Windows Installer file from get.diagrams.net originally and it has had several automatic updates since. This last automatic update is the one that changed the functionality of alt+shift.
