### ISSUE TITLE
On MacOS version, setting Minimal theme removes menu and leaves us locked.

### ISSUE THREAD

**Issue by uchoa** [jgraph/drawio-desktop#336]
I'm attaching a screenshot showing the menu is missing.
<img width="922" alt="Screen Shot 2020-07-18 at 00 00 52" src="https://user-images.githubusercontent.com/587124/87843332-0ef1ef80-c88a-11ea-98a3-5415bd0bab66.png">

**Comment by davidjgraph** [comment]
Locked, so none of the button or menu in the UI work?

**Comment by godfrey-cw** [comment]
This seems to still be an issue. I was able to switch back out of minimal theme using the internal menu but the built-in MacOs menu bar is still gone w/ the exception of "Edit."
