### ISSUE TITLE
update from 13.4.6 to 13.5.1 ,some library missing

### ISSUE THREAD

**Issue by silloy** [jgraph/drawio-desktop#341]
I used the "cloud and enterprise "(CAE lib)， but when I update to 13.5.1, I can't find the lib?

**Comment by silloy** [comment]
And How can I use iconfinder to search in desktop version, I hava found the web drawio can use iconfinder to search, but the desktop version can't

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio/issues/1058
