### ISSUE TITLE
`--scale 1` breaks `--crop`

### ISSUE THREAD

**Issue by brechtm** [jgraph/drawio-desktop#344]
When exporting to PDF from the command line using `--crop`, the latter is ignored when `--scale 1` is also passed. The PDF is cropped when the factor passed to `--scale` is different from 1.

draw.io 13.5.1 on MacOS

**Comment by brechtm** [comment]
I just discovered that this may indeed be intended behavior. However, I do have to note that draw.io shows very confusing command-line behavior for `--export --format pdf`:
* no extra options - output is not cropped (implicit scale = 1)
* `--crop` - output is cropped (implicit scale = 1)
* `--crop --scale 1` - output is not cropped
* `--scale 2` - output is cropped
* `--crop --scale 2` - output is cropped

**Comment by ashrafteleb** [comment]
Fixed, will be available in the next release
