### ISSUE TITLE
Visual glitches when autosaving a svg graph while moving blocks around

### ISSUE THREAD

**Issue by jeremyVignelles** [jgraph/drawio-desktop#345]
I have some left-behind visual glitches that appeared on my SVG graph.

After some digging, I could narrow it down to the following repro:

- Create a new diagram, as an "editable vector image (.svg)" (I didn't manage to reproduce with a drawio file)
- Save it somewhere (I didn't manage to reproduce if the file is not saved, which, I suspect, indicates that it has something to do with the autosave).
- Drag something onto the graphic and wait for it to be saved.
- Drag the shape around. After a few tries, you should see some visual glitches, as if the shape was duplicated. You cannot interact with the glitch, but it follows the window and survives everything I tried, and only went away when closing the file and opening it again.

![repro](https://user-images.githubusercontent.com/3399355/88927988-8e16f880-d278-11ea-8d32-92fbc48d2959.gif)

I'm using diagrams.net 13.5.1 on windows

**Comment by mararad** [comment]
Hi, 

If you repeat all the steps without being in dark mode (click Extras > Themes > Automatic) can you repeat the same problem?

P.S I recreated the issue in desktop version 13.5.7 but only in Dark mode. In Automatic mode I couldn't reproduce this.

Regards,

**Comment by jeremyVignelles** [comment]
I couldn't reproduce anymore with diagrams.net 13.9.9. Closing.
