### ISSUE TITLE
"Cloud & Enterprise" shapes missing after update to 13.5.1

### ISSUE THREAD

**Issue by martini5468** [jgraph/drawio-desktop#346]
Running the autoupdater from 13.4.5 to 13.5.1 causes all shapes from "Cloud & Enterprise" to disapear. The shapes do not appear in the list "More shapes" list as well. Going back to 13.4.5 resolves this.

Let me know if you require any additional infomration.

Regards,
martin

**Comment by jeremyVignelles** [comment]
I just read the Changelog, so I can reply :) It has been removed due to licensing reasons : https://github.com/jgraph/drawio/blob/master/ChangeLog#L33

**Comment by davidjgraph** [comment]
They are back in 13.5.7

**Comment by martini5468** [comment]
@jeremyVignelles yeah i knew i forgot to do something.
@davidjgraph thank you for the update
