### ISSUE TITLE
Export to PNG doesn't display SVG images

### ISSUE THREAD

**Issue by jeremyVignelles** [jgraph/drawio-desktop#347]
Hi,
When exporting the attached drawio file (inside the zip) as PNG, the SVG image isn't shown.

It doesn't happen with the online version of drawio.

I'm using the desktop version 13.5.1 .
[svg.zip](https://github.com/jgraph/drawio-desktop/files/5007191/svg.zip)

**Comment by davidjgraph** [comment]
Is the SVG embedded or hosted somewhere?

**Comment by jeremyVignelles** [comment]
I dragged the SVG URL into the desktop app, so I'd say it's a hosted SVG.

**Comment by davidjgraph** [comment]
Probably hitting a security restriction. For now, it you embed the SVG directly, that should workaround the issue.

**Comment by jeremyVignelles** [comment]
Is there a way to embed the SVG directly without having to manually download the file first ? (something like a right click/ embed image or even better "Embed all images" ?)

**Comment by jeremyVignelles** [comment]
Probably related : right click on such images/ copy as image shows "Invalid image"

**Comment by jeremyVignelles** [comment]
This is still an issue

**Comment by jeremyVignelles** [comment]
I didn't test in a while, but chances are that it's still an issue. any update on this?

**Comment by eperdeme** [comment]
Hit this problem today. :(

**Comment by davidjgraph** [comment]
Works in 15.8.7 on MacOS 12.0.1 for me with provided example.

**Comment by jeremyVignelles** [comment]
Just downloaded the latest draw.io version (15.8.7) and downloaded the attached draw.io file. After exporting to the PNG format, this is the PNG I get:
![svg drawio](https://user-images.githubusercontent.com/3399355/146449843-450f4ba2-ca87-4985-8cd0-cff1b1ed43c5.png)

I think this is still an issue.
Windows 10 21H2

**Comment by davidjgraph** [comment]
OK, I can repeat now, but we cannot fix this in desktop. The image is coming cross-domain and we cannot use a proxy to load it, the canvas is tainted and the image export won't work.

The only fix is to serve the image from a server with a CORS header that allows cross-domain loading.

**Comment by jeremyVignelles** [comment]
> The image is coming cross-domain

I'm not sure I understand the process here. Shouldn't that be an issue to display the image in the first place too ? What's the process involved in generating a PNG file ? Is it possible to pass the images as base64-urls or download them in a cache folder somewhere before exporting them as PNG ?

I still think there is an issue somewhere and that the ticket should be reopened : As a user, I expect my PNG ton contain exactly what I see on screen. Worse, if I spend 3 hours finding images online to fill a draw.io file, I might be a bit disappointed to see that my images are not exported.

Or maybe the issue isn't about the export but about how they are integrated into the file ?

**Comment by davidjgraph** [comment]
The issue is that images loaded onto a canvas cross-domain taint the canvas unless the CORS header is set. 

Adding a proxy into the app to avoid that 1) might not help and 2) seems a large security attack surface to add. I'm open to technical solutions to fix it, but there's no point leaving this open if it cannot be fixed.
