### ISSUE TITLE
Optimization recommendations for line segment intersection

### ISSUE THREAD

**Issue by pealpool** [jgraph/drawio-desktop#348]
When drawing a flowchart encounters line intersections, I hope we can add the ability to automatically cross the lines. 
Just like Visio do.

![2020-8-3 23-15-31](https://user-images.githubusercontent.com/16716146/89198412-c3f10f80-d5df-11ea-9466-90732a066e34.png)

**Comment by davidjgraph** [comment]
https://drawio-app.com/draw-io-now-supports-line-jumps/
