### ISSUE TITLE
Line Jumps doesn't work when lines overlap

### ISSUE THREAD

**Issue by pealpool** [jgraph/drawio-desktop#350]
![20200805001719](https://user-images.githubusercontent.com/16716146/89318594-94123c80-d6b1-11ea-99ce-60ea63d5608b.png)

**Comment by mararad** [comment]
Hi,

it seems that you are using rounded lines. When you add line jumps, just make sure that the lines are "in front"
i.e select the line you want to have line jumps and click Arrange - To front. 

If that doesn't help, update desktop app version to the latest https://github.com/jgraph/drawio-desktop/releases and test again.

If nothing helps, feel free to attach a file so I could test it directly (and tell me operating system you are using)

Regards,

**Comment by pealpool** [comment]
ok, thank you, it work now!
