### ISSUE TITLE
When I copy/paste an screen capture from `snipping Tools` into my diagram. The image is blurred !

### ISSUE THREAD

**Issue by amorel** [jgraph/drawio-desktop#352]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I copy/paste an screen capture from `snipping Tools` into my diagram. The image is blurred !

**To Reproduce**
1. Go to Snipping Tools
2. Click on 'Copy' icon
3. Past in diagram
4. Picture is blurred !

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net 13.5.7

- draw.io version [e.g. 12.6.7]
diagrams.net 13.5.7

**Desktop (please complete the following information):**
 - Windows 10
- Draw.io for Desktop

**Comment by mararad** [comment]
Hi,

could you send a png you are adding and screen shot of the result, please?

Thanks,

**Comment by amorel** [comment]
Sometimes, when I directly paste an image, he asks me if I want to resize the image. I think the problem is that sometimes he doesn't ask me and automatically chooses "Resize". The quality is then lower... How can I prevent the automatic choice?

**Comment by mararad** [comment]
Please, try holding Ctrl while dragging the image into the drawing area.

**Comment by amorel** [comment]
I don't do dragging. I use ctrl+v to paste my image.

![image](https://user-images.githubusercontent.com/2759186/89885675-b59c8800-dbcb-11ea-8f8e-d95350c1e933.png)
