### ISSUE TITLE
Open file does not work when path contains symbolic link under linux

### ISSUE THREAD

**Issue by npfistner** [jgraph/drawio-desktop#356]
Opening a file using file association with a file path containing a symbolic link does not open the file an leafs the canvas empty.
Also trying to open the the file using the file dialog does not work because symbolic links do not show up in it.

I'm using drawio desktop 13.6.2 from Snap (available from package manager) 
on Linux:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

**Comment by jclc** [comment]
Any update on this? This is particularly unfortunate for me since my Documents folder is a symlink pointing to a separate drive.

**Comment by jclc** [comment]
Turns out this could be a filesystem permission issue with Snap and Flatpak. Running `flatpak override --user --filesystem=host com.jgraph.drawio.desktop` fixes the issue, I had similar issues with a few other apps as well.
