### ISSUE TITLE
XML Input

### ISSUE THREAD

**Issue by vkuehn** [jgraph/drawio-desktop#357]
Many Workflow Systems do use XML as an input.
Is there a way to use xml files as an input to start e.g. a workflow documentation. 

If not I did not see any other input method than file or creating manually, is there any ?

**Comment by ashrafteleb** [comment]
Can you explain more please?
What is the XML file format? *.drawio uses XML format

**Comment by vkuehn** [comment]
so I should requestion my question 
is there any documentation on how to generate the *.drawio Files by some automation process or script ?

Sorry for the late reponse..!

**Comment by ashrafteleb** [comment]
I'm not aware of such documentation. BUT, drawio files are very simple XML files (the uncompressed version). You can check the details of its tags here 
https://jgraph.github.io/mxgraph/docs/js-api/files/io/mxCodec-js.html

So, you can use JS to generate it or build your own generator if you like

Note: We have also CSV import which is useful for some use-cases such as organization charts

**Comment by vkuehn** [comment]
Thanks for the hint on the csv and the Link. I'll work with them for now
