### ISSUE TITLE
render some strange things when the mouse cursor over the shape

### ISSUE THREAD

**Issue by lhtin** [jgraph/drawio-desktop#361]
App Version: 13.6.2 (but version 12.9.13 no such problem)
OS: macOS Catalina 10.15.6

![image](https://user-images.githubusercontent.com/13173904/90350663-68f3f980-e070-11ea-8801-c10beb40c56b.png)

**Comment by mararad** [comment]
Hi,

is it possible to attach a draw.oi file here so we could test it, please? Do you have the same problem with other diagrams?

Regards,

**Comment by davidjgraph** [comment]
It's an electron issue on Macs, it's not specific to draw.io. There was a twitter conversation about it, but I can't find it now.
