### ISSUE TITLE
Add ArchLinux AUR packages into releases list

### ISSUE THREAD

**Issue by sxiii** [jgraph/drawio-desktop#366]
Greetings dear developers.

I recently found that there are at least two drawio packages in ArchLinux repos (actually I'm on Manjaro):
```
* aur/drawio-desktop 13.6.2-1 (30, 3.65)
    Diagram drawing application built on web technology    
* aur/drawio-desktop-bin 13.6.2-1 (24, 2.84)
    Diagram drawing application built on web technology  
```
I do understand that these packages are user provided packages; but I wonder if you could add them into your releases list (maybe; with some "User-provided packages" flags/marks). The "drawio-deskop-bin" is based off DEB package and you can always download and verify PKGBUILD file from AUR if you want to.

I also tested the current release (13.6.2-1 bin) and it works very well.

This will make it easier for users to find your package.

Thank you very much!

**Comment by davidjgraph** [comment]
No, the problem is once we host the files people will come to us for support. We have a massive support load as it is, we can't add to that we packages that aren't ours.

**Comment by sxiii** [comment]
Thank you for fast answer.

That's sad. It would be possible just to put under "external packages: no support" spoiler.

Anyways. Thank you for your work & good luck.
