### ISSUE TITLE
How to compile diagrams on mips64el?

### ISSUE THREAD

**Issue by Streamlethy** [jgraph/drawio-desktop#369]
Hi，My processor architecture is mips64el. I want to use diagram on it. How can I do?

**Comment by ashrafteleb** [comment]
The app is based on Electron, this is the list of supported OS/Architectures https://www.electronjs.org/docs/tutorial/support#supported-platforms

Unfortunately, mips64el is not there so most probably it is not possible

**Comment by ashrafteleb** [comment]
You may use a self-hosted server-based draw.io or the online version
