### ISSUE TITLE
Sketchy font

### ISSUE THREAD

**Issue by sudwhiwdh** [jgraph/drawio-desktop#370]
should of course still be readable, what do you think, if the writing can also be displayed in sketch form?

**Comment by ashrafteleb** [comment]
You can add google or web fonts from the text tab. For example: https://fonts.google.com/specimen/Cabin+Sketch

**Comment by sudwhiwdh** [comment]
I rather thought of an integrated font. Wouldn't that be better for security reasons than including an external font in a document?
