### ISSUE TITLE
Allow secure and collaborative end-to-end encrypted sharing & simultaneous editing of a diagram in a web browser

### ISSUE THREAD

**Issue by sudwhiwdh** [jgraph/drawio-desktop#373]
the idea is so far completely in the title of the issue.

**Comment by kiliiiiii** [comment]
why

**Comment by ashrafteleb** [comment]
This is the desktop version, the web version already have collaborative editing on Google Drive and OneDrive

**Comment by sudwhiwdh** [comment]
My main focus of this issue was on secure collaboration! Do Google Drive and OneDrive allow that?

To the point Desktop Version/Web Version: That was indeed not so precise. If the desktop version has an online function, I find it exciting to see if both can be combined. Some people work in the desktop client, others prefer the browser. Otherwise this issue could be moved to the development repository of the web client, couldn't it?
