### ISSUE TITLE
no BPMN icons (Events/Gateways)

### ISSUE THREAD

**Issue by JO70** [jgraph/drawio-desktop#376]
![grafik](https://user-images.githubusercontent.com/66570760/92603954-36749f80-f2b0-11ea-9982-eed775d1af6c.png)
BPMN Icons in the sidebar:
-  can drag them 
- but they are empty
- 'General' is fine (visible and you can drag them)
- issue lasts for about 6 months
 HP Elitebook, Firefox, Win7 enterprise

[MENU]Ansicht>>>Shapes (opening: Shape box) --> Business --> BPMN ticked ---  all 3 subtypes (Events, Gateways, General)

**Comment by davidjgraph** [comment]
Version?

**Comment by JO70** [comment]
![grafik](https://user-images.githubusercontent.com/66570760/92605135-a46d9680-f2b1-11ea-9359-36a910f9c4af.png)
online version 13.6.9

**Comment by davidjgraph** [comment]
This the repo for the desktop build, please file at https://github.com/jgraph/drawio/issues
