### ISSUE TITLE
Shapes / Image search shows very few results

### ISSUE THREAD

**Issue by sashokbg** [jgraph/drawio-desktop#380]
App version: 13.6.2
OS: Ubuntu 20.4

**Description:** 
When searching for shapes / images in the "Search Shapes" box only a few items are shown compared to the web version.
**How to reproduce:** 
 - Search for "Spring Boot" in the application (you get no results)
 - Search for "Spring Boot" in the web version (you get many results)

**Comment by davidjgraph** [comment]
It's an offline app, we can't extend the search results using our servers.

**Comment by sashokbg** [comment]
Isn't it possible to just make it use the server if there is a connection and just fall back to "offline mode" other ways ?

**Comment by davidjgraph** [comment]
No, the whole point of the project is to make a completely offline app for privacy and security. If you want the features of the online version, just use the online app.
