### ISSUE TITLE
Command line SVG export

### ISSUE THREAD

**Issue by maecky** [jgraph/drawio-desktop#382]
When I export an SVG image from the app, I am able to select "Embed Images" (see Screenshot below). If I do the export from the command line, I am missing this option. It would be really great to include this. My command line export looks like this:
`draw.io.exe" -x -e -f svg -o test.svg test.drawio`
![image](https://user-images.githubusercontent.com/1969683/93647632-258f0100-fa09-11ea-9a6b-bc099320fd17.png)

**Comment by sestegra** [comment]
Editor code is here
https://github.com/jgraph/drawio/blob/8a8053202b63093845f989c7c586013299cddc71/src/main/webapp/js/diagramly/Menus.js#L769

Command line options code is here
https://github.com/jgraph/drawio/blob/dev/src/main/webapp/electron.js#L273

**Comment by m-mohamedin** [comment]
`--embed-svg-images` option will be available in the next release. Also, embedding diagram data will be available in SVG format also
