### ISSUE TITLE
[Feature request] Ability to disable hardware acceleration.

### ISSUE THREAD

**Issue by bjonnh** [jgraph/drawio-desktop#383]
Chromium and Electron apps are glitchy on my configuration (AMDGPU driver on linux with a RX550). 
There are flags on chromium, but on electron apps the only way to solve that is to call:

````javascript
app.disableHardwareAcceleration();  
````

I confirm that putting that line in **electron.js** before the:
````javascript
app.on('ready', e =>
````

solves the issue for me.

Would it be something that could be available with a command line flag?

**Comment by m-mohamedin** [comment]
--disable-acceleration will be added to the next release
