### ISSUE TITLE
The option 'Open Library from’ URL is not available

### ISSUE THREAD

**Issue by JamesDLD** [jgraph/drawio-desktop#385]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The option 'Open Library from’ URL is not available.

**To Reproduce**
1. Go to the 'File' menu
2. View ‘Open Library' and that's it.

Previously we there was Click on ‘Open Library from’. Click on ‘URL…’.

**Expected behavior**
Click on the ‘File’ menu. Click on ‘Open Library from’. Click on ‘URL…’.

**Screenshots**
Before like explained [here](https://www.moderndata.ai/2020/08/working-with-azure-icons-in-draw-io-diagrams-net/?utm_source=rss&utm_medium=rss&utm_campaign=working-with-azure-icons-in-draw-io-diagrams-net).
<img width="391" alt="image" src="https://user-images.githubusercontent.com/18073917/94036106-3c947100-fdc4-11ea-9fa3-60d40bca400e.png">

Now --> 
<img width="814" alt="image" src="https://user-images.githubusercontent.com/18073917/94148118-7f168600-fe76-11ea-84a0-b393f26d8555.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.7.3

**Desktop (please complete the following information):**
 - OS: macOS Cataline Version 10.15.6

**Comment by mararad** [comment]
Hi,

You mentioned "Previously we there was Click on ‘Open Library from’. Click on ‘URL…’." - what desktop version had "Open library from" option? Do you maybe remember?

Thanks

**Comment by JamesDLD** [comment]
Hi,
unfortunately I don't remember, I did just change my laptop.

**Comment by davidjgraph** [comment]
This might be when the desktop version basically acted as a web browser and loaded the online app. We have to switch away from that model for security reasons, the newer architecture proritises security over matching the functionality in the online version.

If something, like this, is not available in the desktop version, that's because a security restriction we've put in place doesn't allow it. The online version is a PWA, can you not use that if you need the function?

**Comment by JamesDLD** [comment]
I understand the security concern, could then update the default Azure icon library as it's obsolete or how can I import the new one from the Desktop client?

Cf the obsolete Azure icons that are natively available from the Desktop client --> 
![image](https://user-images.githubusercontent.com/18073917/94425278-f5bfc600-018b-11eb-9fd9-85b283a06abe.png)

**Comment by davidjgraph** [comment]
They will go into next release.

**Comment by JamesDLD** [comment]
Thanks, for info the official icon list is available here : https://docs.microsoft.com/en-us/azure/architecture/icons/

**Comment by JamesDLD** [comment]
Version 13.7.9 now rocks !! 
<img width="710" alt="image" src="https://user-images.githubusercontent.com/18073917/95680450-27984a00-0bda-11eb-8e3b-1920d96baa45.png">

**Comment by lkdmid** [comment]
This seems to be missing again, version 15.2.7.

**Comment by davidjgraph** [comment]
Open library from URL isn't possible due to the security architecture of the desktop app.

**Comment by carsonbird** [comment]
Old thread, but I couldn't see it until I changed the theme of the app (worked for me on Simple). However, the actual functionality didn't work - not sure if that's something on my end, or an issue with app.

**Comment by carsonbird** [comment]
Old thread, but I couldn't see it until I changed the theme of the app (worked for me on Simple). However, the actual functionality didn't work - not sure if that's something on my end, or an issue with app.

**Comment by alderg** [comment]
> Old thread, but I couldn't see it until I changed the theme of the app (worked for me on Simple). However, the actual functionality didn't work - not sure if that's something on my end, or an issue with app.

Which theme did it not work on and which URL did you try that didn't work? This URL worked for me in the Simple theme: `https://raw.githubusercontent.com/jgraph/drawio-libs/master/libs/templates.xml`
