### ISSUE TITLE
Save default style after closing the app

### ISSUE THREAD

**Issue by Chup123** [jgraph/drawio-desktop#386]
Every time I close and reopen the Windows app (downloaded from GitHub, version 13.7.3) the default style of the project has been reset. The style of the file is the same, but the default style setting of the app have been reset to the default black, what I don't use. I also use some custom style, what is also back to normal when I reopen the app.

Is it possible to change the default in the GUI? Or add this feature?

**Comment by mararad** [comment]
Hi,

when you say "the default style of the project has been reset. I also use some custom style, what is also back to normal when I reopen the app."  - could you give me some examples of project style and custom style that have been reset, please? What steps did you perform in order to make them default?

Thanks,

**Comment by Chup123** [comment]
Here's what I did:

- I Have this when I open my project, selected a style previously on the right side:
![Before](https://user-images.githubusercontent.com/33879050/94544434-84474c80-024b-11eb-9ef0-73af304d5599.png)
- Then when I add a object it's black, not like the style I selected:
![middel](https://user-images.githubusercontent.com/33879050/94544617-bf498000-024b-11eb-8843-91d93e8048b7.png)
- I have to press the style again:
![middel 2](https://user-images.githubusercontent.com/33879050/94544688-d5efd700-024b-11eb-8110-3e70454ae88b.png)
- And everything is fine:
![after](https://user-images.githubusercontent.com/33879050/94544721-dee0a880-024b-11eb-9443-ab94f6b8d8db.png)

My question is, is it possible to not do this process every time I reopen the app?

**Comment by davidjgraph** [comment]
Thanks for the suggestion. We investigated this, but couldn't come up with a solution that works for all implementations, not just desktop.
