### ISSUE TITLE
text becomes blurred when editing

### ISSUE THREAD

**Issue by lotcz** [jgraph/drawio-desktop#387]
I have just installed new version of windows desktop application (version 13.7.3) and there has been an ugly bug introduced that is hurting my eyes.

Each time when I double click an element and start editing text inside, text become blurred. Strange thing is, that during editing, text sometimes goes back to non-blurred state, then comes back.

When editing is finished, all text is ok, problem seems to be only affecting text being edited at the moment.

![drawio-bug](https://user-images.githubusercontent.com/5775751/94339023-19053c80-fff7-11ea-9431-cd1ce93e7a4b.png)

**Comment by mararad** [comment]
Reproduced with 13.7.3 Win 10

**Comment by TehWan** [comment]
Also present in 13.7.9 on Linux (Ubuntu 20.04.1 / KDE Plasma 5).

**Comment by tony0918** [comment]
@davidjgraph Any update on this? Thanks.

**Comment by TehWan** [comment]
This issue no longer exists on 14.1.8. Not sure when it was fixed.
