### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by DJ-Dingo** [jgraph/drawio-desktop#389]
It could be nice with a Raspberry Pi version

**Comment by scrumit** [comment]
I'm re-opening this issue and will update it when it work. There has to be an arm build for linux and this machine is :

Linux raspberrypi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux

**Comment by davidjgraph** [comment]
Closing due to lack of interest.
