### ISSUE TITLE
Exporting to PDF results in 'BAD REQUEST' screen (13.7.8)

### ISSUE THREAD

**Issue by Joostverrijk** [jgraph/drawio-desktop#392]
Reproduction steps:

1. Open a diagram
2. Export to PDF
3. Don't alter checkmarks
4. Select 'Device' 
5. DrawIO opens file dialog with "Bad Request" text inside

OS used: 
Win10 - all updates

**Comment by davidjgraph** [comment]
Version?

**Comment by davidjgraph** [comment]
Fixed in 13.7.9
