### ISSUE TITLE
File opening broken again

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio-desktop#394]
I just updated Drawio. Now when I double click a .drawio file it launches the app but doesn't open the diagram. Instead I just see this:

<img width="506" alt="Screen Shot 2020-04-25 at 3 35 32 PM" src="https://user-images.githubusercontent.com/191903/80292287-6d378800-870a-11ea-9478-4f986df7ff39.png">

macOS Catalina 10.15.6
diagrams.net 13.7.8

P.S. Is there a way I can roll back to a previous version?

**Comment by davidjgraph** [comment]
Yeah, we've quite a few problem, I would re-install 13.7.3 for now

**Comment by JesseAldridge** [comment]
How do I do that?

**Comment by JesseAldridge** [comment]
Oh, looks like I just run the binary here: https://github.com/jgraph/drawio-desktop/releases/tag/v13.7.3

Yeah, that works. Thanks.

**Comment by JustBru00** [comment]
I also have this issue.

drawio-desktop version: 13.7.8
Windows 10 Pro Version 1909

I will be going back to version 13.7.3

**Comment by davidjgraph** [comment]
13.7.9 should fix this. Long story, but relates to hole in testing. We'll review our to improve it.
