### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by brush59** [jgraph/drawio-desktop#396]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When trying to print a diagram (either Preview or Print) receive the popup error "Unknown error Uncaught TypeError: PrintDialog.electronPrint is not a function"

**To Reproduce**
1. Go to 'File'
2. Click on 'Print or Preview'
3. See error

**Expected behavior**
I expect to see a print dialog box

**Screenshots**
![image](https://user-images.githubusercontent.com/72566832/95481218-c1ea5a80-095a-11eb-9db6-03cefd225eca.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 13.7.8]

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Enterprise]
 - Browser [Firefox 81.0.1]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
Fixed in 13.7.9
