### ISSUE TITLE
Various error messages

### ISSUE THREAD

**Issue by michael-reggev** [jgraph/drawio-desktop#400]
Starting the application, leads to an "Unknown Error" popup, with the text "Uncaught Class 'OrgChart.Annotations.CanBeNullAttribute' is already defined". 
Selecting "Open an existing file" leads to an "Unknown Error popup, with the text "Uncaught TypeError: dialog.showOpenDialogSync is not a function". 
In the File menu, selecting "Save As" leads to a popup headed "Unknown Error", with the text "Uncaught TypeError: dialog.showSaveDialogSync is not a function". 

I'm running diagrams.net 13.7.9, on Win10 Pro 64bit build, ver 2004, build 19041.508. 

It may be leftovers in memory that would be solved by a restart, or maybe reinstalling will solve the issue, but I figured either way it may be something of interest to a bored developer ;)

**Comment by davidjgraph** [comment]
Where did you download this version from?

**Comment by michael-reggev** [comment]
Originally from the draw.io site. But I think it auto-updated recently.

**Comment by davidjgraph** [comment]
Something is very broken there, I would uninstall and re-install the latest release.
