### ISSUE TITLE
Any tutorial for Beginner? 

### ISSUE THREAD

**Issue by davidlehub** [jgraph/drawio-desktop#404]
Hi, sorry if this is not a good place to ask.

Is there any tutorial for Beginner.

I have succesfuly install it but don't know how to test and see  what i have modified. when i do "npm start", it keep running the unmodifed version. I think i miss the Push and other steps, but i don't know how to do it.

thanks in advance.

**Comment by nopeslide** [comment]
Setup the repos as described.
Attach a debugger to node executing electron and set the debug env.
Here is a examplary launch config for vscode:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Debug Draw.io",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/drawio/src/main/webapp/electron.js",
            "runtimeExecutable": "${workspaceRoot}/node_modules/electron/dist/electron",
            "sourceMaps": true,
            "env":{"DRAWIO_ENV":"dev"}
        }
    ]
}
```

**Comment by davidjgraph** [comment]
What do you modify and not see changed in the running debug version?

**Comment by davidlehub** [comment]
Hi @davidjgraph and @nopeslide , thanks for the reply :-)

@davidjgraph, for example, I just tried to change the menu item "file" to "file2":
1- In the file: _\drawio-desktop\drawio\src\main\webapp\js\diagramly\Menus.js_
1.1- I modified the line 34, from: `Menus.prototype.defaultMenuItems = ['file', 'edit', 'view', 'arrange', 'extras', 'help'];`
1.2- To: `Menus.prototype.defaultMenuItems = ['file2', 'edit', 'view', 'arrange', 'extras', 'help2'];`

Then when i run it (with "npm start"), it still showing "file".
