### ISSUE TITLE
PDF Export Bug

### ISSUE THREAD

**Issue by debrovnik** [jgraph/drawio-desktop#408]
I'm running version 13.6.2 on a few of our Windows 7 machines because later versions do not present me with the Drawio startup screen (The app simply crashes with a blank background).

Exporting a PDF file directly from Drawio Desktop fails with the error:

![image](https://user-images.githubusercontent.com/73177029/96717596-9de93900-139e-11eb-9c24-39479048d1c1.png)

Printing to a virtual PDF printer also fails.

All other export formats work as normal.

I've tried disabling the antivirus but that didn't help. I ran Diagrams.net in the browser and that works as expected.

**Comment by davidjgraph** [comment]
Electron doesn't support Windows 7 any more. Only suggestion would be to go back and find the last release where the required set of functionality you need works.

**Comment by debrovnik** [comment]
It works as normal on many of my Windows 7 instances, which is weird.

Rolling back to an old version (12.6.5) doesn't show the same error message. Instead I get an endless spinner of death.

![image](https://user-images.githubusercontent.com/73177029/96719602-83fd2580-13a1-11eb-82b7-5a50d3d88a8f.png)

**Comment by davidjgraph** [comment]
None of us are running Windows 7, it's an end of life OS. Given that, nobody is going to debug it, unfortunately.

**Comment by debrovnik** [comment]
Just wanted to report back that I managed to fix this error by building 32 bit binary from the latest drawio-desktop source. For some reason there isn't an ia32 version in your releases.
