### ISSUE TITLE
broken letter shape in arabic font

### ISSUE THREAD

**Issue by Daybayzayd** [jgraph/drawio-desktop#411]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When i want to apply different style / colour to an arabic letter, it break his shape.

**To Reproduce**
1. write the word exemple فتحا
2. Select only the last character, and apply a red color
3. The connexion between ا and ح is broken.

**Expected behavior**
The expected behavior would be to have letters shape unchanged, but only the colour.

**Screenshots**

What i want to do (work in word) :
![image](https://user-images.githubusercontent.com/55182867/97110750-3e12cb00-16db-11eb-940e-66930a4a56b7.png)

What actually produces :
![image](https://user-images.githubusercontent.com/55182867/97110758-4ff46e00-16db-11eb-8cab-473960925b7e.png)
(the connection between the 2 last letters is broken, and the shape of the before last letter is broken too).

I think it's maybe because of the style who separate the letters. It seems to work in Word but not in draw io. It's very hard to modify the HTML for every character so i came to you.

EDIT : The same issue doesn't exist on the web version. I can use it, but i prefer the desktop.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.7.9

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mararad** [comment]
Reproduced in desktop 13.7.9 and in Chrome Version 86.0.4240.111 (Official Build) (64-bit). 
All good in FF.

**Comment by ashrafteleb** [comment]
Unfortunately this is an issue with Chromium that Electron is based on.
We got the same behavior on Gmail on Chrome
