### ISSUE TITLE
Cannot select the bottom point in the UML class diagram

### ISSUE THREAD

**Issue by MeowxYee** [jgraph/drawio-desktop#412]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The bottom of the UML class diagram cannot prompt related points

**To Reproduce**
1. Add two UML class diagrams to the drawing board
2. Connect one UML class diagram with another UML class diagram with a wire
3. The connected UML class diagram, the bottom point cannot be intelligently prompted

**Expected behavior**
Hope that the point at the bottom of the UML class diagram can be indicated normally. (Regardless of the number of entries)

**Screenshots**
(Normal) When the UML class diagram removes all entries, I can prompt to connect to the bottom point
![image](https://user-images.githubusercontent.com/18101168/97280600-7222f300-1877-11eb-9b3a-4c423c53b175.png)

But when the UML class diagram once has some items. At this time, if other line segments are connected to this graph, they will not be able to intelligently prompt the bottom point.

When I move the line segment to the border, it can prompt the bottom point normally. But this seems to be nothingness.
![image](https://user-images.githubusercontent.com/18101168/97281200-2de42280-1878-11eb-95ed-072c1846825f.png)

When you move it to the bottom, it will not be prompted normally.emmmmm
![image](https://user-images.githubusercontent.com/18101168/97281114-15740800-1878-11eb-9dc9-3fb71149bbdd.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version :13.6.2

**Desktop (please complete the following information):**
 - OS: Windows 10 1903

**Comment by mararad** [comment]
Hi,

try to add connection points to the row in question as described here: https://desk.draw.io/support/solutions/articles/16000042498-how-to-add-remove-connection-points-how-to-connect-anywhere-on-a-shape-

I tested this and it worked (you could add just some of them, I added all for test purposes)

![conn points](https://user-images.githubusercontent.com/44292306/97553962-6568e100-19d6-11eb-95ef-0f32d8a808de.JPG)

Regards,

**Comment by fransf-wtax** [comment]
This is sadly still broken.
draw.io desktop version 22.03 on macOS Monterey.

**Comment by fransf-wtax** [comment]
Workaround that seems to work for me: select the class members and move them out of the class container. Now you can connect arrows to the connectors of the class rectangle because the members don't interfere anymore. When done connecting everything, move the members back into the class container.

**Comment by davidjgraph** [comment]
Can't repeat this.
