### ISSUE TITLE
The outer box of Advance->Mindmap chart does not auto resize. 

### ISSUE THREAD

**Issue by ForrestFeng** [jgraph/drawio-desktop#416]
I'm new to drawio-desktop and I found the the outer box of Advance Mindmap does not auto resize. 

![image](https://user-images.githubusercontent.com/5875631/97723874-37cf8500-1b07-11eb-8c02-4f0f5a40496f.png)

I'm using v13.6.2 and 13.7.9 both have the same issue.

**Comment by mararad** [comment]
Reproduced at my place 13.7.9

**Comment by davidjgraph** [comment]
Thanks for the report. In this case, the workaround of manually resizing is reasonable.
