### ISSUE TITLE
mac dmg fails on Apple silicon

### ISSUE THREAD

**Issue by scrumit** [jgraph/drawio-desktop#419]
I tried installing the DMG the Apple Transition Development Kit (DTK) and it opens a white box and nothing.

Like many other apps it is the Electron Framework that is failing.

[draw.io Helper (Renderer)_2020-11-05-162406-1_Mels-Mac.crash.log](https://github.com/jgraph/drawio-desktop/files/5495628/draw.io.Helper.Renderer._2020-11-05-162406-1_Mels-Mac.crash.log)

At the very least report that this DMG will not work with Apple Silicon, and to continue to use the web app, which works (in Firefox).

**Comment by davidjgraph** [comment]
It sounds like Electron 11 should improve this. We'll do a release with 11 once it's stable.
