### ISSUE TITLE
Unable to easily use extended file selection dialog for offline app in High Sierra

### ISSUE THREAD

**Issue by liamdawson** [jgraph/drawio-desktop#42]
(from: https://groups.google.com/forum/#!msg/drawio/JnzXOEgwuNg/iZbszGx5AwAJ)

App version: v8.5.12
MacOS Version: 10.13.4

Steps to reproduce:

1. Create a new blank diagram
2. File > Save As
3. Click down chevron next to filename to access fuller save dialog (e.g. to navigate to a particular folder)

Expected behaviour:

Dialog expands and shows full save behaviour.

Actual behaviour:

Dialog UI partially changes, but dialog does not expand, making the path navigation impossible. Dialog also cannot be manually expanded.

Workaround:

Dialog seems to expand correctly if you attempt to open it again, after closing it in the "expanded" state.

**Comment by davidjgraph** [comment]
10.7.7 working OK on macOS 10.14.5. If it can still be re-created on latest build, let us know and we'll reopen.
