### ISSUE TITLE
how to disable the spell checker in drawio-desktop?

### ISSUE THREAD

**Issue by FFHUVDNENG** [jgraph/drawio-desktop#420]
When I'm editing text in my diagrams, everything is red-underlined by the spell checker because I'm writing in non-English language. This is very annoying and I would like to disable the spell checker, but I don't see that option anywhere. How can I do this?

Using the Windows Desktop version of diagrams.net 13.7.9

**Comment by mararad** [comment]
Hi,

spell check in not something we support at the moment so we don't have a control over it at this moment. Maybe you could turn it off globally as described here:
https://www.howtogeek.com/244272/how-to-disable-autocorrect-in-windows-10/#:~:text=Press%20Windows%2BI%20to%20open,words%E2%80%9D%20option%20to%20disable%20Autocorrect. 
and bring it back when you need it.

Regards,

**Comment by FFHUVDNENG** [comment]
Hi, great suggestion. Unfortunately, it didn't solve the issue for me. I have both "autocorrect" and "highlight" mispelled words turned off in my Windows 10 settings and it's still doing the red-underlining. Also rebooted my PC with no effect. Could there be another system component interfering with this?

**Comment by davidjgraph** [comment]
It seems Electron 9 turned this on by default, we'll see whether we can add a menu option to toggle this.

**Comment by davidjgraph** [comment]
Disabled for window and linux, enabled for Mac.

Mac uses built-in dictionary, so we'd assume that's the right locale. Win and Linux require dictionary download and locale isn't clear, so better to disable it.

Will go into next release.

https://github.com/jgraph/drawio/commit/6245c05c230fb59f51fb47807bf8b46bcb7e4d49

**Comment by SEARANATAT** [comment]
Do you know in which release to expect this fix? I've updated my drawio desktop for Windows to version 13.9.9, but the issue is still present.

**Comment by zhongxiang117** [comment]
@davidjgraph Although this issue has been closed, I would like to comment something on it. Could you please turn on back the spell check on all systems? The fact is that not everyone is using Mac nor working on non-English graph. It has been years since this program firstly released, no one ever has complained on spell checking, or at least inside Github open/closed issues, so, it is safely to say it is fairly OK with spell checker on for most users in all different kinds of systems, why do you turn off this useful feature only on this single request? Instead, it does have influenced some users like me without spell checking, e.g., [#1721](https://github.com/jgraph/drawio/issues/1721)  not sure why this request is closed. Therefore, could you please add speak checker back on the future release or add an option/setting to turn it on? Thanks!

**Comment by ZEN-Gerrie** [comment]
I agree, seems a simple function to implement... Spell checker on/off? Would really appreciate it... :)

**Comment by Mert1980** [comment]
I need to disable the spell checker on drawio but still can not find how to disable it. I am using Mac Big Sur.

**Comment by ZEN-Gerrie** [comment]
Hello guys, don't want to be a nuisance, but any news regarding an on/off option?

**Comment by zhongxiang117** [comment]
@ZEN-Gerrie FYI, you can modify this line:
`spellcheck: (os.platform() == "darwin" ? true : false),`
to
`spellcheck: (os.platform() == "darwin" ? true : true),`
link: https://github.com/jgraph/drawio/blob/dev/src/main/webapp/electron.js#L80
Then compile package by yourself, which will finally bring you `spellcheck` for all OSs..

**Comment by davidjgraph** [comment]
Open another issue and include a suggestion for where to toggle the spellchecker in the UI

**Comment by Hel1a** [comment]
> @ZEN-Gerrie FYI, you can modify this line: `spellcheck: (os.platform() == "darwin" ? true : false),` to `spellcheck: (os.platform() == "darwin" ? true : true),` link: https://github.com/jgraph/drawio/blob/dev/src/main/webapp/electron.js#L80 Then compile package by yourself, which will finally bring you `spellcheck` for all OSs..

That link does not look like what you have quoted.

**Comment by zhongxiang117** [comment]
@Hel1a The setting file is in lively update, search keyword `spellcheck` in file `electron.js`, and set its value to `true` if you want to use spell check on all systems.
FYI, the new corresponding line: [https://github.com/jgraph/drawio/blob/dev/src/main/webapp/electron.js#L92](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/electron.js#L92)
