### ISSUE TITLE
File picker opens in the back

### ISSUE THREAD

**Issue by maifeeulasad** [jgraph/drawio-desktop#421]
File picker windows should be opened in the front not in the back. 

Here is the problem : 

![Screencast from বুধবার 11 নভেম্বর 2020 02 39 15 +06](https://user-images.githubusercontent.com/29339330/98789172-269e4680-242c-11eb-91e4-673cf305d55b.gif)

**Comment by ak2766** [comment]
All tickets relating to this issue are closed yet I'm still seeing this issue on my installation with diagrams.net 17.2.1 on Ubuntu 20.04.4 LTS.  Looks like my only option is to open another ticket.

**Comment by davidjgraph** [comment]
It's an upstream issue in electron. You can open one, but we can't fix it.
