### ISSUE TITLE
Tabs instead of new windows?

### ISSUE THREAD

**Issue by breachr** [jgraph/drawio-desktop#424]
Great App!

There is just one thing im missing. If often work with multiple .drawio files and my taskbar gets cluttered pretty quickly. Would it be difficult to implement a Tabs instead of new Windows feature? Or would it be difficult to change the code to do this? Chromium should support this i guess?

Help is appreciated!

**Comment by FernandoPA11** [comment]
It would be great. In the meantime you can try something like groupy.
![image](https://user-images.githubusercontent.com/49043927/100780579-8191e080-33cf-11eb-8cf6-78d4777c12c5.png)

**Comment by breachr** [comment]
> 
> 
> It would be great. In the meantime you can try something like groupy.
> ![image](https://user-images.githubusercontent.com/49043927/100780579-8191e080-33cf-11eb-8cf6-78d4777c12c5.png)

Great Workaround! Thanks ALOT! :-)
