### ISSUE TITLE
windows installer link 404

### ISSUE THREAD

**Issue by nhomble** [jgraph/drawio-desktop#426]
I went through [draw.io](https://draw.io) to do some sketches. I picked my local device for storage. At the bottom of the page, there was a popup to get the desktop application. I am on windows. I clicked on the link [https://github.com/jgraph/drawio-desktop/releases/download/v13.9.8/draw.io-13.9.8-windows-installer.exe](https://github.com/jgraph/drawio-desktop/releases/download/v13.9.8/draw.io-13.9.8-windows-installer.exe) and I get a 404.

**Comment by nhomble** [comment]
I am not too familiar with how release artifacts are tied together from github to the draw.io website. But recently there was a mac only release for 13.9.8: https://github.com/jgraph/drawio-desktop/releases/tag/v13.9.8

**Comment by davidjgraph** [comment]
Should be resolved.
