### ISSUE TITLE
The help>Support menu takes us to the GitHub site of online version of draw.io; thus making us raise the issue at a wrong place

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio-desktop#427]
When a user has a problem with the desktop version of draw.io, he would use the **Help > Support** menu. 
This link takes him to the GitHub for online version of the draw.io, instead of taking him to the desktop version of draw.io.

In other words, he is taken to https://github.com/jgraph/drawio instead of https://github.com/jgraph/drawio-desktop

As a result, he ends up describing his issue to the wrong set of developers.
- Would his bug be rejected and closed? Or redirected?

Either way, this is not a good situation. 
Please correct the URL that is provided in the **Help > Support** menu of the Desktop version of Draw.io.

**Comment by mararad** [comment]
Hi,

could you tell me desktop version you are using, please? Can be seen under Help.  

Thanks,

**Comment by raindropsfromsky** [comment]
I just upgraded to 13.9.9

BTW when I click on the **Help > Support** link, it takes me to the following page:
![image](https://user-images.githubusercontent.com/9047168/99245418-8d0ad680-2829-11eb-9a86-3fb707549e7c.png)

As shown, the top of the page has the very familiar link to raise issues.
But the bottom of the page provides a link to switch to the Desktop version of the product.

This is confusing: Why should the user of the Desktop version go to the online version and then to his own version every time??
Let him go to his own help page.
