### ISSUE TITLE
Please include prompts in the issue form so that the user does not miss any important information by mistake.

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio-desktop#428]
The **Help > Support** menu in the Desktop version of Draw.io takes us to the GitHub for online version of Draw.io.
As a result, I have raised several bugs there.
When I reached that section, I noticed that the form contains several prompts.
We have to respond to these questions while filing the issue.
This ensures that the users do not omit any important information by mistake.

But in the Desktop version of GitHub section, the form does not contain any such prompts.
The user can simply type whatever he wants and raise the issue.

IMHO this section should follow the same good practices that are being followed by the online version of Draw.io.
Of course, the template should be changed to suit the Desktop version of the product.
(For example, do not ask which browser is being used.)

**Comment by mararad** [comment]
Hi,

Could you just tell me a desktop version you are using, please? Can be seen under Help.

Regards,

**Comment by raindropsfromsky** [comment]
I have upgraded just now to 13.9.9

Even this version has a link that opens a page called "getting help".
But the very top of the page itself provides the very familiar "Issues" link.
If I click on it, it takes me to issues for the **online version** of Draw.io.
![image](https://user-images.githubusercontent.com/9047168/99244731-816ae000-2828-11eb-8abd-d2f1e6eddf30.png)

But if I go down the page, a link is offered to switch to the desktop version of draw.io.
But why should this be done at all??

The desktop version of the product should straightaway jump to its own help page directly.
