### ISSUE TITLE
Please provide documentation to explain all properties 

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio-desktop#429]
When we select a shape or a connector, Draw.io shows a long list of parameters ("properties").
Obviously, the purpose is to allow the user to tweak these properties and get a perfect drawing.

Unfortunately, these properties are not explained anywhere.

At minimum, we should know the following about each property:
1. what the property represents
2. The range of adjustment
3. When we adjust its value, what happens to the shape/connector
4. Does it have any side-effects?

Please provide this description upfront to the users.
Users cannot be expected to join the support Google group to ask each-other the possible answers and make wild guesses.
Or to change the properties experimentally and figure out what happens.

A step-by-step visual guide must be provided.

**Comment by mararad** [comment]
Hi,

I understand you. Meanwhile, some of the properties are described here: https://drawio-app.com/shape-properties-panel/ 

Regards,

**Comment by AlexDixson** [comment]
> When we select a shape or a connector, Draw.io shows a long list of parameters ("properties"). Obviously, the purpose is to allow the user to tweak these properties and get a perfect drawing.
> 
> Unfortunately, these properties are not explained anywhere.
> 
> At minimum, we should know the following about each property:
> 
> 1. what the property represents
> 2. The range of adjustment
> 3. When we adjust its value, what happens to the shape/connector
> 4. Does it have any side-effects?
> 
> Please provide this description upfront to the users. Users cannot be expected to join the support Google group to ask each-other the possible answers and make wild guesses. Or to change the properties experimentally and figure out what happens.
> 
> A step-by-step visual guide must be provided.

Did you find a description of the properties?

**Comment by OdyAsh** [comment]
Self-reminder to eventually publish a blog/youtube video explaining most of these properties once I get a handle on this program!

**Comment by woldaker** [comment]
I second this.

I would in particular like to know what these do:

Expand
Edit Dialog
Autosize and Autosize Grid (you'd think these would be simple to figure out but I can't tell that they do anything at all)
Tree Folding, Tree Moving
Move Cells on Fold
Perimiter
Resize Children
Fixed Dash
A description of how the Directions North South East West work with the constraints
