### ISSUE TITLE
File picker opens in the back

### ISSUE THREAD

**Issue by maifeeulasad** [jgraph/drawio-desktop#430]
Same problem as #421 appears, when you're trying to save file as : 

![Screencast from সোমবার 16 নভেম্বর 2020 05 35 53 +06](https://user-images.githubusercontent.com/29339330/99248497-bd0aa780-2832-11eb-9fb1-e32cf29f00cf.gif)

**Comment by davorpa** [comment]
Confirmed to me too in both tickets, here and #421 

**Enviroment**
```
Ubuntu 20.04.1 Focal Fossa
Diagrams Desktop 13.9.9
```

**Comment by adriandab** [comment]
Confirm for Ubuntu 18.04 & draw.io 11.1.4-229 
Error message on console: 
Gtk-Message: 18:26:59.111: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by rickiewars** [comment]
I still got this issue on Manjaro KDE in draw.io version 18.0.6

**Comment by davidjgraph** [comment]
We can leave it open, but there's nothing we can do to fix it. You need to supply a repro example to electron as an issue.

**Comment by rickiewars** [comment]
How do you mean that exactly? Open an issue on the Electron git repository refering to this repository and this issue?

**Comment by rickiewars** [comment]
I've tried to find a similar issue on the github issue-tracker of Electron but failed to find one.
I've opened a new issue on their Github Issue-tracker mentioning this bug.
The issue can be found on [https://github.com/electron/electron/issues/34341](https://github.com/electron/electron/issues/34341)

**Comment by davidjgraph** [comment]
https://github.com/electron/electron/issues/32857
