### ISSUE TITLE
Cannot download installer for MacOs

### ISSUE THREAD

**Issue by jonjieviduya** [jgraph/drawio-desktop#434]
Cannot download the latest install for macOs. My internet is good, but it seems like there's a problem with the source. Any idea?

**Comment by davidjgraph** [comment]
What error do you get? Have you tried a different computer/browser?

**Comment by mararad** [comment]
Where did you downloaded it from, please?

**Comment by davidjgraph** [comment]
Tickets that delete the bug template are closed.

**Comment by jonjieviduya** [comment]
Sorry for late response, this is the download link I've tried, but all is good now.

https://github.com/jgraph/drawio-desktop/releases/download/v13.9.9/draw.io-13.9.9.dmg
