### ISSUE TITLE
Apple Silicon M1 support

### ISSUE THREAD

**Issue by merrcury** [jgraph/drawio-desktop#437]
Does Desktop App support M1 natively(without Rosetta 2)?

**Comment by davidjgraph** [comment]
Not yet. Requires Electron support for it to come out of beta.

**Comment by imrefazekas** [comment]
11.0.3 is out for awhile now, stable enough?

**Comment by davidjgraph** [comment]
We use electron-builder to build, https://github.com/electron-userland/electron-builder/issues/5392, that doesn't yet have support.

**Comment by pekcheey** [comment]
just saying, it seems like electron-build had release support for apple-silicon already.

**Comment by davidjgraph** [comment]
We'll try it, but none of us have an M1 yet, so it's as-is until we do.

**Comment by pekcheey** [comment]
it seems like @ashrafteleb merged the codes for building a native arm version in the following commit already. 3c0ffe4e4b3889b6d45b75a4c941a993a22aefac

I'm only a rudimentary node developer. but after doing the following 

```
cd drawio-desktop/
npm install
cd drawio-desktop/drawio/src/main/webapp
export npm_config_arch=arm64
rm -rf node_modules
npm install
npm start
```

I'm getting a sweet arm version of the desktop app running. 
it's slick. and very fast. 

![image](https://user-images.githubusercontent.com/1754160/103294751-6bf2f380-4a2d-11eb-86d3-6b74c39447b5.png)

Let me know if there's anything I can help with. testing or something. 

If you can show me the commands, I'll be glad to run them and come back with the result.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio-desktop/releases/download/v14.1.4/draw.io-arm64-14.1.4.dmg

**Comment by WiesBen** [comment]
Shouldn't it be a so called universal binary with support for both architectures as apple proposes? Currently our systems try to install it with munki on intel mac which fails....
