### ISSUE TITLE
Is this repo development will still be active?

### ISSUE THREAD

**Issue by abdashaffan** [jgraph/drawio-desktop#439]
Is this repo development will still active after mxgraph development (currently) got discontinued?

Basically the same question like https://github.com/jgraph/drawio/issues/1473, but just want to make sure because this repo specifically uses mxgraph for DEV mode from the information on the README page

Also, is there an active community forum like discuss or slack for the open-source developers? 

Thank you so much for your hard work on this project.

**Comment by ashrafteleb** [comment]
Development is continuing as normal on this repo. README is updated and drawio linked repo is updated (the version used in this repo is not updated yet. It will be updated in the next release)
