### ISSUE TITLE
Create New Diagram opens FilePicker twice and the created diagram non-editable

### ISSUE THREAD

**Issue by ejalaa12** [jgraph/drawio-desktop#441]
## How to reproduce
- click on create new diagram
- click on "Create"
- a File picker window is opened to select where to save the file
- once confirmed, a second File picker window is opened (in the back this time)
- once confirmed again, we have access to the classic view
- but we can't edit anything

However, if I close the first dialog box instead of choosing between "Create a New Diagram and "Open Existing", everything works fine.

### Preview
The step to reproduce the bug are shown in this gif
![bug-snapcraft](https://user-images.githubusercontent.com/12619034/101894763-ebb43d80-3ba6-11eb-953f-5023927b063c.gif)

## Environment:
- ubuntu 18.04: Linux forssea1 5.4.0-56-generic 62~18.04.1-Ubuntu
- drawio version from snap: 13.9.20

**Comment by mararad** [comment]
Hi,

Did you use https://github.com/jgraph/drawio-desktop/releases to download the desktop version, please?
Are you sure you are using 13.9.20? If you update it to 13.9.9 does it help?

Thanks,

**Comment by rpahu32323** [comment]
I am having the same problem. Installed from the Ubuntu Snap store on Ubuntu 20.04.1 LTS. The snap store shows version 13.9.20 but when I run draw.io desktop, help -> about shows "diagrams.net 13.10.0" as the version. Closing the initial dialog box as described in comment 1 allows editing.

**Comment by ejalaa12** [comment]
@mararad No I installed drawio with snap. This is the output of `snap info drawio`
```
name:      drawio
summary:   draw.io desktop
publisher: draw.io (jgraph✓)
store-url: https://snapcraft.io/drawio
contact:   support@draw.io
license:   unset
description: |
  draw.io Desktop packaged for snap. https://github.com/jgraph/drawio-desktop
commands:
  - drawio
snap-id:      84JReQ8pcNGJyAbT0gSDiW7OpDkrdaXp
tracking:     latest/stable
refresh-date: 34 days ago, at 17:06 CET
channels:
  latest/stable:    13.9.20 2020-11-19 (84) 97MB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      12.6.5  2020-02-19 (11) 87MB -
installed:          13.9.20            (84) 97MB -
```

**Comment by erihh3** [comment]
I'm having the same problem. I've downloaded it from Ubuntu Snap store on Ubuntu 20.04.1 LTS too.

**Comment by erihh3** [comment]
I've removed the snap version and installed the .deb file from https://github.com/jgraph/drawio-desktop/releases given by @mararad ver 13.9.9.

However, snap version is still needing some attention.
