### ISSUE TITLE
drawio crashes in docker container

### ISSUE THREAD

**Issue by PhilipSiEn** [jgraph/drawio-desktop#442]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I am trying to crate a docker image that allows me to convert drawio files to images in a CI pipeline. When I run drawio inside the container in CLI mode I get an error message:
```
The futex facility returned an unexpected error code.
Aborted
```

**To Reproduce**

Dockerfile:
```
FROM ubuntu:20.10
COPY draw.io-amd64-13.9.9.deb /opt/install/
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install --fix-missing -y sudo libgbm-dev libasound2 /opt/install/draw.io-amd64-13.9.9.deb && \
    rm -rf /var/lib/apt/lists/* && rm /opt/install/draw.io-amd64-13.9.9.deb
RUN useradd --create-home --shell /bin/bash --groups sudo docker && \    
    sed -i 's/ALL$/NOPASSWD:ALL/' /etc/sudoers
USER docker
```

Build image:
`docker build --tag drawio .`

Navigate to directory containing .drawio file and run docker:
`docker run -it -v $PWD:$PWD -w $PWD --privileged drawio bash`

Try to  convert .drawio file:
`drawio -x -f png -o test test.drawio`

**Expected behavior**
An image file test.png is created.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io 13.9.9

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10

**Comment by PhilipSiEn** [comment]
I just found a solution for this issue: https://github.com/pkg-src/drawio.docker
Works for me.

**Comment by fantostisch** [comment]
What was your solution? Using xvfb? Because then it is the same issue as https://github.com/jgraph/drawio-desktop/issues/338.

**Comment by PhilipSiEn** [comment]
> What was your solution? Using xvfb?
Yes

**Comment by KenwoodFox** [comment]
@PhilipSiEn did you ever get that CI working? id love to see it.

**Comment by PhilipSiEn** [comment]
Dockerfile:

```
FROM ubuntu:20.04

ENV DRAWIO_VERSION 13.6.2

RUN set -e -u -x; \
    apt update; apt -y upgrade; \
    DEBIAN_FRONTEND=noninteractive apt -y install \
        curl xvfb nano libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libappindicator3-1 libsecret-1-0 libgbm1; \
    curl -LJO "https://github.com/jgraph/drawio-desktop/releases/download/v${DRAWIO_VERSION}/draw.io-x86_64-${DRAWIO_VERSION}.AppImage"; \
    chmod a+x "draw.io-x86_64-${DRAWIO_VERSION}.AppImage"; \
    "./draw.io-x86_64-${DRAWIO_VERSION}.AppImage" --appimage-extract; \
    rm "draw.io-x86_64-${DRAWIO_VERSION}.AppImage"

COPY drawio /usr/local/bin/
```
Content of file drawio:

```
#!/usr/bin/env bash
export DISPLAY=:1
xvfb-run -a /squashfs-root/drawio "$@" --no-sandbox --headless --disable-gpu

```

**Comment by KenwoodFox** [comment]
Awesome, thx so much
