### ISSUE TITLE
draw.io and gitlab plug-in integration throws error 0 when I try to access the drawings from Gitlab repository

### ISSUE THREAD

**Issue by Aravinda93** [jgraph/drawio-desktop#443]
I have integrated the draw.io into my organization GitLab. It has been done correctly because when I go to my https://drawio.company-group.com/ and open the existing GitLab projects then I see all my repositories.

1. I have a repository ```ABC``` which contains some of the .drawio files. 
2. I am trying to access them to https://drawio.company-group.com/. 
3. When I click on my ABC repository in the https://drawio.company-group.com/ then I get the following error: 'error 0 OK'.
4. In the console, I get the error:
Access to XMLHttpRequest at '**https://code.some-group.com//api/projects/SOMEPROJECTNAME/repository/branches?per_page=100&page=1' from origin 'https://drawio.company-group.com'** has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

5. So I tried to copy the URL and run it directly in the browser and I got the error: Requested URL not found. 

6. When I replaced the SOMEPROJECTNAME in URL with the respective project ID such as 10 then I got the JSON response with some fields from the respective repository.

I could not find an error when I searched for the same. Just found 1 article where it has been mentioned as an error due to the safari browser. I tried using Chrome, Firefox, Safari, and I got the same error in all browsers.

I just wanted to know how can I resolve this issue? Also, do I need to provide any additional permissions from the GitLab side? Because I am able to see all projects so I guess it has all permissions. Any help would be really appreciated.

I looked into the GitLab REST API and there they are taking only the `ProjectID` they are not taking the `Repo Name` anywhere. Can someone please clarify is this a bug from `jGraph`? Because they are reading `Repo name` and it's not working as expected. But if I replace the `Repo Name` with my `Project ID` then I am able to get the response.
Here is the link to GitLab rest API request:
https://docs.gitlab.com/ee/api/api_resources.html#project-resources

![screenshot-drawio-company-group-com-1608042245972](https://user-images.githubusercontent.com/29374160/102227254-a2872500-3ee9-11eb-86f8-c1f82fa24a39.png)

**Comment by Aravinda93** [comment]
@davidjgraph Please at least provide some explanation or work-around before closing the issue.

**Comment by davidjgraph** [comment]
This isn't going to be looked at, there's no point leaving it open. I don't have to provide an explaination.
