### ISSUE TITLE
Copy and paste clipboard between diagrams

### ISSUE THREAD

**Issue by dnosferatus** [jgraph/drawio-desktop#445]
I am using Parrot 4.10. With 2 diagrams open at the same time. I cannot copy elements between diagrams.

**Comment by mararad** [comment]
Hi,

when selected, try copy/paste using keyboard shortcuts. For Win it is Ctrl+c/Ctrl+v, but not sure about Parrot OS shortcuts. I assume you will know.

Regards,

**Comment by dnosferatus** [comment]
> Hi,
> 
> when selected, try copy/paste using keyboard shortcuts. For Win it is Ctrl+c/Ctrl+v, but not sure about Parrot OS shortcuts. I assume you will know.
> 
> Regards,
Thank you for responding quickly.
Tried it with keyboard shortcut and context menu.
It seems that the problem is in the clipboard shared between the drawio diagrams.

**Comment by davidjgraph** [comment]
Does it work with 14.1.4? What is parrot?
