### ISSUE TITLE
connect the cloud (github,onedrive,etc)

### ISSUE THREAD

**Issue by AronWater** [jgraph/drawio-desktop#449]
Sorry this is not a  bug report nor feature request
may i know is it possible to connect the cloud when using the desktop version?

**Comment by mararad** [comment]
Hi,

At the moment, the desktop app can't access cloud storage options. Downloading a file from a cloud file and opening it in the desktop app is the only solution for now.

Regards,

**Comment by ashrafteleb** [comment]
The idea of the desktop app is to work without internet access. You can have the cloud services in the online app which is identical to the desktop one.

I would close this issue for now unless there is a reason the online app doesn't fit your needs?
