### ISSUE TITLE
Add support for event storming diagrams

### ISSUE THREAD

**Issue by ghisvail** [jgraph/drawio-desktop#45]
Something I have struggled to draw recently is event storming diagrams:

![brandolini_everythingflattened](https://user-images.githubusercontent.com/1964655/41868241-627f4136-78ad-11e8-8912-9da26ec2db22.png)

It would be awesome if a toolbox was available in `draw.io` with templates for `Command`, `Aggregate` and `Event` post-it notes.

**Comment by davidjgraph** [comment]
What's the difference between the 3 shapes, just the colours?

**Comment by ghisvail** [comment]
The colors mostly. There is also the `personna` post-it (top-right), which always contain a human and an optional description of his role under it.

**Comment by davidjgraph** [comment]
Moved to https://trello.com/c/2EkYC8Or/392-event-storming-diagrams, not specific to desktop version.

**Comment by jaideeprana** [comment]
@ghisvail On a different note, do you an example where the "UI" is explained in the context of event storming?

An example of the same would really help.
