### ISSUE TITLE
Cannot create new diagrams

### ISSUE THREAD

**Issue by iloving** [jgraph/drawio-desktop#451]
### Preflight Checklist

* [ X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I just updated to 14.1.4, and I can no longer make a new diagram.  When I choose a template (in my case, one of the network templates), instead of opening a new window with the template showing, it goes into an infinite loop of file save dialog windows.  Every filename I give produces a zero byte file, but I just get another file chooser dialog instead of the workspace window.

**To Reproduce**
1.  Upgrade existing install, or install fresh copy of 14.1.4
2. Create a diagram
3. choose template and click create

**Expected behavior**
When I click create, I should see a new draw.io editor workspace with the template showing.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
14.1.4

**Desktop (please complete the following information):**
Mac OS 10.15.7

**Additional context**

**Comment by davidjgraph** [comment]
Yup, we're aware, a new build is currently in testing.
