### ISSUE TITLE
drawio-desktop snap package : texts are turning into boxes in the file manger when tried to open files

### ISSUE THREAD

**Issue by rohittz** [jgraph/drawio-desktop#452]
- [x]  I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Description**
After installing drawio through snap package, if I select 'Open existing diagram' , all the texts of the file manager turn into boxes. 

**To Reproduce**
1. Open drawio installed through snap package. 
2. Click on 'Open existing diagram'

**Expected behavior**
I have also tried deb package(14.1.5 and also older versions) to install drawio which works good 

**Screenshots**
![Screenshot_01_01_2_2021](https://user-images.githubusercontent.com/72378355/103438204-e9e81200-4c5a-11eb-908c-e922936f6de3.png)

**draw.io version**
- 14.1.5

**Desktop**
 - Ubuntu 20.10

**Comment by davidjgraph** [comment]
Duplicate #368
