### ISSUE TITLE
SHASUM does not match for draw.io-arm64-14.1.5.dmg

### ISSUE THREAD

**Issue by pekcheey** [jgraph/drawio-desktop#453]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
from the file latest-mac.yml
the shasum should be  
 
```
- url: draw.io-arm64-14.1.5.dmg
    sha512: wrWinSRqTn6jYb9xP0VSd0mrXDHgQ63pewqOzT8tB7sL7QKy5lOOLHlw84YWZfVo3z4VC8Y0qobdXYDKhVniNg==
```

my computation of the shasum showed a different hash.
```
> shasum -a 512  ~/Downloads/draw.io-arm64-14.1.5.dmg
c2b5a29d246a4e7ea361bf713f45527749ab5c31e043ade97b0a8ecd3f2d07bb0bed02b2e6538e2c7970f3861665f568df3e150bc634aa86dd5d80ca8559e236  /Users/caycepek/Downloads/draw.io-arm64-14.1.5.dmg
```

**Expected behavior**
the hash in the provided file and what shasum -a 512 produced should match.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 114.1.5 

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Big Sur 11.1]

**Additional context**
```
> file /usr/bin/shasum
/usr/bin/shasum: Perl script text executable
> which perl
/usr/bin/perl
> file /usr/bin/perl
/usr/bin/perl: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/perl (for architecture x86_64):        Mach-O 64-bit executable x86_64
/usr/bin/perl (for architecture arm64e):        Mach-O 64-bit executable arm64e
```

**Comment by davidjgraph** [comment]
Still an issue with 14.1.8?

**Comment by pekcheey** [comment]
seems like the hash is still not matching up. perhaps I'm using the wrong command?

```
~/Downloads> openssl dgst -sha512  ~/Downloads/draw.io-arm64-14.1.8.dmg
SHA512(~/Downloads/draw.io-arm64-14.1.8.dmg)= c734d99a4e0334f2d2d834542bee453ad292091051d21b97cf468a021774efc9cf578617e4a968c06f762b4e5b3c7b45fe8bf0aad7be7a5541b3de0e05495db8
~/Downloads> cat latest-mac-2.yml  | ag draw.io-arm64-14.1.8.dmg -A3
  - url: draw.io-arm64-14.1.8.dmg
    sha512: xzTZmk4DNPLS2DRUK+5FOtKSCRBR0huXz0aKAhd078nPV4YX5KlowG92K05bPHtF/ovwqte+elVBs94OBUlduA==
    size: 114605294
~/Downloads> ls -ltra draw.io-arm64-14.1.8.dmg
-rw-r--r--@ 1  ~  staff  114605294 Jan  4 01:34 draw.io-arm64-14.1.8.dmg
```

**Comment by ashrafteleb** [comment]
@pekcheey Electron builder uses base64 to encode the sha512 binary hash. Using the code in https://github.com/electron-userland/electron-builder/issues/3913 The results is matching for 14.1.8
