### ISSUE TITLE
SHASUM does not match for draw.io-ia32-14.1.5.exe

### ISSUE THREAD

**Issue by NulAsh** [jgraph/drawio-desktop#454]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
from the file latest.yml
the shasum should be
```
    sha512: ynrUDEPHdyvJtF++gysxF9HqWvTgcVgwkJWyqVY2GIioKnaMX4Zuw+IW3UI+D3CKfTx8kMM0Y/H1PkB/imDedA==
    size: 72455998
```
But instead filesize is 72462320 and shasum is
```
SiwX8j0gO+i3iHlPpfuXk2BiEewE6xRSqd55RQiwaiPu3QT2A1bLiJDWmXQfuufcEhEDaoANBQroButYtbGcMg==
```

**Expected behavior**
Filesize and hash should match.

**Screenshots**
![image](https://user-images.githubusercontent.com/32499449/103457974-46573a00-4d0c-11eb-8ef3-997d9b8e5d1a.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- 14.1.5

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by ThomasOwens** [comment]
Although it's not a good fix, I was able to install the latest version by downloading the installer and running it. It appeared to default to overwriting the previous installation, so pretty much the same result as updating the application. The update from inside the application should work, but this can perhaps get some people updated to the latest version until this issue is resolved.

**Comment by davidjgraph** [comment]
We had the same problem with the x64, build, so we've switching to copy that naming. The windows builds have to be signed on initial installation, but signing the updates messes up the SHAs. The update, https://github.com/jgraph/drawio-desktop/releases/download/v14.1.8/draw.io-ia32-14.1.8.exe, is no longer signed from 14.1.8.

To make the initial install, use https://github.com/jgraph/drawio-desktop/releases/download/v14.1.8/draw.io-ia32-14.1.8-windows-32bit-installer.exe
