### ISSUE TITLE
Uncaught type Error : cannot read property X of undefined.

### ISSUE THREAD

**Issue by pekcheey** [jgraph/drawio-desktop#456]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When trying to drag a text box over another, 
an error pop up : Uncaught type Error : cannot read property X of undefined. 

**To Reproduce**
1. open up the attached document in draw.io-arm64-14.1.5.dmg
2. Try to drag box B over box A
3. See error

[testBug.drawio.gz](https://github.com/jgraph/drawio-desktop/files/5761633/testBug.drawio.gz)

**Expected behavior**
There should not be a error

**Screenshots**
![Screenshot 2021-01-03 at 9 13 18 PM](https://user-images.githubusercontent.com/1754160/103479545-5739a580-4e09-11eb-8667-3f4f7942cdd5.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version : diagrams.net 14.1.5

**Desktop (please complete the following information):**
 - OS: OSX 11.1 Big Sur

**Additional context**

**Comment by pekcheey** [comment]
the error does not exist in https://github.com/jgraph/drawio-desktop/releases/download/v14.1.4/draw.io-arm64-14.1.4.dmg

**Comment by Space-jerk** [comment]
Good morning. 
<img width="1440" alt="Screen Shot 2021-01-03 at 8 17 38 AM" src="https://user-images.githubusercontent.com/76059292/103481362-1ce7ee00-4da0-11eb-8a59-d60fc9b8794f.png">

**Comment by Space-jerk** [comment]
I had this issue when trying to use my shape libraries. Only some of the shapes. I reverted to previous version and everything was fine. No issues on browser version on Mac app. Thank you for this wonderful software!

**Comment by davidjgraph** [comment]
Try 14.1.8.

**Comment by pekcheey** [comment]
version 14.1.8 resolved it for me. I'll close the ticket. 
Thank you for the prompt fix!

**Comment by Space-jerk** [comment]
Version 14.1.8 Fixed the issue! Thank you so much! Incredible software

**Comment by aulyeah** [comment]
> 

how to download or access the version 14.1.8 of draw.io ?
