### ISSUE TITLE
Export elements as SVG, then import to word file "Viewer does not support full SVG 1.1"

### ISSUE THREAD

**Issue by hestyle** [jgraph/drawio-desktop#459]
export some elements to svg file, 
then import to a word file, 
the svg element will show a text "Viewer does not support full SVG 1.1"
![image](https://user-images.githubusercontent.com/44233477/103863622-28b71580-50fc-11eb-9292-b1dfa1482687.png)
![image](https://user-images.githubusercontent.com/44233477/103863704-45ebe400-50fc-11eb-8e71-c863c3909d57.png)

drawio edition 14.1.8
word edition 16.44(20121301)
system edition Mac OS Catania 10.15.2

I hope that you can deal with this problem as soon as possible. Thank you very much！

**Comment by davidjgraph** [comment]
It's nothing to do with us, your viewer doesn't support the full SVG 1.1 specification.

**Comment by RogerH7** [comment]
> export some elements to svg file,
> then import to a word file,
> the svg element will show a text "Viewer does not support full SVG 1.1"
> ![image](https://user-images.githubusercontent.com/44233477/103863622-28b71580-50fc-11eb-9292-b1dfa1482687.png)
> ![image](https://user-images.githubusercontent.com/44233477/103863704-45ebe400-50fc-11eb-8e71-c863c3909d57.png)
> 
> drawio edition 14.1.8
> word edition 16.44(20121301)
> system edition Mac OS Catania 10.15.2
> 
> I hope that you can deal with this problem as soon as possible. Thank you very much！

看这个https://desk.draw.io/support/solutions/articles/16000042487
按照下列操作来：
Right click on a blank area of the drawing canvas, then choose Select All from the context menu.
In the Text tab of the format panel, uncheck the Formatted Text option.
Right click on a blank area of the drawing canvas, then choose Select Vertices.
In the Text tab of the format panel, uncheck the Word Wrap option.

**Comment by davidjgraph** [comment]
23.0.2 now replaces the warning text with a high-res image of the label, if embed images and embed fonts are ticked in the SVG export dialog.
