### ISSUE TITLE
Problem: Viewer does not support full SVG 1.1

### ISSUE THREAD

**Issue by Hubie510** [jgraph/drawio-desktop#461]
Hallo,
I am new here and I am a beginner:

I use Draw.io as desktop version with Mac (10.15.7).
When I create an image with links, export it as svg, then in the svg code appears the information:
Viewer does not support full SVG 1.1
So the image and the important link is not visible in the html.page. When exporting as image, the links do not work.
Is there a solution to this?
Thanks and greetings

Hubie

**Comment by mararad** [comment]
Hi,

My suggestion would be to take a look at this article here: https://www.diagrams.net/doc/faq/svg-export-text-problems 
and discussion: https://github.com/jgraph/drawio/issues/774 
They could be helpful.

P.S When a diagram is exported as an image, links are not supported. Also,you might consider exporting as PDF if it is possible in your case.

Kind regards,

**Comment by Hubie510** [comment]
Hi Mararad,
thank you. Too bad. I had hoped there is a better solution than pdf. Then draw.io would be perfect.
Thanks again for the feedback
many greetings

**Comment by davidjgraph** [comment]
If the SVG is being viewed using Inkscape, the suggested workaround is to export to PDF and import that PDF to Inkscape.

**Comment by davidjgraph** [comment]
23.0.2 now replaces the warning text with a high-res image of the label, if embed images and embed fonts are ticked in the SVG export dialog.
