### ISSUE TITLE
DPDT shape does not export to PNG/JPEG but to PDF

### ISSUE THREAD

**Issue by friedl-ap** [jgraph/drawio-desktop#464]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The shape "DPDT" from the "Electrical / Switches and Relays" does not export to PNG/JPEG but to PDF.

**To Reproduce**
1. Add different shapes to sheet, including the mentioned DPDT shape.
2. Export to PNG, JPEG and PDF
3. The DPDT shape is not shown in the exported PNG/JPEG files, but is shown in the exported PDF.

**Expected behavior**
Regardless of method of export, all shapes contained should be exported to whatever output format is selected.

**Screenshots**
See attached ZIP-file for example sheet and exports.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io desktop version 13.6.2 and 14.1.8

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise LTSC (1809)

**Additional context**
[draw.io-bugreport.zip](https://github.com/jgraph/drawio-desktop/files/5803950/draw.io-bugreport.zip)

**Comment by mararad** [comment]
Reproduced in desktop version 14.1.8 and Win 10 Pro

**Comment by davidjgraph** [comment]
Working on Windows and MacOS using 24.5.3.
