### ISSUE TITLE
Disable update check on Computer level

### ISSUE THREAD

**Issue by DanielSjogren** [jgraph/drawio-desktop#467]
Most companies have users without administrative rights and if Draw.io prompts for an available update, it will create tickets to service desk.
The timing to include the flag in the config file is hard, the user probably starts the app before IT can deploy it. 

I would suggest having a central config file that overrides the user settings, or a config file that is inherited on first launch.

**Comment by PierreLev** [comment]
Following

**Comment by wolfmar** [comment]
While not exactly the most elegant solution, I found that you can set a global environment variable to disable the update check:
```
setx /M DRAWIO_DISABLE_UPDATE true
```

**Comment by davidjgraph** [comment]
Maybe better, try to determine if user is admin on the computer and disable update for installable versions. https://stackoverflow.com/questions/3600322/check-if-the-current-user-is-administrator

**Comment by davidjgraph** [comment]
24.5.1 adds the startup parameter --disable-update.
