### ISSUE TITLE
can't edit file

### ISSUE THREAD

**Issue by guwf563** [jgraph/drawio-desktop#468]
I can't edit my diagram file anymore. It is create and draw bymyself,but after a few day later , it become uneditable.
![image](https://user-images.githubusercontent.com/30889358/104806516-0798a800-5813-11eb-8bf0-365bc822cb80.png)

**Comment by davidjgraph** [comment]
The selection parts of the menu are disabled?

What desktop version is it? What operating system? How do we recreate this, what are the exact steps? Do you have multiple layers and there is nothing on the current layer?

**Comment by chinaturkeyfarm** [comment]
The Layer being locked is the issue for me, thanks for the tip!
