### ISSUE TITLE
Almost Daily Updates to Win App

### ISSUE THREAD

**Issue by eightbit** [jgraph/drawio-desktop#469]
Thanks for this excellent program! It has been a game changer for me to document our infrastructure. The Windows app has been updating almost everyday lately. Are you pushing out a lot of updates or might there be a problem w/my install?
Installed version is 14.1.8

Thanks again.

**Comment by mararad** [comment]
Hi, 

thanks for the nice words :) 

All the desktop releases can be seen here: https://github.com/jgraph/drawio-desktop/releases The last one was released 15 days ago. 
What OS are you using? Is it possible to send a print screen when it starts updating?

Thanks,

**Comment by mararad** [comment]
P.S and this one please. How did you install it?  If you are a Win user and have admin rights on the machine, did you use "Windows Installer" or "Windows No Installer"?

Thanks,

**Comment by flospi** [comment]
I had the same happening here... Some version 13 was installed and on every start of draw.io it told me that an update was available. So I let it install the update... couple days later the same... it always tried to update to 14.1.8 but never succeeded, even though there was no error. So i just downloaded the 14.1.8 Windows Installer and just ran it and installed it on top in the same folder. For now the constant update is gone.

**Comment by eightbit** [comment]
I used the Windows Installer with admin rights
Screen grab attached. I'll reinstall on top and see if the problem goes away.

![draw io_updateRequest](https://user-images.githubusercontent.com/5913748/105135368-890f6500-5ab5-11eb-86f0-0705f8b4339d.png)

**Comment by eightbit** [comment]
This has not recurred since reinstalling the current version.
