### ISSUE TITLE
Sign Draw.io.exe

### ISSUE THREAD

**Issue by DanielSjogren** [jgraph/drawio-desktop#470]
Draw.io.exe not signed, many companies utilize security features like AppLocker and best way is to whitelist Publisher to approve the application.

**Comment by davidjgraph** [comment]
The exe is the updater, use the signed installation exes linked in the top comment.

**Comment by DanielSjogren** [comment]
I know the installers are signed, but not the actual application. This is what companies whitelist to be able to run/start, not installers.

![image](https://user-images.githubusercontent.com/40316868/105010936-9fc5a580-5a3c-11eb-8dc4-3851f017e143.png)

**Comment by davidjgraph** [comment]
there's a signed no installer version. We cannot sign the exe, that's only used for updating.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio-desktop/releases/download/v14.1.8/draw.io-14.1.8-windows-no-installer.exe

**Comment by DanielSjogren** [comment]
I have tried the "No Installer" edition, but when the exe unpacks to the Temp folder, it still launches the unsigned draw.io.exe
Why do you say "it's only used for updating"? That exe is still the file you launch to start the application.

Most companies sign their executables. No companies want to allow %TEMP%\*\Draw.io.exe

**Comment by davidjgraph** [comment]
The update process break if we sign that one. Lots of users have managed to automate this process, I would suggest to post on another thread asking others how they have done it.
