### ISSUE TITLE
libXtst -  broken package dependancies ?

### ISSUE THREAD

**Issue by marcoczen** [jgraph/drawio-desktop#472]
Hi ...

Package dependancies of this package ( draw.io rpm )   are broken ?

`` 
rpm --requires -qp draw.io-x86_64-14.1.8.rpm 

/bin/sh
/bin/sh
at-spi2-core
gtk3
libXScrnSaver
libXtst
libnotify
libuuid
nss
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
xdg-utils
``  

The dependencies should require libs, not package names ?

Lines like

  Requires: libXtst 

should be removed from specfile. Instead it should be 

  AutoReqProv:    on

(which will result in proper libs requires) if it's not even yet the
default. Maybe in the spefile even

  AutoReqProv:    off

is set which would be totally wrong.

Note -> draw.io version - latest - .14.1.8
         -> OS:- OpenSuse Leap 15.x

The above is from info provided by sn******@suse.de

Thanks.

**Comment by davidjgraph** [comment]
I don't see any error message, what's the problem here? Does it not install?

**Comment by marcoczen** [comment]
> I don't see any error message, what's the problem here? Does it not install?

Hi ... Yes, draw.io will not install on a OpenSuse 15.1/15.2 as it requires libXtst but these distros provide libXtst6. When i contacted the  Stefan at suse.de, he ran the above command and told me the dependencie were broken and that i should inform the github repo for this software. 

I have his email ... Should I pm you ?

**Comment by davidjgraph** [comment]
No, I have no idea how rpm works. The information needs to go here to wait for someone who does.

**Comment by marcoczen** [comment]
Ok. Noted. Pls let me know if i am in the worng place. I downloaded the rpm from 
https://github.com/jgraph/drawio-desktop/releases/tag/v14.1.8

**Comment by davidjgraph** [comment]
Yes, this issue tracker is the right place to post.

**Comment by marcoczen** [comment]
Update from  sn******@suse.de

Lines like

  Requires: libXtst 

should be removed from specfile. Instead it should be 

  AutoReqProv:    on

(which will result in proper libs requires) if it's not even yet the
default. Maybe in the spefile even

  AutoReqProv:    off

is set which would be totally wrong.

**Comment by davidjgraph** [comment]
Thanks. Just to clarify we use https://github.com/electron-userland/electron-builder to build the rpm. We don't have any experience with rpm, so an external contribution is likely needed in order to fix the issue.

**Comment by marcoczen** [comment]
I have sent email to sn******@suse.de requesting his assistance. Lets see.

**Comment by sndirsch** [comment]
I don't know electron-builder RPM build system. No idea how it works. If you don't provide a specfile for it I don't know how this issue could be fixed without changing electron-builder. I can only repeat, what the reporter already wrote:

The dependencies should require libs, not package names!

Lines like

Requires: libXtst

should be removed from specfile. Instead it should be

AutoReqProv: on

(which will result in proper libs requires) if it's not even yet the
default. Maybe in the spefile even

AutoReqProv: off

is set which would be totally wrong.

**Comment by davidjgraph** [comment]
Thanks for taking the time to look. We'll see whether electron builder can input this file.

**Comment by sndirsch** [comment]
BTW, usually the openSUSE community provides packages for a software, which then gets built via our buildsystem on build.opensuse.org, if there is any user using this software and there is someone in the openSUSE community building this software as package.  It is news to me that github generates RPM packages.

**Comment by marcoczen** [comment]
Hi ... Thanks for chipping in. 

> I don't know electron-builder RPM build system. No idea how it works. If you don't provide a specfile for it I don't know how this issue could be fixed without changing electron-builder. I can only repeat, what the reporter already wrote:
> 
> The dependencies should require libs, not package names!
> 
> Lines like
> 
> Requires: libXtst
> 
> should be removed from specfile. Instead it should be
> 
> AutoReqProv: on
> 
> (which will result in proper libs requires) if it's not even yet the
> default. Maybe in the spefile even
> 
> AutoReqProv: off
> 
> is set which would be totally wrong.

**Comment by marcoczen** [comment]
> I have sent email to sn******@suse.de requesting his assistance. Lets see.

He is here ... Sounds omnious ... Like Galactus coming to earth ... hehehehehe

**Comment by marcoczen** [comment]
Hi ... any update on this ?
If this is the wrong way to ask, pls delete the comment.

**Comment by davidjgraph** [comment]
Any updates will be posted in the thread. If nothing is posted you can assume there are no updates...

**Comment by marcoczen** [comment]
Closed as there seems to be no movement on this.

**Comment by thoschneider** [comment]
Unfortunately this issue still remains. I tried to install draw.io on openSuse 15.2 and it requires libXtst but the distro provides libXtst6.
