### ISSUE TITLE
Wrong Line Position when exported to PDF

### ISSUE THREAD

**Issue by floriab** [jgraph/drawio-desktop#474]
Dear all,
I played around with the line thickness and alignment.

The preview seems correct:
![preview](https://user-images.githubusercontent.com/28810330/105382362-4615d480-5c10-11eb-8866-2046d7d3e8d4.png)

There are three big boxes with linewidth 1pt, 2pt and 3pt.
The small boxes do have a linewidth with 1pt.

When exporting to pdf, the middle box seems slightly shifted.
[bug-crop.pdf](https://github.com/jgraph/drawio-desktop/files/5850791/bug-crop.pdf)

When looking closer to this problem, it showed up that the Lines of the big Box with 2pt are not exported correctly,
they are slightly shifted compared to the preview in the drawio program.

System: Ubuntu 18.04.5 LTS
Version: diagrams.net 14.1.8

**Comment by mararad** [comment]
Hi, 

I opened the PDF you sent and not sure I see the issue you are talking about. Could you mark it somehow and send a print screen of it, please"? Also, attach a draw.io file here so we could test it.

Regards,

**Comment by floriab** [comment]
I pasted the problem in a screenshot:

![Screenshot_20210122_125047](https://user-images.githubusercontent.com/28810330/105488260-a3159700-5cb1-11eb-9e89-290b399a4110.png)

Here is the draw.io file:
[bug.zip](https://github.com/jgraph/drawio-desktop/files/5855583/bug.zip)

I hope you can see now the problem. The middle box is shifted by about 0.5 pt to the left in the pdf file, caused by the different line thickness.

**Comment by davidjgraph** [comment]
Still repeatable on latest?

**Comment by floriab** [comment]
Yes, still present in 15.8.7
