### ISSUE TITLE
A Zen Mode 🏞️

### ISSUE THREAD

**Issue by d4g0** [jgraph/drawio-desktop#477]
* [✅ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [✅ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**It's not a problem**
It's just geting further. Going to a spot where there is no more interface then your thoughts . Like the "zen" mode of Adobe Illustrator, where all interface elements disapperars. It just left the blank page  and the things you are creating.

**What im thinking**
A full screen mode where all interface elements gets hidded. And the user it's able to spawn things using the  key-board commands. And optionally open individual tools windows like `shapes` and `format` (wich shuold collapse the second we useit 😉️).

**Additional context**
I really like what have been crafted so far. I think this is an amaizing tool. 
I know that achieve what im proposing  will need tons of hard work, wich i will be happy to help 😁️. To start we need to land a key-board shortcuts setting to customize all the actions we can. And some other ones. Let me know what you think. I have tons of Ui/Ux enhacements ideas.

**Comment by YukinoHayakawa** [comment]
I also like the idea of a fullscreen mode, but with the option of showing necessary toolboxes. The window titlebar+native menu+app menu+OS taskbar really wastes vertical space compared with the web version which I can make it fullscreen. Besides, the zooming level of the desktop version can't be changed (a separate issue though). These together make the desktop version much less spatially efficient.

**Comment by eodeluga** [comment]
Along these lines, a side panel autohide could be very useful too.
