### ISSUE TITLE
Not a diagram file. Extra content at the end of the document

### ISSUE THREAD

**Issue by kendoori** [jgraph/drawio-desktop#478]
### Preflight Checklist

**Describe the bug**
Opening a draw.io file that I created in the past on a different computer displays error messages:

Error Loading file
Not a diagram file (error on line 1 at column 1673: Extra content at the end of the document)

**To Reproduce**

1. Launch draw.io (either desktop or browser version)
2. Open file

**Expected behavior**
File opens normally

**Screenshots**
![ksnip_20210125-113507](https://user-images.githubusercontent.com/2447420/105735784-1ada0080-5f02-11eb-89e3-a299d542b326.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
14.1.8

**Desktop (please complete the following information):**
 - OS: Linux Mint 20 

**Additional context**
The file has exactly 1 row with 1673 columns. Am uploading the problem file.
[caresight platform 2019.drawio.zip](https://github.com/jgraph/drawio-desktop/files/5868030/caresight.platform.2019.drawio.zip)

**Comment by davidjgraph** [comment]
Do you see it at https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1#R1Vldk9smFP01frRHgD6sR1trt8kkzSZOmukjkbDNBAkFodrbX9%2BLhCR7Ze80M%2BsG68FGlwsXOIcDgglJ8uNvipb79zJjYoK97DghDxOMURx78GcsT9aCfGvZKZ5Z22DY8H%2BYNXZuNc9YdeaopRSal%2BfGVBYFS%2FWZjSolD%2BduWynOo5Z0x0aGTUrF2PqVZ3rfWuc4Guy%2FM77bd5FRGLc5Oe2cbU%2BqPc3k4cREVhOSKCl1m8qPCRNm9Lpxacutr%2BT2DVOs0P%2BlwPRNof1FmX%2F%2BEgYf%2F%2FqY%2Fln9sZ3aWv6morYdTqDCTdMh7H1Q6Z5VWlHN4G06MRFCAdGWVUkL0yf9ZAcq%2FFGbjiy3stDTgx2RBbgUUuVUDA6Q2tn%2FpibeGd7Kb%2BC%2BgYhZLXixa6PRvIS89hcs72XBtVRNdlseOsyf1wm2toGdGZ%2B1FQMUpUmqhjFLJesiY2aYELwd9lyzTUlT43EAWoNtr3Nhs3sYPfOilfzOEimkamom6%2BYx48CFOLEzlAUsMj1RqSU58exw2Xfkt%2BOaQufesa3BNIg6F9t20wAq%2BK6AtGh8muxLDbDAMqXZ8SpjUM9DmMFM5kyrJ3CxBaJw5s%2FbQnb6hsSbYTSPgtZ6GGYEieNZgL3h8VuX%2FcnkiPAsxLYotfNy10cdqAsJy96fYDK%2ByORHyQvD5E%2BMZkzdnsQbWavUTJYHqmkTtxQ8pZrLwkHCFrJgY66G%2FnK5wq%2FC1WvkfMbh1%2BCq%2F5yrJJqhoOebS1QlI6qiq4hDdbDUGZRKpjjEZ2qwPg6mU3TMOI2geFm3ts0z5gLyIhKv%2BhLdEuiPse1r6LBNAbmmZa%2BAbreGdruIeAQq8uazODwBFY1BbXxIFDz3eXWA%2FRe16KtU37cCsLi5Gn2qBeydLq2jH2pd1qYxq2LHQQTuRZvW84TM71%2BbUBDMUOTmQhqMyItdVac1jglyT51g5fEuLz1OqVT4skoprv%2BPHdNnRYtqC97Qhy9l1n5qJELWmd1FfaOVEbF7EShvvpqjuxcoHJGZm%2FIUjVhLXJWnxcpHBLsmTxjWHo8g19VpPsK5m%2B9m7K6LUNXAaCQI%2BeVxLECnGneiPbeWuUclU1ZVw5chhG2%2FD6XSP3uc0ZvboXBB94KHaB3Hd697JEYzbGaHH7eP754CxqOZ4buqgJj4fvDgmgISWNw8P7y0vDklgd0Z%2BJXT2UdQDqM9t5auVZFN66rZC%2FYhx1%2BUiyznJjI3sG2NrtzLli1ESZis7l66Ai929WwWja8ZAlclC%2BHFYhm4Jlk%2BrEue81%2BUaHwIH%2F5qnK%2FdyMRhRBbhRZxHeN7wjqU7XOkuWBD%2BpTjD63Aj2eSdXOyS1b8%3D

?

**Comment by kendoori** [comment]
> If yes, edit it with the pen icon and carry on working on it.

Thank you. It worked. What did you do?

**Comment by alderg** [comment]
There was a missing closing tag in the file. Please update to the latest version.

**Comment by kendoori** [comment]
I have updated, but I do have some older files that I've created that are
likely to spawn similar issues. What is the syntax of the closing tag in
case I need to add myself?

**Comment by alderg** [comment]
In this case we had to append `</mxfile>`

**Comment by HenrikM1** [comment]
As of February 2023, this bug still persists. It affects new files in version 20.8.10.

https://github.com/jgraph/drawio-desktop/issues/1218

Looks like some extra tags are appended at the end of the file.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/90210437/221925580-bd651ad4-5518-4ac3-9231-60c72646af02.png">

**Comment by PracheLaclaree** [comment]
Hello, I would like to raise the same issue on one of my diagram. When I open with notepad++ I don't see any tag or mxfile though...
I recently updated to 21.2.1 but it does not change anything...
[Diagramme_fabrication.zip](https://github.com/jgraph/drawio-desktop/files/11382635/Diagramme_fabrication.zip)

Please check the diagram attached and help if possible...! Thanks !

**Comment by alderg** [comment]
@PracheLaclaree Unfortunately, it was only possible to recover the first page of the file.
[Diagramme_fabrication.zip](https://github.com/jgraph/drawio-desktop/files/11382927/Diagramme_fabrication.zip)

**Comment by PracheLaclaree** [comment]
OK well most of the work is lost then... Do you know how to prevent this from happening ?

**Comment by alderg** [comment]
Was this stored in a folder that is synced with a cloud storage (eg. OneDrive, Google Drive, iCloud etc)?

**Comment by PracheLaclaree** [comment]
Yes it was stored in a folder that is synced with a cloud (nextcloud)

**Comment by davidjgraph** [comment]
Does nextcloud have revisioning for files? If yes, you can get a previous version that way.
