### ISSUE TITLE
Add a `Ctrl+Shift+Z` key shortcut to Redo (similar as `Ctrl+Y`)

### ISSUE THREAD

**Issue by F8ER** [jgraph/drawio-desktop#486]
Dear Draw.io,

I very much appreciate you for the project.

May I ask if it's possible to add a shortcut of `Ctrl+Shift+Z` combination for Redo functionality?  
Some may find the `Ctrl+Y` shortcut quite discomfort to use.

![](https://i.imgur.com/VmPAnkH.png)
Source: <https://drawio-app.com/wp-content/uploads/2016/11/draw.io_shortcuts_basic_win_EN.pdf>

Best and kind regards

**Comment by davidjgraph** [comment]
Where is this standard?

**Comment by serious-angel** [comment]
> Where is this standard?

Assuming I understood the question correctly, please check the following:
- <https://defkey.com/what-means/ctrl-shift-z>;
- <https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts>;
- <https://developer.mozilla.org/en-US/docs/Tools/Keyboard_shortcuts#source_editor>.

> In most Microsoft Windows applications, the keyboard shortcut for the undo command is `Ctrl+Z` or `Alt+Backspace`, and the shortcut for redo is `Ctrl+Y` or `Ctrl+Shift+Z`.

Source: <https://en.wikipedia.org/wiki/Undo>

**Comment by jessetmoody** [comment]
I too would appreciate this option! Adobe products use Ctrl+Shift+Z for Redo, which is much faster and more ergonomic.

Maybe a moonshot feature would be the ability to reassign any keyboard shortcuts. :)
