### ISSUE TITLE
Remove menu"draw.io" to maxmize the window for user  

### ISSUE THREAD

**Issue by oakwasp** [jgraph/drawio-desktop#487]
I am using draw.io（ v14.1.8). There is a button(or menu) named as "draw.io", which contains 3 sub-menu "website", "support" and "check for updates" . Can you please re-locate this menu and put it next to "file“， ”edit"， or "help "menu, so that we can save space for the user's window.

**Comment by ashrafteleb** [comment]
Unfortunately, this is not possible currently

Please follow this issue https://github.com/jgraph/drawio-desktop/issues/91
