### ISSUE TITLE
In the MacOS device, it is not possible to preview the contents of the drawio file quickly through the  space bar.

### ISSUE THREAD

**Issue by hzhgino** [jgraph/drawio-desktop#488]
I use MacBook. In most cases, you can quickly preview the contents of a file by selecting the file and clicking the space bar. You don't need to open the file to preview it. However, you cannot preview the drawio file with this operation. Hope to support this function as soon as possible.

**Comment by brant-ruan** [comment]
It would be awesome if draw.io could support preview with space bar :) I use DEVONthink to manage my important files but currently there's no way to preview draw.io files.

**Comment by davidjgraph** [comment]
We'd need support in electron-builder for this, https://github.com/electron-userland/electron-builder/issues/1223 .
