### ISSUE TITLE
MacOS custom keyboard shortcuts do not work 

### ISSUE THREAD

**Issue by maxsnts** [jgraph/drawio-desktop#489]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In Mac, Internal menu options Cut, Copy, Paste do not reflect the ones of the external OS app menu after OS change.
Because of this, even if we change the shortcuts keys on the OS, the new ones won't work.

**To Reproduce**
1. Go to MacOS keyboard settings
2. Click on add application shortcut to Cut,Copy,Paste
3. Both old (CMD-) and New stop sorking

**Expected behavior**
The internal menu should reflect (use) the external key shortcuts so that we could change them in the OS

**draw.io version (In the Help->About menu of the draw.io editor):**
v14.1.8 (and older)

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
I know that this is a niche request as not many people will need to change this shortkeys.
But, for the few of us that do, it would be nice.
Thank you

**Comment by davidjgraph** [comment]
A bit too niche to investigate.
