### ISSUE TITLE
Desktop shows Save As dialog first time when saving an existing PNG file

### ISSUE THREAD

**Issue by GolezTrol** [jgraph/drawio-desktop#49]
Windows desktop version. 
I love the "Include a copy of my diagram" for PNG files, so I can have diagrams which are editable, but are also ready for inclusion anywhere.

But when I press save for the first time after opening such a 'rich' PNG diagram, I get the save-as dialog instead of the diagram just being saved to the same file using the same settings. 

No biggie, but feels weird.

**Comment by alderg** [comment]
We're unable to reproduce this problem (the PNG saves for without showing the dialog). What are the steps to reproduce this problem? What operating system and version of draw.io are you using?
