### ISSUE TITLE
File open/save dialogs not on top of main window 

### ISSUE THREAD

**Issue by PhilipSiEn** [jgraph/drawio-desktop#491]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I start draw.io desktop version and click on "Open Existing Diagram" the file dialog opens behind the main window. I have to move the main window or select the file dialog from the task bar to make it visible. Additionally the taskbar icon has no text.

**To Reproduce**
- Start draw.io desktop app.
- Click "Open Existing Diagram"

**Expected behavior**
The file dialog appears in front of the main window.

**Version & OS**

diagrams.net 13.9.9

Betriebssystem: Debian GNU/Linux 10
KDE-Plasma-Version: 5.14.5
Qt-Version: 5.11.3
KDE-Frameworks-Version: 5.54.0
Kernel-Version: 4.19.0-14-amd64
Art des Betriebssystems: 64-bit
Prozessoren: 8 × Intel® Core™ i7-4810MQ CPU @ 2.80GHz
Speicher: 23,4 GiB Arbeitsspeicher

**Comment by mararad** [comment]
Hi, if you update desktop version to the latest 14.1.8 https://github.com/jgraph/drawio-desktop/releases 
does it help?

You could also click "Check updates" top left 
![updates](https://user-images.githubusercontent.com/44292306/107222936-d4ae9200-6a15-11eb-8be6-c37cbc777ee5.JPG)

**Comment by PhilipSiEn** [comment]
Unfortunately I cannot update due to issue #138.

**Comment by mararad** [comment]
Just found that the conversation on this topic was already opened https://github.com/jgraph/drawio-desktop/issues/430 so feel free to comment there and track the progress.

Thanks,

**Comment by mararad** [comment]
duplicated https://github.com/jgraph/drawio-desktop/issues/430
