### ISSUE TITLE
"Lock Object" possibility

### ISSUE THREAD

**Issue by maxsnts** [jgraph/drawio-desktop#494]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Is there a possibility that we "lock" objects so that they don't get selected, moved, altered?
When placing a background panel (rectangle) to create a division on the diagram, that panel is constantly being selected when if first click on an object that its on top of the panel.

**Describe alternatives you've considered**
It would be nice to be able to lock an item, so that it never got selected for changes unless unlocked.
It would be part of a selection to make a copy (drag select many elements, but would not accept changes)

Thank you

**Comment by maxsnts** [comment]
Forget it, i got it

For anyone with the same question:
You can turn off the properties "editable" and "movable" in the panel properties.

Thank you

**Comment by davidjgraph** [comment]
Edit->Lock ?

**Comment by maxsnts** [comment]
LOL, Nice.
I was looking at the context menu and never thought to look in the Edit Menu
Thanks.
