### ISSUE TITLE
using special characters in save dialog won't throw error

### ISSUE THREAD

**Issue by Stimmenhotel** [jgraph/drawio-desktop#495]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Trying to save a file with special characters won't show an error message, instead is will just not work.

**To Reproduce**
1. Create file
2. Eyport PNG
3. Give it a name with "?"
4. Try to save it

**Expected behavior**
Popup saying "Can't be saved, use name without special characters" or similar.

**Screenshots**
https://user-images.githubusercontent.com/15821524/107240241-fd408700-6a29-11eb-8a7d-16cdde784ccb.mp4

- draw.io version 14.1.8

**Desktop:**
 - OS: Win10
 - Firefox 85.0.1

**Comment by davidjgraph** [comment]
Moved to desktop repo.

**Comment by Stimmenhotel** [comment]
Thanks for moving, completely forgot there is a dedicated repo for the client.

(also.. Damn, I thought the mail answer would work better...)

**Comment by m-mohamedin** [comment]
It turned out it is a windows issue (feature?) that it allows * and ? in save/open dialog such that users can use them as wildcards to find files!

The same behavior in any other app
