### ISSUE TITLE
Math Typesetting doesn't work

### ISSUE THREAD

**Issue by Desjajja** [jgraph/drawio-desktop#496]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The DPI of the default export formats is lower than I expect, so I exported my diagrams through File -> Export as ->Advanced... to manually changed it to 300. And the formulas in it do not render anymore.
**To Reproduce**
1. Go to 'File'
2. Click on 'Export as'
3. Click on 'Advanced'
4. export in whatever format
5. See error

**Expected behavior**
I wish the formulas could be rendered normally when exported in "advanced" option

**Screenshots**
![image](https://user-images.githubusercontent.com/58029489/107457653-6987cb80-6b8d-11eb-871a-f0effef98f4c.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [14.1.8]

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Additional context**

**Comment by mararad** [comment]
Hi,

I tried to reproduce it with File > Export as > Advanced > PNG (with 300dpi) and draw.io 14.1.8 using the example here:
https://desk.draw.io/support/solutions/articles/16000032875-use-mathematical-typesetting-in-diagrams and all went well.

What format did you export to? Could you attach your file here? If you test with the example from the article do you see the same behaviour? Is it working in diagrams.net online?

**Comment by Desjajja** [comment]
How strange.... Things don't work well even if using those examples offered in the hypertext link. I attach the file containing my failed attempts there, hopefully that will help you figuring out what's wrong.
[bug report.zip](https://github.com/jgraph/drawio-desktop/files/5971768/bug.report.zip)

**Comment by mararad** [comment]
I recorded a video for you using your file. I am not able to reproduce the issue.
draw.io desktop version 14.1.8 and Win10 Pro

https://user-images.githubusercontent.com/44292306/107941788-873ca280-6f8a-11eb-8de4-354f1b4ca03f.mp4

Kind regards,

**Comment by no0777osum** [comment]
I have reproduced this problem on 18.0.1.

* use Dark Theme
* export PNG with uncheck "Dark" on the dialog

If use Default Theme, there are no problem.

**Comment by augustebaum** [comment]
Reproduced on 18.0.1 as well. Thanks @no0777osum!

**Comment by davidjgraph** [comment]
18.0.1 is too old, we'd need a repro on latest.
