### ISSUE TITLE
Weblink open with new tab.

### ISSUE THREAD

**Issue by Gerd88** [jgraph/drawio-desktop#498]
Hello,
Is it possible to make a text web link open in a new tap or window? 
If so, please write me a solution. 

Thx for the help.

**Comment by mararad** [comment]
Hi, 

What desktop app version are you using, please (can be seen under Help)
At the moment, links added to a shape or/and to text within a shape are opened in a new browser tab. 

Could you attach a video showing the behaviour you would like to change, please?

Thanks.

**Comment by Gerd88** [comment]
14.1.8

**Comment by Gerd88** [comment]
It works but if I make a svg file the link open inside the frame.

**Comment by mararad** [comment]
When you export as svg, links are opened in the same tab. As a workaround in this moment, they can be opened in a new tab via right mouse click > Open in a new tab
