### ISSUE TITLE
Editable PDFs

### ISSUE THREAD

**Issue by lokeller** [jgraph/drawio-desktop#499]
**Is your feature request related to a problem? Please describe.**

I would like to use drawio-desktop to create and maintain diagrams within a sphinx project that is rendered to pdf using latex. The simplest way to integrate diagrams in this kind of project is to export them to pdf. To do this I can currently export the diagrams to pdf, however I have to either manually keep in sync the pdf export with original diagram or have to run draw-io during the sphinx  build to convert the diagrams to pdf (which can be done thanks to sphinxcontrib-drawio but adds a lot of dependencies and is non-trivial within the docker-based build environment I would like to use).

**Describe the solution you'd like**

What I would like to ask is the addition of a menu option in draw.io desktop to save the diagram embedded in a pdf (similar to the "editable png" and "editable svg" options.

**Describe alternatives you've considered**

There are a few other ways to solve my problem:

- perform a manual export of the pdf alongside the diagram
- perform an automatic conversion of the diagram to pdf using the draw.io in cli mode (however to view the diagrams one has to install draw.io)
- use editable pngs (but this will cause loss of quality in final output)
- use editable svgs and add some sort of svg to to pdf conversion in the build (but doesn't really work well due to the advanced svg features used by draw.io as explained in https://www.diagrams.net/doc/faq/svg-export-text-problems)

**Additional context**

I noticed that on the web version of the editor it is possible to create an editable PDF by using the export feature and selecting "Include a copy of my diagram". I also noticed that the desktop version is able to read such "editable pdf" diagrams. However, the desktop version doesn't seem to present an option to export the diagram within the pdf.

**Comment by ashrafteleb** [comment]
Editable pdf will be available in next version (export only [in GUI and CLI]). I think this would be enough as adding it as a save format is heavy as PDF export takes noticeable time

**Comment by lokeller** [comment]
I tried the feature in the latest snap and works like a charm! Thanks a lot for implementing this feature, it makes draw.io desktop even more awesome :)

**Comment by lester1027** [comment]
Hi, I would like to know if the diagrams will lose some properies when I only keep the pdf versions of them.
