### ISSUE TITLE
Drive integration

### ISSUE THREAD

**Issue by kakawait** [jgraph/drawio-desktop#5]
Maybe stupid question but I used tu use draw.io inside browser and everything is store inside drive.

When I tried Electron Desktop app, the way I find to load existing document is from system Filesystem.

**Comment by davidjgraph** [comment]
At the moment the application is loaded from file:// internal so it isn't possible to load cloud based storage, the domain won't match.

**Comment by davidjgraph** [comment]
With the security improvements in the next release, this won't be possible.

**Comment by AlphaKennyBudy** [comment]
So is it possible to sync with drive on desktop?
