### ISSUE TITLE
Cancelling Save dialog results in error message

### ISSUE THREAD

**Issue by GolezTrol** [jgraph/drawio-desktop#50]
When cancelling the Save dialog on Windows desktop, I get an error message: "Error saving file - Unknown error".

After closing the error everything works as normal, so it's not a big problem, but it just seems like this cancel flow is not covered completely.

![unknown_error](https://user-images.githubusercontent.com/1395222/44456484-f676ed00-a600-11e8-82d4-34606e0aec7a.png)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
