### ISSUE TITLE
'Not a diagram file' File corruption

### ISSUE THREAD

**Issue by HeartandSeoulXVI** [jgraph/drawio-desktop#501]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
A quite large file of mine has been seemingly corrupted and deleted. After the program CTD'd, the save file now shows a size of 0 bytes and when loading it using diagrams.net desktop the message 'Error loading file: Not a diagram file' is shown.

The version I am using is 13.0.3 and I see no option to review version history or restore older versions of files.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by davidjgraph** [comment]
Unfortunately, older versions of the desktop tool didn't save a second draft autosave in the case of file corruption. It was added early in the 13.x series. Updating to the latest version will give you this function.
