### ISSUE TITLE
Support embed images for SVG export in command line

### ISSUE THREAD

**Issue by houqp** [jgraph/drawio-desktop#502]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When exporting diagram as SVG, the web UI allows me to select an option to embed images. I would like to be able to specify the same requirement when exporting SVGs through command line. Something like this:

```
drawio -x --embed-images -o foo.svg docs/foo.drawio
```

**Describe alternatives you've considered**
Currently, exports have to be done manually through GUI.

**Additional context**
N/A

**Comment by mararad** [comment]
@houqp there is a feature request already created here: https://github.com/jgraph/drawio-desktop/issues/382 so feel free to comment and track it there.

Regards,

**Comment by mararad** [comment]
duplicated https://github.com/jgraph/drawio-desktop/issues/382
