### ISSUE TITLE
Export a graph to png

### ISSUE THREAD

**Issue by ehurt** [jgraph/drawio-desktop#503]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Additional context**

**Comment by ehurt** [comment]
Currently I am using a older mxgraph jar. The version mxgraph-core-3.2.0. The xml is <mxGraphModel>. I am using mxCellRenderer to generate the image, but I get an empty image. 

			mxGraph graph = new mxGraph();
			Document document = mxXmlUtils.parseXml(xml);
		
			mxCodec codec = new mxCodec(document);
			codec.decode(document.getDocumentElement(), graph.getModel());
			
			BufferedImage image = mxCellRenderer.createBufferedImage(graph, null,
					1, Color.WHITE, true, null);
			
			
			screenShot = Files.createTempFile("flowChartScreenShot", FORMAT).toFile();
			ImageIO.write(image, FORMAT, screenShot);

**Comment by davidjgraph** [comment]
This does not relate to draw.io desktop.
