### ISSUE TITLE
.deb dependency on libappindicator3-1 not available on Kali Linux

### ISSUE THREAD

**Issue by laomaiweng** [jgraph/drawio-desktop#504]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

On Kali Linux (`kali-rolling`), `libappindicator3-1` is no longer available since 2021-01-19 (see https://pkg.kali.org/pkg/libappindicator#, it's also been moved to the _oldlibs_ package subsection in Debian Sid). Apparently, `libayatana-appindicator` should be used now (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037).

Installation of the draw.io .deb package (v14.1.8) can be forced with `dpkg -i --force-depends` and draw.io seems to work, so this is not a big issue, but I guess it's worth mentioning at least.

**Comment by frankgerhardt** [comment]
Same on Debian 10.

```
# dpkg -i drawio-amd64-14.5.1.deb 
Selecting previously unselected package draw.io.
(Reading database ... 262410 files and directories currently installed.)
Preparing to unpack drawio-amd64-14.5.1.deb ...
Unpacking draw.io (14.5.1) ...
dpkg: dependency problems prevent configuration of draw.io:
 draw.io depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.

dpkg: error processing package draw.io (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for shared-mime-info (1.10-1) ...
Errors were encountered while processing:
 draw.io
```

And then to fix it:

```
# apt-get install -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libappindicator3-1 libindicator3-7
The following NEW packages will be installed:
  libappindicator3-1 libindicator3-7
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 106 kB of archives.
After this operation, 217 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://deb.debian.org/debian buster/main amd64 libindicator3-7 amd64 0.5.0-4 [52.9 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 libappindicator3-1 amd64 0.4.92-7 [53.5 kB]
Fetched 106 kB in 0s (1947 kB/s)         
apt-listchanges: Can't set locale; make sure $LC_* and $LANG are correct!
Selecting previously unselected package libindicator3-7:amd64.
(Reading database ... 262503 files and directories currently installed.)
Preparing to unpack .../libindicator3-7_0.5.0-4_amd64.deb ...
Unpacking libindicator3-7:amd64 (0.5.0-4) ...
Selecting previously unselected package libappindicator3-1:amd64.
Preparing to unpack .../libappindicator3-1_0.4.92-7_amd64.deb ...
Unpacking libappindicator3-1:amd64 (0.4.92-7) ...
Setting up libindicator3-7:amd64 (0.5.0-4) ...
Setting up libappindicator3-1:amd64 (0.4.92-7) ...
Setting up draw.io (14.5.1) ...
Processing triggers for libc-bin (2.28-10) ...
```

**Comment by AnwarKamel** [comment]
Try this: 
sudo apt-get update
sudo apt-get clean
sudo apt-get autoremove

**Comment by 532910** [comment]
libappindicator3-1 is not available on debian sid
https://tracker.debian.org/news/1257945/removed-0492-8-from-unstable/

libappindicator is deprecated:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037

**Comment by ngulden** [comment]
And it's the same with Debian 11. The latest version draw.io 15.4.0 cannot be installed.

```
sudo dpkg -i drawio-amd64-15.4.0.deb
Selecting previously unselected package draw.io.
(Reading database ... 305989 files and directories currently installed.)
Preparing to unpack drawio-amd64-15.4.0.deb ...
Unpacking draw.io (15.4.0) ...
dpkg: dependency problems prevent configuration of draw.io:
 draw.io depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.

dpkg: error processing package draw.io (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.69) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for shared-mime-info (2.0-1) ...
Errors were encountered while processing:
 draw.io

sudo apt-get install -f
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  draw.io
0 upgraded, 0 newly installed, 1 to remove and 67 not upgraded.
1 not fully installed or removed.
After this operation, 325 MB disk space will be freed.
Do you want to continue? [Y/n] y
```

**Comment by 320x200** [comment]
On Debian Sid. Same problem, obviously.

`dpkg -i --force-depends` helps indeed at first, but then next time you want to upgrade any other parts of the system, apt refuses to work unless you `apt --fix-broken` and this uninstalls `draw.io`.

**Comment by WaldemarLehner** [comment]
As a workaround, one can use 
```sh
wget http://ftp.us.debian.org/debian/pool/main/libi/libindicator/libindicator3-7_0.5.0-4_amd64.deb
wget http://ftp.us.debian.org/debian/pool/main/liba/libappindicator/libappindicator3-1_0.4.92-7_amd64.deb
sudo apt install ./libindicator3-7_0.5.0-4_amd64.deb
sudo apt install ./libappindicator3-1_0.4.92-7_amd64.deb
```
(source: https://github.com/RocketChat/Rocket.Chat.Electron/issues/1975#issuecomment-899256569)

Here's a CI-Job that installs drawio using this Approach:

[Job Definition](https://gitlab.com/WaldemarLehner/drawio-mkdocs-headless-test/-/blob/d631ab3a548b4c09d6af94f3657248d889d6b0d3/.gitlab-ci.yml)

[Job Log](https://gitlab.com/WaldemarLehner/drawio-mkdocs-headless-test/-/jobs/1697176170)

**Comment by ywpc** [comment]
@WaldemarLehner  Thanks for the solution. Debian officially dropped this package but unfortunately "legacy" software (like 3 years old) are still needed.

**Comment by codebyAbhishekBharti** [comment]
@WaldemarLehner thanks your solution also worked for me. having this problem while running droidcam in kali linux -5.10.0-kali9-amd64

**Comment by OliverSolomon** [comment]
> As a workaround, one can use
> 
> ```shell
> wget http://ftp.us.debian.org/debian/pool/main/libi/libindicator/libindicator3-7_0.5.0-4_amd64.deb
> wget http://ftp.us.debian.org/debian/pool/main/liba/libappindicator/libappindicator3-1_0.4.92-7_amd64.deb
> sudo apt install ./libindicator3-7_0.5.0-4_amd64.deb
> sudo apt install ./libappindicator3-1_0.4.92-7_amd64.deb
> ```
> 
> (source: [RocketChat/Rocket.Chat.Electron#1975 (comment)](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1975#issuecomment-899256569))
> 
> Here's a CI-Job that installs drawio using this Approach:
> 
> [Job Definition](https://gitlab.com/WaldemarLehner/drawio-mkdocs-headless-test/-/blob/d631ab3a548b4c09d6af94f3657248d889d6b0d3/.gitlab-ci.yml)
> 
> [Job Log](https://gitlab.com/WaldemarLehner/drawio-mkdocs-headless-test/-/jobs/1697176170)

This worked for me. I had the same error trying to install binance.

**Comment by davidjgraph** [comment]
This thread is just noisy, now. I'm going to unsubscribe and close it. If someone has a solution, please start a new issue.

**Comment by hifihedgehog** [comment]
> As a workaround, one can use
> 
> ```shell
> wget http://ftp.us.debian.org/debian/pool/main/libi/libindicator/libindicator3-7_0.5.0-4_amd64.deb
> wget http://ftp.us.debian.org/debian/pool/main/liba/libappindicator/libappindicator3-1_0.4.92-7_amd64.deb
> sudo apt install ./libindicator3-7_0.5.0-4_amd64.deb
> sudo apt install ./libappindicator3-1_0.4.92-7_amd64.deb
> ```

Can confirm this solution works as expected.

**Comment by markuspla** [comment]
Reason - unable to install StarUML, missing libappindicator3-1.
Im confirm that this solution works on:

PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.1"
VERSION_ID="2022.1"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
