### ISSUE TITLE
Feature Request: Support editing files from Microsoft Teams

### ISSUE THREAD

**Issue by Danielku15** [jgraph/drawio-desktop#506]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
We cannot use Draw.io Desktop efficiently within our company because it does not natively support opening files from SharePoint/Microsoft Teams. 

**Describe the solution you'd like**
The desktop version of draw.io should be able to open files from various non-local disk locations like SharePoint (Microsoft Teams). The Microsoft Teams SSO mechanism should be used to gain access to the storage provider. Opening from the Microsoft Teams file browser would be also nice to make the transition from one application to the other smooth. 

**Describe alternatives you've considered**
Using the web version is an alternative. But it does not always integrate so well in the local workflows. 
Also synchronizing the sharepoint to local disk is a potential alternative, but also not really a "proper" integration. 

**Additional context**
While this feature request is mainly for Teams (because that's our concrete need) I guess the other storage providers would also be great to support in the Desktop version. 

In an initial version I guess the file would be locked for update once it is opened by one person. But for the future concurrent editing with merging would make the usage of Draw.io really efficient together with other productivity tools widely used today.

**Comment by davidjgraph** [comment]
The scope of the desktop project is strictly local only.

**Comment by Danielku15** [comment]
It's really unfortunate to see that you do not seem to be open for discussions on this topic. 😞 Draw.io Desktop seems to be rather a "Draw.io Local" then. This project scope you are mentioning seems to be not very well communicated, you should probably consider documenting this more explicitly on the website and the project readme. 

I understand the point of having a local-only flavor for some special customers in secure environments. Tthe Security section of the readme tries to pick this requirement up. But I would say usually people making such diagrams, are not working alone but in a collaborative environment. Security is guaranteed within this corporate environments with SSO (e.g. Microsoft 365) etc. 

Draw.io as is a great software and I was using it a long time. But not being able to integrate it with all our other tools and documents unfortunatelly means that we will need abandon Draw.io fully and replace it with tools that allow this. Using the web version is not an option for us and not in our interest. Hosting an own Draw.io is not feasable from a operational costs perspective (somebody will need to maintain this). The desktop client is perfect for daily use, but only being able to save files to the local disk is quite a show stopper.

**Comment by davidjgraph** [comment]
That's fine, thank you for your extended discussion.
