### ISSUE TITLE
Windows release: auto update on x64 download and install the ia32 edition

### ISSUE THREAD

**Issue by ericbl** [jgraph/drawio-desktop#507]
On Windows 10 x64, I had the x64 edition (default installer) of draw.io 14.1.8 installed.
I got proposed to update to 14.4.2.
So did I.
The update however downloaded and installed the ia32 edition, so that I had both versions of different editions installed.

**Comment by davidjgraph** [comment]
Thanks for the report. Should be fixed with 14.4.3. I'm afraid you'll have to uninstall and re-install the correct version, though.
