### ISSUE TITLE
Global export PNG settings

### ISSUE THREAD

**Issue by flmn** [jgraph/drawio-desktop#508]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Not a problem, a feature.

**Describe the solution you'd like**
Have a settings dialog, user can set Zoom, Border Width, Transparent Background, etc. settings globally. Next when user open a file, can use global setting for export.

**Describe alternatives you've considered**
Save export settings in file.

**Additional context**
no.

**Comment by lvmm** [comment]
Merging in #771. Also settings for all export types should be saved, not just png.

Sometimes it is necessary to export multiple pages of a diagram as images e.g. for publication on a website. When export dialogue (file-export as-) is opened it always reverts do default configuration and one has to reconfigure it every time which is time-consuming, annoying and may lead to mistakes.
