### ISSUE TITLE
 Wrong autoupdate version in  M1

### ISSUE THREAD

**Issue by FLIER001** [jgraph/drawio-desktop#509]
**Describe the bug**
The version I am using is macOS-arm, but when I click "check for updates" to upgrade, it will incorrectly install the macOS-intel version.

**draw.io version (In the Help->About menu of the draw.io editor):**
- 14.1.8

**Desktop (please complete the following information):**
 - OS: macOS, m1 processor

**Comment by imrefazekas** [comment]
I can confirm. ARM version updates to Intel version requiring rosetta right away ...

**Comment by davidjgraph** [comment]
Thanks for the report. Should be fixed with 14.4.3. I'm afraid you'll have to uninstall and re-install the correct version, though.
