### ISSUE TITLE
RPM package does not install on openSUSE

### ISSUE THREAD

**Issue by rombert** [jgraph/drawio-desktop#51]
Hi,

I tried to install the RPM package on openSUSE Tumbleweed and I get the following error:

```
Problem: nothing provides libappindicator needed by draw.io-8.8.0-156.x86_64
 Solution 1: do not install draw.io-8.8.0-156.x86_64
 Solution 2: break draw.io-8.8.0-156.x86_64 by ignoring some of its dependencies
```

The appindicator package in openSUSE is versioned:

```
$ rpm -q libappindicator1 
libappindicator1-12.10.1+bzr20170215-3.2.x86_64

$ rpm -q --provides libappindicator1 
libappindicator.so.1()(64bit)
libappindicator1 = 12.10.1+bzr20170215-3.2
libappindicator1(x86-64) = 12.10.1+bzr20170215-3.2
```

If I force the installation, the program works just fine.

It would be great if you could support a way of installing the RPM on openSUSE as it's much more convenient than the AppImage.

**Comment by davidjgraph** [comment]
Does 9.3.1 behave any better?

**Comment by rombert** [comment]
@davidjgraph - no, still does not work for me

```
$ sudo rpm -Uvh draw.io-x86_64-9.3.1.rpm 
error: Failed dependencies:
	libappindicator is needed by draw.io-9.3.1-160.x86_64
```

**Comment by rombert** [comment]
Sorry, I don't have a good idea - I know a couple of things about RPM building, but not about electron packaging.

If draw.io does not use the dependency, maybe you can just remove it? Alternatively it could be set to a 'recommends' so that it will be installed when available but otherwise ignored.

Another option is to use the rich RPM dependency sytnax, see http://rpm.org/user_doc/boolean_dependencies.html , but that's only available for RPM 4.13 or newer, so probably does not work on older distros...

**Comment by Rainmaker52** [comment]
See https://github.com/electron-userland/electron-builder/issues/1082#issuecomment-272794622.

Appearantly, this can be controlled by setting includeRequiredLib to true. This will however bloat the package somewhat.

**Comment by davidjgraph** [comment]
I had this on ubuntu and just force installed the dependency. I think Linux users should be able to do this, the package bloating is excessive.
