### ISSUE TITLE
Issue with text spacing and alignment.

### ISSUE THREAD

**Issue by bt-tech-dd** [jgraph/drawio-desktop#510]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When aligning text to top, the spacing affects it differently than when aligning text to bottom.

**To Reproduce**
1. Create two text boxes
2. Select one text box and align to bottom
3. Select the other text box and align to top
4. Notice the difference in spacing

**Expected behavior**
The spacing between the top of the text and the top of the text box that was aligned to the top should be the same as the spacing between the bottom of the text and the bottom of the text box that was aligned to the bottom.

**Screenshots**
![Screenshot 2021-02-25 135924](https://user-images.githubusercontent.com/68382967/109203783-92ee4d00-7772-11eb-8901-06e53491fe7c.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 14.4.3

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Version 2004 (OS Build 19041.804)

**Additional context**

**Comment by mararad** [comment]
Hi,

so you experimented with Spacing in Text tab when text box is selected. Could you copy/paste code for both text boxes please? Select one and click Ctrl+e and do the same for the 2nd box. 

Thanks,

**Comment by bt-tech-dd** [comment]
This is the code for the 1st text box:
`text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;`

This is the code for the 2nd text box:
`text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;`

**Comment by bt-tech-dd** [comment]
This bug is still present in version 15.8.7.

**Comment by davidjgraph** [comment]
The label used to test with should include the highest ascending character in that font family.

**Comment by bt-tech-dd** [comment]
New test with all characters
![image](https://user-images.githubusercontent.com/68382967/144474029-ab915435-ee1e-43f7-87d2-f91704abf900.png)

This is the style window of the top aligned text box
![image](https://user-images.githubusercontent.com/68382967/144474177-a298da05-b498-4364-bf1b-34b5a479659f.png)

This is the style window of the bottom aligned text box
![image](https://user-images.githubusercontent.com/68382967/144474279-bc53ae56-b6b5-41e0-91f0-d6975d21998c.png)

**Comment by bt-tech-dd** [comment]
This bug is still present in 17.2.4.
