### ISSUE TITLE
[solved] Debian package configuration file in draw.io-amd64-14.4.3.deb

### ISSUE THREAD

**Issue by LucN31** [jgraph/drawio-desktop#512]
Hi,
Thanks for this new version.

Installation is done in **/opt/draw.io** and postinstall script **/var/lib/dpkg/info/draw.io.postinst** refers to **/opt/drawio** directory.
Installation fails. 

No problem after script correction.

[drawio.zip](https://github.com/jgraph/drawio-desktop/files/6051447/drawio.zip)

Luc.

**Comment by HMaker** [comment]
That path typo is in post-install
```sh
#!/bin/bash

# Link to the binary
ln -sf '/opt/drawio/drawio' '/usr/bin/drawio'

# SUID chrome-sandbox for Electron 5+
chmod 4755 '/opt/drawio/chrome-sandbox' || true

update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
```
and post-removal scripts
```sh
#!/bin/bash

# Delete the link to the binary
rm -f '/usr/bin/drawio'
```

**Comment by LucN31** [comment]
> ```shell
> # Link to the binary
> ln -sf '/opt/drawio/drawio' '/usr/bin/drawio'
> ```

Sure, but binary is installed in /opt/draw.io, that is the problem.

Luc.

**Comment by m-mohamedin** [comment]
Can you confirm the problem is solved in the last release? 
Note: we changed app name to drawio (without the dot)

**Comment by LucN31** [comment]
> Can you confirm the problem is solved in the last release?
> Note: we changed app name to drawio (without the dot)

Yes. Installation is OK with debian package version 14.5.1.
Thx,
Luc.
