### ISSUE TITLE
Text Font & Sizing Issues

### ISSUE THREAD

**Issue by Kevin-Townsend** [jgraph/drawio-desktop#513]
When I try to change the text font or size inside of an object I highlight the text to be modified. If I change the font it does make the changed but the program then un-highlights/deselects the text. I must go back and highlight the text. If I am then increasing the font size up two steps (12 pt to 14 pt) using the NumericUpDown controls, when I click to move from 12 pt to 13 pt the font size does change. However, the selected text is again deselected. I must again select the text for the third time. When I change the font from 13 pt to 14 pt it again deselects the text. I do not think this is the way the system was designed and I wanted you to be aware of this vexing situation. Thank you.

**Comment by mararad** [comment]
Hi, 

I tested this in draw.io desktop version 14.4.3 (Win10 Pro) and couldn't reproduce. I selected text and changed font and size. Also font and size can be changed if only shape is selected. Please take a look at the video I attached and check if we are performing the same steps.

Regards,

https://user-images.githubusercontent.com/44292306/109490651-d0abe800-7a88-11eb-86f3-b9dabe71e583.mp4

**Comment by raindropsfromsky** [comment]
Even I could not reproduce the issue in 14.5.1 Desktop version (I am using Win 10 Home, 64 bit version).

BTW the font can be changed by using the **Formatting Panel** (at the right) also.
Just select the text object (without selecting the actual text), and then open the **Text** tab in the **Formatting Panel**.
Adjust the font size.

The **Formatting Panel** also allows you to select multiple text objects and set their font size at once.
