### ISSUE TITLE
Application user interface does not follow OS font

### ISSUE THREAD

**Issue by jay-ramani** [jgraph/drawio-desktop#514]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The user interface of the app does not use the OS-wide font. Would be good to see Drawio be consistent. I had already raised [issue# 319](https://github.com/jgraph/drawio-desktop/issues/319), but was auto-closed without any response due to inactivity.

**To Reproduce**
1. Open application
2. Observe drawio's font in comparison to user set OS-wide font

**Expected behavior**
The application's font should adhere and be consistent with OS-wide font

**draw.io version (In the Help->About menu of the draw.io editor):**

- Version: 14.4.3

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by eduncan911** [comment]
I'll add in Pop_OS (Ubuntu) 20.10 as well, as not following the system fonts and sizing.

**Comment by DevDorrejo** [comment]
Hello, have the same issue.

OpenSUSe TW KDE 5.22, using appimage/rpm of drawio
![image](https://user-images.githubusercontent.com/7697566/122678410-c424da00-d1b4-11eb-8291-aa158c966a8d.png)

**Comment by jay-ramani** [comment]
Not assigned to anyone yet? Looks like the issue will get closed down on inactivity; happened the last time I raised the same [issue](https://github.com/jgraph/drawio-desktop/issues/319).

**Comment by eduncan911** [comment]
> Not assigned to anyone yet? Looks like the issue will get closed down on inactivity; happened the last time I raised the same [issue](https://github.com/jgraph/drawio-desktop/issues/319).

Make a calendar reminder to come back.  ;)

**Comment by jay-ramani** [comment]
> 
> 
> > Not assigned to anyone yet? Looks like the issue will get closed down on inactivity; happened the last time I raised the same [issue](https://github.com/jgraph/drawio-desktop/issues/319).
> 
> Make a calendar reminder to come back. ;)

LOL! Wouldn't help if they are not going to fix it. Been more than a year since I raised the issue the first time. I wonder how complicated fixing this bug is.

**Comment by MrFuNK1** [comment]
Not fully sure but I believe the issue lays with the font definition made in the grapheditor.css: Currently the code is
```
.geEditor {
	font-family:Helvetica,Arial,sans-serif;
[...]
}
```
which makes Helvetica font the standard but as it's not available on all systems. And even if it is, it does cause trouble in some situations. 

But there are much more robust definitions that should work cross-platform/cross-system, such as (taken from the github.com CSS):
```.geEditor {
	font-family: -apple-system, BlinkMacSystemFont, "Segoe UI Variable", "Segoe UI", system-ui, ui-sans-serif, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
[...]
}
```

Currently, I'm using the above code in my custom configuration of the desktop app as a workaround to the issue. In "Extras > Configuration" I've put the following code (note it does also changes some other settings, but nothing fancy):
```
{
  "css": ".geEditor { font-family: -apple-system , BlinkMacSystemFont , \"Segoe UI Variable\" , \"Segoe UI\" , system-ui,ui-sans-serif , Helvetica , Arial , sans-serif , \"Apple Color Emoji\" , \"Segoe UI Emoji\" !important; } td.mxPopupMenuItem { font-family: -apple-system , BlinkMacSystemFont , \"Segoe UI Variable\" , \"Segoe UI\" , system-ui,ui-sans-serif , Helvetica , Arial , sans-serif , \"Apple Color Emoji\" , \"Segoe UI Emoji\" !important; } .geFormatSection { font-weight: normal !important; } div.mxPopupMenu { border-radius: 0px !important; } .geTemplate { font-size: 12px !important }"
}```

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
