### ISSUE TITLE
Appear to be caught in an "update available" loop.

### ISSUE THREAD

**Issue by ThomasOwens** [jgraph/drawio-desktop#518]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The "confirm update" dialog appears every time the desktop app is opened, even after installing the update. If I decline the update, the application is behaving normally, but it appears to be a later version.

**To Reproduce**
1. Open the desktop app.
2. Observe the dialog prompting to download and install an update.
3. Click "Ok" to download the update.
4. Click "Install" to install the update. The Windows security dialog indicates that the 14.4.3 installer is going to be executed.
5. Confirm the execution of the installer.
6. When completing the installation of the update, select the option to launch the app.
7. The app loads, but there is a dialog prompting to download and install an update. Continue again.

**Expected behavior**
Downloading and installing an update should only happen if there's an update to install. The latest version should be installed so there should not be an immediate need to install the update again.

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 14.4.2

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by iqapps** [comment]
I see this as well. Exact same problem.

**Comment by davidjgraph** [comment]
There were issues with the update files in 14.4.2. Unfortunately, we can't update them without...updating them. So, you'd have to uninstall and re-install 14.4.3.
