### ISSUE TITLE
Bug in release package draw.io-amd64-14.4.3.deb

### ISSUE THREAD

**Issue by accetto** [jgraph/drawio-desktop#519]
Hello,

I maintain for quite a time a Docker image with **drawio-desktop** ([accetto/xubuntu-vnc-drawio](https://hub.docker.com/r/accetto/xubuntu-vnc-drawio)).

However, I've just found out by updating the image, that there is an incorrect link in the package `draw.io-amd64-14.4.3.deb.`

**How it is**

```shell
$ ls -l /usr/bin/drawio
lrwxrwxrwx 1 root root 18 Mar  1 15:18 /usr/bin/drawio -> /opt/drawio/drawio

### checking - 'which' returns no output
which drawio
```

**How it should be**

```shell
ls -l /usr/bin/drawio
lrwxrwxrwx 1 root root 19 Feb 19 20:41 /usr/bin/drawio -> /opt/draw.io/drawio

### checking - 'which' ouput is not empty
$ which drawio
/usr/bin/drawio
```

I'll correct the link in my Dockerfile this time, but could you fix it please? Thanks.

Regards,
accetto

**Comment by m-mohamedin** [comment]
Can you confirm the problem is solved in the last release? 
Note: we changed app name to drawio (without the dot)

**Comment by accetto** [comment]
I'm glad to confirm that the last release (14.5.1) is OK again.

FYI
Meanwhile I've retired the Docker image from above because I've release a newer one [accetto/ubuntu-vnc-xfce-drawio-g3](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-drawio-g3) (from the source GitHub repository [accetto/headless-drawing-g3](https://github.com/accetto/headless-drawing-g3)).
