### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by fabianschilling** [jgraph/drawio-desktop#52]
Is there a way to integrate pinch to zoom (à la macOS) functionality in the Electron app? Currently, pinch to zoom affects the *entire* application, not the zoom level within the main view.

I think a more "native" pinch to zoom would really enhance the usability of the app. I'd be happy to help with the implementation, maybe you could give me some pointers on where to start!

I really love draw.io otherwise!

**Comment by alderg** [comment]
Hold down the Cmd key while using the pinch gesture. As you can see, the problem is the sensitivity of the touchpad (event is handled [here](https://github.com/jgraph/mxgraph/blob/v3.9.8/javascript/examples/grapheditor/www/js/EditorUi.js#L2027)). We have the same problem in the webapp.

**Comment by fabianschilling** [comment]
> Hold down the Cmd key while using the pinch gesture. As you can see, the problem is the sensitivity of the touchpad (event is handled here).

Thanks, that works (modulo sensitivity, as you say).

> What might be a condition for touchpad vs. mousewheel zoom?

Can you elaborate on what you mean by "condition"?

**Comment by alderg** [comment]
Condition to check if it's a touchpad pinch gesture or a real mousewheel event (didn't have time to look at the event details, but I think last time I checked it was difficult to tell them apart).

**Comment by Jargonius** [comment]
I would like to see this implemented for Windows 10 machines with touchscreens.  It is a really intuitive gesture that, right now, just jumps the contents of the main panel back and forth in a jittery manner.

**Comment by SanjayVyas** [comment]
I tried CMD on Mac and I did not notice any difference in zoom speed with pinch gesture.
CTRL-NUMPAD + and - dont work on mac as there is no separate NUMPAD.
If there could be a keyboard shortcut implemented for Mac with slow zoom.. 1 pt at a time, it would be great.

**Comment by ashrafteleb** [comment]
Pinch to zoom on trackpad works now with acceptable sensitivity. 
If there is still an issue, let us know to re-open

**Comment by jdschwam** [comment]
Hey everyone, great program.

On a Mac the zoom is still too sensitive for my taste.  It just seems out of sync compared to normal movement speed. Can there be an option set to slow it down, or a faceted zoom with a slight delay?

Just my 2 cents.  Thx

**Comment by florian-obradovic** [comment]
Hey All,
can we re-open this? The issue still persists and zooming via pinch gesture or option+scroll on touchpads is way too sensitive and almost unusable.
Thank you very much.
Best regards, Flo.

**Comment by davidjgraph** [comment]
We're unable to adjust this further. As mentioned, we cannot detect the difference between mouse wheel and trackpad. We'll re-open if someone provides the means to do this in this thread.

**Comment by mrjovanov** [comment]
Could we simply add ability to tune sensitivity?
Hence you don't need to "detect" mouse wheel or trackpad, but user can simply adjust the sensitivity according to the needs?

Also, I think pinch zoom function should be non-linear or should include acceleration factor. I wanted to offer help, but then I realized I could simply clone the project and try out the suggestion myself ;)

**Comment by flotpg** [comment]
I just wanted to suggest the same.
Setting a sensitivity level would solve the issue or some techniques which smooth line based scrolling.
The issue is not only related to pinch gestures. It’s also almost unusable when scrolling with magic mouse, Logitech MX Mastere 3, etc.

it only works ok with cheap mice with legacy line based scrolling

**Comment by davidjgraph** [comment]
Yup, makes sense - https://github.com/jgraph/drawio/issues/2469

**Comment by davidjgraph** [comment]
There is a JSON config option, btw, in case that was missed:

```
{
  "zoomFactor": 1.05
}
```

**Comment by mihaiconstantin** [comment]
@davidjgraph Sorry for the dumb question, but where should this config be placed?

**Comment by GoodDonkey** [comment]
on App, Extras - Configuration, put that json config works. smooth like baby's ass

**Comment by ckjoris** [comment]
just tried it on linux (with gnome wayland).
Touchpad pinch to zoom works fine,
but with touchscreen - pinch is just doing rectangular selection.

**Comment by tanovich** [comment]
> just tried it on linux (with gnome wayland). Touchpad pinch to zoom works fine, but with touchscreen - pinch is just doing rectangular selection.

the problem mentioned still exist 28.0.6. Drawio in app.diagrams.net site on firefox works fine, so i can pinch to zoom either on touchscreen and touchpad, but on drawio-desktop none of above work.

**Comment by alderg** [comment]
If touchscreen pinch still starts a rubber band selection in the current version, please open a new issue with your distribution, desktop environment and whether the app runs under Wayland or X11 (also with `ELECTRON_OZONE_PLATFORM_HINT=auto`).
