### ISSUE TITLE
Import Not Working

### ISSUE THREAD

**Issue by mekaam** [jgraph/drawio-desktop#521]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
On the Desktop version 14.4.3
Open the app
click file > import > from device
then i choose .vss file
application show loading for a few seconds then the load disappear and nothing happen
the stencils are not loaded or anything appear

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
14.4.3
**Desktop (please complete the following information):**
Windows 10
**Additional context**

**Comment by davidjgraph** [comment]
Binary .vsd .vss etc formats aren't supported in the desktop build.
