### ISSUE TITLE
Adding of new shapes or connectors should not be allowed when a locked layer selected

### ISSUE THREAD

**Issue by ahmedbrave** [jgraph/drawio-desktop#522]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. Add at least two layer to a diagram
2. Add some shapes to both layers
3. Lock one of the layers
4. Select locked layer
5. Double-click on a free space of the diagram (a popup with shapes will appear)
6. Select a shape to add it to the diagram
7. Hover over a shape on a the not locked layer to see a arrows around the shape, click on an arrow (popup with shapes will appear) and click on a shape
8. Unlock the locked layer, check the added shapes (see what is the layer they belong to)

** Actual behavior **
for pt.5 Shape will be added to the locked layer you selected
for pt.7 Shape will be added to the locked layer you selected, and the arrow connector will be added to the layer the parent shape of the arrow belongs to

**Expected behavior**

for pt.5 popup with shapes should not appear at all
for pt.7 control points or arrows should not be displayed for the shape

So in general, if a locked layer is selected, all shapes and connectors on the diagram should behave as if all layers are locked (whether or not they are locked). It should only be possible to add or edit shapes if an unlocked layer is selected.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.4.3

**Desktop (please complete the following information):**
 - OS: Windows [Version 10.0.19041.804] 

**Additional context**
I add it as a bug just to have a somewhat structured description.

**Comment by mararad** [comment]
Reproduced in desktop 14.4.3, Win 10 Pro
