### ISSUE TITLE
ARM64 support for Windows 10x (appx build)

### ISSUE THREAD

**Issue by mieliespoor** [jgraph/drawio-desktop#524]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Support ARM64 builds for the Windows Store

**Describe the solution you'd like**
Windows 10x support x86 emulation but providing native ARM builds is a better solution. Providing ARM build option for this platform will increase app support.

**Describe alternatives you've considered**
Using the x86 emulation of Windows.

**Additional context**
N/A.

**Comment by ppczouz** [comment]
Where can I find an ARM64 Windows version? none of the assets seems to contain one.
