### ISSUE TITLE
Org Chart Layout Error - g.execute is not a function

### ISSUE THREAD

**Issue by gareth-watson** [jgraph/drawio-desktop#525]
When selecting the Org Chart layout from the menu I receive the error:

![image](https://user-images.githubusercontent.com/33933171/110315546-538cef80-8001-11eb-8414-70c58adaf7ee.png)

You can repro this by:

1. Create a new diagram
2. Choose Org Chart as the template
3. Click on Arrange -> Layout -> Org Chart
4. Click OK

You'll then get the above error message.

**Comment by mararad** [comment]
Reproduced in 14.4.3 and Win 10 Pro

**Comment by ashrafteleb** [comment]
Fixed, thanks for the report
