### ISSUE TITLE
Windows switching in desktop version (MacOS)

### ISSUE THREAD

**Issue by lojza3d** [jgraph/drawio-desktop#526]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
There's no windows management available in MacOS desktop version as it is common in almost any other app.

**Describe the solution you'd like**
1. Implement main menu item "Window" in order the user would be able to choose and switch between existing open windows (documents).
2. Implement common keyboard shortcut (Cmd+`) for cycling between open windows / documents.

**Describe alternatives you've considered**
There's just one workaround known to me on Mac: define a keyboard shortcut for displaying all app windows (System Preferences -> Keyboard -> Shortcuts -> Mission Control -> Application windows) and use it for choosing / switching between open windows.

**Additional context**
The Draw.io app is excellent in many ways, so keep up & thank you!

**Comment by psyrendust** [comment]
I can confirm that the keyboard shortcut (<kbd>Cmd</kbd>+<kbd>`</kbd>) for cycling between open windows / documents works on mac version <code>14.4.3</code>.

**Comment by lojza3d** [comment]
I can also confirm that version 14.4.3 correctly supports Cmd+` for cycling between open windows. This resolves the issue for me.
