### ISSUE TITLE
is the |-0-----0-| missing from the ERD symbols?

### ISSUE THREAD

**Issue by kswope** [jgraph/drawio-desktop#527]
* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Every relation with carnality-modality seems to be there except for zero or one to zero or one

This is easy to see since there are 4 endings and there are only 3 symmetrical relations

This is the one that I can't find in draw.io ( image from a website )

![image](https://user-images.githubusercontent.com/321586/110706102-533d5180-81c5-11eb-80ad-7328b789fd5a.png)

- draw.io version [e.g. 12.6.7]

diagrams.net 14.4.3

OSX

**Comment by mararad** [comment]
Hi,

it's possible to create it via "Line start" and "Line end" under Style tab when a connector is selected. Is this what you are looking for, please?

Thanks,
![erd](https://user-images.githubusercontent.com/44292306/111130902-04523c00-8578-11eb-9fe3-1b219ceeb837.JPG)

**Comment by kswope** [comment]
That looks like it.  Maybe it should probably be added to the Entity Relation section since its the only one missing.  Very low priority though.
