### ISSUE TITLE
To open diagram directly from command line in offline application

### ISSUE THREAD

**Issue by ratermir** [jgraph/drawio-desktop#528]
I wanted to integrate offline application into windows to be able to open files with "drawio" extensions directly from Windows explorer, but I didn't succeed. 

I tried the most obvious way - command something like this: 

"C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory=Default --app-id=pebppomjfocnoigkeepgbmcifnnlndla "d:\Projects\BP_Diagram.drawio"

The application opens, but with no diagram. It only offers menu "New diagram" and "Open diagram".

The desired behaviour would be to open diagram passed on command line.

**Comment by iturdikulov** [comment]
I have similar issue.
I open / create diagram through command line, using this:
`drawio "figures/filename 1"`

if here no instance of opened drawio it's opening correctly. But if here already some opened diagram, I see menu with "New diagram" and "Open diagram".

So I can't open 2 different diagrams through command line.
