### ISSUE TITLE
Move redundant system menu “draw.io”

### ISSUE THREAD

**Issue by Taswen** [jgraph/drawio-desktop#530]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Description
I haven't updated draw.io desktop for a long time, and when I updated to the latest version (14.4.3), I found a uncomfortable change, that is, a menu item `draw.io` occupies a whole row of space. I don't understand why this is necessary. For me, it just means a waste(especially for this kind of software that requires a larger working area). Maybe it's not obvious on the large screen equipment, but It seems redundant on my laptop.
P.S. I’m using the No Installer version

### Suggestion

Move it to menu `Help` or Remove it.
If you want to keep it in its original position, I recommend making it optional to display or not.

**Comment by mararad** [comment]
Unfortunately, this is not possible at the moment. 
Please follow this issue https://github.com/jgraph/drawio-desktop/issues/91

Regards,
