### ISSUE TITLE
Mac Intel draw.io desktop client: Copy as Image for selection copies entire diagram

### ISSUE THREAD

**Issue by dcwangmit01** [jgraph/drawio-desktop#535]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

On MacOS draw.io desktop client as of 14.5.1, "copy as image" no longer copies the *selection*, but instead copies the entire image from the worksheet.  Downgrading to 14.4.3 verifies that the feature works as expected in the older version.

**To Reproduce**
1. Install 14.5.1 on Mac Intel
2. Create a diagram
3. Drag and select part of the diagram
4. Click on "copy as image" from the menu.
5. Paste the image into another application.
6. See error, that the entire image in the worksheet is pasted as image, instead of the selection.

**Expected behavior**

Expected behavior is that only the selected elements of the diagram should have been pasted, instead of the entire diagram.

**Screenshots**

n/a

**draw.io version (In the Help->About menu of the draw.io editor):**

- Bug is present in 14.5.1
- But is not present in 14.4.3

**Desktop (please complete the following information):**
 - Mac Intel

**Additional context**

n/a

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by sergeyblagodarnyy** [comment]
Is the patch available now? I also have this issue.
