### ISSUE TITLE
Error: Cannot create BrowserWindow before app is ready

### ISSUE THREAD

**Issue by mccataldo** [jgraph/drawio-desktop#540]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. Download the Mac dmg file ([14.5.1](https://github.com/jgraph/drawio-desktop/releases/download/v14.5.1/draw.io-14.5.1.dmg)) from the releases page
2. Run the installer
3. Drag the app icon into Applications
4. Open the .app file in the Applications folder
5. Select the affirmative on the MacOS security prompt
6. Observe the error,
```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
at createWindow (/Applications/draw.io.app/Contents/Resources/app.asar/electron.js:85:19)
at App.<anonymous> (/Applications/draw.io.app/Contents/Resources/app.asar/electron.js:797:3)
at App.emit (events.js:315:20)
```

7. Click OK
8. Observe app opens and seems normal
Note: I have not tested to see if the application is working as it should. It's possible this error is benign but I still thought I should report it.

**Expected behavior**
app should have opened without error
**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
14.5.1

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.3

**Comment by davidjgraph** [comment]
Cannot repeat
