### ISSUE TITLE
Javascript Plugins not functioning in desktop version

### ISSUE THREAD

**Issue by tvanyo** [jgraph/drawio-desktop#541]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The builtin javascript plugins tooltips.js and flow.js are not working with the desktop version, even after app restart. 

In the case of tooltips, I do not see an icon on shapes or connectors with a tooltip properties.
In the case of flow, I do not get a context menu option to start the flow.

**To Reproduce**
1. Run desktop version
2. Click Extras ➙ Plugins… ➙ Add… ➙ Select Flow from drop down
3. You'll get a dialog saying it will take effect after restart, so restart
4. Create a connector
5. Right click to get context menu, notice no "Toggle Flow…" option

**Expected behavior**
In the case of the flow plugin, there should be an option for "Toggle Flow…" when a connector is selected.
In the case of the tooltip plugin, there should be an icon on any shape or connector with a tooltip property

**draw.io version (In the Help->About menu of the draw.io editor):**
draw.io version 14.5.1 (loaded from homebrew)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7

**Additional context**
Have confirmed that the plugins work as expected on browsers Edge, Firefox, and Safari on the same machine. I've seen the issue on two different machines running the same macOS and draw.io versions.

**Comment by tvanyo** [comment]
I thought the tags plugin was working but it is not either. I don't think any of the plugins are working on the desktop.

**Comment by mararad** [comment]
Reproduced with tags.js and flow.js in 14.5.1

![desktop plugins](https://user-images.githubusercontent.com/44292306/113413791-c0569800-93bb-11eb-8274-8daa07e98459.JPG) plugins added

![flow plugin](https://user-images.githubusercontent.com/44292306/113413799-c482b580-93bb-11eb-9190-6d74f46c8e32.JPG) There is no option Toggle flow 

![no tags plugin](https://user-images.githubusercontent.com/44292306/113413805-c64c7900-93bb-11eb-9cb5-7431a94106ea.JPG)
There is no Tags plugin under Extras

**Comment by m-mohamedin** [comment]
Fixed, will be available in the next release

**Comment by saf-dmitry** [comment]
The built-in JavaScript plugin flow.js stopped working again.

**draw.io version:**

draw.io version: 21.6.8

**Desktop:**

OS: macOS 10.15

**Comment by davidjgraph** [comment]
Please create a new issue, this issue relates to all plugins being blocked, not specific problems with one.

**Comment by saf-dmitry** [comment]
OK, done (#1446).
