### ISSUE TITLE
Advanced config json

### ISSUE THREAD

**Issue by PierreLev** [jgraph/drawio-desktop#542]
Hello, I work for governement organization that use your software. 
I write scripts to automatically deploy programs on users' computer.

Is there a way I could copy paste a JSON File to add some customFonts for the user by default? Like on this page, without passing by the program? https://desk.draw.io/support/solutions/articles/16000104033-use-custom-fonts-in-confluence-cloud 
ex : { "customFonts": ["Lato", "Charter"] }
I tried to change the Preferences file in AppData/Roaming/draw.io, no change.

If yes, where is it?

Thank you!

Pierre

**Comment by mararad** [comment]
Hi Pierre,

you could try to use Configuration under Extras in the editor. Does it help?

Regards,

**Comment by slavistan** [comment]
I have the same problem. A dedicated configuration file would be very useful to share configurations with other users of the desktop application.

My Linux installation already has a `~/.config/draw.io/config.json`, however, this files doesn't seem to work. My attempts to configure default fonts in this file get ignored completely.
```
{
  "defaultFonts": [ "Tahoma" ]
}
```
