### ISSUE TITLE
SVG Import Failing for em-dash.

### ISSUE THREAD

**Issue by tvanyo** [jgraph/drawio-desktop#545]
**Describe the bug**
SVG import limits strings to Latin1 encoding, meaning characters as simple as an en-dash or em-dash cause an import error. 

**To Reproduce**
1. Go to File
2. Click on Import
3. Select file TestFail.svg

**Expected behavior**
I would expect that UTF-8 characters would be acceptable, so em-dash and en-dash would not cause a problem. You can import the file Test.Pass.svg to see that everything is the same except for the em-dash character.

[SVGImportTest.zip](https://github.com/jgraph/drawio-desktop/files/6297318/SVGImportTest.zip)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 14.5.1 (desktop app)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.2

**Additional context**
I've attached the file [SVGImportTest.zip](https://github.com/jgraph/drawio-desktop/files/6297325/SVGImportTest.zip) with the TestFail.svg and TestPass.svg files, since GitHub doesn't like SVG files.

**Comment by mararad** [comment]
Hi,

there is no error shown if you drag&drop svg file directly onto the draw.io canvas. Could you try that and let us know the result, please?

P.S I tested on Win 10

Regards,

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
