### ISSUE TITLE
Can not import gliffy file on desktop app? import on webapp online is ok?

### ISSUE THREAD

**Issue by trievis** [jgraph/drawio-desktop#546]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Can not import gliffy file on desktop app? import on webapp online is ok? Desktop app version 14.5.1. Webapp version 14.6.0

**To Reproduce**
1. Go to File->Import
2. Select gliffy file from local computer 
3. See nothing

**Expected behavior**
expect diagram imported to the app

**Screenshots**
Screen shot of webapp import ok include 
[test.zip](https://github.com/jgraph/drawio-desktop/files/6311689/test.zip)

![image](https://user-images.githubusercontent.com/2893084/114731673-39ea7080-9d42-11eb-9e80-3088d55a441f.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
webapp 14.6.0
desktop app 14.5.1

**Desktop (please complete the following information):**
 - OS: Windows 7

**Additional context**

**Comment by davidjgraph** [comment]
Not supported on desktop.

**Comment by trievis** [comment]
Hi, gliffy file not supported on desktop version?

**Comment by davidjgraph** [comment]
No. You've asked the same question three times and got the same answer three times. Let's avoid a fourth :).

**Comment by trievis** [comment]
Well, than it would be nice to update the unsupported feature of desktop version. For example in https://www.diagrams.net/blog/diagrams-offline
