### ISSUE TITLE
Missing BPNM 2.0 shapes

### ISSUE THREAD

**Issue by ScribbleGhost** [jgraph/drawio-desktop#548]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Among the shapes available in the groups **_BPNM General_**, the shape for **_Send Task_** is not one of them. Or perhaps I am missing something? Is it possible to make this shape another way?

I see the Send Task e-mail-symbol, but this is not the correct symbol according to BPNM.

![2021-04-17T19-20-44](https://user-images.githubusercontent.com/49068170/115156883-cec4d500-a086-11eb-9e64-e68f97acf357.png)

According to the BPNM specification, the symbol should also have the process-rectangle:

![Business Process Model and Notation (BPNM) Spesification 2 0 - Send Task](https://user-images.githubusercontent.com/49068170/115121235-cd75a880-9fb1-11eb-940b-f000baabb0ba.png)

This is weird because the shape for _Receive Task_ is correct and available:

![image](https://user-images.githubusercontent.com/49068170/115121310-4ecd3b00-9fb2-11eb-9b87-ddd2a1c5114b.png)

So one should expect the symbol for Send Task to be similar.

**To Reproduce**
1. Open the draw.io app for Windows.
2. Expand the shapes category BPNM General
3. Look for the Send Task shape
4. Cannot find the correct Send Task shape

**Expected behavior**
I expect the Send Task shape to be similar to the Receive Task shape. However it is not.

**Screenshots**
Screenshots in the exmpanation.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
diagrams.net 14.1.8

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Not browser. Desktop version.
 - Version 14.1.8

**Comment by mararad** [comment]
Hi, 

Thanks for the report. BPMN 2.0 will be released soon.

Regards,

**Comment by ScribbleGhost** [comment]
Really? I can't wait 😆!

**Comment by davidjgraph** [comment]
They are out in 14.6.5

**Comment by ScribbleGhost** [comment]
The latest version I can see for Windows is 14.5.1. Where can I find 14.6.5?

**Comment by davidjgraph** [comment]
Ah, this is desktop, ok, yeah, next release :)
