### ISSUE TITLE
Let an object be part of multiple layers

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio-desktop#558]
* [Y] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [Y] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Sometimes a node is part of multiple groups.

For example, take an organization chart with 3 levels of hierarchy.
- The CEO tops the chart, followed by Heads of departments.
- Under each HOD, there are employees.

Now if we want to show senior management, the CEO (apex node) and HODs (middle level) are to be shown.
If we want to show the departments, the HOD and employees are to be shown.

Thus the nodes that show HODs have to be displayed in both groups.
Currently, Draw.io does not allow this.

Making a duplicate set of all HOD nodes is a clumsy workaround!

**Describe the solution you'd like**

Let each node be part of multiple layers.
Thus, the "senior management" layer consists of **CEO** and the **HOD-HR**, **HOD-Fin**, **HOD-Production** etc nodes.
Also, the "HR" layer consists of **HOD-HR** node and the nodes that represent all employees in the HR department.
 
**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ChronosMOT** [comment]
You could make 3 layers, one for each hierarchy level. Then you can show senior management and the departments by activating the appropriate levels, without the need for duplicates.

**Comment by raindropsfromsky** [comment]
Of course! Now why didn't I think of that? 🤦‍♂️

I leave the following notes for anyone who has this issue and not found the
answer:

Layer 1 contains only the "CEO" shape, and nothing else.
Layer 2 contains all "HOD" shapes and incoming connectors from the "CEO" shape.
Layer 3  contains all "staff" shapes and incoming connectors from the "HOD" shapes.

Thus-
To show the *senior management*, select Layer-1+layer 2
To show the *departments*, select layer-2 and Layer-3.
To show the entire structure, select all three Layers.
