### ISSUE TITLE
Draw.io cannot detect system fonts and provide to the user

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio-desktop#568]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The following image shows the font-selection dialog. It shows a few system fonts, but a vast number of fonts are not shown here.

If I press 

**To Reproduce**
1. Select any text field in the drawing.
2. In the **Properties** panel, click on the **Fonts** drop-down menu. <br>A list of some fonts drops down.
![image](https://user-images.githubusercontent.com/9047168/116820686-db235480-ab93-11eb-86f5-e710090bf1c4.png)
3. Note that this dialog lists only a few fonts available in the Windows 10 system,. <br> Most of the system fonts are not listed here. <br>Even commonly used fonts such as Arial are missing from the list. **[BUG#1]**
4. Click on the **Custom...** button at the bottom. <br> The following dialog pops up.<br> ![image](https://user-images.githubusercontent.com/9047168/116820806-75839800-ab94-11eb-8df0-2bf28f6837c3.png)
5. Note that the **System fonts** field does not have a drop-down list of all system fonts. (spot marked in red circle) **[BUG#2]**<br> The user has to type in the name of the font he wants. <br> This is OK if it is a well-known font such as "Arial" has to be typed here. <br>But if the font name is not easily recallable, the user has to switch to some other application, and check which fonts are available.. <br>He has to select a font that matches his need visually. <br>Then he has to memorize the exact spelling of the font's name, and switch back to Draw.io; and type that string. <br>This is extremely tedious.

**Expected behavior**
A drop-down menu should be provided that lists all system fonts.

**Screenshots**
As shown above.

**draw.io version (In the Help->About menu of the draw.io editor):**
14.5.1

**Desktop (please complete the following information):**
 - OS: Windows 10 Home, 64 bits

**Additional context**
NA

**Comment by llvs** [comment]
I fully support this. Please add a selection of the expected font names. 
Sometimes the bold and italic variants have a different font name, sometimes not. It is not clear, which character string is expected from the user. A pre-populated list of font names would dramatically simplify using the local system fonts!
It is still an issue in 14.6.13

**Comment by Jose-Verdu-Diaz** [comment]
Reopening as the system fonts are still not available on v22.1.21, Ubuntu 20.04
