### ISSUE TITLE
Let users change the font size using the standard keyboard shortcuts CTRL+[ and CTRL+]

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio-desktop#574]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
If we want to change the font size in text, we have two options:
1. Select one or more text objects and then use the **Formatting Panel** (at right) to change the font size
2. Select a text object. Double-click to enter edit mode. A toolbar appears at the top. Change font size.

Thus, both methods use a spinner control to change the font size.
This is fairly tedius, and requires too many clicks (or manual entry of font size).

Instead, using a keyboard shortcut is much simpler and faster: After selection, use CTRL+[ and CTRL+] to change fonts.
This is a standard shortcut in Windows software; so easy to remember!

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
NA

**Additional context**
-

**Comment by belonesox** [comment]
Sorry, the issue closed as «completed» but looks that request is not implemened… Even on diagrams.net.
Or may be the issue is implemented but with different hotkeys?

**Comment by davidjgraph** [comment]
Github always shows this message, we don't know of a way to change the status when closing.
