### ISSUE TITLE
The properties panel should identify the shape type and its collection

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio-desktop#575]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
After we add any shape to the canvas, it is not possible to identify the shape.
If we have used shapes from multiple categories, you cannot remember the shap's name and its category.

e.g. the following shapes look confusingly similar:
1. "Event" shape, from the "Archimate 3.0/Application" collection.
2. "Event" shape, from the "Archimate 3.0/Business" collection.
3. "Event" shape, from the "Archimate 3.0/Implementation" collection.
4. "Event" shape, from the "Archimate 3.0/Technology" collection

**Describe the solution you'd like**
The Properties panel should have two fields at the very top that identify the name of the shape and the name of the collection.

For example, 
Shape name= Event
Shape collection: "Archimate 3.0/Business"

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by tinkercnc** [comment]
I agree with @raindropsfromsky 's suggestion.
Without this "feature"  the App is quite unusable.
It's almost impossible to edit a existing drawing from a third person.
I tried it out with this example
https://viewer.diagrams.net/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=#Uhttps%3A%2F%2Fraw.githubusercontent.com%2Fjgraph%2Fdrawio-diagrams%2Fdev%2Fexamples%2Findustrial-iot-example.drawio#%7B%22pageId%22%3A%22SXgX17sldJI9QkPeDldp%22%7D

I have no clue how I can find out which shapes/objects are used in this drawing.

**Comment by tinkercnc** [comment]
OK, then I will cancel this app from my list.
Farewell!

**Comment by alderg** [comment]
To find the shape used in a cell: Click **Edit**, **Edit Style** or **Ctrl+E** (**Cmd+E** on macOS), and look for `shape=X` in the cell style:

<img width="384" alt="Image" src="https://github.com/user-attachments/assets/5b215f71-7176-4360-9911-d1e282bae44e" />

To find the library for that shape, enter the shape name in the search box, hit Enter, right click on the corresponding shape in the search results, and click **Open Library** (this will open all libraries that contain this specific entry):

<img width="222" alt="Image" src="https://github.com/user-attachments/assets/d00ee687-2d1b-40f9-9907-a354a0deb43b" />
