### ISSUE TITLE
No AWS Grafana and Prometheus shapes

### ISSUE THREAD

**Issue by eXist-FraGGer** [jgraph/drawio-desktop#579]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The desktop version does not have all icons from the web version.

**To Reproduce**
1. Go to Search Shapes
2. Type 'grafana'
3. No results found for 'grafana'

**Expected behavior**
'grafana' Shape should be provided
The same with 'Prometheus'

**Screenshots**
![image](https://user-images.githubusercontent.com/13423093/117561239-a5073880-b09d-11eb-94f4-be5d426af701.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
14.5.1

**Desktop (please complete the following information):**
macOS Big Sur 11.3.1 (20E241)

**Additional context**
It is fine in web version.
![image](https://user-images.githubusercontent.com/13423093/117561276-04654880-b09e-11eb-955a-9a8a9f99bebf.png)

**Comment by davidjgraph** [comment]
This is expected. The web version augments the search results with third-party search results. The desktop version is no comms, except for updates.

**Comment by flipch** [comment]
Is there a way one could import an AWS Shapes library?
