### ISSUE TITLE
Crash when clicking on a url link

### ISSUE THREAD

**Issue by internetscooter** [jgraph/drawio-desktop#58]
If I add a text link/url to a page and click on it, DrawIO desktop crashes with no error message. 

It works ok in the web online version so I suspect it is something related to Electron security settings(?).

To reproduce: Add text and Insert Link, Click on Link

Crashes on Windows 10, not sure about other OS's

**Comment by alderg** [comment]
This works for me. Can you attach a test case, please?

**Comment by internetscooter** [comment]
Sorry - it appears to be the Desktop App (v 9.3.0) that is crashing (and takes all Chrome windows with it) and the Desktop one is ok. 

Attached is the zip xml:
[url.zip](https://github.com/jgraph/drawio-desktop/files/2503353/url.zip)

I will do a bit more investigation and update the issue.

**Comment by internetscooter** [comment]
If I use "draw.io", the actual desktop install, it is all good. If I install the Chrome extension "draw.io Desktop" and run that from the start menu on Windows, it opens draw.io in it's own container. The "draw.io Desktop"  is the one that crashes. I can live with running "draw.io" but there looks to be a bug in the Chrome extension.

**Comment by alderg** [comment]
What Chrome extension? Can you please provide a link?

**Comment by internetscooter** [comment]
My environment was corrupt somehow - this is the official Draw.io link but I get no option to install it (my colleague does) [draw.io Diagrams](https://chrome.google.com/webstore/detail/drawio-diagrams/onlkggianjhjenigcpigpjehhpplldkc).

If I look on the Chrome Webstore there is no official Draw.io that I can see. Maybe I grabbed a dodgy one?

Reinstalling Chrome seems to work and I installed from the link and have the official version now.

You should put one up on the Chrome Webstore though?

**Comment by davidjgraph** [comment]
Yeah, the CWS is full of malware, we have never had a Chrome extension, there's no reason to. Best avoid the CWS unless you're absolutely sure about what you're installing.
