### ISSUE TITLE
 Share

### ISSUE THREAD

**Issue by gahuva** [jgraph/drawio-desktop#581]
Hi,

I love working with diagrams.net, easy to use (intuitive interface). However, I had some issue with sharing my work board and would like to ask if you could please add the option to share my work?

At the moment, when pressing the share button, I get the message "Sharing available for Google Drive and OneDrive files"(not sure how this info will allow me to share my work).
<img width="528" alt="Screen Shot 2021-05-11 at 11 15 36 pm" src="https://user-images.githubusercontent.com/29497407/117821396-e15db300-b2ae-11eb-9ab9-24b06cec3afa.png">

Thank you
Ahuva Gigi

**Comment by davidjgraph** [comment]
It's saying sharing is only possible when the file is stored somewhere that everyone can access it. Where are you saving the diagram?

**Comment by gahuva** [comment]
Hi
Many thanks for the prompt reply:)
Ok, So when I saved the files in google drive I still got the message "Sharing available for Google Drive and OneDrive files". However, when I open the file from google drive and then try to share my work board it worked, Success!
Thank you for the help:).
