### ISSUE TITLE
Mirror function and forcing straight lines

### ISSUE THREAD

**Issue by ThibautThai** [jgraph/drawio-desktop#583]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
1. When I design complex systems with subsystems, I would like to copy paste the subsystems and mirror them entirely. 
2. Second problem is to get lines that are constantly straight

**Describe the solution you'd like**
1. Another button to mirror an entire selection of objects and connecting lines
2. Hold control or shift button and draw a line forcing it to be straight

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
Must be one issue per issue
