### ISSUE TITLE
When we edit multiple shapes with CTRL+SHFT+M, let the dialog show all properties that have common values

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio-desktop#584]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Suppose we have selected multiple shapes and we want to set their properties by using the CTRL+SHT+M.
The problem is that this dialog box is completely empty, even when the shapes have some common values (height/width).
![image](https://user-images.githubusercontent.com/9047168/118304798-c1bfc800-b504-11eb-8891-27c0e732c671.png)

**Describe the solution you'd like**
The dialog box should find which parameters have common values and display them.
For example, the height of all selected boxes could be the same (say, 10).
Similarly, all shapes may have a rotation value of 0 by default. 

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
Declined
