### ISSUE TITLE
How do I set a default font size

### ISSUE THREAD

**Issue by 2870743367** [jgraph/drawio-desktop#586]
This **default font** is a little small for me, and it is troublesome to set the font size one by one every time. How can I set a unified **default font size**

**Comment by mararad** [comment]
Hi,

font defaults to whatever the last font set on a cell is. You can change font size on a cell and that will become the default.
​To clear default styling, ensure nothing is and click "clear default styling" in the right-hand format panel.
Please, take a look at the video below.

https://user-images.githubusercontent.com/44292306/118780482-6129e580-b88c-11eb-8b63-fed03801eec8.mp4

Regards,

**Comment by 2870743367** [comment]
Thank you very much! I used to double click the text in the box, but this format will not be saved by default, only the box on stand-alone, and then select the text button in the option on the right, in which changes will be saved, I do not know the feature is also a bug
Here's my usual usage

https://user-images.githubusercontent.com/48408747/119258362-da626900-bbfb-11eb-9247-1e610f61d6af.mp4

**Comment by 2870743367** [comment]
https://user-images.githubusercontent.com/48408747/119258080-c66a3780-bbfa-11eb-9f76-bf91d22e2939.mp4

**Comment by fuyun1107** [comment]
> Thank you very much! I used to double click the text in the box, but this format will not be saved by default, only the box on stand-alone, and then select the text button in the option on the right, in which changes will be saved, I do not know the feature is also a bug
> Here's my usual usage
> 
>  Video_2021-05-23_190910.mp4

可以试试不选中文字，只选中框更改文字大小，应该可以成为默认字体

**Comment by mbolzan** [comment]
Right click on a shape with text formatted as you need, select "Set as Default Style".
Next element will have that style.

**Comment by StLeoX** [comment]
pefermance how to write?

**Comment by Krojack** [comment]
> Right click on a shape with text formatted as you need, select "Set as Default Style". Next element will have that style.

Isn't working for me. I set the font size to 18, right click and set as default style, add a new box and font is still 12. Even the further up video clip doesn't work.

I'm using the self hosted docker install if that matters.

**Comment by GSTbyMM** [comment]
How to set the font size to default so that it remains the same on every run?

**Comment by alderg** [comment]
Try [this](https://app.diagrams.net/#_CONFIG_UzV3UjUySklNSyzNKQlLLSpJrQguqcxJBQqqGjuqgmXT8vNKgjOroGJGJqrmLqpGzghtrinpqURpMncBAA==) configuration via **Extras**, **Configuration**:

```
{
  "defaultVertexStyle": {
    "fontSize": 24
  },
  "defaultEdgeStyle": {
    "fontSize": 24
  }
}
```

<img width="483" height="275" alt="Image" src="https://github.com/user-attachments/assets/fcb68b1d-1e00-4c8e-8298-1dcd12b76d7e" />

**Comment by GSTbyMM** [comment]
Thank you so much.
