### ISSUE TITLE
Transaction test error while installing release 14.6.13 RPM

### ISSUE THREAD

**Issue by ahmedmsvb** [jgraph/drawio-desktop#587]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
While installing release 14.6.13 (the RPM version) from bash, I receive the following error:
```
Error: Transaction test error:
  file /usr/lib/.build-id/13/070cd6d4401903dee7a42e402d150de4362b18 from install of draw.io-14.6.13-1.x86_64 conflicts with file from package 1password-8.0.33_92.BETA-1.x86_64
  file /usr/lib/.build-id/3e/d503d7be965ab698b328fe3a69162a4efb5351 from install of draw.io-14.6.13-1.x86_64 conflicts with file from package 1password-8.0.33_92.BETA-1.x86_64
  file /usr/lib/.build-id/5b/8864b69ddfe3bd034d5dbef9b814a8f9b59cbd from install of draw.io-14.6.13-1.x86_64 conflicts with file from package 1password-8.0.33_92.BETA-1.x86_64
  file /usr/lib/.build-id/af/4374e54497edac9a84703037832fafb0d99308 from install of draw.io-14.6.13-1.x86_64 conflicts with file from package 1password-8.0.33_92.BETA-1.x86_64
  file /usr/lib/.build-id/b4/fe1769dc0dbcd634d93f5ffd826d0354016f9e from install of draw.io-14.6.13-1.x86_64 conflicts with file from package 1password-8.0.33_92.BETA-1.x86_64
  file /usr/lib/.build-id/f0/d8c634c19103e2e50b980cc1fb5cbacdc8d07c from install of draw.io-14.6.13-1.x86_64 conflicts with file from package 1password-8.0.33_92.BETA-1.x86_64
  file /usr/lib/.build-id/f3/13677b4c4d959f49800be71689dc788f06ae94 from install of draw.io-14.6.13-1.x86_64 conflicts with file from package 1password-8.0.33_92.BETA-1.x86_64
```

Googling for the above filenames (e.g. 070cd6d4401903dee7a42e402d150de4362b18) showed that they are part of electron-12.0.2-1.fc34

**To Reproduce**
1. Download Linux rpm installer from https://github.com/jgraph/drawio-desktop/releases/tag/v14.6.13
2. From the terminal, cd to the directory where you downloaded the file
3. Type `sudo dnf in ./drawio-x86_64-14.6.13.rpm` then hit Enter

**Expected behavior**
Release 14.6.13 rpm file to be installed successfully from teminal (to update my 14.5.1 version).

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 14.5.1

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux 8.3 (Ootpa)

**Additional context**
The reason for having me do a manual update (download RPM and install) is because drawio-desktop update process doesn't work. 
When I click update inside the application, the update progress dialog box pops up with blank content (just while background).

**Comment by lasleyaj** [comment]
I have a similar issue. In my case I have a conflict between [draw.io desktop 15.4.0](https://github.com/jgraph/drawio-desktop/releases/tag/v15.4.0) and [Rocket.Chat Electron 3.5.7](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.5.7).

```
Error: Transaction test error:
  file /usr/lib/.build-id/3c/f3dce1c9e94bdf4e5ae52a57a14e8b02f3e2cf from install of draw.io-15.4.0-1.x86_64 conflicts with file from package rocketchat-3.5.7-1.x86_64
  file /usr/lib/.build-id/4b/d1434c7f9139c9e65deb95dad4693bf522e713 from install of draw.io-15.4.0-1.x86_64 conflicts with file from package rocketchat-3.5.7-1.x86_64
  file /usr/lib/.build-id/e8/75bf159c6409cfeb2471b9e8f4bb917b67a4e0 from install of draw.io-15.4.0-1.x86_64 conflicts with file from package rocketchat-3.5.7-1.x86_64
  file /usr/lib/.build-id/f9/5ad887e13e9f4ceb539f8b9375c198875cf2e0 from install of draw.io-15.4.0-1.x86_64 conflicts with file from package rocketchat-3.5.7-1.x86_64
  file /usr/lib/.build-id/fc/45cc0e8eeb65dbed3d516283e3b7903f59fc1f from install of draw.io-15.4.0-1.x86_64 conflicts with file from package rocketchat-3.5.7-1.x86_64
```

I am on Oracle Linux 8.4.
