### ISSUE TITLE
Save does not work on windows 8.1 with 14.6.13

### ISSUE THREAD

**Issue by matt-cave** [jgraph/drawio-desktop#589]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Save does not work on windows 8.1 with 14.6.13

**To Reproduce**
1. Open program'
2. Click save

**Expected behavior**
I would have expected it to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/74371909/118830268-cf6ea800-b88c-11eb-8382-ddf512ab53f4.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
We don't support Windows 8.1.

**Comment by matt-cave** [comment]
On my old windows 8.1 box, something must have happened, uninstalled and reinstalled desktop version works fine now. Web version also works fine.
