### ISSUE TITLE
The arrow keys are very sluggish when moving graphics

### ISSUE THREAD

**Issue by MoqiYNU** [jgraph/drawio-desktop#590]
### Preflight Checklist

When I use draw.io to draw graphs on a Mac, **it is very slow to move the image through the arrow keys**. In addition, I **strongly hope** that the new version needs to add the function of exporting the graphs in draw.io to tiff format, because this is very important for the wide application of draw.io to academic activities.
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Additional context**

**Comment by mararad** [comment]
Hi,

You could try pressing and holding a shape (it'll "jump") or Shift+cursor (it'll "follow" the grid)

Regards,
