### ISSUE TITLE
Adding new page results in software freeze on MacOS

### ISSUE THREAD

**Issue by bikeridercz** [jgraph/drawio-desktop#592]
### Preflight Checklist

* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Clicking to (+) should add a new page results in whole software freeze onn MacOS. It works fine on web version.

**To Reproduce**

**Expected behavior**
New empty page was opened

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 14.6.13 and previous versions]

**Desktop (please complete the following information):**
 - OS: MacOS Catalina

**Additional context**

**Comment by davidjgraph** [comment]
Anyone got Catalina to double check? I only have 11.2.3.

**Comment by pankostka** [comment]
I have same problem on windows desktop. Add new page freezes draw.io. 
I can duplicate page but only created in older version.
Reinstaled last version downloaded today no help.

**Comment by davidjgraph** [comment]
Version anyone?

**Comment by bikeridercz** [comment]
I checked a really old version 13.03 and even on that version it does not work - drow.io frees. Did it ever work on mac ? how it can work on big sur and not on catalina thats strange ... is it developed natively for m1 or it is running via rosetta ?

**Comment by pankostka** [comment]
i have tried another notebook, fresh download (diagrams.net 14.6.13) and click on new page freezes drawio desktop completely. 
A have to kill it from task manager.

**Comment by davidjgraph** [comment]
@pankostka Which binary did you download and run from the downloads page?

**Comment by pankostka** [comment]
This link https://github.com/jgraph/drawio-desktop/releases/download/v14.6.13/draw.io-14.6.13-windows-installer.exe

**Comment by pankostka** [comment]
Now its OK. I didnt change anythink, maybe windows update?
On windows looks ok.

**Comment by davidjgraph** [comment]
Not sure, we never could recreate the problem. Could be a video driver on windows.

**Comment by bikeridercz** [comment]
Resolved in 14.9.6. Thanks.
