### ISSUE TITLE
Incorrect foreground color selection on Windows when non-Dark theme selected

### ISSUE THREAD

**Issue by jimpaton-ufx** [jgraph/drawio-desktop#593]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Light foreground colors are selected for certain UI elements regardless of theme selected, resulting in menu items, ruler, *etc.* being not visible with any theme other than **Dark**.

**To Reproduce**
1. Fresh install & launch on Windows
2. Click **Create New Diagram**
3. Select *Empty Diagram*
4. Click **Create**
5. Open **Edit** menu
6. Open **View** menu
7. Enable Ruler
8. Open **Extra -> Themes** menu
9. Click **Dark**
10. Close & restart application

**Expected behavior**
- After **Step 2**: sample/preview of diagram types should be visible behind diagram type names; they are not;
- After **Step 4**: grid should be visible; default color selected for grid is `#D0D0D0`, so not visible on white background;
- After **Step 5**: unavailable menu items should be visible; they are rendered in a color not visible on white background;
- After **Step 7**: ruler should be visible; it is rendered in a color not visible on white background;

The affected items are only visible when **Dark** theme is selected.

**draw.io version (In the Help->About menu of the draw.io editor):**
- 14.6.13

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional, 20H2, Build 19042.985

**Additional context**
Dark mode selected in Windows, although I checked with both Dark and Light mode selected, behavior is the same regardless.

**Comment by mararad** [comment]
Hi,

Could you attach print screens or video showing all 4 issues you reported, please? I am not able to reproduce this behaviour at the moment. 
I am using Win 10 Pro, draw.io 14.3.16 and Automatic theme.

Regards,
