### ISSUE TITLE
Cmd-Q has to be pressed twice

### ISSUE THREAD

**Issue by StevenMagdy** [jgraph/drawio-desktop#6]
Cmd-Q has to be pressed twice. First press behaves as a Cmd-W, second press quit the application.

**Comment by nvllsvm** [comment]
Replicated on:

**Version**: 7.8.4
**OS**: macOS 10.12.6

**Comment by Techcadia** [comment]
If launched from Shell you also get the same results. the session is not closed until you close twice.

**Comment by Techcadia** [comment]
The reason for this is explained here.
https://github.com/jgraph/drawio/blob/master/src/main/webapp/electron.js#L253

**Comment by davidjgraph** [comment]
https://apple.stackexchange.com/questions/234495/os-x-should-i-quit-apps-or-close-windows-red-cross-button-behavior

**Comment by introom** [comment]
yes.  i have the same issue.

**Comment by davidjgraph** [comment]
Is this still the case?

**Comment by ashrafteleb** [comment]
Fixed in v10.8.0
