### ISSUE TITLE
Error in HTML for Ascii-Math help on https://www.diagrams.net/doc/faq/math-typesetting

### ISSUE THREAD

**Issue by hugotoledo** [jgraph/drawio-desktop#602]
### Preflight Checklist

* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When you click on **Extras** in the menu bar and click on the help icon, a question mark in a circle, at the end of the Mathematical Typesetting menu item, the web page https://www.diagrams.net/doc/faq/math-typesetting opens in your default browser.
The first bullet point has bad HTML. It correctly shows you must enclose Ascii-Math equations with the ` character (i.e., the angled single quote typically found with the tilde character ~ on the top-left-most key on contemporary American computer keyboards. However, the code example is missing the delimiters.

**To Reproduce**
1. Go to https://www.diagrams.net/doc/faq/math-typesetting
2. View the first bullet point
3. The equation is NOT shown enclosed by the delimiter as it is in subsequent examples

**Expected behavior**
You are shown this:
AsciiMath between **`**, for example: a^2+b^2 = c^2

You should be shown this:
AsciiMath between **`**, for example: **`**a^2+b^2 = c^2**`**

**Screenshots**

1) How I originally found the webpage. I clicked on the question mark in the circle:
<img width="361" alt="diagram io Screenshot 2 of 4 - 2021-05-25 224123" src="https://user-images.githubusercontent.com/4201898/119596526-594ad380-bdad-11eb-8ac7-258bea8e5263.png">

2) I saw the first bullet point is incorrect, it doesn't show the example formula within the delimiters specified:
<img width="361" alt="diagram io Screenshot 3 of 4 - 2021-05-25 224123" src="https://user-images.githubusercontent.com/4201898/119596543-6071e180-bdad-11eb-911e-9938ec8b2916.png">

3) The HTML is missing the delimiters in the formula on the right. It is properly included in the first circled example on the left:
![diagram io Screenshot 4 of 4 - 2021-05-25 224123](https://user-images.githubusercontent.com/4201898/119596559-68ca1c80-bdad-11eb-8c4a-5d7193c162bf.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 14.6.13

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise, Version	10.0.18363 Build 18363

**Additional context**
none

**Comment by davidjgraph** [comment]
Fixed, thanks for report.
