### ISSUE TITLE
Basic request: Simple option to save the file when quitting it.

### ISSUE THREAD

**Issue by oMrSmith** [jgraph/drawio-desktop#603]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by oMrSmith** [comment]
Save changes?

YES // NO // CANCEL

**Comment by davidjgraph** [comment]
Declined

**Comment by oMrSmith** [comment]
Every other software is working this way for good reasons. I think your descision is bad.

**Comment by oMrSmith** [comment]
![image](https://user-images.githubusercontent.com/78870770/146214823-1ad2fc13-af20-48df-a6b6-5621e1a0fa1c.png)
