### ISSUE TITLE
After the drawio software is opened, the drawio icon is not displayed in the taskbar (ubuntu20.04 lts, gnome)

### ISSUE THREAD

**Issue by missuor** [jgraph/drawio-desktop#605]
After the drawio software is opened, the corresponding software icon is not displayed in the taskbar. And the opened program is separated from the program in the favorites (not the same as other software like google chrome or code)

I don't know if this is a problem with gnome or ubuntu or a software problem

The problem recurrence process is as follows

![drawio](https://user-images.githubusercontent.com/4561294/119757306-58ae5c00-bed7-11eb-8407-20983e8c9000.gif)

Installing the snap version of the soft (10.x) through apt-get does not appear the above problem

**Comment by missuor** [comment]
![drawio2](https://user-images.githubusercontent.com/4561294/119757837-22bda780-bed8-11eb-9023-d3c68d354bfb.gif)

**Comment by missuor** [comment]
I found that I have already mentioned this bug. Does anyone know this problem? thx :）

**Comment by missuor** [comment]
It is OK to use the snap version of the software installed in the ubuntu software center

**Comment by ashed** [comment]
Missing icon in snap version of drawio.desktop - this is bug when snap build
