### ISSUE TITLE
Trying to open non-existent files may lead the user to nuking another file

### ISSUE THREAD

**Issue by MazeChaZer** [jgraph/drawio-desktop#607]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When the user tries to open a file from the “Open Recent” menu that does no longer exist, a file dialog pops up that looks like a “Open File” dialog to select which file to open instead. In reality, it's a “Save File” dialog and if the user selects a file, it is overwritten with an empty diagram. Fortunately, I had all of my diagrams versioned in Git, but otherwise I would have lost a lot of work due to this bug :(

**To Reproduce**
1. Create the obsolete entry in the “Open Recent” menu
    1.1. Save a non-empty file somewhere
    1.2. Close draw.io
    1.3. Rename the file
    1.4. Open draw.io again
2. Run the actual problematic sequence
    2.1. When draw.io opens, close the new file/open dialog with the X button in the upper right corner
    2.2. Go into the menu, choose File -> Open Recent -> Select the file that no longer exists under that path
    2.3. The file dialog will pop up
    2.4. Select the file under their new name
    2.5. The file will have been overwritten with an empty diagram

**Expected behavior**
I expect a meaningful error message if I try to open non-existent paths, not some strange and misleading „default behavior“.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.6.13

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by argenos** [comment]
I unfortunately just ran into this. I couldn't understand why my file is now showing up empty, and sadly my backup is quite old, so I lost quite a bit of work due to this. I'm assuming there is no way to recover them?

**Comment by MazeChaZer** [comment]
Today I hit this bug again and nuked another important file. Fortunately, it was again versioned in Git, but I would be very screwed if it would not have been. Why doesn't get this issue any attention?

**Comment by davidjgraph** [comment]
Attempt to address this in 16.0.0. Feeback welcome.
