### ISSUE TITLE
Add .png file type to CFBundleTypeExtensions on Mac OS

### ISSUE THREAD

**Issue by andreykeks** [jgraph/drawio-desktop#609]
Add png format to the list of file types supported by the application. This will open editable pngs using the OS "Open with..." function.
To do this, add an element in the Info.plist file under the <key>CFBundleDocumentTypes</key> section.
An example of an added element:
` <dict>
                <key>CFBundleTypeExtensions</key>
                <array>
                    <string>png</string>
                    <string>PNG</string>
                </array>
                <key>CFBundleTypeMIMETypes</key>
                <array>
                    <string>image/png</string>
                </array>
                <key>CFBundleTypeName</key>
                <string>Portable Network Graphics Image</string>
                <key>CFBundleTypeOSTypes</key>
                <array>
                    <string>PNGf</string>
                </array>
                <key>CFBundleTypeRole</key>
                <string>Editor</string>
                <key>LSIsAppleDefaultForType</key>
                <true/>
                <key>LSItemContentTypes</key>
                <array>
                    <string>public.png</string>
                </array>
                <key>NSDocumentClass</key>
                <string>PVDocument</string>
            </dict>`

**Comment by sbliven** [comment]
Can this be reopened? This is a very simple fix with a big impact.

**Comment by davidjgraph** [comment]
@sbliven Please submit a PR for the change.

**Comment by sbliven** [comment]
I just added  PNG, but I guess SVG would make sense as well.

**Comment by sbliven** [comment]
@davidjgraph I'm not sure if you saw my comments on the PR after you closed it.

I see your point about most PNG (as well as SVG and HTML) not being openable with drawio because they lack the correct internal structure. However, I think drawio should still be associated with these extensions and mime types because otherwise basic OS functionality like drag-and-drop and 'open with' are disabled. Drawio shouldn't be the default for these, but it should be on the list.

Dragging a non-drawio PNG onto the app should be handled in the same way that selecting a non-drawio PNG in the 'Open' dialog is handled: by displaying the error 'Not a diagram file'.

**Comment by davidjgraph** [comment]
I did see it, yes, but I'm not convinced by the change. I'm thinking we'll receive support for people opening PNGs then asking why they can't edit them.

On a Mac it's possible to "open with", then pick pretty much any app.

Dragging a non-model PNG into the app shouldn't be rejected, that would change the default behaviour that's exists for many years.

**Comment by sbliven** [comment]
> On a Mac it's possible to "open with", then pick pretty much any app.

For unregistered extensions ones needs to right click » Open with... » Other... » Enable All Applications » Select draw.io.app. One can also do this from the 'Get Info' window to set it permanently for that specific file. Both of these are convoluted enough I would expect them to be overlooked by most users.

> Dragging a non-model PNG into the app shouldn't be rejected, that would change the default behaviour that's exists for many years.

On Mac it's not possible to drag a non-model PNG (drag and drop is only supported for registered extensions). Is this the linux behavior? Maybe part of the confusion is that mac and linux share an electron build file, but the behavior of apps with and without `fileAssociations` set is different. Maybe this setting needs to be OS-specific, with PNG and SVG only on Mac.

**Comment by sbliven** [comment]
Maybe I should also clarify that I'm only discussing dragging files onto the app icon. Dragging them into existing diagrams is a separate action and works fine.
