### ISSUE TITLE
`pt` different from conventional point size

### ISSUE THREAD

**Issue by christianbrodbeck** [jgraph/drawio-desktop#610]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

After exporting a diagram I noticed that draw.io font sizes are inconsistent with other applications. I found [this post](https://groups.google.com/g/drawio/c/xqtqTC18Y1c/m/90WVy4e2FgAJ) suggesting that a draw.io point seems to equal a CSS q point (0.25 mm), not a standard [DTP point](https://en.wikipedia.org/wiki/Point_(typography)) (0.3528 mm). Is this intended behavior? It took me a while to figure out why my exported diagrams had different font sizes than intended, and would be nice to have a setting for using DTP pt sizes.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 14.6.13]

**Desktop (please complete the following information):**
 - OS: macOS 11.4

**Comment by anthonyesau** [comment]
I just started trying out drawio and the nonconventional size of pt units was an immediate issue. In the app it appears that 100 pts = 1 inch. The standard is 72 pts = 1 inch. I come from a graphic design background where pts are commonly used and 72 pts always equal 1 inch in my experience. Drawio is the only exception I have come across and it would be much easier to use if it followed the standard.
