### ISSUE TITLE
Error Occurs When Opened At The First Time

### ISSUE THREAD

**Issue by anderlaw** [jgraph/drawio-desktop#613]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
As the message says, the App was not ready when the software had been clicked and opened!
**To Reproduce**
when I close the dialog, ignore and continue, everything will be fine.
But someday this bug will definitely show again

**Expected behavior**
No error message shows
**Screenshots**
![image](https://user-images.githubusercontent.com/21139011/120758219-22f71c00-c544-11eb-8568-dd74cb62f1cc.png)
**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [14.6.13]

**Desktop (please complete the following information):**
 - MacBook Pro, macOS: 11.2.3

**Additional context**
No

**Comment by davidjgraph** [comment]
Never been able to recreate. If anyone sees this on latest, please open a new issue.
