### ISSUE TITLE
Autoexport file on save

### ISSUE THREAD

**Issue by albinsunnanbo** [jgraph/drawio-desktop#616]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I have a workflow in the desktop application where I export my diagrams to SVG.
Every time I save I want to export my drawing to SVG.

**Describe the solution you'd like**
Option to autoexport file on each save
For my purpose saving the setting in each file is preferable, but a global setting would be good enough.

Requires #615 to make sure the exported file is exported with my preferred options.

**Comment by davidjgraph** [comment]
Doesn't giving the file a .svg suffix do this?

**Comment by albinsunnanbo** [comment]
Oh, I didn't know about that feature.
It almost works, however images are not embedded.
I have used the "Icon" shape from the Misc category
![image](https://user-images.githubusercontent.com/5158396/121345447-25cb8580-c925-11eb-8155-dd06b78c2618.png)
When I copy my svg file to a web site the cog wheel doesn't show up since it references a local file.

That is when saving directly as svg you can't use any of the options in the export dialog

**Comment by davidjgraph** [comment]
OK, but that's a different issue to this one.
