### ISSUE TITLE
About the latest draw.io

### ISSUE THREAD

**Issue by llan-ml** [jgraph/drawio-desktop#617]
* [-] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [-] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Recently, the latest drawio [enables decimal stokewidths](https://github.com/jgraph/drawio/blob/dev/ChangeLog#L8) in 14.7.5. I want to know if you have a plan to update the drawio version in drawio-desktop. Adjusting the linewidth in decimal is a quite common and necessary function.

**Comment by davidjgraph** [comment]
Yes, it will come in the next release. We don't currently have an ETA.
