### ISSUE TITLE
Allow pasting items within the currently visible screen area, instead of near the original position

### ISSUE THREAD

**Issue by pgp** [jgraph/drawio-desktop#619]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
For big graphs, I believe it's a bit uncomfortable to copy and paste an item in place, and then drag and drop it till the destination point (when it is out of the visible screen boundary).

**Describe the solution you'd like**
When pasting an item and its original position is not visible anymore, just paste it on a new position in the currently visible area (e.g. top left, top right, etc...)

**Comment by mararad** [comment]
Hi,

Does right mouse click > Paste here help?

Regards,

**Comment by pgp** [comment]
Yes, it works! However, a key shortcut would be welcome (e.g. CTRL+SHIFT+V for paste here, along with the standard CTRL+V for pasting into the original position)
