### ISSUE TITLE
Windows defender flags 8.8.0 as virus

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio-desktop#62]
If only it could scan itself...

**Comment by davidjgraph** [comment]
It's a false positive, we don't know what is triggering it at this point.

**Comment by SamuelColacchia** [comment]
To add more info to this issue, it appears to only happen during an initial download.

**Comment by davidjgraph** [comment]
I couldn't repeat it on initial download on a surface. I then went into windows explorer, context menu, scan with Windows Defender and it said the file was clear. Does any have exact reproduction steps or a video?

**Comment by SamuelColacchia** [comment]
Sure!

Initial info:
Windows 10 1803
Windows Defender KB2267602 (Definition 1.279.768.0)

Browsers tried:
Firefox Version 63.0 (64-bit) | Was able to download no issue
Chrome 70.0.3538.77Version 63.0 (64-bit)
Chrome Canary 72.0.3595.0 Version 63.0 (64-bit)
Edge 42.17134.1.0 | Was able to download no issue

Procedure:
_Pre-Steps_

1. Ensure Windows is update
2. Ensure Defender is update and Real-time protection is running

**Steps**

1. Navigate to https://about.draw.io/integrations/
2. Click download .exe (https://github.com/jgraph/drawio-desktop/releases/download/v8.8.0/draw.io-setup-signed-8.8.0.exe)
3. Note that windows defender detects the Unconfirmed X.crdownload as a Trojan

![capture](https://user-images.githubusercontent.com/10569553/47672741-fb5f9c00-db6f-11e8-94ae-49ed697df6e7.PNG)

![image](https://user-images.githubusercontent.com/10569553/47672788-1a5e2e00-db70-11e8-9e43-c226eeabfbe2.png)

**Comment by davidjgraph** [comment]
Thanks for the details. There are other reports, I'm just struggling to reproduce.

I just updated a copy of Win 10 and defender and tried to download the exe using the same versions of Chrome 70 and Edge, neither triggered defender, which had real time checking enabled.

What extensions do you have installed in Chrome?

**Comment by SamuelColacchia** [comment]
Well it appears this issue has been resolved with windows defender as V 1.279.771.0 no longer flags the download as a trojan.

For extensions i disabled all extensions prior to testing.

**Comment by davidjgraph** [comment]
OK, thanks for the update and testing. I guess the reports should stop soon, if the issue does occur again, just open another issue here.
