### ISSUE TITLE
[14.6.13 desktop] Collapse/Expand of containers on mac throwing error

### ISSUE THREAD

**Issue by b52src** [jgraph/drawio-desktop#623]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
expanding or creating collapsable containers in the 14.6.13 desktop app fails to open throwing `Uncaught TypeError: Cannot read property 'splice' of undefined` on macOS 11.3.1, web version this works fine. 

**To Reproduce**
1. Follow this article will get you the error: [https://drawio-app.com/create-a-container-shape-in-draw-io/](https://drawio-app.com/create-a-container-shape-in-draw-io/) 
2. Error will popup when you Collapse/Expand the group:`Uncaught TypeError: Cannot read property 'splice' of undefined`

**Expected behavior**
collapsing and expanding of collapsible to work correctly in the desktop app on Mac.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [14.6.13]

**Desktop (please complete the following information):**
 - OS: [MacOS 11.3.1]

**Additional context**
na

**Comment by davidjgraph** [comment]
I cannot repeat this. Could you please provide exact reproduction steps?

**Comment by b52src** [comment]
adding screen shots with steps taken here: [https://imgur.com/a/XWhOZlH](https://imgur.com/a/XWhOZlH)

**Comment by davidjgraph** [comment]
Thanks, but I still cannot repeat it. Do you have any plugins installed to the app?

**Comment by b52src** [comment]
I have Flows, Trees, and Explore  plugins enabled.
looks like it was the Trees plugin causing the issue, removed it and containers work.
