### ISSUE TITLE
Background color of label glitches and can't be retained.

### ISSUE THREAD

**Issue by BillyCottrell** [jgraph/drawio-desktop#624]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When you have a label outside the shape background of the text gets locked you can't change the colour or even uncheck the background, when you try to change the colour of the label directly and click outside of the shape/label, it automatically reverts back to its previous colour.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'More shapes'.
2. Scroll down to 'Networking' and then check 'IBM'.
3. Apply Changes.
4. Scroll through the shapes and select any shape from IBM.
5. Double-click the newly added shape and type some text.
6. Leave the shape by clicking on the background.
7. Now click the shape again.
8. Go to the tab 'Text'.
9. Try to change the text background colour.
10. Try to uncheck the background colour.
11. Edit the label again.
12. Try to change the background colour of the label directly.
13. As you can see now of the changes are being applied instead are being reverted to their previous state.

**Expected behaviour**
Changing the background colour of the label or even disabling the background colour should work just fine and shouldn't be reverted to its previous state.

**Screenshots**
[https://i.imgur.com/9ySweUk.gif](https://i.imgur.com/9ySweUk.gif)

**diagrams.net version:**

- diagrams.net version 14.5.1

**Desktop (please complete the following information):**
 - OS: Windows 10 Home v21H1

**Additional context**
The issue happens with shapes where the label is outside of the shape, don't know if it also happens when the label is inside of the shape and the shape has a transparent background.

**Comment by mararad** [comment]
Hi,

if you double click the shape and change the background color as shown in the image, does it help?

![txt color](https://user-images.githubusercontent.com/44292306/122020035-b510e700-cdc4-11eb-9c97-c9b266a089e3.JPG)

**Comment by BillyCottrell** [comment]
Hi @mararad, this does indeed work but only partially as you can see in the following screenshot.
That's because you are only setting the background of the label itself, but the background of the shape remains black.
![https://i.imgur.com/dydsuuC.png](https://i.imgur.com/dydsuuC.png)

**Comment by BillyCottrell** [comment]
So I found out that this only occurs when you add a new icon from the menu from under the IBM sections. When you start of with a diagram from IBM and copy the existing ones you can freely change that background.

Seems like the background color setting is bugged out for some reason for newly added icons:
https://i.imgur.com/Hu5s1at.gif

Hope this helps!
