### ISSUE TITLE
Cannot open very simple SVG for editing in Draw.io desktop

### ISSUE THREAD

**Issue by jp-coetzee** [jgraph/drawio-desktop#625]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

When I try and open this very simple SVG for editing (also attached [sample rectangle v1.zip](https://github.com/jgraph/drawio-desktop/files/6654736/sample.rectangle.v1.zip)), I get the "Not a diagram file" error.  I can import the SVG into a new blank diagram, but then I cannot edit it. 

I have run the code through an XML syntax checker.  I'm using Windows 10, draw.io-14.6.13-windows-no-installer.

Any ideas what the error might be and how to fix it? Does draw.io have any error logs I can look at?

many thanks

    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xl="http://www.w3.org/1999/xlink" version="1.1" viewBox="0 0 898 574" width="898pt" height="574pt" xmlns:dc="http://purl.org/dc/elements/1.1/">
    	<metadata>Produced by OmniGraffle 6.6.2
    		<dc:date>2021-06-15 09:19:28 +0000</dc:date>
    	</metadata>
    	<defs/>
    	<g stroke="none" stroke-opacity="1" stroke-dasharray="none" fill="none" fill-opacity="1">
    		<title>Canvas 1</title>
    		<rect fill="white" width="1037" height="845"/>
    		<g>
    			<title>Layer 1</title>
    			<rect x="187" y="343" width="639" height="159" fill="white"/>
    			<rect x="187" y="343" width="639" height="159" stroke="black" stroke-linecap="round" stroke-linejoin="round" stroke-width="1"/>
    		</g>
    	</g>
    </svg>

**Comment by davidjgraph** [comment]
This isn't an SVG editor, the message is correct. It's a diagramming application that can only open diagram files.

If you want to import an image, drag and drop the image into the editor canvas.

**Comment by jp-coetzee** [comment]
Thank you for your reply. 
Draw.io can save and open SVG, see below. Does that mean it can only **edit** SVGs that were **created** by Draw.IO?

![Drawio_Save_SVG](https://user-images.githubusercontent.com/56002865/122052488-a8e55380-cddd-11eb-9eff-926b7eee4e78.png)

![Drawio_Open_SVG](https://user-images.githubusercontent.com/56002865/122052453-9ff48200-cddd-11eb-9037-518b2d175574.png)

**Comment by davidjgraph** [comment]
Correct. When we save as SVG we embed the diagram file within the SVG itself. Stand-alone SVG is only an SVG image and behaves like any image type.

**Comment by jp-coetzee** [comment]
OK, so SVG is a filetype that Draw.IO can use to store its diagrams, but the content of SVGs from other diagramming tools (Visio, OmniGraffle) are not compatible.

Many thanks
