### ISSUE TITLE
"Copy as image" does not render custom fonts in the image

### ISSUE THREAD

**Issue by caprarm** [jgraph/drawio-desktop#626]
### Preflight Checklist

* [ X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In the draw.io desktop app, in macOS, i have a custom font defined (https://virgil.excalidraw.com/Virgil.woff2). When i use the "Copy as Image" it copies the image using a default font

**To Reproduce**
1. Add a custom font to draw.io
2. use that custom font in a drawing
3. right click the drawing and select Copy as image
4. note the font is inaccurate 

**Expected behavior**
The font should be rendered properly in the copied image

**Screenshots**
What i see in draw.io
![image](https://user-images.githubusercontent.com/59487676/122103877-f0fb7a80-cdcb-11eb-8215-46435d067587.png)

What i get when i Copy as image
![image](https://user-images.githubusercontent.com/59487676/122103899-f953b580-cdcb-11eb-98f6-644d4f259e5c.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: diagrams.net 14.6.13

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7

**Comment by joel-loewenstein** [comment]
Hello, 
i witnessed the same behavior. Same for Export, custom Font is not rendered there. I think some years ago this was already an issue according to google search, but i just created some presentations with pictures from desktop app on mac. Some of them were fine. Now currently the only way to get a custom font exported is PDF format. 
I am convinced that this happened with the last update but did not verify this. 

Additionally within Teams the Fonts are shown scrambled... is that related or should i open a second issue?
![CSDM Teams - with Error](https://user-images.githubusercontent.com/4130973/122167573-75590680-ce7b-11eb-965c-c81a46f0a566.png)

**Comment by taksedo** [comment]
The issue is still there
