### ISSUE TITLE
Improve the Efficiency of Diagramming by Adding Keyboard Shortcuts

### ISSUE THREAD

**Issue by ZRQZRQZRQ** [jgraph/drawio-desktop#633]
# Add Some Keyboard Shortcuts 
I have used draw.io for learning purposes and realized that almost all kinds of options in draw.io require at least one click by the mouse. This is especially annoying when I intend to create mind maps. My advice to solve the problem is that we can enable "enter" &"↓“as a shortcut for creating a similar shape right behind the current shape. Namely, use "enter" & "→” for the right, use "enter"&"↑“ for the top, use ”enter“&“←”for the left.

**Comment by KacimiBadr** [comment]
Hey i don't know about the shortcuts, but you can save various type of customised graphics, i you select any groupe of items holds and move them to the menu just under search bar, above general. (it will create the "scratchpad")
