### ISSUE TITLE
Can't open multiple drawings on Mac

### ISSUE THREAD

**Issue by Timmmm** [jgraph/drawio-desktop#639]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
On Mac it's difficult to run the app multiple times, and the app itself doesn't support multiple windows or tabs, so essentially you can only edit a single drawing at a time.

**Describe the solution you'd like**
You should be able to open multiple windows.

**Describe alternatives you've considered**
It *is* possible to run an app twice on Mac, but it's not user friendly.

**Comment by m-mohamedin** [comment]
Doubling clicking a drawio file will open the file in a new window. The same can be done using File -> Open/New
![Screen Shot 2021-06-25 at 11 05 35 AM](https://user-images.githubusercontent.com/24944765/123444786-46424380-d5a5-11eb-828c-bc8866f936ef.png)

**Comment by Timmmm** [comment]
Ah I see. That's a bit unintuitive - File->Open Recent always opens in the same window so I assumed File->Open would do the same. In most software they behave the same way.

**Comment by vision-ken** [comment]
Suggest always open recent in a new window.
