### ISSUE TITLE
upgrade to drawio 14.8.0

### ISSUE THREAD

**Issue by cmdares** [jgraph/drawio-desktop#641]

**Comment by mararad** [comment]
Hi,

Not sure why this issue is opened. Could you provide me with additional details?

Regards,

**Comment by helmo** [comment]
I assume that the original poster is wondering when version 14.8.0 becomes available in this repo as a package.

I assume that one of the maintainers needs to follow the release steps in https://github.com/jgraph/drawio-desktop#developing

**Comment by davidjgraph** [comment]
Requests to update are off-topic, the project always needs an update.
