### ISSUE TITLE
Flip and menu rotation don't work for grouped shapes

### ISSUE THREAD

**Issue by lvmm** [jgraph/drawio-desktop#650]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Flip and menu rotation don't work for grouped shapes

**To Reproduce**
1.    add two shapes to the diagram - I used circle and triangle from General shapes
2.    select both and group them (press ^G)
3.    select Arrange-Direction-Flip Horizontal menu item - nothing happens
4.    select Arrange-Direction-Rotation, enter 45 and press enter - selection box rotates 45 degrees but the shape itself doesn't

**Expected behaviour**
in step 3 the whole grouped shape should've flipped and in step 4 it should've been rotated

**draw.io version (In the Help->About menu of the draw.io editor):**
- 14.6.13

**Desktop (please complete the following information):**
 - windows 10-64

**Additional context**
Steps 3 or 4work for atomic (ungrouped) shapes e.g. single triangle, only grouped shapes are affected. Rotation by dragging the circular arrow handle works even for grouped shapes, only rotation via menu is broken. Also I find it completely illogical that flipping around the *vertical* axis is called 'Flip horizontally', surely it has to be the other way around.

**Comment by auersteve** [comment]
I have noticed the same issue regarding rotation of grouped shapes. The original bug report was for version 14.6.3. I am using drawio version 15.2.7 (actually, diagrams.net 15.2.7, according to help>about), and the bug has not yet been fixed. Is this on the list of bugs to fix?

Also, regarding lvmm's comment about flipping around the vertical axis being called "flip horizontal":  my take is that the current nomenclature is OK. My logic is as follows: in physics or math nomenclature, if you "rotate an object about an axis", by definition everything on that axis does not move. And, "flipping" is just a 180 degree rotation. So, if you flip about the vertical axis, this just amounts to flipping left for right, which is the same as flipping horizontally.  Actually,   I personally would prefer "flip left-right" to "flip horizontal", and "flip up-down" to "flip vertical"
