### ISSUE TITLE
The "Autosize" command does not work in horizontal direction; the "Constrain proportions" control has no effect

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio-desktop#652]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When the **Autosize**![image](https://user-images.githubusercontent.com/9047168/125626994-c3b60be9-55bb-4dd7-bcde-5b1a4512e836.png) button is pressed,
(a) The shape should resize to fit the text in both X and Y directions.
(b) It should respect the "Constrain proportions" setting.

(refer to https://www.diagrams.net/doc/faq/autosize)

**To Reproduce**
1. Insert a rectangle shape.
2. Enter some text in it. 
3. Resize it to a larger size (in both x and y directions)
4. Press the **resize** button. <br>![image](https://user-images.githubusercontent.com/9047168/125623392-985fe3cb-0700-43f4-bf27-82c97e94b45e.png)

**Expected behavior**
The rectangle should shrink in x and Y directions to fit the text.
(That's what the icon of the button indicates.)

**Actual behavior**
The rectangle shrinks only in Y direction; not in X direction. [BUG#1]

Further, there is no effect of the **Constrain proportions** control. [BUG#2]
Regardless of whether it is selected, the rectangle shrinks identically.

**Screenshots**
**Case-1: The rectangle is smaller than the text in both directions, and the "constrain proportions" checkbox is unselected** 

Before
![image](https://user-images.githubusercontent.com/9047168/125624501-dadd95aa-8267-4037-97a6-b037893bdbc4.png)

After
![image](https://user-images.githubusercontent.com/9047168/125624573-672186b0-a14c-4dda-a1fa-2d6b1473afd9.png)
Note that the rectangle did not expand in X direction to encompass the text (it should).

**Case-2: The rectangle is smaller than the text in both directions, and the "constrain proportions" checkbox is selected** 
Before
![image](https://user-images.githubusercontent.com/9047168/125624654-a353752d-773f-4284-88ad-d9cd0d33c4da.png)

After
![image](https://user-images.githubusercontent.com/9047168/125624734-c782045a-3d10-4508-9bb0-84376a4b3a06.png)
Note that the X:Y ratio has changed (it should not). 
Secondly, the rectangle's X dimension did not change at all (it should).

**Case-3: The rectangle is larger than the text in both directions, and the "constrain proportions" checkbox is unselected** 

Before
![image](https://user-images.githubusercontent.com/9047168/125624936-f6c4d8fd-d53a-4797-8177-826cefc2976f.png)

After
![image](https://user-images.githubusercontent.com/9047168/125624988-b55804dd-af04-4811-940a-429681b107d4.png)
Note that the rectangle did not shrink in X direction to fit the text (it should).

**Case-4: The rectangle is larger than the text in both directions, and the "constrain proportions" checkbox is selected** 
Before
![image](https://user-images.githubusercontent.com/9047168/125625321-50de6a07-d4f2-423c-be7a-1bab59874606.png)

After
![image](https://user-images.githubusercontent.com/9047168/125625359-af6b7848-034f-42a5-bf08-0d5275d4734e.png)
Note that the X:Y ratio has changed (it should not). 
Secondly, the rectangle's X dimension did not change at all (it should).

**draw.io version (In the Help->About menu of the draw.io editor):**
Desktop version 14.6.13

**Desktop (please complete the following information):**
 - OS: Win 10 Home, 64 bit

**Additional context**
NA

**Comment by mararad** [comment]
Hi,

I recorded a video for you. My suggestion would be to tick Autosize in Property/Values on the right when the shape is selected. Autosize in Arrange tab works a bit differently.

Note: the autosize effect will be only seen when the label is changed in some way i.e you can change font family, font size, use bold/italic, text itself etc. and only then you'll see the difference.

Does this help?

Regards,

https://user-images.githubusercontent.com/44292306/125773282-0ba76607-47a9-4ce4-9d8f-a372ab5a2bcf.mp4

**Comment by raindropsfromsky** [comment]
Hi

your video shows that a similar feature is provided at another place, which works in a little different manner. But that has nothing to do with the bugs I raised. 

Your video would be useful only if I were looking for a workaround. But that is not my intention. 
These controls must work as described in the blog (and also as expected); and hence the bugs.
