### ISSUE TITLE
draw.io allows editing of read-only files without warning/explicit user concent

### ISSUE THREAD

**Issue by ll3141** [jgraph/drawio-desktop#654]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
draw.io allows to edit read-only files. Warns only on save attempt

**Expected behavior**
draw.io should at least warn prominently that a file is read-only when opening it.
Better would be to reject editing until explicit user action.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io [12.6.13]

**Desktop (please complete the following information):**
 - Win10

**Comment by mararad** [comment]
Hi,

could you recheck drawio version, please? Is it maybe 14.6.13?

Could you describe all the steps you performed related to giving permissions prior diagram opening in drawio desktop? It would be great if you could attach an example file so we could test it

Regards,

**Comment by ll3141** [comment]
yes, sorry 14.6.13 on win10.0.19042 pro

There are no special steps required.
Just set the read-only flag on a draw.io file.
When opening the file, there is no indication that the file is read-only and the file can be edited.
The first indication you fucked up will be the "unsaved changes ..." text in the menu bar when trying to save.

This is a problem in any case, because the read-only status will be there for a reason.

When using a version control system, it most likely indicates, that the file need locking for edit.
In our case this resulted in data loss, because an inexperienced user locked (and was forced to update in the process) a file after the fact, while the file was still open in draw.io, then save. That then lead to loss of all changes since his previous update.

I am not sure if draw.io files are easly merged, but I doubt it. The file structure seems to cryptic for a successful, automatic merge of a complex change.

I think it would be best to show a "read-only" indicator (like the "unsaved changes ...") in the menu bar  when a read-only file is opened in draw.io and prevent editing.

There are more possibilities. Other editors either open the file exclusively (preventing outside changes) or indicate the open file was changed on disk and propose to reload or save with an other name.

**Comment by m-mohamedin** [comment]
Read-only status would be shown in the next release. Edits would still be possible but saving would show an error. Save-as can be used then in order not to lose work.

**Comment by ll3141** [comment]
This is an improvement, but ...

we use subversion to version our diagrams.
Because drawio-Files are not mergable, we use subversions file-locking feature to prevent parallel editing.

Subversion sets the RO-Flag when checking out and/or updating a file marked to require locking.

Being told that the file is RO when trying to save is a bit late in this scenario.
