### ISSUE TITLE
Copy As Image Behavior

### ISSUE THREAD

**Issue by 2608027102** [jgraph/drawio-desktop#659]
* [√] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [√ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
In the previous version of drawio, CopyAsImage can be pasted properly into Confluence, but with the latest version of drawio, it does not display properly when pasted into Conference. I don't know how the previous version CopyAsImage was implemented, but I need the behavior of the previous version.

**Describe the solution you'd like**
It would be great if add the previous behavior to the right-click menu if possible.

**Describe alternatives you've considered**

**Additional context**

**Comment by rhythm321** [comment]
I just installed draw.io version 14.6.13 on OS: Win10. Earlier the feature "copy as image" used to work to paste in MS Word (2013). Now, it's not working. Nothing is pasted in the word file.

Update: The functionality works well in Office 2019

**Comment by Kur0x** [comment]
Same issue in 15.4.0. "copy as image" not working in MS Word (2013) and other app. Background  of pasted image become black.
