### ISSUE TITLE
Paper Size keeps changing to 11" x 11" and blank pages appearance

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio-desktop#66]
1. The potential issue with paper size changed when the file is opened via Desktop app 
(from Us letter, it becomes Custom 11x11) and three pages have extra white space at the top 
which maybe make blank pages when printed.
(Diagram was created via draw.io online and then opened via Desktop app)

2. When user's file is opened via draw.io online in Opera (drag&drop into canvas)
all pages look ok but when go File > Print Preview
again extra blank pages are shown

https://desk.draw.io/a/tickets/9766

**Comment by alderg** [comment]
What version number to you see in Help, About?

**Comment by mararad** [comment]
I used Opera Version: 56.0.3051.52 and draw.io is 9.3.2 to drag&drop the user's file.
And Desktop app where I drag&dropped the file is 9.3.1

**Comment by mararad** [comment]
I used Opera Version: 56.0.3051.52 and draw.io is 9.3.2 to drag&drop the user's file.
And Desktop app where I drag&dropped the file is 9.3.1

**Comment by alderg** [comment]
Can you attach the file pls?
