### ISSUE TITLE
Multiple consecutive Drawio CLI invocations occasionally fail on Debian linux

### ISSUE THREAD

**Issue by steinwelberg** [jgraph/drawio-desktop#664]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using the Draw.io CLI on Debian linux (through the [mkdocs-drawio-exporter](https://github.com/LukeCarrier/mkdocs-drawio-exporter), occasionally exporting an image fails with exit code `-11` without any additional exception.

A number of the below Draw.io CLI export commands are executed as the mkdocs-drawio-exporter exeports all the files in a mkdocs site in a sequence:

```
drawio --export /home/circleci/docs-checkout/docs/internal/docs/sdk-flows/diagrams/DynamicClientUpdateV1.drawio --page-index 0 --output /home/circleci/docs-checkout/docs/internal/docs/rendered-diagrams/b5604b745821edcc06f228cd8dac615cfa4f90b4-0 --format svg
```

The export format (png/svg) does not matter, I have not tried other flag variations.

Retrying to build the mkdocs site makes the same Draw.io CLI export command that failed previously succeed.

**To Reproduce**
1. Create a mkdocs site
2. Add the [mkdocs-drawio-exporter](https://github.com/LukeCarrier/mkdocs-drawio-exporter) plugin
3. Add 20 of drawio files
4. Build the mkdocs site on a Debian linux machine

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.6.13

**Desktop (please complete the following information):**
 - OS: Debian Linus

**Additional context**
On MacOS this problem does not exist. There, all consecutive Drawio CLI invocations are successful.

**Comment by davidjgraph** [comment]
We'd need an example process that does not involve third-party software to consider looking. Please describe a stand-alone case that repeats.
