### ISSUE TITLE
group shape  resize  can't  get correct result

### ISSUE THREAD

**Issue by lovekobe24** [jgraph/drawio-desktop#665]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
  when i group some shapes,then  i resize the group shape, some shape in the group cannot  get correct position.

**To Reproduce**
1. draw a rectangle and a circle,put circle in center of the rectangle.
2.  group the rectangle and circle
3.  resize the group
4.  the circle is not in center of the rectangle any more

**Expected behavior**
the circle relative position  remains unchanged

**Screenshots**
![企业微信截图_16276067341705](https://user-images.githubusercontent.com/19279810/127584163-e20e51a4-0b11-4950-9d81-88e09b2c6927.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- 14.9.3

**Desktop (please complete the following information):**
 - Windows

**Additional context**

**Comment by lvmm** [comment]
Resizing doesn't work very well if group contains a mixture of shapes with fixed and free aspect ratios. If you remove aspect=fixed from the circle's style it will move as expected, but then it won't be a circle any more. Still a bug.

**Comment by mararad** [comment]
Reproduced in desktop 14.6.13 Win 10 Pro
