### ISSUE TITLE
The inserted SVG image is not displayed in Office Word

### ISSUE THREAD

**Issue by ueJone** [jgraph/drawio-desktop#666]
**Describe the bug**
1. Drag a external svg file to Draw.io
2. Export as svg file
3. Copy the file exported to Word, then the image shows nothing
4. The svg file exported can be displayed normally with Chrome

- draw.io version 14.6.13
- OS: Win10

**Comment by GeorgeLiou** [comment]
draw.io version 14.9.6 also had similar problem.

User added svg files, even if they are added as reusable library, are not exported correctly. 
Not only Microsoft Word/PowerPoint 2019 can't read them, but also inkscape 1.1 .

Reproduce sample files are listed as attachments below:
[Sample.zip](https://github.com/jgraph/drawio-desktop/files/7113125/Sample.zip)

In Sample.zip are 4 files: sample.svg, Sample.drawio, SampleSvg.xml, SampleOutput.svg
 + sample.svg is the source svg file.
 + Sample.drawio contains two hexagon, one is black, the other is green.
   + The black one is imported by drag&dropping sample.svg 
   + The green one is copied from the black one, and applied "Edit Style" function with "editableCssRules=maincolor;" according to https://www.diagrams.net/doc/faq/svg-edit-colours
 + Sample.xml is generated by "New Library" function then drag&drop the black and the green hexagon into it and edit the name to Orig and Styled.
 + SampleOutput.svg  is the result by using "Export as -> SVG" 

SampleOutput.svg is not vector graphic if opened in inkscape, and would be empty if imported into PowerPoint 2019.

**Comment by davidjgraph** [comment]
Our SVG export generally contains foreign objects. That's an early architectural decision, we cannot change that now.

Read https://www.diagrams.net/doc/faq/svg-export-text-problems for how to switch them off by default.

**Comment by davidjgraph** [comment]
23.0.2 now replaces the warning text with a high-res image of the label, if embed images and embed fonts are ticked in the SVG export dialog.
