### ISSUE TITLE
please update drawio-desktop to 14.9.5

### ISSUE THREAD

**Issue by szmabcd** [jgraph/drawio-desktop#668]
please update drawio-desktop to 14.9.5,thanks!

**Comment by PulsarFX** [comment]
I second that. 
In 14.8 the move sinlge step back and forth was implemented, which is important for my drawing.
https://github.com/jgraph/drawio/issues/1103#issuecomment-864166631

**Comment by DaPa** [comment]
+1

**Comment by davidjgraph** [comment]
Requests to update are off-topic, the project always needs an update.
