### ISSUE TITLE
Link to Mac intel installer does not work

### ISSUE THREAD

**Issue by edgehero** [jgraph/drawio-desktop#671]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
Fixed, thanks for report.
