### ISSUE TITLE
The draw.io.exe process does not exit when I close several of its windows at the same time

### ISSUE THREAD

**Issue by tsegha** [jgraph/drawio-desktop#672]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The draw.io.exe process does not exit (still visible in the task manager) when I close several of its windows at the same time.

**To Reproduce**
1. Open at least 2 draw.io files
2. In the task bar, right click -> "Close all windows" on the Draw.io button
3. The error occurs: All windows close but the draw.io.exe process is still visible in the Windows task manager.

**Expected behavior**
The draw.io process should exit

**Screenshots**
See Attached screenshots
![01 - 2 windows are open](https://user-images.githubusercontent.com/59162082/129736761-851389fa-1d9e-4928-9982-2a32ebfaf1ed.png)

![02 - Right clic on Draw io in TaskBar](https://user-images.githubusercontent.com/59162082/129736770-ef7a146d-dc9d-4e9e-ab9b-93f4f44984c8.png)

![03 - Draw io windows are closed in TaskBar](https://user-images.githubusercontent.com/59162082/129736772-a574cbca-2978-487f-b063-d76fd7deb6a2.png)

![04 - Process Draw io exe still open in TaskManager](https://user-images.githubusercontent.com/59162082/129736773-8efb322e-4d8e-43a1-9ae0-618b01125188.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version : diagrams.net 14.5.1

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 [21H1 build 19043.985]

**Additional context**
1. The problem also sometimes appears when closing the windows one after the other.
2. The problem does not appear if only one Draw.io window is open at a time

**Comment by mararad** [comment]
Hi,

I couldn't reproduce this.
Win 10 Pro and draw.io 14.9.6 Windows installer

If you update draw.io to the latest 14.9.6, are you still seeing this? If you are, please record a video and attach it here.

https://user-images.githubusercontent.com/44292306/129889862-d41198af-9557-45f2-952c-c4015d4b4714.mp4
