### ISSUE TITLE
To Front not working (linux v14.9.6)

### ISSUE THREAD

**Issue by gskerry** [jgraph/drawio-desktop#673]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Arrange -> To Front does not bring element to front

**To Reproduce**
1. Add element 1
2. Add element 2 (over element 1)
3. Select element 1
4. Context menu (right click) >> To Front

**Expected behavior**
Element 1 should be moved to the front of element 2

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io v14.9.6

**Desktop (please complete the following information):**
 - Ubuntu (Mint) 20.1 Cinnamon

**Additional context**

**Comment by bugrasan** [comment]
works for me on linux manjaro w/ v14.9.6

**Comment by profriemke** [comment]
works on kubuntu 21.04 KDE/X with v14.9.6

**Comment by davidjgraph** [comment]
@gskerry Could you attach a video of the whole operation please?

**Comment by gskerry** [comment]
Hello,
Yes. Will work on a screen-record solution. Thanks
