### ISSUE TITLE
Pasting onSuccessfulLoginBeforeVerifiedDeviceCheck after selecting a box freezes drawIO desktop

### ISSUE THREAD

**Issue by dpb06** [jgraph/drawio-desktop#674]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Pasting the text onSuccessfulLoginBeforeVerifiedDeviceCheck into a newly created text box causes the display window of drawIO to freeze. 
Closing the window needs to be done using Task Manager (Ctrl-Shift-Esc). 
The "draw.io" button in top left, minimize and maximize are the only buttons to function. 

DrawIO seemed to stabilize after being left processing this action for about 15 minutes. During this time DrawIO's CPU usage increased to 35-40%

**To Reproduce**
1. Open a new diagram
2. Drag a text box into the diagram (Oval, Curved rectangle, Rectangle etc)
3. Select the text box when there is no text inside, so that you can resize the box
4. Ctrl-V the text onSuccessfulLoginBeforeVerifiedDeviceCheck onto the box

**Expected behavior**
The text "onSuccessfulLoginBeforeVerifiedDeviceCheck" is entered into the box

**Screenshots**
![image](https://user-images.githubusercontent.com/341625/129988828-f2d47261-06ee-4f2b-b698-b9ee78109ff5.png)
The above image was taken after pasting the text

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.5.1

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
It appears that once text has been entered into the text box, doing the same steps above to replace that text does not cause an issue.
Pasting the text in after double clicking on the text box also does not cause this issue.
If there is a box in the window with the same text, it appears this also does not cause this issue.

However I have recreated with both mildly populated and freshly created diagrams. I have also had this occur 20 minutes into creating an (unsaved) diagram.

**Comment by davidjgraph** [comment]
Could you re-check after updating to 14.9.6 please?
