### ISSUE TITLE
Using FontAwesome with draw.io desktop?

### ISSUE THREAD

**Issue by Swoy** [jgraph/drawio-desktop#68]
It is not entirely clear from your [link](https://about.draw.io/zzz-demo-pages/font-awesome/) how to use FontAwesome with this desktop app. 

Could you maybe shed some light on this?

**Comment by davidjgraph** [comment]
That's a template wordpress page that shouldn't have been published.

**Comment by Swoy** [comment]
So fontAwesome is not supported by this app?

**Comment by davidjgraph** [comment]
There's a link from https://github.com/jgraph/drawio-libs that will open in online version. For desktop version download the library and open it via File menu.

**Comment by Swoy** [comment]
Great, thanks!

**Comment by iaeiou** [comment]
See also this post for details: https://roneo.org/en/diagrams.net-adding-icons-font-awesome-twemoji
