### ISSUE TITLE
Improving the Cropping UI

### ISSUE THREAD

**Issue by dannystaple** [jgraph/drawio-desktop#680]
* [/] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [/] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

I find the current cropping dialogue, with the expanding square, quite frustrating. It doesn't always allow me to select a full height or width of an image, especially when I really want to just trim the side off.

I frequently use drawio-desktop to create diagrams involving screenshots, along with arrows and text.

**Describe the solution you'd like**

An in-document cropping feature. The workflow would be:
* Select the image
* Context menu for a crop tool
* Cropping handles appear on the image in the document. These are 4 corners, plus midpoints on the boundary lines.
* Drag these cropping handles to resize the cropping area. Or drag the image within the cropping area to position it there.
* Select off the image - ie click anywhere outside the cropping area to conclude the cropping operation.
* This leaves a trace in the undo buffer and can be undone.

This would be even better if the drag handles would pick up on context like aligning with other drawing boundaries and midpoints.

**Describe alternatives you've considered**

An alternative could be to get a selection tool, drag a rectangle over the area to be cropped, and then click crop. I don't think it would be as sensible a workflow, unless the boundaries of that rectangle could then be adjusted before making the crop.

**Additional context**

**Comment by davidjgraph** [comment]
Declined
