### ISSUE TITLE
Pease add RACK  Feature 

### ISSUE THREAD

**Issue by szmabcd** [jgraph/drawio-desktop#681]
The cabinet displays the size of the equipment, and the left and right sides of the cabinet can display numbers.

![image](https://user-images.githubusercontent.com/38176269/130164052-b5b72390-6e4a-4030-bf89-a297f9c031e1.png)

**Comment by mararad** [comment]
Hi,

Thanks for the suggestion but manual number adding is the only solution and unfortunately, something we are not planning (not have resources) to improve in near future.

Thanks for understanding.

**Comment by davidjgraph** [comment]
Closing for not agreeing code of conduct.
