### ISSUE TITLE
`presetColors` in configuration disables color selection overall for all shapes and connectors

### ISSUE THREAD

**Issue by bugrasan** [jgraph/drawio-desktop#682]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
when a `presetColors` parameter is in configuration, then you can't change the fill color and the following error is shown: `Unknown error` `Uncaught TypeError: Cannot read property 'toUpperCase' of undefined`
even the shape line disappears (no color).

I consider this a grave but, since with `presetColors` set in configuration no colors can be selected anymore.

**To Reproduce**
1. Install drawio **v14.9.6** (doesn't matter windows or linux, happens on both)
2. open drawio
3. from the menu, **Extras** => **Configuration..."
4. enter the following snipplet as configuration
    ```json
    { "presetColors": [ "001155" ] }
    ```
5. click **Apply** button, and then **OK** button
6. then restart drawio
7. create a new blank diagram
8. drag'n'drop a shape from "General" library
9. create a connector by clicking the arrows that appear when hovering a shape
10. stay with the selected connector and click on the right hand panel, **Line** color
11. you will get the error msg:
    `Unknown error` `Uncaught TypeError: Cannot read property 'toUpperCase' of undefined`
12. click **OK** to close the dialog
13. the connector line will be selected, but disappears...
14. if not, while still the connector is selected click on the right hand panel, **Line** color
15. then the error msg will reappear and the connector line will disappear

**Expected behavior**
This was working fine with previous release, probably v14.6.13.

**Screenshots**
if required please ask.

**draw.io version (In the Help->About menu of the draw.io editor):**
v14.9.6

**Desktop (please complete the following information):**
 - OS: windows & linux

**Additional context**
article on how to customize colors through configuration with `presetColors`:
https://drawio-app.com/customise-default-colours-fonts-styles-and-the-draw-io-ui-in-confluence-cloud/

**Comment by mararad** [comment]
Hi,

I reproduced this in 14.9.6 and Win 10 Pro.
This is working well in diagrams.net online. 

https://user-images.githubusercontent.com/44292306/130781765-75f89586-c059-4652-904f-9ff169dc5e95.mp4

**Comment by davidjgraph** [comment]
This was fixed in 14.9.7, unfortunately. It will be in the next desktop release.
