### ISSUE TITLE
After drawing a line a rectangle is automatically added 

### ISSUE THREAD

**Issue by Badkast** [jgraph/drawio-desktop#683]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
After drawing a line from a connection point a rectangle is automatically added to the end of the line

**To Reproduce**
 I don`t know how to reproduce this behavior it just happened out of nowwhere. 

**Expected behavior**
I expected to just have a line without rectangle 

**Screenshots**

Below is a video:
https://user-images.githubusercontent.com/62446598/130583565-693d2500-771b-4df4-b493-82d35958a85e.mp4

// Settings of the drawn line:
![image](https://user-images.githubusercontent.com/62446598/130583825-2e4affe3-e937-42b1-a132-4170bce7dca2.png)
![image](https://user-images.githubusercontent.com/62446598/130583918-b1c74339-2682-4344-918f-dcd615f2e5f8.png)

- draw.io version [diagrams.net 14.9.6]

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Additional context**
I have restared Draw.io and Windows but none of it helped. Crreating new files also didn't make a difference.

**Comment by mararad** [comment]
Hi,

I couldn't reproduce this draw.io version 14.9.6 and Win 10 Pro. 

Did you use https://github.com/jgraph/drawio-desktop/releases to install desktop draw.io?
Did you maybe hold Ctrl while dragging? Ctrl+drag will clone a shape (as shown when light blue arrow is hovered)

https://user-images.githubusercontent.com/44292306/130771778-63cd15fa-a840-4af6-8db5-895b638e6c1a.mp4

Regards,
