### ISSUE TITLE
Cross-Functional Flowchart 支持移动线条整体放大像Excel一样，而不是像在WORD表格哪有整体不变局部调整。

### ISSUE THREAD

**Issue by mojusousuo** [jgraph/drawio-desktop#685]
目前的操作移动图形内的线条只能局部左右移动，而不是整体移动线条 像EXCEL一样移动线条会把旁边的表格一起移动。

**Comment by mojusousuo** [comment]
![image](https://user-images.githubusercontent.com/26040438/131065107-ddf985ed-922f-4eb2-ac08-1bbfd6284b34.png)

**Comment by mojusousuo** [comment]
把图1的功能
![动画](https://user-images.githubusercontent.com/26040438/131065631-0a72d44e-2f2a-4671-bf38-eb2eba963448.gif)

修改为图2这种
![动手打](https://user-images.githubusercontent.com/26040438/131065656-8d4e46f7-9662-4a50-95fe-9f5fb1700599.gif)

**Comment by mojusousuo** [comment]
最后的结果希望可以是这种。
![动1](https://user-images.githubusercontent.com/26040438/131067864-366b1450-95c2-4724-837c-6f926b5cb6c2.gif)

**Comment by StudentWeis** [comment]
我建议你用英文讲一下~
