### ISSUE TITLE
Export diagram to an image can't  find "selection only" checkbox

### ISSUE THREAD

**Issue by Limorettle** [jgraph/drawio-desktop#686]
export as a PNG just the selected shapes.
in help doc, there's "Selection only" checkbox,
![1630310408(1)](https://user-images.githubusercontent.com/66759791/131306856-33dae7f3-0204-44fe-a5dc-35111d679122.png)

but in version 14.9.6, can't find it.
![1630310591(1)](https://user-images.githubusercontent.com/66759791/131306808-187a687a-72e0-4895-8258-a7f2faec2194.png)

**Comment by mararad** [comment]
Hi,

You should select shapes first and then export selection only.
I recorded video for you. Hope it'll help.

Kind regards,

https://user-images.githubusercontent.com/44292306/131330327-1cc43917-a14a-4325-9a1a-be10245bc2cd.mp4

**Comment by Limorettle** [comment]
Thank you very much for your answer! But it didn't seem to solve my question. my question is described in the pictures below.
![1](https://user-images.githubusercontent.com/66759791/131335949-71b7c0c0-1de5-4677-958e-20c17895bbfb.png)
![2](https://user-images.githubusercontent.com/66759791/131335980-45b1e244-4681-45e2-aa7a-fd94ef0dcac0.png)
![3](https://user-images.githubusercontent.com/66759791/131336020-6e9a34de-82cf-4127-813f-fa2329708577.png)

**Comment by mararad** [comment]
Thanks for the additional info. Unfortunately, it is not possible.

Kind regards,
