### ISSUE TITLE
diagrams.net app 14.9.6 release does not import gliffy files while online version works fine

### ISSUE THREAD

**Issue by vincentgerris** [jgraph/drawio-desktop#688]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Draw.io latest desktop release does not show anything when importing Gliffy file while https://app.diagrams.net/?splash=0 does work as expected.

**To Reproduce**
1. Go to draw.io desktop - (14.9.6)
2. Click on import - choose the gliffy file
3. See error - nothing happens in the app

**Expected behavior**
To view the gliffy diagram just like in https://app.diagrams.net/?splash=0

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version : diagrams.net 14.9.6 ()

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.5.2

**Additional context**
none

**Comment by davidjgraph** [comment]
Desktop doesn't have Gliffy import support.

**Comment by vincentgerris** [comment]
hi, instead of instantly closing it, can you elaborate on that and perhaps change it into a feature request? This is also not clear from documentation nor the feedback from the application. thank you

**Comment by davidjgraph** [comment]
It's not technically possible in the Desktop tool so cannot be added. We'll look into a better dialog when it's attempted.

**Comment by vincentgerris** [comment]
would you mind explaining why not? seems like a simple conversation of JSON to XML to me? thank you

**Comment by davidjgraph** [comment]
The gliffy import is written in Java, there isn't any sensible way to run Java within/with electron.

This is for migrating from their online version?

**Comment by vincentgerris** [comment]
aha, thanks for clarifying. Is the source open for that part? Perhaps someone can port it, or it could hook in to a webservice. Yes I wanted to put some gliffy diagrams in draw.io editor, I was a bit surprised it didn't work, because I got the idea from docs. I found someone posting about the online version to realise that can be used - happy with that.
But would be great if it works offline, I am happy to give the port a go if you can point me to the source, or fire up a dedicated webservice. I know about the option to do this within confluence but I do not have the option to install the diagrams.net plugin at the moment. thank you

**Comment by davidjgraph** [comment]
What about using app.diagrams.net to convert the diagrams and copy the result over?

**Comment by vincentgerris** [comment]
hi,that it what I did as a workaround. this ticket was to have it in the app, so one can do it without internet or when the site is down.

**Comment by davidjgraph** [comment]
Yeah, unfortunately, the effort of adding non JS code to electron is high, as is the security risk and maintenance load. Even if someone added it, we don't want to take on the second two issues for a free app.

Our uptime for app.diagrams.net is available at [http://stats.pingdom.com/i6zi2vdl2t6b/697170/history](http://stats.pingdom.com/i6zi2vdl2t6b/697170/history). The online version stays up. Offline, OK, that one we can't solve, I'm afraid.

**Comment by vincentgerris** [comment]
I see the code is open source: https://github.com/jgraph/drawio.git . I will take a look, thanks.
