### ISSUE TITLE
关于字体的问题

### ISSUE THREAD

**Issue by SherlockCodeHolmes** [jgraph/drawio-desktop#689]
我发现在线版的字体大小最小为12，而windows桌面版则无此限制，这导致我从windows复制到在线版时出现错误

**Comment by mararad** [comment]
Hi,

I google translated this hopefully correctly:
"I found that the minimum font size of the online version is 12, but the windows desktop version has no such limitation, which caused me to get an error when copying from windows to the online version"

Both online and desktop versions support reducing font size below 12 pt by using up/down arrows. 
Could you provide us with the additional details? What seems to be the issue?

Regards,
