### ISSUE TITLE
The user having problem to download draw.io-arm64-14.9.6.dmg

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio-desktop#692]
"Is there a download for mac ARM 11.5.2? I tried downloading here https://github.com/jgraph/drawio-desktop/releases/tag/v14.9.6

![image](https://user-images.githubusercontent.com/44292306/132196205-e68463a1-8531-4e8f-8ce6-ec371a143b56.png)

but it doesn't allow me to install it

![image (d035e678-e548-4f61-80db-88c3d4ac8a74)](https://user-images.githubusercontent.com/44292306/132196232-52e57169-f057-4c73-a2c1-6ccd209e440c.png)

Asked in https://drawio.atlassian.net/browse/DND-218

**Comment by davidjgraph** [comment]
Sounds system specifc, maybe security permission.
