### ISSUE TITLE
LaTeX export as svg doesn't work with another theme

### ISSUE THREAD

**Issue by VadVergasov** [jgraph/drawio-desktop#693]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When you try to export the diagram as SVG with LaTeX text and changing your theme in export it will be exported without transformation, text will be the raw text element.

**To Reproduce**
1. Go to the app.
2. Create a diagram using LaTeX.
3. File -> Export As -> SVG...
4. Change Theme to different -> Export -> Save
5. See the $$ signs.

**Expected behavior**
Export should be the same as export from the site.

**Screenshots**
### Export from the site.
![image](https://user-images.githubusercontent.com/25568118/132227812-3eb59258-d5d8-4405-ac96-488a864d1c79.png)
### Export from the app.
![image](https://user-images.githubusercontent.com/25568118/132227923-d2a85dc7-c8e4-4506-bd39-f6cf63aa1211.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.9.6

**Desktop (please complete the following information):**
 - Windows 10x64 Home

**Comment by mararad** [comment]
Hi,

You listed "File -> Export As -> SVG" and then "Change Theme to different -> Export -> Save" 

How did you change a theme exactly? Did you go to Extras > theme or you changed some settings in the Export window?

Thanks,

**Comment by VadVergasov** [comment]
I'm using dark theme in app, but I'm unchecking Dark Theme in export options.

**Comment by mararad** [comment]
Thanks. I added your issue to https://github.com/jgraph/drawio-desktop/issues/515 so you can comment and track.

The issue related to exporting from dark theme is already open so it is good to have all under on roof.

**Comment by llvs** [comment]
To me, SVG export from the app also doesn't render the formula but has the LaTeX code in the boxes. Tested on a fresh install of v15.2.7 on Win10. I have never used any dark theme or checked such boxes on SVG export, just kept the default.
