### ISSUE TITLE
list item fill overlaps list border 14.9.6 .. 15.1.3

### ISSUE THREAD

**Issue by ll3141** [jgraph/drawio-desktop#695]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
activated fill of an list item overlaps the list border

**To Reproduce**
1. place a new list shape
2. select one of the default list items
3. check the "Fill" checkbox on the Style tab of the format panel (maybe select a color different from white to better see the effect)
4. list item background oberlaps list border

**Expected behavior**
list border should overlap list item background

**Screenshots**
![list item fill](https://user-images.githubusercontent.com/87464784/132458540-c9ace709-1e02-4e21-ab62-4ae70b98e9ac.png)

in the following screenshot I've faked the desired outcome by drawing lines over the list borders
![image](https://user-images.githubusercontent.com/87464784/132459554-41147943-9141-402d-9ed9-a49b7dd9392a.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version [e.g. 14.9.6]

**Desktop (please complete the following information):**
 - OS: windows 10 pro (10.0.19042 Build 19042)

**Comment by davidjgraph** [comment]
Could you re-test in 15.1.3 please?

**Comment by ll3141** [comment]
same behavoir with 15.1.3

**Comment by davidjgraph** [comment]
Please provide an example diagram that demonstrates this problem.

**Comment by ll3141** [comment]
here is an example file.
[ListItemBackgroundOverlapsListBorder.zip](https://github.com/jgraph/drawio-desktop/files/7648026/ListItemBackgroundOverlapsListBorder.zip)

Same reproduction receipt as above
This now is with 15.8.7
![image](https://user-images.githubusercontent.com/87464784/144573921-d95688a7-5fea-41c8-b872-ef66cf98592e.png)

Also I see a regression vs the screenshots from 14.9.6 and 15.1.3
![image](https://user-images.githubusercontent.com/87464784/144574229-0af4e2a5-6451-4d8a-85fa-ff84020aac80.png)
should I report this as a separate ticket?
