### ISSUE TITLE
Blank display on Wayland (Plasma desktop), window contents do not redraw themselves 

### ISSUE THREAD

**Issue by etna** [jgraph/drawio-desktop#698]
Hi, if I run drawio with the following arguments:

_--enable-features=UseOzonePlatform,UseSkiaRenderer --ozone-platform=wayland --user-data-dir=/custom/profile/directory --ignore-gpu-blocklist --enable-gpu-rasterization --use-gl=egl --disable-gpu --high-dpi-support=1 --force-device-scale-factor=1.8_

drawio will launch a window but its contents will never redraw. It starts out as a blank window and I have to keep resizing the window for the contents to reload and redraw. Which makes it completely unusable.

Does not happen if drawio is launched under Xwayland, or if _--disable-gpu_ is removed.

Will appreciate it if someone can help address this as --disable-gpu is automatically activated for systems using Nvidia cards and the Nouveau driver.

Thanks.

EDIT: I am using Debian 11, and the version of drawio I am using is 14.9.6, downloaded directly off this repository.

**Comment by davidjgraph** [comment]
It's possible we're not passing on Electron parameters. Does updating to 15.1.3 help?

**Comment by etna** [comment]
No joy with v15.1.3, unfortunately. Still facing the same issue: drawio launches a Wayland window but the contents are all empty until I resize the window. And the contents will also never refresh and redraw regardless of how I interact with it, unless I keep resizing the window.

**Comment by davidjgraph** [comment]
Try 15.2.5...
