### ISSUE TITLE
How to use a plugin in Desktop version of draw.io?

### ISSUE THREAD

**Issue by Zaijo** [jgraph/drawio-desktop#7]
Creating a diagram online (with a plugin) works well, also opening it works well, but when trying to create elements using a plugin, it doesn't offer the `Extras -> Plugins` menu.

How do I use a plugin locally?

**Comment by lzrski** [comment]
Hey! Just wanted to say thank you for Draw.io and that having plugins in the Electron app would be very cool.

We are using Draw.io for diagramming database schema (using SQL plugin) and keep diagrams in Git repository (as SVG+XML). GitHub integration works, but only for GitHub, is a little bit cumbersome and requires extensive permissions. Working with a desktop app and local filesystem would be preferable for us.

I understand that this may be technically challenging and not at the top of your priority list. If there is any workaround (maybe building from sources with a plugin code somewhere in the tree?) I would greatly appreciate hints.

**Comment by alderg** [comment]
We'll add plugins in the next release of the desktop version.

**Comment by nickball-granta** [comment]
Would be great if this could also work from a local URI (for true offline mode, eg on a plane), but I can't seem to make that work.

**Comment by tobiashochguertel** [comment]
@nickball-granta I use a local webserver on my laptop to serve the plugin. Quick and Easy via MAMP Pro.

![image](https://user-images.githubusercontent.com/3332669/41102696-bdcaa534-6a67-11e8-9a2a-b4a85961d348.png)

![image](https://user-images.githubusercontent.com/3332669/41102708-c3366eae-6a67-11e8-8f18-9c24eeb59d53.png)

![image](https://user-images.githubusercontent.com/3332669/41102717-c69026e4-6a67-11e8-9772-d17fd308c929.png)

![image](https://user-images.githubusercontent.com/3332669/41102718-c9e6d310-6a67-11e8-8055-057aa1d49a1a.png)

**Comment by NickABoen** [comment]
Apologies for bumping this as it's a bit old, but thought I'd chime in as I just dealt with this with what I think is a simpler work around that was convenient for me. 

A potentially more generic solution to this is to spin up a [simple HTTP server with python](https://vgmoose.com/blog/how-to-host-a-file-locally-4370481922/). This can be done by navigating to whatever folder has the plugin files you want to host. Instructions are in the link but to summarize 

With python 2 this is:

> `python -m SimpleHTTPServer`

With python 3 this is:

> `python -m http.server`

Which should spin up a local server on port 8000 by default (can be configured of course) with it's root pointing to the directory it ran from. Then to add the plugin you simply add it with the link 

> `http://localhost:8000/<path from server root to file>`

Like

> `http//localhost:8000/plugins/test_plugin.js`

And that's it. Provided that python is already installed (which it will be on unix/linux systems but easy to install on Windows) it's a quick one-liner with no special configuration.
 
I'm not sure how robust this is for larger plugin libraries, but it worked for my single file case on Windows at least for both desktop and browser versions.
