### ISSUE TITLE
add dark scrollbar feature

### ISSUE THREAD

**Issue by hasan-4** [jgraph/drawio-desktop#701]
![ou](https://i.ibb.co/WVB2wRK/Issue-scrollbar.png)

### Info
drawio version: 15.1.3
OS version: Kubuntu 20.04
theme: dark

### Summary
scrollbar is not dark in dark  theme

### Feature/Issue Details
add dark scrollbar feature\
if not possible, at-least add ability to customize the scrollbar using CSS\
again, if not possible, then please remove the light scrollbar in dark mode (in dark theme).

\
\
Thank you

**Comment by mararad** [comment]
Thanks for the report. It'll be fixed in the next release.

Regards,

**Comment by hasan-4** [comment]
![fixed-scrollbar](https://i.ibb.co/Lnx8SDD/fixed-scrollbar.png)


Info
drawio version: 15.2.7
OS version: Kubuntu 20.04
theme: dark


## Thanks for fixing it very quickly
