### ISSUE TITLE
Review of electron security recommendations

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio-desktop#703]
https://www.electronjs.org/docs/tutorial/security

-     Only load secure content
-     Disable the Node.js integration in all renderers that display remote content
-     Enable context isolation in all renderers that display remote content
-     Enable sandboxing
-     Use ses.setPermissionRequestHandler() in all sessions that load remote content
-     Do not disable webSecurity
-     Define a Content-Security-Policy and use restrictive rules (i.e. script-src 'self')
-     Do not set allowRunningInsecureContent to true
-     Do not enable experimental features
-     Do not use enableBlinkFeatures
-     <webview>: Do not use allowpopups
-     <webview>: Verify options and params
-     Disable or limit navigation
-     Disable or limit creation of new windows
-     Do not use openExternal with untrusted content
-     Use a current version of Electron

**Comment by m-mohamedin** [comment]
Done
