### ISSUE TITLE
Actual hashes don't match YAML for 15.2.7

### ISSUE THREAD

**Issue by luckman212** [jgraph/drawio-desktop#705]
Repeat of #425 
Happening again for release 15.2.7

e.g. from **[latest-mac.yml](https://github.com/jgraph/drawio-desktop/releases/download/v15.2.7/latest-mac.yml)**:

```
  - url: draw.io-arm64-15.2.7.dmg
    sha512: XjHQ3Swuze3T1IPf8jqPyZ7I/TarGgDEMXtcj4r4feLb4VJil/ewGFoD/gwjDxVGmkdlDtzdWt8QIn/JwAjCPQ==
    size: 123781680
```

**Actual:**

```
$ openssl dgst -sha512 -binary draw.io-arm64-15.2.7.dmg | base64
koaQ2Dea3cetTi+HiGYe7eFAz6doObnk4Hs5UrrFtJmEMDSLYlACOG2ZWbILTaX4q282w47an4oew74ZksYCeg==

$ stat -f%z draw.io-arm64-15.2.7.dmg
123781656
```

**Comment by davidjgraph** [comment]
Should be fixed. Looks like a race condition on build.

**Comment by luckman212** [comment]
@davidjgraph Yes, working now, thanks! Sorry to nitpick but I work in security and these things matter for me.

**Comment by davidjgraph** [comment]
Sure, that's why they are there. We are investigating what's going on.
