### ISSUE TITLE
File picker fails on open, save, and export

### ISSUE THREAD

**Issue by wwitzke** [jgraph/drawio-desktop#706]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I attempt to open, save, or export a file using drawio-desktop, the file picker fails to open. When I have started the application from the command line, I see the following:
`[5036:0915/171552.752134:ERROR:browser_main_loop.cc(269)] Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed
`
In every case, I see the file picker briefly, but it disappears. Note that the file picker does not open under the main drawio window, it either fails to open or to stay open.

**To Reproduce**
1. Start drawio (preferably from the command line)
2. Go to File > Open

Or:
1. Start drawio
2. Add an element to the drawing
3. Go to File > Save As...

**Expected behavior**
The file picker opens, I am able to select a file and open it, or the file picker opens, I am able to name/rename the drawing and save it.

**draw.io version (In the Help->About menu of the draw.io editor):**

- 5.2.7

**Desktop (please complete the following information):**
 - OS: xubuntu 20.04.3

**Additional context**
I updated today. This did not happen in the previous version of drawio I was using (14.9.6)

**Comment by alishir** [comment]
I have the same problem on Debian 11.0 with drawio 15.2.7.

**Comment by aszswaz** [comment]
I have the same problem on manjaro linux, even the window does not flash.
I guess the reason is electron, or the Chromium version embedded in electron is too old. This log indicates that the error comes from the GTK framework used by the embedded Chromium. The old GTK and the latest X11 have compatibility issues.
The browser I use is Chromium, which is the latest version, and it runs well on my computer.
Lovely developers, it’s time to update electron.

**Comment by davidjgraph** [comment]
5.2.7 is Electron 14, what is it you're suggesting to update to?

**Comment by aszswaz** [comment]
> 5.2.7 is Electron 14, what is it you're suggesting to update to?

Okay, I think I should go to the electron side to check it out.

**Comment by wwitzke** [comment]
If what @aszswaz is saying is true, wouldn't that mean that older versions of drawio-desktop would also be having this problem? I don't have any trouble getting the file picker windows to open in version 14.9.6. Do older versions of drawio-desktop use a newer version of the GTK framework (for some reason)?

**Comment by wwitzke** [comment]
I also just tried version 15.1.3 and 15.2.5. The problem does not appear in 15.1.3, but does in 15.2.5.

**Comment by keypey** [comment]
I have the same problem on Debian 10.0 with drawio 15.2.7.
Version 15.1.3 works fine.

**Comment by aszswaz** [comment]
> If what @aszswaz is saying is true, wouldn't that mean that older versions of drawio-desktop would also be having this problem? I don't have any trouble getting the file picker windows to open in version 14.9.6. Do older versions of drawio-desktop use a newer version of the GTK framework (for some reason)?

This is just my guess, in fact I found that this may not be a problem with the old version.  Instead, it may be caused by the new version of eletron.  My other application, typora, based on eletron, also has a bug that cannot drag files, which has never appeared in previous versions.

**Comment by ferrolho** [comment]
Hi! I am using Ubuntu 20.04.3 and I also have this issue on versions `15.2.5`--`15.2.7`. Version `15.1.3` is the most recent release where this is not a problem.

**Comment by Nimelrian** [comment]
Chiming in, Manjaro with i3 as WM, draw.io version 15.2.7.

**Comment by davidjgraph** [comment]
Thanks for all the feedback. It's an upstream issue on Electron, we'll build on new releases as they come out on stable.

**Comment by jethrogb** [comment]
What's the upstream ticket?

**Comment by chicolucio** [comment]
Same problem on Linux Mint 19.3 using version 15.2.7

*edit: works normally downgrading to 15.1.3*

**Comment by argenos** [comment]
Same issue on Ubuntu 18.04 with v15.2.7. Do we know which is the upstream issue that needs to be tracked? It would help manage expectations on the ETA for this fix, since we're waiting for an upstream fix to make it to stable (which in my experience can take some time).

**Comment by davidjgraph** [comment]
We believe it's https://github.com/electron/electron/pull/30927, which is fixed. Our release candidates are built, if anyone wants to test a specific build, let me know which.

**Comment by ferrolho** [comment]
I can test the Linux DEB file. Where can I find it?

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio-desktop/releases/download/v15.3.5/drawio-amd64-15.3.5.deb

**Comment by ferrolho** [comment]
Unfortunately, the issue is still present.

**Comment by yurayko** [comment]
(Debian 11, drawio 15.3.5) Run from terminal. After click 'File -> Open' I see message on terminal:
`14041:0927/161434.457553:ERROR:browser_main_loop.cc(269)] Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed`

**Comment by nurgasemetey** [comment]
Same for (Linux Mint 20.2, drawio 15.3.5, AppImage)

```
[698488:0927/174047.536924:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
17:40:47.574 › Checking for update
17:40:48.467 › Update for version 15.3.5 is not available (latest version: 15.3.5, downgrade is disallowed).
[698450:0927/174059.055590:ERROR:browser_main_loop.cc(269)] Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed
[698450:0927/174102.972435:ERROR:browser_main_loop.cc(269)] Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed
```

**Comment by neonoxd** [comment]
Fedora 34, 15.3.5-beta, the issue is still present
`[590022:0928/173942.262107:ERROR:browser_main_loop.cc(269)] Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed
`

**Comment by davidjgraph** [comment]
We've done a 15.3.7. This reverts to Electron 14, but I suspect it have the same problem.

If it does, we'll remove all Linux releases after 15.1.3, so people don't update beyond that. We'll try to work out what is happening, in the meantime.

**Comment by jethrogb** [comment]
Just tested on Ubuntu 20.04, issue remains on 15.3.7

**Comment by davidjgraph** [comment]
Thanks for checking, we'll pull the incorrect releases now. Please all revert to 15.1.3, thanks for your patience.

**Comment by davidjgraph** [comment]
https://github.com/electron/electron/issues/31152 looks like the correct upstream. Please vote for the issue (thumbs up the original post).

**Comment by davidjgraph** [comment]
We reverted to Electron 13.4.0 in 15.3.8 to avoid this issue.
