### ISSUE TITLE
Export as PDF Pages n to n exports all pages

### ISSUE THREAD

**Issue by teivarodiere** [jgraph/drawio-desktop#707]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Appreciation**
Hello, First time poster. This product is fantastic so thank you.

**Describe the bug**
My document contains several Pages (Tabs), and on each page, there is one or more diagrams.

Say I want to export Pages (tabs) 2 and 3 only to a PDF, the export function seem to export all pages (tabs) of the document. 

I use 'Tab' since a tab can contain many pages when exporting. I have 1 diagram to export per Page (tab).

**To Reproduce**
1. Create a new document with 4 tabs
2. Generate a diagram in each tab
3. Each tab with 1 page with a diagram in it
4. Go to 'File -> Export As -> PDF'
5. When the PDF Wizard window, select Radio button 'Pages'
6. Enter 2 to 3
7. Leave everything else as
'Crop' unselected
'Grid' unselected
'Include a copy of my diagram' selected or unselected, that makes no difference

2. Click on the 'Export' button
3. When prompted to save, select a location to save the output file
4. Click on Save
5. Review the document, and it contains all 4 pages 

**NOTE***
Further to my message earlier, it appears that one must be on the same page to export that Page (tab) only to export PFD.

If I clicked on Page 2 (tab 2), and hit file -> Export As -> PDF, and select pages 3 of 3, then then all of the pages of the draw IO document is exported to PDF.
However if I clicked on Page 3 (tab 3), and and hit file -> Export As -> PDF, and select pages 3 of 3, it would only export page 3 (tab3) to PDF.

**Expected behavior**
The expected behavior should be that only pages(tab) 2 and 3 should be exported.

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net 15.2.7

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.5.2 ( it was an issue prior to 11.5.2)

**Additional context**
None

**Comment by mararad** [comment]
Hi,

Could you tell me if File > Print > Pages 2 to 3 > OK > Print to PDF/Save as PDF help as a workaround?

Thanks,

**Comment by bt-tech-dd** [comment]
This bug is still present in 15.3.8.

**Comment by teivarodiere** [comment]
> Hi,
> 
> Could you tell me if File > Print > Pages 2 to 3 > OK > Print to PDF/Save as PDF help as a workaround?
> 
> Thanks,

Hi Mararad, apologies for the lateness of this reply.

The work around ( File > Print > Pages 2 to 3 > OK > Print to PDF/Save as PDF ) exports the correct pages, BUT, the output PDF are in Portrait Mode despite the diagrams being in Landscape. So the correct pages export but the formatting isn't maintained.

Hope that helps narrowing it down.

Tried this with 15.3.5 on 11.6

I tried updating to the latest version a couple of days ago, but that version freezes when navigating between Tabs. So i reinstalled 15.3.5.

**Comment by bt-tech-dd** [comment]
This issue is still present in 19.0.3.
The workaround suggested is not acceptable because when printing there is an issue with scaling. Even when setting the scaling at 100% the print option will still reduce the scaling. See my attached files for the tests I did.
01 is exporting as PDF
02 is printing as PDF
[scale_test_01.pdf](https://github.com/jgraph/drawio-desktop/files/9020222/scale_test_01.pdf)
[scale_test_02.pdf](https://github.com/jgraph/drawio-desktop/files/9020224/scale_test_02.pdf)

**Comment by edschreibman** [comment]
This issue is still present in 20.3.0.

**Comment by harrandt** [comment]
Saw it in version 16, seems to be gone in 21.6.1
