### ISSUE TITLE
"App threw an error during load" following README Developing instructions

### ISSUE THREAD

**Issue by humphd** [jgraph/drawio-desktop#709]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I'm trying to build and run the app locally, but it's crashing on startup

**To Reproduce**

I followed the instructions in the README under https://github.com/jgraph/drawio-desktop#developing, and then did:

```
$ npm start

> draw.io@15.2.7 start /Users/humphd/repos/drawio-desktop
> electron ./drawio/src/main/webapp

App threw an error during load
Error: @electron/remote >= 2.x is required for Electron >= 14. See https://github.com/electron/remote/blob/main/docs/migration-2.md for migration instructions.
    at Object.initialize (/Users/humphd/repos/drawio-desktop/drawio/src/main/webapp/node_modules/@electron/remote/dist/src/main/server.js:342:15)
    at Object.<anonymous> (/Users/humphd/repos/drawio-desktop/drawio/src/main/webapp/electron.js:20:34)
    at Module._compile (internal/modules/cjs/loader.js:1083:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1113:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Module._load (internal/modules/cjs/loader.js:781:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at loadApplicationPackage (/Users/humphd/repos/drawio-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:110:16)
    at Object.<anonymous> (/Users/humphd/repos/drawio-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:222:9)
    at Module._compile (internal/modules/cjs/loader.js:1083:30)
```

**Expected behavior**

Likely there's a version or other setup issue somehow, but following the installation instructions in the README lands me here, so I'm not sure what to change.  Any tips would be appreciated.

**draw.io version (In the Help->About menu of the draw.io editor):**

- drawio-desktop: `dev` branch, 3968b9999b442aa35e348ab2c02efe1eec250063
- draw.io version: v15.2.7 (4a4a2ed0c9905a5cb680076f7e369cebfe7ea235)

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2

**Comment by davidjgraph** [comment]
Were you working of a previous version before? If yes, did you update the dependencies?

**Comment by humphd** [comment]
No, first time I've cloned/built.

**Comment by humphd** [comment]
Digging in a little, it looks like it's installed electron `14.0.1`:

```
version {
  node: '14.17.0',
  v8: '9.3.345.16-electron.0',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '89',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1',
  icu: '69.1',
  unicode: '13.0',
  electron: '14.0.1',
  chrome: '93.0.4577.63'
}
```

From https://www.npmjs.com/package/@electron/remote I see:

> Note: In electron >= 14.0.0, you must use the new enable API to enable the remote module for each desired WebContents separately: require("@electron/remote/main").enable(webContents).

It looks like https://github.com/jgraph/drawio-desktop/commit/fcf6577ec1021766063050ddaf95bcf5e5b76ab9 is what broke me, updating to the parent commit (f86094df1bfac01be8dc7d411a5003f6f05c8982) fixes it (i.e., I can run without crashing).

Based on where I'm crashing, it looks like the migration to 14 requires more work? From `drawio/src/main/webapp/node_modules/@electron/remote/dist/src/main/server.js`:

```js
function initialize() {
    if (initialized)
        throw new Error('@electron/remote has already been initialized');
    console.log('version', process.versions)
    if (Number(process.versions.electron.split('.')[0]) >= 14)
        throw new Error('@electron/remote >= 2.x is required for Electron >= 14. See https://github.com/electron/remote/blob/main/docs/migration-2.md for migration instructions.');
```

**Comment by davidjgraph** [comment]
Actually, it's npm start in the root desktop directory, the instructions aren't clear. Is that the problem?

**Comment by humphd** [comment]
I'm running `npm start` in the root directory, yes.

**Comment by davidjgraph** [comment]
Afraid I don't know, then. HEAD works for me both in debug and that's the version in production.

**Comment by humphd** [comment]
I suspect the issue is that you're using `^1.2.1` of [@electron/remote](https://github.com/electron/remote), and it's now automatically installing the patched version `1.2.2`(from 2 days ago), which specifically includes this new code to throw on Electron versions `>= 14`.  The code in 1.2.1 doesn't do it.

https://github.com/electron/remote/commit/ee2725fd1c015178ff20df0ce73c97d70013d84f

```
[humphd /tmp/drawio-desktop (dev)]$ npm list electron
draw.io@15.2.7 /private/tmp/drawio-desktop
└── electron@14.0.1

[humphd /tmp/drawio-desktop (dev)]$ npm list @electron/remote
draw.io@15.2.7 /private/tmp/drawio-desktop
└── @electron/remote@1.2.2

[humphd /tmp/drawio-desktop (dev)]$ cd drawio/src/main/webapp

[humphd /tmp/drawio-desktop/drawio/src/main/webapp ((v15.2.7))]$ npm list @electron/remote
draw.io@15.1.2 /private/tmp/drawio-desktop/drawio/src/main/webapp
└── @electron/remote@1.2.2

[humphd /tmp/drawio-desktop/drawio/src/main/webapp ((v15.2.7))]$ npm list electron
draw.io@15.1.2 /private/tmp/drawio-desktop/drawio/src/main/webapp
└── electron@14.0.1
```

**Comment by davidjgraph** [comment]
OK, yes, good point. Not sure that's exactly semver to make the change on 1.2.2...

**Comment by davidjgraph** [comment]
This is now fixed.
