### ISSUE TITLE
Switch to built-in Electron PDF export

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio-desktop#71]
https://electronjs.org/docs/api/web-contents#contentsprinttopdfoptions-callback
https://dev.to/sathish/converting-an-electron-view-content-to-pdf-caa
https://medium.com/@ishwar.rimal/generating-pdf-with-electron-js-31b59ac93249

**Comment by jkaiser-ioki** [comment]
Is there any progress on this? We would love to use the desktop version in our company, but the fact that rasterisation is still done remotely severely impedes the certification process on our end. (Which is a shame, since draw.io is otherwise a tremendously useful app).

**Comment by ashrafteleb** [comment]
Fixed, will be available in next release
