### ISSUE TITLE
laggy menu redraw

### ISSUE THREAD

**Issue by lvmm** [jgraph/drawio-desktop#711]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When mouse pointer moves from one menu item to another selection bar is not removed immediately creating a trailing shadow

**To Reproduce**
1. Open menu
2. Start moving mouse pointer over it
3. Selection bar trails over several menu items

**Expected behavior**
Selection bar is removed from one item at the same time it is drawn over the other one, there should be no trail.

**Screenshots**
Trailing selection bar created when mouse pointer is moved rapidly over menu.
![draw-io-menu-lag](https://user-images.githubusercontent.com/11752339/133746885-c11c7642-9767-4769-b46f-b3d1442c2e8f.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.2.7

**Desktop (please complete the following information):**
 - OS: windows 10

**Comment by mararad** [comment]
Hi,

I couldn't reproduce this using Win 10 and 15.2.7 
drawio version was installed from here: https://github.com/jgraph/drawio-desktop/releases (Window installer)

Did you use this link to install the app?

https://user-images.githubusercontent.com/44292306/133766371-18c2b70e-b52c-4571-94b9-c7de7104a866.mp4

Regards,

**Comment by lvmm** [comment]
> I couldn't reproduce this using Win 10 and 15.2.7

Here is a screenshot from your own video where this issue is clearly visible:
![shot0001](https://user-images.githubusercontent.com/11752339/133773890-7314c0e9-42ca-4306-9f79-66a167fbc342.png)

**Comment by davidjgraph** [comment]
@lvmm  That's not the same thing. In real time the user doesn't notice this. Can you show a video of your case?

**Comment by lvmm** [comment]
> That's not the same thing. In real time the user doesn't notice this.

@davidjgraph, excuse me, but I created this issue and I am quite sure that this is exactly what it is about. I do notice and it is annoying. It's like working on a laptop from the nineties with display response time of half a second.
