### ISSUE TITLE
Color Picker useless due to semi-transparent white layer above everything

### ISSUE THREAD

**Issue by DanLo-peratingSystem** [jgraph/drawio-desktop#712]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Bug Description**
When it comes to get a precise hexadecimal color using **color picker**, it is not possible with embedded tool, 
1) as the color selector UI stays in place with a "grey-ish layer above all the app interface. 
2) even ignoring precedent issue, if I still use color picker and click anywhere, the red color value is set to NaN and the desired color is not set. 

The workaround using Shift + click on the color settings avoid the grey-ish interface but brings directly to the second issue : the color picker don't pick correctly any color and sets White instead. 

See screenshot bellow for illustration : I want to get the exact color from an image I copy/paste on the app for this purpose... but I can't because the color selector UI with a semi-transparent white background stays and changes the colors of what I have on my page. 

**To Reproduce**
1. Create a shape and change its background color
2. Click on '....' next to the HEX color value
3. Click on color picker...
4. See the color selector UI still here preventing from any useful color picking.

**Expected behavior**
When clicking on the color pick option, the color selector UI should disappear so that we are able to see the whole app and drawing with no semi-transparent layer over it.

* [ ] Change the pop-up of color selection when clicking on the color picker tool in order to use it correctly : make the pop-up temporarily disappear to show the rest of the app with original colors (no screen overlay), until the user clicks somewhere to pick a color onscreen. 
* [ ] Fix the color picker so that it actually picks the wanted color when used. 

**Screenshots**
<p align="center">
      <img src="https://user-images.githubusercontent.com/11614445/133887180-6e2e63db-a395-455c-ac3b-86ec356242ba.png">
</p>
_FIG. 1: How to reproduce the issue, workaround issue #1 not used._

<p align="center">
      <img src="https://user-images.githubusercontent.com/11614445/136032782-2de5bc76-9509-44fb-82cc-ed93ed9a4dd6.png">
</p>
_FIG. 2: just used the color picking tool and clicked somewhere : white selected, Red value set at NaN._

**draw.io version :**
- draw.io version 15.4.0
- On Desktop - Ubuntu 20.04

**Additional context**
On web application we don't even have the color pick option, as it opens a color selecter strangely looking like the old one from Paint.... so I guess there's still some work in progress aroung all this here to both unify desktop & webapp versions and improve this tool. :)

**Comment by mararad** [comment]
Hi,

my suggestion would be to shift+click on the color button. This should bring up the native picker with no semi-transparent background.

Regards,

**Comment by DanLo-peratingSystem** [comment]
Hi,

I just tried all this again on my computer (Ubuntu 20.04,v15.2.7) and... the color picker is in fact completely broken.

When I use it as show above, I have a NAN value for red every time, and the result is not applied.
If I trie Shift + click workaround, I get directly to "step #2" windows from image above, and here again the color picker is broken :  the  magnifying glass (c.f. step #3) displays nothing coherent with what it is pointed on, and when you click somewhere it always selects White.

(Sorry I couldn't take a screenshot while doing it, it breaks my pointer behavior and I am forced to reboot gnome after that...)

**Comment by davidjgraph** [comment]
Try 15.3.5

**Comment by DanLo-peratingSystem** [comment]
I just tried 15.4.0 : 

Shift + click gives a correct interface to use the color picker.
However, second bug is still up : the selected color is not applied. It always sets white instead. 

Editing OP to better display the issues.

**Comment by Ziesie1** [comment]
The problem with the grayish layer is still present in v21.6.5.
This is very annoying if you don't know the shift+click trick mentioned by @mararad .

**Comment by davidjgraph** [comment]
@Ziesie1 could you open as a new issue please and describe that specific problem in the new ticket?

**Comment by praksharma** [comment]
Same issue, can't pick colour, Red goes to NAN.
