### ISSUE TITLE
Changes made to original and copy of drawings

### ISSUE THREAD

**Issue by techauthoruk** [jgraph/drawio-desktop#716]
[x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
 [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Opening an existing drawing then saving with a different filename results in changes made to both drawings.

**To Reproduce**
1. Create a new drawing
2. Save with a filename (e.g 'test.drawio')
3. Edit the drawing, then save with a different filename
4. The changes occur in BOTH drawings

**Expected behavior**
The changes should only be propagated to the drawing saved with the new filename.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version - 15.2.7

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2, also Ubuntu Desktop 20.04

**Comment by m-mohamedin** [comment]
Is auto save on?

**Comment by davidjgraph** [comment]
Duplicate of #377
