### ISSUE TITLE
Application freezes after upgrade

### ISSUE THREAD

**Issue by n33lkanth** [jgraph/drawio-desktop#717]
Hi,
After upgrading the tool to version 15.3.5, draw.io desktop app screen is freezer when I am trying to load the XML file on my MacBook air, 2017 model.

**Comment by jradwan** [comment]
Same issue here: the app opens, but when I try to load an existing diagram (XML) file, it freezes with a white screen.

Release 15.3.5 (installer version) on Windows 11.

I tried the no-installer version and was able to open my diagram, but then when I saved it, it corrupted the XML and turned it into a 1k un-openable file. :(

**Comment by davidjgraph** [comment]
@n33lkanth What MacOS version are you running?

**Comment by n33lkanth** [comment]
Big Sur

**Comment by niklaslissjos** [comment]
Appears like I have run into the same problem. Updated to 15.3.5 today on a Macbook (BigSur 11.6) and continued working on a diagram, then it started giving white screens, and now the file seems destroyed. Does anyone know of a way to go back to the previous version of draw.io? Now I'm afraid of damaging more files with this version...

**Comment by davidjgraph** [comment]
You can delete the app under /Applications and install 15.2.7 from https://github.com/jgraph/drawio-desktop/releases. We'll do another release today going back to Electron 14. I'm guessing there's an issue in Electron 15. Does anyone remember the operation they were performing when it crashed?

**Comment by niklaslissjos** [comment]
Ok thanks @davidjgraph. 

I had just added new images to the scratchpad then it crashed when I was resizing and repositioning this in the diagram.

Any way of repairing the file that got damaged? Maybe a stupid question. Should have had a backup..

**Comment by mararad** [comment]
Also try to find .bkp files ~${FILENAME}.bkp

Check in e.g. in folder where you saved the diagram and/or under Windows explorer (these files might be there by default) etc.
I's worth checking if there are previous versions of the file under Properties > Previous versions (when the file is right mouse clicked)

Hopefully something will help.

**Comment by n33lkanth** [comment]
I started using the chrome extension of draw.io
It works fine.

**Comment by davidjgraph** [comment]
We don't have a Chrome Extension. What did you install?

**Comment by n33lkanth** [comment]
I reinstalled the new version, still, there is the same problem. As a
workaround, I am using chrome extension.

**Comment by jradwan** [comment]
> Does anyone remember the operation they were performing when it crashed?

For me it's just trying to open an existing diagram. I get the "Loading" spinner animation for about 3 seconds and then the window just goes white and stops responding to clicks so I have to kill it from Task Manager (this is on Windows).

![image](https://user-images.githubusercontent.com/11047158/135102870-a7ca5f19-ebcd-4647-b411-be0863b3df4a.png)

For my corrupted diagram (when I saved using the no-installer version), I had to restore from backup (no previous version in Windows or .bkp file).

**Comment by n33lkanth** [comment]
For me it won't even show the spinner after selecting the xml file. I am
not performing any operation apart from trying to open the xml file.

**Comment by davidjgraph** [comment]
We've released 15.3.7 to address this. That reverts to Electron 14. In the meantime we'll investigate why Electron 15 might be causing this problem.

**Comment by davidjgraph** [comment]
We're going to stick to Electron 13.x for the time being. I'll close this up, but we'll certainly have a pre-release and testing effort on Windows before trying an Electron 15 release.
