### ISSUE TITLE
Opening via command line parameter on Windows 10 and detach

### ISSUE THREAD

**Issue by cinderblock** [jgraph/drawio-desktop#72]
This may be a duplicate of #4 but I don't believe it is as that part seems to be working for me.

## Setup

If I open the Windows command prompt, I can launch draw.io with a parameter of the file I want to open and it opens as expected. The cmd prompt even prompts me for the next command to run.

Interestingly, after it does launch, I get an stdout output from draw.io: `createWindow {}`.
> ```batch
> Microsoft Windows [Version 10.0.17134.407]
> (c) 2018 Microsoft Corporation. All rights reserved.
> 
> C:\Users\Cameron>"C:\Program Files\draw.io\draw.io.exe"
> 
> C:\Users\Cameron>
> createWindow {}
> 
> ```

Notice I only hit "enter" once. Now my prompt is at the beginning of and empty line.

## What is broken

If I type "exit", the command prompt window does not close. The command prompt no longer accepts input.

If I close draw.io, the command prompt window closes (if it has been told to `exit`).

If I close the cmd window, draw.io is forcefully closed.

## Possibly related breakage

If I right click on the file I want to edit, select "Open with...", "Choose another app", "More apps", "Look for another app on this PC", and finally select `draw.io.exe` nothing happens. I don't even see a quick short lived launch of the .exe in the task manager.

Now that Windows knows I have tried to open `.png` files with draw.io, draw.io is presented as options in the various "Open with..." sub menus. Intriguingly, those all work as expected. It is only when you dive deep into the "Open with..." menu tree that draw.io fails to launch.

EDIT: It seems that this "possibly related breakage" is more of a Windows issue as ~15 minutes later, draw.io is finally opening up. Like something slowed down the startup a crazy amount.

**Comment by ashrafteleb** [comment]
This behavior occurs when on Windows and using GUI mode of draw.io. The command prompt re-appear after draw.io is started, but draw.io process is still associated with the command prompt process. So, closing the command prompt will close draw.io also.

This is why exit did not exit the command prompt since the child process (draw.io) is still active. Also, closing the command prompt forces the child process (draw.io) to close.

**Comment by cinderblock** [comment]
Other software can be started in a command window via cli and don't create a sub-process of the command window keeping them un-linked. See for instance VS Code. Can this behavior be replicated?

Why close this issue? Is this not something that you want to support? Were someone to make a patch that does this, might you accept it?

**Comment by ashrafteleb** [comment]
draw.io Desktop is based on Electron, thus we are controlled by its behavior.

We couldn't find a solution for this issue (we are happy to apply a patch to fix this issue of course)

For example, this article (https://binary-studio.com/2017/09/21/implementing-cli-electron-apps/) suggests using `start /wait draw.io.exe` which will force the prompt to wait until draw.io finished.

**Comment by cinderblock** [comment]
VS Code is also based on electron.

Note, I don't want the command prompt to wait for draw.io to close. I want it to exit quickly and allow me to close cmd.exe without killing draw.io

**Comment by davidjgraph** [comment]
Happy to review a PR.
