### ISSUE TITLE
reset toolbar

### ISSUE THREAD

**Issue by hasan-4** [jgraph/drawio-desktop#723]
**Describe the bug**
![toolbar](https://i.ibb.co/5W906BM/Screenshot.png)
toolbar is resetting every time when a document is reopened

**To Reproduce**
1. open a drawio file
2. <br> ![toolbar_new](https://i.ibb.co/PQKywVh/toolbar-new.png) <br> make some changes in the toolbar
3. close drawio
4. reopen the same drawio file

**Expected behavior**
The toolbar should not be reset whenever a file is opened/reopend

**Environment**
drawio version: 15.3.5
OS: Kubuntu 20.04
theme: dark

Thank you

**Comment by davidjgraph** [comment]
The only thing you might persist is the zoom, and it doesn't make sense to persist it per file or per app.
