### ISSUE TITLE
15.3.7 stable release is missing the "windows-no-installer" version

### ISSUE THREAD

**Issue by TE-PongsakornUchupala** [jgraph/drawio-desktop#725]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
15.3.7 stable release is missing the "windows-no-installer" version.

**To Reproduce**
1. Go to 'https://github.com/jgraph/drawio-desktop/releases/tag/v15.3.7'
2. Click on 'Assets'
3. Notice that 'draw.io-15.3.7-windows-no-installer.exe' is missing.

**Expected behavior**
'draw.io-15.3.7-windows-no-installer.exe' is available to download.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.3.7

**Desktop (please complete the following information):**
- OS: Windows (64 bits)

**Additional context**

**Comment by davidjgraph** [comment]
Fixed, thanks for report.
