### ISSUE TITLE
Release 15.3.7 lacks Debian package

### ISSUE THREAD

**Issue by languitar** [jgraph/drawio-desktop#726]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The latest release 15.3.7 lacks a Debian package

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
Read the release notes.

**Comment by languitar** [comment]
Where exactly in

> * Reverts from Electron 15 to Electron 14. There were stability problem we suspect are caused by 15.
> * We are fixing Linux releases at 15.1.3 build for now. There have been problems with the native picker since 15.1.3.
> * Updates to diagrams.net core 15.3.7. All changes from 15.1.4 to 15.3.7, inclusive, are added in this build.

Would I find the relevant information?

**Comment by davidjgraph** [comment]
"We are fixing Linux releases at 15.1.3 build for now. There have been problems with the native picker since 15.1.3."

**Comment by languitar** [comment]
Sorry, that's pretty hard to understand. That means the DEB in 15.1.3 will replaced with a working version at some point in time not related to the Github release? Or how does that work?
