### ISSUE TITLE
FontSize always sets to 12, Draw.io Desktop Windows

### ISSUE THREAD

**Issue by prabaljainn** [jgraph/drawio-desktop#727]
everytime i make a new text widget i have to resize it to 18 by myself , can't change the default size of fonts

**Comment by alderg** [comment]
What UI theme are you using (if not sure, please provide a screenshot)?

**Comment by prabaljainn** [comment]
here is the video stating the problem


https://user-images.githubusercontent.com/62801988/135420556-38d7c83d-b821-465f-9ade-27cf5c6b9db9.mp4

**Comment by alderg** [comment]
Select the cell, not the text, then change the font size.

**Comment by prabaljainn** [comment]
Sorry, but i want my text size to be 20ptr every time i create a text widget

**Comment by alderg** [comment]
This is currently only supported if the cell is selected, not if text inside the cell is selected.

**Comment by alderg** [comment]
This will be fixed in the next release.

**Comment by prabaljainn** [comment]
Hey I don't know what i did but somehow my default text size in 18 now. **don't know how**

**But thanks for this beautiful amazing Piece of work i do teachings from this wonderful Application Dude loved it Thanks :Friendlykiss **

**Comment by prabaljainn** [comment]
Should i upload a Video How i sorted my Problem?

**Comment by davidjgraph** [comment]
No need, we released a fix, that's why it's now working.
