### ISSUE TITLE
CLI freezes when converting a .drawio file the second time

### ISSUE THREAD

**Issue by KGergo88** [jgraph/drawio-desktop#728]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. Have a .drawio file in a folder
2. Run the convert it into an svg file with the command:
`<YOUR_DRAWIO_DESKTOP_PATH>/draw.io.exe --recursive --check --export --format svg --transparent .`
3. Conversion succeeds the .svg files are there
4. Run the same command the second time
5. The app freezes.

**Expected behavior**
The expected behaviour would be that I get a warning that the output file already exists and it is skipped if `--check` is used, or gets overwritten otherwise.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 15.3.5

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CLI Tool: Git Bash - Git for Windows v2.31.1

**Comment by KGergo88** [comment]
@davidjgraph thank you for the quick reply.

I have upgraded to 15.3.8 today. The issue is still present the same way as before.

Another bug was found when starting the program from Windows CMD:
When printing the version with `draw.io.exe --version` the version string is printed but the control does not go back to the CMD. I mean it seems that the string is printed correctly but then the program keeps running.
This is not present with Git Bash on Windows.

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
