### ISSUE TITLE
draw.io.9.3.1.zip is corrupt

### ISSUE THREAD

**Issue by Nejat** [jgraph/drawio-desktop#73]
I can not open the zip file with either WinRAR 5.60 64 bit & 7Zip 18.05 x64 running on Windows 10 Pro w/latest updates applied. I also downloaded it several times to make sure it was not corrupted during the download.

**Comment by davidjgraph** [comment]
Which zip, https://github.com/jgraph/drawio-desktop/releases/download/v9.3.1/draw.io-9.3.1.zip or the source zip? They uncompress fine for me on a mac. Have you another computer you can test?

**Comment by Nejat** [comment]
I was trying to unzip the one you listed, not the source zip.

I tried it on another Windows machine and also Windows' Linux subsystem, Debian and get similar messages regarding additional data past payload

**Comment by alderg** [comment]
Works for me on macOS and Windows.

**Comment by davidjgraph** [comment]
We've had a bunch of the team try to open it, all worked. Given yours is the only report and nobody here can recreate, we'll have to close.

I can only assume there's a proxy somewhere between you and the Github server that is either altering the download, or has cached a corrupt version.
