### ISSUE TITLE
Please provide the windows controls (minimize, resize, close) in the interface 

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio-desktop#733]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When we work with multiple apps at the same time, we have to arrange their windows so that we can see them simultaneously. This requires us to resize/minimize the window. Also, when we have finished work, we need to close the Drawio window. But the interface does not have the traditional Windows controls  (minimize, resize, close).

**Describe the solution you'd like**
Please provide the three traditional windows controls (minimize, resize, close) at the top-right corner.
In addition, another control may be provided to pin the window at top.

**Comment by davidjgraph** [comment]
Declined
