### ISSUE TITLE
The Extra>plugs dialog does not show which plugins are installed; allows double installation

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio-desktop#734]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The **Plugs** dialog (menu: Extra>plugs) has two problems:
1. It does not show which plugins are installed (all plugins look the same in the list, whether installed or not)
2. It allows us to install any given plugin any number of times!

**To Reproduce**
1. Select the Extras>Plugin menu option.
2. Look at the list. The display does not show which plugins are already installed, and which are not installed.
3. Add some plugins. 
4. When you have not pressed the **Apply** button, the display does not change which plugins are selected for installation.
5. The dialog allows you to install the same plugin any number of times. <br> The installed pulgins are not grayed out.
6. If you press **Apply**, and repeat Step#1, the whole list appears.

**Expected behavior**
1. The list must show which of the plugins are installed, and which are not.
2. The dialog must not allow us to install the same plugin multiple times.

**draw.io version (In the Help->About menu of the draw.io editor):**

Desktop version 15.4.0

**Desktop (please complete the following information):**
 - OS: Win 10 Home, 64 bits

**Comment by m-mohamedin** [comment]
Will be added to next release
Thanks for the report
