### ISSUE TITLE
KaTeX Issue: Changing font size does not resize KaTeX superscripts or subscripts.

### ISSUE THREAD

**Issue by Zushauque** [jgraph/drawio-desktop#735]
![image](https://user-images.githubusercontent.com/62147947/135930275-abf44cca-2563-4345-89d9-24e31a96cc9e.png)
![image](https://user-images.githubusercontent.com/62147947/135930319-67574e99-ee97-4c1c-9086-96f8857d7fcc.png)

Title explains it: KaTeX superscripts and subscripts are not affected by changes in font.

**Comment by davidjgraph** [comment]
Closing for not agreeing to code of conduct.
