### ISSUE TITLE
KaTeX Issue: KaTeX does not support \tiny in \text{}

### ISSUE THREAD

**Issue by Zushauque** [jgraph/drawio-desktop#736]
I usually use this when writing \begin{aligned} \end{aligned} in KaTeX. I'd write text of varying sizes within the KaTeX environment, e.g., I use \tiny in \underbrace to explain equations or techniques used in a derivation. I use it in KaTeX on Notion, but it is certainly missing from Draw.io.

**Comment by davidjgraph** [comment]
Closing for not agreeing to code of conduct.
