### ISSUE TITLE
Command line options to select layers to export

### ISSUE THREAD

**Issue by ebousse** [jgraph/drawio-desktop#737]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

When writing a report or when making slides, I often need to include different variants of the same diagram (eg. a "simple" one, then a more "complex" one). To store all variants of a diagram in the same draw.io file, I tend to use the _layers_ feature, where each layer adds new elements to a "base" diagram (eg. enabling a layer can make a "simple" diagram into a "complex" one).

However, when lots of layers are stored in the same draw.io file, it quickly become tedious to manually disable/enable layers and make an export (eg. as PNG or PDF) for each variant. For instance, I have a figure where I have 7 layers, with one new variant per enabled layer, thus 7 variants to export.

**Describe the solution you'd like**

Adding a simple command line option to select which layers must be enabled for a given export would allow people in my case to write a small script to automatically export all required variants of a given draw.io figure containing layers. 

For instance, `drawio diagram.drawio --export --format png --layers 1,3,7 --output diagram137.png`  could create the file `diagram137.png` which would only contain the content of layers 1,3 and 7 of `diagram.drawio`.

**Describe alternatives you've considered**
An "advanced" menu in the GUI could maybe give the possibility to select layers to export, but that would still make it tedious to export each required variant one by one.

**Additional context**
Here is an animation showing what I mean by "multiple variants" of a figure, where each enabled layer gives a new and more complex variant:

![layers](https://user-images.githubusercontent.com/5868014/136059558-22a39469-a218-4ea7-a8e0-bbbc110df61b.gif)

**Comment by ebousse** [comment]
Sorry I just found out this is a duplicate of #405, I must have made a typo when I initially searched in the tracker.

**Comment by davidjgraph** [comment]
Worth pasting the additional content into 405.
