### ISSUE TITLE
Add note to readme about winget installation method

### ISSUE THREAD

**Issue by DOliana** [jgraph/drawio-desktop#738]
Since it seems that the package for winget was created by someone maintaining this repository it would be nice to mention in the readme that it is an official package. This would add trust to using winget as source instead of wondering whether it is an official package or some malware.

**Comment by davidjgraph** [comment]
We don't publish anything on winget

**Comment by DOliana** [comment]
@davidjgraph interesting - then you might want to check if someone is abusing your name. There is a package called diagrams.net and the maintainer is named JGraph: https://winget.run/pkg/JGraph.

**Comment by davidjgraph** [comment]
We don't have the resources to chase every such case.
