### ISSUE TITLE
Excessively distant new connected shapes in Tree Layouts, or Tree Containers, that are within another Container

### ISSUE THREAD

**Issue by Kookiness** [jgraph/drawio-desktop#740]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Clicking an arrow to add a shape to a Tree Layout or Tree Container that's already within a container causes the non-tree container to resize vertically to an unnecessarily huge size. Depending on which shape you extended the arrow from and in which direction, this may also create an arrow that extends unnecessarily far from its source.

**To Reproduce**
1. Create new blank project
2. Create a new "Container" shape
3. Drag and drop a new Tree Container into the existing Container shape
4. Mouse over the "Parent" shape of the Tree Container
5. Click on one of the faint arrows that appear, to create an arrow leading to a new shape
6. The first Container you created will become vertically huge, and if you clicked any arrow EXCEPT the downward arrow, then the new arrow you created will lead far down and to the left

**Expected behavior**
I expected the new shape to be created nearby using a short arrow, and the largest container not to be unnecessarily resized.

**Screenshots**
![image](https://user-images.githubusercontent.com/75261412/136563326-568becd0-7cc3-48cb-b826-10ce00ceeff6.png)
![image](https://user-images.githubusercontent.com/75261412/136563442-ba67e4f6-d193-4d0a-b847-23ca36279d9b.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 15.3.8

**Desktop (please complete the following information):**
 - OS: Win10 x64

**Additional context**
If, for step 3, you use a Vertical or Horizontal Tree Layout instead of a Tree Container, the problem with the hugely-extending container still occurs, but the hugely-extended arrow does not. With the Tree Container, For some reason, the arrow only extends hugely if you click the Parent's left, up, or right arrows, but not down, however the largest container still gets hugely resized. It's difficult to summarise all observations in words, so I recommend trying extending the arrows in various directions from various Tree shapes that are within some kind of Container.

**Comment by mararad** [comment]
Hi,

I am not able to reproduce this using the latest version. Could you upgrade the app to the latest 15.4.0 and test again?
If this doesn't help, please attach a video showing all the steps and the result.

Regards,

**Comment by Kookiness** [comment]
Yes, certainly. I have upgraded to 15.4.0, and then recorded the following video:

https://user-images.githubusercontent.com/75261412/137550572-e0cb6b6a-bd19-4533-9d26-2a1e6d3e1825.mp4

**Comment by Kookiness** [comment]
Here is another video, showing that the location of the outer container (seemingly, how much it is offset from the origin of the document) effects the direction and distance in which the child shape will be positioned:

https://user-images.githubusercontent.com/75261412/137552113-24b4909b-979c-4f6b-a486-9bb185f212f9.mp4

**Comment by mararad** [comment]
Thanks. I managed to reproduce this and it looks like this behaviour depends on diagram position on the page. 
If you move diagram to the top of the page (or close to the top) does it help?

Regards,

**Comment by Kookiness** [comment]
Yes, if the outer container is positioned near the page's origin (0,0), the problem decreases.

However, the farther the container is positioned away from the origin, the farther the next created arrow will extend unnecessarily in that direction.

It's as if the outer container causes the tree to become confused about how far to offset its new shapes, and multiplies their offset based on their distance from the approximate location of 0,0 on the page.
