### ISSUE TITLE
How to close image compression?

### ISSUE THREAD

**Issue by huanqwer** [jgraph/drawio-desktop#741]
I just click the checkbox to remember to ajust the image, but I don't know how to close this feature, the image after compressing is not clear, I need your help to close image compression feature, and my version is 15.4.0.
![WeChat Image_20211012111909](https://user-images.githubusercontent.com/50089997/136885655-47205ed2-10e9-4670-83e4-2a448a2e1dec.png)

**Comment by mararad** [comment]
Hi,

In diagrams.net online this can be easily solved by clearing local storage but on desktop it is difficult to bring the dialogue back. You can try to uninstall/reinstall the app. This might help.

What operating system do you use? On Win just add DRAWIO_ENV=dev and on Mac it is
export DRAWIO_ENV=dev
/Applications/draw.io.app/Contents/MacOS/draw.io

Regards,

**Comment by wangsqly0407** [comment]
问题：draw.io选择实际尺寸，并且记住此设置之后，再次把大图片复制进来之后，不再显示实际尺寸和调整大小的选项，直接出错（图片太大）。
![image](https://user-images.githubusercontent.com/19249636/142959565-5bc51c23-6b9c-4dad-898b-fdb327dde50b.png)
![image](https://user-images.githubusercontent.com/19249636/142959572-7ead5def-b460-42cb-b6bf-f78d75e1f457.png)

解决方案：
![image](https://user-images.githubusercontent.com/19249636/142959388-62d548e1-c910-4856-8c8a-d4bd90bf13d4.png)
![image](https://user-images.githubusercontent.com/19249636/142959403-168b59ee-d81c-4e1c-911a-6e8e41f32a69.png)
![image](https://user-images.githubusercontent.com/19249636/142959449-5caf5743-915e-41b6-88c5-4f14240739f7.png)

Everything's all right.
