### ISSUE TITLE
Exporting PNG with Include a copy of my diagram should not include all tabs

### ISSUE THREAD

**Issue by andyvanosdale** [jgraph/drawio-desktop#744]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When I have a drawio file with multiple tabs and I export a PNG and choose the "Include a copy of my diagram" option, it includes a copy of all the tabs.

**Describe the solution you'd like**
I would like for the option to only include a copy of the specific diagram or tab I'm exporting rather than all the tabs. There could be a secondary option to say include all tabs/diagrams in the project or even select the specific ones.

As an aside, it's a bit odd to see the Diagram size option yet the Include a copy of my diagram includes all the tabs.

**Describe alternatives you've considered**
I could choose to Copy as Image from the Edit menu, but that sets the alpha background by default, making it difficult to share that in places where dark mode is enabled and the diagram now has a dark background.

**Additional context**
None

**Comment by sathishkumar294** [comment]
I have the same need. I have one file on a single topic, but several tab to provide several views of architecture. When I export to PNG and attach it to presentations or store in drive it will be very helpful for future collaborators to have a copy of the diagram from which I generated the image, but not the entire file with all the tabs. It would be very unhelpful. So an option during the export to specify whether to include the entire file or only the selected tab or the selection would be helpful.
