### ISSUE TITLE
Visio Viewer and DrawIO: difference in rendering thick arrows

### ISSUE THREAD

**Issue by hacksterous** [jgraph/drawio-desktop#749]
Hi,

I drew a diagram in DrawIO and exported to the Visio .vsdx format and there's a difference in the way
thick arrows with fill are rendered in DrawIO and MS Visio Viewer. Visio Viewer renders thick arrows as
thin.

DrawIO

![inDrawIO](https://user-images.githubusercontent.com/16697108/138870699-96f246ea-0ce6-4ff6-80ac-d9ea06f85845.png)

MS Visio Viewer
![inVisio](https://user-images.githubusercontent.com/16697108/138871028-ed6cc0f2-d77a-4934-8bf9-8f23a48817b5.png)

Let me know if you need more information.

**Comment by mararad** [comment]
Hi,

Could you attach the draw.io diagram here?
Export as vsdx is beta so there is a possibility this can't be improved at the moment.

Regards,

**Comment by hacksterous** [comment]
Attached (gzipped).

[test.drawio.gz](https://github.com/jgraph/drawio-desktop/files/7427754/test.drawio.gz)

**Comment by mararad** [comment]
Thanks. 

Reproduced in desktop 15.4.0 and online 15.6.0 in Chrome and Win 10
