### ISSUE TITLE
auto export

### ISSUE THREAD

**Issue by janscholten** [jgraph/drawio-desktop#75]
Hi,

First, thanks for this great work, it is such an improvement for all schematics I need to print.

I'd like to suggest a feature request to improve its workflow with latex (at least for me):
Using the desktop app, I typically save the xml or html file, and then export as a pdf to the graphics folder of a latex project. I then typically need to go back and forth from latex to draw.io a couple of times to finetune font sizes etc. I feel like most of this time is spent by going through the export menu:  Diagram>Export As>PDF>Crop>Export>Wait..>Navigate to folder>Yes, Replace existing.
These steps are always the same for me, and it would be great if they were remembered by means of a 'Repeat last export'  hotkey that automatically puts the updated pdf in place.

Best regards,

Jan

**Comment by ashrafteleb** [comment]
The next release will support command line export. So, as a workaround, you can now use draw.io in a script to automate the export process.

**Comment by davidjgraph** [comment]
Added in https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5
