### ISSUE TITLE
Conflicting packages in Debian Bullseye (11) due to libappindicator

### ISSUE THREAD

**Issue by sajkbflksadbfkasdjf** [jgraph/drawio-desktop#752]
**Describe the bug**
The .deb depends on libappindicator but support for it has been removed in upstream Debian 
[https://wiki.debian.org/Ayatana/IndicatorsTransition](https://wiki.debian.org/Ayatana/IndicatorsTransition)
[https://lists.debian.org/debian-devel/2018/03/msg00506.html](https://lists.debian.org/debian-devel/2018/03/msg00506.html)

1. Install package in Debian 11 or testing
2. Can't install due to broken dependencies

**draw.io version :**
- 15.4.0
**Desktop (please complete the following information):**
 - OS: Debian 11

**Comment by 532910** [comment]
a dup of https://github.com/jgraph/drawio-desktop/issues/504
