### ISSUE TITLE
Allow PDF export with transparent background

### ISSUE THREAD

**Issue by jiuntian** [jgraph/drawio-desktop#753]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am unable to export as PDF with transparent background. This is possible in draw.io online but not desktop version. Tested on 15.4.0 macOS. To reproduce: File -> Export As -> PDF.
![drawio_desktop](https://user-images.githubusercontent.com/13869695/139539179-5f496276-d073-4d36-afdd-dd63f947a31b.jpeg)

**Describe the solution you'd like**
Having option to export PDF with transparent background like the online version of draw.io would be great
![drawio_online](https://user-images.githubusercontent.com/13869695/139539197-4be70218-7b6e-4ed6-aa59-c2b12d57a48d.jpeg)
.

**Comment by mararad** [comment]
Hi,

If you click File > Export as > Advanced > PDF you should see Background: Transparent ticked by default.
Click Export button.

Does this help?

Regards,

**Comment by jiuntian** [comment]
Hi, 
No, this does not help, it does not allow to export `only selection`.

**Comment by davidjgraph** [comment]
Declined

**Comment by b10n** [comment]
I also experience this. Ticking `transparent` in the advanced export options or using the `--transparent` command-line switch both yield a PDF with a white background.

**Comment by JurijsNazarovs** [comment]
I faced the same issue, and I am curious why is that like this? Why online version can export pdf with transparent background, while offline version on Mac cannot export selected region with transparent. Going in "advanced" does not allow to save only selected region. Also, even like this background is still white and not transparent.

**Comment by baldassarreFe** [comment]
I ran into the same issue, it's so annoying that the command line has a `--transparent` option but the output PDF is actually not transparent!

I needed to automate the drawio -> pdf export, so here's what I do.
I noticed that there is always a group `g12` that contains a single large white rectangle as the background.
So I use the inkscape command line to remove it after the export.
```
drawio figure.drawio --transparent --crop --export --output figure.pdf
inkscape figure.pdf --select=g12 --actions=delete --export-filename=figure.pdf
```

It would be great if `--transparent` would work.

**Comment by iDoka** [comment]
@baldassarreFe the same issue for me.
I have using identical pipeline with inkscape: `.drawio -> .pdf`
and the white background is the bigest problem which I can't manage.

`--transparent` option works only for png output, can't wait to support `--transparent` option for PDF outputs.
