### ISSUE TITLE
Easier way for adding text

### ISSUE THREAD

**Issue by BummiYo** [jgraph/drawio-desktop#754]
* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

- **Is your feature request related to a problem? Please describe.**

Hi, I use drawio as a brainstorm tool in my workflow, I hope there is an easier way to quickly type down a bunch of textbox.
I think it is a little tedious and unintuitive...

            Adding text methods that I know: 
            [1] "ctrl+shift+x" + double click to highlight "text" to text
            [2] double click + click "text" + double click to highlight "text" to text

- **Describe the solution you'd like**

**[1] A more neatly "duplicate"** 
I think the "Ctrl+Enter",  which is the "duplicate", is a convenient and fast way to add a bunch of items.
But I hope they could be duplicated and piled more neatly at least not blocking the previous text. 
  
  ![Clipboard - 2021-11-01 13 39 59](https://user-images.githubusercontent.com/93506039/139626914-8d9f8861-94b1-4065-9917-b2189ecaa58c.png)

**[2] A quick access for (insert>Advanced>text)**
I found this tool meets my need as well but the access path is a little bulky...
  ![Clipboard - 2021-11-01 12 58 04](https://user-images.githubusercontent.com/93506039/139625999-388ca9d1-3e7e-4c02-b7b0-a3a06d582ac9.png)

**Comment by mararad** [comment]
Hi,

Which draw.io version are you using? Can be seen under Help menu. The latest is 15.4.0 https://github.com/jgraph/drawio-desktop/releases

You could click text "shape" in General library on the left and just start typing. Does this help?

![text](https://user-images.githubusercontent.com/44292306/139662553-b70c2ab2-a28b-485c-b66f-3de1515036d7.JPG)
Regards,
