### ISSUE TITLE
Problems using mind maps and tables

### ISSUE THREAD

**Issue by SONGjiemo** [jgraph/drawio-desktop#755]
**Is your feature request related to a problem? Please describe.**
1、When moving Central Idea, Branch and Topic did not follow the movement.
2、The Branch and Topic of Mindmap graphics have no shortcut shapes that are transformed
3、Can't find table insert and delete

**Describe the solution you'd like**
1、When moving Central Idea, Branch and Topic hope to follow the move.
![VeryCapture_20211101170736](https://user-images.githubusercontent.com/46627639/139772420-03d6e433-3b90-4a49-ac7b-72f1aeb2c107.gif)

2、I hope that Branch and Topic can transform shapes and fast shape solutions like many Mindmap tools.
As shown below:
![image](https://user-images.githubusercontent.com/46627639/139772206-51e22cef-35a1-42ed-a84d-a21ab9853afe.png)

3、Provide table insertion and deletion
![Uploading VeryCapture_20211102094331.gif…]()

**Describe alternatives you've considered**
Not yet

**Comment by SONGjiemo** [comment]
Picture supplement on point 3
3、Provide table insertion and deletion
![VeryCapture_20211102094331](https://user-images.githubusercontent.com/46627639/139773553-c953d28e-2d2f-4c13-86ca-45b9a903a5dd.gif)

**Comment by mararad** [comment]
Hi,

We improved table shapes and you might want to try them as described here: https://www.diagrams.net/blog/tables

Regards,

**Comment by davidjgraph** [comment]
1. Please agree to the code of conduct and fill in as much of the issue template as possible, do not simply delete it
2. Please add one issue per issue. We cannot track multiple issues within a single issue.

**Comment by SONGjiemo** [comment]
> 1. 请同意行为准则并尽可能多地填写问题模板，不要简单地删除它
> 2. 请为每个问题添加一个问题。我们无法在一个问题中跟踪多个问题。

Okay, I will pay attention.
 I want to ask. I often use mind maps in my work. I made a corresponding design for him, hoping to consider or use it as a solution to optimize mind maps. I look forward to answering my thoughts about you.
Links I have sent:  #756  [Link](https://github.com/jgraph/drawio-desktop/issues/756#issue-1041855627)

**Comment by SONGjiemo** [comment]
> 你好，
> 
> 我们改进了表格形状，您可能想按照此处所述尝试使用它们：[https](https://www.diagrams.net/blog/tables) : [//www.diagrams.net/blog/tables](https://www.diagrams.net/blog/tables)
> 
> 问候，

Thank you very much, it helped me a lot
