### ISSUE TITLE
Auto add connection points if not available

### ISSUE THREAD

**Issue by macux** [jgraph/drawio-desktop#761]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Some shapes found via the search (e.g. Azure icons) do not have connection points so in order to use them with snapping to lines/arrows I often add an invisible shape around the icon. This is a pain to do and often requires multiple send to back/front to see the hidden shape's connection points. Whilst you can kind of connect to/from these sorts of shapes dragging them around doesn't keep the connections and connectors often don't snap consistently.

**Describe the solution you'd like**
Could the system detect if no connection points are available when a shape is added and if so auto add a hidden shape of the same size with connection points? This could be optional.

**Describe alternatives you've considered**
See above for how I currently deal with this.

**Additional context**
N/a

**Comment by mararad** [comment]
Hi, 

this article might help you: https://www.diagrams.net/doc/faq/shape-connection-points-customise

Regards,

**Comment by macux** [comment]
Thanks @mararad I'll take a look, although I still think this would be a useful feature and definitely quicker (for me at least).

**Comment by davidjgraph** [comment]
It's possible to connect anywhere by holding the alt key when you drop.

**Comment by macux** [comment]
Seems this should also help here although not tried it yet: https://twitter.com/drawio/status/1486799110967599104
