### ISSUE TITLE
The first letter of Pinyin is often entered automatically, resulting in typing twice every time.

### ISSUE THREAD

**Issue by fntp** [jgraph/drawio-desktop#766]
When one control connects to another control, there will be an exception in the middle route, which is written in Chinese. The first letter of Pinyin is often entered automatically, resulting in typing twice every time.
![image](https://user-images.githubusercontent.com/46984923/141028461-262f1368-1eb6-4684-aec0-abb9e7d4ae16.png)
I originally wanted to type "过期", but as a result,it became "g怄气" ,I lost a phonetic alphabet, which was really uncomfortable. I thought the author prompted me to update the software to solve the problem at 14.x, but it hasn't been solved yet!

**Comment by m-mohamedin** [comment]
@fntp Can you please share with us a video showing the issue. Also, a detailed letter sequence to reproduce.

I tried to reproduce on Mac with Pinyin keyboard layout and it works (but I don't know the correct letter sequence to reproduce)
