### ISSUE TITLE
macOS Monterey and drawio-desktop file picker is not opening when exporting a diagram

### ISSUE THREAD

**Issue by anksos** [jgraph/drawio-desktop#767]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
After updating to macOS Monterey version 12.0.1 when I try to export a diagram/file the file picker is not opening to select the destination where I want to export the file and the name.

**To Reproduce**
1. Open a diagram
2. File -> Export as -> .png 
3. Click export

**Expected behavior**
Expectation is to open the file picker and give you the possibility to select destination and name of the outcome file.

**Screenshots**
N/A

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v15.4.0

**Desktop (please complete the following information):**
 - macOS Monterey version 12.0.1

**Additional context**
This was not happening to previous version of MacOS, this happened exactly after updating to Monterey.

**Comment by davidjgraph** [comment]
ARM or intel?

**Comment by anksos** [comment]
> ARM or intel?

Intel (MacBook Pro (16-inch, 2019))

**Comment by davidjgraph** [comment]
Could you test again with 15.7.3 please.

**Comment by anksos** [comment]
> Could you test again with 15.7.3 please.

Yup, seems that is resolved now in the new released you did guys with 15.7.3. Awesome!

**Comment by anksos** [comment]
@davidjgraph after some time this issue happened again yesterday. During export is not working, it was working fine after I updated to the latest 15.7.3. Anything I can check locally so I can provide you some troubleshooting data? 

Thanks!
