### ISSUE TITLE
Performance Regression (Frame Rate, Input Latency, Responsiveness)

### ISSUE THREAD

**Issue by Ben-Fields** [jgraph/drawio-desktop#770]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When upgrading to `15.7.3` from `12.6.5`, I noticed significantly decreased responsiveness in the desktop application. This includes lower frame rates and increased input latency. Besides the experience, the reduced input rate may affect productivity.

I manually uninstalled and re-installed ~10 different versions, and version `14.1.5` seems to be the last unaffected version. I expected a sudden regression but found the effect to be incremental between versions since `14.1.5`. (Though my testing was qualitative only).

**To Reproduce**
1. Install the desktop app for a version between `14.1.5` and `15.7.3`.
2. Right-click and pan the blank canvas.
3. Observe the frame rate and synchronization between the cursor and canvas.
4. Record differences between versions.

**Expected behavior**
No performance degradation in subsequent versions.

**draw.io version:**

- draw.io version `14.4.3` (approx.) to `15.7.3`.

**Desktop:**
 - Windows Installer (64-bit)

**Additional context**
Web apps already require significant overhead, so the performance degradation causes version `15.7.3` to act as a slideshow on my recent hardware. Builds could be run and tested for performance with C.I. to detect trends, but that might not be practical.

**Comment by davidjgraph** [comment]
Is this with all diagrams or just some?
