### ISSUE TITLE
remember export as settings

### ISSUE THREAD

**Issue by lvmm** [jgraph/drawio-desktop#771]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Sometimes it is necessary to export multiple pages of a diagram as images e.g. for publication on a website. When export dialogue (file-export as-<type>) is opened it always reverts do default configuration and one has to reconfigure it every time which is time-consuming, annoying and may lead to mistakes.

**Describe the solution you'd like**
I'd like export dialogue to remember settings from the last time it was used.

**Describe alternatives you've considered**
Don't see any.

**Comment by mararad** [comment]
There is a similar thread already open: https://github.com/jgraph/drawio-desktop/issues/508 
You can add your comment there so we can have all suggestions under one roof.

**Comment by lvmm** [comment]
duplicate, closing
