### ISSUE TITLE
Window does not correctly maximize/minimize on startup

### ISSUE THREAD

**Issue by JonoMacC** [jgraph/drawio-desktop#772]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Window titlebar does not correctly resize the window without first resizing the window.

**To Reproduce**
Window does not restore down correctly:
1. Open a new window
2. Click on the 'Restore' button in the titlebar
3. The window resizes to a width of a few pixels and several pixels tall

Window does not maximize correctly:
1. Open a new window
2. Move the window over to a larger secondary display
3. Click on the 'Restore' button in the titlebar
4. No action occurs

Window does not maximize on double-click:
1. Open a new window
2. Move the window over to a larger secondary display
3. Double-click the titlebar to maximize the window
4. No action occurs

**Expected behavior**
Window does not restore down correctly:
The 'Restore' button should restore the window down to a reasonable default state.

Window does not maximize correctly:
The 'Restore' button should change state to reflect the new display. Clicking on the 'Maximize' button should maximize the window.

Window does not maximize on double-click:
Double-clicking the titlebar should maximize the window up to fill the display.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 15.7.3

**Desktop:**
 - OS: macOS
 - Browser: N/A
 - Version: 12.0.1

**Additional context**
MacBook Pro 2017. Primary display 3072x1920 @200% scaling, secondary display 5120x2880 @200% scaling.

If the window is manually resized by manipulating its edges, the 'Restore' button correctly changes state to reflect the current display. Clicking the 'Maximize' button then enables the window to fill the screen. Double-clicking the titlebar still does not function.

Issue encountered immediately upon update to draw.io 15.7.3

<img width="86" alt="Screen Shot 2021-11-11 at 4 35 37 PM" src="https://user-images.githubusercontent.com/39803935/141382361-1680f3da-9655-4530-9d04-8780b60ecd15.png">
<img width="1475" alt="Screen Shot 2021-11-11 at 4 34 11 PM" src="https://user-images.githubusercontent.com/39803935/141382379-dde27b9c-da3b-4036-ac02-93471f9abf6f.png">

**Comment by Roy150** [comment]
Not exactly the same thing, but maybe can be resolved at the same time. Every time I open the desktop application, it opens slightly smaller than maximized, and I have to manually click the maximize button. It would be great if it could remember that step, or provide a setting, so it can open maximized without extra action. Thank you!

**Comment by m-mohamedin** [comment]
@JonoMacC  We use the native title bar in Mac again, so I believe this issue is over. Let us know if you're still having it.
@Roy150 We now remember the window position and state

**Comment by manmoncang** [comment]
When you click fullscreen menu the draw.io windows dekstop version can be changed to fullscreen. Unfortunately, it cannot return to normal back. Minimum, maximum, and close buttons were gone. I couldn't find the solution. tired already. i try hold and drag the title.. but cannot move.

![image](https://github.com/jgraph/drawio-desktop/assets/10664618/8fc1b5a4-c89a-4a16-99d0-1e27c1ec9bd8)

**Comment by manmoncang** [comment]
> When you click fullscreen menu the draw.io windows dekstop version can be changed to fullscreen. Unfortunately, it cannot return to normal back. Minimum, maximum, and close buttons were gone. I couldn't find the solution. tired already. i try hold and drag the title.. but cannot move.
> 
> ![image](https://private-user-images.githubusercontent.com/10664618/304179960-8fc1b5a4-c89a-4a16-99d0-1e27c1ec9bd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjExNzIsIm5iZiI6MTcwNzc2MDg3MiwicGF0aCI6Ii8xMDY2NDYxOC8zMDQxNzk5NjAtOGZjMWI1YTQtYzg5YS00YTE2LTk5ZDAtMWUyN2MxZWM5YmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDE4MDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4Nzc4NzZkMTg4NTVlYzc4Njg1ZjlmNDAyOWFjMjE3MGNmY2E0M2RkODgyZDhjNjg0MWE2ZWZiMzU2YjExNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EaTUagsEk4_56WcwtFDAQeNb-9fQVlA_PQWAgmbLrNU)

ok solve.... hmmmm

i delete configuration file at C:\Users\<USER-NAME>\AppData\Roaming\draw.io\

**Comment by ChristianSayne** [comment]
> > When you click fullscreen menu the draw.io windows dekstop version can be changed to fullscreen. Unfortunately, it cannot return to normal back. Minimum, maximum, and close buttons were gone. I couldn't find the solution. tired already. i try hold and drag the title.. but cannot move.
> > ![image](https://private-user-images.githubusercontent.com/10664618/304179960-8fc1b5a4-c89a-4a16-99d0-1e27c1ec9bd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjExNzIsIm5iZiI6MTcwNzc2MDg3MiwicGF0aCI6Ii8xMDY2NDYxOC8zMDQxNzk5NjAtOGZjMWI1YTQtYzg5YS00YTE2LTk5ZDAtMWUyN2MxZWM5YmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDE4MDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4Nzc4NzZkMTg4NTVlYzc4Njg1ZjlmNDAyOWFjMjE3MGNmY2E0M2RkODgyZDhjNjg0MWE2ZWZiMzU2YjExNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EaTUagsEk4_56WcwtFDAQeNb-9fQVlA_PQWAgmbLrNU)
> 
> ok solve.... hmmmm
> 
> i delete configuration file at C:\Users<USER-NAME>\AppData\Roaming\draw.io\

Man thank you so much. I was so despearte searching for the reason why there is no title bar anymore :D This has to be a bug. After deleting Roaming Folder everything works. Thanks alot !!

**Comment by manmoncang** [comment]
> > > When you click fullscreen menu the draw.io windows dekstop version can be changed to fullscreen. Unfortunately, it cannot return to normal back. Minimum, maximum, and close buttons were gone. I couldn't find the solution. tired already. i try hold and drag the title.. but cannot move.
> > > ![image](https://private-user-images.githubusercontent.com/10664618/304179960-8fc1b5a4-c89a-4a16-99d0-1e27c1ec9bd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjExNzIsIm5iZiI6MTcwNzc2MDg3MiwicGF0aCI6Ii8xMDY2NDYxOC8zMDQxNzk5NjAtOGZjMWI1YTQtYzg5YS00YTE2LTk5ZDAtMWUyN2MxZWM5YmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDE4MDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4Nzc4NzZkMTg4NTVlYzc4Njg1ZjlmNDAyOWFjMjE3MGNmY2E0M2RkODgyZDhjNjg0MWE2ZWZiMzU2YjExNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EaTUagsEk4_56WcwtFDAQeNb-9fQVlA_PQWAgmbLrNU)
> > 
> > 
> > ok solve.... hmmmm
> > i delete configuration file at C:\Users\AppData\Roaming\draw.io\
> 
> Man thank you so much. I was so despearte searching for the reason why there is no title bar anymore :D This has to be a bug. After deleting Roaming Folder everything works. Thanks alot !!

Wah... Glad to hear that. All the best

**Comment by KalemaEdgar** [comment]
> > When you click fullscreen menu the draw.io windows dekstop version can be changed to fullscreen. Unfortunately, it cannot return to normal back. Minimum, maximum, and close buttons were gone. I couldn't find the solution. tired already. i try hold and drag the title.. but cannot move.
> > ![image](https://private-user-images.githubusercontent.com/10664618/304179960-8fc1b5a4-c89a-4a16-99d0-1e27c1ec9bd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjExNzIsIm5iZiI6MTcwNzc2MDg3MiwicGF0aCI6Ii8xMDY2NDYxOC8zMDQxNzk5NjAtOGZjMWI1YTQtYzg5YS00YTE2LTk5ZDAtMWUyN2MxZWM5YmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDE4MDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4Nzc4NzZkMTg4NTVlYzc4Njg1ZjlmNDAyOWFjMjE3MGNmY2E0M2RkODgyZDhjNjg0MWE2ZWZiMzU2YjExNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EaTUagsEk4_56WcwtFDAQeNb-9fQVlA_PQWAgmbLrNU)
> 
> ok solve.... hmmmm
> 
> i delete configuration file at C:\Users<USER-NAME>\AppData\Roaming\draw.io\

Thank you very much @manmoncang. This still works even on newer draw.io versions as of now July 2024.
It has disturbed me for weeks and almost gave up. I uninstalled many times, reinstalled older versions, deleted registry keys for draw.io, deleted program files folders to no avail.
