### ISSUE TITLE
Unable to drag app window on windows 11 desktop

### ISSUE THREAD

**Issue by ak-paca** [jgraph/drawio-desktop#773]
**To Reproduce**
Update to v 15.7.3
And try to drag window

**Screenshots**
![image_2021-11-12_18-10-14](https://user-images.githubusercontent.com/827452/141489036-78241c9f-340d-45a5-ab63-db1c759cac19.png)

- draw.io version 15.7.3
 - OS: [window 11]

**Comment by songql** [comment]
It's unable drag drawio application to move the window at below view:
<img width="833" src="https://user-images.githubusercontent.com/11689082/141752054-92b9aeb6-1809-4b1b-b457-41a9906281d5.png">

and can drag at below view:
<img width="820" src="https://user-images.githubusercontent.com/11689082/141750943-01ba12d7-c927-457a-8578-1d8c9926b34b.png">

but the global language button is disabled.

**Comment by davidjgraph** [comment]
Thanks, we'll look into the issue, no further reports needed.

**Comment by davidjgraph** [comment]
Suggested fix in 15.8.4
