### ISSUE TITLE
The title bar is not user friendly on Mac

### ISSUE THREAD

**Issue by Kistelekig98** [jgraph/drawio-desktop#774]
Title bar is completely opposite of the Apple human interface guidelines.

**To Reproduce**
Start the app.

**Expected behavior**
The classic red, yellow and green circles should appear on the top left corner, like in every other macOS application.
The design guidelines for the title bar:
![title-bar](https://user-images.githubusercontent.com/11194127/141500526-4f919668-1689-4860-95e7-9a3681f8d150.png)

**Screenshots**
![Képernyőfotó 2021-11-12 - 17 23 05](https://user-images.githubusercontent.com/11194127/141501333-1ea70a6d-aa88-464c-a124-6dbadbde58e8.png)

**draw.io version**
15.7.3

**Desktop:**
OS: MacOS 12.0.1 Monterey

**Additional context**
Now the app is pretty ugly because of this windows-style title bar. I love your application, and I have been using it for a long time, but this is completely unacceptable for me, as a Mac user.
Please adapt to the [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/window-anatomy/)

**Comment by WhisperSign** [comment]
The same question! How to fix this!?

**Comment by peterpk** [comment]
This situation is a result of issue #91 and I understand the rationale on other platforms. On macOS however it ends up making Draw.io.app feel "foreign" -- more like a port from some other platform than a native macOS application. 

Echoing the comments on issue #775 , there should be an option to allow this to be toggled by the user.

**Comment by stewartadam** [comment]
+1, window customization should be disabled by default on MacOS.

**Comment by m-mohamedin** [comment]
Native mac titlebar will be restored in the next release. To get rid of it, one can use mac full screen option

**Comment by davidjgraph** [comment]
Suggested fix in 15.8.4
