### ISSUE TITLE
Native window title bar missing and not following the desktop manager "look-and-feel"

### ISSUE THREAD

**Issue by dumdan** [jgraph/drawio-desktop#775]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Linux (Fedora, Mate) - The "drawio-desktop" window lost the standard title bar and desktop managed controls (double click to scroll-up, )

**To Reproduce**
1. Start the "drawio" application
2. Observe the lack of (desktop manager) window title bar in the application window.
2. Double click the title bar to have the window scroll-up - it should obey the desktop manager window behavior. 

**Expected behavior**
Proper desktop integration and to respect the look-and-feel of the desktop, ***whatever that may be!*** 

**Screenshots**

![Screenshot at 2021-11-12 18-53-46](https://user-images.githubusercontent.com/4112169/141596614-cb36460b-2930-4624-a1d0-4d281d0f8c31.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version: 15.7.3 - desktop

**Desktop (please complete the following information):**
 - OS: Fedora 34, CentOS 8.3
 - Desktop: Mate 1.22.2

**Additional context**
I do understand this contradicts other issues (#091). However, the seamless window is not always desirable.
We ***must** have the option to **maintain the native window frame!*** (even  VSCode has that !)

**Comment by lvmm** [comment]
Same on windows, hugely annoying. 15.4.0 is the last version which worked properly.

**Comment by lvmm** [comment]
In addition, contrast window border is missing in 15.7.3, as a result when draw.io windows overlap they blend together. Consider two screenshots of two draw.io windows, first 15.4.0, second - 15.7.3 (hmmm, never noticed that draw.io title bar changes height when window is maximised). Please restore window border as well as title bar.
![2draw-io-15-4-0](https://user-images.githubusercontent.com/11752339/141744538-da02e9fe-085a-4c94-a211-2ec4b5f1bf3f.png)
![2draw-io-15-7-3](https://user-images.githubusercontent.com/11752339/141744542-de50dcb6-6e0e-4047-b07d-6f13231227e2.png)
