### ISSUE TITLE
Smart connection line

### ISSUE THREAD

**Issue by SONGjiemo** [jgraph/drawio-desktop#777]
* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
In drawing a flowchart, I always modify the process from time to time. Among them are mainly new processes that will be inserted into the process

**Describe the solution you'd like**
When inserting new images in the process, I hope to insert them intelligently. Below I have a plan to watch.

**Describe alternatives you've considered**
Not yet

**Additional context**
Please watch my envisioned plan
![VeryCapture_20211114200810](https://user-images.githubusercontent.com/46627639/141680664-6ba22c41-879c-48ce-a81d-b0400ce64274.gif)

**Comment by davidjgraph** [comment]
Declined
