### ISSUE TITLE
[Linux]draw.io-x86_64-9.3.1.AppImage can't work well on the Debian 9.6!

### ISSUE THREAD

**Issue by jiangqii** [jgraph/drawio-desktop#78]
Hi!My os is debian 9.6.The kernel is 4.9.130.Desktop environment is gnome.
When I run the command "./draw.io-x86_64-9.3.1.AppImage"，follow this：

![default](https://user-images.githubusercontent.com/45223669/50258696-c2d79280-043b-11e9-9ab5-64c9212c1ccf.png)
and the window of drawio is black,display is irregular.Like this:

![default](https://user-images.githubusercontent.com/45223669/50258841-72146980-043c-11e9-88d4-796d14016c98.png)

When I click "X" to close,the terminal will disappear "Window on close 0",AppImage nothing to do,still black and can't close it!Closed by pressing "Ctrl+C" twice.

But draw.io-x86_64-8.8.0.AppImage is OK on my computer!

**Comment by davidjgraph** [comment]
9.3.1 uses Electron 3.0.6, it might be a problem with that, so I'm not going to install this specific debian to investigate. Does the .deb work?

**Comment by jiangqii** [comment]
Same as before！
Like this:
![default](https://user-images.githubusercontent.com/45223669/50284022-a74ba680-0492-11e9-8a88-242b2bba55cf.png)

**Comment by haimoz** [comment]
I had the same issue with AppImage (9.3.1) on Debian 9.6.  The .deb works for me.

**Comment by davidjgraph** [comment]
Why would you use the AppImage over the .deb on Debian?

**Comment by haimoz** [comment]
Just curious to give it a spin, since Debian is supposed to support AppImage based on [AppImage wiki](https://github.com/AppImage/AppImageKit/wiki/Similar-projects#linux-distribution-support).

**Comment by maurom** [comment]
Same here. Tried draw.io 9.3.1 both in .deb (draw.io-amd64-9.3.1.deb) and flatpak image. I only get a blank (black) window. The previous version (8.8.0) works ok, though.
I'm currently running Cinnamon on Debian 9.9 (stretch) 64 bits.

**Comment by davidjgraph** [comment]
Try https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5

**Comment by maurom** [comment]
Thanks David. I've just tried v10.7.5 on Debian 9.9, Draw.io runs ok and I haven't found any problems in my first tests. Should work on Debian 9.6 too.

**Comment by davidjgraph** [comment]
Thanks for the feedback, I'll mark as closed until someone says otherwise.
