### ISSUE TITLE
export to PDF doesn't work

### ISSUE THREAD

**Issue by lvmm** [jgraph/drawio-desktop#780]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
export to PDF doesn't work and leaves 'Saving...' twirly thing

**To Reproduce**
Steps to reproduce the behaviour:
1. go to file-export as-PDF
2. press Export: 'Saving...' twirly thing appears and stays on forever, PDF is not created. The program is not frozen, I can continue using it, but the twirly thing keeps on twirling over everything. As far as I can tell changing export settings has no effect.

**Expected behaviour**
Prompt for a file name and export to PDF

*draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 15.7.3

**Desktop (please complete the following information):**
 - OS: windows 10

**Additional context**
15.4.0 has the same issue

**Comment by lvmm** [comment]
update: it happens when windows print spooler service is not running.

**Comment by mararad** [comment]
As a workaround does one of these help?
* File > Export as > Advanced > PDF
* File > Print > OK > Print to PDF/Save as PDF

If nothing helps, tell me the file size and attach the file if possible so it can be tested.
If I understood you well, export as PDF is working in 15.7.3 when windows print spooler service is running?

**Comment by lvmm** [comment]
As I said, it happens when windows print spooler service is not running, so the most obvious workaround is to start it. The way draw.io fails when it is not running, however, is not nice - no error messages, visual glitches...

**Comment by DynamDan** [comment]
Still failing on PDF export, the workarounds do not work either. Fails with this error in an unreachable page with address https://exp.draw.io/ImageExport4/export


This site can’t be reached
Check if there is a typo in exp.draw.io.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by davidjgraph** [comment]
Export to PDF does not reach out externally. Is this is a very old desktop install?

**Comment by DynamDan** [comment]
No, not desktop install. It's running in browser in the latest version of Chrome on Mac: Version 96.0.4664.55 (Official Build) (x86_64)

**Comment by davidjgraph** [comment]
What version do you see under help menu? What URL are you accessing this app under?

**Comment by DynamDan** [comment]
15.8.7 

I was trying to go to draw.io but it redirected to

https://app.diagrams.net/

**Comment by davidjgraph** [comment]
This is the desktop project, please file an issue on the online version https://github.com/jgraph/drawio/issues
