### ISSUE TITLE
first page is inaccessible from ... menu if it is taler than the screen height

### ISSUE THREAD

**Issue by lvmm** [jgraph/drawio-desktop#781]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If number of pages is a document is so large that ... menu becomes taller than the screen height, first page cannot be clicked.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create large number of pages (33 in my setup) so that the three dots menu to the left of the page tab bar becomes taller that the screen height and scroll bar appears in this menu.
2. Open this menu
3. When mouse hovers over the topmost item in this menu menu selection bar disappears and clicks are ignored

**Expected behavior**
Topmost item should've been accessible and clickable.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 15.7.3

**Desktop (please complete the following information):**
 - OS: windows 10

**Additional context**

**Comment by mararad** [comment]
Tested and page 1 can't be selected from page bar but not sure what disappears at your place.
As a workaround could you select Page 2 from page list as shown:
![page 2](https://user-images.githubusercontent.com/44292306/141792025-ea60c911-b06e-4e95-9b52-4e60f78af5d3.JPG)

And then select Page 1 (marked yellow) from the page bar
![page 1](https://user-images.githubusercontent.com/44292306/141792068-a3bf2b97-b13f-4109-9291-668f4acc550b.JPG)

Does this help?

**Comment by lvmm** [comment]
Yes, it is not a blocker, there are workarounds. Still, not nice. What disappears is the menu selection bar - when mouse pointer move along the menu it follows it, but disappears when mouse pointer hovers over the topmost item.

**Comment by m-mohamedin** [comment]
It will be fixed in the next release
