### ISSUE TITLE
Window titlebar is missing context menu for, e.g., moving the window to another desktop

### ISSUE THREAD

**Issue by raphendyr** [jgraph/drawio-desktop#784]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Before removing the native window title bar, I was able to use (right click) context menu to do action for the window. In KDE this includes, but is not limited to, move the window to another desktop, to another screen, move, resize and so on.

However, after removing the native window border, I'm unable to open this menu.

**To Reproduce**
1. Install drawio 15.7.3 and open it.
2. Right click on the title bar
3. No menu is opened

**Expected behavior**
When I right click, a menu is opened.

**Screenshots**
Right click is supposed to open menu like this
![image](https://user-images.githubusercontent.com/2327687/141847836-0692525b-2307-4212-95bb-8595b93d7b95.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.7.3

**Desktop (please complete the following information):**
Debian GNU/Linux bookworm/sid
KDE Frameworks 5.86.0

**Additional context**
This problem was introduced as a result of fixing #91 . I didn't spend time to find the actual commit yet.

In addition of the context menu, the title bar misbehaves with double click, which is reported in #775.

**Comment by raphendyr** [comment]
I would be fine to set an environment variable before starting the application, which specifies if native borders should be enabled or not (e.g. `enabled`, `disabled` or `auto` (selects default based on operating system)). I can then set this environment variable in the `.desktop` file, which is relatively simple for the enduser to do.

For me, returning to native borders is acceptable solution, as it also solves placement of buttons on window border and double click behaviour.

This mechanic is used to e.g. enable Wayland for Firefox and things like that.

**Comment by cachandlerdev** [comment]
+1 for making native borders an optional setting.

VSCode is a great example of this. They let users use the custom style if they want, but users also have the option to use a native feel (configurable in the program's settings) as well.

![image](https://user-images.githubusercontent.com/70250943/156696589-f9b3044c-0479-4b56-be94-c1b597aeece4.png)

**Comment by kid4git** [comment]
Apart from being a great application, it is indeed pretty annoying that it behaves so much differently than other applications on my KDE desktop. It looks totally weird without the borders and I can't use my configured actions for them, e.g. move to another desktop or just click the titlebar with the middle mouse button to move it to the background.

As there are no borders and my configured window shadows also don't apply, it doesn't stand out from other windows, so if I got a browser with a website with a white background behind it, it looks like drawio is on that website.

Please make the native titlebar configurable.

**Comment by maetthu** [comment]
> Apart from being a great application, it is indeed pretty annoying that it behaves so much differently than other applications on my KDE desktop.

Since you are using KDE, you can define a window rule to force frame and titlebar.

![Screenshot_20220831_111300](https://user-images.githubusercontent.com/1193955/187643344-c7904f1b-6022-4628-9755-0641db7fcbbc.png)

But I agree that it would be better to make this configurable without resorting to hacks.

**Comment by kid4git** [comment]
> Since you are using KDE, you can define a window rule to force frame and titlebar.

@maetthu Awesome, you are my hero! Thanks.

And if I hit that "Collapse/Expand" toggle on the top right, it looks even more like a native application.

**Comment by davidjgraph** [comment]
Could you test whether 20.7.4 improves this issue please?

**Comment by raphendyr** [comment]
@davidjgraph thanks. It's perfect now :+1: 

I close this as fixed in 20.7.4 or before.
