### ISSUE TITLE
Mermaid diagrams are unreadable in dark mode

### ISSUE THREAD

**Issue by lvmm** [jgraph/drawio-desktop#785]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Mermaid diagrams are unreadable in dark mode

**To Reproduce**
prerequisite: dark mode is on

Steps to reproduce the behaviour:
1. Go to arrange-insert-advanced-mermaid
2.  paste the following text
```
sequenceDiagram
    participant Reporting
    participant S4 as S4 Y_R2RR025_CONTRACTRECON
    Reporting->>S4: Customer
    S4->>Reporting: Agreement list
    Reporting->>S4: Agreement and date range
    S4->>Reporting: Report
```
3. click Apply
4. connectors are almost invisible

**Expected behavior**
Lines should've been white, the same colour as other connectors in dark mode

**Screenshots**
![2021-11-16 13_43_33-Untitled Diagram - diagrams net](https://user-images.githubusercontent.com/11752339/141972574-a1985398-9657-46c9-8799-2aed7a5cba7c.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.7.3

**Desktop (please complete the following information):**
 - OS: windows 10

**Comment by davidjgraph** [comment]
From a quick scan the init should be:

`mermaid.initialize({ theme: 'dark', startOnLoad: true });`

but then we risk using a less tested section of mermaid.

**Comment by m-mohamedin** [comment]
Mermaid dark theme will be used with the our dark theme in the next release

**Comment by davidjgraph** [comment]
16.0.0
