### ISSUE TITLE
fix corrupted .drawio file

### ISSUE THREAD

**Issue by ibrahemesam** [jgraph/drawio-desktop#787]
I have an important .drawio file. it seems to be corrupted. it give this error on drawio-desktop:
"Not a diagram file (error on line 1 at column 1761258: Extra content at the end of the document)"
I also tried it on the web drawio, but also does not work.
can it be fixed?
here is the file:
[Life.drawio](https://www.mediafire.com/file/i8dtwtd3v9rtfcq/Life.drawio/file)

**Comment by davidjgraph** [comment]
What is the version of the desktop (under help menu)?

**Comment by ibrahemesam** [comment]
15.7.3 AppImage on Linux Manjaro KDE

**Comment by mararad** [comment]
Hi,

Could you open the attached file? Does it help?
[user file opened.zip](https://github.com/jgraph/drawio-desktop/files/7569971/user.file.opened.zip)

**Comment by ibrahemesam** [comment]
> Hi,
> 
> Could you open the attached file? Does it help? [user file opened.zip](https://github.com/jgraph/drawio-desktop/files/7569971/user.file.opened.zip)

thanks, that is one of my diagrams but not all.
I was able to recover most of them by removing the last incomplete diagram tag < digram > </ diagram >
I lost only two diagrams: one I remember its content, but the other not
