### ISSUE TITLE
UI goes white on Importing image file

### ISSUE THREAD

**Issue by dunxd** [jgraph/drawio-desktop#790]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When Importing a png image, the draw.io window goes completely white, with no menus or controls visible.

**To Reproduce**
1. Go to Import...
2. Select a PNG file
3. Click open

**Expected behavior**
Import works

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [15.7.3]

**Desktop (please complete the following information):**
 - OS: [macos and Windows 10]

**Comment by dunxd** [comment]
I do not get the issue with JPG files

**Comment by dunxd** [comment]
When I click on Import in the web app, a window appears to ask if I want to resize or use the original size.  The images I tested with result in Too big message in the web app, and import ok when resizing (but too small!)

**Comment by davidjgraph** [comment]
I'm unable to repeat in MacOS 12, drawio 15.7.3.

**Comment by dunxd** [comment]
This is with an Intel Mac.  I am using the same images as in #789 
The issue arises with the large dimension images.  With smaller dimension images the problem doesn't arise.

**Comment by davidjgraph** [comment]
Please attach a PNG that recreates the problem.

**Comment by dunxd** [comment]
<img width="856" alt="Basement" src="https://user-images.githubusercontent.com/16608541/142659644-06e7afb7-2003-45d8-b8b3-5a835497b755.png">

**Comment by dunxd** [comment]
When I drag the image off the GitHub page to my desktop and try that version it works ok. Strange.

**Comment by oyton** [comment]
After updating to 16.0.2, when I add the first picture by dragging and selecting resize, it works. But when I add the second one and select resize, UI goes white. 
![IMG_0090](https://user-images.githubusercontent.com/3387012/147326565-74641814-f30d-4405-ab31-25d849bd8f37.JPG)
![IMG_0105](https://user-images.githubusercontent.com/3387012/147326575-139fba5c-9f00-4a5b-a3f2-0a1889990f1f.JPG)

**Comment by davidjgraph** [comment]
We're assuming this is the same issue as #853
