### ISSUE TITLE
Cant click on menu items in Atlas theme

### ISSUE THREAD

**Issue by Dariusz1989** [jgraph/drawio-desktop#798]
**Describe the bug**
Cant click on any of menu items in this theme>
![image](https://user-images.githubusercontent.com/13185728/143085168-d04640cb-03b4-4ce4-951e-2d8b03deb5b8.png)

**To Reproduce**
Changed theme to the blue thini one

**Expected behavior**
Items clickable.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10x64
No idea about versions as I cant click.

**Additional context**

**Comment by MrFuNK1** [comment]
Can confirm that the Atlas theme does not allow to click the menu buttons. All other themes do work, even the standard one after clicking the button to hide/minimize the titlebar.

**Comment by davidjgraph** [comment]
When did you install it? Did you update very recently?

**Comment by MrFuNK1** [comment]
Am using the AppImage, that did update. But I also downloaded a fresh copy.

After deleting the AppImage's cache (/home/USER/.config/draw.io) I was able to use the default theme. Switching to Atlas theme will end in menu items not clickable.

**Comment by Dariusz1989** [comment]
I downloaded it about 20 mins before posting this post. So it was brand new today's version.
draw.io-15.8.4-windows-installer

**Comment by jradwan** [comment]
I just upgraded to 15.8.4 and am having the same issue ... can't click on anything in the menu bar (running Windows 11 in case it matters).

**Comment by davidjgraph** [comment]
And everyone in thread is in atlas mode?

**Comment by Dariusz1989** [comment]
Well not any more since it does not work... but I Miss click on it anyway, I was aiming for dark :D

**Comment by pdlourenco** [comment]
Two versions ago I could not drag the window around. Last version fixed that, but only if clicked right at the edge of the top bar. This new version does not allow to click on any of the buttons except the minimize,maximize,close combo, but it does allow to drag the window by clicking anywhere in the top bar.

**Comment by davidjgraph** [comment]
We'll remove the atlas style, it shouldn't be in the menu

**Comment by davidjgraph** [comment]
To clear the configuration, go to your user folder in explorer and navigate to:

AppData\Roaming\draw.io

And delete these folders:

IndexedDB
Local Storage

**Comment by davidjgraph** [comment]
Fix in 15.8.7
