### ISSUE TITLE
Indentations disappear when pasting text 

### ISSUE THREAD

**Issue by alpha75lap** [jgraph/drawio-desktop#799]
### Preflight Checklist

* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When pasting text into a shape any indentation at the start of any paragraph within the same shape disappears.
This does not happen when you tabulate the whole paragraph, unless is a 1 line paragraph or it has indentation as well.

**To Reproduce**
1. Go to shapes and create a rectangle (bug appears on every shape I've tested).
2. Write a paragraph and add an indentation at the beginning of the first line.
3. Copy a word (or any amount of characters) and paste it anywhere inside the same shape.
4. Indentation disappears and has to be entered manually again.

**Expected behavior**
Tabulations already at the beginning of paragraphs (indentations) are expected to persist regardless any addition of text by copy-pasting, specially if the text was added in a different line of text in the shape.

**Screenshots**
![indentation](https://user-images.githubusercontent.com/94994852/143309066-65f35157-c7b9-4a56-a614-c95c83e8d3e4.PNG)

**draw.io version**

- draw.io version 15.8.4  (experienced this problem in every version I've tested)

**Desktop**
 - OS: W10

**Additional context**
While taking the screenshots for this bug I encountered a second bug that so far I don't know how to replicate: 
(In the future I plan to post about that bug too, as soon as I know how to replicate it.)
Notice I was trying to create a line with the following text "Here the pasted text: Copy pasted line of text" but couldn't put both phrases in the same line. Putting the text cursor in the beginning of the added line and pressing backspace results in the last character of the previous line to be deleted without merging the lines.

**Comment by stevesun21** [comment]
Hi, any updates on this issue? I got the same issue at MacOS with all versions I have upgraded :(

**Comment by davidjgraph** [comment]
What's the ETA on a fix for this?

**Comment by ltOgt** [comment]
In case anyone wanted to do this for pasting source code to visualize in drawio, here is a workaround:

- replace all " " spaces in your code with another inivisible char:
  - E.g.: `U+2007    Figure Space           &#8199;      " "`
- Now copy and paste, these characters are preserved
