### ISSUE TITLE
No Native Menu Support

### ISSUE THREAD

**Issue by aswinrajeev** [jgraph/drawio-desktop#8]
Native menus are to be supported at some point in time. It feels really awkward to stick with the web interface menus and shortcuts.

**Comment by bjonnh** [comment]
That or in the mean time being able to remove the current menu bar that is not really useful.

**Comment by raydeo** [comment]
Which file manages the main draw.io menu items and sub items? i.e. File, Edit, View, Arrange? I would like to limit the amount of options available in the app, as will be used by children - I do not want to overwhelm them.

**Comment by aswinrajeev** [comment]
I am trying to work on this. Have already created a bare-bone native menu that is able to communicate with the draw.io application.

**Comment by msvi** [comment]
Hello!

Electron 12 implements support for Wayland that can be enabled with the command line switches `--enable-features=UseOzonePlatform --ozone-platform=wayland`. Unfortunately, Gnome does not provide server-side decorations for Wayland windows and thus the window cannot be closed or resized with the mouse.

![Bildschirmfoto vom 2021-05-18 06-57-08](https://user-images.githubusercontent.com/6871571/118602627-3881ed00-b7b3-11eb-825b-d5d42efb5c6b.png)

There seems to be some work going on in Electron to support client-side decorations (CSD) [here](https://github.com/electron/electron/issues/11907) and [here](https://github.com/electron/electron/issues/27522). However, this will probably take some more time. In the meantime, as more distros switch to Wayland by default and HiDPI/MixedDPI setups are becoming more common, it would be good to have an option to draw some basic window decorations.

I'm not too familiar with Electron but I found this library [here](https://github.com/AlexTorresSk/custom-electron-titlebar) and a more simple approach [here](https://github.com/binaryfunt/electron-seamless-titlebar-tutorial). Maybe this could be used to at least draw close/minimize/maximize buttons and make the window resizable with the mouse?

**Comment by davidjgraph** [comment]
Menu changes implemented in 15.7.3. Please add discussions about changes either as discussion or issue if there's a bug.
