### ISSUE TITLE
Draw.io Desktop connects to www.draw.io

### ISSUE THREAD

**Issue by desk7** [jgraph/drawio-desktop#80]
Why does the desktop version draw.io.exe connect to www.draw.io? What kind of information are sent? What is the privacy policy of the desktop version?

**Comment by davidjgraph** [comment]
It connects to try to download an updated version of the app. No diagram data is sent upstream to www.draw.io.

**Comment by davidjgraph** [comment]
10.7.5. is fully offline https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5
