### ISSUE TITLE
Ctrl + Right Arrow stops before the end of the last word

### ISSUE THREAD

**Issue by stevesimmons** [jgraph/drawio-desktop#802]
**Preflight Checklist**

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

When editing text in a shape, Ctrl + Left/Right Arrow moves the cursor one word at a time, but stops before the end of the last word. So to move to the end of the text, I have to Ctrl + Right Arrow to the start of the last word, then use Right Arrow repeatedly to move one letter at a time to the end of the last word.

**To Reproduce**

1. Draw a rectangle with the text "stop too early".
2. Place the cursor before the 's'.
3. Hit Ctrl + Right Arrow twice. The cursor moves to the start of "early".
4. Hit Ctrl + Right Arrow again. The cursor won't move to the end of "early".

**Expected behaviour** - Keeping pressing Ctrl + Right Arrow should move to the end of the text

**Screenshots** - n/a

**draw.io version:** - draw.io version: 15.8.4

**Desktop:** - Windows 11. Also observed on Linux Ubuntu.

**Comment by mararad** [comment]
I tested this and it is working but I am using Win 10 Pro so might be related to Win version.

**Comment by stevesimmons** [comment]
It works ok in the online version. The problem occurs for me in the desktop app on Win 11.

**Comment by davidjgraph** [comment]
I can't repeat on Win 11 with 15.8.7

**Comment by stevesimmons** [comment]
I reinstalled 15.8.7 and it works ok. So closing the issue.
Thanks for your prompt help!

(Funny, I did an update earlier before reporting the problem. Maybe that update didn't fully complete, which is why I reported against 15.8.4.)
