### ISSUE TITLE
Error in filename rewriting when exporting per CLI

### ISSUE THREAD

**Issue by GordianDziwis** [jgraph/drawio-desktop#803]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

## Input

```bash
drawio --export --format png --output public/ diagrams/
```

## Actual Output

```
diagrams/metadata.xml -> public/metadata.xml.png
diagrams/workflows.xml -> public/workflows.xml.png
```

## Expected Output

```
diagrams/metadata.xml -> public/metadata.png
diagrams/workflows.xml -> public/workflows.png
```

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
