### ISSUE TITLE
API for csv import 

### ISSUE THREAD

**Issue by daknhh** [jgraph/drawio-desktop#807]
It would be perfekt if diagrams.net /draw.io could offer an API for csv / sql import which returns an png or draw.io as response - right now its just possible to do it via browser.

**Comment by souliane** [comment]
I also think that this is a great feature to add.

I am writing a converter that outputs CSV for diagrams.net, and this would save me dozens of copy/clicks/paste/clicks.

**Comment by davidjgraph** [comment]
Duplicate of #202
