### ISSUE TITLE
dragging shape moves all diagram

### ISSUE THREAD

**Issue by nabazgharib** [jgraph/drawio-desktop#808]
Hi,
I have a strange issue with diagram, it happened after the upgrade.
I am using desktop diagram 15.8.7 on windows 10.

When I want to drag a shape, all  diagram connected to the shape moves with it, then when  I release the shape except the dragged shape, the rest goes back to the previous  position.
if you notice the video, this happens to in between shapes, the leaf shapes can be moved without any issue.

https://user-images.githubusercontent.com/4522358/144199080-f5374ac4-89c1-4a74-b43a-c82bc2a92b15.mp4

**Comment by mararad** [comment]
Could you attach the diagram file in question so I could test it? 

Thanx

**Comment by nabazgharib** [comment]
Sure this is the file.
[request_task_diagram.zip](https://github.com/jgraph/drawio-desktop/files/7636612/request_task_diagram.zip)

**Comment by nbaghm** [comment]
> Could you attach the diagram file in question so I could test it?
> 
> Thanx

**Comment by mararad** [comment]
Hi,

I am not able to reproduce the behaviour after upgrade to 15.7.8 on Win 10, Windows Installer

When whole diagram is selected, it moves the way you described, but I am not able to reproduce the issue when only one shape is selected.

https://user-images.githubusercontent.com/44292306/144421426-f11dc910-f1eb-43c7-9c1a-5817e05884d5.mp4

Do you have the same issue in diagrams.net online?

**Comment by nabazgharib** [comment]
I just tried it on another PC, worked without any issue.
I installed some plugins, may be they caused that issue.
anyway, i close the issue, thanks for confirming it.
