### ISSUE TITLE
Draw.io Desktop Privacy Policy

### ISSUE THREAD

**Issue by desk7** [jgraph/drawio-desktop#81]
I've just realized that even the desktop app needs internet access to export in PDF and other formats and to convert LaTeX markup to math expression. So, how are these information used? What is the privacy policy?
It is very important because you can't always use the program in offline mode, otherwise you have these big limits. Thanks

**Comment by davidjgraph** [comment]
We don't have a privacy policy for the desktop app at this point. I'd advise not to use it.

**Comment by davidjgraph** [comment]
10.7.5 is fully offline https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5
