### ISSUE TITLE
External Changes dialog does not hide existing dialog

### ISSUE THREAD

**Issue by alderg** [jgraph/drawio-desktop#812]
External Changes dialog is shown repeatedly on top of existing external changes dialog if no action is taken (ie with repeated external changes). Possible solution would be to show the sync message only in the status bar.
![Screenshot 2021-12-02 at 11 31 25](https://user-images.githubusercontent.com/921200/144407074-81aeaa36-0fce-4263-99e6-7ad1ab4f680c.png)

**Comment by m-mohamedin** [comment]
Fixed
