### ISSUE TITLE
Partial Rectangle Corner Is Incomplete

### ISSUE THREAD

**Issue by bt-tech-dd** [jgraph/drawio-desktop#813]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When a partial rectangle is created without any styling the lines at the top left corner do not connect.

**To Reproduce**
1. Drag the Partial Rectangle shape from the shape list to the drawing page to create a partial rectangle
2. Click on Edit Style
3. Remove all text except for "shape=partialRectangle" and click Apply
4. Unselect the partial rectangle and see the top left corner is wrong.

**Expected behavior**
Expectation is that a partial rectangle with all sides should appear as a normal rectangle.

**Screenshots**

This is the shape I am using to create the partial rectangle.
![image](https://user-images.githubusercontent.com/68382967/144457400-51ce1827-bcbc-43f5-9a31-2a0daa2fb526.png)

This is the corner of the partial rectangle that is wrong.
![image](https://user-images.githubusercontent.com/68382967/144457657-e53a4855-dfd7-48cc-a996-2ab6e7337e7e.png)

This is a screenshot of the style window for the partial rectangle.
![image](https://user-images.githubusercontent.com/68382967/144457165-3ffc65f4-0a85-4818-be4c-ede45b27e01f.png)

This is how I am expecting the partial rectangle to look.
![image](https://user-images.githubusercontent.com/68382967/144458121-11d1fdda-b622-491c-b944-55539265ea5d.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.7.3

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by bt-tech-dd** [comment]
This bug is still present in version 15.8.7.

**Comment by alderg** [comment]
Fixed in the next release.
