### ISSUE TITLE
Exporting PDF Adds Extra Pages

### ISSUE THREAD

**Issue by bt-tech-dd** [jgraph/drawio-desktop#814]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When exporting a drawing as a PDF extra blank pages will be created.

**To Reproduce**
1. Go to File -> Export as -> PDF...
2. Click on Export
3. Click on Save
4. Open the PDF that was just saved and there will be extra blank pages.

**Expected behavior**
Expectation is not having extra blank pages in the PDF.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.8.7

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
The drawing I tested with was set to a paper size of US-Letter (8,5" x 11").
The PDF is showing a paper size of 8.51 x 11.01.

**Comment by mararad** [comment]
Are you having the same issue with both Portrait and Landscape US-Letter (8,5" x 11") orientation, please?
How many pages does your diagram have?
Do you have the same problem with other paper sizes?

Thanks,

**Comment by bt-tech-dd** [comment]
Landscape does not produce extra pages however, the exported page size is still wrong, 11.00 x 8.53 instead of 11.00 x 8.50.

My diagram only has one page.

Exporting a US-Tabloid (11" x 17") landscape does not produce extra pages but the page size is wrong, 17.00 x 11.01 instead of 17.00 x 11.00.

Exporting a US Tabloid (11" x 17") portrait does not produce extra pages but the page size is wrong, 11.00 x 17.01 instead of 11.00 x 17.00.

Were you unable to reproduce the issue?

**Comment by mararad** [comment]
US-Letter (8,5" x 11") Portrait orientation extra blank page - reproduced with 15.8.7 on Win 10 Pro.

Does File > Print > Print to PDF/Save as PDF help as a workaround? At my place it doesn't show extra blank page.

**Comment by bt-tech-dd** [comment]
Using the print to PDF option is not a acceptable workaround because when using that option the scaling of the drawing is wrong. For example, if I have a box that creates a border 0.5" from the edge of the page, exporting the drawing as a PDF the border is positioned correctly. Using the print to PDF option the border is not positioned correctly. I have attached the test PDF files for your review.
[PDF print test.pdf](https://github.com/jgraph/drawio-desktop/files/7668811/PDF.print.test.pdf)
[PDF export test.pdf](https://github.com/jgraph/drawio-desktop/files/7668814/PDF.export.test.pdf)

**Comment by spidermonkdust** [comment]
I have experienced this same behavior using 15.8.7 on Win 10 Pro.
As a work around, I use a Custom paper size of 8.49 x 10.99, which then outputs a single page PDF of 8.5 x 11.
Seems it has to do with the export adding that extra 0.01" to the PDF.

**Comment by bt-tech-dd** [comment]
This bug is still present in 17.2.4.

**Comment by suikan4github** [comment]
I have a similar problem using v17.2.4 on Ubuntu 20.04. 

This problem can be reproduced by the command line ( it seems to be file-dependent ). 
Attached [050_010_overview.zip](https://github.com/jgraph/drawio-desktop/files/8403624/050_010_overview.zip) reproduce this problem with the following command line. 

```
drawio -xf pdf --crop -b 10 050_010_overview.drawio
```
This command generates a two pages PDF while only one page is expected. See the following screenshot. 
![Screenshot from 2022-04-03 10-26-40](https://user-images.githubusercontent.com/26223147/161407305-5f690005-3a95-44a0-a7e7-04b88a99226b.png)

By quick investigation, I found the option "-b" makes this problem. The following command line doesn't generate an extra PDF page. 

```
drawio -xf pdf --crop 050_010_overview.drawio
```

Of course, we will lose the expected border area, in this case. 

This problem can be also reproduced on the GUI operation. To reproduce, 

1. Go to File -> Export as -> Advanced... 
1. Set PDF to the file format.
1. Set a non-zero value to the border width. 

![Screenshot from 2022-04-03 10-39-14](https://user-images.githubusercontent.com/26223147/161407569-8098ee6c-d146-4e5b-b2ec-e2642659317c.png)

**Comment by JacobChikwanda** [comment]
Here's another quick solution. File -> Export As -> PDF. Tick the crop option and that's it.

**Comment by bt-tech-dd** [comment]
Using the crop option will create a page size smaller than what the paper size is set at within draw.io. For example if I have a single box on the 8.5"x11" page that is 1"x2", when I export to PDF with the crop option the page size ends up being 1.01"x2.04".

**Comment by macdonaldtomw** [comment]
same problem.  This bug is giving me carpal tunnel syndrome

**Comment by gusmaogabriels** [comment]
This issue still persists.

**Comment by euan-cowie** [comment]
Still persists

**Comment by jmesterh** [comment]
Still persists, in my case setting the first page as landscape and then setting page scale for that page to 80% creates a blank first page when exporting as PDF.

**Comment by p3t-namyen** [comment]
I used this workaround : Print -> Microsoft PDF printer -> Select the pages I wanted to print

**Comment by alderg** [comment]
Works for me in v26.1.3 with [this test case](https://app.diagrams.net/?dark=auto#R%3Cmxfile%3E%3Cdiagram%20name%3D%22Seite-1%22%20id%3D%22ihsY0P0q-jaZ489HQAD1%22%3EjZJRb4MgEMc%2FjY9bEFrnHteu29JlyZIu6eNC5CokKAZxaj%2F9cB5VszTpE%2FC7%2Fx3wv4vYtuheLa%2FkhxGgI0pEF7HniNKYrBK%2FDKQfSZrQEeRWCRRN4KDOEDKRNkpAvRA6Y7RT1RJmpiwhcwvGrTXtUnYyenlrxXP4Bw4Z10jJfTrxoxJOojpOHqfAG6hc4uUpfRgDBQ9i%2FEstuTDtDLFdxLbWGDfuim4LerAvODPmvVyJXh5soXS3JPRnWhN4X3%2BdzMbtm2%2FytD%2FeYZUfrhv88udgCSUYqF0fvLCmKQUMxUjENq1UDg4Vz4Zo67vvmXSF9qfYb7EsWAfd1ffGFxf8AIEpwNneSzCBrdE4nJ1VGIp21odgrpy1IEHGsfn5pfTkjt%2BgQeE4NeIvNhtotvsF%3C%2Fdiagram%3E%3Cdiagram%20id%3D%22BokLmXq13iu_x1kBXkqk%22%20name%3D%22Seite-2%22%3EjZJLT8QgEMc%2FTY8mBWpdr%2B5DE11jsge9YhkLCS0NpdvWTy%2B1Qx%2FZbLInht88YP4zEdsW3bPllTwaATqisegitosoJXGS%2BmMg%2FUg2KR1BbpXAoBmc1C%2BETKSNElCvAp0x2qlqDTNTlpC5FePWmnYd9mP0%2BtWK53ABThnXl%2FRTCSexC%2Fow8xdQuQwvk%2FRx9BQ8BGMnteTCtAvE9hHbWmPcaBXdFvQgXtBlzDtc8U4fs1C6WxLg3JJ3Vb6%2Bfcndkd0fEvtN77DKmesGG%2F4YBKExTql2fVDCmqYUMBSLI%2FbUSuXgVPFs8LZ%2B9p5JV2h%2FI97EsmAddFf%2FSyYV%2FPqAKcDZ3odgAt2gcLg5JMF7O8%2BBBHHlYgYpMo6jz6fSszreQIHCdR7Ev2%2Bxzmz%2FBw%3D%3D%3C%2Fdiagram%3E%3C%2Fmxfile%3E):

<img width="692" alt="Image" src="https://github.com/user-attachments/assets/fdea8173-444e-4c2d-9912-1c1d111b40b5" />

**Comment by ixm-ibrahim** [comment]
Still occurring for me.

I don't know if my case is niche or general, but the issue was caused for me because "mathematical typesetting" was enabled, and the **pre-formated** latex scripts (which would be a single line with no line breaks) would extend to the right and left of the page (even though the nice, formatted text would be well within the page.

Noticed this because every time I'd open the page (when I'm on a different page - note I have the "page view" setting on), the blank pages to the right and left would be temporarily visible - until I'd zoom in or out, then they would go away.

Resolved by disabling "mathematical typesetting" to show the pre-formatted latex scripts, adding a bunch of newlines to the pre-formatted latex script so that it would be within the page, then re-enabling the "mathematical typesetting" option. Export to PDF worked just fine after that!

**Comment by alderg** [comment]
Thanks, that's a useful lead: with math typesetting on, the unformatted LaTeX source seems to count towards the page size before it's rendered. If this still happens with the current version, please open a new issue with a small file that shows the extra pages.
