### ISSUE TITLE
MSI Installer required for deployment

### ISSUE THREAD

**Issue by alexhass** [jgraph/drawio-desktop#815]
Can you add an MSI based installer for per machine installations, please?

**Comment by davidjgraph** [comment]
That differs how from the current installable option?

**Comment by alexhass** [comment]
The current installers are EXE installers only.

EXE installers cannot deployed to desktops via Microsoft Active Directory GPO. The only allowed setup format is MSI.

**Comment by m-mohamedin** [comment]
Will be added to the next release
