### ISSUE TITLE
Copy and paste keyboard shortcuts donot work on linux with drawio-desktop

### ISSUE THREAD

**Issue by SunicYosen** [jgraph/drawio-desktop#817]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I use drawio-desktop(lastest 15.8.7) on my linux desktop(Ubuntu 21.10) installed with deb package and APPImage, the copy shortcut ctrl+c and the paste shortcut ctrl+v have no any response. While the action with mouse "copy" and "Paste here" work well.

**To Reproduce**
1. Go to drawio desktop
2. Click on ctrl+c when something selected
3. Click on ctrl+v
4. See nothing happen
5. Ctrl+c cannot copy and ctrl+v cannnot paste

**Expected behavior**
The selected objects should be copied and pasted.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version  15.8.7

**Desktop (please complete the following information):**
 - OS: Ubuntu21.10

**Comment by mararad** [comment]
Does uninstall/reinstall help?
Is e.g Ctrl+d working?

**Comment by SunicYosen** [comment]
> Does uninstall/reinstall help? 

Actually not. I have installed drawio-desktop with deb/appimage/flatpak packages on my linux desktop, the copy and paste shortcut donot work.

> Is e.g Ctrl+d working?

Ctrl+d works well with duplicating the selected objects.

Thanks for your reply.

**Comment by slightcrazed** [comment]
I can confirm this bug on Ubuntu 20.04 with all updates applied and the latest drawio deb installed (18.1.3).

**Comment by Shaco-Ma** [comment]
I got the same question on ubuntu 20.04.3LTS and use the lastest drawio deb version  20.3.0,ctrl+d is ok,but ctrl +c and ctrl + v can't work.

**Comment by m-mohamedin** [comment]
I couldn't reproduce on Ubuntu 20.04.5 LTS (amd64)

**Comment by terence4444** [comment]
Linux version 5.15.0-71-generic (buildd@lcy02-amd64-044) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023

This issue remains

**Comment by 0xab-c0de** [comment]
Disabling the "Show position of mouse pointer when the Control key is pressed" in the System > Preferences > Hardware > Mouse > General settings was the solution in my case.

`gsettings set org.mate.peripherals-mouse locate-pointer false`

Confirm that `CTRL+D` always worked. And now - super happy - `CTRL+C`, `CTRL+X`, `CTRL+V` is back. 

Applies to: 
* Linux w. MATE Desktop

Affects:
* Draw.io Desktop (flatpak, .deb, AppImage)
* WebApp app.diagrams.net

**Comment by terence4444** [comment]
Update: Instead of Flatpak version, this time I chose deb v26.2.15 on my new computer. Copy and paste works this time.
Linux  6.14.4-061404-generic #202504251003 SMP PREEMPT_DYNAMIC Fri Apr 25 12:15:31 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mrkissinger** [comment]
The issue remains v27.0.9 Deb version.
Ctrl-D works.

**Comment by ditingvh** [comment]
this issue remains v[28.2.5] on linux mint 22.2

**Comment by ranai-srivastav** [comment]
This issue remains in v29.6.1 on Ubuntu 22.04

**Comment by alderg** [comment]
Works for me on Ubuntu 24.04.4 LTS with Xfce4.

**Comment by davidjgraph** [comment]
This issue doesn't occur for me using Ubuntu 24 with our latest distribution.

If you're still seeing this using our distributions, please open a new ticket with full details. Note there are many distributions that we are not the author of, like flatpak, archlinux, etc. We cannot assist with a distro that we're not the author of.
