### ISSUE TITLE
External Changes popup

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio-desktop#819]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I get a popup that says "External Changes. File has been modified." once every few minutes. I don't believe the file is actually being modified.
<img width="269" alt="Screen Shot 2021-12-07 at 1 39 54 AM" src="https://user-images.githubusercontent.com/191903/144986958-9b8bc259-f02c-4c6a-a87b-a57e7bb61677.png">

I just updated to the latest drawio version. This didn't happen until I updated.

**To Reproduce**
not sure

**Expected behavior**
No popup when file is not modified

**Screenshots**
See above

**draw.io version (In the Help->About menu of the draw.io editor):**

15.8.7

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6

**Comment by ldesordi** [comment]
Same issue here.

Draw.io desktop version: 16.5.1
OS: Windows 10 21H1

**Comment by JesseAldridge** [comment]
Updated to 17.4.2 and the issue has gotten worse.
After clicking Synchronze in the initial popup, a second one appears:
<img width="463" alt="Screen Shot 2022-04-29 at 5 10 52 AM" src="https://user-images.githubusercontent.com/191903/165933765-fb17488a-1075-4875-a35a-2fe8a77d41c6.png">
If I click Merge, after saving, drawio switches to the top-left corner of the first tab in the diagram file.
This is very disorienting and annoying since I usually work with many tabs.

**Comment by davidjgraph** [comment]
@JesseAldridge Does it always happen with that one diagram, or all? Could we see that diagram (support@diagrams.net) ?

**Comment by JesseAldridge** [comment]
I think it only happens with large files (i.e. several large images). I sent a video and a sample diagram to the support email.

**Comment by davidjgraph** [comment]
We're hoping switching off compression might well with this.

**Comment by JesseAldridge** [comment]
I actually can't remember the last time I saw that popup. I think this bug was somehow fixed long ago.
