### ISSUE TITLE
can I copy data from Excel and keep the original style

### ISSUE THREAD

**Issue by wtslpx** [jgraph/drawio-desktop#821]
When I copy data from Excel,it imported as a large txt box.
 
here has two for reference：

1.imported data from excel and can edit as a table object

2.pasted from excel copied and edit as a table object

would you like it? tks.

**Comment by wtslpx** [comment]
or pasted as a picture

**Comment by davidjgraph** [comment]
What are you expecting it to do? We don't support import from a spreadsheet.
