### ISSUE TITLE
SVG export fails with lists and latex expressions

### ISSUE THREAD

**Issue by SpghttCd** [jgraph/drawio-desktop#822]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I saw issues about svg latex expression export, but all with regards to some dark mode topic and without the list problem.

**Describe the bug**
Lists and latex expressions are not correctly set when the drawing is exported as svg.
In the svg file, there are all lines of the list in one string, without the bullets of the list and latex expression are shown raw, i.e. unrendered.

**To Reproduce**
1. Create a shape and add text, mark the text
2. change to bullet list
3. create a shape and insert a latex expression, e.g. $$\frac{1}{2}$$
4. save document
5. export document as svg filetype

**Expected behavior**
I'd expect to see a bullet list and rendered latex output in the svg in e.g. Inkscape

**Screenshots**
![image](https://user-images.githubusercontent.com/25030860/145374754-c69701ef-b73b-497c-9e12-2d77501c0da1.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net 15.8.7 and 
https://app.diagrams.net/?src=about 15.9.4

**Desktop (please complete the following information):**
Windows 10

**Comment by alderg** [comment]
Could you attach a test case please? Which browser and version are you using?

**Comment by SpghttCd** [comment]
Hello,
my Browser is Microsoft Edge, Version 95.0.1020.44 - but I see this behaviour in both the browser based editor and the desktop application.
I have tried to attach the drawio-file which was my test case for the screenshot in my first post, but github refused it because of being no image file.
So the testcase is basically described in the "To Reproduce" section of my post above.

Anyway, if there is a possibility to upload the drawio file, please let me know - I don't understand how to do that yet.

**Comment by alderg** [comment]
Export as URL and paste that here.

**Comment by SpghttCd** [comment]
ok, thanks for the hint - here you are:
https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=list_and_formula.drawio#R3ZXbcpswEIafhst2OMQ4vSzYTQ9uJ62TurnUGBnkyCwVi4E%2BfQWSEMQZJ%2BlMbjrjsbXf7uqw%2B0t2gvjQXAlSZF8hodzx3aRxgoXj%2B2Hgyu8OtArMwkCBVLBEIc%2BCNftDNdR5acUSWk4CEYAjK6ZwC3lOtzhhRAiop2E74NNVC5LSE7DeEn5KNyzBTNFLf275R8rSzKzshe%2BU50BMsJ6izEgCtUL94YKlE8QCANXo0MSUd7Uzddl8ajd8dR9eff5e%2Fia30Zebbz%2FfqLJ8eEnKcARBc%2FznqX%2FE7mJTr69X%2B9tsv7u5XgZgUtwSW1MvmsjyaRMEZpBCTvjS0khAlSe0m9WVlo1ZARQSehLuKWKrtUAqBIkyPHDtpQ3DX13625m27kaeRaNn7o3WGDmKdpTUmXdjn03rLZOnztcd6oEcnqil6TlUYkvPxOnLgESk9Ox83qAYedMoHKjcpUwUlBNkx%2BnuiNZ8OsTZvsqBbu0LFKR3eSS80is5fsjlfqNK5oYp9pVShDND3hsk17T0NC56Zlx8Nk7C8WYeyNKKrtNJnTGk64L0ranluzUV2A5y1OrzZNGjlJOy1IIoUcD98BR00cO9tnp5rjyOVCBtRr07bbDxhvqq6Wf0Upu1fZM8X7Ns9B5duK8kCc97RBMX3WcWE15kRPp67EqwE2TrzCM5KpgzX8hh0P2o%2BP%2B9Vd7s9XolTfsH0vtG%2F8LB8i8%3D

**Comment by alderg** [comment]
Are you viewing the exported SVG in a browser? If no, can you check if that works? If that works your viewer does not support foreignObjects. See https://www.diagrams.net/doc/faq/svg-export-text-problems

**Comment by SpghttCd** [comment]
No, I actually wanted to use the diagram in a Word Doc, eventually add some things in Inkscape - and both applications don't show the correct representation.

You are completely right: when opened in a browser (tested it with Edge -> ok, with IE -> not ok btw...) it works.
Sorry for filing this as a drawio-bug - in my world inkscape was always the standard for svg.
And thanks for your immediate help.
_____

EDIT: For all users who have a similar workflow and want to go on with a diagram in inkscape:
Afaics exporting as pdf and importing this pdf into inkscape works at least for my needs described in the post above.
