### ISSUE TITLE
Cutting and pasting large images into new tab extremely slow

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio-desktop#823]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
After upgrading to latest version, copy and pasting large images has slowed down drastically.

**To Reproduce**
1. Go grab a handful of large images from wikipedia
2. Throw them into a diagram
3. Make a new tab
4. Cut and paste all the images from one tab to the other

It takes like 20 seconds for the operation to complete

**Expected behavior**
Faster, like it was before

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io 15.8.7

**Desktop (please complete the following information):**
<img width="247" alt="Screen Shot 2021-12-10 at 3 45 01 AM" src="https://user-images.githubusercontent.com/191903/145553189-bf52f242-9ba1-491d-a4c2-5fdf26895b84.png">

**Additional context**

**Comment by davidjgraph** [comment]
We're assuming this is the same problem as #853 .
