### ISSUE TITLE
Better connection mode

### ISSUE THREAD

**Issue by nick87720z** [jgraph/drawio-desktop#826]
**Is your feature request related to a problem? Please describe.**

Current connection mode could be more convenient.

Current way - per connection:

1. Add connection (adds as object)
2. Drag one end to one node
3. Drag second end to second node

**Describe the solution you'd like**

Better way, more like how other editors implement it *(in particular, LibreOffice Draw and [Dia](https://wiki.gnome.org/Apps/Dia) graph editor)*:

- For all connections: select connection type (in toolbar, palette, etc).
- Per connection: drag from one node to second to create connection.

**Describe alternatives you've considered**

[DotEditor](https://vincenthee.github.io/DotEditor), worthy WYSIWYG editor and [graphviz](https://graphviz.org) frontend, does it via dialog, where connected nodes are selected via combobox'es.

**Comment by davidjgraph** [comment]
Both of these methods are built-in, please read https://www.diagrams.net/blog/use-connectors
