### ISSUE TITLE
Persistent auto-layout mode

### ISSUE THREAD

**Issue by nick87720z** [jgraph/drawio-desktop#828]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**  

Current way of workflow with auto-layout is relatively inefficient.

My current workflow:

1. Add nodes by click in palette.
2. Manually arrange nodes in order to be able to connect them, because:
 - They appear in center of view (paning view is only way to change insertion positon).
 - Also: Bug: Auto-layout ignores unconnected graph parts
3. Connect nodes (related feature request #826)
4. Invoke auto-layout to rearrange current layout.

**Describe the solution you'd like**  

Auto-layout could be implemented as persistant editing mode.  
Following changes should trigger it:

- Any graph change, affecting structural or geometric change for graph (by geometric I mean nodes size due to text, placement due to weight, may be lines thickness).
- Changes to auto-layout mode and its parameters

Expected workflow:

1. Add nodes by click in palette
2. Connect nodes
3. PROFIT?

If no-auto-layout way is still wanted, there could be checkbox (for both menu and toolbar) to toggle persistant auto-layout. Both in menu and toolbar.

I see issue #549 closed with no clue of what's resolution. Anyway - implementing this should even further improve workflow (could be little problem with hotkeys when web version is used).

**Comment by davidjgraph** [comment]
Declined.
