### ISSUE TITLE
Export to PDF Error - Truncates Diagram

### ISSUE THREAD

**Issue by jwhaus** [jgraph/drawio-desktop#832]
When I export to PDF my diagram is cut off and partially moved to a new page making it hard to use.
![PDF Export Bug](https://user-images.githubusercontent.com/95928458/145602398-ab8f7c7d-bc50-42df-a8a0-b27f8b44bc4d.png)

**Comment by mararad** [comment]
Could you attach whole file or if you are using multiple pages, attach all pages. 
This is how I see the attached diagram logs in the editor and PDF:
![test user pdf](https://user-images.githubusercontent.com/44292306/146900277-b9b1856a-fbdf-4be3-8bc2-d5052a55cf1c.JPG)
[test pdf.drawio.pdf](https://github.com/jgraph/drawio-desktop/files/7750906/test.pdf.drawio.pdf)

Also, try the export with version 16.0.0 (do hard reload until you see the version).
Also try File > Print > Print to PDF or File > Export as > Advanced > PDF and experiment with different layouts

**Comment by m-mohamedin** [comment]
Please check the page size. As seen in the following screenshot, you are using a page size that doesn't fit the entire diagram.
![Screen Shot 2021-12-21 at 8 35 52 AM](https://user-images.githubusercontent.com/24944765/146938891-a54e7d10-c1b1-404b-a45e-5672f4589c1e.png)

Another option is to use File > Print > Print to PDF and choose fit option
