### ISSUE TITLE
Request to Add Option to Select Whether Turn On/Off Spell Check

### ISSUE THREAD

**Issue by zhongxiang117** [jgraph/drawio-desktop#842]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
* [how to disable the spell checker in drawio-desktop? jgraph/drawio#420](https://github.com/jgraph/drawio-desktop/issues/420)
* [Add spell check function jgraph/drawio#1721](https://github.com/jgraph/drawio/issues/1721)

Since the first request to disable `spell check` was fulfilled, it has been around one year that this useful function is not added back. Why to turn if off only on a "single"(_open & close issues_) request? The fact is not every is using Mac or the native English speaker. Please take it back or at least add an option to let user make their decision.

**Describe the solution you'd like**

May it be a good solution to modify UI:
![image](https://user-images.githubusercontent.com/28009328/146754645-c990666a-044b-46ea-bd01-a3bfcb0e6a20.png)

**Describe alternatives you've considered**

Or the modification on startup:
![image](https://user-images.githubusercontent.com/28009328/146754940-cc23c859-406d-491b-b6c0-37a0ce0c1391.png)

**Comment by m-mohamedin** [comment]
Will be added to the Extras menu in the next release

**Comment by zhongxiang117** [comment]
@ashrafteleb Cool, thank you for your work and consideration!

**Comment by zhongxiang117** [comment]
First of all, thanks for your work and consideration for the adding of "Spell checker" option into "Extra" menu starting from [v16.1.0](https://github.com/jgraph/drawio/commit/7964a40d76c7a02d63db5e1b7cc592047b19d8e1).

However, when I tried the new build release [v16.1.2](https://github.com/jgraph/drawio-desktop/releases/tag/v16.1.2) **Linux deb** version, I found the spell checker does not work even with "Spell checker" turned on.

But, for **Windows** version, it works very well.

Let me show you the differences;

**Linux -- Ubuntu**
![image](https://user-images.githubusercontent.com/28009328/147800267-57e1b7c4-0520-433e-9b3c-61e5ed1f4722.png)

**Windows 10**
![image](https://user-images.githubusercontent.com/28009328/147800336-542d2d3b-4187-421a-8de4-7a74e2bc6601.png)
![image](https://user-images.githubusercontent.com/28009328/147800827-27f8ce58-318f-4b35-9f9a-647ce1cca689.png)


My Ubuntu info & dpkg version.
![image](https://user-images.githubusercontent.com/28009328/147800624-94acd950-4c38-4ed4-bf52-492fc4666b1b.png)

Could you please take a look into this question? Thanks!

**Comment by m-mohamedin** [comment]
I think you need to install Hunspell. Electron docs say: "On Windows and Linux this is powered by Hunspell dictionaries, and on macOS it makes use of the native spellchecker APIs."

Could you please try that and let us know?

**Comment by zhongxiang117** [comment]
Hi @ashrafteleb, followed your advice, I installed `Hunspell`, now the spell checker works, thanks!

**Comment by sandeepshivhare** [comment]
Does spell check gives recommendation on correction? If yes, then how since I am not able to find any option for suggestion.

**Comment by zhongxiang117** [comment]
@sandeepshivhare In my experience, no, it does not give spell suggestion, it only shows the indication on whether the word is "valid" or not, which is defined in the dictionary.
