### ISSUE TITLE
connector line runs through the text field of a shape - makes it difficult to read

### ISSUE THREAD

**Issue by ih8snow** [jgraph/drawio-desktop#845]
* [ xx] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I imported my own custom shapes. When I doubleclick the shapes I can enter a text below the shape.
I use this "text field" for additional important info related to the given shape.
When I use a connector from this position, the line of the connecotr "goes throughthe text" and makes it difficult to read.

See Screenshot attached

**Describe the solution you'd like**
I'm looking for a solution that allows me to keep the text below the shape  but brings the line of the connector in the background. So the text is clearly visible.

Screenshot:
![shapes](https://user-images.githubusercontent.com/82544852/147093352-cac4dd60-181e-4629-8a42-7f5a8042d1e2.png)

**Comment by schindld** [comment]
"closed as completed"...what was the resolution?
