### ISSUE TITLE
Doesn't detect system dark appearance MacOS

### ISSUE THREAD

**Issue by Zombobot1** [jgraph/drawio-desktop#847]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The application doesn't detect OS preferred color scheme. As a result theme is always light (even if it is set to automatic) when the whole system is in dark mode.

**To Reproduce**
1. Set dark appearance in system preferences
2. Launch the app

**Expected behavior**
The dark theme is set automatically

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 16.0.2]

**Desktop (please complete the following information):**
 - OS: MacOS
 - Application dmg (https://github.com/jgraph/drawio-desktop/releases/tag/v16.0.2)

**Additional context**

**Comment by NewAlexandria** [comment]
~~Does the app even have a native dark mode?~~  Wondering how remote this feature actually is. 

* The underlying library [does seem to have dark mode support](https://github.com/jgraph/drawio/search?q=dark).
* [There is a mode, via themes, but switching is manual.](https://www.diagrams.net/doc/faq/editor-theme-change)  Also it requires restarting the app.
