### ISSUE TITLE
Provide a method to change the length of all/selected edges

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio-desktop#851]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When we create a large flow diagram from text, the edge lengths are excessive, which produces a flowchart that is unnecessarily too large. It is very tedious to reduce the lengths of all edges. 

This [old thread](https://groups.google.com/u/2/g/drawio/c/Bx8VrsG99k4/m/lr_hSGwyAQAJ) at Google Group describes how to shorten the edges, but it is meant for the **online** version of drawio, not for its **desktop** version.

**Describe the solution you'd like**
Please provide a control/property in the Format panel, which can be used to shorten the selected (or all) edges.

This solution is useful for straight edges.
It may or may not work for the other types like orthogonal/isometric/simple/curved.

**Describe alternatives you've considered**
-Not Applicable-

**Additional context**
-Not Applicable-

**Comment by davidjgraph** [comment]
Declined
