### ISSUE TITLE
Unresponsive buttons after window resizing in Minimal theme

### ISSUE THREAD

**Issue by iu0v1** [jgraph/drawio-desktop#852]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When using the "Minimal" theme, resizing the window makes the control buttons in the top row unclickable (except zoom and undo groups).

**To Reproduce**
1. Open app.
2. Maximize window or change size of floating window by dragging it's corner. 
3. Unable to click "Diagram" "Shapes" "Format" "Insert" or "Delete" buttons, they unresponsive. 

**Expected behavior**
Buttons should work as before resizing.  

**Screenshots**
![draw io_XwT3Kcdejq](https://user-images.githubusercontent.com/1669027/147359647-d9be3409-17c6-4d71-8555-05971f682afd.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.0.2

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro x64 and Windows 10 Pro x64

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
Thanks for the report
