### ISSUE TITLE
"Behind firewall" mode

### ISSUE THREAD

**Issue by maln0ir** [jgraph/drawio-desktop#86]
As mentioned in #80 application tries to connect to www.draw.io to check for updates. This work fine if you are completely offline, but unexpected things may happen if you are behind corporate proxy :|

If that proxy (for some reason) blocks www.draw.io and responds for example with notification "domain www.draw.io is blocked" then draw.io just displays that notification and app is not launched.

Here is how it looks (obfuscated):

![2019-02-05 13_44_13-clipboard](https://user-images.githubusercontent.com/20753183/52274460-08e5a880-294d-11e9-8037-5c1895b8cf2e.jpg)

At this point to make it work one needs to close application, disconnect from network, launch app again and eventually connect to network and it needs to be done for each file.

I think it would be enough to just check updates some time after app was fully loaded and ignore strange responses. Or just allow to disable checking for updates.

**Comment by davidjgraph** [comment]
It's probably the check on this line, https://github.com/jgraph/drawio/blob/94642c30f91fe9b27211d53f22db9139c0f7fbda/src/main/webapp/electron.js#L113.

I assume this check is only catching the case of being offline and returning straight away. The proxy obviously isn't giving the same result and it's not a timeout, a result is returned, just not the right one.

Is it possible to load www.draw.io via your proxy at all? If not, what error code does the proxy return?

**Comment by ashrafteleb** [comment]
Fixed, will be available in next release

**Comment by davidjgraph** [comment]
Done in https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5
