### ISSUE TITLE
Keyboard shortcut to force selection box tool

### ISSUE THREAD

**Issue by ejolson9** [jgraph/drawio-desktop#861]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
It is frustrating to select items within frames in a sequence diagram.  Consider this simple example based off of the sequence diagram template, with a frame placed over the elements.
![image](https://user-images.githubusercontent.com/3166412/148270607-55492e7b-19e4-4856-9e73-4e98f98f2ab5.png)

Let's say that I wanted to move the inside callback down for some reason (humor me).  Resulting in something like: 
![image](https://user-images.githubusercontent.com/3166412/148271475-315d45b9-6977-453a-bbf0-d2a286e74919.png)

The only ways I know how to select these three items (box and two arrows) are:
-  attempt combination of shift-click, alt-shift-click until you successfully select the items
   - shift-click alone runs into issues where non-desired objects are selected
- use selection box, _starting from outside the frame_  (e.g. from right side)
  - this will not work in more complicated examples

Then move items however.

**Describe the solution you'd like**
I would like a keyboard shortcut for the normal selection box tool  (that you normally get by click + dragging in free space).  I would propose this to be alt+right-click,   to be similar to the existing alt+left-click shortcut, select intersection.

This would allow me to start a normal selection box anywhere in the diagram without worrying about whether the items are inside a frame (or possibly other shapes).  This makes the example selection very simple.

**Describe alternatives you've considered**
I'm not sure of alternatives.  Could maybe allow users to disable the 'move' tool that is automatically chosen when mouse is inside frame, but that seems like it would affect existing users.

**Additional context**
Picture indicating the selection boxes.
![image](https://user-images.githubusercontent.com/3166412/148272914-406380fc-2865-40a0-a535-f9a689f5b1f6.png)

**Comment by ejolson9** [comment]
Note that I believe my problem is similar to this problem,  but my solution/request is different:
https://github.com/jgraph/drawio/issues/4070

**Comment by aqx-ddeluca** [comment]
I would also like to start a normal click and drag selection box anywhere in the diagram. This requires the ability to override the move single item cursor that is the default if you are hovering over a larger background item. My drawings often have borders which make selecting groups of items within the border a real nightmare. Locking the items doesn't fix the problem.

EDIT: Found the solution! Hold down Alt while left-click and dragging to achieve the desired box selection action.
