### ISSUE TITLE
Plugins not working, windows 16.1.2

### ISSUE THREAD

**Issue by Mentaleak** [jgraph/drawio-desktop#862]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Local Plugins do not appear to work in 16.1.2

**To Reproduce**

1. Download a copy of the "sql.js"
2. Click on 'Extras'
3. Click on 'Plugins'
4. Click 'Add'
5. Click 'Select File'
4. Click 'Apply'
5. Restart draw.io
6. Click "Arrange"
7. Go to "Insert'
8. Notice the insert from sql is missing from the bottom of list

This happens with other custom plugins as well.

**Expected behavior**
Plugins options should appear in menu

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.1.2

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by iurifarenzena** [comment]
It might be worth mentioning that there are no error messages/alerts, the application simply does not activate the plugins.

**Comment by m-mohamedin** [comment]
Thanks for the report. It will be fixed in the next release
