### ISSUE TITLE
Read-only file can not be saved under different filename from within drawio-desktop

### ISSUE THREAD

**Issue by friedl-e** [jgraph/drawio-desktop#864]
**Describe the bug**
A file which has been set to read-only in the filesystem can not be saved under a different filename because drawio-desktop complains about the read-only status of the original file.

**To Reproduce**
1. Create a new file with some sample contents, save it as "test.drawio".
2. In the filesystem using Windows Explorer set the "read-only" flag.
3. Double click the file to open it in drawio-desktop again.
4. Click File -> Save As to save it again as "test2.drawio".

**Expected behavior**
"Save As" should always work, even if the original file is read-only.

**draw.io version (In the Help->About menu of the draw.io editor):**
drawio-desktop 16.1.2 (installed using draw.io-16.1.2-windows-installer.exe)

**Desktop (please complete the following information):**
OS: Windows 10 Version 20H2 (Build 19042.1415)

**Comment by friedl-e** [comment]
The only way out of the misery at the moment is:
- export as XML, e.g. as "test2.drawio.xml"
- via "Open..." open the XML file "test2.drawio.xml"
- Now save as "test2.drawio"

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
