### ISSUE TITLE
open, save, export folders wished to be "following" folder of current document

### ISSUE THREAD

**Issue by friedl-e** [jgraph/drawio-desktop#865]
According to issue https://github.com/jgraph/drawio-desktop/issues/117 the last open, save, export folders are currently remembered. This is also what I experience.

When I work with files in different directories I would like the open, save, export folders to follow the currently opened file. Very much like it's in Microsoft Word, when I export a PDF there, or when I select to open a file, the folder of the currently open document is the default path.

If I work in directory X and create e.g., a PDF export, I'd like to have the export saved to the same directory X.

Currently if I've exported to directory Y before, because I edited a file there, closed all drawio-desktop windows,  and then double clicked a file in directory X, I have to switch the export path manually. A lot of times the files end up in the wrong directory because of that.

Please consider. Thanks in advance.

**Comment by friedl-e** [comment]
Am I really the only one which is annoyed by the fact that every time your save or export, you always have to select the correct folder because the last folder is used instead of the current working folder of the file you just opened?

**Comment by friedl-e** [comment]
Again, am I really the only one which is annoyed by the fact that every time your save or export, you always have to select the correct folder because the last folder is used instead of the current working folder of the file you just opened?

**Comment by davidjgraph** [comment]
Looks like it from the lack of votes.
