### ISSUE TITLE
Can not move the interface of drawio-desktop between two screens

### ISSUE THREAD

**Issue by qingfeng520** [jgraph/drawio-desktop#866]
**Describe the bug**
      My notebook connected a Dell display, When I opened drawio-desktop, not ever Zoom in or out the drawio-desktop interface,
Can not move drawio-desktop from the notebook screen to the Dell Display screen;
     But I remembered the pre-version could move between screens;

- draw.io version 16.1.2
- OS: Windows  11

**Comment by mararad** [comment]
Could you take a look at this thread please https://groups.google.com/g/drawio/c/TcikGL_aAwc/m/KrRxFZjvDwAJ and let me know if it helps.

**Comment by qingfeng520** [comment]
Yes, it worked. My APP interface default is full screen, So I don't see the top bar and can't move the interface. When I click the full screen button on the top right corner, I can move the interface.
 Thanks, bro.

**Comment by qingfeng520** [comment]
> Could you take a look at this thread please https://groups.google.com/g/drawio/c/TcikGL_aAwc/m/KrRxFZjvDwAJ and let me know if it helps.


Yes, it worked. My APP interface default is full screen, So I don't see the top bar and can't move the interface. When I click the full screen button on the top right corner, I can move the interface.
Thanks, bro.

**Comment by ahrib** [comment]
Hi, am unable to move the draw.io interface by click&drag anywhere on the title bar in Draw.io v19.0.3

what I have tried
- following instructions in https://groups.google.com/g/drawio/c/TcikGL_aAwc/m/KrRxFZjvDwAJ  

what does work:
- using alt-space and selecting 'move' allows me to move the window e.g. with arrow keys
- resizing the window using mouse controls
- minimise, maximise, full screen and close controls

Environment
- Draw.io v19.0.3 Desktop for Windows 64 bit
- Windows 10 21H2 64-bit
- HP EliteBook 840 G8 Notebook PC
