### ISSUE TITLE
Mouse wheel zooming too sensitive

### ISSUE THREAD

**Issue by marin-8** [jgraph/drawio-desktop#868]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Zooming via the the CTRL key + the mouse wheel multiplies/divides the current zoom level by 2.333... (being to much).

**To Reproduce**
1. Open a new or any existing draw.io file.
2. Zoom via the CTRL key + the mouse wheel.

**Expected behavior**
Zoom in smaller steps, multiplying/dividing the current zoom level by a factor of 1.2 (like in previous versions).

**Screenshots**
Not applicable.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 16.1.2
- Not being sure, I think that this is happening since version 16

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
In version 15.0.6 of the web app this doesn't happen. It zooms multiplying/dividing the current zoom level by a factor of 1.2

**Comment by mararad** [comment]
Hi,

For smoother zooming try using config zoom factor under Extras. An example:
{
"zoomFactor": 1.05 (or 1.2)
}

Does this help?

**Comment by marin-8** [comment]
> Hi,
> 
> For smoother zooming try using config zoom factor under Extras. An example: { "zoomFactor": 1.05 (or 1.2) }
> 
> Does this help?

Hey.

Yes! Thanks a lot!

Even though this works as a perfect _workaround_, I think that the problem still exists underneath since the zoomFactor that you configure is still smaller than the one that ends up being applied.

I don't know how to continue from here regarding the issue.

Still, thank you again!
