### ISSUE TITLE
Reduce appveyor build trouble

### ISSUE THREAD

**Issue by wobbol** [jgraph/drawio-desktop#87]
In PR#85 the build seemed to fail for reasons unrelated to the added code.
After researching the issue and posting about it in #84, it seems that the trouble is related to the `--depth` argument to `git`. The general advice seems to be use the appveyor config option `shallow_clone: true` instead.
The only stopper in this is that this project uses a `clone_script`. Since the only special thing it does is checkout submodules, I think moving that over to `install`is a small price to pay to get github api shallow clone.

Would a PR that made these changes be accepted?

related reading, in no particular order:
- https://www.appveyor.com/docs/how-to/repository-shallow-clone/#downloading-repository-via-github-or-bitbucket-api
- https://stackoverflow.com/questions/31278233/disadvantages-of-shallow-cloning-on-travis-and-other-ci-services#answer-53857834
- https://www.appveyor.com/docs/build-configuration/
- https://github.com/appveyor/ci/issues/899#issuecomment-426850994

**Comment by davidjgraph** [comment]
Sure, willing to look at a PR.

**Comment by davidjgraph** [comment]
Since the feature requested in #84 and #85 are added, I'll close this, unless there's a good technical reason to implement it.
