### ISSUE TITLE
Changes in JSON configuration are not remembered

### ISSUE THREAD

**Issue by saf-dmitry** [jgraph/drawio-desktop#873]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Since update to v16.4.0 JSON configuration setting are not remembered.

**To Reproduce**
1. Go to 'Extras > Configuration'
2. Make changes in JSON configuration and click 'Apply'
3. Restart the application
4. Go to 'Extras > Configuration'
5. See changes discarded.

**Expected behavior**
After changing the JSON configuration and restarting the app changes are saved and have effect.

**Screenshots**
Not applicable.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 16.4.0

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6

**Additional context**
Not applicable.

**Comment by m-mohamedin** [comment]
Will be fixed in the next release.
