### ISSUE TITLE
No file extension is appended to the filename by the Save As dialog

### ISSUE THREAD

**Issue by skoehler** [jgraph/drawio-desktop#874]
When saving a file, the Save As dialog will not automatically append the file extension `.drawio` to the filename if it is entered without a file extension. I think appending the extension is standard behavior of many programs and drawio should behave the same.

I'm am using version 16.4.0.

**Comment by Lawri-van-Buel** [comment]
@davidjgraph Can you add why this is a wontfix?
(not that I think this proposal is worthy of a fix... but communicating why can help people understand why somethings are the way they are.)

**Comment by davidjgraph** [comment]
There is a bug template, the OP deleted it and posted a report that lacks the basic information we need. I spend my life asking the same questions when people should have filled in the template. Then I answer questions like yours asking why I haven't explained myself.
