### ISSUE TITLE
Open and Save dialogs to not get focus

### ISSUE THREAD

**Issue by skoehler** [jgraph/drawio-desktop#875]
I am using KDE Plasma on Arch Linux with drawio-desktop-bin 16.4.0. I have to switch focus manually from the main window to the dialog. In most cases the dialog "hides" behind the main windows.

I also tried the 16.4.0 AppImage on Ubuntu 18.04 with the same result.

**Comment by reidca** [comment]
I had the same issue, I had to to add the extension myself to open the file.
