### ISSUE TITLE
Outdated builds

### ISSUE THREAD

**Issue by kelteseth** [jgraph/drawio-desktop#88]
Hi,

Can you please create a new release, the current one is nearly half a year old.

Thanks!

**Comment by davidjgraph** [comment]
Well, this is always true that a build needs doing. But the editor updates in-place when you load it online, the electron shell only needs updating when there's a new chrome version.

**Comment by kelteseth** [comment]
Well to bad when one is behind a company firewall.... :(

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5 fixes that problem.
