### ISSUE TITLE
HTML export feature - include local copy of JS libraries for offline/air-gapped viewing

### ISSUE THREAD

**Issue by IAXES** [jgraph/drawio-desktop#880]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am testing the "export to HTML" feature, and the resulting output is nice (very useful for interactive diagram and training materials). However, it can only be viewed when my machine has internet access. Presumably this is to fetch the JavaScript library needed to render the diagrams, but I'm not certain of whether or not the script pulls additional dependencies. In any case, it would be helpful if the "export to HTML" feature included a copy of the necessary dependencies (and have the HTML reference the local copies rather than one on a remote server) so that one could view the HTML render of the final diagram when no internet access is available, or if one is deploying to an air-gapped LAN (i.e. student lab network).

If it's impractical to implement this feature, is there at least a means to manually implement this? (i.e. pull the JS files and any other necessary artifacts from some canonical/official location like a jgraph git repo) so that offline viewing of the HTML exports work?

**Describe the solution you'd like**
Noted above.

**Describe alternatives you've considered**
Noted above (i.e. manual workaround if full-blown enhancement/feature-request is impractical).

**Additional context**
N/A.

**Comment by IAXES** [comment]
Additionally, lab security policies might require a static snapshot of the JS rather than a "live" copy being pulled every time the page is loaded (assuming the browser always purges local cache daily).

Thank you.

**Comment by davidjgraph** [comment]
Export as SVG and embed that?

**Comment by IAXES** [comment]
@davidjgraph I exported my multi-page diagram as an SVG, but it just provides a single page view (i.e. currently-open page) and the interactive functionality (i.e. links) are not present, at least when opening the `.svg` file locally via Firefox. The intent is to preserve/retain the interactive functionality (but in an offline/air-gapped use case).

**Comment by davidjgraph** [comment]
Best solution is fork the [repo](https://github.com/jgraph/drawio) and change the viewer URL in preconfig.js to point at the server.

**Comment by IAXES** [comment]
Sounds good. Thanks for the help, and this awesome tool.

Cheers!
