### ISSUE TITLE
Disabling "Show Start Screen" causes two windows to be openend

### ISSUE THREAD

**Issue by david-04** [jgraph/drawio-desktop#883]
This issue is only for sharing an observation regarding [#860 - Opening Draw Desktop causes two instances to be opened](https://github.com/jgraph/drawio-desktop/issues/860). Sorry for creating a duplicate, but #860 is currently locked.

The problem seems to be related to the "_Show Start Screen_" option. When I delete `Appdata\Roamin\draw.io` and let draw.io re-create it with all the default settings, only one window is opened. As soon as I disable the "_Show Start Screen_" option, two windows (without the splash screen) are opened. After re-activating the "_Show Start Screen_" option again, it's back to normal and only one window is opened.

**Comment by davidjgraph** [comment]
That's very useful, thanks. We'd be trying to work this out.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
