### ISSUE TITLE
document encryption

### ISSUE THREAD

**Issue by chaserene** [jgraph/drawio-desktop#887]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
compartmentalized access to diagrams.net files is currently possible only by using external encryption tools, which makes usage quite complicated.

**Describe the solution you'd like**
the most hands-on solution to this is document encryption that you can opt into when saving the file the first time, or saving as. in this paradigm, all contents of the document are encrypted with a user-defined password using a symmetric cipher, similarly how LibreOffice does it. note that I don't necessarily recommend using the same primitives LibreOffice uses. AES-256 with Argon2 could be a good starting point.

**Describe alternatives you've considered**
GnuPG's symmetric encryption

**Comment by robinbstard** [comment]
This is a valid point in Network diags.  you are documenting a lot of sensitive data - its like keys to safes - in the wrong hands a disaster and very expensive to reset from a hacker.
Its a document and I guess document encryption is quite ok

**Comment by chaserene** [comment]
@stale bad bot, this isn't stale. @davidjgraph, please reopen.

I generated activity on this issue in according to the [Stale bot FAQ](https://github.com/jgraph/drawio/wiki/Stale-bot-FAQ/f4334d18e50a37f3de9f6ddc58f9c5f4cab23e1a#can-i-stop-it-being-closed) that was in force at the time the stale bot's above comment, in order to keep it open:

> just write a comment like "bump" and then delete the comment. That will reset the activity counter for another year.

looks like the method doesn't work, or the bot doesn't obey by it.
