### ISSUE TITLE
Extras -> Plugins menu is gone in Desktop install

### ISSUE THREAD

**Issue by pnt** [jgraph/drawio-desktop#893]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The Extras -> Plugins menu item is gone in 16.4.11. It was there before it auto-updated, now it's gone. Tried re-installing via the universal dmg downloaded from https://github.com/jgraph/drawio-desktop/releases/download/v16.4.11/draw.io-universal-16.4.11.dmg and via Homebrew, neither of which helped.

**To Reproduce**
1. Go to 'Extras'
2. 'Plugins' menu item is gone / not visible

**Expected behavior**
'Plugins' menu item is visible and allows you to install plugins.

**Screenshots**
![Screenshot 2022-01-28 at 17 22 10](https://user-images.githubusercontent.com/1242945/151573370-2e347358-da1d-4e0c-b78e-39e9f8f96fc3.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.4.11

**Desktop (please complete the following information):**
 - OS: macOS 12.1

**Additional context**
Tried removing app data from ~/Library/Application Support/draw.io to no benefit.

**Comment by davidjgraph** [comment]
Fixed in 16.5.1. Thanks for report.
