### ISSUE TITLE
SVG not rendering

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio-desktop#895]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

If I drag and drop this svg: https://upload.wikimedia.org/wikipedia/commons/3/33/Map_Macedonia_336_BC-en.svg
into a diagram I get a blank box.

**To Reproduce**
see above

**Expected behavior**
should see the svg

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.1.2

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6

**Comment by davidjgraph** [comment]
Does it work on app.diagrams.net?

**Comment by JesseAldridge** [comment]
Nope, same result:
<img width="652" alt="Screen Shot 2022-01-29 at 7 22 00 AM" src="https://user-images.githubusercontent.com/191903/151666557-7e5dd75c-31ad-4d1e-b18d-a12c45d09272.png">

**Comment by mararad** [comment]
SVG drag&drop fails also in 16.5.1 (Win 10) but File > Import is working.

Is File > Import > svg working at your place?

**Comment by JesseAldridge** [comment]
Yes that works, but looks like it imports as a low-res bitmap. The text is pretty badly pixelated and hard to read.

<img width="743" alt="Screen Shot 2022-01-31 at 7 13 27 AM" src="https://user-images.githubusercontent.com/191903/151819321-30345d9d-de98-4a98-bfbf-6fe8d1ab6c84.png">

**Comment by davidjgraph** [comment]
The SVG example fails any validation tester I put it through. If I run it through an SVG cleaner like https://svg.enshrined.co.uk/ it then works. Conclusion - not a valid SVG image.
