### ISSUE TITLE
Installation without administrator requirement

### ISSUE THREAD

**Issue by diegounger** [jgraph/drawio-desktop#897]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to update and is required administrator profile. In my company I do not have the administrator profile and any installation or update I need to request IT.

**Describe the solution you'd like**
It would be interesting to be able to install only for the current user, without administrator requirement.

**Comment by davidjgraph** [comment]
Use the no install version

**Comment by diegounger** [comment]
> Use the no install version

I already use the no installation version .
I gave the suggestion because I had the same problem with Bizagi and it was solved this way.
Thank you very much for this software and for the quick response.
