### ISSUE TITLE
Document is empty error

### ISSUE THREAD

**Issue by esell** [jgraph/drawio-desktop#90]
I am trying the desktop app for the first time and running into an issue. I am trying to open a vsdx file but keep getting an error about the document being empty (see attachment). This same vsdx file opens just fine at draw.io though. Am I doing something wrong? I am running the latest release.

<img width="482" alt="Screen Shot 2019-03-22 at 9 08 24 AM" src="https://user-images.githubusercontent.com/9735165/54832809-8574e200-4c82-11e9-9e06-dc101cf4fd9c.png">

**Comment by davidjgraph** [comment]
How are you opening it? Exactly what steps do you follow?

**Comment by esell** [comment]
I just open the app locally (on a mac) and then select "Open Existing Diagram". Once I select a vsdx I get the error. I've tried it with a few different vsdx files.

**Comment by davidjgraph** [comment]
Under Help->About in the menu, what version do you see?

**Comment by esell** [comment]
It says: v 10.5.9

**Comment by davidjgraph** [comment]
Open is designed to open draw.io diagrams. If you want to import an external format, create a blank new diagram and use File->Import to open the .vsdx

**Comment by ThaoPhDo** [comment]
Hi,
I get this error when I try to click on the link which sends to my email. 
I can't open the file. What should I do?
![image](https://user-images.githubusercontent.com/40586892/92071214-5d2a6600-edd8-11ea-88f6-d995e029b2f1.png)
Thanks

**Comment by mikiqex** [comment]
Hello,

on my Windows 10 I created a file type association for ".dio" with draw.io. It works like a charm, but I'd like to be able to create a new diagram by creating a blank file first and then launch draw.io using this empty file. It lauches draw.io, but shows Error loading file: "Not a diagram file".

I'd like draw.io to warn about the empty file and ask, if I want to use it anyway. If I then save it, it will create the proper XML structure for a diagram. Draw.io wouldn't care, if the file is blank. If the file is not blank, the "Not a diagram file" would be a correct error.

Or draw.io could open a blank file right away, without any messages.

**Comment by apboon** [comment]
Experiencing this bug on version `13.7.3` when just starting the Draw.io application (not by opening an associated file).

**Comment by davidjgraph** [comment]
@apboon that's fairly old now, could you try latest please?

**Comment by apboon** [comment]
I am deserving of a face-palm.. I should have checked for this before making an issue :')
Thank you. I will check this ASAP.
