### ISSUE TITLE
147 pages were added as Blank Canvas Pages, cannot delete these pages.

### ISSUE THREAD

**Issue by aysin71** [jgraph/drawio-desktop#900]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I was trying to make a change in my diagram and Drawio added 147 pages to the left of my diagram. It does add a page when something goes out of range, I know that. So although 147 seems unlikely, I zoomed out to see if there is anything in the the first page that may cause this. I see nothing.

I tried to find a menu item to delete the pages I do not want, could not find that either. Since it is not 1 or 2 pages, but 147, I believe it must be a bug, right? 

**To Reproduce**
?

**Expected behavior**

**Screenshots**
![Screenshot 2022-02-03 at 14 22 15](https://user-images.githubusercontent.com/14966824/152352258-a0f39aa8-0fc5-4c23-a997-424ef3313d3d.png)
![Screenshot 2022-02-03 at 14 22 28](https://user-images.githubusercontent.com/14966824/152352319-3177a593-1d0d-46a8-bdd8-6f77e9c67513.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net 15.4.0

**Desktop (please complete the following information):**
MacOS Catalina 10.15.7

**Comment by davidjgraph** [comment]
I would update to the latest desktop build to start with. Are you able to delete the offending shape that adds the pages?

**Comment by aysin71** [comment]
Hi David thank you for such a quick answer. I did update right away.

About the offending shape... I have no idea what that is... I cannot find it. As much as I can see, all my drawing is in one page which is now the last page. And what kind of shape would create 147 pages. That is what makes me think there is a problem with the tool. 

But beside that, is there any way to delete a page?

**Comment by mararad** [comment]
You can delete Page-1 (containing all 147 pages) via right mouse click Page-1 and "Delete". All should go away.

If you'd like to preserve the diagram, you can open a new file and copy/paste the diagram (select the whole diagram Cmd+a and then Cmd+c/Cmd+v) or copy/paste the code you'll find under Extras > Edit diagram

Do you have the same issue when you copy/paste it?

P.S If possible, attach the file so we could test it.

**Comment by aysin71** [comment]
Hi! It was one of the boxes that did not even go over the next page. I found it by chance and deleted it an recreated it.
Thank you...

**Comment by davidjgraph** [comment]
OK, if you hit it again please send the file to support@diagrams.net and we'll work out what the pattern is.

**Comment by liu906** [comment]
I met the same issue and I found a quick solution for it: use binary search to quickly locate the buggy box.  Delete the right half of your boxes to check if blank pages, if yes, then the buggy box is in the right half, otherwise, it is in the left half. Repeat the procedure until the blank pages disappear. Good Luck.
