### ISSUE TITLE
Showing Grouped shapes in Connection Editor

### ISSUE THREAD

**Issue by timboxyz** [jgraph/drawio-desktop#902]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
If trying to edit connectors on a grouped shape the shape is not shown making placing connectors accurately impossible

**Describe the solution you'd like**
Displaying a grouped shape in the connection editor

**Describe alternatives you've considered**
Trial and error seem the only alternative which is painful and inaccurate.

**Additional context**
Example simple grouped shape and Connection editor showing the issue.
<img width="637" alt="Screenshot 2022-02-07 at 10 48 44" src="https://user-images.githubusercontent.com/58913363/152775340-a78f7045-a04b-4583-99e5-e5109c80b92b.png">

**Comment by timboxyz** [comment]
This is a duplicate of #2606 in the drawio repo.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio/issues/2606
