### ISSUE TITLE
Saving a read-only file should open the save-as dialog

### ISSUE THREAD

**Issue by friedl-e** [jgraph/drawio-desktop#904]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Saving a read-only file should open the "save as" dialog, very much like MS Word does in the same case.

This would be a further evolution of [issue #654](https://github.com/jgraph/drawio-desktop/issues/654), to do away with the rather useless error message.

**To Reproduce**
1. Create a file, save it and set it read-only
2. Open it again
3. Click "Save" or Ctrl-S
4. Error message appears.

**Expected behavior**
Very much like MS Word does in the same case, automatically open the "save as" dialog.

**draw.io version (In the Help->About menu of the draw.io editor):**
Draw.io-Desktop 16.5.1

**Desktop (please complete the following information):**
Windows 10 Version 20H2

**Comment by m-mohamedin** [comment]
Will be added to the next release
Thanks for the report
