### ISSUE TITLE
Constantly asking to save file after every single change.

### ISSUE THREAD

**Issue by hienvuvg** [jgraph/drawio-desktop#905]
Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Could you please make this notification optional? I know turning on auto save is good but I don't want the program to continuously save to my hard drive after every single change. I disabled that function and now I have this super annoying notification. Thank you!

<img width="621" alt="image" src="https://user-images.githubusercontent.com/60267498/152717040-1ffe0c10-a637-4e30-af02-8ee9cbb07a50.png">

**Comment by davidjgraph** [comment]
This is the desktop version?

**Comment by hienvuvg** [comment]
> 

Yes, it is. I'm using version 16.5.1 on mac os.

**Comment by robinbstard** [comment]
Indeed an auto save feature save every 5mins would do it

**Comment by mararad** [comment]
When Autosave is unticked, every change a diagram triggers mentioned notification. 
drawio 16.5.1

Suggestion: enable autosave and then configure "autosaveDelay" https://www.diagrams.net/doc/faq/configure-diagram-editor
This might help.

**Comment by hienvuvg** [comment]
Thank you @mararad . It was a bit tricky but here it is (delay 60s): 
<img width="264" alt="image" src="https://user-images.githubusercontent.com/60267498/153887948-521a29bd-bda6-4a58-90e2-7ecdfdc79074.png">
