### ISSUE TITLE
Unable to move the app window to a different screen

### ISSUE THREAD

**Issue by veryviral** [jgraph/drawio-desktop#906]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Unable to move the app window to a different screen.

**To Reproduce**
1. Open the App on a laptop connected to one or more external screen(s) (could be direct or via a docking station)
2. Click and hold on the Title/Menu bar and try to drag the window to a different screen. Does NOT work since the last few release versions. 
3. Use Windows keyboard shortcut Alt + Spacebar to open the Window action menu -> Move -> Use arrow keys to drag the window to another screen. This workaround works fine. 

**Expected behavior**
Moving app windows across mutliple screens is typically done by clicking on Title bar of a window and dragging it to the desired screen. 

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.5.1

**Desktop (please complete the following information):**
- OS: Windows 10 21H2

**Additional context**
N/A

**Comment by mararad** [comment]
Please check https://github.com/jgraph/drawio-desktop/issues/866 and https://groups.google.com/g/drawio/c/TcikGL_aAwc/m/KrRxFZjvDwAJ

Does this help?

**Comment by veryviral** [comment]
> Please check #866 and https://groups.google.com/g/drawio/c/TcikGL_aAwc/m/KrRxFZjvDwAJ
> 
> Does this help?

It does help, thank you. 

Clearly my searching wasn't thorough enough to find that thread before.

**Comment by nicolaskarmazyn** [comment]
Hello, I had the same "issue", so thank you veryviral for the link you provided : (very easy) solution worked fine with me too

Russ solution is : 

> Right under the closing X in the upper right corner of the drawio window, you will see the double arrows/carrots/^ 's pointing down.  Click those and they will point up, and show the title bar noted above allowing you to move drawio window to another screen.  
> 
> I had the same problem and was looking at this thread when I happened to click them and it worked.
