### ISSUE TITLE
Way to hide or remove the native menu bar

### ISSUE THREAD

**Issue by nostdm** [jgraph/drawio-desktop#91]
Currently the Draw.io desktop app presents two menu bars, the web ui menu bar and the native menu bar. On MacOS it's not an issue since MacOS integrates application native menu with the title bar so its not visible unless you hover over the window title.

However, most Linux distributions don't have native menu integration like MacOS and so the user ends up seeing an extra empty menu bar which serves no purpose and takes up a significant portion of the screen.

![Screenshot](https://user-images.githubusercontent.com/16334589/54880921-68870d00-4e42-11e9-9af4-877ff659f3a3.png)

Is there an easy way to remove/hide the native menu bar from the application window or is there something that would not allow this?

**Comment by nostdm** [comment]
Seems like this should be in the main drawio repository

**Comment by chipbite** [comment]
@nostdm  - did you add this someplace else? I would love to be able to free up some screen real estate and get my display contents more focused...

**Comment by lttr** [comment]
This problem does occur on Gnome too.

**Comment by jp311** [comment]
maybe like VS Code. integrate into Window Title

**Comment by vintprox** [comment]
Indeed, this additional menu is extra distracting. Platform doesn't change the cause in this case.

**Comment by vintprox** [comment]
![image](https://user-images.githubusercontent.com/5708819/75352749-4e0fac00-58bb-11ea-9d90-ac65cb16b9fd.png)
Also, I believe removing window frame entirely and transcending window control buttons into webpage is necessary for fluent user experience. Imagine the screen with the lowest height in the world, and you have to use it while drawing another diagram in draw.io.

**Comment by Hashfastr** [comment]
![drawiodark](https://user-images.githubusercontent.com/21127811/75385009-396feb80-589c-11ea-95ec-64a7c283b7bb.png)
In i3 on Arch Linux the native menu bar has no function, maybe an option to hide the menu bar unless `alt` is pressed?

**Comment by miguelangelnieto** [comment]
Same problem on Windows version. A blank menu bar with "draw.io" string. This should be removed somehow to make the interface cleaner.

**Comment by tgram75** [comment]
I just noticed this issue as well - would be really nice to get rid of the native title bar.

It looks like Electron supports frameless windows (see [here](https://www.electronjs.org/docs/api/frameless-window)). A simple test to perform would be to augment the `options` in `createWindow` (in `drawio/src/main/webapp/electron.js`) with `frame: false` to see what happens.

I am not sure what happens to the frame with the option though. Will it loose its ability to resize?  According to the Electron doc, the minimize, maximize and close buttons will disappear so somehow that functionality would have to be added to the web title bar.

**Comment by corebots** [comment]
GNOME user here. The empty draw.io toolbar on top really looks out of place and wastes space, would be great if you could remove it. Also, an integrated headerbar which would replicate GNOME window controls would be fantastic!

**Comment by dalva24** [comment]
I found that by setting this [line](https://github.com/jgraph/drawio/blob/0e19be6b42755790a749af30450c78c0d83be765/src/main/webapp/electron.js#L675)
from `menu.setApplicationMenu(menuBar)` to `menu.setApplicationMenu(null)` hides the menu bar completely. Conditionals can then be added to maintain the application menu functionality as-is for darwin environemnts. 

It might be a good idea to move "Website" and "Check for updates" functionality to the "Help" menu, as "Support" has already existed in the "Help" menu anyways.

![image](https://user-images.githubusercontent.com/7037014/83996188-af98e980-a985-11ea-973d-dcc06d29f1a4.png)

I tried editing "Help" menu at `drawio/src/main/webapp/js/diagramly/Menus.js`, but when running `npm start`, the changes I made does not seem to take effect. I think it is caused by the app loading the minified versions at `drawio/src/main/webapp/js` instead?

How can I update the minified js to reflect changes I made to the `Menus.js`?

**Comment by raphendyr** [comment]
To hide the menu bar, two locations need changes.

Add `win.removeMenu()` after this line: https://github.com/jgraph/drawio/blob/c4871279bdfa039520cb776dfc40ca9f8f240db1/src/main/webapp/electron.js#L593

Remove/comment these two lines: https://github.com/jgraph/drawio/blob/c4871279bdfa039520cb776dfc40ca9f8f240db1/src/main/webapp/electron.js#L716-L717

That said, I think it would be beneficial to have a toggle to select where the menu is rendered (in custom app position or using native menu bar). That way, the user could use the best version for them. For example, on macOS the menu could be moved to the top panel as with any other app. In contrast, on Windows the window frame could be replaced with a custom code, which would also allow moving the close button inside the app frame, resulting more windows look'n'feel. Well, any variaton is fine as long as the native window frame is not removed on Linux.

**Comment by bjonnh** [comment]
Line 717 if I comment the two lines and add : 
````javascript
	//const menuBar = menu.buildFromTemplate(template)
	//menu.setApplicationMenu(menuBar)
	menu.setApplicationMenu(null)
````

The menu gets hidden (Gnome on Linux).

**Comment by walkafwalka** [comment]
For reference, it is not as simple as simply removing the title bar as support for window options need to be supported and there needs to be a toggle to enable/disable it. In Electron, this is called a [Frameless Windows](https://www.electronjs.org/docs/api/frameless-window#frameless-window) (see [example](https://github.com/binaryfunt/electron-seamless-titlebar-tutorial)).

**Comment by oOtroyOo** [comment]
Same issue from Windows v14.5.1 .
this issue was opend almost a year ago ,Does anyone want to fix this ?

**Comment by tlhunter** [comment]
I would love to see this feature land. Is there a bug bounty? Appearance on KDE:
![2021-06-04_13-56-50](https://user-images.githubusercontent.com/551402/120862048-22a75280-c53d-11eb-9f00-8a3e37d7ee3d.png)

**Comment by raphendyr** [comment]
@tlhunter I'm rebuilding the package locally with a minimal patch to hide the menu ([see](https://github.com/raphendyr/debian-repackaged/blob/master/drawio.modify.sh#L25)). I personally think that this is so small issue that I didn't have time to upstream the change, as I don't have time to test it on different platforms. Additioanlly, I disable update checks, as I don't want those. And I like to ensure that post/pre installation scripts don't start to do anything harmful.

Also, @walkafwalka mentioned frameless windows, which possibly might be a correct way to go. However, that does sound the wrong way to me, as it sounds like removing the decoration (which shouldn't be done of course).

**Comment by raisin8010** [comment]
This is ridiculous.

**Comment by davidjgraph** [comment]
For comments about the changes in 15.7.3 please open new issues per subject.

**Comment by tlhunter** [comment]
Interesting! It no longer uses native window borders at all. VS Code has this as an optional mode.

Here's a draw.io desktop window in front of some native windows on KDE/Linux:
![2021-11-10_22-31-44](https://user-images.githubusercontent.com/551402/141249278-c15160fa-7690-4fa4-99bb-9def63a225e8.png)

This is certainly an improvement with the screen real-estate.

**Comment by jake-brandt** [comment]
I believe this may have caused other unintended consequences. On macOS 12.0.1 (Intel), it's no longer possible to maximize the application to fullscreen mode, instead simply resizing to fill the desktop only (screen shot below showing that window chrome is still being rendered and is not full screen). It's a common macOS experience to have the maximize button actually trigger fullscreen mode, and move the app to a dedicated new virtual desktop. This allows the user to "swipe sideways" between other fullscreen applications as well as the desktop.

Happy to test any upcoming bugfix builds if your team doesn't have a Mac available for testing.

![image](https://user-images.githubusercontent.com/7774705/142559658-c1bfc731-2ddc-4b08-9a36-580beecc5c60.png)

**Comment by jake-brandt** [comment]
I want to add that I decided against opening a new issue as I'd be surprised if the latest wave of UI/UX/title bar tickets weren't all related anyway.

**Comment by davidjgraph** [comment]
Mac issue is tracked as https://github.com/jgraph/drawio-desktop/issues/774

**Comment by fgashakamba** [comment]
In Chrome, I realized that Draw.io was always opening without the traditional menu bar. It was bothering since it was taking me a while to get familiar this new interface. It might help with better management of the screen real estate, especially for those working on laptops, but it was not worth it for me to go through that learning curve. So I fiddled around and found that these steps will get you back the old menu and title bars:

```
- **Three dots** (top-right corner) -> **Settings** ->  **Configuration**.
- At the bottom-right corner of the Configuration dialog window, choose "**Preferences**".
- In the JSON-like text that oppears in the window, look for the "**ui**" key and give it the value: "**menuBar**".
- Refresh the page.
```

That's it; your menu bar is back.
In case you want to go back to the new look, go to the "**Extras**" menu and open the "**Configuration**" window from there. Then, in the **Preferences** JSON, delete the "**menuBar**" value of the "**ui**" key.

**Comment by alderg** [comment]
If you see this:
<img width="1322" alt="Image" src="https://github.com/user-attachments/assets/b00adde5-360f-4286-9632-6f45b497aeb1" />

Click on the icon on the top right (sun or moon) und untick **Simple**:
<img width="247" alt="Image" src="https://github.com/user-attachments/assets/f3063338-7c26-43d6-912a-cd1c7803d0cc" />

This will result in this:
<img width="1322" alt="Image" src="https://github.com/user-attachments/assets/e8f2c6f9-4677-48b6-bd4f-e09563285043" />
