### ISSUE TITLE
Large background shapes not congruent with diagram when using 5 mm grid alignment.

### ISSUE THREAD

**Issue by RERossel** [jgraph/drawio-desktop#912]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Large diagram elements on a page used as a background for other diagram pages do not align properly with a (5 mm) grid on the local page.

**To Reproduce**
1. Create a new blank diagram.
2. Set units to Millimeters: View --> Points --> Millimeters.
3. Set the diagram grid to 5 mm. This is important. 
4. Add a new page to the diagram + --> Page-2.
5. On Page-2 Create a non-filled 1-pt line rectangle shape 180 mm x 260 mm at position 20 mm, 20 mm.
6. Zoom in and scroll to observe that the rectangle aligns with the 5 mm grid on all four corners.
6. Go to Page-1.
7. On the diagram tab, go to background --> change... and choose Page-2 as the background for Page-1.
8. Zoom in and scroll to observe that the background rectangle does NOT align with the 5mm grid on the right and bottom.
9. The error seems to get more prominent, the more right and down we look (scaling issue due to 5 mm units?)
10. **NOTE:** The problem can be made more visible: Go back to Page-2
11. On Page-2, mark all and copy (CTRL+A, CTRL+C)
12. Go back to Page-1
13. Paste the rectangle onto the diagram.
14. Set the opacity of the pasted rectangle to 50%
15. Scroll to the lower right.
16. Observe, that the background rectangle and and pasted rectangle, which should be the exact same shape, are not exactly congruent.

**Expected behavior**
I expect the background diagram to align perfectly in all directions and distances with the current page grid.
Especially on architectural sketches of A2 or A1 portrait poster formats this can become an issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/5354214/153747825-90b497d7-5951-4159-b65c-e4ead4972828.png)
![image](https://user-images.githubusercontent.com/5354214/153747870-49d5af9c-69d5-46ea-96d3-7079c4a98395.png)
![image](https://user-images.githubusercontent.com/5354214/153748417-92c5447e-94b5-49d4-9596-d71446fb8bd8.png)
![image](https://user-images.githubusercontent.com/5354214/153748440-fbf17dab-1dd2-4f0c-9f32-ae7092e496cb.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 16.5.1

**Desktop (please complete the following information):**
 - OS: Windows
 
**Additional context**
My reference to learn about the background template feature:
https://drawio-app.com/define-background-images-in-the-draw-io-editor/
My goal is to make a large custom background box with ABCD grid coordinates and "drawn by" info as you would find it in electronics design and architectural drawings.

**Comment by hellwue** [comment]
Hey, I had a similar problem to yours. My shapes measured in mm wouldn't snap right to the grid. The thing is (my observations): The grid is not measured in the unit you choose for viewing. It is always measured in Points, whereas a Point seems to be 1/100 Inches. So to get a millimeter grid you have to go to to `Extra`->`Edit Diagram...`
Then in the first opening tag change the value for gridSize to `gridSize="3.937007874015748"`   (that is roughly 10/2.54). If you try to do this in the page setup the value will be rounded down to the nearest integer. Then your shapes should all snap to the correct mm-values. However, the rendering of the grid is not correct on all zoom levels....

Furthermore, you can also change the configuration to `{"gridSteps": 5}` to have a 5 mm grid at your hands.

Hope this helps.

**Comment by RERossel** [comment]
Hi @hellwue 

Thanks for the great advice!
This exactly solves the issue. I didn't dig deep enough into the config.

I understand that the `gridSize="3.937007874015748"` value is a per-page setting and has to be adapted for each new page within the diagram file. The configuration value `{"gridSteps": 5}` however seems to be a global setting for draw.io which changes the sub-grid partition to 5 instead of 4.
(Although I can see the usefulness of having a divisible-by-two sub-grid when aligning things.)

I my case, I'll go with `gridSize="19.68503937007874"` meaning `5 * 3.937007874015748` for the diagram setting and `{"gridSteps": 5}` for the configuration value to emulate a 5 mm grid paper.

Thank you for your help!
