### ISSUE TITLE
Suggestion: Add ability to open GitLab, GitHub, Google Drive, etc. drawio files similar to the website

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [jgraph/drawio-desktop#913]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it doesn't have the option to open a drawio file from my GitHub repository or from anywhere else.

**Describe the solution you'd like**
Implement this feature.

**Describe alternatives you've considered**
The only alternative is using the website version of it.

**Additional context**

**Comment by davidjgraph** [comment]
That's not that idea of the desktop tool. The primary goal is security, so XHR calls to wildcard domains are blocked.
