### ISSUE TITLE
Cant move window (version 16.5.1 using windows 11)

### ISSUE THREAD

**Issue by jacq-ueline** [jgraph/drawio-desktop#917]
### Preflight Checklist

* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Exactly the same issue as #773 which suggests this is fixed by earlier update but I have just downloaded 16.5.1 on windows 11 and I can make the window smaller but I cannot drag it on the main display or drag to secondary display.  All other apps are dragging without issue.

**To Reproduce**
1. Go to the top bar
2. Click on any part
3. Doesnt drag

**Expected behavior**
I would expect to be able to pick up the window and drag it around the screen and to second display

**Screenshots**

**16.5.1**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by mararad** [comment]
Please check https://github.com/jgraph/drawio-desktop/issues/866 and https://groups.google.com/g/drawio/c/TcikGL_aAwc/m/KrRxFZjvDwAJ

Does this help?

**Comment by jacq-ueline** [comment]
Yes, sorry I didnt find that other issue post.  Thank you.
