### ISSUE TITLE
Internal links do not work once the diagram is exported as a PDF.

### ISSUE THREAD

**Issue by Bruneux** [jgraph/drawio-desktop#918]
It is possible to navigate within a multi-page document by creating links.For example 3 links in the first page can take us to page 2, 3 and 4. This navigation is very useful in many situations.

However, when exporting to PDF, these internal links no longer work. Only the hyperlinks to a web page work. These links should work, especially as other diagramming tools allow this.

**Comment by Bruneux** [comment]
Sorry David, I don't understand the "issue template not filled" label. How can I fill the template please?

**Comment by Bruneux** [comment]
Can I know why this issue has been closed please?

**Comment by makingcl** [comment]
I have the same question as Bruneux. Can this item be reopened?
