### ISSUE TITLE
Make desktop icon configurable in (silent) installer

### ISSUE THREAD

**Issue by mape2k** [jgraph/drawio-desktop#924]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the solution you'd like**
The installer should offer a checkbox, the silent installer should offer parameter to disable the (re)creation of the desktop icon on installation.

**Describe alternatives you've considered**
Disable desktop icon per default in installer to make clean desktop possible.

**Comment by mape2k** [comment]
Comment to hold issue in open state

**Comment by schuelerj** [comment]
Hi, is there an update to this? We would like to roll out drawio-desktop automatically, and the desktop icon does not fit into our workflow.
Thanks

**Comment by davidjgraph** [comment]
All updates are shown in this thread.

**Comment by davidjgraph** [comment]
Desktop icon not installed bt default from 24.4.13.
