### ISSUE TITLE
Can't trim Pictures with Ellipse function

### ISSUE THREAD

**Issue by MrTeslaM3** [jgraph/drawio-desktop#925]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
If I want to Edit a Picture in draw.io I can do it but if I click on apply it do not change the Picture. So actually I can't use an ellipse or Picture with rounded edges

**To Reproduce**
1. Go to a Picture and right click -> edit picture
2. Click on "trim" and change the settings / use ellipse
3. Click on "Apply" 
4. See that the changes will not apply to the picture5. 
5. Open the "trim" Options again. You will see that the changes you have done before are still there, but still not ally to the picture on your Page.

**Expected behavior**
Normaly and I know it worked before the picture looks then exactly like in the editor

**Screenshots**
no Screenshot

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.5.1

**Desktop (please complete the following information):**
 - OS: MacOS 12.2.1

**Additional context**
Nothing - Thanks vor your support

**Comment by mararad** [comment]
At my place it is working well but I am a Win user.

Do both options fail?
Right mouse click > Edit image > Crop > Ellipse > Apply > Apply 
Right mouse click > Crop > Ellipse > Apply

Did you add PNG?
Could you attach video showing all the steps and the results? 
Do you have this issue with online version also? [diagrams.net](https://www.diagrams.net/)

**Comment by MrTeslaM3** [comment]
Sorry for my late reply.
Yes both options fail.
In the Video I used an jpeg File and try to changed it. Did not work on desktop and also did not work with the online Version.

I can not attach the File but will still attach the Video. Thanks for your support

https://user-images.githubusercontent.com/82288528/157752227-6e688ea1-e565-4889-abdc-ecd4e8c162da.mov

.

**Comment by m-mohamedin** [comment]
Thanks for the report. It will be fixed in next version (v17.1.3)
