### ISSUE TITLE
Vertical Container Text box function does not contain styling that normal text boxes do

### ISSUE THREAD

**Issue by AB-RRT** [jgraph/drawio-desktop#926]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Upon using a vertical container and selecting the text box feature, some text formatting features are not available

**To Reproduce**
1. Go to vertical container
2. Click on open area below container heading (double click)
3. Click on text feature
4. Enter 30+ character text and notice that text box does not apply word wrapping
5. Go to Text Tab
6. No option for word wrap as with normal text box

**Expected behavior**
No word wrap feature when using the text box linked to a vertical container

**Screenshots**
![image](https://user-images.githubusercontent.com/100578516/155979980-60f16398-9b82-4640-87ae-d0c901b23e67.png)
![image](https://user-images.githubusercontent.com/100578516/155980086-1fb163d4-399b-452c-9d5a-07a5cff5205a.png)
![image](https://user-images.githubusercontent.com/100578516/155980125-2fb0cac8-9ca1-47a8-b370-16fb9929a571.png)

- diagrams.net 16.5.1
 - OS: Windows

**Additional context**
I love your app and greatly appreciate the hours upon hours it's taken to produce it - for free. Thank you <3

**Comment by egrimate** [comment]
This isn't about the Vertical Container shape, but instead the textbox shape you create by double clicking. If you want to use it as other shapes, make sure you untick "autosize" (and you will need probably "resizable" set to on, too) in the Properties window in the Format panel and tick "word wrap" in the Text tab in the Format panel too.

**Comment by AB-RRT** [comment]
Thank you!
