### ISSUE TITLE
Draw.IO Desktop App not working on New Macbook M1 Max for the OS Monterey (Apple M1 Max) Version 12.2.1

### ISSUE THREAD

**Issue by pavany666666** [jgraph/drawio-desktop#929]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Draw.IO (Multiple Versions) desktop application displays Blank Window without any options to do anything. In short, the desktop app is unusable.

**To Reproduce**
1. Go to Applications on Mac M1 Max, Open the draw.io App
2. Try to find any options to do any basic operations like create, open etc.

**Expected behavior**
All the draw.IO options available on other Macbooks should be available up and running.

**Screenshots**
![image](https://user-images.githubusercontent.com/55155030/156583920-d2104916-9459-4246-9708-ec831ca186ee.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 16.5.1, 16.4.11

**Desktop (please complete the following information):**
 - OS: MacOS Monterey (Apple M1 Max) Version 12.2.1

**Additional context**
This is happening only on Mac Universal Installer and didn't happen for M1 specific installer = draw.io-arm64-16.5.1.dmg

**Comment by davidjgraph** [comment]
Does 18.0.1 ARM version work?

**Comment by pavany666666** [comment]
yes. I was using arm 16.5 before and now upgraded to 18.0.1 which seems to work well so far.
