### ISSUE TITLE
Character encoding / possible file type issue; when saving / opening a file through the GUI low-priority* 

### ISSUE THREAD

**Issue by Kstuart1992** [jgraph/drawio-desktop#930]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When saving / opening an existing file - from my file system [on Fedora 35 Workstation] all I see (for text) is the rectangular blocks and some out of place icons, usually associated with an issue of character encoding issues. When saved - I will type a file name, it works as expected, but does not apply r-w or a file extension of any kind. I only see the usual xml as expected in a plain text file. No other issue to speak of. Within the application itself, all looks rather nice.

**To Reproduce**
1. Go to '...'  : -----------------------| Save As / Open ... within the application UI 
2. Click on '....' :---------------------| See above
3. Scroll down to '....' :-------------| See above
4. See error : ------------------------| No error other then a possible character encoding issue and file type appendage

**Expected behavior**
Seeing the general text is plain readable characters and once saved the file to be formatted to open to the appropriate program, under the file type that is utilized by your application 

**Screenshots**
![Screenshot from 2022-03-06 19-16-36](https://user-images.githubusercontent.com/80655766/156948742-f859f061-67da-42e8-911e-5b14fc5f57e2.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net 16.5.1 <- from snap repository 

- draw.io version x.y.z
- 16.5.1

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, Linux...
OS: Linux, Distro: Fedora 35 Workstation, WS: Wayland, 64-bit 

**Additional context**
To be honest - I don't mean this as a complaint, if someone can just point me to the right direction. I know the download package from snap means I am most likely going to need to uninstall and doing what I should have (I was lazy - need to jump on a project this would help with) and build from source by forking from here etc. but in order to avoid a similar issue / possibly provide a patch, any ideas on where I would go in the repository to see what may have gone wrong - if that is even applicable. I also didn't want to say nothing and uninstall / reinstall without reaching out if it can avoid issues for others or yourselves. 

So any insight would be great, I'll browse a bit myself, but I'm not sure if this would be on the packaging management side either and should be forwarded to snap. If sorry I apologize for sounding any alarms. - All my best -

**Comment by Kstuart1992** [comment]
![Screenshot from 2022-03-06 19-22-48](https://user-images.githubusercontent.com/80655766/156949060-70389e5a-b8b2-4efe-9f9b-6cbbbce35b5e.png)
This is the issue as described - my apologizes I added the log screenshot there and meant these to be in the opposite place. - Thanks again !

**Comment by davidjgraph** [comment]
Duplicate #368

**Comment by Kstuart1992** [comment]
Thank you I'll go check that out !
