### ISSUE TITLE
Version 16.5.1 doesn't work correctly on multiple Windows 10 monitors

### ISSUE THREAD

**Issue by RJM61** [jgraph/drawio-desktop#931]
### Preflight Checklist
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
* Well actually a few people have reported it but the issue has been closed because the Preflight Checklist has not been filled in. 

**Describe the bug**
Version 16.5.1 does not work on Windows 10 when multiple monitors extend the desktop. It only works correctly  on Monitor 1.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the application
2. Click on the window square button (top right) till one square is shown.
3. Try and drag the window to a different monitor - it doesn't work.
4. Alternatively, reduce the window size (top right and bottom left) and drag the window to a different monitor. Once completely in a new window click the square button and it  will move to the other monitor.

**Expected behaviour**
1. Launch the application
2. Click on the window square button (top right) till one square is shown.
3. Drag the window to a different monitor.
4. when mostly in the bounds of the new monitor clicking the square button should maximise screen size to totally fill the monitor.

**Screenshots**
Not required. Only needs the above description.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.5.1

**Desktop (please complete the following information):**
 - Windows 10 64 bit.
 - Edition	Windows 10 Business
Processor	Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Version	21H2
Installed on17/‎03/‎2021
OS build	19044.1566
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Additional context**
Probably somthing you don't regression test.
It used to work with previous versions.

**Comment by mararad** [comment]
Please check https://github.com/jgraph/drawio-desktop/issues/866 and https://groups.google.com/g/drawio/c/TcikGL_aAwc/m/KrRxFZjvDwAJ

Does this help?
