### ISSUE TITLE
Necesito recuperar archivo

### ISSUE THREAD

**Issue by Mamnuelajp** [jgraph/drawio-desktop#936]
Hola 
He guardado un archivo PDF encima de otro por error

¿Cómo puedo recuperarlo?

**Comment by mararad** [comment]
Hi,

Where did you store the file, please? How did yo get PDF? Was it via File > Export as > PDF?

If yes, try to drag&drop the file into the canvas directly. If "Include copy of my diagram" was ticked when exported, the file should be editable again.

Regards,
