### ISSUE TITLE
Not a diagram file (error on line 1 at column 11: error parsing attribute name)"

### ISSUE THREAD

**Issue by NoiGS2015** [jgraph/drawio-desktop#937]
**Describe the bug**
I was going to use my diagram and this now popped up anytime I try to open it:
Error loading file - Not a diagram file (error on line 1 at column 11: error parsing attribute name)

It happens on the desk app and the browsers, It worked perfectly before, don't know what's happening.
If you can help me I'll thank you eternally, that's an urgent file to me!

draw.io version 16.5.1 (desk app)
I'm on Windows 10 Pro
[DqD.zip](https://github.com/jgraph/drawio-desktop/files/8226098/DqD.zip)

**Comment by mararad** [comment]
Hi,

The file is partly corrupted, not sure why this happened. Did you save it locally? 

If yes, could you check if you able to find ~${FILENAME}.bkp in the system or other file versions?

Meanwhile, I managed to recover a part of the file (you'll see 4 separate diagram pages)

[user file.zip](https://github.com/jgraph/drawio-desktop/files/8243895/user.file.zip)

**Comment by NoiGS2015** [comment]
Broooooo!! Thank you a lot for your help and response!

No, I had it in a cloud, I have the Google Drive desktop thing that sync your cloud in your pc like another drive, I did had it in my desktop but a long ago, the past year I think. And I periodically pass a cleaner on my pc.
I'll try searching it anyways. I tried to look older versions but seems like it didn't saved any. I'm scared.
Btw, thanks for your work at recovering, you managed to one of the three sheets that I needed. In case that I don't find anything, Do you think it is possible to fully recover it? (And if it's possible, do it by myself to not annoy you? I imagine it's not easy.)

**Comment by NoiGS2015** [comment]
Didn't find anything... ˚‧º·(˚ ˃̣̣̥⌓˂̣̣̥ )‧º·˚

**Comment by NoiGS2015** [comment]
Hi man. Glad to say my partner managed to save a back up, an oldie with some outdated things but the one you recevered helps to that.
Man! Thank you! My best wishes for you!

**Comment by Thach2001-git** [comment]
[NRF.zip](https://github.com/user-attachments/files/17971689/NRF.zip)
I got the same issue, Can you help me to check or restore it? I need it urgently :((
