### ISSUE TITLE
Blank window using Flathub Flatpak 16.5.1 on Fedora Silverblue 35 with Wayland

### ISSUE THREAD

**Issue by shoop** [jgraph/drawio-desktop#938]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When running the draw.io desktop app installed from Flathub I get a completely blank window.
Somehow it seems to respond to interaction, e.g. when I click on top right corner it closes and when I randomly click in topleft corner I get redirected to "get.draw.io".

**To Reproduce**
1. Install flatpak of draw.io from Flathub, https://flathub.org/apps/details/com.jgraph.drawio.desktop
2. Run it
3. See error

**Expected behavior**
I expected the user interface of the application.

**Screenshots**
![image](https://user-images.githubusercontent.com/851341/158185254-73d20ec9-7b1e-46b8-b9d0-ca49813dc839.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
I cannot see the help, but this is the 16.5.1 stable flatpak version.

**Desktop (please complete the following information):**
 - OS: Linux, Fedora Silverblue 35

**Additional context**
Please ask if needed.

**Comment by shoop** [comment]
Update: removing the GPU acceleration permission (device=dri) using Flatseal helped, this allows me to use the app.
Possibly this is connected to running with the official nvidia driver for 3D acceleration?
Other flatpaks work just fine though.

**Comment by davidjgraph** [comment]
Could you check with 17.x please?

**Comment by shoop** [comment]
No change, unfortunately.

![image](https://user-images.githubusercontent.com/851341/161153695-d28f4005-0fa5-466b-9ee5-780dbcd3301e.png)

**Comment by davidjgraph** [comment]
Hard to say. We've no experience of Flathub, so don't know if the binary is altered. Have you tried one of the builds we create -> https://get.draw.io

**Comment by DSeeLP** [comment]
I have the same issue on Fedora 36 with Wayland with version `17.2.4`. Removing the `device=dri` permission works.
The AppImage and rpm build works for me.

**Comment by davidjgraph** [comment]
We're not the authors of the Flathub version.
