### ISSUE TITLE
electron modifiable url parameters

### ISSUE THREAD

**Issue by bernatesquirol** [jgraph/drawio-desktop#94]
Wouldn't it be nice if the [url parameters](https://desk.draw.io/support/solutions/articles/16000042546-what-url-parameters-are-supported-) could be specified in the electron app, stored as user data, and remembered next time the user uses the app?

**Comment by davidjgraph** [comment]
I would say the convention for this is to create environment variables/a shortcut that passes the parameters each time. Having an application remember the state of the last run doesn't sound right to me.
