### ISSUE TITLE
drawio fails on ubuntu 20.04 - cannot save files and corrupts files

### ISSUE THREAD

**Issue by gvoss** [jgraph/drawio-desktop#941]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
on ubuntu `20.04` snap automatically updated `drawio` to the latest version `17.1.5   144  latest/stable` and it is unable to save changes that are made to diagrams and it is corrupting diagram files.

**To Reproduce**
0. be on ubuntu `20.04 LTS`
1. install `drawio` via snap: `sudo snap install drawio`
2. launch `drawio`
3. open an existing diagram
4. edit the diagram and save
5. see the error `EINVAL: invalid argument, write` in the UI and in the console:
```
[Error: EINVAL: invalid argument, write] {
  errno: -22,
  code: 'EINVAL',
  syscall: 'write'
}
```

**Comment by gvoss** [comment]
Screengrab:
![drawio-bug](https://user-images.githubusercontent.com/7536636/159721886-0668a4e6-375b-4cb9-a640-de250157c5a8.gif)

**Comment by gvoss** [comment]
Things I have tried that have not fixed the problem:

1. remove local diagram files and re-clone the project they live in via git (incase some weird file permissions)
2. open different documents from the ones I was editing recently (like an old diagram from last year)
3. create a new `drawio` document in a different folder like `/tmp` (as shown in the screengrab)
4. revert `drawio` version via snap (this failed to open for some reason, the console hinted that for some reason some dependency got lost, im not an expert at `snap` so assumed `PEBKAC`)
5. completely uninstall `drawio` snap and then reinstall (screengrab above shows the result of this too)

**Comment by hasnimehdi91** [comment]
I am facing the same issue

**Comment by davidjgraph** [comment]
Please update to 17.2.1

**Comment by gvoss** [comment]
Thank you!  I used it all day yesterday and it worked perfectly.
