### ISSUE TITLE
Drawio desktop (Windows) release 17.2.1 (and 17.2.4) extremely slow to launch

### ISSUE THREAD

**Issue by cvillerm** [jgraph/drawio-desktop#944]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

After being prompted to to update my draw.io Windows desktop version 16.5.1 to the new 17.2.1 version (using the windows installer version), I found that this version is soooo slow to start. After a while, it displays the welcome border, then several minutes later the welcome screen and this is still very unresponsive afterwards. I had to kill it after several minutes. Restarting my PC didn't change this behavior.

I didn't see unusual CPU or I/O usage while waiting.

I reverted to 16.5.1, working fine.

**To Reproduce**
1. Start drawio and wait and wait...

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.2.1

**Desktop (please complete the following information):**

 - OS: Windows 10

**Additional context**

**Comment by davidjgraph** [comment]
I couldn't repeat this. Do you know which binary you installed?

**Comment by cvillerm** [comment]
Yes, this is https://github.com/jgraph/drawio-desktop/releases/download/v17.2.1/draw.io-17.2.1-windows-installer.exe

**Comment by cvillerm** [comment]
And I tested again reinstalling 17.2.1 and starting it. I had to kill it after several minutes. Installing again 16.5.1 (from https://github.com/jgraph/drawio-desktop/releases/download/v16.5.1/draw.io-16.5.1-windows-installer.exe) works fine without any performance issue.

**Comment by kentLee170** [comment]
same on my side, version 17 totally not able launch after prompt update, i have to uninstall 17 and manually install 16.5

**Comment by cvillerm** [comment]
And, by the way, I am experiencing the same slowness with the [no-installer version](https://github.com/jgraph/drawio-desktop/releases/download/v17.2.1/draw.io-17.2.1-windows-no-installer.exe)

**Comment by eupraxis1981** [comment]
same here -- so slow it's unusable.

**Comment by davidjgraph** [comment]
We can't repeat this. We need to work out what is different in your setups to ours. Do you have local JSON config set? Any non-default settings in the 16.5 app?

**Comment by tangerine2003** [comment]
> same here -- so slow it's unusable.

It started happening with the install of 17.2.1. See the below system info. Let me know what information I can provide to help with diagnosis.

System information: Windows 10 Enterprise
Version: 21H2
OS Build: 19044.1586

Processor: 11th gen i7 3.00 GHz
RAM: 32 GB

**Comment by cvillerm** [comment]
Links:
------
[1]
https://github.com/jgraph/drawio-desktop/issues/944#issuecomment-1079641079
[2]

**Comment by eupraxis1981** [comment]
> We can't repeat this. We need to work out what is different in your setups to ours. Do you have local JSON config set? Any non-default settings in the 16.5 app?

Nope — just installed with the windows installer in both cases

**Comment by eupraxis1981** [comment]
Here's my system info:

- Windows 10 Enterprise 10.0.19042 Build 19042
- LENOVO_MT_20QE_BU_Think_FM_ThinkPad X1 Carbon 7th
- Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, 2112 Mhz, 4 Core(s), 8 Logical Processor(s)
- 16GB RAM

**Comment by davidjgraph** [comment]
2 x Windows 10 Enterprise. @cvillerm is yours Enterprise?

**Comment by cvillerm** [comment]
Yes, same for me Windows 10 Enterprise 20H2, build 19042.1586

**Comment by cvillerm** [comment]
What is very strange is that I don't have any longer a performance problem today after running it (v17.2.1), using the installer-based version.
Yesterday and the day before yesterday, I always had problems with this version and I was restarting Windows several times in between my tests.

**Comment by cvillerm** [comment]
This is still working today without any performance issue. I am not sure what uninstall/install caused this to work again, but my current installation is based on draw.io-17.2.1-windows-installer.exe. Even when using draw.io-17.2.1-windows-no-installer.exe, this works fine too. These 2 configurations were not working well (i.e. very slow start) before.

I am leaving this issue open anyway as other are (were?) impacted.

**Comment by davidjgraph** [comment]
Thank for the details. It's hard to say without having a test win 10 enterprise version. We'll try releasing with an updated electron-builder, since the version we used is a little older due to a different issue.

**Comment by cvillerm** [comment]
As I found that v17.2.4 was available, I installed it ([draw.io-17.2.4-windows-installer.exe](https://github.com/jgraph/drawio-desktop/releases/download/v17.2.4/draw.io-17.2.4-windows-installer.exe)), and this is again very slow to launch. I tried installing back draw.io-**16.5.1**-windows-installer.exe and this worked fine (no slow start). Installing again either **v17.2.4** or **v17.2.1** is taking again ages when launching it. Starting in "admin mode" doesn't change anything.

I reverted to v16.5.1.

By the way, after waiting several minutes when launching **v17.2.4** and then selecting to create a new blank diagram, while this is taking again ages, I monitored the process using SysInternals Process Monitor and this is looping internally with these accesses, with several delays of several seconds:

![image](https://user-images.githubusercontent.com/9128625/160556387-ce5de336-897c-4ac5-8e75-5c3edd11d6e1.png)

Edit: I observe the same "loops" (24 in total) after clicking on "Create" with a "Blank Diagram" using **v16.5.1**, but there are no such long delays (e.g. 7s) within each loop:

![image](https://user-images.githubusercontent.com/9128625/160556547-7047962f-9bab-42c5-a481-5d8c6e4fd9d7.png)

**Comment by julienbrunet** [comment]
> As I found that v17.2.4 was available, I installed it ([draw.io-17.2.4-windows-installer.exe](https://github.com/jgraph/drawio-desktop/releases/download/v17.2.4/draw.io-17.2.4-windows-installer.exe)), and this is again very slow to launch. I tried installing back draw.io-**16.5.1**-windows-installer.exe and this worked fine (no slow start). Installing again either **v17.2.4** or **v17.2.1** is taking again ages when launching it. Starting in "admin mode" doesn't change anything.

Exactly the same behaviour here, with the same config (windows 10 enterprise 20H2 build 19042.1586).
Everything was working fine with version 16.5.1.

**Comment by davidjgraph** [comment]
OK, next thing with be a build with Electron 18. We're tight on time right now with work, so stick with 16.5.1 until that's out.

**Comment by LeopoldLerch** [comment]
having the same issue here too. 17.4.2 is way the slowest one, 17.2.4 seems to be a bit faster, but all too slow (not even the "loading"-circle shows animations). 
Reverted back to 16.5.1, which works like a charme.

Im on Win10 Enterprise, 20H2, 19042.1586

i7 @ 2,6 GHz, 16 GB RAM (altough system never exhausted).

**Comment by kkayal** [comment]
Just to confirm that I have the same issue with 17.4.2 just like LeopoldLerch with the same setup. The CPU Load is low. It feels like something is blocking, which is not the case for version 16.5.1

**Comment by davidjgraph** [comment]
Could someone re-try with 18.0.1 please?

**Comment by cvillerm** [comment]
I just installed the "Windows installer" version of 18.0.1 and this is still very very slow to start.

**Comment by davidjgraph** [comment]
Could you try with windows defender disabled please?

**Comment by cvillerm** [comment]
On my side, I cannot disable it as this is an enterprise-managed feature.

**Comment by danielcalvogonzalez** [comment]
I can confirm the same behaviour with Windows Enterprise in my computer. It was runnng fine till I updated to the last version when I experienced the same sluggish response.

No matter what I tried, it was working very slow.

After reading this thread I went back to version 16.5.1 and now everything runs as it should be.

Hope this helps.

**Comment by davidjgraph** [comment]
If anyone is able to test with disabled Windows Defender, that's one of our two currect main theories.

The other one is described in https://stackoverflow.com/questions/40482406/electron-nw-js-slow-startup-time-2-minutes-on-windows. We're wondering if the app update request to github is being blocked on a timeout.

Anyone able to test either of these would be helping us out. We don't have a Windows Enterprise setup to test this with.

**Comment by cvillerm** [comment]
What is very strange is that yesterday and today, after reinstalling the "Windows installer" version of 18.0.1, performance is again Ok. This happened to me before with a previous "new" version, but performance degraded again later. I will try again several times.

**Comment by danielcalvogonzalez** [comment]
> If anyone is able to test with disabled Windows Defender, that's one of our two currect main theories.
> 
> The other one is described in https://stackoverflow.com/questions/40482406/electron-nw-js-slow-startup-time-2-minutes-on-windows. We're wondering if the app update request to github is being blocked on a timeout.
> 
> Anyone able to test either of these would be helping us out. We don't have a Windows Enterprise setup to test this with.

Unfortunately, my company don't allow me to change Windows Defender behaviour so I can't test what you propose.

Sorry.

**Comment by sorin-costea** [comment]
Same issue here with 18.0.6, again Windows 10 Enterprise and unable to disable Defender.

**Comment by davidjgraph** [comment]
Could someone measure the exact startup time please and post it? I wonder if it's the Github update check that's timing out.

**Comment by sorin-costea** [comment]
Approximative times:
40s the window is black
30s the window is white
50s the window displays the namechange text and loading
then we're at the "create/open" dialog. "Open" reacts immediately with the file chooser, while "create" needs another 30s to open its popup and another 10s to actually draw its contents (the sample diagrams).

**Comment by sorin-costea** [comment]
PS: canceling that dialog needs 50s to get to the main screen. Then just opening the Help menu needs another 20s.

Basically, unusable.

**Comment by davidjgraph** [comment]
Sounds like defender / other scanning then. Anyone getting this and not on Windows 10 Enterprise?

**Comment by sorin-costea** [comment]
Okay, then excluding its folders from Defender scanning:

- C:\Users\youruser\AppData\Roaming\draw.io
- C:\Program Files\draw.io

restores the reaction time. A good workaround for me, thank you for pointing to the right place.

**Comment by davidjgraph** [comment]
@sorin-costea  Cool, thanks. Glad someone finally tested this.

We'll look whether we can submit to MS to add an exclusion for the app, meantime I assume yours is the best workaround.

**Comment by cvillerm** [comment]
I confirm that, although the performance of draw.io 18.0.1 has been more acceptable for me for the last 10 days (without any reason, after taking ages), excluding the above folders in Defender makes it start very quickly.
