### ISSUE TITLE
Drawio Desktop Windows 17.2.4 Expand Collapse Not Working

### ISSUE THREAD

**Issue by NixonUey** [jgraph/drawio-desktop#946]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Collapse / Expand objects no longer respond. The - or + shows in the upper left corner, but clicking on them does nothing.

**To Reproduce**
1. Open drawing or create new drawing.
2. Make sure Extras - Collapse/Expand is selected.
3. Add collapse/expand object to drawing, such as General - List.
4. Click on collapse (minus sign) in upper left corner. Nothing happens.

**Expected behavior**
Clicking on collapse/expand toggle should collapse or expand the object.

**Screenshots**
N/A

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.2.4

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
N/A

**Comment by NixonUey** [comment]
I uninstalled all plugin's and functionality returned. Not sure which plugin was causing the problem.

**Comment by mjk-gh** [comment]
I had the same problem with the current 20.2.3 release under Linux (AppImage).
The plugin that seems to cause the collapse/expand feature to fail is called "**trees**", deleting it made the collapse/expand feature work again.

**Comment by ForbiddenEra** [comment]
> I had the same problem with the current 20.2.3 release under Linux (AppImage). The plugin that seems to cause the collapse/expand feature to fail is called "**trees**", deleting it made the collapse/expand feature work again.

Same here on `21.4.0`, your comment saved the day.

**Comment by ottowayi** [comment]
this is still an issue in v27.0.9 on Windows 11
