### ISSUE TITLE
Incorrect Japanese translation in the export settings. 

### ISSUE THREAD

**Issue by suikan4github** [jgraph/drawio-desktop#948]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
A translation from English to Japanese is wrong. The English word "Border with" is translated to "枠線の太さ" in Japanese. But it should be "余白の広さ".

This mistranslation comes from the ambiguity of the word "border". The "border" in the drawer desktop means "margin". The current Japanese translation takes it as "borderline". 

**To Reproduce**
1. Go to ''File -> Export as ... -> Advanced ... "
2. See the "Border Width" at the bottom. 

**Expected behavior**
In the Japanese translation, it is displayed as "枠線の太さ" incorrectly. It should be corrected as "余白の広さ"

**Screenshots**
![Untitled Diagram drawio](https://user-images.githubusercontent.com/26223147/161407848-92ce372c-a3b0-48d0-bacf-9dffad10ba35.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.2.4

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS

**Additional context**
To change the Japanese translation, click the top-right globe icon and chose "日本語"
![Screenshot from 2022-04-03 10-59-33](https://user-images.githubusercontent.com/26223147/161407928-56e306c6-999e-43e3-a973-51297f2950af.png)

**Comment by davidjgraph** [comment]
I've corrected the entry in https://docs.google.com/spreadsheets/d/1FoYdyEraEQuWofzbYCDPKN7EdKgS_2ZrsDrOA8scgwQ. That will go into the next release. Many thanks for the report.

**Comment by suikan4github** [comment]
Thank you for fixing :+1:
