### ISSUE TITLE
Cloud Sync from Desktop

### ISSUE THREAD

**Issue by analyticsdept** [jgraph/drawio-desktop#950]
* [ Y ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ Y ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
It's difficult to share files created on the desktop version with collaborators, and for various reasons, the desktop app is preferable (no requirement for constant connect, etc)

**Describe the solution you'd like**
Ideally, I'd like to be given the same options to save to a specific location, whether local or cloud, as in the web version. I like the idea of managing it like a repo - automatic saves are handled like commits (stored locally) until a push happens. Also aware, however, that for most users the automatic push / saves to cloud would be a great help.

**Describe alternatives you've considered**
Manually uploading the .drawio file to Google Drive - it works, but is a messy process

**Additional context**
None; thanks for the great app!

**Comment by davidjgraph** [comment]
The scope of the project is defined specifically in https://github.com/jgraph/drawio-desktop#readme. Anything with remote access would have to be a fork of this project.

**Comment by analyticsdept** [comment]
> The scope of the project is defined specifically in https://github.com/jgraph/drawio-desktop#readme. Anything with remote access would have to be a fork of this project.

Got it, thanks!
