### ISSUE TITLE
Adding external two or more icons in the Scratchpad

### ISSUE THREAD

**Issue by abelpc** [jgraph/drawio-desktop#951]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I often add/import external icons into my Scratchpad. I have been using draw.io Desktop standalone application (macOS/ARM), right now version 17.2.4.

The problem is that when I add one icon/image (JPEG/PNG), [draw.io](http://draw.io/) displays it in the Scratchpad correctly, and I can then add it to my diagram. 
However, when I add a second (or third, fourth...) icon, they are not displayed at all. If I try re-adding the same icon again, the application complains that the icon already exists and has already been added.

The way to visualize/display the icon, is to close and re-open the whole application, which is very cumbersome when you are adding multiple external icons.

**To Reproduce**
1. Go to the Scratchpad and click on the 'Pencil' sign
2. Then either click on 'Add Images' or on 'Import'
3. Find, select, and add a JPEG/PNG icon
4. The icon will be displayed correctly
5. Then, repeat steps 1 to 3
6. This time, the icon is not displayed
7. If you try to re-add the same icon (Steps 1-3), the application complains the icon has already been added

**Expected behavior**
No matter how many icons one adds, or at what order one adds them, icons should always be displayed if they are added.

**Screenshots**
N/A.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.2.4

**Desktop (please complete the following information):**
 - OS: MacOS (ARM CPU)...

**Additional context**
N/A.

**Comment by bdleedy** [comment]
I have the same issue. I'll add that restarting the app does not 'refresh' the Scratchpad or make the image appear.
