### ISSUE TITLE
The desktop version should supports plantuml import  

### ISSUE THREAD

**Issue by hanbing5210** [jgraph/drawio-desktop#952]
This is currently supported only by the Web version and hopefully also by the desktop version

**Comment by davidjgraph** [comment]
External data transmission is outside of the scope of the project, see the main README section on security.

**Comment by hanbing5210** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by davidjgraph** [comment]
Adds client-side PlantUML parser in 30.3.6.
