### ISSUE TITLE
17.4.2 Crashing When Shape Added/'Create New Diagram' Selected

### ISSUE THREAD

**Issue by Will-stack11** [jgraph/drawio-desktop#955]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
App crashes as soon as a shape is interacted with or when "Create New Diagram" is selected on startup.

**To Reproduce**
1. Launch applicaiton
2. Either
    2.1 Close dialoge and attempt to add a shape to the canvas
    2.2 Click on "Create New Diagram"

**Expected behavior**
Application continues to run.

**Screenshots**
n/a

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.4.2

**Desktop (please complete the following information):**
 - OS: Windows 11 Home

**Additional context**
- This issue started imediately after installing 17.4.2
- Have alreday tried restarting the machine and reinstalling version 17.4.2

**Comment by davidjgraph** [comment]
Which binary did you install?

**Comment by Will-stack11** [comment]
> Which binary did you install?

I used "draw.io-17.4.2-windows-installer.exe"

**Comment by davidjgraph** [comment]
Maybe a hardware error with electron. Maybe try 17.2.4 and switch off updates.

**Comment by Will-stack11** [comment]
> Maybe a hardware error with electron. Maybe try 17.2.4 and switch off updates.

I've reinstalled this version (17.2.4) and it's working fine.

**Comment by rackomint** [comment]
Was having the same issue. Re-installing fixed the problem.

**Comment by johnluecke** [comment]
Experienced the same issue. Reverting to 17.2.4 prevents draw.io from crashing on Windows 10 Enterprise when adding new objects.

**Comment by rackomint** [comment]
> Was having the same issue. Re-installing fixed the problem.

Re-installing did not fix the problem. Crashes still occur

**Comment by davidjgraph** [comment]
We've had stability issues on Windows with recent electron builds, with a small number of users. Probably some of the issue is in our code, but we've not been able to reproduce the issues. If you're a VSCode user, you might consider the plugin there, https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio. That hasn't suffered from these issues.

**Comment by davidjgraph** [comment]
Note that the version in the windows store is still 17.2.x, https://apps.microsoft.com/store/detail/drawio-diagrams/9MVVSZK43QQW

We hold back on updating that version to see if users get any issue on our binary releases. There have been reports on 17.4.x, so the windows store is better for stability.

**Comment by davidjgraph** [comment]
Could someone try 18.0.1 please?
