### ISSUE TITLE
Draw.io v17.4.2 unable to move Window

### ISSUE THREAD

**Issue by kstephen00** [jgraph/drawio-desktop#956]
### Preflight Checklist

* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**

**To Reproduce**
1. Attempt to Drag or Alt+Spacebar to move
2. Window will not Move

**Expected behavior**
Able to move/drag the WIndow from one screen/monitor to another

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.4.2

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by mararad** [comment]
Please check https://github.com/jgraph/drawio-desktop/issues/866 and https://groups.google.com/g/drawio/c/TcikGL_aAwc/m/KrRxFZjvDwAJ

Does this help?

**Comment by kstephen00** [comment]
Perfect, thanks!

Thank you,

Kirk

Kirk Stephenson | Merchandising Systems
Kroger Technology & Digital | The Kroger Co.
office: 513.864.7870 cell: 513.508.7517
***@***.***
