### ISSUE TITLE
Application Crashed

### ISSUE THREAD

**Issue by bisnukundu** [jgraph/drawio-desktop#959]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I have some components and I am trying to make a group but when I select and click group then it's crashed.

**To Reproduce**
1. Go to my document
2. select some components and try to make a group
4. See an error

**Expected behavior**
It should after selecting and clicking group makes a group.

**Screenshots**
![image](https://user-images.githubusercontent.com/48401689/163463937-3ea60efb-463d-4201-9abd-3914308f3c5e.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.4.2

**Desktop (please complete the following information):**
 - OS: Windows.

**Additional context**

**Comment by davidjgraph** [comment]
We've had stability issues on Windows with recent electron builds, with a small number of users. Probably some of the issue is in our code, but we've not been able to reproduce the issues. If you're a VSCode user, you might consider the plugin there, https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio. That hasn't suffered from these issues.

**Comment by davidjgraph** [comment]
Note that the version in the windows store is still 17.2.x, https://apps.microsoft.com/store/detail/drawio-diagrams/9MVVSZK43QQW

We hold back on updating that version to see if users get any issue on our binary releases. There have been reports on 17.4.x, so the windows store is better for stability.

**Comment by davidjgraph** [comment]
Could someone try 18.0.1 please?
