### ISSUE TITLE
Logo in SVG format

### ISSUE THREAD

**Issue by ghisvail** [jgraph/drawio-desktop#96]
It would be nice to have a version of the logo in a scalable format like SVG instead of a high-res PNG. This would facilitate the generation of thumbnails downstream such as for Flatpak.

**Comment by davidjgraph** [comment]
Where would you want in the folder structure?

**Comment by ghisvail** [comment]
Under `build/icon.svg` maybe?

**Comment by davidjgraph** [comment]
Added.
