### ISSUE TITLE
CORS stops HTTP from plugin

### ISSUE THREAD

**Issue by maarnold2** [jgraph/drawio-desktop#960]
I am writing a plugin to install in the drawio Desktop to fetch drawio XML from a REST service that I wrote. The requests seem to be blocked by CORS. I have tried without success fetch(), XMLHttpRequest, window.open(), ui.showDialog(). From web research, it would appear that I would need to modify the electron main app js; but, I would rather not re-build the drawio desktop. I read an old drawio github issue reporting the same problem; but that issue was closed without a solution. I cannot find that issue any more. I saw that the Confluence plugin has configuration properties to get around the CORS block. How do they do it?

OS: Windows 10
Drawio desktop version 17.4.2

thanks,
Mark Arnold
maarnold@speakeasy.net

**Comment by m-mohamedin** [comment]
Hi,
Sorry, I don't understand. If it is your service, you can allow all in the CORS header without changing the app itself

**Comment by maarnold2** [comment]
Mohamed,

I’ve tried that. Something in the render side of drawio desktop does not allow it. It seems that my plugin runs in the render space of the desktop client. I would need to be able to initiate the download from within the server side of the desktop client in order for it to be a server-to-server request where CORS does apply.

Thanks,

Mark a.

**Comment by m-mohamedin** [comment]
I understand now, this is most probably due to our default "Content-Security-Policy" which restrict connecting to other services. Also, plugins can only run in the renderer process.

**Comment by maarnold2** [comment]
Mohamed,

Thanks for your response.

You wouldn’t happen to know how the Confluence plugin gets around this, would you?

Is there a way the render process can post a request to the server process?

Consider implementing an “Add Add-in” option that injects an add-in into the server process.

Thanks,

Mark a.

**Comment by davidjgraph** [comment]
The confluence plugin uses different integration code, this CSP is specific the desktop build.

If you want custom comms to an external server the desktop codebase is not the place to start, unless you understand the security model and CSP in detail.

**Comment by maarnold2** [comment]
David,

It is an in-house application, not public. I would rather it be the desktop than a web server. I understand the implications.

Please advise on how Confluence did it.

Thanks,

Mark a.
