### ISSUE TITLE
Error loading file | Illegal constructor

### ISSUE THREAD

**Issue by elca-maxime-gamboni** [jgraph/drawio-desktop#964]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
A specific file won't open on 17.4.2 and 17.2.4, but works fine on 17.2.1

**To Reproduce**
1. Attempt to open the file (see "additional context" below), either by double-clicking on it, or with File > Open, or with the "Open Existing Diagram" button in the startup popup.
2. I can see a faint outline (shapes but no text) of the diagram, and a pop-up "Error loading file", "Illegal constructor" appears, with just an "Ok" button.

**Expected behavior**
The file should open successfully, like it does on version 17.2.1

**Screenshots**

![image](https://user-images.githubusercontent.com/95483008/164427261-ac3ae6d7-6a45-4291-8fd6-bf29624ab887.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.2.4 or 17.4.2

**Desktop**
 - OS: Windows 10 Enterprise 20H2. 64-bits operating system, x64-based processor

**Additional context**

I can't post the file publicly. Can you provide me with an e-mail or other means to transmit it privately? Thank you!

**Comment by davidjgraph** [comment]
support@diagrams.net. Please link this thread in your email.

**Comment by m-mohamedin** [comment]
Thanks for the report. The bug will be fixed in the next release.
Currently, please use the online version to open this diagram

**Comment by davidjgraph** [comment]
Sorry, we have reverted this change. The problem here is the diagram contains shape(s) created with a faulty plugin (C4). This plugin is not written correctly, I don't want to change the codebase to allow for a bug in third-party code. The place where the fix is needed in a critical function and changing it is very risky.

To fix the issue you need to open the diagram in app.diagrams.net, delete the shapes created with the C4 plugin and replace them with the C4 shapes built into the application.

**Comment by elca-maxime-gamboni** [comment]
Ok thanks a lot for the analysis. We will do as you suggest.

Have a nice day!
