### ISSUE TITLE
"Error loading file", "Not a diagram file (error on line 1 at column 1: Document is empty)", on plain start of application

### ISSUE THREAD

**Issue by apboon** [jgraph/drawio-desktop#965]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The Draw.io application starts with an error dialog titled "Error loading file", with message "Not a diagram file (error on line 1 at column 1: Document is empty)".

![image](https://user-images.githubusercontent.com/5346609/164438438-8e0ca34a-680f-41b4-8b0d-bc8a96f806c7.png)

**To Reproduce**
1. Go to application launcher of desktop environment.
2. Click on Draw.io application icon.

**Expected behavior**
Expected to see the "Create New Diagram" / "Open Existing Diagram" options.

![image](https://user-images.githubusercontent.com/5346609/164439973-ad0255f0-86e6-4e17-acde-61ae68cf2498.png)

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version `13.7.3`

**Desktop (please complete the following information):**
 - OS: KDE Neon `5.24` (Linux, `Linux 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`)

**Additional context**
I am *not* opening Draw.io by opening a file with Draw.io associated file extension; just plain opening the application.
During start-up, Draw.io does take about 4 full seconds trying and load something. Load indicator is showing between start-up and the moment it displays the error.

My application shortcut targets `/opt/draw.io/drawio` (or `/opt/draw.io/drawio %U` to be exact).
When I execute `which drawio` from the terminal, it responds with `/usr/bin/drawio`.

If (from the terminal) I execute `/opt/draw.io/drawio`, I get this error.
If (from the terminal) I execute `/usr/bin/drawio`, I get this error.
If (from the terminal) I simply execute `drawio`, everything works as expected.

A somewhat similar issue that I found was https://github.com/jgraph/drawio-desktop/issues/90, but I believe that issue was centered around opening a file with a Draw.io associated file extension.

**Comment by davidjgraph** [comment]
As mentioned in 90, please re-test on latest.

**Comment by apboon** [comment]
Updated to the latest version. Everything works like a breeze 👍🏻
Sorry to have wasted you time. Thank you for the support though.

Draw.io (desktop) is one of my most favorite tools. Thank you for making it :)

**Comment by skain69** [comment]
Hi there, I am having the above error message occur when trying to open a drawio file from both desktop and web apps. other drawio files open without issue , any ideas?

**Comment by iPriyanshuRanjan** [comment]
### Issue
Even after updating to the latest version facing same issue.
Not a diagram file (error on line 1 at column 1: Start tag expected, '<' not found)
How I resolve this issue ?

![image](https://github.com/user-attachments/assets/06f0beae-fe33-4dfe-99dc-6cc42fd46cc2)

**Comment by davidjgraph** [comment]
If the error occurs on an old version, updating to the latest version doesn't help. Please create a new issue rather than extending an existing issue.
