### ISSUE TITLE
Cannot load shape library from URL in configuration file

### ISSUE THREAD

**Issue by RobMcA** [jgraph/drawio-desktop#968]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

A configured library shows access denied when trying to open the shape library using a URL. Importing the downloaded file works fine.

**To Reproduce**
1. Start Draw.io Desktop
2. Click on Extras -> Configuration...
3. Paste the configuration in the additional context section below and click Apply
4. Restart Draw.io
5. On the left pane, click More Shapes...
6. Select Oracle -> OCI Graphics and click Apply
7. On the left pane expand OCI
8. See Access Denied error

**Expected behavior**

When expanding the OCI section the graphics library should be loaded and shown.

**Screenshots**
<img width="699" alt="image" src="https://user-images.githubusercontent.com/12396361/164798490-4ebafa1d-cb81-4f9d-be7e-1ba8a9546c38.png">

<img width="337" alt="image" src="https://user-images.githubusercontent.com/12396361/164799058-360757ab-11a6-4d2f-84bc-fd6651fcef46.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.4.2

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.3.1 

**Additional context**

Here is the configuration.

```
{
  "libraries": [
    {
      "title": {
        "main": "Oracle"
      },
      "entries": [
        {
          "id": "oci-graphics",
          "title": {
            "main": "OCI Graphics"
          },
          "desc": {
            "main": "Graphics for Topologies and Diagrams"
          },
          "libs": [
            {
              "title": {
                "main": "OCI"
              },
              "url": "https://docs.oracle.com/en-us/iaas/Content/Resources/Assets/OCI_Icons.drawio"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by davidjgraph** [comment]
This is correct, the app is designed to be firewalled. We need to improve the error, though.
