### ISSUE TITLE
Cable problem

### ISSUE THREAD

**Issue by alboert** [jgraph/drawio-desktop#969]
There will be a problem with the connection when moving the module, when the connection changes.
1. 开始
image：https://unrealdream-my.sharepoint.com/:i:/g/personal/nanosoft_unrealdream_onmicrosoft_com/Ec2bhiDo2J9EqUmGkkM3FUcBc4eJGYGWrkvxGAgx0OPDzA?e=gzNUjm
2. 第一步
image：https://unrealdream-my.sharepoint.com/:i:/g/personal/nanosoft_unrealdream_onmicrosoft_com/ETbzhslghY5KtxKUI5EJG2cBSL5fZ2RrdM5JD-b19v9XZQ?e=qx8c1B
3. 出错
image：https://unrealdream-my.sharepoint.com/:i:/g/personal/nanosoft_unrealdream_onmicrosoft_com/ETxJriUbAlZOkBw94V9PyEgBCYsw43Wv6gabM6HGKyRsvA?e=o6js83
4. 本应该正确的是这样
image：https://unrealdream-my.sharepoint.com/:i:/g/personal/nanosoft_unrealdream_onmicrosoft_com/EZMpdS-RzNZBt2QNnvYAvoYBpb5ZQ5kWigtAMmQ3n6mSaA?e=RtbfQ7

**Comment by mararad** [comment]
Hi,

If you are not already using, please try with orthogonal waypoint and check if it is working (as shown in the image below marked yellow):

![waypoint](https://user-images.githubusercontent.com/44292306/165075825-963b9c05-f02c-4662-b691-835da692b889.JPG)
