### ISSUE TITLE
vsdx export doesn't keep links

### ISSUE THREAD

**Issue by DuncanMcRae** [jgraph/drawio-desktop#970]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
export as, using the beta vsdx, doesn't keep the attached url given to objects

**To Reproduce**
1. open new process template
2. right click on object and select 'edit link'
3. add url and select 'open in new window'
4. select File>export as>vsdx
5. copy to sharepoint
6. from sharepoint, open or preview in webbrowser.
7. ........no link to url

**Expected behavior**
When clicking the object a new browser tab opens with input url

**Screenshots**
nonie

**draw.io version (In the Help->About menu of the draw.io editor):**
Flatpak diagrams.net 17.4.2

**Desktop (please complete the following information):**
 - Manjaro linux

**Additional context**
none

**Comment by davidjgraph** [comment]
What does step 5 "copy to sharepoint" entail?

**Comment by DuncanMcRae** [comment]
Drag and drop in to a documents folder. Then, if I preview the document there are no links.

Is there a different way to use the raw drawio file in sharepoint rather than exporting as different formats?

**Comment by Titanfinger** [comment]
I have the same Issue with a PDF export, there is no url link to a webpage anymore after export.
Should i open a new issue or is it enough to post it here?

**Comment by davidjgraph** [comment]
PDF export is off-topic for a vsdx export thread. Please open a new thread with environment details and full repoduction steps.
