### ISSUE TITLE
Draw.io Desktop for Windows - Crash after starting the application - 0x80000003

### ISSUE THREAD

**Issue by orbiton21** [jgraph/drawio-desktop#972]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Draw.io Desktop for Windows - Crash after starting the application - 0x80000003

**To Reproduce**
1. Start the application
2. After a few seconds the application crash
3. See error 0x80000003

**Expected behavior**
The application should start normally

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io-17.4.2

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2 build 22000.613

**Additional context**
Add any other context

https://user-images.githubusercontent.com/8853936/165000729-038ac628-3bf5-4ec9-9c9e-76855d555345.mp4

 about the problem here.

**Comment by mikromcz** [comment]
Same here. I just update to the latest "no-installer" version 17.4.2 and it keeps crashing.
deleted whole %appdata%\draw.io folder, still the same.

It can stay on the "create a new diagram" page forever if you close this window and you are at the blank document it is still fine, but when you go to a menu, or just change paper size, it crashes.

[Window Title]
draw.io

[Main Instruction]
draw.io has stopped working

[Content]
A problem caused the program to stop working correctly. Please close the program.

[Close the program]

**Comment by mikromcz** [comment]
17.2.4 works without any issues

**Comment by depiman** [comment]
Same here. Will try the previous version.

Yep, 17.2.4 works perfectly.

**Comment by davidjgraph** [comment]
Note that the version in the windows store is still 17.2.x, https://apps.microsoft.com/store/detail/drawio-diagrams/9MVVSZK43QQW

We hold back on updating that version to see if users get any issue on our binary releases. There have been reports on 17.4.x, so the windows store is better for stability.

**Comment by davidjgraph** [comment]
Could someone try 18.0.1 please?

**Comment by A1714840712** [comment]
win11 安装了几个版本 都是无法启动   我使用虚拟机win10   安装这几个版本都可以正常运行  不知道什么情况

**Comment by mikromcz** [comment]
> Could someone try 18.0.1 please?

18.0.1 works fine for me

**Comment by amitguptagwl** [comment]
I'm facing the same issue with Ubuntu version
