### ISSUE TITLE
feat: AWS icons update 

### ISSUE THREAD

**Issue by sliedig** [jgraph/drawio-desktop#974]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The AWS icons are well behind the current icon shapes are not in line with the current release. 

Would like to see an "AWS20" with the latest icons published in the AWS Architecture centre https://d1.awsstatic.com/webteam/architecture-icons/q1-2022/AWS-Architecture-Icons-Deck_For-Dark-BG_01312022.pptx.5ea04f9d12f6173b0788f26b5b8e6eda8cbe220c.zip

Also I think it would be good to remove AWS 17 and AWS18 from the editor as these are not considered to be valid icons any longer.

**Describe alternatives you've considered**
Powerpoint

**Additional context**
N/A

**Comment by davidjgraph** [comment]
What version of the desktop are you using?

**Comment by sliedig** [comment]
17.4.2

**Comment by davidjgraph** [comment]
Looks like the Q1 2022 set to me. Where exactly did you look?

**Comment by sliedig** [comment]
Looks like it! Thanks! :-)
