### ISSUE TITLE
[MacOS] Keyboard Shortcuts to Zoom In & Out

### ISSUE THREAD

**Issue by OliverPearmain** [jgraph/drawio-desktop#978]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
_This is regarding the Mac app specifically, although it may also apply to other platforms_

I would expect `CMD -` and `CMD +` to control the zoom, as is done in most other applications, however this does not work in drawio-desktop.

From looking at the hints, it looks like the numpad might be required to perform zoom operations via the keyboard. However I don't have a numpad keyboard, and I suspect the large majority of Mac users don't either

![Screenshot 2022-04-28 at 13 50 56](https://user-images.githubusercontent.com/765324/165757836-8bf22718-4992-46ae-95cd-70f544b2366f.png)

Its therefore impossible to zoom in and out using keyboard shortcuts, unless one uses the alt mouse-scroll option but thats massively over-sensitive and unusable in my opinion. 

It would be highly benefical if one could zoom in and out with regular `CMD -` and `CMD +` 

**To Reproduce**
1. Open any diagram in Mac draw.io desktop
2. Press `CMD -`  or `CMD +` 
3. The diagrams zoom level does not change

**Expected behavior**
The diagram should zoom in with `CMD +`  and out with  `CMD -` 

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 17.4.2

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.1

**Additional context**
The draw.io website also does not respond to `CMD -` and `CMD +` shortcuts either.  I expect this is to avoid a clash with the browsers zoom shortcuts (see video below) however in the context of the drawio-desktop application we don't have the browser keyboard shortcuts to contend with so I was wondering if the application layer could just forward `CMD -` / `CMD +` presses to `CMD - (numpad)` / `CMD + (numpad)`

https://user-images.githubusercontent.com/765324/165757874-1ba52806-4c43-4fc5-b3fa-7a44d72c9814.mov

**Comment by baronne** [comment]
Yep, experiencing this issue as well. Can confirm Cmd+ / - does not zoom on Mac OS Monterey

**Comment by ignaciofite** [comment]
I fully agree with the suggestion, the mouse option is highly unusable and no num keypad in most Macs...

**Comment by OliverPearmain** [comment]
Please don't close it, the issue still persists and is still relevant.

**Comment by bbugh** [comment]
I had this problem as well and ended up here from some searching. I was able to "solve" (hack) the problem using BetterTouchTool (and using an Accessibility Keyboard Panel to temporarily simulate the number pad, which you don't need to do).  

I've exported the settings for the draw.io app which you can import into BetterTouchTool if you use it. This maps `Cmd`+`+` to `Cmd`+`Pad +` and `Cmd`+`-` to `Cmd`+`Pad -` in the draw.io app, so that draw.io works like most other Mac tools with zoom.

https://gist.github.com/bbugh/40f852294fcb3029bfd06044bd994538

**Comment by karijkangas** [comment]
Having this same problem. FYI: noticed chancing the zoom level explicitly using "control + 0" works okayish for the zoom in/zoom out purposes from the laptop keyboard.

**Comment by schoblaska** [comment]
I use [awesome-hammerspoon](https://github.com/wyne/awesome-hammerspoon) (shoutout @wyne) to remap `CMD +` and `CMD -` in the draw.io app:

```lua
spoon.AppBindings:bind("draw.io", {
	{ { "cmd" }, "=", { "cmd" }, "pad+" },
})

spoon.AppBindings:bind("draw.io", {
	{ { "cmd" }, "-", { "cmd" }, "pad-" },
})
```

**Comment by datgausaigon** [comment]
Hi all,
Please take a look at this related Issue in drawio-core

https://github.com/jgraph/drawio/discussions/4159

**Comment by datgausaigon** [comment]
> I use [awesome-hammerspoon](https://github.com/wyne/awesome-hammerspoon) (shoutout @wyne) to remap `CMD +` and `CMD -` in the draw.io app:
> 
> ```lua
> spoon.AppBindings:bind("draw.io", {
> 	{ { "cmd" }, "=", { "cmd" }, "pad+" },
> })
> 
> spoon.AppBindings:bind("draw.io", {
> 	{ { "cmd" }, "-", { "cmd" }, "pad-" },
> })
> ```

Hi @schoblaska , 
How to use it? I use macOS 14.5 Sonoma. After downloading it and unzipping it, AppBindings.spoon is a Folder. I cannot run the application.

**Comment by gammalogic** [comment]
@datgausaigon It looks like it's a Lua script, so you would need to have Lua installed on your Mac.

**Comment by datgausaigon** [comment]
@gammalogic Got it, thanks ❤️

**Comment by davidjgraph** [comment]
In 24.6.1.

**Comment by datgausaigon** [comment]
@davidjgraph In 24.6.1 this issue is fixed. But the Zoom In Shortcut (cmd +) not work. Please check. 
Thanks ❤️

**Comment by davidjgraph** [comment]
@datgausaigon you're not the original poster, please open a new issue with full details.

**Comment by datgausaigon** [comment]
@davidjgraph Yep, this is my mistake. I created the issue here: https://github.com/jgraph/drawio-desktop/issues/1792
Thanks ❤️

**Comment by OliverPearmain** [comment]
@davidjgraph hey, original poster here. Thank you for looking into the issue. I just downloaded the latest version 24.6.1 on Mac and whilst `CMD`-`-` now works to zoom out 🎉, `CMD`-`+` doesn't seem to do anything.

**Comment by davidjgraph** [comment]
Yeah, we've got a new issue for that, as posted. It's working on the online version, we're trying to work out why it's not working for cmd + in the desktop version.

**Comment by OliverPearmain** [comment]
Both zoom in and out are working in v24.6.4
🥳  🙇

**Comment by datgausaigon** [comment]
@OliverPearmain Yep, both Web and Desktop app work well. Thanks @davidjgraph ❤️
