### ISSUE TITLE
Mac Quit Doesn't Work

### ISSUE THREAD

**Issue by shawnweeks** [jgraph/drawio-desktop#98]
With the 10.6.7 version you have to quit twice for app to exit.

**Comment by algi** [comment]
I can confirm this. Plus the application is missing other commands like **Hide**, **Hide others**, etc. For me, **Hide** command is quite essential, so I just cloned the repo and I'm trying to find a way how to fix this problem in Electron.

**Comment by davidjgraph** [comment]
I'd wait for the next release, we've some fixes around these issues.

**Comment by algi** [comment]
Yes, Quit and Hide commands are now working correctly. The only minor thing is that I don't see them in the menu, but the functionality is there and that's important. Thank you @davidjgraph !

**Comment by algi** [comment]
Hm, on the other hand, when I run it with `npm run start`, it does hide itself, but then it prevents other application from listening to this command. I'm not sure if there's a issue for that somewhere.

**Comment by ashrafteleb** [comment]
Fixed. Will be available in the next release

**Comment by davidjgraph** [comment]
See https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5
