### ISSUE TITLE
Cannot create new draw.io file from template url

### ISSUE THREAD

**Issue by rharsley-i4pd** [jgraph/drawio-desktop#981]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Cannot create a new file using a template url either using a configuration file or using the "From Template URL" button. Using the configuration file, the list of available templates matches what is in the templates file but when clicking on the template to select the "Create" button is greyed out. This does work in the online version of draw.io but not the desktop version.

**To Reproduce**
Using "From Template URL" button on draw.io desktop
1 - Click File -> New
2 - Select "Create New Diagram"
3 - Click "From Template URL"
4 - Enter URL for template and click create - for testing I've used the example template url https://raw.githubusercontent.com/jgraph/drawio-diagrams/master/templates/business/accd.xml
5 - After clicking the create button it goes back to the list of templates on the machine

Using configuration
1 - Click Extras -> Configuraytion
2 - Set the configuration to 
```
{
  "templateFile": "C:/templates.xml"
}
```

where templates.xml is saved in "C:/" contains
```
<templates>
    <template section="Test"
     title ="Test"
    url="https://raw.githubusercontent.com/jgraph/drawio-diagrams/master/templates/business/accd.xml"
    libs="general"/>
</templates>
```
3 - Click apply and restart Draw.io
4 - On restart click "Create New Diagram"
5 - Find the template to start from listed in template file and click on it
6 - "Create button is greyed out"

**Expected behavior**
When using the "From Template URL" it should make a open a new file with the selected template.
When using the configuration setup, after selecting the template, the "Create" button should be clickable and when clicked on should create a new draw.io file with the new template.

**Screenshots**
![image](https://user-images.githubusercontent.com/81811763/165904075-b3592f7c-921b-484a-b138-2ed4d7094c82.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.4.2
- draw.io version 16.1.2

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I have tried this with the url as file paths on a local machine and to a private github repo but have used the example template repo from jgraph as it is public. I have tried with the templates.xml file saved in different locations and have had the same result. I've also tested it including a preview image which does show up in the template select screen, however it still won't allow me to create the new file from template. 
I am able to insert the template using "Arrange -> Insert -> Template..." and click on the "From Template URL". This doesn't insert into the file but instead creates a new file. However I still can't open from the list of templates in the template browser --- the "Insert" button is greyed out.

**Comment by Oc3anPho3nix** [comment]
While using the installer version it would crash when i was in the templete menu. The Microsoft store version however runs smoothly without any problems. I guess there is a problem in the JS implementation.

**Comment by rharsley-i4pd** [comment]
I get the same behaviour in the windows store version as in the original issue (the create button is greyed out when selecting the template), v16.5.1

**Comment by mararad** [comment]
Could someone attach a video showing all the performed steps and the result, please?

Thanks,

**Comment by rharsley-i4pd** [comment]
https://user-images.githubusercontent.com/81811763/166443132-94e3b42f-fdda-4102-8769-1fdfd93692c7.mp4

Attached is a recording showing the issue
