### ISSUE TITLE
click-to-select object doesn't work randomly

### ISSUE THREAD

**Issue by bogdanv-ntnu** [jgraph/drawio-desktop#982]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Sometimes (randomly) the click-to-select object doesn't work/doesn't select the object, like the object is not even there.
It happens randomly on random objects.
Drag-to-select works after which using the keyboard to move the object and reopening the document fixes the problem. Until  randomly starts again.

**To Reproduce**
Hard to reproduce. It's random.

**Expected behavior**
Clicking an object should select the object

**Screenshots**
![Google Chrome-20220503-1030102_gif](https://user-images.githubusercontent.com/73938209/166425208-a9031f02-c082-4463-ac22-0c22d8c6c777.gif)
Hard to see in the gif with missing cursor, but I am clicking the objects

- draw.io version 17.4.2
- OS: [Windows 10x64]
- Version [21H2]

**Additional context**

**Comment by davidjgraph** [comment]
Please try again with 18.0.1
