### ISSUE TITLE
After opening a non-diagram file, the welcome prompt remains open (Minor)

### ISSUE THREAD

**Issue by aslmx** [jgraph/drawio-desktop#984]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Maybe a minor inconvenience, but i can reproduce it very clearly. After trying to open a file that is not a diagram file and then choosing a proper diagram file to open, the dialog that asks to either create a new diagram or open an existing one does not disappear automatically.

**To Reproduce**
1. Open draw.io
2. Choose "Open existing diagram"
3. Choose a file that is not a diagram, e.g. SVG
4. -> "Error loading file - Not a diagram file" error appears
5. Click okay
6. Choose "Open existing diagram" again
7. This time, choose a proper drawio file
8. -> File opens
9. -> Dialog which offers Creating a new file or opening and existing file does not disappear but stays in foreground. But can be closed with (x) button.

**Expected behavior**
I would expect the dialog that is shown in step 9 to disappear automatically when a file is loaded.

**Screenshots**

If steps are not clear enough, I can provide a video, but I would need to create some non-personal content first. I think the steps to reproduce are clear, let me know if not.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.4.2 (also occurred in 17.2.1, before i updated to check if it was fixed already)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1 XFCE

**Additional context**

**Comment by mararad** [comment]
Reproduced in 18.0.0, Win 10 Pro plus when I click "x" the editor opens again

![repr](https://user-images.githubusercontent.com/44292306/166913823-82c1ca2d-85ed-4304-8834-db7a23721b31.JPG)
![hit x](https://user-images.githubusercontent.com/44292306/166913834-b01ba6b7-598a-4cf3-8b3b-c5991c9cd040.JPG)

Also, when Open draw.io > Choose "Open existing diagram" > Choose drawio file => The dialog Create/Open existing file shows for a second and then disappears
