### ISSUE TITLE
Autosave backup files accumulating on Linux FS

### ISSUE THREAD

**Issue by gskerry** [jgraph/drawio-desktop#989]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Desktop client spams Linux filesystem with auto-save/lock files (e.g. `~$<file>.drawio.bkp`)

**To Reproduce**
Save `<file>.drawio` locally on linux fs.

**Expected behavior**
Remove after explicit save within Drawio; remove on program close; or automatically hide them.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 18.0.1

**Desktop (please complete the following information):**
- Linux Mint 20.1 Cinnamon 4.8.6 (5.4.0-92-generic)

**Comment by davidjgraph** [comment]
This is the autosave draft, it's not windows specific.

**Comment by gskerry** [comment]
Are they supposed to remain after closing the Drawio desktop?

**Comment by davidjgraph** [comment]
Yes, we had some issues with empty files written, so this is used as a backup. Is this is a frequency of write issue because of disk damage?

**Comment by JonathanLindsey** [comment]
I'm on windows and also see this behavior.

It's annoying because the `.drawio.bkp` file gets left behind when draw.io is closed. You end up with 2 files for every document.

I would expect this file to be deleted when draw.io is closed. And while draw.io it is still open the file should either have the hidden attribute or be saved in another location. Maybe saving it in another location would defeat the purpose though.

**Comment by gskerry** [comment]
> Yes, we had some issues with empty files written, so this is used as a backup. Is this is a frequency of write issue because of disk damage?

Don't know if this is to me (OP)? Not sure I fully follow the question... No disk damage that I am aware of. It's a filesystem _hygiene_ issue for me. Nothing mission critical, but would prefer not to have the clutter on the fs.

**Comment by wwdok** [comment]
> I'm on windows and also see this behavior.
> 
> It's annoying because the `.drawio.bkp` file gets left behind when draw.io is closed. You end up with 2 files for every document.
> 
> I would expect this file to be deleted when draw.io is closed. And while draw.io it is still open the file should either have the hidden attribute or be saved in another location. Maybe saving it in another location would defeat the purpose though.

This is also what i want to say ~

**Comment by moongoal** [comment]
Same here. An option to turn this behaviour off would be nice to have. I've never experienced empty files being written but the autosave files accumulating is very annoying.

**Comment by o-l-a-v** [comment]
I store some `.drawio` files in my OneDrive, having `.drawio.bkp` files continously created and synced to the cloud seems unneccessary.

An option to redirect those temp / backup files to a different folder would be great. Like `%LOCALAPPDATA%\Diagrams\Temp` maybe?

**Comment by gian1200** [comment]
Or to delete the `.drawio.bkp` file if the project was saved successfully (or has no unsaved changes)

**Comment by hasan-4** [comment]
setting  Extras->Drafts 0 (0 to disable) solved the problem for me.
